### ISSUE TITLE
[Garou Densetsu 3] Blocage à l'écran de chargement avant le combat

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1000]
Dans la v2.1.5 publique et dans la dernière WIP, avec les 2 noyaux, le jeu se bloque à l'écran de chargement avant le 1er combat.
![image](https://user-images.githubusercontent.com/7624262/113765497-a353f900-971c-11eb-868f-c2322b5bd98d.png)

Au début de l'écran de chargement, le CD est accédé pendant plusieurs secondes, puis cela s'arrête sans que le combat démarre. L'IHM de Kronos continue de répondre. L'animation de l'écran de chargement tourne en boucle. Appuyer sur les boutons de la manette ne change rien.

Ce blocage ne se produisait pas en v1.6.0 et apparaît en WIP du 6 ou 7 mai 2019.

Save state avant l'écran de chargement qui bloque :
[garou_densetsu_3_avant_combat.zip](https://github.com/FCare/Kronos/files/6267048/garou_densetsu_3_avant_combat.zip)

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Kronos 14.10.2021 : idem

**Comment by BenjaminSiskoo** [comment]
Débloque avec les branches test sync / FB access de Janvier et Février 2023
