### ISSUE TITLE
[AIR MANAGEMENT '96] Problème de transparence sur le menu...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1002]
Kronos 2.1.5 
CS

![AIR MANAGEMENT '96](https://user-images.githubusercontent.com/12481242/116103024-807b8b80-a6af-11eb-9b37-89d28f7f003f.PNG)

[airmanagemen96.zip](https://github.com/FCare/Kronos/files/6378039/airmanagemen96.zip)

**Comment by fafling** [comment]
Même problème dans les 2 noyaux, en version publique et dans la dernière WIP.

Sur la console, le NBG1 comporte à la fois des éléments opaques (choix sélectionné du menu) et semi-transparents (choix non sélectionné du menu et fond de la boite de dialogue) qui laissent entrevoir l'arrière-plan (RBG0). Dans Kronos, tout est actuellement opaque.

Dans l'écran debug du VDP2, le NBG1 est un bitmap avec color calculation activée (ratio 16:16) sans special color calculation. Il devrait donc être entièrement semi-transparent, ce qui n'est pas le cas sur la console.
![image](https://user-images.githubusercontent.com/7624262/116485289-259e8b80-a88b-11eb-8c13-02653fecf6cd.png)

L'effet est donc sûrement obtenu par un changement des paramètres de color calculation du NBG1 en cours d'affichage.

L'affichage était correct en v1.6.0. En v1.7.0, le choix sélectionné est à moitié opaque, à moitié semi-transparent. A partir de la v2.0.1, tout est opaque.

Testé avec le CD jap.

Save state :
[air_management_96_menu_titre.zip](https://github.com/FCare/Kronos/files/6395505/air_management_96_menu_titre.zip)

**Comment by BenjaminSiskoo** [comment]
Semble corrigé le 15.12.2021

![image](https://user-images.githubusercontent.com/12481242/146230175-af602be7-72ba-4d36-ad1f-0b8c1f35e921.png)

**Comment by fafling** [comment]
Vu qu'un fix sur la logique d'overlap des fenêtres du VDP2 est fait le même jour, le changement d'activation de la color calculation sur le NBG1 est sans doute obtenu par la color calculation window. Mais comme on n'a aucune info dans l'écran debug du VDP2 sur ce type de fenêtre, ça rend tout analyse sur ce genre de problème très compliquée (Mednafen n'affiche malheureusement rien du registre de fenêtres).

**Comment by BenjaminSiskoo** [comment]
Je peux fermer ou pas @fafling  ?

**Comment by fafling** [comment]
Oui, le bug est corrigé.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 15.12.2021 : keyword (qui servira à retrouver ce jeu par rapport au commentaire de fafling qui pourrait être utile).

**Comment by fafling** [comment]
En fait l'affichage des semi-transparences ne devient correct qu'en WIP du 03/01/2022 suite à la correction de l'inversion de la color calculation window a3f9503779441d4be6a7b536b5325bd13fd376e9 :
![image](https://user-images.githubusercontent.com/7624262/147984022-a057d017-5169-4dff-8ff1-4fabe788cd44.png)
