### ISSUE TITLE
M3u 

### ISSUE THREAD

**Issue by jhdgghost** [FCare/Kronos#1005]
What's the full name of the game (including region) ? Any game

What's your frontend ? (standalone, libretro, ...) ? Attract mode, retroarch

What's your OS ? (windows, linux, OSX, ...) ? W10

What's your hardware ? (CPU, GPU, ...) ? Ryzen 5, HTC 1060

What's the storage type of the game (official cd, burned cd or cd image) ?

Cd image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...) m3u with cue bin

Are you using any setting different from default ? If so, precise

Did this game work previously ? Do you remember when ? Is it happening with other games ? The game works when launch in retroarch

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

Hello, I have a curious issue with m3u. I have multi cds with m3u pointing to cue bin, the files open perfecty in retroarch but when I come from attractmode the m3u is load, you can see the message of retroarch. But the bios appears saying that  the tray is open as if not Disc was present. The config in attract is -L cores/kronos_libreto.dll "[romfilename]"
Ext .cue;.m3u

Best

**Comment by barbudreadmon** [comment]
I don't know anything about attract mode, so if the issue comes from that i won't be able to help.
m3u works with retroarch and kronos for me, but maybe there is a problem with your m3u file ? Could you please share its content ?

**Comment by jhdgghost** [comment]
Hello thanks for the answer here the m3u. The weird thing is retroarch launch the m3u but not attract. But if i use mednafen saturn there is no problem in retroarch or atract with the same m3u file. Atract mode is launching retroarch.exe  -L cores/kronos_libreto.dll Panzer Dragoon Saga (E)(Saturn).m3u so it should work. 

Panzer Dragoon Saga (E)(Saturn).m3u

Panzer Dragoon Saga Disc 1 of 4 (E)(Saturn).cue
Panzer Dragoon Saga Disc 2 of 4 (E)(Saturn).cue
Panzer Dragoon Saga Disc 3 of 4 (E)(Saturn).cue
Panzer Dragoon Saga Disc 4 of 4 (E)(Saturn).cue

**Comment by barbudreadmon** [comment]
> The weird thing is retroarch launch the m3u but not attract

It might be better to ask support from those guys then ? As i said i don't know anything about attract mode.
The m3u seems fine, but your command line should probably look like `retroarch.exe -L cores/kronos_libreto.dll "Panzer Dragoon Saga (E)(Saturn).m3u"` if you are using spaces in m3u filename, the missing "" might be your issue ?
If it's not, let's give this one last try, could you please post your logs ?

**Comment by jhdgghost** [comment]
Ok fixedthe problem was that therom folder finish was "roms/saturn" and should be "roms/saturn/" with the dash there is no poblem.
