### ISSUE TITLE
[Arcade Gears Vol - 2 - Gun Frontier (Japan)] Push start button est coupé et trait noir...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1006]
Kronos 2.1.5 
Mode CS
Paramètres complet dans la vidéo : https://www.youtube.com/watch?v=94BYZLra7OY

Sur la photo, j'ai rassemblé les 2 problèmes : 

![image](https://user-images.githubusercontent.com/12481242/116779963-a327ee80-aa79-11eb-8b77-b96892c2e3df.png)

**Comment by fafling** [comment]
Pour le "push start button" coupé, c'est un bug du jeu. C'est pareil sur la console.

Les lignes noires horizontales apparaissent régulièrement toujours aux mêmes endroits sur le NBG1 qui représente le sol.
Le NBG1 est un bitmap 512x512, son adresse est constante et la coordonnée de scrolling y augmente progressivement de -511 à 0, revient à -511 et ainsi de suite d'après l'écran debug du VDP2 (ce n'est pas la vraie valeur du registre de screen scroll, voir #1007 ).
Le sol est donc dessiné dans le bitmap au fur et a mesure qu'il apparaît à l'écran et que la position de celui-ci remonte dans le bitmap (on peut voir ce dessin progressif dans Yabause 0.9.15 en OpenGL car le scrolling de cette couche ne fonctionne pas).
Les lignes noires semblent apparaître à chaque fois que la coordonnée de scrolling y passe directement de 0 à -511.
Dans le visualiseur de l'écran debug du VDP2, on voit que le dessin du sol est complet, les lignes noires n'y figurent pas.
![image](https://user-images.githubusercontent.com/7624262/116797446-064f6a80-aae6-11eb-8fae-3c7a7664fa77.png)

Le problème existe dans les 2 noyaux dans la dernière WIP et en v2.1.5 publique. Il existe déjà dans Kronos v1.0.0.
Dans Yaba Sanshiro, il est présent jusqu'en v2.7.5 (02/09/2019) et disparaît en v2.8.1 (25/09/2019).

Save state :
[gun_frontier_ligne_noire.zip](https://github.com/FCare/Kronos/files/6410516/gun_frontier_ligne_noire.zip)

Testé avec le CD jap.

**Comment by BenjaminSiskoo** [comment]
En 720p, il manque la bordure blanche en haut du push start button.

![image](https://user-images.githubusercontent.com/12481242/145796844-fcaf26ca-92fc-4885-8295-752505ab86e3.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 13/12/2021
