### ISSUE TITLE
[Baku Baku Animal - Sekai Shiiku Gakari Senshuken (Japan)] Le jeu ne boot plus (Master SH2 error)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1009]
Kronos 2.1.5

Baku Baku Animal ne boot plus.

25	89.424510	6024	kronos.exe	Error: Master SH2 invalid opcode
26	89.424510	6024	kronos.exe	
27	89.424510	6024	kronos.exe	R0 =  00000003	R12 =  00000000
28	89.424510	6024	kronos.exe	R1 =  00000802	R13 =  00000000
29	89.424510	6024	kronos.exe	R2 =  00000000	R14 =  00000000
30	89.424510	6024	kronos.exe	R3 =  06086AC4	R15 =  06001FB0
31	89.424510	6024	kronos.exe	R4 =  00000802	SR =   00000000
32	89.424510	6024	kronos.exe	R5 =  25FE00A0	GBR =  060B4578
33	89.424510	6024	kronos.exe	R6 =  060107CE	VBR =  06000000
34	89.424510	6024	kronos.exe	R7 =  060B5FD8	MACH = 00000000
35	89.424510	6024	kronos.exe	R8 =  00000000	MACL = FFFFFFFF
36	89.424510	6024	kronos.exe	R9 =  00000000	PR =   FFFFE1FC
37	89.424510	6024	kronos.exe	R10 = 00000000	PC =   FFFFE1FC
38	89.424510	6024	kronos.exe	R11 = 00000000

**Comment by fafling** [comment]
Le problème apparaît en WIP du 16/03/2020 (dans celle que j'ai récupéré à 19h42).

**Comment by fafling** [comment]
Le blocage se produit quand on appuie sur start pendant l'intro, ou à la fin de celle-ci si on ne fait rien.
Au moment du blocage l'affichage est désactivé (plus rien dans l'écran debug du VDP2).
Testé avec le CD d'origine US qui a le même problème que la version japonaise.

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

Corrigé
