### ISSUE TITLE
[Batsugun] Artefacts après la disparition du logo Banpresto (NBG0)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1011]
Kronos 2.1.5 Wip du 25.02.2021
CS et OpenGl

En décochant la couche NBG0, ca disparait.

Le détail dans la description de la vidéo.

https://youtu.be/2IL3hTetwgM

**Comment by fafling** [comment]
Dans Kronos, il y a un 1er flash très court du logo Banpresto qui ne se produit pas sur la console. Juste avant, on voit le NBG0 activé pendant plusieurs frames, mais l'écran est noir :
![image](https://user-images.githubusercontent.com/7624262/117516210-ca5e4e80-af98-11eb-9165-ca41ec940c04.png)
Au moment ou le logo apparaît très brièvement, on ne voit aucune couche activée sur le VDP2 :
![image](https://user-images.githubusercontent.com/7624262/117515550-e3660000-af96-11eb-9eed-ff39c0ec3498.png)
Peut-être dû à un décalage d'une frame dans Kronos sur la prise en compte des registres du VDP2 par rapport à ce que fait la console, car le jeu semble faire disparaître le NBG0 au moment où il charge le logo en vram. Ou bien c'est encore l'absence d'émulation du registre de cycle pattern...

Le logo correct apparaît ensuite après un flash blanc. Ce flash est un color offset progressif vers le blanc (canaux à +255) sur le back screen sans autre couche VDP2 active, puis après saturation du blanc le NBG0 est activé avec ce même color offset blanc, qui revient ensuite à 0 pour faire apparaître le logo.

Le logo disparaît ensuite avec un color offset progressif vers le noir (canaux à -255). Sur la console, il ne réapparaît pas, elle affiche "Toaplan legendary series" :
![image](https://user-images.githubusercontent.com/7624262/117517024-114d4380-af9b-11eb-92dd-0d11d6df4ab6.png)
Sur Kronos, le logo réapparaît partiellement. Quand c'est le cas, le color offset remonte vers 0 et le NBG0 est toujours actif (si on le désactive l'écran est noir) :
![image](https://user-images.githubusercontent.com/7624262/117515996-1ceb3b00-af98-11eb-8914-2cc8253b2d7b.png)
Il semble donc que ce soit le graphisme du NBG0 affiché à ce moment qui n'est pas le bon.

Affichage correct : [https://www.youtube.com/watch?v=m6evnbPqvN4](https://www.youtube.com/watch?v=m6evnbPqvN4)

Testé avec le CD jap.

**Comment by fafling** [comment]
L'affichage du logo et de "Toaplan legendary series" était correct dans Yabause 0.9.14.

Le 1er flash incorrect du logo apparaît dans Kronos v1.4.0. C'est associé à l'apparition d'une saute incorrecte très brève en fin d'animation du bios, lors du color offset vers le blanc qui fait apparaître le logo Sega Saturn (ci-dessous dans la dernière WIP, tout l'écran devrait être blanc) :
![image](https://user-images.githubusercontent.com/7624262/117518232-3ba10000-af9f-11eb-9c3d-470a4f5fb5d0.png)

Le message "Toaplan legendary series" était corrompu dans Kronos v1.0.0 (ci-dessous en v1.4.5). Il devient le logo Banpresto partiel en v1.5.0.
![image](https://user-images.githubusercontent.com/7624262/117517793-74d87080-af9d-11eb-8e65-bf6a155c7753.png)

**Comment by fafling** [comment]
L'affichage est correct dans les 2 noyaux en WIP du 15/12/2021.

**Comment by BenjaminSiskoo** [comment]
Corrigé avec Kronos 2.2.0 du 15.12.2021
