### ISSUE TITLE
[Résolution 480p/720p] Artefacts...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1013]
En utilisant l'une ou l'autre résolution, il y a des artefacts comme sur la cape de dracula (fin de vidéo) Trait verticaux.

https://www.youtube.com/watch?v=wAVN_Gu_tq8

**Comment by BenjaminSiskoo** [comment]
Sur le I de Station trait vertical

![image](https://user-images.githubusercontent.com/12481242/117014423-125b4800-acf1-11eb-8600-296a8415cd12.png)

**Comment by FCare** [comment]
Le STAT commence en 30 et fait 136 pixels de large. Le IONS commence a 160 et fait 136 de large.
la partie transparente de IONs ecrase la partie de STAT....

**Comment by FCare** [comment]
Non en fait le STAT n'est pas affiché jusqu'au bout

**Comment by BenjaminSiskoo** [comment]
Il y a 2 problèmes.

En 720p : sur la cape de Dracula, il y a un trait vertical (sous le cou et au dessus de l'estomac.

![image](https://user-images.githubusercontent.com/12481242/120282500-75bda300-c2ba-11eb-9967-fd0809bb4580.png)

En 1080p : il y a des triats verticaux et horizontaux.

![image](https://user-images.githubusercontent.com/12481242/120282592-8cfc9080-c2ba-11eb-8f88-8326666aee34.png)

**Comment by BenjaminSiskoo** [comment]
Je ferme car c'est corrigé avec la version du 20.08.2021
