### ISSUE TITLE
[Black Dawn (Europe)] Bug très étrange...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1018]
Kronos 2.1.5 Wip du 05.05.2021
Mode CS
Options vidéo par défaut

A certains moments, l'affichage est correct mais rarement.

![bob](https://user-images.githubusercontent.com/12481242/117282181-bd404300-ae64-11eb-91cb-58d56ae88de0.PNG)

Sauvegarde d'état sur la fenêtre avec le problème

[blackdown.zip](https://github.com/FCare/Kronos/files/6433686/blackdown.zip)

**Comment by fafling** [comment]
C'est pas un bug de Kronos, il y a le même problème sur la console (testé avec la version US).

**Comment by BenjaminSiskoo** [comment]
Ok je ferme merci
