### ISSUE TITLE
RetroBit Saturn Controller not recognized 

### ISSUE THREAD

**Issue by saturn32Beats** [FCare/Kronos#1020]
Bonjour! Im sorry I cant speak french properly.

Well I wanted to try Kronos emulator and its last version 2.1.5. but I cant set up my saturn controller. Other controllers as well as keyboard and mouse are recognized as input but the saturn one gives no input. The same result with version 2.1.1.

Hopefully this issue has some kind of fix. Thanks for developing a Saturn emulator.

Cheers :)

**Comment by barbudreadmon** [comment]
iirc, Kronos isn't compatible with xinput controllers, maybe that controller is one of those ?

Edit : i just read that switching between D-input and Xinput on that controller is done by holding Start + B for five seconds (at least on second model), try D-input.

**Comment by FCare** [comment]
Look at the documentation of the controler, there is different modes witht those controlers. You have to switch the mode of the controler. Some of those modes are not recognized on Linux or Windows.
I have some of Retrobit controlers. Please add the model of the controler. "Saturn controler" is ambiguous.

**Comment by saturn32Beats** [comment]
Thanks guys for your inputs. I have been looking in the box and the instructions. There is no model number or whatsoever, Sega Saturn Slate Grey Controller. I ordered it here https://www.amazon.de/gp/product/B07H3QWY1C/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1.

I have also tried changing between D and X-input but either is not working or the emulator is not recognizing it. 

This controller is recognized in Windows 10 without troubles. I can play all the games I have in my PC with it, also SSF and yaba sanshiro. Since my snes controller is recognized by Kronos, I believe the reason for this behaviour with the retrobit one could be that my saturn controller is not set up as the default controller in windows but the SNES is the primary controller. Maybe you could do some tests about this.

**Comment by BenjaminSiskoo** [comment]
Should be ok with kronos 2.2.0. If not I'll open this BR.
