### ISSUE TITLE
[College Slam (USA] Artefacts sur les personnages

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1025]
Kronos 2.1.5 Wip du 05.05.2021
Mode CS

![image](https://user-images.githubusercontent.com/12481242/118356671-b0af9f00-b576-11eb-98d9-61417a1e236b.png)

https://youtu.be/5qNH1KDSnn8

**Comment by fafling** [comment]
Problème similaire aux corruptions de sprites de Earthworm Jim 2 (#473).

**Comment by BenjaminSiskoo** [comment]
En partie corrigé, il reste des artefacts sur les joueurs, mais la bouillie de pixel sur la tête est corrigé.

**Comment by BenjaminSiskoo** [comment]
Kronos 14.10.2021

Toujours cassé, c'était corrigé avec les timings.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.5.0
Cs

Semble corrigé
