### ISSUE TITLE
[Chou Jikuu Yousai Macross - Ai Oboete Imasu ka (Japan)] Fenêtre de dialogue décalé...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1026]
Kronos 2.1.5 Wip
Mode CS

![image](https://user-images.githubusercontent.com/12481242/118357670-a512a700-b57b-11eb-9945-5efe9d549e8b.png)

**Comment by FCare** [comment]
Meme probleme que https://github.com/FCare/Kronos/issues/79
Il y a un decalage de 8 pixels du NBG3 (dans les deux cas). ca vient de la fonction Vdp2DrawMapTest

**Comment by FCare** [comment]
probleme de cycle pattern....

**Comment by BenjaminSiskoo** [comment]
Corrigé le 19 Mai 2021
