### ISSUE TITLE
Wachenröder - Dailouge window during battle bug

### ISSUE THREAD

**Issue by FuxorLuck** [FCare/Kronos#1027]
What's the full name of the game (including region) ?

Wachenröder (Japan)

What's your frontend ? (standalone, libretro, ...) ?

Both standalone and librerto

What's your OS ? (windows, linux, OSX, ...) ?

Windows

What's your hardware ? (CPU, GPU, ...) ?

I7 -8700
Gtx 1060

What's the storage type of the game (official cd, burned cd or cd image) ?

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)
CHD

Are you using any setting different from default? If so, precise
No

Did this game work previously ? Do you remember when ? Is it happening with other games ?
No

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

During battles, if a dialogue screen will appear the entire screen will squeeze into 1 line of pixels except for the dialogue screen 

How it looks like

![Wachenröder Bug](https://user-images.githubusercontent.com/55870574/118402493-c2766c80-b672-11eb-8457-2498daeb6b8b.jpg)

How it supposed to look 

![Wachenröder on saturn](https://user-images.githubusercontent.com/55870574/118402495-c6a28a00-b672-11eb-8ade-d78ba6eb7d07.jpg)

How to reproduce the issue

Start the first battle in the game

**Comment by FCare** [comment]
Can you add a savestate to your ticket?

**Comment by FuxorLuck** [comment]
@FCare 

https://easyupload.io/30p9t0

**Comment by BenjaminSiskoo** [comment]
[GS-9183_000.zip](https://github.com/FCare/Kronos/files/6991801/GS-9183_000.zip)

here the savestate

**Comment by fafling** [comment]
Almost fixed in 21st december WIP.

In both video cores, there remains a column of pixels in the middle of the sprite layer that is incorrectly transparent to the VDP2 background (you see the blue gradient of the back screen though it) :
![image](https://user-images.githubusercontent.com/7624262/147570035-aebb8487-3b9d-46b6-8c9d-70f54388cb0e.png)

It's likely a remaining window issue. In VDP2 debug screen, all layers use a combination of 2 line windows (the improvement probably comes from the fix of incorrect windows combination bug #986 ) :
![image](https://user-images.githubusercontent.com/7624262/147570386-9d414248-1358-421b-8120-4eeff2e5d2ac.png)

Tested with original CD.

Save state made with that WIP (incompatible with Kronos public versions) :
[Wachenroder_1er_combat_20211228.zip](https://github.com/FCare/Kronos/files/7784819/Wachenroder_1er_combat_20211228.zip)

**Comment by fafling** [comment]
However, when the combat starts after the dialog, the sprites disappear entirely !
![image](https://user-images.githubusercontent.com/7624262/147570722-3945652c-d61a-40bc-a772-b145634c1512.png)

**Comment by fafling** [comment]
Sprites reappear when pressing start, and disappear again when pressing B.
![image](https://user-images.githubusercontent.com/7624262/147570929-f7a00787-7dde-4546-84f3-8fd106a293f8.png)

**Comment by fafling** [comment]
There's another problem of disappearing graphics on dialogs visible at the start of the game in both video cores. The dialog frame is missing on layer NBG3.
![image](https://user-images.githubusercontent.com/7624262/147612011-c7a446d5-6349-46b7-b38b-e28eb2a1de4c.png)

Correct display in public v2.2.0 :
![image](https://user-images.githubusercontent.com/7624262/147611460-6ed473cf-193d-4802-88a5-7af6513f6b10.png)

Probably also a window problem as it appears with the fix on windows combination in 15th december 3rd WIP (likely with 47d461deb4bd89d31c2342becef39d63ba73bc7f ), and the VDP2 debug screen shows a combination of line windows on NBG3 :
![image](https://user-images.githubusercontent.com/7624262/147611916-df7c3f8a-bfdd-4132-8052-989fee32a4c3.png)

The missing graphics is visible in the viewer :
![image](https://user-images.githubusercontent.com/7624262/147611999-9cde9fb4-f96c-4e5c-b7b3-89abe11bc106.png)

No need of save state, it's right at the start of the game.

**Comment by FCare** [comment]
les valeurs de la W0 sont 0 et 0 a toutes les lignes.

**Comment by fafling** [comment]
In the last WIP, the missing dialog frames and the disappearance of the sprites are fixed.
However, during dialog at the beginning of combat, the transparent column in the middle of sprites is still present.
@FCare Can you reopen ?

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 18.01.2022
Mode Cs

Pas de soucis avec la verison du 17.01.2022

![image](https://user-images.githubusercontent.com/12481242/150019162-891ba5fe-19fe-4b3e-907e-8ed908237429.png)

savestate : 
[GS-9183_000.zip](https://github.com/FCare/Kronos/files/7892401/GS-9183_000.zip)
