### ISSUE TITLE
[Daikoukai Jidai Gaiden (Japan)] Freeze aléatoire et problème RGB0...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1031]
Kronos 2.1.5 Wip du 05.05.2021
Mode CS

En décochant la couche RGB0, l'arrière plan est affiché. Il y a des freeze aléatoires sur ce jeu.

![image](https://user-images.githubusercontent.com/12481242/118795922-617dad00-b89b-11eb-9fac-f020d6042ddd.png)

https://youtu.be/n-khK1DHis0

Savestate : 
[T-7657G_001.zip](https://github.com/FCare/Kronos/files/6507802/T-7657G_001.zip)

**Comment by fafling** [comment]
Pour l'affichage incorrect du RBG0, c'est un doublon de #670 .
