### ISSUE TITLE
[Daikoukai Jidai Gaiden (Japan)] Paramètres non géré par la savestate ?

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1032]
Kronos 2.1.5 Wip
Mode CS

Quand j'ai fais la savestate on voyait les dialogues et les personnages, seul le fond n'était pas affichés (problème de RGB0). En relançant la savestate, je ne vois plus les personnages et les dialogues. Paramètres non géré à cause du RGBo ??

Savestate : 
[T-7657G_001.zip](https://github.com/FCare/Kronos/files/6507818/T-7657G_001.zip)

**Comment by fafling** [comment]
Il y a des incompatibilités dans les dernières WIP de Kronos avec les save states créées sur des versions ou WIP précédentes.
La save state que j'ai créée sur ce jeu au mois de janvier sur une des premières WIP de la v2.1.5 ne fonctionne plus avec la dernière WIP.

**Comment by BenjaminSiskoo** [comment]
J'utilise pas d'ancienne savestate, le test à été fait avec la dernière WIp et la correction des savestates. 

Un autre jeu a des soucis de savestate : Doukyuusei - if (Japan) 

Savestate : 

[T-20102G_001.zip](https://github.com/FCare/Kronos/files/6553642/T-20102G_001.zip)

**Comment by FCare** [comment]
Les incompatibilités, ca a ete reglé. Ca n'apparait plus. Mais pour celle qui ne passe aps, je me souviens qu'avec un editeur hexa, j'arrivais a les faire passer...
Faudrait que je tente de charger avec des parametres differents quand ca fail...

**Comment by BenjaminSiskoo** [comment]
Ca semble ok Kronos 2.2.0 16.12.2021
