### ISSUE TITLE
[Darius II (Europe)] Filtre Deinterlacing Bob...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1034]
Kronos 2.1.5 20.50.2021
Mode CS

Le texte est tronqué

![image](https://user-images.githubusercontent.com/12481242/118959505-addff000-b962-11eb-8625-33648083c201.png)

**Comment by FCare** [comment]
Artefact du deinterlacing. le desentrelacement bob repete une ligne sur deux, ca deforme le texte... Vire le deinterlacing.

**Comment by BenjaminSiskoo** [comment]
C'est un bug à corriger ou pas, sinon je ferme le BR !!!

**Comment by FCare** [comment]
ce n'est pas corrigeable. Le desentrelacement genere des artefacts. Ferme
le BR


Le jeu. 20 mai 2021 à 12:08, Benjamin Siskoo ***@***.***> a
écrit :
