### ISSUE TITLE
[Bishoujo Senshi Sailor Moon SuperS - Various Emotion (Japan)] Artefacts sur les personnages...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1035]
Kronos 2.1.5 du 21.05.2021
Mode CS

Ce type de  bug est présent dans plusieurs jeux

![bishoujou](https://user-images.githubusercontent.com/12481242/119156811-e233d900-ba54-11eb-872c-06698f30e13f.PNG)

Savestate : 
[T-15701G_001.zip](https://github.com/FCare/Kronos/files/6523341/T-15701G_001.zip)

**Comment by fafling** [comment]
Encore similaire à #473 .

**Comment by fafling** [comment]
C'est fixé chez moi en WIP du 04/02/2022 dans les 2 noyaux.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 04.02.2021
