### ISSUE TITLE
Prise en compte des CHD de Mame

### ISSUE THREAD

**Issue by newton9278** [FCare/Kronos#104]
Bonjour,
Serait-il possible que l'émulateur puisse lire les CHD Saturn de Mame dans une prochaine version ?
Bonne continuation

**Comment by FCare** [comment]
Pourquoi pas, le format semble bien documenté. Actuellement je travaille avec des redump de saturn car ils contiennent egalement les pistes de musiques qui manquent dans beaucoup d'iso d'emuparadise par exemple. Pouvez-vous me dire ou trouver des CHD Saturn?

**Comment by newton9278** [comment]
Bonjour,

Voici pour les infos :

https://archive.org/details/MESS_0.149_CHD_saturn_1

https://archive.org/details/MESS_0.149_CHD_saturn_2

https://archive.org/details/MESS_0.149_CHD_saturn_3

Il y a pleins d’autres CHD pour les différentes consoles.
Bon courage pour l’avancement de l’émulateur :o)

Bien cordialement

De : FCare [mailto:notifications@github.com]
Envoyé : jeudi 22 février 2018 20:46
À : FCare/yabause <yabause@noreply.github.com>
Cc : newton9278 <pat.hoche@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [FCare/yabause] Prise en compte des CHD de Mame (#104)


Pourquoi pas, le format semble bien documenté. Actuellement je travaille avec des redump de saturn car ils contiennent egalement les pistes de musiques qui manquent dans beaucoup d'iso d'emuparadise par exemple. Pouvez-vous me dire ou trouver des CHD Saturn?

**Comment by barbudreadmon** [comment]
Support ajouté
