### ISSUE TITLE
[Derby Analyst (Japan)] Problème avec la transparence sur le menu...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1041]
Kronos 2.1.5 du 21.05.2021
Mode CS

On ne voit pas l'option du menu qu'on choisit.

![image](https://user-images.githubusercontent.com/12481242/119256525-62774d00-bbc1-11eb-99a2-3abf21e3ea90.png)

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 16.12.2021

Savestate : 
[T-20505G_000.zip](https://github.com/FCare/Kronos/files/7727352/T-20505G_000.zip)

**Comment by FCare** [comment]
usage of MSB set

**Comment by FCare** [comment]
NBG0 mode
8-bit(256 colors)
Bitmap(1024x512)
Bitmap Address = 0
Bitmap Palette Address = 30
Screen Scroll x = 0, y = 0
Coordinate Increments x = 1,000000, y = 1,000000
Gradation Calculation Disabled
Window disabled whole screen
Color Ram Address Offset = 0
Priority = 2
Line Color Screen insertion = 0
Color Offset A Enabled
R = 0, G = 0, B = 0
Special Color Calculation 0


RAMCTL 0x384
Border Color Mode = Back screen
Display Resolution = 640 x 240(NTSC)
Interlace Mode = Double-Density Interlace
Latches HV counter when external latch flag is read
During Even Field
H Counter = 0
V Counter = 242

Line Color Screen Stuff
-----------------------
Mode = Single color
Address = 05E00000

Back Screen Stuff
-----------------
Mode = Single color
Address = 05E7FFFE

Sprite Stuff
------------
Sprite Type = C
VDP1 Framebuffer Data Format = Palette only
Window disabled whole screen
Color RAM Offset = 0
Color RAM Mode = 0
Priority 0 = 4
Priority 1 = 4
Priority 2 = 4
Priority 3 = 4
Priority 4 = 4
Priority 5 = 4
Priority 6 = 4
Priority 7 = 4

**Comment by fafling** [comment]
Les options non sélectionnées font l'objet d'une commande de dessin rectangulaire en mode "MSB on".
![image](https://user-images.githubusercontent.com/7624262/149855807-52aa3794-2cc4-4369-b0ef-d076f38ae8b3.png)

Sur un framebuffer 8 bits, cela met à 1 le MSB d'un pixel sur 2, toujours sur la même colonne. Ces pixels correspondent probablement aux 8 bits de poids forts des pixels d'un framebuffer 16 bits.

Avec un types de sprites 8 bits, les effets de MSB du VDP2 (MSB shadow ou sprite window) ne s'appliquent pas. Tous les bits des types de sprites 8 bits servent à l'adresse de color ram. Le MSB peut en plus avoir une valeur de numéro de registre de priorité ou de color calculation.

Ici, tous les pixels des sprites sont transparents initialement puisqu'on voit le NBG0 sur tout l'écran alors qu'il a une priorité plus faible à 2.

Le type de sprite est C, le MSB (bit 7) a une valeur de numéro de registre de priorité, mais comme toutes les priorités du des sprites sont les mêmes (4), la mise à 1 du MSB rend les pixels concernés opaques, puisque leur valeur passe de x00 à x80, avec une priorité à 4.
