### ISSUE TITLE
[Die Hard Arcade (Europe)] Petits points sombre...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1044]
Kronos 2.1.5 du 21.05.2021
Mode CS

On peut voir des petits sombres

![image](https://user-images.githubusercontent.com/12481242/119332890-7f775300-bc89-11eb-9706-318cc217cd00.png)

savestate : 

[MK-81057_001.zip](https://github.com/FCare/Kronos/files/6531547/MK-81057_001.zip)

Vidéo : 
https://youtu.be/gAuUDQ3XZyQ

**Comment by fafling** [comment]
Les points sont aussi sur la console : [https://youtu.be/yKI4CyHyGw4?t=905](https://youtu.be/yKI4CyHyGw4?t=905)
