### ISSUE TITLE
[Doukyuusei - if (Japan)] Artefacts dans les dialogues...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1046]
Kronos 2.1.5 21.05.2021
Mode CS

![image](https://user-images.githubusercontent.com/12481242/119819965-45a88580-bef1-11eb-9539-43387877c712.png)

savestate : 
[T-20102G_000.zip](https://github.com/FCare/Kronos/files/6553659/T-20102G_000.zip)

**Comment by fafling** [comment]
Se produit uniquement en noyau CS, dans la dernière WIP et en v2.1.5 publique.
Visible sur le 7ème écran de texte in-game quand il termine son défilement vers le haut.

Affichage correct en OpenGL :
![image](https://user-images.githubusercontent.com/7624262/120072942-75dd5900-c096-11eb-9d24-953362454f6c.png)

On voit en bas de l'écran le haut de caractères japonais (normal sprite avec y à 218) qui devraient être entièrement tronqués par le user clipping qui les précède (ligne du bas à 217) :
![image](https://user-images.githubusercontent.com/7624262/120073008-cbb20100-c096-11eb-826d-a027c05b26a8.png)
![image](https://user-images.githubusercontent.com/7624262/120073030-e4bab200-c096-11eb-9e2d-813e224bc9ca.png)

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 15.12.2021

**Comment by fafling** [comment]
@BenjaminSiskoo Tu peux rouvrir, c'est de retour...
Probablement lié aux multiples problèmes de scaling de sprites en CS, voir #1126 .

**Comment by fafling** [comment]
Ce n'est pas un problème d'upscale mais de user clipping incorrect en CS. Sans doute lié à #723 .

**Comment by BenjaminSiskoo** [comment]
Corrigé le 14.01.2022 (10h20)
