### ISSUE TITLE
[DX Nippon Tokkyuu Ryokou Game - Let's Travel in Japan (Japan)] Transparence manquante sur les dialogues...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1047]
Kronos 2.1.5 du 21.05.2021
Mode CS

![image](https://user-images.githubusercontent.com/12481242/120098670-8d205300-c137-11eb-8b7b-bbb87eb64fb9.png)

**Comment by fafling** [comment]
Je ne reproduis le problème dans les 2 noyaux qu'avec le mesh mode improved.
En mesh mode original, l'affichage est correct.
Même situation dans la dernière WIP et en v2.1.5 publique.
C'est peut-être un reste du problème #223 car je ne trouve pas de version depuis où la semi-transparence soit visible en mesh mode improved.

Pour rappel, commande de dessin de la trame avec le color mode en v1.7.0 (l'affichage du color mode a été supprimé dans les versions suivantes car il prêtait à confusion) :
![image](https://user-images.githubusercontent.com/7624262/120113094-36d40400-c179-11eb-9fde-3d3dc8d02d74.png)

La trame est dessinée par le VDP1 avec un polygone qui utilise le noir RGB comme couleur, mais avec un color mode 8bpp (color mode 4). D'après le mode d'emploi du VDP1, les commandes non texturées sont censées utiliser le color mode 0 quelque soit le type de la couleur dessinée. Cela n'empêche pas la console de dessiner correctement ce polygone.

De manière générale, il semble que le VDP1 ne fait rien du color mode sur les commandes non texturées car plusieurs jeux ont spécifié un color mode différent de 0 pour ce genre de commande.

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
@fafling on est bon ou pas ?

**Comment by fafling** [comment]
En WIP du 16/12, c'est correct en CS, mais pas en OpenGL où la trame est toujours complètement transparente en mesh mode improved..

**Comment by fafling** [comment]
En WIP du 07/01/2022, c'est correct dans les 2 noyaux avec et sans mesh mode improved.
