### ISSUE TITLE
Galaxy Fight will randomly crash when going through menus or fights. All versions.

### ISSUE THREAD

**Issue by Eilde** [FCare/Kronos#1051]
What's the full name of the game (including region) ? Galaxy Fight. Tested USA and JP.

What's your frontend ? (standalone, libretro, ...) ? Standalone

What's your OS ? (windows, linux, OSX, ...) ? Windows 10

What's your hardware ? (CPU, GPU, ...) ?  CPU Ryzen 7 1800x. GPU - AMD Radeon RX 5700 XT

What's the storage type of the game (official cd, burned cd or cd image) ? Official CD and CD image. Same with both.

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...) Tried with ISO and cue/bin

Are you using any setting different from default ? If so, precise. I have tried default settings and changed settings to troubleshoot it and figure out if any setting would mitigate the random crash.

Did this game work previously ? Do you remember when ? Is it happening with other games ? Only this game. Haven't tried it previously but I did have an older version of Kronos installed which it was not working with. Updated and still not working. This is the only game I have that does this problem.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this
There is no error message or anything. What happens is, the game starts normally. You get to the title screen, then you can pick options and what not. Sometimes it will randomly crash just going through menus, other times it will work through menus. Playing in VS a few matches, sometimes it will crash instantly after picking characters. Sometimes after a match, sometimes after several matches. This "crash" is a black screen where it no longer responds. Only option is to reset the game or restart the emulator. Sometimes reset won't even work when the black screen happens. "Black screen on the game, not the computer itself." The longest I was able to get the game working while going through matches was 5. No setting seems to mitigate it. Is completely random. However, my physical copy of the game instantly crashes while my friend's cue/bin is completely random when it crashes. I then later downloaded the JP version which is cue/bin, a ISO of USA and an ISO of JP and they all kept randomly crashing. I made my own ISO from my physical copy of the game which would randomly crash as well. Perhaps the correct word is "hang"? Basically, I went through my own copy and making my own ISO of it along with trying other isos and bin/cues to which all have had random crashes. No other game I play on the emulator does this so far that I know of which is roughly around 40+ games.

**Comment by BenjaminSiskoo** [comment]
Master SH2 invalid opcode : 

Tested with the real bios / built in bios

![image](https://user-images.githubusercontent.com/12481242/120795753-2a192c80-c53a-11eb-8934-858b7af2d781.png)
