### ISSUE TITLE
[Fishing Koushien II (Japan)] Freeze après le bios...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1058]
Kronos Wip 01.06.2021

Le jeu freeze Kronos après le bios.

**Comment by fafling** [comment]
Toujours présent dans la dernière WIP, dans les 2 noyaux video.
DebugView n'est pas bloqué pendant le freeze et aucun message n'apparaît quand on kille Kronos.
Le jeu démarrait jusqu'en v1.4.5. Le freeze apparaît en v1.5.0.
Pas de changement lors des essais de timings de fin août 2021.
Paramétrer une 2ème manette ne change rien.
Pas de fuite mémoire lors du freeze, l'utilisation du CPU augmente et celle du GPU tombe à 0.

Une bonne nouvelle : le jeu démarre en bios émulé !

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

Corrigé
