### ISSUE TITLE
[Funky Fantasy (Japan)] Gros ralentissement sur la vidéo...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1061]
Kronos Wip 01.06.2021
Mode Cs

Gros ralentissement après avoir appuyé sur press start screen.

**Comment by FCare** [comment]
Dans ce jeu la, la liste des commandes VDP1 correspond a toujours dessiner la meme commande...

**Comment by BenjaminSiskoo** [comment]
Funky Fantasy on est presque bon, ils restent des micro freeze (au début de la vidéo quand la planète tourne sur elle même).

**Comment by BenjaminSiskoo** [comment]
Corrigé le 9.01.2023
