### ISSUE TITLE
4MB games doesn't run, ever

### ISSUE THREAD

**Issue by threenator** [FCare/Kronos#1062]
What's the full name of the game (including region) ? Street Fighter Zero 3, D&D, X-Men Vs. Street Fighter

What's your frontend ? (standalone, libretro, ...) ? Standalone

What's your OS ? (windows, linux, OSX, ...) ? Windows 10

What's your hardware ? (CPU, GPU, ...) ? intel i7-4970k

What's the storage type of the game (official cd, burned cd or cd image) ? CD Image and Official CD

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...) .cue/bin

Are you using any setting different from default ? If so, precise No

Did this game work previously ? Do you remember when ? Is it happening with other games ? No / 

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

I'm trying to run 4MB games and none of them are working, even with 32 Dram selected. I tried redump ISOs and official media. The options for 4MB Cartridge aren't working too.

**Comment by BenjaminSiskoo** [comment]
Hello

Try with a blank kronos.ini and setting up again.
