### ISSUE TITLE
[Gekirindan (Japan)] L'écran saute...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1066]
Kronos Wip 01.06.2021
Mode CS

https://youtu.be/pqtGPs13aFY

**Comment by FCare** [comment]
Il saute a quelle minute du jeu? Sur que c'est pas le cas sur la console?

**Comment by BenjaminSiskoo** [comment]
La taille horizontale est plus petit de plusieurs pixels. . De plus en bas à gauche de l'écran on peut voir que le petit passe sous l'arrière plan.

![image](https://user-images.githubusercontent.com/12481242/127462000-5bd62987-e0b5-4989-844c-88800766b8a1.png)

**Comment by BenjaminSiskoo** [comment]
Ca me semble ok grâce au patch Batsugun (je pense). Corrigé le 15.12.2021
