### ISSUE TITLE
[Akumajou Dracula X] Bande jaune en haut de l'écran (CS/OpenGL)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1072]
Kronos Wip 01.06.2021
Mode CS

A 9'25 : une barre jaune apparaît en haut de l'écran d'une hauteur de plusieurs pixels.
On peut voir cette barre mais de couleur bleu sur toute la partie du gameplay, ça bascule en jaune sur la fin de vidéo quand on descend les escaliers.

https://youtu.be/tOYrgpxwljI

La savestate : 

[T-9527G_000.zip](https://github.com/FCare/Kronos/files/6796739/T-9527G_000.zip)

**Comment by BenjaminSiskoo** [comment]
Le mode OpenGl est dans le même cas.

**Comment by fafling** [comment]
Sur la console, le haut de l'écran reste noir, alors que dans Kronos, il change de couleur et devient jaune à un certain moment. Cette couleur recouvre tout l'écran si on désactive toutes les couches dans Kronos, c'est donc celle du back screen.

Les autres couches sont tronquées en haut sur les 12 1ères lignes soit par une fenêtre pour les NBG, soit par le user clipping pour les sprites :
![image](https://user-images.githubusercontent.com/7624262/143334302-56bd7689-cf37-4eac-9aed-465beb59c32e.png)
![image](https://user-images.githubusercontent.com/7624262/143334340-8a8dc6fb-ccca-49c8-857d-a154640c47fa.png)

Le polygone de vidage des sprites ne concerne pas les 12 1ères lignes de l'écran :
![image](https://user-images.githubusercontent.com/7624262/143334385-934e1ecb-7c73-411c-8bb2-26c50c421d78.png)

Dans Mednafen, ce sont les sprites qui comportent une bande noire en haut de l'écran. Si on désactive les sprites, on voit la même couleur de back screen en haut de l'écran que dans Kronos, y-compris quand elle devient jaune. De plus, les registres d'erase/write du VDP1 ont les valeurs suivantes :
![image](https://user-images.githubusercontent.com/7624262/143349789-fed56a0a-b589-4196-882e-88b87b85b495.png)
Le VDP1 n'efface donc pas non plus les 12 1ères lignes d'écran par l'erase/write.

C'est donc que cette bande noire a été dessinée en haut de l'écran sans doute au début du jeu et elle y reste sans être effacée. Il s'agit potentiellement d'un dessin software par le CPU. J'ai déjà pu constater que Kronos ne prenait pas en compte des écritures faites par le CPU dans le framebuffer.

Je ne parviens pas à charger la save state avec Kronos v2.2.0, peut-être parce que qu'il s'agit d'une traduction et pas du jeu d'origine (mais aucune de mes save states de ce jeu, même celle du mois d'août, ne charge non plus).

Donc nouvelle save state du jeu d'origine :
[Akumajou_Dracula_X_descendre_pour_barre_jaune.zip](https://github.com/FCare/Kronos/files/7599462/Akumajou_Dracula_X_descendre_pour_barre_jaune.zip)

**Comment by fafling** [comment]
Moyen plus rapide de reproduire le problème car avec Alucard il faut attendre la fin de la video : quand on sélectionne Maria ou Richter directement, le problème ne se produit pas car le haut de l'écran est bien noir. Mais si on a sélectionné d'abord Alucard, puis fait A+B+C+start pour revenir à l'écran titre puis sélectionné Maria ou Richter, le haut de l'écran n'est plus noir sur au moins un des 2 framebuffers et on peut voir le back screen.

**Comment by BenjaminSiskoo** [comment]
Enfin corrigé ce bug, qui date de très longtemps.  :) Avec les branches test sync / FB access / esdr de Janvier / Février 2023

**Comment by BenjaminSiskoo** [comment]
Corrigé pour Maria et Richter mais pas pour Alucard. Testé avec Kronos 2.5.0 avec la vsync on et off. En Cs et sans filtres
