### ISSUE TITLE
[Gussun Oyoyo S (Japan)] Problème d'affichage du VDP1...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1078]
Kronos Wip 01.06.2021
Mode CS

Sur une des dernières lignes en bas de l'écran à hauteur d'1 pixel(alternance de bleu et de blanc)

![image](https://user-images.githubusercontent.com/12481242/126894457-572cfde8-2b6a-44b3-99d9-5e6af5e6d760.png)

Savestate : 
[gossun.zip](https://github.com/FCare/Kronos/files/6873629/gossun.zip)

**Comment by fafling** [comment]
C'est visible aussi sur la console, c'est le haut de l'eau qui monte progressivement dans les niveaux suivants.
