### ISSUE TITLE
[Scorcher] Affichage du ciel corrompue en 720p et GPU RBG...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1088]
Kronos Wip du 05/08/2021
Mode Cs

Le troncage du ciel en 720p avec GPU RBG est déjà présent à cette date.

![image](https://user-images.githubusercontent.com/12481242/128476800-fcdd71f3-db3c-445c-aa0a-31b22373877d.png)

**Comment by fafling** [comment]
Le troncage apparaît de manière variable quel que soit l'upscale, il est plus important en 1080p et moins en 480p. Exemple en 480p :
![image](https://user-images.githubusercontent.com/7624262/128595469-cdfa25b7-bc5f-461d-ace3-82a7bfe1caf1.png)

Ce troncage a toujours été présent en upscale avec GPU RBG depuis que le jeu s'affiche (à partir de la WIP du 08/12/2019).

La zone tronquée est une zone noire opaque sur le RBG1. Si on désactive cette couche, on voit le RBG0 derrière sans troncage.

Pour rappel, comme le RBG0 est un bitmap, il est rendu en OpenGL même en GPU RBG (workaround du bug #537 ).

L'affichage de la zone noire varie avec l'évolution du bug qui fait que le RBG1 est entièrement opaque au lieu d'être partiellement semi-transparent (voir #551 ). Quand ce bug a été temporairement résolu en résolution originale (entre le 29/12/2019 et le 04/01/2020), on voyait ceci en upscale (v2.0.1 publique) :
![image](https://user-images.githubusercontent.com/7624262/128595830-7473a0f5-8890-4f3e-8395-1073e99434bd.png)

Testé avec le CD d'origine US.

Save state :
[Scorcher_troncage_RBG1_upscale.zip](https://github.com/FCare/Kronos/files/6948892/Scorcher_troncage_RBG1_upscale.zip)

**Comment by BenjaminSiskoo** [comment]
Avec le correctif du 07/08/2021, il y a une pligne de pixel au milieu de l'écran qui commence à gauche et se termine au centre de l'écran.

![image](https://user-images.githubusercontent.com/12481242/128599155-90cae7ca-9f40-4e7f-9907-81b770273ee0.png)

**Comment by fafling** [comment]
Fixé en WIP du 07/08. Les lignes parasite sur les RBG sont un autre problème indépendant du troncage en upscale (voir #1091 ).
