### ISSUE TITLE
[Hideo Nomo World Series Baseball (Japan)] Kronos se ferme avant d'entrer in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1090]
Kronos Wip 07.08.2021
Mode CS

**Comment by barbudreadmon** [comment]
Pas de crash ici (testé avec asan), par contre le jeu est resté un bon moment sur l'écran de chargement pre-game, à un moment j'ai même cru qu'il avait freeze à cause d'une boucle infinie ou qqch du genre, vu que la charge de ma machine semblait très élevée (toutes mes applications commençaient à avoir de la latence).

**Comment by BenjaminSiskoo** [comment]
En relancant, j'ai pu aller un peu plus loin puis écran noir de mon moniteur après le loading playball je crois. Puis je suis revenu sur le bureau

![image](https://user-images.githubusercontent.com/12481242/128634222-c11ee192-f6bd-4c7d-8fda-a686b5d05a36.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 04.02.2022
