### ISSUE TITLE
[Scorcher] Ecran gris et ligne de pixel en trop...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1091]
Kronos Wip 07.08.2021
Mode Cs

![image](https://user-images.githubusercontent.com/12481242/128645940-04c64e59-34dd-4584-991c-b455010a00c9.png)

![image](https://user-images.githubusercontent.com/12481242/128645948-f43c6395-3edd-41b1-a090-8ebc27e7ff3b.png)

**Comment by fafling** [comment]
Ce sont 2 problèmes différents :
- La ligne parasite en bas du RBG1 en CS uniquement apparaît en 1ère WIP du 16/04/2020.
- L'écran gris n'est visible qu'en noyau OpenGL entre l'écran "Prepare to race" et la course. Le noyau CS enchaîne les 2 sans écran intermédiaire. Les 2 noyaux sont incorrects, car la console affiche un écran noir intermédiaire. Si on fait un soft reset en course avec le ciel affiché et qu'on relance une course, le noyau CS affiche le ciel en haut de l'écran gris intermédiaire :
![image](https://user-images.githubusercontent.com/7624262/128789640-1e7f32dd-6e8e-411c-9dee-55af2604824c.png)

**Comment by fafling** [comment]
Cet écran gris apparaît avec le fix de la semi transparence entre les RBG (#551 ), mais l'affichage du ciel comme écran intermédiaire en cas de reset est déjà là en version publique.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 05.01.2022
Mode Cs

Pour moi ca semble corrigé @fafling si tu vois un problème je rouvrirais.

**Comment by fafling** [comment]
@BenjaminSiskoo Peux pas vérifier dans les dernière WIP puisque le jeu freeze depuis la WIP du 05/01 :-/

Mais en WIP du 04/01 :
- L'écran intermédiaire est noir après l'écran de loading en OpenGL, mais vu que ça redevient noir en WIP du 09/12/2021 avec la disparition du RBG0 in game #551 , je dirais pas que c'est fixé tant qu'on peut pas résoudre les 2 problèmes en même temps.
- En CS, l'écran noir intermédiaire est toujours manquant, et les parasites en bas du RBG1 sont toujours là.

Est-ce que tu peux rouvrir ?

**Comment by BenjaminSiskoo** [comment]
Kronos 2.5.0
CS

Corrigé @fafling au pire je réouvre
