### ISSUE TITLE
[SEGA Rally Championship] Artefacts sur la route...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#11]
UoYabause 0.5.6 : 

![ss_sega_ rally_ championship](https://user-images.githubusercontent.com/12481242/32170868-a7f115f2-bd76-11e7-97c9-d9a2896488b2.JPG)

**Comment by BenjaminSiskoo** [comment]
Kronos du 20/10/2018 :

Les artefacts n'ont pas disparues, mais rien qu'au début il y en a bien moins.

![sega rally](https://user-images.githubusercontent.com/12481242/48834961-56f00480-ed7f-11e8-8a65-201f5f52f4c3.PNG)

**Comment by fafling** [comment]
Dans la demo, les trous ne semblent plus là dans la WIP du 08/06 :
![Capture_sega_rally_trous_20190608](https://user-images.githubusercontent.com/7624262/59144295-1d5ab000-89d6-11e9-96f5-e2b4d1d714dc.PNG)
@BenjaminSiskoo Tu peux vérifer ?

**Comment by BenjaminSiskoo** [comment]
En triangles, il reste encore quelques petits trous mais c''est largement moins marqués, à certains moments ce sont juste des points blancs. en CPU tesselation ca ne change rien, on voit toujours les trous.

**Comment by BenjaminSiskoo** [comment]
Je pense qu'on peut fermer
