### ISSUE TITLE
[Virtual On] Ecran noir après la démo...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1118]
Kronos Wip 20.08.2021
Mode CS

Si tu laisse tourner la vidéo de démo après le press start screen. A la fin Kronos bloque sur écran noir.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 04.02.2022
Mode Cs

Même problème mais avec la savestate c'est mieux : [MK-81042_000.zip](https://github.com/FCare/Kronos/files/8007064/MK-81042_000.zip)

Je suis sur l'écran noir à la fin de la démo

**Comment by fafling** [comment]
Reproduit avec la version japonaise (CD d'origine) dans les 2 noyaux en v2.3.1 publique et dans la dernière WIP.

Semble se produire lors d'un chargement juste après la fin de la video d'intro.
En fait pas la peine d'attendre la fin de la video, il suffit de la laisser démarrer et d'appuyer sur start pour obtenir le blocage.

L'IHM de Kronos continue de répondre, mais les compteurs de FPS disparaissent.
Il y a un invalid opcode dans DebugView lors de l'écran noir : 

Error: Master SH2 invalid opcode

R0 =  00000001 R12 =  06068418
R1 =  25FE00C4 R13 =  00000000
R2 =  00000000 R14 =  060020D0
R3 =  06000900 R15 =  06000A2C
R4 =  000000A0 SR =   000001F2
R5 =  25FE00A0 GBR =  FFFFFE00
R6 =  E0000000 VBR =  06000000
R7 =  E0000000 MACH = 00000000
R8 =  FFFFFFFF MACL = 00000000
R9 =  06068BD4 PR =   00000212
R10 = 06068430 PC =   E000021E
R11 = 06068BD8

C'est un problème ancien car je n'ai pas trouvé de version de Kronos sans, et il existe déjà dans Yabause 0.9.14.

**Comment by fafling** [comment]
Corrigé par le rework des interrupts entre le 27/10 et le 09/11.

**Comment by BenjaminSiskoo** [comment]
Merci pour les tests appronfondies
