### ISSUE TITLE
[Thunder Storm & Road Blaster (Japan) (Disc 1) (Thunder Storm)] Regression avec le patch du 27/08/2021...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1119]
Kronos Wip du 27.08.2021
Mode Cs

Avec ce commit qui corrigé les artefacts now loading du jeu akumajou draculaX et à priori doukyusey. Il entraine une régression sur le texte pour thunderstorm.

https://github.com/FCare/Kronos/commit/9aa00925f513850cc03ae9d51719c81abc8bacfc

![image](https://user-images.githubusercontent.com/12481242/131136450-aae12c45-2b77-461d-ad54-5d78e78eca92.png)

**Comment by fafling** [comment]
Les lettres sont des distorted sprites dont la texture fait 8x8 pixels et la zone de dessin fait la même taille. Il ne devrait donc y avoir aucune déformation de ces textures.
![image](https://user-images.githubusercontent.com/7624262/131233146-9e0c5ffa-0ba7-4f43-800f-7420e6112a3e.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 14.10.2021
