### ISSUE TITLE
[Doom] Régression 27.08...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1120]
Scintillement en bas de l'écran avec la version du 27.08, pas de soucis avec celle du 25.08

https://youtu.be/kwQ6LPXfeqs

**Comment by fafling** [comment]
Il y a effectivement des clignotements supplémentaires dans cette WIP, mais je ne dirais pas qu'il n'y avais pas de souci avant. Le sol est déjà complètement incorrect dans la version du 25/08 (en fait il l'a toujours été en noyau CS, voir #470 ).

**Comment by BenjaminSiskoo** [comment]
Corrigé le 30.08.2021
