### ISSUE TITLE
Sprites sans scaling incorrect en CS

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1126]
En WIP du 30/08, et depuis celle du 23/08, en noyau CS uniquement, les boutons du mutiplayer sont dessinés de manière incorrecte :
![image](https://user-images.githubusercontent.com/7624262/131419384-85d629e5-974c-40f3-9ecf-01e34f1334b7.png)

Affichage correct en noyau OpenGL :
![image](https://user-images.githubusercontent.com/7624262/131419715-0c76ab6a-668f-489f-8e53-4a8982555c00.png)

Le boutons sont des scaled sprites avec une texture de 32x32 et une taille de zone de dessin de 32x32, il ne devrait y avoir aucune déformation par rapport à la texture affichée dans l'écran debug du VDP1 :
![image](https://user-images.githubusercontent.com/7624262/131419559-544be2b1-0649-446e-b367-86414a074285.png)

**Comment by fafling** [comment]
Un problème similaire apparaît aussi dans la WIP du 23/08 en noyau CS uniquement sur les chiffres du HUD dans Off world interceptor (suffit de laisser démarrer la démo pour le voir). Ce sont des normal sprites. Leur dernière ligne est doublée de manière incorrecte (screenshot en integer scaling) :
![image](https://user-images.githubusercontent.com/7624262/134766116-fca65648-b818-461e-b56c-c236203070c4.png)

Affichage correct en v2.1.5 publique :
![image](https://user-images.githubusercontent.com/7624262/134766212-531f9bd1-f7b9-40e4-a834-746de99e2c6f.png)

![image](https://user-images.githubusercontent.com/7624262/134766226-e668b67c-3f08-4c72-8737-f8371ff9bb00.png)

**Comment by fafling** [comment]
Le problème touche aussi les distorted sprites dont les coordonnées de dessin font la même taille que la texture, donc sans aucun scaling sur la console. On le voit dans Gale racer sur l'écran de sélection de la sauvegarde quand on relance le jeu. Le haut des chiffres ou lettres est tronqué :
![image](https://user-images.githubusercontent.com/7624262/134766538-a847638a-a2be-404b-bbe7-8a54954b7eaf.png)

![image](https://user-images.githubusercontent.com/7624262/134766553-d249fe85-f188-4f2a-b6cc-1b3393dae302.png)

Affichage correct en v2.1.5 publique :
![image](https://user-images.githubusercontent.com/7624262/134766705-64cf30a0-fe88-4fc8-81b4-292d2a904185.png)

**Comment by fafling** [comment]
En WIP du 15/10/2021, redeviennent corrects :
- Les chiffres du HUD dans Off world interceptor
- Les boutons du bios

Mais dans le bios, les chiffres dans le bandeau bleu en haut ne sont plus corrects. Ce sont des normal sprites.
Capture en integer scaling :
![image](https://user-images.githubusercontent.com/7624262/137562946-17bc3f5c-34ee-4669-86d8-efc73ae47e3b.png)

Nouveau problème visible aussi sur les textes ou chiffres dans Sonic 3D :
![image](https://user-images.githubusercontent.com/7624262/137563813-a799e9f7-4d09-4f77-808d-28c9bed13499.png)

Les distorted sprites de Gale racer ont changé de forme, mais sont toujours incorrects :
![image](https://user-images.githubusercontent.com/7624262/137563164-aff57082-40be-4d3f-892a-9d816ff24f69.png)

**Comment by fafling** [comment]
En WIP du 17/12/2021, sont corrects :
- Les caractères dans Gale racer (distorted sprites).
- Les chiffres du bandeau bleu du bios (normal sprites).
- Les caractères de l'écran titre de Sonic 3D (normal sprites), testé sur la WIP du 16/12, parce que l'écran titre freeze Kronos dans celle du 17 :-/

Mais sont incorrects :
- Les boutons du bios (scaled sprites), voir 1ère capture tout en haut.
- Les sprites du HUD de Off world (distorted sprites), la ligne du milieu est dupliquée :
![image](https://user-images.githubusercontent.com/7624262/146620364-70fdeacf-0df6-48ec-a805-3f71a6c00a17.png)

**Comment by fafling** [comment]
En WIP du 28/12/2021, sont corrects :
- Les chiffres du bandeau bleu du bios (normal sprites).
- Les caractères de l'écran titre de Sonic 3D (normal sprites).
- Les sprites du HUD de Off world (distorted sprites).

Sont incorrects :
-  Les boutons du bios (scaled sprites) :
![image](https://user-images.githubusercontent.com/7624262/147614559-30195006-da8e-4efb-9ace-9671b0e9f65f.png)

- Les caractères dans Gale racer (distorted sprites, manque une ligne au milieu sur "3" et le "E") :
![image](https://user-images.githubusercontent.com/7624262/147612936-57ddf389-2026-4447-b524-4cb0c1b33e9d.png)

**Comment by BenjaminSiskoo** [comment]
Kronos du 29.12.2021

![image](https://user-images.githubusercontent.com/12481242/147707800-13ff40b1-71df-4ffe-a8ba-881e8c0ca169.png)

**Comment by fafling** [comment]
Les boutons (scaled sprites) du bios sont maintenant déformés de l'autre côté, et les chiffres dans le bandeau bleu (normal sprites) sont de nouveau incorrects :
![image](https://user-images.githubusercontent.com/7624262/147713120-97247b27-396d-4ac9-9a26-09f8fbb210ae.png)

**Comment by fafling** [comment]
Début des problèmes d'upscale incorrects en résolution originale ou integer scaling dans la WIP du 31/05/2021 lors du début de la résolution de ce problème graphique pour l'upscale de Kronos : #1013.

**Comment by fafling** [comment]
Je confirme les sprites sans scaling sont corrects en WIP du 21/05/2021, et deviennent incorrects en WIP du 31/05/2021 (probablement dû au commit 214b9458700e957f934a4f75dfb6f34064f23c50).

Les sprites sans scaling redeviennent ensuite temporairement corrects en WIP du 10/08/2021 (reverts  70e5bea2d4cb40c59d4e65905fe05ab182bd50a4 et 9915bf2c99f4b7cedfe50c3dbd6580c7739358da), et redeviennent incorrects en WIP du 20/08/2021 (probablement dû à ddecc6b1d7e5f12b3d125e39b91e7cd6ec49d60d).

**Comment by BenjaminSiskoo** [comment]
Kronos du 13.01.2022
Mode CS 
Option vidéo par défaut

Off World Interceptor : ca semble ok 

![image](https://user-images.githubusercontent.com/12481242/149382419-77a2f0df-d419-4d76-ac63-c79367eed391.png)

**Comment by BenjaminSiskoo** [comment]
![image](https://user-images.githubusercontent.com/12481242/149382654-9297031f-a4ed-4b46-8839-f61a108fbdec.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 13.01.2022

**Comment by fafling** [comment]
Le fix introduit une régression dans les 2 noyaux dans fire pro gaiden blazing tornado sur les scaled sprites inversés horizontalement par les coordonnées de dessin (xc < xa).

En WIP du 13/01/2022, ces sprites ne sont plus affichés, et en WIP du 14/01/2022, leur taille est trop petite d'un pixel (se voit sur les cordes de la moitié droite du ring qui ont des trous entre les sprites). Même situation dans la v2.3.1 publique.
![image](https://user-images.githubusercontent.com/7624262/154266984-d70b4cd0-d92b-4b86-90c3-a81b3046dbf5.png)

Dans l'écran debug du VDP1, les coordonnées de dessin de ces commandes sont bien adjacentes et les textures des cordes n'ont pas de trous au bord :
![image](https://user-images.githubusercontent.com/7624262/154266760-e8287d6f-0368-4dbe-8c73-2b680f4a9d5e.png)
![image](https://user-images.githubusercontent.com/7624262/154266806-57bbb4f3-a66d-4775-9388-0fea5b790645.png)

Testé avec le CD original.
Save state :
[blazing_tornado_debut_combat_2.3.1.zip](https://github.com/FCare/Kronos/files/8079939/blazing_tornado_debut_combat_2.3.1.zip)

@BenjaminSiskoo Est-ce que tu peux rouvrir ?

**Comment by fafling** [comment]
Fixé en WIP 01/12/2024, sûrement par 5807590.
