### ISSUE TITLE
[Hyper Duel (Japan] Artefacts en bas d'écran...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1133]
Kronos Wip 30.08.2021
Mode CS

![image](https://user-images.githubusercontent.com/12481242/131967562-d6a9110e-0d3b-4b49-a198-688eb3c27bb4.png)

**Comment by fafling** [comment]
C'est un affichage correct, pas des artifacts : ce sont les jauges de tir spécial du mode Saturn. Le mode arcade a des jauges de forme différente.
