### ISSUE TITLE
[Burning Rangers] Régression Ralentissement et bug graphique...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1134]
Kronos Wip du 01.09.2021
Mode CS et OpenGL

Possiblement un problème avec le VDP1.

Ralentissement dans le jeu. Plus des problèmes graphique. 

![image](https://user-images.githubusercontent.com/12481242/132059760-6b0a0b33-b903-4aca-94ce-4336d32229e4.png)

**Comment by BenjaminSiskoo** [comment]
Charge CPU quasi doublé.
Photo de droite, c'est avec la dernière version public

![image](https://user-images.githubusercontent.com/12481242/132061043-4df4cc0e-b73a-4264-97ba-cc10753599ca.png)

**Comment by BenjaminSiskoo** [comment]
la liste de commande est différente

![image](https://user-images.githubusercontent.com/12481242/132061206-c6fe7a8b-d9ae-4ef9-9160-53fd405033ec.png)

**Comment by barbudreadmon** [comment]
Le problème commence avec https://github.com/FCare/Kronos/commit/8a7fe2ce2b26a6063668d2f0e5060e33b87b07d8 (et disparaît de nouveau en faisant un revert du commit), c'est peut-être lié à ce qui avait été constaté et fixé avec https://github.com/FCare/Kronos/commit/89646cca3fa4fe433751ac94630da28f3a5ab52f : le jeu exécute énormément de cmds sur le vdp1.

**Comment by fafling** [comment]
J'ai noté que la WIP du 14/01 servait à fixer les clignotements de sprites sur Earthworm Jim PAL (#982 ). Elle entraîne d'autres régressions (#987 ) :
- Des corruptions de sprites dans Metal slug.
- Des clignotement dans l'inventaire de Virtual Hydlide.

Burning rangers utilise 2 listes de commandes VDP1 dans une même frame :
- La 1ère dessine les graphismes semi transparents (flammes, flares, vitres) et des masques qui les effacent correspondant aux graphismes opaques (personnages, objets du décor). Le dessin est fait à une échelle 1/2, et il est transféré vers la VRAM du VDP2 pour être affiché par le NBG1 avec un zoom.
- La 2ème efface le 1er dessin et dessine ensuite les graphismes opaques à l'échelle normale.

Depuis la WIP du 14/01, le dessin de la 1ère liste chevauche celui de la 2ème. Ce sont les perso dessinés en noir qu'on voit dans le coin en haut à gauche.

**Comment by barbudreadmon** [comment]
En faisant le revert : 
- les clignotements sur Earthworm Jim 2 (PAL uniquement) reviennent
- les clignotements d'inventaire sur Virtual Hydlide disparaissent
- la corruption de sprite sur Metal Slug est toujours là
- les clignotements sur la selection de langue dans Darklight Conflict disparaissent également

**Comment by rob-ack** [comment]
relates to #1158

**Comment by fafling** [comment]
Fixé en WIP du 20/09/2021, mais au prix du retour des clignotements dans Earthworm Jim 2 (PAL).

**Comment by BenjaminSiskoo** [comment]
Corrigé le 04.01.2022

**Comment by fafling** [comment]
Dans la WIP du 04/01/2022, dans les 2 noyaux, les perf sont en dents de scie in game, il y a d'énorme saccades et le compteur de fps ne correspond pas à ce que je vois : il peut y avoir une image par seconde alors que le compteur affiche 40 fps.

C'est très visible au démarrage de la 1ère mission, et une partie des sprites n'est pas affichée lorsque les perf chutent (on retrouve un affichage similaire à une des captures de Benjamin du 03/09/2021, mais sans le chevauchement des sprites en noir) :
![image](https://user-images.githubusercontent.com/7624262/148132816-5c0d90d0-2f5b-45f2-a5c4-93e8ec02b833.png)

Save state :
[Burning_rangers_debut_1ere_mission_20220104.zip](https://github.com/FCare/Kronos/files/7810809/Burning_rangers_debut_1ere_mission_20220104.zip)

@BenjaminSiskoo Est-ce que tu peux rouvrir ?
