### ISSUE TITLE
[Doukoku Soshite (J)] Problème de transparence...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#114]
Problème de transparence sur la lune et dans les dialogues.

Kronos 1.1.0 : 

![doukoku_soshite_kronos_ingame](https://user-images.githubusercontent.com/12481242/37355282-46df0796-26db-11e8-9f82-e703334765b7.jpg)
![doukoku_soshite_kronos_moon](https://user-images.githubusercontent.com/12481242/37355283-470d8a12-26db-11e8-8813-a979a4d134ec.jpg)

Acquis depuis une TV et une console saturn : 
 
![doukoku_soshite_tv_ingame](https://user-images.githubusercontent.com/12481242/37355326-5e08a422-26db-11e8-8e2e-3ff8e5f9c59f.jpg)
![doukoku_soshite_tv_moon](https://user-images.githubusercontent.com/12481242/37355327-5e2c6646-26db-11e8-9e8b-0adc1f53b031.jpg)

**Comment by FCare** [comment]
La lune est fixée. Le dialogues sont toujours differents...

**Comment by BenjaminSiskoo** [comment]
La lune semble fixé, le premier dialogue scintille avec le commits qui a permis de régler la lune.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 25/04/2018
