### ISSUE TITLE
[J.League Go Go Goal! (Japan)] Problème graphique avec le GPU RBG activé...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1141]
Kronos 09.09.2021
Mode CS

En activant le GPU RBG, le terrain de foot est mal affiché.

![image](https://user-images.githubusercontent.com/12481242/132942115-d085553a-86c5-4bf8-93a8-22fd40db0846.png)

En le désactivant, le comportement est correcte : 

![image](https://user-images.githubusercontent.com/12481242/132942135-0441ef0c-68dd-47a3-be32-128039870b41.png)

**Comment by fafling** [comment]
Le problème apparaît en WIP du 09/08. Peut-être causé par d9098f2b1ba57bb41923ef112dfea9dfde95d3dd.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 24.09.2021
