### ISSUE TITLE
Regression with September 19-20 commits...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1157]
**Stellar Assault :** 

- the game was playable. The main issue was slowdowns to display logo and video at the start . 
- With the commit of september 19-20, video was not played but the logo was displayed at the good speed. Here a footage :  (https://youtu.be/ejo6Nk1YStU). With 
- With the commit of september 20 (doom fixe), Stellar Assault is not booting, we have a black screen.

**Neon genesis Digital Card Library :** 

- With Kronos 2021.09.17 : the game was playable since a long time. 
- With Kronos 2021.09.20 : the game closes Kronos at the start.

**Digital Ange - Dennou Tenshi SS :**

- With Kronos 2021.09.17 : the game was playable since a long time. 
- With Kronos 2021.09.20 : the game closes Kronos when you push start to the press start screen.

**Comment by BenjaminSiskoo** [comment]
**Die Hard Trilogy :** 

- With Kronos 2021.09.17 : the game was not playable but it was possible to have the first screen (very long).
- With Kronos 2021.09.20 :We have a black screen.

**Comment by FCare** [comment]
Digital Ange is working perfectly on linux side, no crash.

**Comment by FCare** [comment]
neon genensis digital card library also

**Comment by BenjaminSiskoo** [comment]
Kronos Wip 23.09.2021 digital ange and digital card are ok.
