### ISSUE TITLE
[Burning rangers] Artefacts in game and flickering...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1158]
Kronos fork Wip 2021.09.21
Mode CS
No filter video.

https://www.youtube.com/watch?v=740XlYtBejs

![image](https://user-images.githubusercontent.com/12481242/134156795-4e22431f-9921-4ecc-b3d1-0c13a8e0150b.png)

![image](https://user-images.githubusercontent.com/12481242/134157052-b4276326-488a-41eb-8f2d-8534de41c105.png)

**Comment by FCare** [comment]
Tu peux expliquer? Je vois que le polygone en haut de manquant. C'est quoi les autres ronds?

**Comment by BenjaminSiskoo** [comment]
Regarde la vidéo pour voir les scintillements / Check the video to see the flickering

**Comment by FCare** [comment]
toujours en carte graphique ATI?

**Comment by BenjaminSiskoo** [comment]
Yup

**Comment by rob-ack** [comment]
vid is private :/

**Comment by BenjaminSiskoo** [comment]
Kronos du 16.12.2021

Régression : avec VDP1 on

![image](https://user-images.githubusercontent.com/12481242/146379764-ec319dc9-ff01-4abb-8665-9128525d17d8.png)

Avec VDP1 off : 

![image](https://user-images.githubusercontent.com/12481242/146379824-8e1c2542-3746-4cb4-95a2-27345020a66d.png)

savestate : 
[MK-81803_000.zip](https://github.com/FCare/Kronos/files/7727592/MK-81803_000.zip)

**Comment by fafling** [comment]
@BenjaminSiskoo La régression, qui n'a rien à voir avec ce br, n'existe plus dans la WIP du 31/12.
Les clignotements et polygones manquants que tu montres avec ta video existent aussi sur la console.

**Comment by BenjaminSiskoo** [comment]
Je ferme alors @fafling ?
