### ISSUE TITLE
[Filtres] Problème avec le scanline en mode fenêtré + autre problème

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#116]
Le filtre scanline ne fonctionne pas en mode fenêtré.
De plus en mettant filtre none + HQ4X, le filtre n'est pas actif.

**Comment by FCare** [comment]
j'ai encore testé ca marche chez moi. envoie moi un screenshot du bios et le kronos.ini qui montre le pb.

**Comment by BenjaminSiskoo** [comment]
![1scanline](https://user-images.githubusercontent.com/12481242/37419988-a18fe3fe-27ad-11e8-89c7-3e04a51778c3.JPG)

**Comment by BenjaminSiskoo** [comment]
![1scanline](https://user-images.githubusercontent.com/12481242/37421091-5421ec40-27b0-11e8-8671-08c07af9931e.JPG)

**Comment by BenjaminSiskoo** [comment]
Corrigé en ce jour
