### ISSUE TITLE
Zero Divide: The Final Conflict (RBG Scaling Has No Effect At All)

### ISSUE THREAD

**Issue by ArtOfZenDigital** [FCare/Kronos#1160]
What's the full name of the game? Zero Divide: The Final Conflict (Japan)

What's your frontend ? Stand Alone Windows 10 Kronos version 2.1.5 64 Bit

What's your OS? Windows 10 Pro 64bit

What's your hardware? Intel i9 9900K at 5ghz, Nvidia RTX 3080 TI, Adata XPG Pro 1Tb M2 SSD, MSI MPG Z390 Gaming Plus Motherboard

What's the storage type of the game? CD image created from my original Sega Saturn game CD

What's the format of your CD image? cue/bin

Settings: Kronos 2.1.5, Multithreading: 14 threads, Bios: Sega Saturn BIOS v1.01 (multinorm).bin, Sync Saturn internal clock with set time, Open GL, Nanovg OSD Interface, Original Aspect Ratio, Start In Fullscreen, Upscale: HQ4X, Bilinear Filtering, Native Current Window Resolution (3840x2160 TV 4K), GPU Tesselation, Scanlines Off, Mesh Mode: Improved, GPU RBG: On, SDL Sound Interface, 32 Mbit Dram, Extend Internal Memory to 8MB, SH2 Kronos Interpreter, 68000 Core: Musashi Interface, Hide Menubar: On Fullscreen, Hide Toolbar: On Fullscreen, SDL Joystick Interface, Gamepad: Official Sega Saturn Retrobit USB Gamepad

Is it happening with other games? The lack of RBG Upscaling also occurs in Virtual-On Cyber Troopers (USA). RBG scaling is working correctly in Virtua Fighter 2, Virtua Fighter Kids, as well as many other Saturn games that I've played in Kronos 2.1.5. As you can see from the two included Zero Divide (Jpn) screen shots, the floor and background elements in look rough and jagged compared to the sharp, and smooth floors and backgrounds in two included Virtua Fighter 2 (USA) screenshots. The Fighter's MegaMix (USA) screenshot also shows correct RBG scaling as well. The settings are exactly the same for all of the games, as is the emulator version, Kronos 2.1.5 64 Bit.

![Zero Divide (RBG Scaling Doesn't Work) 1](https://user-images.githubusercontent.com/91174966/134288206-036177a7-c534-41e6-b205-7c5d1150fe4b.jpg)
![Zero Divide (RBG Scaling Doesn't Work) 2](https://user-images.githubusercontent.com/91174966/134288211-1ddf71e1-6ec5-4e10-8ec4-a7c58cd9dbdf.jpg)
![Virtua Fighter 2 Watch Mode (RBG Works Using The Settings Listed) 1](https://user-images.githubusercontent.com/91174966/134289147-61e271c1-6ed2-45af-b971-87ff7f87616e.jpg)
![Virtua Fighter 2 Watch Mode (RBG Works Using The Settings Listed) 2](https://user-images.githubusercontent.com/91174966/134290437-aa48e49f-2b4b-4979-8dfe-094e77fd76ed.jpg)
![Fighters MegaMix (RBG Works Using The Settings Listed) 1](https://user-images.githubusercontent.com/91174966/134290451-9707d47c-fce4-4419-9c61-3c82dfe579c6.jpg)

**Comment by FCare** [comment]
RBG scaling has effect only on tile mode since it is computationally displayed.
In case of the games your are reporting, the RBG is in bitmap mode.

There is no way to improve the RBG in that case since the bitmap used is in low resolution. Scaling linke bilinear or whatever will not improve the image. Only possibility would be to replace the texture itself.

**Comment by ArtOfZenDigital** [comment]
Kronos is easily the best Saturn emulator, and all of your hard work is truly appreciated. Your response is a little confusing though, because YabaSanshiro also has RBG scaling and it works perfectly in Zero Divide. When RBG is turned off in YabaSanshiro, the floors and background graphics look exactly the same way they look in Kronos 2.1.5 with RBG scaling turned on. The reason why playing it in Kronos is better is because the player models aren't fully rendered in YabaSanshiro. I turned off the VDP1 layer so you can see what Zero Divide's floors look like with RBG on in YabaSanshiro in the first screenshot. The second screenshot shows the same exact stage in Kronos with RBG on, and VDP1 on. Both emulators are rendering at 4K, however, the screenshots are saved at 2560x1440. 

In every other game that works on both YabaSanshiro and Kronos, when RBG is on in both emulators, the games look exactly the same, except YabaSanshiro's Original Aspect Ratio option is visibly wider than the Original Aspect Ratio option in Kronos. Since Kronos has much higher game compatibility, and it's updated more frequently, with more bug fixes, it's a better emulator overall. Thank you again for all of your hard work. The Saturn was one of my favorite systems, and it was used more than my PlayStation One. Until Kronos was released, with RBG, I thought VDP2 scaling would never happen. The games that work with RBG look amazing.

![Zero Divide  YabaSanshiro VDP1 Off RBG On](https://user-images.githubusercontent.com/91174966/134517165-530ae7fe-7aa6-47a0-834c-e9642d181158.jpg)
![Zero Divide Kronos VDP1 On RBG On](https://user-images.githubusercontent.com/91174966/134517174-683b248a-291a-4be5-b744-00a77a0d6301.jpg)
