### ISSUE TITLE
[Panzer Dragoon Saga] missing texts in in-game documents

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#1161]
- Panzer Dragoon Saga (USA)
- Libretro port on linux x64
- Nvidia GTX 960
- using a redump image
- default settings (it seems to happen whatever the settings anyway)
- i don't know if the issue is new or not
- here is a bkram from disc 3 : [bkram-pds.zip](https://github.com/FCare/Kronos/files/7209144/bkram-pds.zip)

There are in-game documents accessible this way :
1. Open menu (start)
2. Select "Show Item List"
3. Select "List of items that cannot be sold"
4. Select an item

This is how it should be displayed (screenshot from mednafen) : 
![Panzer Dragoon Saga (USA) (Disc 3)-210922-104122](https://user-images.githubusercontent.com/10391265/134311797-18ce8206-024f-4243-b6f6-f207a87a0bd2.png)

This is how it's displayed in Kronos : 
![Panzer Dragoon Saga (USA) (Disc 3)-210922-104206](https://user-images.githubusercontent.com/10391265/134311845-ed7e1769-e1bb-481d-881f-0adac17a5216.png)

**Comment by BroKill** [comment]
Same bug/issue with the PAL version of the game and it happens both using the Standalone and the RA core.

GREETs

**Comment by BenjaminSiskoo** [comment]
Thanks for your bug report. We have to wait a fix. It can take some time. But it will be fix :)

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 15.12.2021
Mode Cs

Still the same. NBG3 problem ?

![image](https://user-images.githubusercontent.com/12481242/146169273-45b4cabd-38a2-4d09-9e82-0d9c484f0e9a.png)


New savestate : [MK-81307_000.zip](https://github.com/FCare/Kronos/files/7718413/MK-81307_000.zip)

**Comment by FCare** [comment]
Window related issue

**Comment by BenjaminSiskoo** [comment]
Fixed with Kronos 2.2.0 15.12.2021

**Comment by legaiaflame** [comment]
Awesome thanks guys!
