### ISSUE TITLE
Adding RBG Resolution Setting Similar To YabaSanshiro

### ISSUE THREAD

**Issue by ArtOfZenDigital** [FCare/Kronos#1163]
What's the full name of the game? Zero Divide: The Final Conflict (Japan)

What's your frontend ? Stand Alone Windows 10 Kronos version 2.1.5 64 Bit

What's your OS? Windows 10 Pro 64bit

What's your hardware? Intel i9 9900K at 5ghz, Nvidia RTX 3080 TI, Adata XPG Pro 1Tb M2 SSD, MSI MPG Z390 Gaming Plus Motherboard

What's the storage type of the game? CD image created from my original Sega Saturn game CD

What's the format of your CD image? cue/bin

Settings: Kronos 2.1.5, Multithreading: 14 threads, Bios: Sega Saturn BIOS v1.01 (multinorm).bin, Sync Saturn internal clock with set time, Open GL, Nanovg OSD Interface, Original Aspect Ratio, Start In Fullscreen, Upscale: HQ4X, Bilinear Filtering, Native Current Window Resolution (3840x2160 TV 4K), GPU Tesselation, Scanlines Off, Mesh Mode: Improved, GPU RBG: On, SDL Sound Interface, 32 Mbit Dram, Extend Internal Memory to 8MB, SH2 Kronos Interpreter, 68000 Core: Musashi Interface, Hide Menubar: On Fullscreen, Hide Toolbar: On Fullscreen, SDL Joystick Interface, Gamepad: Official Sega Saturn Retrobit USB Gamepad

Is it happening with other games? Yes. I opened an issue about RBG backgrounds that look rough even with the RBG setting on. FCare was kind enough to respond quickly, saying that:

> RBG scaling has effect only on tile mode since it is computationally displayed.
> In case of the games your are reporting, the RBG is in bitmap mode.
> 
> There is no way to improve the RBG in that case since the bitmap used is in low resolution. Scaling linear bilinear or whatever will not improve the image. Only possibility would be to replace the texture itself.

The confusing thing for me was how YabaSanshiro, another fork of Yabuse, doesn't have that issue when RBG is on. Now I know why the floor and background textures are always sharp in YabaSanshiro, even though it handles RBG scaling the same way. In YabaSanshiro, there's an option to change the actual resolution of RBG scaling, similar to the setting for VDP1 resolution scaling. The reason I prefer Kronos, despite the RBG resolution scaling option is its frequent updates, and wider game compatibility. Is it possible to add RBG Resolution scaling to match the OS resolution?

The first screen shot shows the RBG scaling option in YabaSanshiro, and the second one shows the Kronos options, which only allow for RBG on or off, without an option to scale the RBG resolution.

![YabaSanshiro](https://user-images.githubusercontent.com/91174966/134617255-1999d41a-7424-4061-ac2c-55390d9c3976.JPG)
![Kronos](https://user-images.githubusercontent.com/91174966/134617272-9e6fcefb-39cf-46af-bb60-579211f7904a.JPG)

You can see in this screen shot from Zero Divide running in YabaSanshiro, with VDP1 turned off, that shows how RBG resolution scaling completely cleans up the VDP2 RBG floor surface. The Windows resolution is 3840x2160 (TV 4K res). The gameplay screen shots are both compressed to 2560x1440.
![134517165-530ae7fe-7aa6-47a0-834c-e9642d181158](https://user-images.githubusercontent.com/91174966/134617285-3a028a12-6fd3-4b34-9ea1-fe4750c7a08d.jpg)

The second screen shot shows Zero Divide running in Kronos 2.1.5 with RBG on. After FCare explained why the VDP2 backgrounds weren't scaled, it makes sense as to why the backgrounds look so sharp in YabaSanshiro. The YabaSanshiro screen shot shows why being able to scale the RBG resolution can drastically improve textures and backgrounds that simply enabling RBG in Kronos can't currently scale.
![134517174-683b248a-291a-4be5-b744-00a77a0d6301](https://user-images.githubusercontent.com/91174966/134617566-89b990bc-1808-445c-a80c-2ec56c3cb49d.jpg)

**Comment by barbudreadmon** [comment]
iirc, there is no RBG resolution setting in Kronos because it's actually always using the same resolution as VDP1, meaning if you are using native in Kronos you should have the same result than native+native in yabasanshiro, so i doubt the lack of RBG resolution setting in Kronos is the issue here.

**Comment by FCare** [comment]
Exactly. Anyway, it may have an issue on kronos regarding RBG bitmap mode
support when running on GPU. currently this support is disabled. Let's try
to re-eanble and see if we can fix :-)

Le ven. 24 sept. 2021 à 08:34, barbudreadmon ***@***.***> a
écrit :

**Comment by FCare** [comment]
I fixed this in the last WIP version. There is effectively a small improvement in the rendering results but not so obvious than VDP1.
If you are able to compile, you can compile by your own or you will have to wait for next release to test it.
Thanks for your report :-)

**Comment by ArtOfZenDigital** [comment]
> 
> 
> I fixed this in the last WIP version. There is effectively a small improvement in the rendering results but not so obvious than VDP1.
> If you are able to compile, you can compile by your own or you will have to wait for next release to test it.
> Thanks for your report :-)

I'm not quite sure how to compile the work in progress releases, but I would love to test them since I'm currently working on a Sega Saturn video for my YouTube channel, as well as a Virtua Fighter port history video, which includes the Saturn versions as well. Thank you for explaining how everything works, I appreciate it.
