### ISSUE TITLE
[Daytona USA Circuit Edition (Japan)] Invisible letters while entering a name

### ISSUE THREAD

**Issue by BroKill** [FCare/Kronos#1167]
Daytona USA Circuit Edition (Japan)

Version used : Standalone and RA core

OS : Windows 10 1803 x64

My HW : CPU Intel I7 4790k, GPU NVIDIA GTX 770 and 16 GB DDR3

Game format is in CHD

To replicate this issue select an Arcade track, finish the race in the first 3 positions and enter a name, letters will be invisible but you will see what you selected when chart appears.
Issue occurs both with default and with custom settings.

GREETs

**Comment by BenjaminSiskoo** [comment]
Same problem with Kronos Wip 2021.09.26.

Here's the savestate : 

[GS-9100_000.zip](https://github.com/FCare/Kronos/files/7271153/GS-9100_000.zip)
