### ISSUE TITLE
Program segfaults at launch when there is a folder named kronos in home directory

### ISSUE THREAD

**Issue by gabrielgaps** [FCare/Kronos#1168]
What's your frontend ? (standalone, libretro, ...) ?
Standalone

What's your OS ? (windows, linux, OSX, ...) ?
Arch GNU/Linux

What's your hardware ? (CPU, GPU, ...) ?
Intel i5-9400
NVIDIA GeForce GTX 1650 SUPER 
Ram 16gb

Are you using any setting different from default ? If so, precise
At first I thought the problem was changing any default directory to ~/kronos, but just that folder existing makes the program segfault

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this
There isn't any other message besides segmentation fault

**Comment by BenjaminSiskoo** [comment]
Thanks :)

**Comment by FCare** [comment]
Hi, this is a really strange issue. Do you have any path which are using the ~/kronos path? Can you please add your kronos.ini file to the ticket (can be found in ~/.config/kronos/qt/kronos.ini)

I am not abl to reproduce on a linux/ubuntu system.

Maybe there is a not updated path in your kronos.ini file

**Comment by gabrielgaps** [comment]
> Hi, this is a really strange issue. Do you have any path which are using the ~/kronos path? Can you please add your kronos.ini file to the ticket (can be found in ~/.config/kronos/qt/kronos.ini)
> 
> I am not abl to reproduce on a linux/ubuntu system.
> 
> Maybe there is a not updated path in your kronos.ini file

I do not have a path using it.
Even with a blank .ini file the problem exists.
It is not a big deal since I can just not have the directory exist to use kronos, but it is very strange.
I'll try replicating this issue on another machine to see if it's an Arch specific problem or just my own system.

**Comment by gabrielgaps** [comment]
Tested in a separate Arch machine with a cleaner install. Issue does not exist. I'm just gonna assume it's a quirk with my personal system and close.
