### ISSUE TITLE
[st-niccc demo] Freeze à la 1ère frame

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1173]
Dans la dernière WIP et en v2.1.5 publique, dans les 2 noyaux, la demo st-niccc de mrkotfw bloque à la 1ère frame. L'IHM de Kronos n'est pas bloquée.
![image](https://user-images.githubusercontent.com/7624262/137211807-9d62d65c-7cdc-48f8-8317-6366d9de0d79.png)

La demo fonctionne en v2.1.3 publique. Le blocage apparaît en WIP du 02/09/2020, qui fixait les fontaines dans Shining force 3.

ISO de la demo :
[vdp1-st-niccc_20211013_1.zip](https://github.com/FCare/Kronos/files/7341391/vdp1-st-niccc_20211013_1.zip)

Fonctionnement du programme de mrkotfw :
![image](https://user-images.githubusercontent.com/7624262/137212684-a36c64d0-d071-497e-8438-a6be94bb01ec.png)

**Comment by BenjaminSiskoo** [comment]
@fafling ca semble ok avec la wip d'hier

**Comment by fafling** [comment]
Oui c'est OK dans la 2 noyaux dans la dernière WIP.
C'est fixé depuis la WIP du 05/01/2022 qui corrigeait #906 .
