### ISSUE TITLE
[SegaColle Sega Bible Mogitate SegaSaturn Soukan-gou (Japan)] Les vidéos ne se lancent plus...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1176]
Kronos Wip du 14.10.2021
Mode CS
Bios intégré / Vrai Bios

En janvier 2021, les vidéos se lançaient avec le bios intégré, mais pas avec le vrai bios. Avec la Wip du 14.10.2021, ca ne marche plus.

**Comment by BenjaminSiskoo** [comment]
kronos20231211_46c12d6

Sur le débug VDP2, dans le choix de l'écran, il n'y a aucune couche

![image](https://github.com/FCare/Kronos/assets/12481242/d5dc2130-c93e-4ce8-b25e-2e37a02d203b)

**Comment by BenjaminSiskoo** [comment]
RAMCTL 0x2000
Screen is enabled
Border Color Mode = Black
Display Resolution = 320 x 224(NTSC)
Interlace Mode = Non-Interlace
Latches HV counter when external latch flag is read
During H-Blank
H Counter = 0
V Counter = 244

Line Color Screen Stuff
-----------------------
Mode = Single color
Address = 05E00000

Back Screen Stuff
-----------------
Mode = Single color
Address = 05E7FFFE

Cycle Pattern
-----------------
A0 = EEEEEEEE
A1 = FFFFFFFF
B0 = EEEEEEEE
B1 = FFFFFFFF

Sprite Stuff
------------
Sprite Type = 1
Screen Mode TVM = Normal
VDP1 Framebuffer Data Format = RGB and palette
Erased Area: EWLR 0x0 EWRR 0x7474
  Erase from (0,0) to (319,223)
Sprite Window Enabled
Sprite Gradation Calculation Disabled
Window disabled whole screen
Color RAM Offset = 0
Color RAM Mode = 2
Priority 0 = 5
Priority 1 = 0
Priority 2 = 0
Priority 3 = 0
Priority 4 = 0
Priority 5 = 0
Priority 6 = 0
Priority 7 = 0
Color Offset A Enabled
R = 0, G = 0, B = 0

**Comment by FCare** [comment]
Testé en 2.6.2 - Semble fixé
