### ISSUE TITLE
[Message Navi (Japan)] Etirement vertical de l'écran...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1201]
Kronos Wip du 14.10.2021
Mode CS
Bios intégré / Vrai Bios

![image](https://user-images.githubusercontent.com/12481242/137474275-46ca61f8-5a94-4125-a8a8-08c3bdfc5627.png)

**Comment by fafling** [comment]
Même problème que #1233, #1234 et #702 : zoom vertical incorrect du NBG1 quand il est en mode bitmap et quand le VDP2 est en double interlace.

**Comment by BenjaminSiskoo** [comment]
Corrigé kronos20231216_0a26fe6
