### ISSUE TITLE
[Street Racer] Régression traits horizontaux...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#121]
Kronos 1.2.0 : 

![1streetracer](https://user-images.githubusercontent.com/12481242/37628937-cbabcaa2-2bd3-11e8-99b1-8051bb4c12c4.JPG)

**Comment by FCare** [comment]
Je n'ai pas les traits... Par contre ingame, les ombres des nuages sur le parcours ne semblent pas bonnes...

Voila mes screenshot avec le scanline activé (j'ai desactivé les filtres, tjrs pareil)

![str](https://user-images.githubusercontent.com/14252808/37638113-7a854c74-2c0b-11e8-92b4-1bafe1344c36.png)

![strbad](https://user-images.githubusercontent.com/14252808/37638120-8055e000-2c0b-11e8-993f-7cebdaf47258.png)

**Comment by BenjaminSiskoo** [comment]
En remettant le kronos.ini à zéro plus de problème. Ce jeu a toujours eu un problème d'affichage de la route.
