### ISSUE TITLE
[Shienryuu (Japan)] Affichage sur 3/4 de l'écran (comme Darklight Conflict)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1218]
Kronos Wip du 14.10.2021
Mode CS
Bios intégré / Vrai Bios

Similaire au problème de Darklight Conflict. https://github.com/FCare/Kronos/issues/1036

![image](https://user-images.githubusercontent.com/12481242/137483031-2148edcb-f649-40d2-8b96-2c2f97f14786.png)

**Comment by fafling** [comment]
C'est le mode vertical, normal que l'affichage soit réduit en largeur (le jeu est fait pour un moniteur pivoté à 90°).
Et sinon c'est encore un doublon de #774.
