### ISSUE TITLE
[Blam Machinehead/Athlete Kings]Traits verticaux...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#122]
Kronos 1.2.0 : 

![1blamverttraits](https://user-images.githubusercontent.com/12481242/37629009-2c1c6c48-2bd4-11e8-9e52-7f057508ea90.JPG)

**Comment by FCare** [comment]
Je ne vois pas le pb... Il sont ou les trais verticaux?

**Comment by BenjaminSiskoo** [comment]
Les traits se trouvent surla montagne en arrière plan.

Yaba Sanshiro 1.6.4 : 

![1blam](https://user-images.githubusercontent.com/12481242/37647920-72b214cc-2c25-11e8-99d3-3453ace4245c.JPG)

**Comment by BenjaminSiskoo** [comment]
Athlete Kings, tu as un voile blanc qui forme des traits horizontaux

![1athlerte kings](https://user-images.githubusercontent.com/12481242/37648477-fced5dda-2c26-11e8-8c12-3c1965aaaf8b.JPG)

**Comment by BenjaminSiskoo** [comment]
Bugs introduit entre la version 1.0.0 : https://github.com/FCare/yabause/commit/35b1fef5f4d4e37b138c1b9893361cdef4125b85

et la 1.1.0 : 
https://github.com/FCare/yabause/commit/1f61c1567f8948bc7d5466f059bc6898d4f5becb

**Comment by FCare** [comment]
Est ce que tu le vois sous yaba?

**Comment by BenjaminSiskoo** [comment]
oui bien vu :)

**Comment by BenjaminSiskoo** [comment]
Kronos 21.04.2018 : même problème.

**Comment by FCare** [comment]
Fixed with 412900f263779dbfa360c04f2080f548da3bee0f
