### ISSUE TITLE
[Super Tempo (Japan)] Ecran noir après le bios...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1225]
Kronos Wip du 14.10.2021
Mode CS
Bios intégré / Vrai Bios

**Comment by fafling** [comment]
Toujours présent dans la dernière WIP (pas de changement si on utilise l'interpréteur debug, le cache ou le bio émulé).

Pas de message d'erreur dans DebugView.

Je n'ai pas trouvé de version de Kronos où le jeu démarrait. Le problème remonte à Yabause 0.9.14.

A noter que le jeu démarre dans Yabause 0.9.15.

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

Corrigé avec les fixs sur le timing du 14-15 Décembre 2023
