### ISSUE TITLE
« kronos à cessé de fonctionner »

### ISSUE THREAD

**Issue by Sebariton** [FCare/Kronos#123]
Mon PC est sous Windows10 64bits, j’ai fait la manipulation indiqué par B. Siskoo( C:\Users\tonnom\AppData\Local ) et j’ai supprimé toute entré existante.
Malheureusement cela n’a rien changé, y compris en testant la version 1.2.0, je continue à avoir la même erreur « kronos à cessé de fonctionner » et l’application se ferme.

**Comment by BenjaminSiskoo** [comment]
Hello, 

As tu pensé à mettre un bios ? As tu configuré la sauvegarde (32 Mb Dram) ?

**Comment by Sebariton** [comment]
Bonjour Benjamin,

    Oui je viens même de refaire le test en ne cherchant à modifier que ces 2 parametres là et dès que je clic sur « ok » pour valider mon changement cela plante.

Cordialement,

________________________________
De : BenjaminSiskoo <notifications@github.com>
Envoyé : Wednesday, March 28, 2018 7:33:08 PM
À : FCare/yabause
Cc : Sebariton; Author
Objet : Re: [FCare/yabause] « kronos à cessé de fonctionner » (#123)


Hello,

As tu pensé à mettre un bios ? As tu configuré la sauvegarde (32 Mb Dram) ?

**Comment by BenjaminSiskoo** [comment]
Hello Sebariton, 

- Récupère le bios sur planetemu ou gametronik.
- Supprime tout ce qu'il y a dans kronos.ini. Enregistre le. Puis configure comme sur l'image (Quand je mets Le chemin du bios, il faut que tu mettes ton chemin à toi ^^)

![1kronosavancee](https://user-images.githubusercontent.com/12481242/38163115-f2e42016-34dd-11e8-8271-a01736434736.JPG)
![1kronoscartouche](https://user-images.githubusercontent.com/12481242/38163116-f302b2ec-34dd-11e8-9f9c-eb24e501b603.JPG)
![1kronosgeneral](https://user-images.githubusercontent.com/12481242/38163117-f320ed8e-34dd-11e8-8c5d-06b90a74e3fb.JPG)
![1kronosson](https://user-images.githubusercontent.com/12481242/38163118-f33c7f68-34dd-11e8-85a6-38045c891365.JPG)
![1kronosvideo](https://user-images.githubusercontent.com/12481242/38163119-f35da0e4-34dd-11e8-98e4-594aa4ba3646.JPG)

**Comment by Sebariton** [comment]
Bonjour Benjamin,
   J’ai fait les manipulation que tu liste dans ton dernier mail et j’ai toujours la même erreur. Même s’il arrive bien à réécrire le fichier ini que j’ai vidé comme tu l’a indiqué.
D’ailleur voici ce qu’il arrive à écrire dans le fichier .ini avant de crasher:
[cid:image003.png@01D3C9F1.3A7AE430]

Cordialement,


________________________________
De : BenjaminSiskoo <notifications@github.com>
Envoyé : Saturday, March 31, 2018 2:20:57 PM
À : FCare/yabause
Cc : Sebariton; Author
Objet : Re: [FCare/yabause] « kronos à cessé de fonctionner » (#123)


Hello Sebariton,

Supprime tout ce qu'il y a dans kronos.ini. Enregistre le. Puis configure comme sur l'image (Quand je mets Le chemin du bios, il faut que tu mettes ton chemin à toi ^^)

[1kronosavancee]<https://user-images.githubusercontent.com/12481242/38163115-f2e42016-34dd-11e8-8271-a01736434736.JPG>
[1kronoscartouche]<https://user-images.githubusercontent.com/12481242/38163116-f302b2ec-34dd-11e8-9f9c-eb24e501b603.JPG>
[1kronosgeneral]<https://user-images.githubusercontent.com/12481242/38163117-f320ed8e-34dd-11e8-8c5d-06b90a74e3fb.JPG>
[1kronosson]<https://user-images.githubusercontent.com/12481242/38163118-f33c7f68-34dd-11e8-85a6-38045c891365.JPG>
[1kronosvideo]<https://user-images.githubusercontent.com/12481242/38163119-f35da0e4-34dd-11e8-98e4-594aa4ba3646.JPG>

**Comment by BenjaminSiskoo** [comment]
Hello, 

Bah le coupable c'est peut être ce fichier image003.png, je comprends pas ce qu'il fait dans l'histoire, A aucun moment tu mets en option un fichier .PNG ^^

**Comment by Sebariton** [comment]
Bonjour Benjamin,
      Fichier .png ? Tu parle de la capture d’écran ou bien je dois carrément supprimer les fichiers .ini ?
celui qui est dans :
D:\Emulateurs a tester\Kronos_1.2.0
Et celui qui est dans
C:\Users\Seb\AppData\Local\yabause
?
En parallèle j’ai fait le test avec d’autre version (yaba sanchiro, uoyabause) j’ai beau supprimer les entrés yabause entre chaque test, j’ai le même comportement avec toutes.
Cordialement,

________________________________
De : BenjaminSiskoo <notifications@github.com>
Envoyé : Monday, April 2, 2018 11:33:32 AM
À : FCare/yabause
Cc : Sebariton; Author
Objet : Re: [FCare/yabause] « kronos à cessé de fonctionner » (#123)


Hello,

Bah le coupable c'est peut être ce fichier image003.png, je comprends pas ce qu'il fait dans l'histoire, A aucun moment tu mets en option un fichier .PNG ^^

**Comment by Sebariton** [comment]
Bonjour autant pour moi la capture d'écran (nomé image003.png) n'apparaissait pas proprement:
![capture](https://user-images.githubusercontent.com/37848194/38464636-3ea478b4-3b11-11e8-8e31-c74af49619a4.JPG)

**Comment by BenjaminSiskoo** [comment]
J'ai pas d'autres idées, il faudrait que je puisse prendre la main sur ton pc pour voir si je peux trouver. Sinon, je vois pas, il y a un truc qui gêne surtout que ca le fait avec Yaba/UoYabause. Je suis sûr que c'est pas grave (un mauvais fichier, une mauvaise config, un fichier ini perdu quelque part sur le disque dur...)

**Comment by Sebariton** [comment]
Bonjour,

   Après avoir désinstallé l'émulateur, supprimé toute trace de sa présence sur la machine et dans le registre. Après avoir vérifié l'intégrité de l'installation de mon PC et de ses fichiers, j'ai réinstallé Kronos, lancé plusieurs fois sans réussite, puis il c'est lancé deux fois et de nouveau plus moyen de le faire marcher.
De plus voilà une copie du journal d'erreur:
Description
Chemin d’accès de l’application défaillante :	D:\LaunchBox\Emulators\Kronos\kronos.exe

Signature du problème
Nom d’événement du problème :	BEX
Nom de l’application:	kronos.exe
Version de l’application:	0.0.0.0
Horodatage de l’application:	5aacd698
Nom du module par défaut:	StackHash_2beb
Version du module par défaut:	0.0.0.0
Horodateur du module par défaut:	00000000
Décalage de l’exception:	PCH_B3_FROM_ntdll+0x0006EDDC
Code de l’exception:	c0000005
Données d’exception:	00000008
Version du système:	10.0.16299.2.0.0.768.101
Identificateur de paramètres régionaux:	1036
Information supplémentaire n° 1:	2beb
Information supplémentaire n° 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Information supplémentaire n° 3:	ed23
Information supplémentaire n° 4:	ed23511856962e4185333bee88769064

Informations complémentaires sur le problème
ID de compartiment :	e558283db2dac85193f51a8d9b935c39 (1438084851517578297)

J'avoue en perdre mon latin à moins qu'il ne s'agisse d'un problème de compatibilité 32/64 bits....

**Comment by BenjaminSiskoo** [comment]
Pas de nouvelle, on suppose que c'est bon

**Comment by Sebariton** [comment]
Tout a fait une réinstallation complète de l'O.S. et cela fonctionne.

Cordialement

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by BenjaminSiskoo** [comment]
Super bonne nouvelle :)
