### ISSUE TITLE
[Virtual Mahjong 2 - My Fair Lady (Japan)] Graphismes manquant + rectangle noir...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1234]
Kronos Wip du 14.10.2021
Mode CS
Bios intégré / Vrai Bios

![image](https://user-images.githubusercontent.com/12481242/137488486-b629340b-96a9-40cc-84d9-1d2c2289acc0.png)

![image](https://user-images.githubusercontent.com/12481242/137488530-bb800619-8d55-43a5-8c44-7691436a2496.png)

**Comment by fafling** [comment]
C'est le problème zoom vertical incorrect du NBG1 quand il est en mode bitmap et quand le VDP2 est en double interlace, voir #1233 et #702.

Le bas de l'écran est affiché par le NBG1 et le haut par le NBG0. Dans Kronos, le graphisme du NBG1 se retrouve dans la partie haute de l'écran à cause du zoom incorrect, et il est caché par le NBG0 qui a une priorité plus élevée.

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

Pas réglé mais plus concentré en bas de page : 

![image](https://github.com/FCare/Kronos/assets/12481242/aa1f8390-773d-41dd-b04c-e39f88606e99)

**Comment by fafling** [comment]
Concernant la partie basse de l'écran, le jeu à le même problème que Baroque report #210 :  la résolution verticale est 256. C'est une résolution illégale en NTSC (donc en 60 Hz). La console l'affiche comme si la résolution verticale était 224 au lieu de 256 et la zone sous le copyright n'est pas visible.
![image](https://github.com/FCare/Kronos/assets/7624262/f61f06ad-09b4-4591-9d49-dda6dee3715a)
