### ISSUE TITLE
[Virtual Open Tennis (Europe)] Jeu au ralentie...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1235]
Kronos Wip du 14.10.2021
Mode CS
Bios intégré / Vrai Bios

J'ai testé la version européenne et USA. Le jeu est jouable s'il n'était pas aussi au ralentie. Le compteur de FPS semble ok.

**Comment by fafling** [comment]
Dans les 2 noyaux, le framerate du VDP1 ne dépasse pas 10 fps dans la version US, sur l'écran titre, dans les menus et in game.

![image](https://user-images.githubusercontent.com/7624262/152268539-f50fac14-c45f-4f40-b6eb-05e5b07b8018.png)

La liste de commande du VDP1 comporte environ 500 commandes sur l'écran titre, donc une grande partie skippées.
In game, il y a entre 900 et 1000 commandes, dont une bonne partie skippée.

Sur la console, l'écran titre est anime les sprites en 60 fps en NTSC, 50 en PAL. In game, les sprites bougent à 30 fps en NTSC, 25 en PAL :
- NTSC : [https://www.youtube.com/watch?v=A5dPj5jsGmM](https://www.youtube.com/watch?v=A5dPj5jsGmM)
- PAL : [https://www.youtube.com/watch?v=qK1ObtvUaTg](https://www.youtube.com/watch?v=qK1ObtvUaTg)

Testé avec le CD US d'origine.

**Comment by fafling** [comment]
Je n'ai pas trouvé de version de Kronos sans ce problème, il apparaît dès la 1.0.0.
Il n'existe ni dans Yabause 0.9.14, ni dans uoYabause / YabaSanshiro.

**Comment by BenjaminSiskoo** [comment]
Avec les patchs de janvier 2023, le jeu est jouable, il y a toujours des commandes skipped, j'attends ton retour sur ce sujet @fafling

**Comment by fafling** [comment]
Il n'y a plus de ralentissement dans la WIP du 17/01 (d8aa47b), mais dans les 2 noyaux, le polygone d'effacement n'est plus exécuté et les graphismes s'accumulent à l'écran titre et dans le menu :
![image](https://user-images.githubusercontent.com/7624262/213321955-30241537-8671-47ae-861b-c3e79bc38009.png)
![image](https://user-images.githubusercontent.com/7624262/213322187-2a1086e8-ebd3-4744-bbfb-1cf3da3d27b8.png)

**Comment by FCare** [comment]
le polygon n'efface qu'une petite partie de l'ecran. Il est bien executé.
Par contre, le VBlank Erase n'est aps pris en compte:

FBCR => Write VBE=0 FCM=1 FCT=1 line = 225 (1)
TVMR => Write VBE=1 FCM=1 FCT=1 line = 225
TVMR => Write VBE=0 FCM=1 FCT=1 line = -1
StartField ***** VOUT(T) 0 FCM=1 FCT=1 VBE=0 PTMR=2 (0, 1, 0, 0)*****

**Comment by FCare** [comment]
Fixed in 6b5a7a8dc6407f9a0acd871c4ca4d45d3a5f8224
