### ISSUE TITLE
[X-Men - Children Of The Atom (Europe)] Ecran noir après l'intro Capcom (MSH2 Invalid opcode)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1240]
Kronos Wip du 14.10.2021
Mode CS
Bios intégré / Vrai Bios

**Comment by fafling** [comment]
L'écran noir se produit toujours dans la dernière WIP, dans les 2 noyaux video.
L'interface de Kronos n'est pas bloquée et les compteurs de fps non plus.

Au moment de l'écran noir, DebugView affiche un invalid opcode :

Error: Master SH2 invalid opcode

R0 =  00000600 R12 =  00000000
R1 =  000005A7 R13 =  060F0FFC
R2 =  05A77100 R14 =  00000000
R3 =  00000000 R15 =  060E2450
R4 =  06006CBC SR =   000000F1
R5 =  00000000 GBR =  060FF000
R6 =  00000000 VBR =  06000000
R7 =  00000000 MACH = 00000000
R8 =  05F80000 MACL = 00000000
R9 =  25E02F00 PR =   00000000
R10 = 05E80000 PC =   05A77100
R11 = 060E8000

Quand on regarde dans Mednafen, le jeu alterne les valeurs 0x0 (1-cycle mode) et 0x3 (manual mode (change)) pour le registre FBCR du VDP1. Le blocage de Kronos semble coïncider avec un passage du FBCR de 0x3 à 0x0.

Je n'ai pas trouvé de version de Kronos sans blocage au démarrage de ce jeu.
Pas de changement lors des essais de timings de fin août 2021.
Paramétrer une 2ème manette ne change rien.
Il ne démarrait pas non plus dans Yabause v0.9.14.

Testé avec le CD PAL d'origine. La version jap se comporte de la même manière.

**Comment by fafling** [comment]
Tests réalisés avec la cartouche Dram 32 mbit que le jeu n'utilise pas. Démarrer le jeu sans cartouche ne change rien.

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

![image](https://github.com/FCare/Kronos/assets/12481242/e2156771-874c-4b41-84d1-99524d575ed2)

**Comment by fafling** [comment]
Réglé par [8637f36](https://github.com/FCare/Kronos/commit/8637f36cff6dbbdc45941bfb649156fb8ee9917b)
![image](https://github.com/FCare/Kronos/assets/7624262/b96e9dc0-0597-43d5-80bf-46a8d9db5298)
