### ISSUE TITLE
Régression à corriger

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1257]
- Emulation Saturn : Gotha - Ismailia SenEki (Japan) : Le jeu était jouable.
- ST-V problème avec le reboot. Lance un jeu ST-V. Ferme Kronos. Essaye de le relancer. Tu as la message can't initialize Kronos. Il faut choisir un autre jeu. Et le lancer sans fermer Kronos

**Comment by BenjaminSiskoo** [comment]
- Perte du chemin des isos sur la version Windows, j'ai pas investigué, mais à certains moments quand tu arrête Kronos et que tu le relance, il perds le chemin vers les isos.

**Comment by Tekkenlord-X** [comment]
I do not speak french but I think you are referring to the same issue I just posted when Kronos does not detect the previous configuration you left and you cannot open an STV game, I have not tried with regular Saturn, but I guess is the same.
