### ISSUE TITLE
[Test Island] problème avec le GPU RBG ...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1261]
Kronos 2.2.0
Mode Cs

![image](https://user-images.githubusercontent.com/12481242/137819191-8c44c843-775e-4d5f-8b33-11a3c9fd127f.png)

J'ai ton affichage en RBG CS. si c'est désactivé, le RBG0 cache le NBG1.
Je confirme, affichage correct avec le GPU RBG off :

![image](https://user-images.githubusercontent.com/12481242/137819202-dc585fe4-f9c3-4422-a9b8-92f8f0569282.png)

https://discord.com/channels/531844227655532554/540356852773552135/899685299217633440

**Comment by fafling** [comment]
Le problème apparaît en WIP du 24/09 qui fixe l'affichage des bitmaps en GPU RBG (bien que dans cette démo, le RBG0 utilise une tilemap, pas un bitmap).
Apparemment, le GPU RBG n'affiche pas le 2ème paramètre de rotation ici.
![image](https://user-images.githubusercontent.com/7624262/137819762-351e0636-b852-43e3-98fb-553a4b6b9036.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 10/12/2021
