### ISSUE TITLE
[Koutetsu Reiiki - Steeldom (Japan)] Les persos ne sont pas affichés dans le jeu et souris cachés...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1265]
Kronos 2.2.0
Mode CS

Sur l'écran press start screen on ne voit pas press start screen. Sur l'écran de sélection des persos, ils ne sont pas affichés et il y a des ralentissements.

![image](https://user-images.githubusercontent.com/12481242/140643571-5228d66b-e3fb-40cc-9446-40d338aa7010.png)

**Comment by fafling** [comment]
Faut appeler Garfield pour faire la chasse à la souris ;-)

Les sprites ne s'affichent plus dans les 2 noyaux dans la dernière WIP, ainsi qu'en v2.2.0 publique, et depuis la WIP du 07/10/2021 qui faisait un premier essai de correction, insuffisant, des lettres manquantes dans le ranking de Daytona CCE (voir #1167 ).

Le problème est visible dès l'écran titre où il manque le "Press start" sur les sprites. Les commandes de dessin sont visibles dans l'écran debug du VP1.

Testé avec le CD d'origine jap.

**Comment by BenjaminSiskoo** [comment]
kronos20231122_7fa6739

corrigé
