### ISSUE TITLE
[Kuro no Danshou - The Literary Fragment (Japan) (2M)] Freeze sur la vidéo in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1266]
Kronos 2.2.0
Mode CS

Le jeu freeze quelques instants la vidéo.

Savestate : 

[kuro no danshou - the literreary fragment.zip](https://github.com/FCare/Kronos/files/7504302/kuro.no.danshou.-.the.literreary.fragment.zip)

**Comment by fafling** [comment]
@BenjaminSiskoo Doublon de  #663 .
