### ISSUE TITLE
[Blue skies v0.001.000] Artifact sur le NBG1

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1267]
En v2.2.0 publique, des traits verticaux sont visibles sur la couche NBG1 si on pointe l'avion vers le ciel. Ces artifacts n'apparaîssent pas sur la console.
![image](https://user-images.githubusercontent.com/7624262/141876638-e9a91526-37f1-4462-aebc-dbb68f8c595e.png)

Le NBG1 est un bitmap 16bpp 512x256 basé à 0, il occupe donc toute la VRAM A. Or le registre RAMCTL vaut 0x1327, ce qui donne en binaire : 0001 0011 0010 0111. Les 2 banks de VRAM sont partitionnés, et les partitions A0, A1 et B0 sont exclusivement réservées au RBG0 s'il est actif, ce qui est le cas.
L'accès à la VRAM A est donc impossible pour le NBG1 même si les timings nécessaires sont positionnés dans le registre de cycle pattern.

Image de la démo :
[Blue_Skies.zip](https://github.com/FCare/Kronos/files/7542532/Blue_Skies.zip)

Save state :
[blue_skies_v0.001.000.zip](https://github.com/FCare/Kronos/files/7542536/blue_skies_v0.001.000.zip)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 13/12/2021
