### ISSUE TITLE
[Lost Vikings 2 - Norse by Norsewest (Europe) (En,Fr,De)] Changement de couleur sur les persos...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1270]
Kronos  2.2.0
Mode CS

Par ex à 3'10 : sur les portraits du personnage ou en fin de vidéo.

https://www.youtube.com/watch?v=RPJ6hyIuuJU

**Comment by FCare** [comment]
ressemble a un pb de timing

**Comment by BenjaminSiskoo** [comment]
Kronos 2.3.1
Mode Cs

Avec la savestate c'est mieux : 
[lostvikings2.zip](https://github.com/FCare/Kronos/files/10105772/lostvikings2.zip)

Il faut appuyer sur A pour parler avec le sorcère

**Comment by BenjaminSiskoo** [comment]
Corrigé
