### ISSUE TITLE
Kronos core broken from 1.9.11

### ISSUE THREAD

**Issue by jhdgghost** [FCare/Kronos#1274]
What's the full name of the game (including region) ? All

What's your frontend ? (standalone, libretro, ...) ? Libreto

What's your OS ? (windows, linux, OSX, ...) ? Windows

What's your hardware ? (CPU, GPU, ...) ? Ryzen 5, Gtx 1060

What's the storage type of the game (official cd, burned cd or cd image) ? Cd image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...) chd

Are you using any setting different from default ? If so, precise

Did this game work previously ? Do you remember when ? Is it happening with other games ? The core from 1.9.11 retroarch work perfect the versions after that work a irregular speed the bios speed is very fast and the sound is totally weird. Yesterday i try 1.9.14 with updated core but was the same, so i replaced but the core from 1.9.11 and work again so not seem a problem of retroarch version but a change in the core after that version.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

**Comment by BenjaminSiskoo** [comment]
Try the last core
