### ISSUE TITLE
[Daikoukai Jidai Gaiden (Japan)] ligne de texte qui "double" !!!

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1279]
Kronos 2.2.0 
Mode CS

En lancant la savestate, on arrive sur un écran noir avec du texte en japonais qui va arriver en fondu blanc. Le texte va avoir un comportement bizarre, comme s'il gonflait.

savestate : [T-7657G_000.zip](https://github.com/FCare/Kronos/files/7727071/T-7657G_000.zip)

**Comment by fafling** [comment]
Je ne voit pas du tout ce que tu décris avec ce save state.

**Comment by BenjaminSiskoo** [comment]
@fafling 

En fait ca fait une sorte de zoom

![dai](https://user-images.githubusercontent.com/12481242/146471383-d7e12612-cf69-4be4-8908-8abca568e7df.gif)

**Comment by fafling** [comment]
Effectivement, les caractères apparaissent sur le NBG1, puis ils sont dessiné sur le VDP1 par des normal sprites quand l'effet d'apparition est terminé. C'est au moment du passage sur les sprites qu'ils "grossissent", sûrement un autre exemple des problèmes listés dans le br #1126 .
Sur la console, les caractères ne changent pas au passage du NBG1 vers les sprites. L'affichage est correct en noyau OpenGL.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 13.01.2022
