### ISSUE TITLE
[Doukoku Soshite (J)] Artefact sur le bus...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#128]
Kronos du 25.04.2018 : 

![1doukoku soshite1](https://user-images.githubusercontent.com/12481242/39246079-110a06f4-4885-11e8-9151-72468296d821.JPG)

**Comment by BenjaminSiskoo** [comment]
En désactivant le vdp1, sur la gauche en bas, ca affiche un poteau indicateur. En désactivant, le NBG3 ca supprime l'artefact.

**Comment by BenjaminSiskoo** [comment]
Kronos 1.2.0 avec les fixs de Yaba du 05.05.2018 : 

Le panneau est affiché, il reste juste le bug sur droite.

**Comment by fafling** [comment]
Problème toujours présent dans la WIP du 15/07, en bio réel et émulé. Peut-être que le VDP2 a un cycle pattern qui l'empêche d'afficher le NBG3 sur la console.

Un save state pour accéder plus rapidement à cet écran :
[doukoku_soshite_artefact_bus.zip](https://github.com/FCare/Kronos/files/3494016/doukoku_soshite_artefact_bus.zip)

Testé avec le CD d'origine.

**Comment by fafling** [comment]
Ce problème existait déjà dans Yabause v0.9.14.

**Comment by BenjaminSiskoo** [comment]
Quand on désactive la couche NBG3, l'artefact disparait

**Comment by BenjaminSiskoo** [comment]
Corrigé le 20 Mai 2021
