### ISSUE TITLE
[Gungriffon] RBG0 incorrect en OpenGL

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1281]
Dans la dernière WIP et en v2.2.0 publique, le sol affiché par le RBG0 est incorrect en OpenGL :
![image](https://user-images.githubusercontent.com/7624262/146638929-bbd50707-ed02-4d3d-abc5-7d3757dc9658.png)

Affichage correct en CS :
![image](https://user-images.githubusercontent.com/7624262/146638916-e5277a81-af01-4b7a-be7b-05ed3ec7e7fd.png)

Le problème apparaît en WIP du 29/12/2019.

Testé avec le CD US d'origine.

Save state de la WIP du 17/12/2021 (incompatible avec la version publique) :
[gungriffon_debut_jeu_WIP20211217.zip](https://github.com/FCare/Kronos/files/7739134/gungriffon_debut_jeu_WIP20211217.zip)

**Comment by gridmortis** [comment]
Ground is incorrect using OpenGL and CS using Retroarch.  Any fix yet?  Ty.

**Comment by fafling** [comment]
In Retroarch, launch the game, then press F1 to display the quick menu, click Core options, set RBG compute shaders to ON, press F1 to exit the menu.

When I use the term CS for an RBG layer, it means that RBG compute shaders is enabled.

**Comment by gridmortis** [comment]
Thank you, fafling!!!!  You are awesome!  As a side note, I noticed that "Improved Mesh" must be turned off, or it causes issues with the correct ground textures.  Cheers!

**Comment by BenjaminSiskoo** [comment]
Support OpenGL supprimé
