### ISSUE TITLE
[Master of Monsters - Neo Generations (Japan)] Ecran rouge pendant les transitions d'écrans...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1283]
Kronos 2.2.0
Mode CS

![image](https://user-images.githubusercontent.com/12481242/146751415-fe76a713-072a-455d-bff2-68ab6d1176d4.png)

Savestate : 
[T-6301G_000.zip](https://github.com/FCare/Kronos/files/7744516/T-6301G_000.zip)

**Comment by fafling** [comment]
L'écran rouge est le back screen, on le voit si on désactive toutes les autres couche et il est alors visible en permanence dans Kronos. Il n'apparaît pas sur la console.

Dans Mednafen, si on désactive les autres couches on voit que le back screen disparaît par intermittence, contrairement à Kronos. A ces moments-là, l'affichage debug de Mednafen montre un flag "DON" qui passe brièvement de 1 à 0 dans la colonne des infos du VDP2. Je pense qu'il s'agit du bit DISP du VDP2.

Lorsque DISP est à 0, la couleur affichée est déterminée par le bit BDCLMD, or celui-ci vaut 0 dans ce jeu car on voit toujours du noir dans la zone de bordure sur la console et dans Mednafen, et non du rouge. Kronos devrait donc afficher du noir et non du rouge pour le back screen quand DISP passe à 0 dans ce cas de figure.

Problème apparu en WIP du 03/03/2020, lors du fix de l'ordre entre la color calculation et le color offset #690 .

**Comment by fafling** [comment]
En WIP du 03/01/2022, les écrans rouges sont toujours présents malgré un patch sur la prise en compte du BDCLMD quand l'affichage est désactivé  587d662360d3d8eb7d089cac0db2003fbdfd87c1.
Ce qui est bizarre, c'est que si on regarde l'écran débug du VDP2 au moment de ces écrans rouges, ils n'indiquent pas que l'affichage est désactivé (case Display enabled cochée dans General info) :
![image](https://user-images.githubusercontent.com/7624262/147995876-5b7cd0c7-9b86-4480-bdc5-bbeead2b19f3.png)

**Comment by BenjaminSiskoo** [comment]
Semble corrigé :)
