### ISSUE TITLE
[Burning Rangers] Le jeu freeze avant d'entrer in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1286]
Kronos 2.2.0 du 20.12.2021 (v2)
Mode Cs

Savestate : 
[MK-81803_000.zip](https://github.com/FCare/Kronos/files/7748256/MK-81803_000.zip)

**Comment by fafling** [comment]
Je ne reproduis pas de freeze en WIP du 31/12.

**Comment by BenjaminSiskoo** [comment]
Plus de freze
