### ISSUE TITLE
[Megaman X3 (Europe)] Sprites du perso cassés quand il se déplace...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1288]
Kronos 2.2.0 du 28.12.2021
Mode Cs

![image](https://user-images.githubusercontent.com/12481242/147654994-b9be4e9c-543c-48c1-820a-68fbc6e61c06.png)

Savestate : [T-7029H-50_000.zip](https://github.com/FCare/Kronos/files/7788445/T-7029H-50_000.zip)

**Comment by FCare** [comment]
Deja la en 2.2.0 publique. A voir depuis quand ca deconne

**Comment by fafling** [comment]
Présent dans les 2 noyaux dans la dernière WIP. Apparaît en WIP du 14/01/2021, lors du 1er fix de #982 .

**Comment by fafling** [comment]
Problème déjà signalé auparavant dans #841, avait dû être fixé une 1ère fois après.

**Comment by BenjaminSiskoo** [comment]
Corrigé : kronos20231216_0a26fe6
