### ISSUE TITLE
[Erreur de mémoire] KoF '95 ne démarre plus...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#129]
Le jeu King Of Fighter '95 avec le support de la mémoire étendue, ne fonctionne plus entre la version du 10 Avril 2016 et le 12 Juin 2016 : 

entre cette page là : https://github.com/devmiyax/yabause/commits/master?after=f41eeed5975acc9297ec17790c0cd16287756e53+1504

et là https://github.com/devmiyax/yabause/commits/master?after=f41eeed5975acc9297ec17790c0cd16287756e53+1854

**Comment by barbudreadmon** [comment]
KOF95 nécessite une cartouche de rom spécifique.
KOF96 et KOF97 nécessitent une cartouche de mémoire étendue 1M ou une cartouche action replay plus.

Chez moi les 3 se lancent.
