### ISSUE TITLE
[Megaman X4 (USA)] Le jeu plante après le logo capcom...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1290]
Kronos 2.2.0 du 28.12.2021
Mode CS

Pas de savestate, c'est juste après le logo.

Avec debugview : 

![image](https://user-images.githubusercontent.com/12481242/147655656-b2f2bbd9-657f-4f1c-9fdf-d34c01ff92c1.png)

**Comment by fafling** [comment]
Je ne reproduit pas de plantage.
Par contre, les sprites clignotent dans les 2 noyaux depuis la 1ère WIP du 17/12.
Visible à partir de l'écran titre.

**Comment by BenjaminSiskoo** [comment]
C'est reparti avec la 29.12.2021 et j'ai aussi des scintillements (d'ailleurs ca touche capcom gen 4 ou 5).
