### ISSUE TITLE
[Capcom Gen 5 (Japan) / Megaman X4] Clignotements de l'image...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1291]
Kronos du 29.12.2021
Mode CS

Clignotements présent sur la plupart des écrans.

**Comment by fafling** [comment]
Les sprites clignotent dans les 2 noyaux depuis la 1ère WIP du 17/12.

**Comment by fafling** [comment]
Résolu en WIP du 31/12.
