### ISSUE TITLE
[Asuka 120% Limited (Japan)] Les ombres sont le miroir des personnages au lieu d'être noir...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1295]
Kronos 2.2.0 du 03.01.2022
Mode CS

![image](https://user-images.githubusercontent.com/12481242/147946402-65fe4d54-90ca-476c-9a26-0176b9f89db3.png)

Savestate : 
[T-16708G_000.zip](https://github.com/FCare/Kronos/files/7802577/T-16708G_000.zip)

**Comment by BenjaminSiskoo** [comment]
Cassé depuis la version du 15.12.2021

**Comment by fafling** [comment]
En WIP du 03/01, je n'ai pas la même chose que toi @BenjaminSiskoo :
- L'affichage est correct en CS : le jeu alterne ombre opaque noire et ombre en mesh noire. Il utilise la même technique que J. League Go Go Goal! (voir #957) pour dessiner du noir RGB en utilisant le mode MSB ON du VDP1 et un framebuffer de type RGB+palette côté VDP2.
- Affichage incorrect en OpenGL car les ombres sont noires opaques en permanence :
 ![image](https://user-images.githubusercontent.com/7624262/147993268-81f7b49b-be8a-4951-94b9-e859106e6d11.png)

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 04.01.2022
Mode Cs
Mesh On

C'est avec le mesh mode on que j'ai le soucis.
