### ISSUE TITLE
[Manx TT SuperBike (Europe)] Artefacts sur le côté gauche de l'écran in game (NBG1)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1299]
Kronos 2.2.0 du 05.01.2022
Mode Cs
Option vidéo par défaut

En désactivant le NBG1, l'artefact disparait.

![image](https://user-images.githubusercontent.com/12481242/148362652-843311d4-0105-4915-86b0-e9b9bc4335da.png)

savestate : 
[MK-81210_000.zip](https://github.com/FCare/Kronos/files/7820890/MK-81210_000.zip)

**Comment by fafling** [comment]
Le problème apparaît en WIP du 20/05/2021 avec le fix du décalage vers la gauche des dialogues de Akumajou Dracula X #888.

Le NBG1 dans Manx TT a effectivement des timings de cycle pattern qui ne respectent pas les contraintes de la table 3.4 du mode d'emploi du VDP2 (vérifié dans Mednafen, pattern names en T5 et character patterns en T4 alors qu'elle devraient être entre T1 et T3).
![image](https://user-images.githubusercontent.com/7624262/148468656-d79fcc16-984e-4d9a-8102-3883a23c086e.png)

Il est donc normal que le NBG1 soit décalé vers la droite de 8 pixels. Ce plan ne s'affiche qu'en fin de course, par exemple si on se retrouve à cours de temps. C'est lui qui affiche "Time is up". J'ai vérifié sur la console que sa position était la même que dans Kronos.
![image](https://user-images.githubusercontent.com/7624262/148468613-d3cc41a4-bd93-479f-abc0-3c604574b795.png)

Les artefacts à gauche de l'écran apparaissent donc dans Kronos suite au décalage vers la droite, parce qu'ils se trouvent à gauche de la tilemap du NBG1 dans la vram du VDP2. Mais ce décalage correspond en fait à un retard de lecture des character patterns par le VDP2, et non à un scrolling. Du fait du retard de lecture, le VDP2 utilise sûrement en début de ligne des données de character pattern qu'il a lue en fin de ligne précédente et qui n'ont pas été rafraîchies comme elles auraient dû l'être. Donc les données graphiques à afficher en début de chaque ligne sont en fait celles qui auraient dû être affichées en fin de ligne précédente, donc à droite de l'écran, s'il n'y avait pas eu le retard.

Testé avec la version US qui a le même problème.

**Comment by fafling** [comment]
Save state pour voir le "time is up" (version US) :
[Manx_tt_time_is_up_20220105.zip](https://github.com/FCare/Kronos/files/7825708/Manx_tt_time_is_up_20220105.zip)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 07.01.2022

**Comment by FCare** [comment]
Pas le bon fix

**Comment by fafling** [comment]
Affichage incorrect en WIP du 07/01/2022 :
![image](https://user-images.githubusercontent.com/7624262/148658848-5491a50b-6df6-4713-8d42-9e83c5b049cb.png)

Le NBG1 se retrouve entièrement décalé vers la gauche par rapport à sa position correcte du 05/01, comme avant que le retard dû aux timings incorrects soit pris en compte par Kronos.

@BenjaminSiskoo ou @FCare est-ce que vous pouvez rouvrir ?

**Comment by BenjaminSiskoo** [comment]
@fafling tu peux retester avec la dernière wip ?

**Comment by fafling** [comment]
C'est correct dans la dernière WIP, et apparemment c'était fixé depuis celle du 13/01/2022.

**Comment by BenjaminSiskoo** [comment]
Je ferme
