### ISSUE TITLE
[Normal et Distorted sprite] Problème restant suite au commit du 13.01.2022

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1304]
Kronos du 13.01.2022
Mode CS
Option vidéo par défaut et résolution original en 720p uniquement : 

![image](https://user-images.githubusercontent.com/12481242/149383007-a7689a9c-58d8-4e43-a421-49f84790a165.png)

Savestate : 
[MK-81383_000.zip](https://github.com/FCare/Kronos/files/7864886/MK-81383_000.zip)

**Comment by BenjaminSiskoo** [comment]
https://github.com/FCare/Kronos/issues/1046

Plutot due a un pb de clipping

**Comment by FCare** [comment]
Fixé par 4ae0763a32dd121efd65c806cb7fac06dcf8ef9a
