### ISSUE TITLE
[Shienryu] Sprite incorrecte in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1306]
Kronos du 14.01.2022
Mode Cs

Affichage correcte :

![image](https://user-images.githubusercontent.com/12481242/149502584-bb8d5564-df13-4ccb-a264-ff4878a62c13.png)

Ca ressemble à ca : 

![image](https://user-images.githubusercontent.com/12481242/149502700-c0247ade-00a3-4f89-adfc-e5ae475cbfee.png)

Savestate : 
[T-29102G_000.zip](https://github.com/FCare/Kronos/files/7869773/T-29102G_000.zip)

**Comment by fafling** [comment]
Doublon de #774
