### ISSUE TITLE
[Airs Adventure (Japan)] Transparence trop sombre et décalage de la fenêtre de sélection...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1308]
Kronos 2.2.0 du 14.01.2022
Mode Cs
Option vidéo par défaut

![image](https://user-images.githubusercontent.com/12481242/149601797-154f2d51-9e15-4110-a6fc-f2a4d6372efd.png)

savestate : [T-20701G_000.zip](https://github.com/FCare/Kronos/files/7873926/T-20701G_000.zip)

**Comment by fafling** [comment]
La fenêtre de selection ne disparaît pas quand on désactive toutes les autres couches que le NBG1 qui affiche le décor et les lettre. Celui-ci active la color calculation et le line color screen, mais pas la spécial color calculation. Le color calculation ration de 31:1 ne correspond pas à l'effet ni dans Kronos ni sur la console.
![image](https://user-images.githubusercontent.com/7624262/149602499-ea722ed9-63ec-4976-9ff8-4c1c38ef9970.png)

C'est donc une utilisation de la color calculation window qui délimite la zone de sélection et qui permet de voir le line color screen par semi-transparence, avec un ratio pris sur le 2ème couche, donc sur la line color screen.

On retrouve 2 problèmes connus :
- Décalage d'un pixel dur le côté d'une fenêtre (voir #665 et #764 , et peut-être #1027 )
- Inversion du color calculation ratio quand il est pris sur le line color screen (#628 , #700 et #905 ).

**Comment by BenjaminSiskoo** [comment]
Corrigé le 18.01.2022
