### ISSUE TITLE
[Mortal Kombat 2 (Europe)] Scintillements sur les portraits...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1310]
Kronos 2.2.0 du 14.01.2022
Mode Cs
Option vidéo par défaut

![mortalkombat2](https://user-images.githubusercontent.com/12481242/149620874-08b87af8-672a-40aa-9713-f2263f0a9884.gif)

Savestate : [T-8103H-50_000.zip](https://github.com/FCare/Kronos/files/7874886/T-8103H-50_000.zip)

**Comment by FCare** [comment]
![image](https://user-images.githubusercontent.com/14252808/149958896-26374f3e-3a27-47d8-8967-1841ef2cff23.png)

**Comment by FCare** [comment]
![image](https://user-images.githubusercontent.com/14252808/149959094-01386ec4-8613-466e-9226-b1c6a1ea64a4.png)

**Comment by FCare** [comment]
Probleme de timing

**Comment by BenjaminSiskoo** [comment]
Corrigé
