### ISSUE TITLE
[Dungeons & Dragons - Shadow Over Mystara (Japan)] Régression du 10 Janvier 2022...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1311]
Kronos 14.01.2022
Mode Cs
Option vidéo par défaut

Artefact en bas à gauche (une ligne vertical de plusieurs dizaines de pixel). 

![image](https://user-images.githubusercontent.com/12481242/149749546-067a8fe1-90e0-402e-b5ae-023dec3b7875.png)

savestate : [T-1245G_000.zip](https://github.com/FCare/Kronos/files/7880953/T-1245G_000.zip)

**Comment by FCare** [comment]
Due to Better manage the delay due the VDAM access penalty - Fix #1299 d46d62353b1bc8aef23d5d264ce99e65f8e78d69

**Comment by BenjaminSiskoo** [comment]
Corrigé le 18.01.2022
