### ISSUE TITLE
[Feng Shui Master (Japan)] Problème de sprite ou NBG1...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1313]
Kronos 2.2.0 du 17.01.2022
Mode Cs
Option vidéo par défaut

il y a un doublement de pixel sur les textes.

![image](https://user-images.githubusercontent.com/12481242/149916101-2cec85d4-617c-4d51-a698-3dca111a8c2e.png)

réf : ![image](https://user-images.githubusercontent.com/12481242/149916353-ac6c4956-a385-423e-91f4-69d65cc81ecc.png)
https://www.youtube.com/watch?v=wh7OgZpjiqg

savestate : 
[T-21701G_000.zip](https://github.com/FCare/Kronos/files/7888081/T-21701G_000.zip)

**Comment by FCare** [comment]
c'est du NBG, la couche est dessinée comme ca.... Ensuite, je repete mais la comparaison des erreurs de pixels ne peuvent etre valide qu'en integer scaling.
Ensuite comparer du pixel exact avec youtube, ca ne peut pas etre certain. Youtube compresse les videos.
@fafling utilise un OSSC pour recuperer la sortie de la console. Il n'y a que de l'echantillonnage dans ce cas la.

**Comment by FCare** [comment]
![game](https://user-images.githubusercontent.com/14252808/149946804-9d543bab-68e6-4a05-ae81-8cadba3e4bf4.png)
 La texture d'origine pour comparaison

**Comment by fafling** [comment]
Je confirme que l'affichage de Kronos correspond bien à celui de la console.
