### ISSUE TITLE
[Neon Genesis - Evangelion - Koutetsu no Girlfriend (Japan)] Traits sur le logo..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1314]
Kronos 2.2.0 du 18.01.2022
Mode Cs
Options vidéo par défaut

![image](https://user-images.githubusercontent.com/12481242/149919226-4a161710-1ce3-4fa9-b29a-f4c11cd47d68.png)

savestate : [GS-9194_000.zip](https://github.com/FCare/Kronos/files/7888211/GS-9194_000.zip)

**Comment by FCare** [comment]
le display est off sur cet ecran
