### ISSUE TITLE
[Régression] Entre le 17 et le 18 Janvier 2022...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1319]
Kronos 2.2.0 du 18.01.2022
Mode Cs

Avec le jeu Bug (Europe), le press start screen est noir avec la wip du 18.01.2022 alors qu'avec la wip du 17.01.2022, aucun problème.

savestate : 
[MK-81004_000.zip](https://github.com/FCare/Kronos/files/7925070/MK-81004_000.zip)

**Comment by fafling** [comment]
Se produit dans les 2 noyaux.

Peut-être une régression liée à #1305 : la color calculation est activée sur les sprites qui affichent tout l'écran titre.
![image](https://user-images.githubusercontent.com/7624262/151072306-759182f2-8b19-4986-b835-2d374615e00d.png)

Le jeu n'est pas bloqué et répond aux commandes. On peut aller in game en appuyant sur start 2 fois. L'écran est devenu noir aussi in game. Les sprites et le NBG0 activent la color calculation, mais pas le NBG1 et le RBG0.
![image](https://user-images.githubusercontent.com/7624262/151073114-ef10db16-3c1d-4607-abcd-c5e5620458c8.png)

Save state :
[bug_debut_1er_niveau_20220118.zip](https://github.com/FCare/Kronos/files/7937756/bug_debut_1er_niveau_20220118.zip)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 04.02.2022
