### ISSUE TITLE
Can't run 4MB+ games

### ISSUE THREAD

**Issue by threenator** [FCare/Kronos#1323]
**What's the full name of the game (including region) ?**
All 4MB+ games such as Street Fighter Zero 3, X-Men vs. Street Fighter, and even 1MB games such as King of Fighters 97.

**What's your frontend ? (standalone, libretro, ...) ?**
Standalone.

**What's your OS ? (windows, linux, OSX, ...) ?**
Windows 10

**What's your hardware ? (CPU, GPU, ...) ?**
i7-4790k / Nvidia Geforce 980

**What's the storage type of the game (official cd, burned cd or cd image) ?**
I tried both official CDs and CD images.

**If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)**
I tried ccd/img and cue/bin.

**Are you using any setting different from default ? If so, precise**
No, but I tried several other options such as Dram 32mbit cart, 4MB cart... it didn't work.

**Did this game work previously ? Do you remember when ? Is it happening with other games ?**
no, only games needing expansion ram carts.

**If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this**
It just shows a black screen. Also, sometimes it says "Kronos can't initialize".

**Comment by BenjaminSiskoo** [comment]
We need more info, games ,etc...

**Comment by threenator** [comment]
What? I've written a VERY detailed report and it wasn't posted. Well, editing main post right now.

**Comment by BenjaminSiskoo** [comment]
Try this 👍 

- Clear your kronos.ini (should be blank).
- Launch Kronos
- Setting up your bios path, video options and controller.
- Push ok and wait a bit
- Close Kronos
- And try with these games.

**Comment by fafling** [comment]
In public v2.2.0, the 3 games start with a bios file. Without it, only King of Fighters 97 starts.

@threenator Problems with built in bios won't be fixed except for games that don't work with a bios file.

**Comment by threenator** [comment]
> Try this 👍
> 
> * Clear your kronos.ini (should be blank).
> * Launch Kronos
> * Setting up your bios path, video options and controller.
> * Push ok and wait a bit
> * Close Kronos
> * And try with these games.

Still not working. Even with a BIOS file.

**Comment by threenator** [comment]
> Try this 👍
> 
> * Clear your kronos.ini (should be blank).
> * Launch Kronos
> * Setting up your bios path, video options and controller.
> * Push ok and wait a bit
> * Close Kronos
> * And try with these games.

It worked! Thank you very much!

**Comment by fafling** [comment]
So can we close this issue ?
