### ISSUE TITLE
[Bishoujo Senshi Sailor Moon SuperS - Various Emotion (Japan)] Artefact en haut de l'écran...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1328]
Kronos 2.2.0 du 04.02.2022
Mode Cs
Options vidéo par défaut 

Quand on saute, l'écran monte de quelques pixels et affichent une bande bizarre

![image](https://user-images.githubusercontent.com/12481242/152523582-a2830ead-e0a8-4ee8-a6fe-845c8b5a4de1.png)

Savestate : 
[T-15701G_000.zip](https://github.com/FCare/Kronos/files/8002724/T-15701G_000.zip)

**Comment by fafling** [comment]
C'est pareil sur la console. Le décor est limité en hauteur à la taille de l'écran et quand il scrolle verticalement, on voit le bas du décor qui apparaît en haut de l'écran.
