### ISSUE TITLE
[Koden Koureijutsu - Hyaku Monogatari - Honto ni Atta Kowai Hanashi (Japan)] Texte manquant sur la partie basse de l'écran...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1329]
Kronos 2.2.0 du 04.02.2022
Mode CS
Option vidéo par défaut

![image](https://user-images.githubusercontent.com/12481242/152532172-ad9c3295-ec69-4edc-a889-023c73da3806.png)

savestate : [T-14312G_000.zip](https://github.com/FCare/Kronos/files/8003118/T-14312G_000.zip)

**Comment by fafling** [comment]
Le problème apparaît dans les 2 noyaux à partir du 18/01/2022 avec le dernier fix sur le logo Ving #1305 .
Les texte manquant est affiché par le NBG0, qui active la color calculation (bitmap 8bpp).
Le NBG1, qui affiche le texte du haut, n'a pas ce souci alors qu'il a pratiquement les mêmes caractéristiques que le NBG0.
![image](https://user-images.githubusercontent.com/7624262/152638540-be40d0b7-59e9-4aff-8a4e-688c7cafd8d3.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 11.02.2022
