### ISSUE TITLE
Small issues with the interface

### ISSUE THREAD

**Issue by Felipefpl** [FCare/Kronos#1336]
1 - Yabause has a nice QT theme, for some reason kronos doesnt seem to use the same GUI, instead its GUI reminds me a bit of a windows 98 GUI, the ok/cancel buttons have no "style" or "theme", instead they come with the same color as the GUI. The GUI is a bit slower to change tabs compared to yabause.

2 - I have a 1600x900 resolution (max my monitor supports) and the settings' window looks like this:

![Untitled](https://user-images.githubusercontent.com/5569804/153924254-7d1b4717-9961-4221-8a54-9c9a2e542f2f.gif)

This doesnt happen with yabause. I know i can reduce the size of the GUI but i have to do this every time i open it.

**Comment by fafling** [comment]
Buttons esthetics are a matter of tastes. Personally I like it the way they are.

The settings dialog is indeed taller than it needs to be : all the tabs have a lot of empty space at the bottom.
If you change the dialog size, the new size isn't saved.
The dialog size has increased in the 11 feb 2022 WIP.

**Comment by barbudreadmon** [comment]
Kronos uses a more recent version of QT, and that's probably the reason behind those different looks and the fact it's a bit heavier/slower.

**Comment by Felipefpl** [comment]
Why was this closed if the problem with the GUI being too big/ugly compared to yabause wasnt fixed?

**Comment by FCare** [comment]
It is closed as a won't fix. There is not enough developers working on kronos to take care to the Gui look&feel.
If one developer wants to contribute there, it would be with pleasure that we will merge the submitted changes.

**Comment by Felipefpl** [comment]
I see, ok then.
