### ISSUE TITLE
Freeze after first guy in Puzzle & Action: Treasure Hunt

### ISSUE THREAD

**Issue by riggles1** [FCare/Kronos#1338]
Puzzle & Action: Treasure Hunt as well as Puzzle & Action: Sando-R (International and Japanese ST-V games)
Libretro
Modern PC running Windows 10 64-bit everything runs full speed, no issues there.
This freeze happens consistently.

Dump from the 0.240 MAME set.

Game works great however it will freeze with the music still playing right as you beat the first guy's minigame stages.

The ST-V version was the only one localized into English, there's emulation inaccuracies in MAME for this title, like corrupted graphics and slowdown during the car minigame.
Kronos has no graphics corruptions where MAME has it, but it will always freeze at that point no matter what.

**Comment by fafling** [comment]
That was the behavior in public v2.2.0. Unfortunately, the freeze occurs even before you meet the 1st guy in public v2.3.1.
This earlier freeze appears in the 3 Feb 2022 WIP.
The new behavior matches the freeze of the Saturn port that had always occured earlier (see #515 ).
Just like for the Saturn port, the experimental timings allowed to complete the 1st stage in the st-v version without freeze in the 7 Sept 2021 WIP.
Tested with the japanese version.

**Comment by BenjaminSiskoo** [comment]
Fixed. Will be availalbe to the next release.
