### ISSUE TITLE
Problème de saut de la fréquence d'affichage au démarrage d'un jeu (15kHz - retroarch)

### ISSUE THREAD

**Issue by blc29seb** [FCare/Kronos#1340]
Bonjour 
Je suis entrain de remettre à jour mes émulateurs pour une utilisation sur une borne d'arcade en 15kHz
et avec cet émulateur à travers retroarch j'ai un saut de la fréquence d'affichage au démarrage
Est il possible de le supprimer  ?
Merci 

> What's the full name of the game (including region) ?

Avec tous les jeux
>What's your frontend ? (standalone, libretro, ...) ?

libretro - retroarch avec crt switchres pour un affichage en 15kHz
retroarch 1.9.14  - Kronos v2.3.0
super resolution : 2560 x 224
>What's your OS ? (windows, linux, OSX, ...) ?

Windows 10
>Are you using any setting different from default ? If so, precise

Resolution : original
Output to original resolution : Yes
>If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

photo de la configuration dans retroarch
![config](https://user-images.githubusercontent.com/14741944/155855445-7f0eba4e-8be8-4b02-a227-721ac93c0e62.jpg)

vidéo dans laquelle je lance un jeu stv avec Kronos où l'on peut voir le saut de la fréquence d'affichage au démarrage (8s) et pour 
comparaison je lance un jeu saturn sous Yabuse avec la même résolution mais là il n'y a pas le saut de la fréquence d'affichage 

On dirait qu'au démarrage, l'émulateur passe en 31kHz puis repasse en 15kHz

https://user-images.githubusercontent.com/14741944/155855601-e977aa55-d9aa-4fff-b876-aa7a8396c470.mp4

**Comment by barbudreadmon** [comment]
>On dirait qu'au démarrage, l'émulateur passe en 31kHz puis repasse en 15kHz

Le support de switchres se situe côté retroarch et n'a rien à voir avec nous, il va falloir voir çà avec leur équipe.

>je lance un jeu saturn sous Yabuse avec la même résolution mais là il n'y a pas le saut de la fréquence d'affichage

Autant comparer des pommes avec des melons, yabause fait du software-rendering, kronos du hardware-rendering, switchres ne gère sans doute pas les 2 procédés de la même façon. A noter que dans ta vidéo je vois que tu utilises d3d11, qui est incompatible avec kronos (et avec la plupart des émulateurs faisant du hardware-rendering en fait), ce qui force retroarch a passer sur un driver compatible (glcore) au lancement, tes sauts ne viendraient pas tout simplement de ce switch de driver ?

**Comment by blc29seb** [comment]
Après pas mal de tests et de lecture 
le problème semble venir du mode fullscreen en openGl qui ne fonctionne pas de la même façon que sous d3d 
la solution est de passer en mode fenêtré et là pas de saut de fréquence mais je n'arrive pas à supprimer le menu de la fenêtre
en tout cas c'est bien plus un problème de retroarch que de kronos et ce n'est pas un problème de changement de driver

Au sujet de yabuse vu que c'est un fork de yabuse et qu'il y a écrit partout yabuse dans le code je pensai que ça devait être un peu similaire mais il semble que non ;) désolé de mon ignorance

**Comment by barbudreadmon** [comment]
>Au sujet de yabuse vu que c'est un fork de yabuse et qu'il y a écrit partout yabuse dans le code je pensai que ça devait être un peu similaire mais il semble que non ;) désolé de mon ignorance

Non, il y a de très importantes différences, et elles se situent en grande partie dans la façon dont l'émulateur communique avec la carte graphique, ce qui doit avoir une grosse importance pour des fonctionnalités telles que switchres :).

**Comment by BenjaminSiskoo** [comment]
Je suppose que je ferme, au pire si c'est pas bon, je ré-ouvre.
