### ISSUE TITLE
How can i build Kronos on Windows 10?

### ISSUE THREAD

**Issue by pftmclub** [FCare/Kronos#1341]
I did look up the guide on https://wiki.yabause.org/index.php5?title=Readme_QT
But nothing work after this command:
`cmake -G"MSYS Makefiles" ../yabause/yabause`

I tried to install Cmake for windows , but i don't know how to build it. Can you provide me a guide step by step for that?

**Comment by BenjaminSiskoo** [comment]
You have to get VS 2017, cmake, sdl and Qt
