### ISSUE TITLE
[Virtua fighter] Angle de caméra et positions incorrects dans la boucle de demo

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1345]
Dans la dernière WIP et en v2.3.1 publique, dans les 2 noyaux, il y a les problèmes suivants pendant la 1ère partie de la boucle de démo qui se répète à chaque itération avant le combat de démo :
- Systématiquement, l'angle de caméra est incorrect après que Pai ait donné son coup de pied (à gauche Kronos, à droite la console) :
![image](https://user-images.githubusercontent.com/7624262/158914351-92f0f6ba-bbd5-4d95-a4d4-fcdbc3a4fea2.png)

- à la 2éme itération de la boucle de démo, Kage et Sarah sont trop proches (à gauche Kronos, à droite la console) :
![image](https://user-images.githubusercontent.com/7624262/158915428-73d242dd-dc6f-490f-94c4-b493d995b86b.png)

Video de la démo sur la console : [https://youtu.be/ggjSaSfXN6U?t=21](https://youtu.be/ggjSaSfXN6U?t=21)

Ces problèmes sont peut-être dus à une absence de l'émulation du cache dans Kronos, c'est ce que dit Devmiyax à propos de soucis semblables dans Yabasanshiro : [https://www.uoyabause.org/blogs/57](https://www.uoyabause.org/blogs/57)

Malheureusement, si on active l'option d'utiliser le cache dans Kronos, il n'y a plus d'affichage quand la séquence en 3d démarre (framerate du VDP1 à 0). Il y a un invalid opcode à ce moment-là, qui ne se produit pas si on active pas le cache :
Error: Master SH2 invalid opcode

R0 =  00000000 R12 =  060432C4
R1 =  FFFF4584 R13 =  060426B0
R2 =  0000AF60 R14 =  06091B84
R3 =  00000000 R15 =  06001FE8
R4 =  0604328C SR =   00000001
R5 =  06043288 GBR =  00000000
R6 =  06043874 VBR =  06000000
R7 =  06043884 MACH = 00000000
R8 =  0601F208 MACL = AF600000
R9 =  00000000 PR =   0606BC44
R10 = 060C8000 PC =   0606BC44
R11 = 060D0000

Save state au début de la 2ème itération :
[vf_demo_iteration_2.zip](https://github.com/FCare/Kronos/files/8295613/vf_demo_iteration_2.zip)

Testé avec le CD japonais d'origine.

**Comment by fafling** [comment]
Ces problèmes apparaissent en WIP du 03/02/2022.

**Comment by FCare** [comment]
avec une version du 04/02/2022, je ne reproduis pas le bug.
Elle etait basée sur quoi cette wip?

**Comment by BenjaminSiskoo** [comment]
Regarde https://github.com/FCare/Kronos/issues/1420 c'est très récent

**Comment by BenjaminSiskoo** [comment]
Le post date du 18 Mars sachant que les Wip sont ul après chaque commit ou presque, il doit parler de la dernière wip du 16 Mars : 
![image](https://user-images.githubusercontent.com/12481242/207014990-798df6db-2e0b-4980-9c55-9b05514d45cb.png)

**Comment by FCare** [comment]
le ticket dit que c'est apparu avec la wip du 03/02/2022. Mais en me mettant sur un commit du 4 mars, je ne vois pas le pb sous linux

**Comment by BenjaminSiskoo** [comment]
Avec la wip du 2 Février 2022, pas de soucis
Avec la wip du 3 Février 2022 ca déconne, par contre je sais pas lequel

![image](https://user-images.githubusercontent.com/12481242/207019578-bd03edee-3e26-4994-a490-6f9702a4cf2e.png)

**Comment by FCare** [comment]
moi je ne vois rien sous linux.  Quasimen sur que c'est un des cleanup

**Comment by BenjaminSiskoo** [comment]
@fafling ca semble corrigé tu peux confirmer ?

**Comment by fafling** [comment]
C'est OK en v2.5.0 publique.
