### ISSUE TITLE
Any plan to Support Dynarec x64 and arm64?(android and linux)

### ISSUE THREAD

**Issue by vus7294** [FCare/Kronos#1349]
What's the full name of the game (including region) ?: Any of game includes Daytona USA CE

What's your frontend ? (standalone, libretro, ...) ?: Lakka Libretro

What's your OS ? (windows, linux, OSX, ...) ?: Nintendo Switch and Windows x64

What's your hardware ? (CPU, GPU, ...) ?: i7 2600K + GTX1050Ti and Nintendo Switch

What's the storage type of the game (official cd, burned cd or cd image) ?: CHD image File

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...): CHD and zip

Are you using any setting different from default ?: If so, precise: No.

Did this game work previously ? Do you remember when ? Is it happening with other games ?: So Much Slow on Nintendo Switch

or ST-V 7z support. It really needs to Improve Performance. Thanks.

**Comment by barbudreadmon** [comment]
Kronos already got a cached interpreter, and the bottleneck is most likely the rendering anyway.

**Comment by eadmaster** [comment]
EDIT: related: https://github.com/libretro/yabause/issues/51

**Comment by FCare** [comment]
no plan to support handled devices, android or dynarec.
