### ISSUE TITLE
[Decathlete] Effet de rémanence du framebuffer manquant

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1351]
Dans la dernière WIP comme en v2.3.1 publique, dans les 2 noyaux, il manque l'effet de rémanence du framebuffer qui se produit dans l'épreuve du saut en longueur (long jump) quand les conditions suivantes sont réunies :
- Jauge de vitesse supérieure à 75%.
- Angle de saut entre 24° et 27°.

On peut accéder au long jump directement dans le Practice mode. Utiliser une manette avec une fonction de répétition automatique permet d'avoir la jauge de vitesse à fond sans problème en activant la répétition sur le bouton A.

Sur la console, le framebuffer n'est plus effacé pendant le saut ce qui lui permet d'accumuler les dessins successifs du perso ( [https://youtu.be/gMu0kVzDQjg?t=213](https://youtu.be/gMu0kVzDQjg?t=213) ) :
![image](https://user-images.githubusercontent.com/7624262/164892611-8abdbc69-2666-419e-84a8-5a9ceeb2b653.png)

Affichage dans Kronos :
![image](https://user-images.githubusercontent.com/7624262/164892732-2e70a654-c991-49d5-bdcf-0c6966ddc9a1.png)

Dans ce jeu, la liste de commande du VDP1 ne comporte pas de polygone d'effacement. L'effacement du framebuffer est donc effectué par l'erase/write.
D'après Mednafen :
- Le registre EWLR du VDP1 est toujours à 0x0000.
- Pendant l'effet de rémanence, le registre EWRR est mis à 0x0000 au lieu de 0xB1E0 (valeur curieuse car si on suit les formules de la doc du VDP1, on obtient [1407, 480] pour [X3, Y3], le double de ce qui est nécessaire).

C'est encore un exemple où on voit que Kronos ne respecte pas les coordonnées EWLR et EWRR qui limitent la zone de l'erase/write (voir #1327 et #1072 ).

Save state :
[Decathlete_long_jump_framebuffer_effect.zip](https://github.com/FCare/Kronos/files/8546835/Decathlete_long_jump_framebuffer_effect.zip)

Testé avec le CD US d'origine.

**Comment by BenjaminSiskoo** [comment]
Tu peux retester @fafling ?

**Comment by fafling** [comment]
L'effet est correct en v2.5.0 publique.
