### ISSUE TITLE
[Ponut64 demo] Freeze au démarrage

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1355]
En v2.3.1 publique et dans la dernière WIP, dans les 2 noyaux, le jeu bloque tout seul juste après le changement d'angle de caméra automatique au démarrage. Le framerate du VDP1 tombe à 0, l'IHM de Kronos continue de répondre.

![image](https://user-images.githubusercontent.com/7624262/167229876-a6224ffc-34c6-41fd-a3e0-435c60fe92bc.png)

Le problème apparaît en WIP du 03/02/2022.

L'ISO est dans le br #701 .

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

Ok

**Comment by fafling** [comment]
Fixé depuis la WIP du 14/02/2023 (747ad60).
