### ISSUE TITLE
[Hyper duel] Les sprites ne s'affichent pas

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1356]
Les sprites ne s'affichent plus dans les 2 noyaux dans la dernière WIP, ainsi qu'en v2.3.1 publique. Le framerate du VDP1 reste à 0. Une frame de sprites peut apparaître aléatoirement et reste figée. Le jeu répond aux commandes.

Les sprites commencent à disparaître dans la WIP du 07/10/2021. C'est la même où les sprites disparaissent dans Steeldom, voir #1265 .

Le problème est visible dès l'écran titre où il manque le "Press start" et le titre "Hyper duel". 

Si la back up ram interne est pleine et que le jeu n'a pas la place créer sa sauvegarde, on a l'impression d'un écran noir après le logo Sega car le message d'erreur est affiché sur les sprites. Il faut appuyer sur A ou C pour le passer :
![image](https://user-images.githubusercontent.com/7624262/167273253-41ecd917-9ce2-4f42-9ddb-3199c9bb9377.png)

Les commandes de dessin sont visibles dans l'écran debug du VDP1.

Pas de message dans DebugView.

Testé avec le CD d'origine jap.

**Comment by BenjaminSiskoo** [comment]
Jeu touché : 

- Blast Wind
- Steeldom

**Comment by fafling** [comment]
Le problème apparaît effectivement aussi dans Blast wind en WIP du 07/10/2021.

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

![image](https://github.com/FCare/Kronos/assets/12481242/104acdae-e282-4412-89de-94750298a103)

**Comment by BenjaminSiskoo** [comment]
Corrigé
