### ISSUE TITLE
error: invalid use of incomplete type 'class QButtonGroup' & 'QValidator'

### ISSUE THREAD

**Issue by cyberconan** [FCare/Kronos#136]
Hi!
Maybe the problem is with new QT 5.11 but if you have this error with compilation you can solved adding this includes lines in this files:
UICheatRaw.h
  #include  < QButtonGroup>
UIHexInput.h
 #include  < QValidator>
Regards!

**Comment by FCare** [comment]
Thanks for the fix :-)

**Comment by BenjaminSiskoo** [comment]
Hello @cyberconan 

What is your setup ? Linux or Windows.

With windows I can compile without any problem. But after launching kronos, I changed some settings, and kronos close itself.

**Comment by cyberconan** [comment]
Hi BenjaminSiskoo

I have linux, and yes, when i change some settings kronos crash

**Comment by cyberconan** [comment]
To solved this you can change in qt/CMakeLists.txt 
find_package(Qt5 COMPONENTS Widgets QUIET)
to
find_package(Qt5Widgets)

**Comment by BenjaminSiskoo** [comment]
:) 

I followed your instruction, but Qt5Multimedia and Qt5OpenGL disappeared from cmake ^^

**Comment by cyberconan** [comment]
Mmm, but this dependences are in the same file... I paste here how I have first 23 lines in qt CMAkeLists.txt, maybe your cmake don't detect QT5 well?

    project( kronos-qt )

    yab_port_start()

    option(YAB_USE_QT5 "Use Qt 5 if available." ON)

        find_package(Qt5Widgets)

    if(Qt5_FOUND) 
        message(STATUS "Qt5 Found")

        if( YAB_WANT_OPENGL )
                find_package(Qt5OpenGL)
        endif()

        include_directories(${Qt5Widgets_INCLUDE_DIRS})
        add_definitions(${Qt5Widgets_DEFINITIONS}) 

        if (WIN32)
                find_package(Qt5Core)
        endif()
        find_package(Qt5Multimedia REQUIRED)
        add_definitions(-DHAVE_QT_MULTIMEDIA=1)

**Comment by BenjaminSiskoo** [comment]
I forget to say, I'm with the windows port not linux :)

**Comment by cyberconan** [comment]
Sorry BenjaminSiskoo, I can't help you with windows compilation, but I think there are many more users than can help you than to linux ones :)

**Comment by BenjaminSiskoo** [comment]
Ok @cyberconan ok no problem thanks
