### ISSUE TITLE
[Fighters megamix] Effet de rémanence du framebuffer manquant

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1363]
Dans la dernière WIP et en v2.3.1 publique, dans les 2 noyaux, il manque un effet de rémanence sur le perso quand on entre son nom à la fin d'une course.

Affichage dans Kronos (il y a 2 champs mélangés car le jeu est en double interlace, mais il ne s'agit pas de l'effet de rémanence) :
![image](https://user-images.githubusercontent.com/7624262/174445156-238a9c38-67d5-4438-ab66-413020626942.png)

Affichage sur la console à la fin du même mouvement (la rémanence est visible au niveau des bras, ce n'est pas un artefact video) [https://youtu.be/a3LWNuRo_1M?t=1075](https://youtu.be/a3LWNuRo_1M?t=1075) :
![image](https://user-images.githubusercontent.com/7624262/174445207-77e6a1d8-6417-4858-9335-7171f009c683.png)

Au début de la liste de commandes du VDP1, il y a un polygone noir dessiné avec la half-transparency, qui assombrit la zone où le perso est dessiné. Il sert assombrir les images précédentes du perso qui n'ont pas été effacées dans le framebuffer. Le problème est que Kronos les a effacées, le polygone est donc sans effet.
![image](https://user-images.githubusercontent.com/7624262/174445446-aa37e7b0-38d1-4a46-8c4a-eddd025f848e.png)

Testé avec le CD d'origine US.

Save state :
[fighters_megamix_entree_nom_fin_course_20220410.zip](https://github.com/FCare/Kronos/files/8933869/fighters_megamix_entree_nom_fin_course_20220410.zip)

**Comment by fafling** [comment]
Dans Mednafen, à ce moment du jeu :
- Les registres TVMR et FBCR sont à 0, le VDP1 est donc en one-cycle mode avec des framebuffers normal 16bpp.
- Les registres EWLR et EWLR sont à 0. D'après la doc du VDP1, on est dans le cas X1 >= X3 décrit en haut de la p. 49 (ils valent tous les deux 0). Donc d'apès les formules de la doc, l'erase/write doit se faire seulement dans la zone entre [0, 0] et [7, 0], soit sur 8 pixels dans le coin en haut à gauche de l'écran. Cela n'efface jamais le perso dessiné au centre.

C'est donc encore un cas de non respect des coordonnées de l'erase/write, voir #1351, #1327, #1072 et #90.

**Comment by BenjaminSiskoo** [comment]
@fafling ca a corrigé decathlete peut être celui là aussi ?

**Comment by fafling** [comment]
Non, il n'y a toujours pas l'effet de rémanence en v2.5.0 publique.

J'ai refait le save state, car l'ancien ne fonctionne plus :
[fighters_megamix_entree_nom_fin_course_v2.5.0.zip](https://github.com/FCare/Kronos/files/10737627/fighters_megamix_entree_nom_fin_course_v2.5.0.zip)

**Comment by fafling** [comment]
En WIP du 17/12/2023, l'effet est toujours manquant.

Les coordonnées de l'erase/write ont été ajoutées dans l'écran debug du VDP2, mais la valeur de EWRR 0x7474 est fausse :
![image](https://github.com/FCare/Kronos/assets/7624262/90d6c774-1165-4642-bed6-2b9f2038e840)

Les valeurs en-dessous "Erase from" sont correctes en terme de conversion des registres, mais ne correspondent pas à la zone qui doit être effacée, entre [0, 0] et [7, 0].

Save state mis à jour, l'ancien ne fonctionne plus :
[fighters_megamix_entree_nom_fin_course_20231217_6.zip](https://github.com/FCare/Kronos/files/13705743/fighters_megamix_entree_nom_fin_course_20231217_6.zip)

**Comment by fafling** [comment]
Fixé par [341106d](https://github.com/FCare/Kronos/commit/341106d270c4ca32714fe4b8a8bce5930f44cf38)
Le framebuffer n'était pas effacé par l'erase/write. C'était le blending du polygone en half-transparency qui ne fonctionnait pas avec les pixels du framebuffer après le switch.
