### ISSUE TITLE
[Layer section II] Cache manquant sur les côtés de l'écran

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1364]
Dans la dernière WIP et en v2.3.1 publique, dans les 2 noyaux, l'affichage des sprites est tronqué sur les côtés de l'écran par rapport à l'arrière-plan du VDP2.

C'est visible dès l'intro, où on voit la galaxie puis la Terre sur 2 bandes verticales sur les côtés où les sprites sont absents (ici en bas à droite) :
![image](https://user-images.githubusercontent.com/7624262/174491901-4bb905c9-7deb-47a6-a3e0-88b13394635e.png)

C'est plus flagrant dans la demo et in game, où les immeubles sont tronqués par rapport au sol :
![image](https://user-images.githubusercontent.com/7624262/174492001-d3ed54b8-5681-429d-a2d8-91f7396a2897.png)

Affichage sur la console :
![image](https://user-images.githubusercontent.com/7624262/174493630-a2707a1f-0bef-4e36-a251-b3dc77959246.png)

La résolution du VDP2 est 352 x 224.
Le VDP1 utilise un user clipping moins large de 16 pixels de chaque côté et toutes les commandes de dessin ont le user clipping activé :
![image](https://user-images.githubusercontent.com/7624262/174495900-73d13577-95c5-4aa5-b223-6bdb6b496f43.png)

Dans Mednafen :
- On voit qu'il y a 2 bandes noires sur les côtés sur la couche des sprites. Elles sont même déjà présentes sur le logo Mediaquest au lancement du jeu.
- Le TVMR est à 8, donc le framebuffer est normal 16bpp, et le vblank erase est utilisé.
- Le registre EWLR est à 0x0400, donc [X1, Y1] vaut [16, 0].
- Le registre EWRR est à 0x54DF, donc [X3, Y3] vaut [335, 224].

Les bandes de 16 pixels sur les côtés de la zone visible des framebuffers ne sont donc pas effacées, ni par le vblank erase, ni par le polygone d'effacement du VDP1. Elles sont sans doute remplies de noir au début du jeu. Je n'ai pas vu de liste de commandes correspondant à ça, donc c'est peut-être fait par les CPU.

C'est donc encore un cas de non respect des coordonnées de l'erase/write, voir #1363, #1351, #1327, #1072 et #90.

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Corrigé avec Kronos 2.5.0 (branche test sync, fbaccess)
