### ISSUE TITLE
[PGA Tour 97 (Europe)] Ecran noir après le press start screen + Message Decode instructions from unexpected area...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1366]
Kronos 2.3.1

Concerne aussi la version Japonaise.

**Comment by fafling** [comment]
Concerne aussi la version US.

Se produit en v2.3.1 publique et dans la dernière WIP, dans les 2 noyaux.

Quand on appuie sur start à l'écran titre, l'interface de Kronos se bloque (il faut le killer) et on voit des invalid opcodes en série dans DebugView :
```
Error: Master SH2 invalid opcode

R0 =  00000000 R12 =  060BF64A
R1 =  05E30600 R13 =  00000000
R2 =  060BFB2C R14 =  060FFF88
R3 =  00000004 R15 =  060FFF88
R4 =  0000000B SR =   00000001
R5 =  06071E90 GBR =  00000000
R6 =  00000282 VBR =  06000000
R7 =  06082A9F MACH = 00025E60
R8 =  00000001 MACL = 00000108
R9 =  060BFB24 PR =   0607CAE8
R10 = 00000000 PC =   05E30600
R11 = 060BF648
```

Ce comportement existait déjà dans la plupart des versions de Kronos, même celles dans lesquelles le jeux affichait des écrans noirs.
Le jeu ne fonctionne pas dans Yabause ni dans Yaba Sanshiro.

Testé avec le CD US d'origine.

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

![image](https://github.com/FCare/Kronos/assets/12481242/f173ff7f-a75d-464f-b78d-cd0ba129ed3a)

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

![image](https://github.com/FCare/Kronos/assets/12481242/7a0fd3da-3c78-4c45-bdd9-b1edab08eab9)

**Comment by fafling** [comment]
Un breakpoint de code sur 0x0007D620 (2 instructions avant le PR de l'invalid opcode) montre bien un appel de fonction vers du code en VDP2 VRAM en 0x05E40078.

Cet emplacement de la VDP2 VRAM contient bien du code valide :
![image](https://github.com/FCare/Kronos/assets/7624262/38a429ce-6cb7-4afa-9f62-c9f236027418)

Il faudrait autoriser l'exécution de code à partir de cette VRAM.

Testé avec le CD US qui a le même comportement que la version PAL.

**Comment by fafling** [comment]
Fixé par 6eb3c96
