### ISSUE TITLE
[Arcade's Greatest Hits (USA)] Ecran noir après avoir sélectionné un jeu dans le menu...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1379]
Kronos 2.3.1
Cs

**Comment by fafling** [comment]
Il s'agit de Midway Presents Arcade's Greatest Hits (l'image redump a tronqué le nom).

Se produit dans les 2 noyaux en v2.3.1 publique et dans la dernière WIP.
Pas de message dans DebugView au moment de l'écran noir.

Le framerate du VDP1 ne change pas au moment de l'écran noir.
L'IHM de Kronos n'es pas bloquée.
Le jeu ne répond à aucune commande.

Je n'ai pas trouvé de version de Kronos sans ce blocage à la sélection du jeu. C'est un vieux problème qui existe déjà dans Yabause 0.9.14.

 Il ne fonctionnait pas mieux lors des expérimentation de timing en septembre 2021. 

Save state sur le menu :
[Midway_Presents_Arcades_Greatest_Hits_menu_v2.3.1.zip](https://github.com/FCare/Kronos/files/9794288/Midway_Presents_Arcades_Greatest_Hits_menu_v2.3.1.zip)

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

Corrigé
