### ISSUE TITLE
[Digital Pinball] Les touches ne fonctionnent plus

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#138]
Ce jeu fonctionnait correctement sur la vers 1.2.0 de Kronos, depuis les touches ne répondent plus.

**Comment by dukeblooders** [comment]
Je confirme, impossible de presser Start pour passer la cinématique ou même commencer le jeu.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 15/01/2020
