### ISSUE TITLE
[Arthur to Astaroth no Nazo Makaimura - Incredible Toons (Japan)]  Les mots press start screen sont coupé en haut...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1380]
Kronos 2.3.1
Cs

![image](https://user-images.githubusercontent.com/12481242/194836324-b9f86460-b0dc-4720-850a-bcaba42e5f43.png)

**Comment by fafling** [comment]
Présent dans la dernière WIP, seulement en CS.

Le "press start button" est sur les sprites. Commande de dessin :
![image](https://user-images.githubusercontent.com/7624262/200196381-28553e8d-781e-41d2-814a-c2e081525c09.png)

Le seul truc spécial c'est l'inversion verticale de la texture.
Peut-être lié au problème restant sur les sprites sans scaling, qui concerne une inversion horizontale de texture, voir #1126 .

Save state :
[incredible_toons_ecran_titre_v2.3.1_20221105.zip](https://github.com/FCare/Kronos/files/9946900/incredible_toons_ecran_titre_v2.3.1_20221105.zip)

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Corrigé
