### ISSUE TITLE
[Blast Wind (Japan)] Sprites manquant...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1383]
Kronos 2.3.1
Cs

![image](https://user-images.githubusercontent.com/12481242/194845176-2023a50c-5979-4ab1-8880-2d03bad63dd1.png)

savestate : 
[blastwind.zip](https://github.com/FCare/Kronos/files/9745143/blastwind.zip)

**Comment by fafling** [comment]
Déjà signalé dans #1356
