### ISSUE TITLE
[BrainDead 13 (USA)] Ecran noir après le bios...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1385]
Kronos 2.3.1
Cs

**Comment by fafling** [comment]
Se produit dans les 2 noyaux en v2.3.1 publique et dans la dernière WIP.
Pas de message dans DebugView au moment de l'écran noir.
Le framerate du VDP1 tombe à 0.
L'IHM de Kronos n'es pas bloquée.
Le jeu ne répond à aucune commande.

Apparaît en WIP du 03/02/2022.

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.3.1 du 14.11.2022
Cs

Le jeu démarre, après avoir presser start sur le press start screen, une vidéo s'affiche et semble tourner en boucle.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 09.01.2023
