### ISSUE TITLE
[Koutetsu Reiiki - Steeldom (Japan) (2M)] Characters are not displayed in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1394]
Kronos 2.3.1
Cs

![image](https://user-images.githubusercontent.com/12481242/195297894-bd472d9a-b2fe-47cd-856b-3ae16174b05a.png)

savestate : 
[koutseki.zip](https://github.com/FCare/Kronos/files/9763292/koutseki.zip)

**Comment by fafling** [comment]
Doublon de #1265
