### ISSUE TITLE
[Metal Slug - Super Vehicle-001 (Japan)] Régression 2.2.0 --> 2.3.1 : Ecran noir in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1397]
Kronos 2.3.1
CS

**Comment by fafling** [comment]
Se produit dans les 2 noyaux, en v2.3.1 publique et dans la dernière WIP.
Apparaît en même temps avec le même type de blocage que #1357 le 03/02/2022.
Testé avec le CD d'origine.

**Comment by FCare** [comment]
patch en cause: 13461842295244a49105ebfd34b72865d96f666a

Auteur: Francois CARON <francois.caron@renault.com>  2022-02-03 10:46:45
Suit: Move-to-new-travis
Précède: 2.3.1_official_release

    Reduce the full rendering loop to minimum since it is executed more than 240000 times per second when running PAL at 240 lines

**Comment by BenjaminSiskoo** [comment]
Corrigé le 11.01.2023
