### ISSUE TITLE
[Samurai Spirits - Amakusa Kourin (Japan) (En,Ja,Es,Pt)] Traits verticaux sur les personnages...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1399]
Kronos 2.3.1
Cs

![image](https://user-images.githubusercontent.com/12481242/195729414-3c14916b-fdb8-4eb8-bd2b-f677f301c119.png)

savestate : 
[samuraispirits.zip](https://github.com/FCare/Kronos/files/9781250/samuraispirits.zip)

**Comment by fafling** [comment]
Se produit dans les 2 noyaux en v2.3.1 publique et dans la dernière WIP. 

Même problème que dans fire pro gaiden blazing tornado sur les scaled sprites inversés horizontalement par les coordonnées de dessin (xc < xa), voir [https://github.com/FCare/Kronos/issues/1126#issuecomment-1041455747](https://github.com/FCare/Kronos/issues/1126#issuecomment-1041455747)

Une des commande de dessin utilisées pour le perso de droite :
![image](https://user-images.githubusercontent.com/7624262/196029793-e68173d3-0aaf-440e-b3c3-56f5c2a8fa6a.png)

Save state :
[Samurai_Spirits_Amakusa_Kourin_traits_verticaux_v2.3.1.zip](https://github.com/FCare/Kronos/files/9794161/Samurai_Spirits_Amakusa_Kourin_traits_verticaux_v2.3.1.zip)

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Corrigé via la branche fb access
