### ISSUE TITLE
[Fire Pro Gaiden Blazing Tornado] Problème graphique avec les spots...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#14]
UoYabause 0.5.6 : sur la première photo prise à avec mednaffen aucun soucis.

![blazing tornado](https://user-images.githubusercontent.com/12481242/32175609-b968e49a-bd85-11e7-9ccd-664cfefbc046.JPG)

Avec UoYabause :

![ss_blazing_dragon](https://user-images.githubusercontent.com/12481242/32175627-c3bd7ee2-bd85-11e7-9cfa-6929541ab05b.JPG)

**Comment by BenjaminSiskoo** [comment]
Kronos WIP du 05/10/2019 : 

L'affichage est presque bon pendant le balayage des spots l'écran devrait être noir avec seulement les spots allumés.

![firepro](https://user-images.githubusercontent.com/12481242/66252587-bcfa3600-e75d-11e9-8b13-bd9a7d7ae6b9.PNG)

Savestate : 
[fireprolights.zip](https://github.com/FCare/Kronos/files/3693024/fireprolights.zip)

**Comment by fafling** [comment]
En WIP accurate_vdp1 du 11/10, on ne voit pas les spots. Il s'agit de l'écran de chargement après la sélection du perso.
![Capture_blazing_tornado_4_acc_vdp1_20191011](https://user-images.githubusercontent.com/7624262/66689744-768c6600-ec8c-11e9-89a3-a44e52d93dc3.PNG)

La sprite window est activée sur le NBG1 qui est noir. La sprite window le rend transparent aux emplacement des spots. Elle est effectivement active car le framebuffer est palette only.
![Capture_blazing_tornado_3_acc_vdp1_20191011](https://user-images.githubusercontent.com/7624262/66689772-a0458d00-ec8c-11e9-93c3-cc93e37a5894.PNG)

La sprite window correspond à tous les pixels des sprites dont le MSB vaut 1. Ils sont dessinés par 2 types de commandes :

- Des sprites avec une color bank dont le MSB vaut 1 :
![Capture_blazing_tornado_5_acc_vdp1_20191011](https://user-images.githubusercontent.com/7624262/66689919-6de85f80-ec8d-11e9-9d1f-4a325eec8fc7.PNG)

- Des polygones qui utilisent le mode MSB on :
![Capture_blazing_tornado_6_acc_vdp1_20191011](https://user-images.githubusercontent.com/7624262/66689922-76409a80-ec8d-11e9-8acc-04665f26fa50.PNG)

**Comment by fafling** [comment]
En WIP accurate_vdp1 du 12/10, la zone de transparence du NBG1 est l'inverse de ce qu'elle est sur la console :
![Capture_blazing_tornado_acc_vdp1_20191012](https://user-images.githubusercontent.com/7624262/66699644-006a1c80-ece9-11e9-85db-260fa2e0c621.PNG)

**Comment by fafling** [comment]
Toujours présent en WIP du 08/12 dans les 2 noyaux.

**Comment by BenjaminSiskoo** [comment]
Pareil wip 15/01/2020

**Comment by fafling** [comment]
Toujours présent en WIP du 22/03 dans les 2 noyaux.

**Comment by fafling** [comment]
L'affichage est correct dans les 2 noyaux en WIP du 15/12/2021.

**Comment by BenjaminSiskoo** [comment]
Au revoir petit bug : corrigé le 15.12.2021
