### ISSUE TITLE
[Linux] Are there binaries available? (e.g. rpm, deb...)

### ISSUE THREAD

**Issue by Weej1** [FCare/Kronos#140]
Hi 
Hope you are well! Do  you have binaries for Linux available Or is Kronos only for Windows?

**Comment by FCare** [comment]
Hi, today there is no .deb or .rpm provided.
Linux is supported but you have to compiled it (qt or cli version). Windows only have a qt version

**Comment by Weej1** [comment]
Thanks @FCare ! Are there any step by step build instructions for Linux?

**Comment by FCare** [comment]
no, it is not documented but it shall be the same than yabause or uoyabause.
cmake ../yabause
then make -j5 and it should build the qt version.

You need libsdl2, openGLES3 support, QT5, qt-multimedia and I think that's all.

**Comment by Weej1** [comment]
Thanks again @FCare. Sadly when loading bin/cue of one of my games (Black Matrix) I get error message `Aborted (Core Dumped)` and emulator exits.  

For anyone else coming here to run Kronos on Linux - The instructions Fcare has given is correct. I installed this on elementaryOS Loki (which is based off Ubuntu 16.04 so it should work for *buntu based distros too). 

1. The dependencies you'll need to install first:  `libsdl2, openGLES3 support, QT5, qt-multimedia,  libxmu-dev libxi-dev`

2. Wherever you place the source code, make sure you're IN the `yabause` directory first before building, (in my case it was `~/Downloads/yabause-extui-align/yabause` ) 

3. Run `cmake ../yabause`

4. Run `make -j5`

5. If build has gone successfully, you will have a file called `kronos` in your `qt` directory (in my case it was `~/Downloads/yabause-extui-align/yabause/src/qt` )

This got me to the GUI but it crashed on loading up my game. But at least you get this far:
 
![screenshot from 2018-07-04 03-24-11](https://user-images.githubusercontent.com/6381159/42246394-06c1865e-7f3a-11e8-9b2d-24549ddd0a8c.png)

I guess this answers the question though so maybe best I close this.
