### ISSUE TITLE
[Sega Ages - After Burner II (Japan)] Scintillements sur le porte avion...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1400]
Kronos 2.3.1
Cs

![afterburner](https://user-images.githubusercontent.com/12481242/195823211-bd50d52a-5426-4490-9757-af65488d0444.gif)

**Comment by fafling** [comment]
Se produit en v2.3.1 publique et dans la dernière WIP, dans le 2 noyaux.

Une des commandes de dessin du porte-avion :
![image](https://user-images.githubusercontent.com/7624262/196029119-98bb8d1c-d086-4bea-8285-544e5af63f9d.png)

Save state correspondant au screenshot de Benjamin :
[afterburner_clignotement_porte_avion_v2.3.1.zip](https://github.com/FCare/Kronos/files/9794121/afterburner_clignotement_porte_avion_v2.3.1.zip)

Apparaît en WIP du 05/01/2022.

Testé avec le CD d'origine.

**Comment by FCare** [comment]
===== CMD =====
CMDCTRL = 0x1
CMDLINK = 0x0
CMDPMOD = 0x1808
CMDCOLR = 0x88c
CMDSRCA = 0x487c
CMDSIZE = 0x400
CMDXA = 0xd9
CMDYA = 0x1de
CMDXB = 0x0
CMDYB = 0x0
CMDXC = 0x108
CMDYC = 0x1df
CMDXD = 0x3c
CMDYD = 0x10
CMDGRDA = 0x0
incorrect 1299
Null size w=32 h=0

**Comment by FCare** [comment]
due to SCU DMA which is too fast.
