### ISSUE TITLE
[Solo Crisis (Japan) (1M)] Ecran incorrect sur l'écran du logo...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1402]
Kronos 2.3.1
Cs

![image](https://user-images.githubusercontent.com/12481242/195844851-6ea386f0-1d0a-4297-bc34-c09528bfa395.png)

**Comment by fafling** [comment]
Se produit en v2.3.1 publique et dans la dernière WIP, dans le 2 noyaux.

L'image est sur le NBG1. Les couleurs incorrectes peuvent varier en fonction des tests. L'image est correcte dans le visualiseur :
![image](https://user-images.githubusercontent.com/7624262/196028381-67b325ee-5157-4de2-8a3d-2d0eb9118c9e.png)

Se produit aussi à l'écran titre sur le NBG0 :
![image](https://user-images.githubusercontent.com/7624262/196028479-4c0326eb-923f-49cf-916f-b282b41fd9d8.png)

Problème sans doute identique à #1404, apparaît aussi en WIP du 03/02/2022.

Testé avec le CD d'origine.

**Comment by FCare** [comment]
PAs de soucis chez moi:
![image](https://user-images.githubusercontent.com/14252808/200074804-c32392ef-db10-45e2-92cd-47119f69e304.png)

**Comment by fafling** [comment]
Save state au 1er logo :
[Solo_crisis_logo_v2.3.1_20221105.zip](https://github.com/FCare/Kronos/files/9946622/Solo_crisis_logo_v2.3.1_20221105.zip)

De même que dans Shining wisdom, le chargement de la save state donne des couleurs correctes alors qu'elles ne l'étaient pas lors de sa création. Suite à un chargement de cette save state, l'écran titre a aussi des couleurs correctes.

**Comment by BenjaminSiskoo** [comment]
Corrigé depuis ce commit : https://github.com/FCare/Kronos/commit/42a127fffb3d1ebcda08ce7db37ed713ca4c06f7

**Comment by fafling** [comment]
En fait c'est déjà fixé dans le commit juste avant, 8328b5e. C'est soit lui, soit le précédent f14540b.
