### ISSUE TITLE
[Shining wisdom] Ecran noir après l'écran titre

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1403]
En v2.3.1 publique et dans la dernière WIP, dans le 2 noyaux, il y a un écran noir quand on appuie sur start pour passer l'écran titre. L'IHM de Kronos n'est pas bloquée, mais le jeu ne répond plus aux commandes.

Dans DebugView, on voit des invalid opcodes à ce moment-là :

```
Error: Slave SH2 invalid opcode

R0 =  00000000 R12 =  00000090
R1 =  00000000 R13 =  00000000
R2 =  060007FE R14 =  0602A414
R3 =  060007FE R15 =  06090FFC
R4 =  26000B0A SR =   00000000
R5 =  000000A0 GBR =  00000000
R6 =  00000009 VBR =  06000400
R7 =  2602A3F4 MACH = 00000000
R8 =  00000009 MACL = 00000000
R9 =  06000334 PR =   06010B40
R10 = FFFFFFFF PC =   060007FC
R11 = 06000330

Error: Master SH2 invalid opcode

R0 =  00000104 R12 =  00000000
R1 =  06000348 R13 =  00000001
R2 =  FFFFFFFE R14 =  06010F68
R3 =  06000900 R15 =  0609FB58
R4 =  FFFFFFFE SR =   000000E0
R5 =  25FE00A0 GBR =  FFFFFE00
R6 =  060102CA VBR =  06000000
R7 =  00000000 MACH = 00000000
R8 =  00000001 MACL = 00000000
R9 =  00000001 PR =   06000928
R10 = 0602FFE0 PC =   060102CA
R11 = 06010688
```

Le jeu commence à ne plus démarrer après le bios en WIP du 07/09/2021, et adopte le comportement actuel en WIP du 20/09/2021.

Testé avec le CD d'origine US.

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

Corrigé avec les fixs sur le timing du 14-15 Décembre 2023
