### ISSUE TITLE
[Shining wisdom] Corruption des couleurs à l'écran titre

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1404]
En v2.3.1 publique et dans la dernière WIP, dans le 2 noyaux, les couleurs sont incorrectes à l'écran titre sur l'image d'arrère-plan.
![image](https://user-images.githubusercontent.com/7624262/195957025-877f7255-5497-447c-8ce3-bbe0fd7eb21c.png)

La couche avec les couleurs incorrecte est le NBG0 :
![image](https://user-images.githubusercontent.com/7624262/195957044-4b989e31-70d2-4027-a20f-8774e5837b8a.png)

Les couleurs sont correctes dans le visualiseur :
![image](https://user-images.githubusercontent.com/7624262/195957082-39947bd5-451d-4930-93e9-bce71ab4b156.png)

Le problème apparaît en WIP du 03/02/2022.

Testé avec le CD d'origine US.

**Comment by FCare** [comment]
Pas de soucis chez moi avec une derniere verison compilée: 
![image](https://user-images.githubusercontent.com/14252808/200074533-fc46a89e-f72d-4477-869f-a582f14bb8ee.png)

**Comment by fafling** [comment]
Save state de la version US à l'écran titre :
[Shining_wisdom_ecran_titre_v2.3.1_20221105.zip](https://github.com/FCare/Kronos/files/9946618/Shining_wisdom_ecran_titre_v2.3.1_20221105.zip)

Bizarrement, le chargement de la save state donne des couleurs correctes alors qu'elles ne l'étaient pas lors de sa création.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.3.1 du 16.11.2022
Cs

Ca ne touche pas la version européenne, ni japonaise, juste la version Américaine

![image](https://user-images.githubusercontent.com/12481242/202155170-9db8ca52-4de8-4375-9173-92c7a64c1f99.png)

**Comment by BenjaminSiskoo** [comment]
Semble corriger avec cette wip kronos20230111_4be7315

**Comment by fafling** [comment]
C'est OK dans les 2 noyaux dans la dernière WIP.
Fixé par la 1ère WIP du 11/01 (26a0647a).
