### ISSUE TITLE
[Batman Forever - The Arcade Game (Europe)] L'ombre de Batman n'est pas noir...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1410]
Kronos 2.3.1 du 16.11.2022
Cs

L'ombre est correcte dans la version public de kronos 2.2.0. Mais il y a des artefacts sur le personnage.

![image](https://user-images.githubusercontent.com/12481242/202195478-f513d07f-0f89-429c-acc9-d33cf71abe22.png)

savestate : 
[batman.zip](https://github.com/FCare/Kronos/files/10022190/batman.zip)

**Comment by fafling** [comment]
Présent dans la v2.3.1 publique et dans la dernière WIP, dans les 2 noyaux.

Apparaît en WIP du 10/12/2021, la WIP précédente du 09/12/2021 n'a pas ce problème.

Il n'y a pas que l'ombre de Batman qui a des couleurs incorrectes, les 2 têtes de Batman sur les côtés des barres en haut, et les ombres des adversaires aussi. On en voit aussi lors de l'intro du niveau 1 sur le tour de l'emblème de Batman (vert au lieu d'être noir) et sur la voiture de Batman (pixels blancs) :
![image](https://user-images.githubusercontent.com/7624262/204154705-e3938cc4-0ed3-4142-a80c-f7a366483679.png)

Tous les graphismes concernés sont sur les sprites, en 8bpp 64 ou 128 color bank. Les couleurs sont correcte dans l'écran debug du VDP1 :
![image](https://user-images.githubusercontent.com/7624262/204154756-a9472daa-f6c1-4a92-a0c1-e328495598c2.png)

Il y a le même souci de save state que dans d'autres jeux avec des couleurs incorrectes : quand on la charge, on ne reproduit pas le problème.

Testé avec le CD d'origine.

**Comment by FCare** [comment]
a cause de 06aef98b931e574aa71bc64d2efe0a7751d5c7a0
