### ISSUE TITLE
[Rapyulus Panic (Japan)] Trait blanc in game et GPU RGB (RGB0)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1412]
Kronos 2.3.1 Wip du 23.11.2022
Cs

En activant l'option GPU RGB, un trait blanc est affiché quand la roue tourne. En désactivant l'option GPU RBG, c'est nickel.

![image](https://user-images.githubusercontent.com/12481242/204001829-1fa8fe32-d9d2-4446-9a29-6e26b1a8b479.png)

savestate : 

[Rapyulus Panic (Japan).zip](https://github.com/FCare/Kronos/files/10093354/Rapyulus.Panic.Japan.zip)

**Comment by fafling** [comment]
Se produit en v2.3.1 publique et dans la dernière WIP, seulement avec le GPU RBG, et seulement après que le jeu a été mis en pause in game en appuyant sur start.

Le passage par l'écran de pause est aussi nécessaire pour reproduire à partir de la save state car l'artifact n'apparaît pas non plus sinon. La save state n'est pas compatible avec la version publique.

L'artifact tourne avec la roue sur le RBG0 (appuyer sur A ou C pour miser au moins une pièce, puis mettre le curseur sur GO et appuyer sur A ou C pour la faire tourner).

Le RBG0 est en mode bitmap 8bpp dans la VRAM B0 :
![image](https://user-images.githubusercontent.com/7624262/204061574-d065074a-9690-4364-90c2-51f56b9d7985.png)

Cet artifact n'apparaît pas sur la console, même après être passé par l'écran pause. On entend le lecteur CD faire du bruit à l'entrée et à la sortie de la pause, il y a probablement des chargements.

L'écran de pause est un bitmap 8bpp sur le NBG0 dans la VRAM B1 :
![image](https://user-images.githubusercontent.com/7624262/204062776-a7d8e8a0-0b5b-43e3-9da5-c41415ba53fc.png)

Le bitmap de l'écran de pause est donc contigu à celui du RBG0, juste en-dessous de lui. L'artifact pourrait être une corruption due à son chargement.

L'artifact a toujours été là depuis que l'affichage des bitmaps a été fixé en GPU RBG en WIP. Les bitmaps étaient auparavant corrompus et affiché en OpenGL en workaround, voir #537 . 

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Correction du 22/112023 - fix last bronx
