### ISSUE TITLE
[Digital Ange - Dennou Tenshi SS (Japan)]  Régression le jeu ne boot plus...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1415]
Kronos 2.3.1
Mode CS

Le jeu ne fonctionne plus. Au lancement du jeu, kronos se ferme auto après le bios.

Erreur avec Debugview

<process started at 18:14:02.284 has terminated with 0xc0000005 (EXCEPTION_ACCESS_VIOLATION)>

**Comment by fafling** [comment]
Le crash se produit dans les 2 noyaux.

Apparaît en WIP du 28/11/2022 (commits 6bae284, c05914d et 61caa0d).

Testé avec le CD d'origine.
