### ISSUE TITLE
[Koutetsu Reiiki - Steeldom (Japan) (2M)] Régression :  le jeu ne boote plus...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1416]
Kronos 2.3.1 du 28/11/2022
Mode CS

**Comment by fafling** [comment]
@BenjaminSiskoo Je vais toujours in game dans la WIP d'hier et d'aujourd'hui, testé avec le CD et le redump et dans les 2 noyaux.

**Comment by BenjaminSiskoo** [comment]
Ca devait être à cause du problème que j'ai eu avec les FPS
