### ISSUE TITLE
Shining Force 3 annoying sounds in all the disks

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#1421]
There is an annoying sound, seems like the same sound when you move the stick to select the options, but this can be only heard during the character's view screen "When you select a character and you can zoom in, rotate, etc"

Please, find attached video record to see the problem. In the past this was not happening, I'll try to bisect the build that caused the issue.

[2022-12-08 13-21-09.zip](https://github.com/FCare/Kronos/files/10185308/2022-12-08.13-21-09.zip)

Using Kronos version from Nov 31 2022.

Specs:

i7 4790k
16 GB DDR3
GTX 970
Windows 11 pro

**Comment by LuismaSP89** [comment]
Ok, after testing a lot of builds from January 2021 to November 2022, I found the problem in all of them, so I'm not sure when this started.

**Comment by BenjaminSiskoo** [comment]
ok thanks :)

**Comment by LuismaSP89** [comment]
Another observation: The problem persist also if the Directx sound library is selected instead of SDL, but with Directx the sound is a bit worse since it adds also a crackle sound.

**Comment by LuismaSP89** [comment]
Update: Seems the premium disk is not the only affected, but all the disks of the game. The text speed is also very fast, and the sound can be hear in most cases. See attached video.

[2022-12-08 16-01-50.zip](https://github.com/FCare/Kronos/files/10186642/2022-12-08.16-01-50.zip)

**Comment by LuismaSP89** [comment]
My apologies, after many investigations, seems that it was a problem with the controller mapping. I deleted all the inputs on the kronos.ini and configured it again and now the problem is solved.
