### ISSUE TITLE
[vdp1-mic3d Yaul demo] Les sprites ne s'affichent pas

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1423]
Dans la dernière WIP (dc092cf) et en v2.3.1 publique, dans les 2 noyaux, Kronos n'affichent rien sur les sprites après le logo Sega.

![image](https://user-images.githubusercontent.com/7624262/208318316-00bd0ba5-260f-4f61-bb32-a9c7a2b94538.png)

Affichage correct dans Kronos v2.0.2 et Yabause 0.9.14 :

![image](https://user-images.githubusercontent.com/7624262/208318361-78c04bc1-bb4b-48e8-94b3-f9e342d4b32f.png)

Le problème apparaît en WIP du 04/02/2020 (la v2.0.2 date de la veille).

Pas de message dans DebugView, l'IHM de Kronos n'est pas bloquée.

Le code de la démo :
https://github.com/ijacquez/libyaul-examples/blob/develop/vdp1-mic3d/vdp1-mic3d.c

Image de la démo :
[vdp1-mic3d.zip](https://github.com/FCare/Kronos/files/10254613/vdp1-mic3d.zip)

**Comment by ijacquez** [comment]
If there is anything needed from me, I'm here to help.

**Comment by FCare** [comment]
Issue due to d34f47a714e41c777e1fd609e384145f1ff2840c

**Comment by FCare** [comment]
Command list I receive is this one:
Command is 0x9 @ 0x0
Command is 0xa @ 0x20
Command is 0x8004 @ 0x40

So, the last polygon reports a end command list.

How do you trigger the next command list?

**Comment by FCare** [comment]
Vdp1Draw
Command is 0x9 @ 0x0
Command is 0xa @ 0x20
Command is 0x8004 @ 0x40
VDP1: Command Finished! count = 0 @ 00000040
Vdp1Draw end at line 0 
Write W 9 @ 40 (31)
Write W 0 @ 42 (31)
Write W 0 @ 44 (31)
Write W 0 @ 46 (31)
Write W 0 @ 48 (31)
Write W 0 @ 4a (31)
Write W 0 @ 4c (31)
Write W 0 @ 4e (31)
Write W 0 @ 50 (31)
Write W 0 @ 52 (31)
Write W 13f @ 54 (31)
Write W df @ 56 (31)
Write W 0 @ 58 (31)
Write W 0 @ 5a (31)
Write W 0 @ 5c (31)
Write W 0 @ 5e (31)
Write W a @ 60 (31)

First list is ready and got a stop bit. But, before the poygon draw ends, the code is updating the command list and remove this stop.
Kronos only take care of the stop when it starts the command, it does not look for an update when the command  shall be ended.

**Comment by FCare** [comment]
Polygon command code is 0x8004. From spec, it is a prohibited command. When END bit is set, the last part of command should be 0. So only 0x8000 is valid. But from code execution on real HW, in case of 0x8004, the polygon command is executed then it is stopped.

I will implement this prohibited behavior.

**Comment by FCare** [comment]
![image](https://user-images.githubusercontent.com/14252808/210793828-a3d781a0-aa7f-4084-b9f2-caa3834d8317.png)

**Comment by fafling** [comment]
Actually fixed by bb43f5c.
Kronos was starting VDP1 draw later than the console, so in Kronos, the demo could erase the beginning of the command list built during the previous frame by an end draw command before VDP1 started drawing.
