### ISSUE TITLE
[Grandia (Jap)] Ecran noir avant d'entrer in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1432]
Kronos 2.3.1 wip du 02.02.2023
Cs

Le compteur VDP1 décroit pour atteindre 0.

savestate : 

[T-4507G_001.zip](https://github.com/FCare/Kronos/files/10574534/T-4507G_001.zip)

**Comment by fafling** [comment]
Présent en v2.5.0 publique.
Dans DebugView, il y a  un Master SH2 invalid opcode au moment de l'écran noir :
```
R0 =  255AD324 R12 =  0608404C
R1 =  06016C00 R13 =  06084048
R2 =  000C0F08 R14 =  06016C08
R3 =  1ED4400A R15 =  06001F34
R4 =  002767A8 SR =   00000000
R5 =  00000000 GBR =  00000000
R6 =  06080BC4 VBR =  06000000
R7 =  06080E54 MACH = 00000000
R8 =  0607E9D8 MACL = 00000000
R9 =  060736E8 PR =   000C0F0C
R10 = 00008000 PC =   000C0792
R11 = FFFFFFFF
```
Save state juste avant l'écran noir :
[grandia_ecran_titre_apres_intro_v2.5.0.zip](https://github.com/FCare/Kronos/files/10727402/grandia_ecran_titre_apres_intro_v2.5.0.zip)

Chez moi, cet écran noir existe aussi en v2.3.1 publique mais avec un message d'invalide opcode différent. Save state :
[grandia_ecran_titre_apres_intro_2.3.1.zip](https://github.com/FCare/Kronos/files/10727414/grandia_ecran_titre_apres_intro_2.3.1.zip)

Testé avec le CD.

**Comment by fafling** [comment]
Détail intéressant, lancer Grandia avec une backup ram interne sans l'espace nécessaire pour créer la sauvegarde du jeu lui fait afficher un écran d'avertissement après l'écran titre, au lieu de la video qu'on ne peut pas passer. Cela permet d'arriver plus rapidement au point où l'écran noir se produit.

Exemple de backup ram interne permettant cela :
[bkram_azel_panzer_dragoon.zip](https://github.com/FCare/Kronos/files/10727484/bkram_azel_panzer_dragoon.zip)

**Comment by fafling** [comment]
Fixé depuis la WIP du 14/02/2023 (747ad60).
