### ISSUE TITLE
[Resident Evil (USA)] Régression Kronos 2.3.1- Le jeu freeze sur l'écran titre...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1440]
Kronos 2.5.0
Cs

La version européenne fonctionne par contre.

Avec Kronos 2.3.1, le jeu est jouable.

**Comment by fafling** [comment]
Pas de message dans debugView. Les compteurs de framerate sont à fond.

Apparaît en WIP du 11/11/2022 (884eaba). La WIP précédente du 10/11 (1289429) n'a pas ce problème.

Testé avec le redump.

**Comment by fafling** [comment]
Se produit toujours en v2.5.0 publique avec tous les interpréteurs SH2 **sauf le SH2 Kronos Debug Interpreter**.

Ne se produit plus dans la dernière WIP de la branche synTiming (résolu en WIP du 14/02 commit 747ad60).

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

Fonctionne de nouveau
