### ISSUE TITLE
[Duke Nukem 3D] In-game music does not properly start in some levels

### ISSUE THREAD

**Issue by TheKins** [FCare/Kronos#1442]
**What's the full name of the game (including region) ?**
Duke Nukem 3D (US)

**What's your frontend ? (standalone, libretro, ...) ?**
Standalone

**What's your OS ? (windows, linux, OSX, ...) ?**
Windows 10

**What's your hardware ? (CPU, GPU, ...) ?**
AMD Ryzen 5 1600
GeForce GTX 1070
16gb RAM

**What's the storage type of the game (official cd, burned cd or cd image) ?**
**If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)**
CD Image, bin/cue.

**Are you using any setting different from default ? If so, precise**
Real BIOS, upscaled graphics resolution.

**The Actual Issue:**
When starting certain levels, the game uses a CD Audio track to play a line of voiceover, then switches to another CD Audio track for the actual level music. This switch does not seem to happen in Kronos, instead continuing to play the voiceover audio track, resulting in Duke randomly spouting contextless one-liners every couple of seconds.

In levels that do not start with a voiceover, the music appears to play as intended.

**How to Reproduce:**
Load the game and start the first level. After Duke finishes talking, the music should start playing. Instead, there'll be a second of silence before he spouts a line of dialogue intended for a few levels down the line.

**Comment by fafling** [comment]
I don't reproduce that issue in public v2.5.0, even with upscale to 1080p.
Tested with the original US CD and the redump image.

**Comment by TheKins** [comment]
Thanks, got it working. Double-checked my image and realized that I'd turned BIOS emulation on.
