### ISSUE TITLE
Doesn't work at all with Windows 11

### ISSUE THREAD

**Issue by ghost** [FCare/Kronos#1443]
Inputting bios or any setting causes the emulator to crash.
Also, the retroarch core loads a game then freezes. 

Can't even test the emulator because it's broken so badly, I can't even set settings.
Has anyone tested Kronos on windows 11 or are these windows 10 issues as well?

**Comment by BenjaminSiskoo** [comment]
A friend of mine testing kronos with windows 11.

We need your specs. Try with a blank kronos.ini. setting up the path to a real bios and your controller, Close Kronos, launch it again and try a game.

What is the game format (redump, bin cue, others) ?
Which game ?

**Comment by ghost** [comment]
Ryzen 3700X
MSI 2070 8GB
32GB Dual Channel DDR4
WD Blue 1TB SSD

Game:
Resident Evil 1
2 bin files, 1 cue file.

**Comment by BenjaminSiskoo** [comment]
Try with a blank kronos.ini. setting up the path to a real bios and your controller, Close Kronos, launch it again and try a game.

**Comment by ghost** [comment]
My path is:
C:/Users/AMD/Desktop/Kronos_2.5.0/sega_101.bin

How would I set that in the ini file?

**Comment by ghost** [comment]
The ini file just says
[1.0]
General\EnableVSync=true
Input\Port\1\Id\1\Type=2
General\Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x6?\0\0\x2\xe6\0\0\b\xc0\0\0\x4\xfc\0\0\x6@\0\0\x3\x1c\0\0\b\xbf\0\0\x4\xfb\0\0\0\0\0\0\0\0\xf\0\0\0\x6@\0\0\x3\x1c\0\0\b\xbf\0\0\x4\xfb)

No clue what's going on there.
Do I just type Bios=C:/Users/AMD/Desktop/Kronos_2.5.0/sega_101.bin
I also tried BiosFilePath= 
still freezing and not showing up
But I don't know the command in which I need to type... 

https://imgur.com/a/4epLh7O

**Comment by ghost** [comment]
I give up I'll just use the Beetle Core in Retroarch this isn't worth my frustration.  It's making me way to mad.
