### ISSUE TITLE
Virtua Fighter 2 graphic artifacts

### ISSUE THREAD

**Issue by mfigueirido** [FCare/Kronos#1451]
What's the full name of the game (including region) ?
Virtua Fighter 2 (USA) (RE)

What's your frontend ? (standalone, libretro, ...) ?
Libretro, core v.2.5.0

What's your OS ? (windows, linux, OSX, ...) ?
Windows 10 x64

What's your hardware ? (CPU, GPU, ...) ?
AMD Ryzen 5 2600, AMD RX 570, 16 GB RAM

What's the storage type of the game (official cd, burned cd or cd image) ?
CD image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)
cue/bin

Are you using any setting different from default ? If so, precise
Default settings. Happens with both old GL renderer and CS.

Did this game work previously ? Do you remember when ? Is it happening with other games ?
This error didn't happen on v.2.3.0

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this
N/A

There's artifacts in the character's geometry and shadows. It's more noticeable in motion.

![Virtua Fighter 2 (USA) (RE)-230218-165610](https://user-images.githubusercontent.com/24922404/219877375-7e75307d-e712-43c6-918a-fb14405c7834.png)
![Virtua Fighter 2 (USA) (RE)-230218-165844](https://user-images.githubusercontent.com/24922404/219877380-927c0a12-9c44-42f5-8f4b-a96bc3890507.png)

**Comment by fafling** [comment]
Known issue first reported here : [https://github.com/FCare/Kronos/issues/1427#issuecomment-1399610285](https://github.com/FCare/Kronos/issues/1427#issuecomment-1399610285)

**Comment by fafling** [comment]
Fixed with the merge of the syncTiming branch.
