### ISSUE TITLE
Kronos 2.5.0. stv input lag compared to mame

### ISSUE THREAD

**Issue by regbox80** [FCare/Kronos#1455]
Loading stv game diehard arcade runs fine. But hast an input lag of about 1/5 seconds compared to load diehard arcade on mame. 
Tested with kronos 2.5.0 standalone windows 10

What's the full name of the game (including region) ?

What's your frontend ? (standalone, libretro, ...) ?

What's your OS ? (windows, linux, OSX, ...) ?

What's your hardware ? (CPU, GPU, ...) ?

What's the storage type of the game (official cd, burned cd or cd image) ?

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)

Are you using any setting different from default ? If so, precise

Did this game work previously ? Do you remember when ? Is it happening with other games ?

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

**Comment by fafling** [comment]
Which video core are you using ? OpenGL currently has a lag issue which make sprites moving with a delay.
CS video core doesn't seem laggy at all in that game.

**Comment by regbox80** [comment]
Thanks, yes I was using OpenGL. Switching to csfi made a difference. But which core should I use? Nanovg?

**Comment by fafling** [comment]
Kronos has only 2 video cores, OpenGL and CS. I don't know why you talk about Nanovg.

**Comment by fafling** [comment]
@BenjaminSiskoo That was an OpenGL issue, so it should be closed since OpenGL has been removed.
