### ISSUE TITLE
[Dark Savior (EUR, USA)] Régression entre Kronos 2.3.1 et 2.5.0...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1461]
Le jeu affiche un écran noir sur l'écran FMV avant d'entrer in game, on entends les musiques et les SFX.

**Comment by fafling** [comment]
Même problème en v2.5.0 et dans la dernière WIP.

L'écran noir se produit immédiatement au début de l'intro si on appuie sur start.
Pendant l'écran noir, le jeu ne répond qu'à A+B+C+start qui fait revenir à l'écran de choix de la sauvegarde.
Le framerate du VDP1 tombe à 0.
Le jeu attend que l'EDSR du VDP1 vaille 2, or il vaut 3.

Le problème apparaît en WIP du 07/01/2023 (commit 7c92e08) après l'implémentation du bit BEF de l'EDSR.

Testé avec le CD d'origine US.

**Comment by FCare** [comment]
tst #0x2, r0
bf 0x

Ne saute que si le bit 1 du R0 est positionné.
Donc le jeu attend que l'EDSR soit 0 ou 1.

**Comment by BenjaminSiskoo** [comment]
kronos20231213_607dc9c

Corrigé
