### ISSUE TITLE
Retroarch core speed issues in windows

### ISSUE THREAD

**Issue by jhdgghost** [FCare/Kronos#1464]
I reopen this issue because still speed and stutering issues are happening in 2.5.0 core in retrorch winx64 that not happen in windows standalone

What's the full name of the game (including region) ? All

What's your frontend ? (standalone, libretro, ...) ? Libreto

What's your OS ? (windows, linux, OSX, ...) ? Windows

What's your hardware ? (CPU, GPU, ...) ? Ryzen 5, Gtx 1060

What's the storage type of the game (official cd, burned cd or cd image) ? Cd image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...) chd

Are you using any setting different from default ? If so, precise

Did this game work previously ? Do you remember when ? Is it happening with other games ? The core from 1.9.11 retroarch work perfect the versions after that work a irregular speed the bios speed is very fast and the sound is totally weird. Yesterday i try 1.9.14 with updated core but was the same, so i replaced but the core from 1.9.11 and work again so not seem a problem of retroarch version but a change in the core after that version.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

**Comment by barbudreadmon** [comment]
>I reopen this issue because still speed and stutering issues are happening in 2.5.0 core in retrorch winx64 that not happen in windows standalone

The libretro core having worse performance than standalone is perfectly normal behavior : retroarch is known for having some overhead, especially with opengl cores.

**Comment by Immersion95** [comment]
Same thing here, I use VRR and it stutters a lot with Vsync Off + Sync to exact framerate.

Curious thing is that Vsync Off + Sync to exact framerate Off make the games run with unlimited framerate which is a weird behavior.

The only solution is Vsync On but it adds input lag unfortunately.

**Comment by jhdgghost** [comment]
> Same thing here, I use VRR and it stutters a lot with Vsync Off + Sync to exact framerate.
> 
> Curious thing is that Vsync Off + Sync to exact framerate Off make the games run with unlimited framerate which is a weird behavior.
> 
> The only solution is Vsync On but it adds input lag unfortunately.

As you say I think more a performance issue is that the framerare is not correctly sync with the game going too fast from example in the bios and the game sttuters to try to sync. In previous core versions as I say the core from retroarch 1.9.11 not had that behaviour I work fine but is a old version. The sync seems the problem

**Comment by jhdgghost** [comment]
See the new commit 

[revert Vsync mechanism on WIN32 to the old one](https://github.com/FCare/Kronos/commit/6f4d05d8f735d1973cd7f73be87ddaf26a1eaa54)

Maybe that can be related, other commits introduced also lately. I will like to twst  but was not able to make a.build if somebody can guide me as nit used to use cmake. If not will wait still offiicial release, hopefully new version is coming seeing last updates.

**Comment by Immersion95** [comment]
> See the new commit
> 
> [revert Vsync mechanism on WIN32 to the old one](https://github.com/FCare/Kronos/commit/6f4d05d8f735d1973cd7f73be87ddaf26a1eaa54)
> 
> Maybe that can be related, other commits introduced also lately. I will like to twst but was not able to make a.build if somebody can guide me as nit used to use cmake. If not will wait still offiicial release, hopefully new version is coming seeing last updates.

I wanted to try but I can't seem to be able to build it :(. There's a configure error. Quite frankly I don't even know how to put the flag.

**Comment by jhdgghost** [comment]
> > See the new commit
> > [revert Vsync mechanism on WIN32 to the old one](https://github.com/FCare/Kronos/commit/6f4d05d8f735d1973cd7f73be87ddaf26a1eaa54)
> > Maybe that can be related, other commits introduced also lately. I will like to twst but was not able to make a.build if somebody can guide me as nit used to use cmake. If not will wait still offiicial release, hopefully new version is coming seeing last updates.
> 
> I wanted to try but I can't seem to be able to build it :(. There's a configure error. Quite frankly I don't even know how to put the flag.

Yes the same happen to me, not sure how cmake for windows works

**Comment by Immersion95** [comment]
> > > See the new commit
> > > [revert Vsync mechanism on WIN32 to the old one](https://github.com/FCare/Kronos/commit/6f4d05d8f735d1973cd7f73be87ddaf26a1eaa54)
> > > Maybe that can be related, other commits introduced also lately. I will like to twst but was not able to make a.build if somebody can guide me as nit used to use cmake. If not will wait still offiicial release, hopefully new version is coming seeing last updates.
> > 
> > 
> > I wanted to try but I can't seem to be able to build it :(. There's a configure error. Quite frankly I don't even know how to put the flag.
> 
> Yes the same happen to me, not sure how cmake for windows works

I built it with Make and it worked. Unfortunately latest build has a lot of bugs, a lot of games have black screen. I will keep the old core, good news is that Vsync ON + Sync to exact framerate is working great with my VRR setup and it doesn't add input lag as I previously thought.

**Comment by jhdgghost** [comment]
Great. Hopefully the bugs get fixed for official release. I keep open the issue still I can test. Thanks immmersion95 for the test. Kronos is great specially upscaling but due the framerate sync issue I can not use it and beetle saturn is great but no upscaling.

**Comment by jhdgghost** [comment]
Fixed.

Be sure  ‘Sync to Exact Content Framerate (G-Sync, FreeSync)’ in video settings. It works with Vsync activated

Thanks to developers. Games look great with upscaling

**Comment by BenjaminSiskoo** [comment]
thanks

**Comment by Immersion95** [comment]
It sill has judders as of today. The core is always outputing at 60.0 fps whereas MAME/Mednafen change its fps to 59.83 or else for some games.
