### ISSUE TITLE
[Virtual on] Sprites et RBG0 manquants

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1466]
En v2.5.0 publique et dans la dernière WIP, les sprites et le RBG0 ne s'affichent plus.

![image](https://github.com/FCare/Kronos/assets/7624262/e5217160-666d-48d3-aad6-f59f4bedf7b3)

Le problème apparaît en WIP du 07/01/2023 (7c92e08). La WIP précédente du 05/01 (58ef217) n'a pas le problème.

Testé avec le CD jap.

**Comment by BenjaminSiskoo** [comment]
Avec la WIP kronos20231118_e8b6c1c

Le sol est affiché, il manque le robot 

![image](https://github.com/FCare/Kronos/assets/12481242/65e75a57-8ac1-4456-9dff-105976cd07cf)

**Comment by fafling** [comment]
@BenjaminSiskoo Le RBG0 ne s'affiche toujours pas chez moi, même après réinitialisation du kronos.ini et de la bkram. Est-ce que tu as des paramètres différents de ceux par défaut ?

**Comment by BenjaminSiskoo** [comment]
@fafling mes settings : 

![image](https://github.com/FCare/Kronos/assets/12481242/ad049611-3b3b-4828-8773-dd5d0d30c172)

**Comment by fafling** [comment]
Pas d'affichage du RBG0 chez moi même avec ces réglages.

Le jeu met à jour le PTMR à 0 (idle) après sélection de "ARCADE" au menu titre.
Avant le commit 7c92e08, il met ensuite le PTMR à 1 (dessin immédiat) dans la fonction 060D67A6 si le bit CEF de l'EDSR est à 0.
Après le commit 7c92e08, le CEF ne passe pas à 0 et le PTMR n'est jamais mis à 1 par cette fonction, donc le VDP1 ne dessine jamais.

Je pense que le problème vient de ce que le commit 7c92e08 supprime la mise à jour de l'EDSR (BEF avec CEF et CEF à 0) au changement de framebuffer pour ne la faire qu'en début de dessin du VDP1 :
https://github.com/FCare/Kronos/commit/7c92e0817c727ea006a5cccce9e1a366da25642b#diff-e59eae3324e808dc8d0251d9b0ff866510d94d42ab8088252fa278f71a6f205fR2580

Cette mise à jour doit avoir lieu quand même au changement de framebuffer lorsque le dessin n'est pas automatiquement déclenché (PTMR différent de 2), comme l'indique la doc du VDP1 p. 52-53.

**Comment by fafling** [comment]
L'affichage des sprites et du RBG0 est effectivement de retour dans Virtual on, mais suite au commit c461dc6, il y a un double shift incorrect de l'EDSR au changement de framebuffer quand PTMR vaut 2. Cela met l'EDSR à 0 quand le dessin commence automatiquement, quelle que soit la valeur de l'EDSR avant le changement de framebuffer, et il passe à 2 quand le dessin se termine.

Sur la console, il n'y a qu'un shift de l'EDSR au changement de framebuffer quand PTMR vaut 2.

C'est visible dans la démo "VDP1 undocumented commands" où le PTMR est à 2. Elle affiche la valeur de l'EDSR pendant le vblank quand le dessin est terminé : 
https://www.youtube.com/watch?v=TknOQ2fS4nQ
Sur la console, quand il y a eu dessin à la frame précédente, l'EDSR vaut 3 en fin de dessin, car il passe à 1 au changement de framebuffer et début de dessin automatique.

Affichage dans Kronos :
![image](https://github.com/FCare/Kronos/assets/7624262/f1a4b2a5-6cf5-4046-99f9-895b575279ed)

Image de la démo :
[demo - VDP1 undocumented commands_20230107.zip](https://github.com/FCare/Kronos/files/13453753/demo.-.VDP1.undocumented.commands_20230107.zip)

@BenjaminSiskoo @FCare Est-ce qu'on peut rouvrir ?

**Comment by fafling** [comment]
Régression sur le shift de l'EDSR fixée par [f9facc3](https://github.com/FCare/Kronos/commit/f9facc366551279535e09f39b5797f23633ecc53)
