### ISSUE TITLE
Master of Monsters - Neo Generations (Japan) : Ecran noir après le bios après la 2.5.0 Public...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1468]
Fonctionne avec kronos20230823_e827a7c (https://github.com/FCare/Kronos/commit/ec9e827115edade5ce6be04c05f30a90438b2ef6)
Ecran noir avec Kronos20230823_ec9e827(https://github.com/FCare/Kronos/commit/e827a7c20086bf4cc69ae578c68e0e9f68c86db0)

**Comment by fafling** [comment]
Réglé par ef11f70
