### ISSUE TITLE
[Nissan Presents - Over Drivin' GT-R (Japan) (Rev A)] Ecran noir après les vidéo d'intro mais en restant appuyé sur start le jeu fonctionne...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1471]
kronos20231123_3893ebb

après le bios si tu laisse partir la vidéo d'intro, appuie sur start, il y aura un écran noir.
maintenant si juste après le bios, je laisse appuyer sur start, ca skip les vidéos directs et on arrive sur le press start screen

**Comment by fafling** [comment]
L'écran noir se produit au moment où il devrait y avoir un chargement à partir du CD.
Il apparaît en WIP du 08/11/2023 (ee4f61b) avec le rework des interrupts. La précédente (67b4a57) n'a pas le problème.
Il ne se produit qu'avec l'interpréteur performance. L'interpréteur debugger ne reste pas bloqué.

Testé avec le CD.
