### ISSUE TITLE
[Daytona USA (Japan)] freezes aléatoires

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1472]
Depuis la 1ère WIP syncTiming du 14/02, des freezes aléatoires se produisent pendant les courses, plus ou moins rapidement en fonction des WIP. Le problème ne se produit pas en v2.5.0 publique.

L'IHM de Kronos n'est pas bloquée. Si j'affiche la fenêtre de log, il y a des messages "WARNING: sound buffer overrun" qui apparaissent pendant l'animation du bios et au démarrage du jeu, mais pas pendant la course. Ces messages se remettent à apparaître sans arrêt quand le freeze se produit :
![image](https://github.com/FCare/Kronos/assets/7624262/427dbb4f-3fbc-4a0b-945d-4312367b416a)

Lors du freeze, les 2 SH2 s'attendent mutuellement. Chacun est dans une boucle qui attend que son input capture flag passe à 1 (bit ICF en 0xFFFFFE11, registre FTCSR). Ce bit permet aux 2 CPU de s'échanger des signaux car le bit ICF de chaque CPU peut être mis à 1 par l'autre CPU (voir Technical bulletin n°28). Dans Daytona USA, cela sert pour déclencher une tâche sur le SH2 slave, et, pour le SH2 master, à vérifier que cette tâche est terminée.

La boucle d'attente de l'ICF du slave commence en 0x06034D20.
Si son ICF passe à 1, le programme du slave est le suivant :
- Met le FTCSR à 0.
- Exécute une fonction dont il lit l'adresse en 0x26063720 si @0x06063720 != 0 (étonnant que 0x06063720 ne soit pas lu uncached pour le test vu que c'est le master qui le met à une valeur différent de 0. Possible que le cache du slave soit désactivé, car le registre CCR a la valeur 0 par défaut pour le bit CE et il n'est pas mis à jour par le programme du slave qui commence en 06034CF4).
- @0x06063720 = 0
- Recommence la boucle d'attente de l'ICF.

@0x06063720 vaut 0 dans le cas du freeze. Le slave est donc dans un état où il a terminé sa tâche précédente et en attend une nouvelle. 

Sur le master on est dans une fonction qui commence en 0x0600BF94. Avant d'entrer dans la boucle d'attente de l'ICF (commence en 0x0600C0B2), cette fonction effectue les actions suivantes :
0x0600C07E : @0x06063720 = 0x0600C108 (adresse de la fonction à exécuter par le slave)
0x0600C084 : @0x21000000 = 0xFFFF (met l'ICF du slave à 1)
Une bizarrerie dans le debugger Master SH2, quand on step sur l'instruction 0x0600C084 qui écrit l'ICF, le debugger exécute d'un coup une dizaine d'instructions et on se retrouve directement dans une sous fonction en 0x06005C38.

A la fin de la fonction 0x0600C108 (dans le delay slot du rts) :
0x0600C188 : @0x21800000 = 0xFFFF (met l'ICF du master à 1)

Save state lors d'un freeze :
[Daytona_freeze_v2.5.0_20231124.zip](https://github.com/FCare/Kronos/files/13463692/Daytona_freeze_v2.5.0_20231124.zip)

Testé avec le CD.

**Comment by FCare** [comment]
MSH2InputCaptureWriteWord
MSH2 context->onchip.FTCSR is 0x87
MSH2 context->onchip.FTCSR is 0x87
MSH2 0x7 => FTCSR (87)
SSH2InputCaptureWriteWord
SSH2 context->onchip.FTCSR is 0x8e
SSH2 0x0 => FTCSR (8e)
MSH2InputCaptureWriteWord
MSH2 context->onchip.FTCSR is 0x87
MSH2 context->onchip.FTCSR is 0x87
MSH2 0x7 => FTCSR (87)
SSH2InputCaptureWriteWord
SSH2 context->onchip.FTCSR is 0x8e
SSH2 0x0 => FTCSR (8e)
MSH2InputCaptureWriteWord
MSH2 context->onchip.FTCSR is 0x87
MSH2 context->onchip.FTCSR is 0x87
MSH2 0x7 => FTCSR (87)
SSH2InputCaptureWriteWord
SSH2 context->onchip.FTCSR is 0x8e
SSH2 0x0 => FTCSR (8e)
MSH2InputCaptureWriteWord
MSH2 context->onchip.FTCSR is 0x87
MSH2 context->onchip.FTCSR is 0x87
MSH2 0x7 => FTCSR (87)
SSH2InputCaptureWriteWord
SSH2 context->onchip.FTCSR is 0x8e
SSH2 0x0 => FTCSR (8e)
MSH2InputCaptureWriteWord
MSH2 context->onchip.FTCSR is 0x87
MSH2 context->onchip.FTCSR is 0x87
MSH2 0x7 => FTCSR (87)
SSH2InputCaptureWriteWord
SSH2 context->onchip.FTCSR is 0x8e
SSH2 0x0 => FTCSR (8e)
MSH2InputCaptureWriteWord
MSH2 0x7 => FTCSR (8f)            **====> Ecriture avant lecture.**

**Comment by FCare** [comment]
Overflow on timer can be trigger one more time in the same frame if FTCSR is cleared => Bug

**Comment by fafling** [comment]
L'interrupt du free running timer déclenché par l'output compare flag A (OCFA) écrit le FTCSR avec l'ICF à 0 sans lecture préalable du registre. Kronos mettait l'ICF à 0 sans vérifier que ce bit avait été lu à 1 au préalable, or c'est nécessaire pour que la mise à 0 de ce bit s'effectue.

Fixé avec [512d1a7](https://github.com/FCare/Kronos/commit/512d1a785296878d624918394f0109b16b3e8951).
