### ISSUE TITLE
[Dino Island (Japan)] Le menu est remplacé par des rectangles  noir (VDP1)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1477]
kronos20231130_75bb84e

VDP1 on

![image](https://github.com/FCare/Kronos/assets/12481242/f74f5e10-a413-4b0a-a8e5-1b5941424327)

VDP1 off : on voir le menu mais pas la partie transparente qui permet de voir ou on est sur le menu

![image](https://github.com/FCare/Kronos/assets/12481242/d67467c0-8a02-437a-b535-0bfd74ccdcb5)

**Comment by fafling** [comment]
L'affichage en v2.5.0 publique est correct :
![image](https://github.com/FCare/Kronos/assets/7624262/054be049-1f07-4d5e-831a-8b819ac352ff)

Le problème apparaît en extui-align avec le merge de la branche syncTiming en WIP du 23/08/2023 (ec9e827).

La color calculation est activée sur les sprites avec une condition sur le MSB de la couleur qui doit valoir 1 :
![image](https://github.com/FCare/Kronos/assets/7624262/ff775868-22a1-4b0d-b7d8-4e127c70fa79)

Commande de dessin en v2.5.0 publique avec le couleur correcte (la dernière WIP la montre noire) :
![image](https://github.com/FCare/Kronos/assets/7624262/9ba77a42-866a-4084-a3eb-4606b8b331db)

La texture 4bpp color bank est en 0x05C10000 en VRAM VDP1 :
![image](https://github.com/FCare/Kronos/assets/7624262/87e5138b-27c8-4987-ab51-3b9f9962cdbc)

Chacun de ses pixels vaut 1.
Associé à la color bank, les pixels dessinés dans le framebuffer valent 0xC001.
Le type de sprite du VDP2 est 0, donc les 11 bits de poids faible du pixel du framebuffer donnent l'index dans la color RAM qui est 1.
Cet index est modifié par le color RAM offset à 3. On obtient donc comme index 3 * 256 + 1 = 769.
La color RAM est en mode 1, donc avec des couleurs BGR555 16 bit, l'adresse de la couleur est obtenu en multipliant l'index par 2. Elle est donc en 0x05F00602.
La valeur est différente à cet endroit entre la v2.5.0 publique (0xFFFF, correct car donne du blanc semi-transparent), et la dernière WIP (0x0000, donne du noir opaque) :
![image](https://github.com/FCare/Kronos/assets/7624262/5c6ec6a8-17b4-4823-8466-391fd246f761)

En fait, les 8 couleurs de 0x05F00600 à  0x05F0060F sont différentes.

Testé avec le CD.

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

Corrigé

**Comment by fafling** [comment]
@BenjaminSiskoo C'est toujours présent chez moi.
Testé avec CD et redump, avec reset du kronos.ini, de la bkram et reboot du pc.
Tu peux rouvrir ?

**Comment by FCare** [comment]
Due to 65fc709f6f6868241682e3b750880054ccb6963d so due to timing accuracy

**Comment by BenjaminSiskoo** [comment]
C'est de retour, mais ca avait été corrigé sur la branch access à un moment donnée

**Comment by FCare** [comment]
A priori, c'est reglé chez moi

**Comment by BenjaminSiskoo** [comment]
Bon pour moi aussi

**Comment by fafling** [comment]
C'est ok chez moi aussi.
