### ISSUE TITLE
DoDonPachi (Japan) Slave SH2 invalid opcode...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1478]
kronos20231130_75bb84e

Le jeu est jouable mais le message SSH2 est apparu avec l'affichage des erreurs pour le débug.

![image](https://github.com/FCare/Kronos/assets/12481242/a041b4fc-c1db-4548-afa6-afb082ebfd9b)

**Comment by FCare** [comment]
les invalid opcode sont toujours la mais ne bloquent plus le jeu
