### ISSUE TITLE
[Dragon Ball Z - La Grande Legende des Boules de Cristal (France, Spain)] Decode array message + ecran noir et son qui boucle + SSH2 invalid opcode...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1479]
kronos20231130_75bb84e

Le jeu est jouable mais le message SSH2 est apparu avec l'affichage des erreurs pour le débug.

2 autres messages SSH2 sont affichés

![image](https://github.com/FCare/Kronos/assets/12481242/b9aeeff2-9add-42e3-b0dd-e4d27f427d64)

Juste après cet écran, on a un écran noir et le son qui boucle

![image](https://github.com/FCare/Kronos/assets/12481242/1e4802ce-1038-4c05-8065-96f3735c59d5)

Quand on attend un peu : 

![image](https://github.com/FCare/Kronos/assets/12481242/3a4a043e-9a38-4462-8dcc-35a06e736d27)

**Comment by FCare** [comment]
les invalid opcode sont toujours la mais ne bloquent plus le jeu
