### ISSUE TITLE
[Aqua-World - Umi Monogatari (Japan)] Ecran noir après la première vidéo d'intro...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1480]
kronos20231130_75bb84e

Juste après le bios, on a une vidéo d'intro, puis un écran noir.

Pas de message d'erreur dans le log

**Comment by fafling** [comment]
Se produit en v2.5.0 publique aussi.
La v2.2.0 publique n'a pas ce problème.
Il apparaît dans la 1ère WIP du 17/12/2021 qui fixe temporairement les perf des videos de Dark seed 2. Le revert partiel du 31/12/2021 n'a pas changé le problème d'Aqua-world (https://github.com/FCare/Kronos/issues/906#issuecomment-1003355728).

Il faut appuyer sur C pour abréger l'intro (start la met en pause) et obtenir le blocage.
L'IHM de Kronos ne répond plus.

Testé avec le CD.

**Comment by BenjaminSiskoo** [comment]
Est corrigé, si jamais @fafling c'est pas bon pour toi je réouvrirais le post
