### ISSUE TITLE
[Firestorm - Thunderhawk 2 (Europe) (En,Fr)] La map est tronquée...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1485]
kronos20231206_3006f2d

Dans le jeu en appuyant sur pause, la map est tronqué.

![image](https://github.com/FCare/Kronos/assets/12481242/5089d753-ff73-4c55-92a8-dde37178f2db)

Savestate : 

[firestorm thunderawk.zip](https://github.com/FCare/Kronos/files/13592260/firestorm.thunderawk.zip)

**Comment by fafling** [comment]
Le problème n'existe pas en v2.5.0 publique.
Il apparaît en extui-align en WIP du 23/08/2023 (ec9e827) qui inclut le merge de la branche syncTiming.

La carte est affichée sur les sprites. On ne la voit pas dans la liste de commandes du VDP1, ni le mot PAUSE. C'est soit une liste de commandes supplémentaire, soit un dessin software, qui est effectué après la 1ère liste.

Non seulement la carte est incomplète, mais Kronos la mélange de manière incorrecte avec le dessin de la liste de commande principale, car la carte apparaît en-dessous des lignes dessinées pour la cible au centre de l'écran, alors que la console l'affiche par-dessus.

In game hors pause, le PTMR du VDP1 (0x05D00004) est écrit en word alternativement par le SH2 master avec :
- 2 (dessin automatique au switch de framebuffer). C'est écrit dans une sous fonction de la fonction d'interrupt 0x06004214 du vblank in (vecteur 0x40). Cette écriture permet sans doute le dessin de la liste de commande principale.
- 1 (dessin immédiat). C'est écrit dans une fonction d'interrupt commençant en 0x060041EA. Cette adresse est dans le vecteur 0x3D. Ce n'est donc pas un interrupt SCU. Mednafen indique que le vecteur 0x3D est celui de fin de transfert DMA1 du CPU :
![image](https://github.com/FCare/Kronos/assets/7624262/c9b3b13d-d6b3-47b1-a0d0-dbd629a51249)

L'écriture du PTMR à 1 permettrait le dessin d'une 2nde liste de commandes à la suite d'un transfert CPU DMA vers la VRAM VDP1, qui servirait à dessiner la carte et le mot PAUSE.

Il n'y a pas d'écriture du PTMR pendant la pause.

Testé avec le CD PAL.

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

Corrigé

![image](https://github.com/FCare/Kronos/assets/12481242/ca87196e-2c52-4620-b9a3-25d6f25c5876)
