### ISSUE TITLE
[Gale Racer (Japan) (En,Ja) (1A)] Arrière plan cassé....

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1486]
kronos20231208_c823250

kronos20231122_7fa6739 à gauche ok à droite cassé kronos20231123_3893ebb

![image](https://github.com/FCare/Kronos/assets/12481242/746ddd5d-4939-472a-b90b-0a4ac877a37d)

**Comment by BenjaminSiskoo** [comment]
![image](https://github.com/FCare/Kronos/assets/12481242/13f44f9d-4351-4b3e-8ed9-b1e2a765a55e)

**Comment by BenjaminSiskoo** [comment]
![image](https://github.com/FCare/Kronos/assets/12481242/6846e167-7ef2-4f0d-a565-bb4d020671e8)

**Comment by FCare** [comment]
3893ebb141d97ccddd07391bcb9643acda66bfc0

**Comment by fafling** [comment]
Sur le menu principal et in game, le jeu met le FBCR à 2 (manual erase) à tous les vblank in.
Il met aussi le FBCR à 3 (manual change) un vblank out sur 2.

Normalement, le VDP1 ne prend en compte le changement du FBCR qu'au hblank in qui suit le vblank out, avec la valeur qu'il a à ce moment-là.

Donc :
- Une frame d'écran sur 2, le FBCR est mis à 2 au vblank in et non modifié au vblank out => effacement du framebuffer à partir du hblank in qui suit le vblank out.
- Une frame d'écran sur 2, le FBCR est mis à 2 au vblank in puis mis à 3 au vblank out => switch des framebuffers au hblank in qui suit le vblank out.

Kronos semble se comporter comme si le 2ème changement du FBCR dans la même frame n'était pas pris en compte, et donc il semble ne faire que des erase.

Infos obtenues avec les breakpoints suivants sur le SH2 master :
- Ecriture word en 0x05D00002 (registre FBCR du VDP1).
- Code en 0x06000840 (point d'entrée de la fonction d'interrupt du vblank in stocké au vecteur 0x40 du SH2 master en 0x06000100).
- Code en 0x06000846 (point d'entrée de la fonction d'interrupt du vblank out stocké au vecteur 0x41 du SH2 master en 0x06000104).

**Comment by BenjaminSiskoo** [comment]
kronos20231211_46c12d6

Corrigé
