### ISSUE TITLE
[Bug Too] Affichage incorrect à l'écran Pause

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1487]
Quand on appuie sur pause, à plusieurs endroits différents, kronos utilise une des 2 1ères copies du framebuffer faites lors des pauses précédentes, pas toujours la même.
Le jeu copie le framebuffer vers une texture en VRAM VDP1 lors de la pause, qu'il utilise pour dessiner le fond sous le mot Pause, voir https://github.com/FCare/Kronos/issues/190#issuecomment-462541757.

A gauche avant la pause, à droite pendant :
![image](https://github.com/FCare/Kronos/assets/7624262/b3f292c2-baf8-4794-a1d0-1927dcb27547)

Le problème existe déjà en v2.5.0 publique.
Il apparaît en WIP du 01/02/2023 (d5270ef). Celle du 31/01 (b61c072) ne l'a pas.

Testé avec le CD US.

**Comment by fafling** [comment]
Virtual Hydlide a le même type de problème apparu en même temps : in game, quand on appuie plusieurs fois sur Y (affiche la carte), ou Z (affiche le menu), en se déplaçant entre les appuis, Kronos affiche l'image copiée du partir du framebuffer lors du 1er appui.

La différence avec Bug too, c'est que le framebuffer est copié vers la VRAM VDP2 et affiché par le NBG0.

Testé avec le CD US.

**Comment by BenjaminSiskoo** [comment]
kronos20231211_46c12d6
