### ISSUE TITLE
[Die Hard Arcade] Régression après le 14 Décembre sur le sol (RBG0)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1494]
kronos20231214_6eb614a - https://github.com/FCare/Kronos/commit/6eb614adcaf9877d7e3e476acef9d39c76f926ec

![image](https://github.com/FCare/Kronos/assets/12481242/b55f2a9b-d1a2-4b88-86fe-520334bafc8a)

Avec la wip suivante kronos20231214_70964a7 

Le sol disparait : 

![image](https://github.com/FCare/Kronos/assets/12481242/ad808ff2-ff42-4af2-8ab3-237de7a70039)

Le problème se trouve sur la couche RBG0 : 

![image](https://github.com/FCare/Kronos/assets/12481242/8ea1038a-152b-4b94-aa56-0b6ac67904b3)

**Comment by FCare** [comment]
32c4d189060044fa634e20f8ab2efaea07695205

**Comment by fafling** [comment]
D'autres jeux sont touchés par des problèmes d'affichage des RBG0 ou RBG1, apparus au même moment :
- Dark savior (sélection du support de sauvegarde),
- Krazy Ivan
- Nights
- Shining Force 3
- Steep slope slider
- Street racer
- Virtual on (sélection du perso)

**Comment by fafling** [comment]
Problèmes fixés par [09e85a8](https://github.com/FCare/Kronos/commit/09e85a8df78ae923b30c41a0ef1e66baa25c46f3)
