### ISSUE TITLE
[Virtua Cop 2 (Europe)] Artefacts in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1506]
kronos20231219_fcf060b

Le jeu semble fonctionner grâce au commit sur PGA Tour Golf 97. Ce jeu est enfin jouable pour la première fois sur un fork yabause.

Il y a des scintillement sin game.

![virtuacop2](https://github.com/FCare/Kronos/assets/12481242/fc3f68c4-6768-4e5a-a4ac-260997a407a0)

**Comment by rcaridade145** [comment]
Mednafen references this "
February 1, 2017:
	SS: Suspend VDP1 command processing while an SCU DMA from SDRAM to VDP1 VRAM is active, to approximate how a SS behaves.  Fixes FMV tearing
	in "Johnny Bazookatone", and fubared graphics in "Virtua Cop" and "Virtua Cop 2".

"

**Comment by FCare** [comment]
fixé sur sequential_vdp1
