### ISSUE TITLE
[Advanced World War - Sennen Teikoku no Koubou - Last of the Millennium (Japan) (2M)] Scintillement sur la page du livre...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1508]
Kronos 2.6.0 Public

![advanced](https://github.com/FCare/Kronos/assets/12481242/12b61698-08d4-4bdb-9a3e-bcd0d41c29bb)

**Comment by FCare** [comment]
fixé dans la branche sequential_vdp1
