### ISSUE TITLE
[Atlantis - The Lost Tales (Europe) (En,De,Es) (Disc 1)] Artefacts sur le press star screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1510]
Kronos 2.6.0 Public

A gauche on a le 2.5.0 Public

![image](https://github.com/FCare/Kronos/assets/12481242/fe4bd2c0-07ef-4bb4-a34d-9a22ef5c9f66)

**Comment by BenjaminSiskoo** [comment]
![image](https://github.com/FCare/Kronos/assets/12481242/b2e31b56-42f3-486f-8616-f1163b89c432)

**Comment by FCare** [comment]
reglé sur branche sequential_vdp1
