### ISSUE TITLE
[Megaman 8 (USA)] Ecran noir sur ce jeu...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1514]
Kronos 2.6.0 Public

Le jeu fonctionne avec les commits du 8 Novembre https://github.com/FCare/Kronos/commit/ee4f61b94128e78b85a3bdcfaad9b39055400ec2

Un des coupables serait : 

https://github.com/FCare/Kronos/commit/1607c2eb3a2df608a4e179ba0ef40a21ca04b55c
https://github.com/FCare/Kronos/commit/bca2cb58138f15635c43ed86c7f4bea16c574c7d
https://github.com/FCare/Kronos/commit/4e1f7f451a0f5455309ad9178153214a7b5df2f6

![image](https://github.com/FCare/Kronos/assets/12481242/0615d89e-6602-4ab1-8771-a7285b3b529d)

**Comment by fafling** [comment]
Seul l'interpréteur performance est bloqué après le logo SEGA. Tous les essais avec l'interpréteur debug m'ont permis de démarrer le jeu.

Chez moi le jeu cesse de démarrer seulement à partir de la 3ème WIP du 15/12 (33fc5e8), et seulement en interpréteur performance. La WIP précédente (f33b22e) n'a pas le problème.

Testé avec l'ISO redump.

**Comment by FCare** [comment]
coupable: 
981ba051918a7b05c833ed3fabed4f41e6c09603

**Comment by FCare** [comment]
regle sur sequential_vdp1
