### ISSUE TITLE
Allow Digital to be Mapped to Analog Triggers

### ISSUE THREAD

**Issue by RinMaru** [FCare/Kronos#1521]
https://retro-bit.com/sega-collaboration/ 
The Sega Saturn Pro controller doesn't utilize Analog Triggers and configuring the 3D control pad L & R triggers won't accept any non-Axis input. While this is a fault of Retrobit and will be addressed in a FW update for the Official console mode i doubt it will be used in the PC FW due to the configurability. It would be nice to allow Digital inputs on the 3D Control pad since Pressure sensitivity rarely made a make-or-break difference in most games though for caution it could be noted Digital is NOT Analog, so users don't report Daytona isn't decelerating accurately.

**Comment by BenjaminSiskoo** [comment]
It should be ok with Kronos 2.6.2
