### ISSUE TITLE
[Sega Ages - Columns Arcade Collection (Japan)] Artefacts sur le premier bloc...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1524]
Kronos 2.6.1 Public

Je sais pas si j'ai pointé, le bon sprite mais tous les autres ont un color bank à 00000000 sauf lui.

![image](https://github.com/FCare/Kronos/assets/12481242/7670de61-88aa-4867-963a-54e4d1ad228e)

**Comment by BenjaminSiskoo** [comment]
![image](https://github.com/FCare/Kronos/assets/12481242/79080790-da50-4f9f-b449-1726381594f6)

**Comment by fafling** [comment]
Problème présent aussi dans la dernière WIP.

Sur la console, le jeu n'a aucune particularité graphique pour ces sprites.

On trouve effectivement dans la liste de dessin du VDP1 d'autres commande avec la même texture qui ne diffèrent que par la color bank (en-dehors des coordonnée de dessin), et qui ne posent pas de problème.

Le jeu est en haute résolution horizontale sur le VDP2 et le VDP1. Le framebuffer est donc en 8 bpp.
Dans ce cas, l'octet de poids fort de la color bank n'est pas pris en compte par le VDP1 pour dessiner, quelle que soit sa valeur.
Et en l'occurrence, l'octet de poids faible de la color bank n'est pas pris en compte non plus puisqu'il s'agit de textures 8 bpp.

Kronos semble se comporter comme s'il dessinait un pixel sur 2, et avec une palette incorrecte.

Testé avec le redump.

**Comment by FCare** [comment]
Fixé sur la wip sequential_vdp1
