### ISSUE TITLE
[Sonic Jam] Blue Sphere Special Stage Flickering

### ISSUE THREAD

**Issue by TheCommandoChicken** [FCare/Kronos#1525]
What's the full name of the game (including region) ?
Sonic Jam (USA)

What's your frontend ? (standalone, libretro, ...) ?
Retroarch 1.17.0

What's your OS ? (windows, linux, OSX, ...) ?
Steam OS

What's your hardware ? (CPU, GPU, ...) ?
Steam Deck (Original Model)

What's the storage type of the game (official cd, burned cd or cd image) ?
CD Image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)
.cue/.bin

Are you using any setting different from default ? If so, precise
Output to original resolution is on, no other setting has been changed.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this
The backgrounds of the blue sphere special stages appear to flicker back and forth while scrolling. The objects scroll normally. Given how the stages are programmed I suspect this to be a palette issue.

**Comment by BenjaminSiskoo** [comment]
Thanks do you have sa savestate ?

**Comment by fafling** [comment]
The problem happens in public v2.6.1 and in the last WIP.

It appears in the december 6th 2019 WIP that fixes incompletely the color RAM changes during display (#695 ).

Can be reproduced by selecting Game > Sonic 3 > Extra game > Special stage.

The sphere background that flickers is on NBG0 :
![image](https://github.com/FCare/Kronos/assets/7624262/852505c8-9445-4da0-9f1f-6e488403d1e7)

The layer is using line scroll and vertical cell scroll.

The resolution is not interlaced.

Tested with the original US CD.

**Comment by FCare** [comment]
Two consecutives frames: balls are moving before the ground. It gives the impression of the flickering
![image](https://github.com/user-attachments/assets/7cc83a3e-a2db-485e-9392-0bfe034bb22a)

**Comment by fafling** [comment]
The background sphere goes regularly back and forth which it shouldn't do.

[Capture vidéo du 27-08-2024 15_25_17.webm](https://github.com/user-attachments/assets/db20b0e0-4846-4039-80ff-572bd9584b76)

**Comment by fafling** [comment]
Fixed by 6732031
