### ISSUE TITLE
Game will not scale to window size

### ISSUE THREAD

**Issue by Tatsh** [FCare/Kronos#1530]
What's the full name of the game (including region) ?

n/a

What's your frontend ? (standalone, libretro, ...) ?

Qt

What's your OS ? (windows, linux, OSX, ...) ?

Linux

What's your hardware ? (CPU, GPU, ...) ?

Intel 11th gen, Nvidia 3060

What's the storage type of the game (official cd, burned cd or cd image) ?

CD Image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)

Cue/bin.

Are you using any setting different from default ? If so, precise

I have tried defaults and the same issue occurs.

Did this game work previously ? Do you remember when ? Is it happening with other games ?

n/a

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

The game renders at the bottom of the screen and only at a very small size relative to the window or screen. No setting or resizing the window seems to fix this.

![Panzer Dragoon (USA) (5S)_16_04_2024-02_45_48](https://github.com/FCare/Kronos/assets/724848/8745ab3a-5674-46ff-8fdb-eb8b37262761)

**Comment by FCare** [comment]
this is working on other configurations. It looks it comes from your environment.
