### ISSUE TITLE
[Debug slave SH2] Blocage après ajout de breakpoints mémoires

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1531]
Présent en v2.6.1 publique et dans la dernière WIP.

Pour reproduire :

- Dans Paramètres > Général > Avancé, mettre l'interpréteur SH2 à "SH2 Kronos Debug Interpreter".
- Lancer l'émulation.
- Pendant l'animation du bios, aller dans Débug > SH2 Esclave, onglet Breakpoints.
- Ajouter une interruption mémoire en 06002000 (adresse quelconque), en lecture word ou long, ou écriture long.
- L'émulation ou l'émulateur se bloque dès qu'on fait fermer.

**Comment by FCare** [comment]
pas reproduit sur sequential_vdp1

**Comment by fafling** [comment]
Reproduit chez moi sur la dernière WIP sequential_vdp1 (baf885a).
