### ISSUE TITLE
[VDP2 Debug] Kronos se ferme avec l'option Save As Bitmap...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1534]
Kronos 2.6.1

Quand on veut sauvegarder une couche via l'option Save as bitmap, Kronos se ferme tout seul. 

Le problème concerne le jeu Flashback de VBT. Pas de soucis avec les redumps.

![image](https://github.com/FCare/Kronos/assets/12481242/500b2cfc-1275-4160-a40b-826a7c632a29)

Iso du jeu : 

[trck2.zip](https://github.com/FCare/Kronos/files/15271624/trck2.zip)

**Comment by BenjaminSiskoo** [comment]
Sur l'écran press start screen (et pas ceux d'avant), si je veux sauvegarder vers le bitmap sur la couche Sprite, Kronos se ferme.

![image](https://github.com/FCare/Kronos/assets/12481242/4c85da79-eacd-4451-b0a7-5d6d9e7242bc)

Est ce rel:atif au bug qui est sur le press start screen ?

https://github.com/FCare/Kronos/issues/1510

**Comment by fafling** [comment]
Plantage reproduit en v2.6.1 publique et dans la dernière WIP en essayant de sauvegarder un des 3 écrans de logo au démarrage du redump de Doom (Japan).
Ce sont aussi des bitmaps 256 couleurs affichés en haute résolution (mais de taille 1024x512 et affichés par le NBG0).
![image](https://github.com/FCare/Kronos/assets/7624262/dbb96300-2361-4435-8566-8b6ea4bee145)
