### ISSUE TITLE
Kronos 2.6.1 - how choose GPU render ?

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#1535]
Hello,

I have a question or issue,, how i choosing the GPU's render ?
I have a notebook with two GPU, intel HD shit and Nvidia 960M
kronos launch the render with GPU primary, is intel, but this GPU not rending the perf / low / graphicals sparks ect...

**Comment by fafling** [comment]
Hello, have you tried this : [https://nvidia.custhelp.com/app/answers/detail/a_id/5035/kw/nvidia%20control%20panel/related/1](https://nvidia.custhelp.com/app/answers/detail/a_id/5035/kw/nvidia%20control%20panel/related/1) ?

**Comment by CloudFR** [comment]
Wow is working great ! thank you very much for this tips !
