### ISSUE TITLE
[NASCAR 98 (Europe)] Filtre Deinterlacing OSSC Bob fait trembler l'image...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1537]
Kronos 2.6.1 Public

Première partie de vidéo avec le filtre et seconde partie sans le filtre.

https://www.youtube.com/watch?v=6mfi6hrFiOE

**Comment by fafling** [comment]
Le jeu est en single density interlace sur le VDP2.
L'écran titre affiche une image différente à chaque champ pour lui donner la même résolution que si elle était affichée en double density interlace.
Même problème de tremblements avec le désentrelacement OSSC que dans les autres jeux avec le même cas de figure (#991).

**Comment by BenjaminSiskoo** [comment]
Comportement normal
