### ISSUE TITLE
3D Control Pad Axis Setting not correct

### ISSUE THREAD

**Issue by Nima-Haula** [FCare/Kronos#1538]
I used microsoft xbox360 pad on pc 

when i play NiGHTs I need setting 3d control pad 

I choose input -> SDL joystick Interface -> 3D control pad

when i set analog pad Axis X (left) and Axis Y (Down) 

the analog pad  work not right , left and down not work correct

when i try use 3d cotrol pad on panzer dragoon saga 

the analog pan not work the same

**Comment by BenjaminSiskoo** [comment]
Can you try with Kronos 2.6.2 ?
