### ISSUE TITLE
Random number generator, working on real hw, but exit at startup (back to bios) on kronos 2.6.1

### ISSUE THREAD

**Issue by willll** [FCare/Kronos#1543]
What's the full name of the game (including region) ?

N\A

What's your frontend ? (standalone, libretro, ...) ?

QT

What's your OS ? (windows, linux, OSX, ...) ?

uname -a
Linux will-Inspiron-5759 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

What's your hardware ? (CPU, GPU, ...) ?

     *-memory
          description: System memory
          physical id: 0
          size: 16GiB
     *-cpu
          product: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          version: 6.78.3
          size: 2500MHz
          width: 64 bits
        *-display
             description: VGA compatible controller
             product: Skylake GT2 [HD Graphics 520]
             vendor: Intel Corporation

What's the storage type of the game (official cd, burned cd or cd image) ?

ISO file

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)

cue\bin

Are you using any setting different from default ? If so, precise

No

Did this game work previously ? Do you remember when ? Is it happening with other games ?

No

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

[Math_-_Random_image.zip](https://github.com/user-attachments/files/15928098/Math_-_Random_image.zip)

Linker script  :
 
OUTPUT_FORMAT(coff-sh)
SECTIONS {

	SLSTART 0x06004000 : {
		___Start = .;
		*(SLSTART)
	}

	.text ALIGN(0x20) :
	{
		* (.text)
		*(.strings)
		*("SEGA_P")

		*(.eh_frame_hdr)
		*(.eh_frame)
        __etext = .;
	}

	SLPROG ALIGN(0x20): {
		__slprog_start = .;
		*(SLPROG)
		__slprog_end = .;
	}

	.tors  ALIGN(0x10) :
	{
		___ctors = . ;
		*(.ctors)
		___ctors_end = . ;
		___dtors = . ;
		*(.dtors)
		___dtors_end = . ;
	}

	.data ALIGN(0x10):
	{
		* (.data)
		__edata = . ;
	}

	.rodata ALIGN(0x20) :
	{
		*(.rodata)
	}

	.bss ALIGN(0x10) (NOLOAD):
	{
		__bstart = . ;
		*(.bss)
		* ( COMMON )
		__bend = . ;
		_end = .;
	}

	HEAP ALIGN(0x10)(NOLOAD):
	{
		__heap_start = .;
	}

	WORK_AREA_DUMMY 0x0000000(NOLOAD):
	{
		*(WORK_AREA_DUMMY)
	}

	work_area_start = 0x060FF000 - SIZEOF(WORK_AREA_DUMMY);

	WORK_AREA work_area_start (NOLOAD):
	{
		__heap_end = .;
		*(WORK_AREA)
		__work_area_end = .;
	}
}

**Comment by FCare** [comment]
There is no ELF header in the elf file so addr2line can not use it and there is no source of your test to debug.
CAn you please share a valid elf or an access to the source code?

**Comment by ReyeMe** [comment]
Sharing new build 
[Math - Random.zip](https://github.com/user-attachments/files/16714240/Math.-.Random.zip)

**Comment by FCare** [comment]
The new build is working perfectly on kronos 2.6.1

It looks like old build system was creating an issue
