### ISSUE TITLE
Resident Evil and Deep Fear--1080 Resolution and higher / Window Size 'Native' settings don't work in 2.6.1

### ISSUE THREAD

**Issue by JasonFyre2k** [FCare/Kronos#1545]
What's the full name of the game (including region) ?
Resident Evil (USA) / Biohazard (JPN) / Deep Fear (EUR)

What's your frontend ? (standalone, libretro, ...) ?
Kronos 2.6.1 Standalone and Retroarch with Kronos 2.6.1 core

What's your OS ? (windows, linux, OSX, ...) ?
Windows 11

What's your hardware ? (CPU, GPU, ...) ?
CPU: 13th Intel i7-13700F, 2100Mhz, 16 Cores, 24 Logical Processors
GPU: RTX 4070
Ram: 16 gb 5600

What's the storage type of the game (official cd, burned cd or cd image) ?
cd image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)
cue/bin

Are you using any setting different from default ? If so, precise
All settings are default aside from resolution/window size settings.

Did this game work previously ? Do you remember when ? Is it happening with other games ?
Yes. In 2.3.1 and older versions the resolution/window size settings worked properly. I can't find any Windows builds between 2.3.1 to 2.6.1 so it may or may not be an issue in releases between those two.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this
In Kronos 2.6.1, 1080 Resolution and above, in retroarch, and setting the Window Size to Native(current resolution of window) in the Standalone version doesn't seem to work. The 3D graphics look excessively jaggy and blocky even at 1080--which wasn't the case in older versions. This happens in Resident Evil/Biohazard and Deep Fear. I haven't tested other games. Below are some screenshots from Resident Evil:

Kronos 2.6.1 core in Retroarch with Resolution at 1080:
![RetroArch Kronos v2 6 1 3646a3f 7_11_2024 7_53_55 AM](https://github.com/FCare/Kronos/assets/126629912/97ffd6a1-ddd7-4dc8-a396-bccc01f9c59a)

Kronos 2.6.1 standalone with Window Size set to Native (current size of window) on a 4k screen
![Kronos v2 6 1 7_11_2024 8_14_28 AM](https://github.com/FCare/Kronos/assets/126629912/d2823647-1d95-4518-a316-6ed9dbcd58ad)

Below is how it should look;
Kronos 2.3.1 standalone** at 1080:
![Kronos Triggered v2 3 1 7_11_2024 7_58_22 AM](https://github.com/FCare/Kronos/assets/126629912/211f94d2-c853-42df-943c-f7093068859e)

Kronos 2.3.1 standalone** at 4k:
![Kronos Triggered v2 3 1 7_11_2024 7_59_19 AM](https://github.com/FCare/Kronos/assets/126629912/7839be89-0585-4b5b-ab3b-9d790adaacc8)

**I actually can't find any official windows binaries for Kronos 2.3.1(only source code) - or most versions prior to 2.6.1 for that matter - so I'm using the windows binaries from the forked 2.3.1 build from here:
https://github.com/jamalzed/Kronos_Triggered

**Comment by FCare** [comment]
Upscale is not a precise process. Saturn  way of rendering SD can not be upscaled without generating artifacts. 2.3.1 was generating a lot of artifacts. So upscale pipeline has been reviewed. This generated some regressions on these games but tfixes many others.
There is no plan to fix this.
