### ISSUE TITLE
add new H1 arcade games Cool Riders, Aqua Stage

### ISSUE THREAD

**Issue by soundsnow** [FCare/Kronos#1550]
System H1 (c) 1994 Sega
hardware similar to the Saturn
Main CPU: Hitachi SH-2 × 1
Cool Riders (1995)
Aqua Stage (1995)

**Comment by barbudreadmon** [comment]
It doesn't look like a saturn-based arcade hardware to me.

**Comment by soundsnow** [comment]
> It doesn't look like a saturn-based arcade hardware to me.

|CPU|H1|Saturn|
|---|---|---|
|Hitachi SH-2|28 MHz|28 MHz|
|Hitachi SH-2| |28 MHz|
|Hitachi SH-1|16 MHz|16 MHz|
|Motorola MC68000|16 MHz|11.2896 MHz|
|Sega SCUDSP| |14.318181 MHz|

|Audio Chips|H1|Saturn|
|---|---|---|
|Yamaha YMF292-F SCSP|22.579 MHz|22.579 MHz|
|Yamaha YMF292-F SCSP|22.579 MHz| |

**Comment by barbudreadmon** [comment]
Well, there are legions of arcade boards sharing 1 or more chips with the saturn, but saturn's 2 VDPs and how its chips interact with each others are its defining features, and the focus of most of the Kronos project's activity.

**Comment by BenjaminSiskoo** [comment]
for now, Only saturn and STV are supported on Kronos. There are lot of works to do. I think @FCare is focus on this 2 system. Anyway,  your report is interesting, I neverd heard about the H1 :)
