### ISSUE TITLE
"Cannot identify Windows ATPI driver"

### ISSUE THREAD

**Issue by ghost** [FCare/Kronos#1554]
So, I have downloaded Kronos to play Policenauts, and when I was setting up stuff like BIOS and Controllers, it appeared a notification that Kronos cannot identify Windows ATPI Driver and then another notification that Kronos cannot initialize.

I saw that the ATPI driver is related to CD driver, something my notebook doesn't have.

Now what?

**Comment by BenjaminSiskoo** [comment]
- Download Kronos 2.6.2
- Unzip it
- don"t use an old kronos.ini. There is blank kronos.ini in the archive.
- Launch Kronos.
- Choose the path to the real bios.
- Set up your controller.
- Close Kronos.
- Launch Kronos then Policenauts.
It should be work :)
