### ISSUE TITLE
Does not build on Arch Linux x86_64

### ISSUE THREAD

**Issue by nerdistmonk** [FCare/Kronos#1555]
Make fails on latest Kronos git.

Arch Linux x86_64 (updated as of this morning, GCC 14.2.1)
AMD Ryzen 3600x, 32gb Ram, AMD RX-7600 GPU 8GB

[build.log](https://github.com/user-attachments/files/17001478/build.log)
[cmake.log](https://github.com/user-attachments/files/17001479/cmake.log)

**Comment by FCare** [comment]
Issue comming here:
-- Performing Test VARIADIC_MACROS_OK
-- Performing Test VARIADIC_MACROS_OK - Failed

It looks C99 Variadic macro are not supported on your distro

**Comment by nerdistmonk** [comment]
Your change to the code fixed the compilation problem, Kronos now builds and runs, but I do not seem to have an opengl video core despite cmake reporting it found opengl and glew (and even says "OpenGL Video Core available" during configuring.

**Comment by nerdistmonk** [comment]
[make.txt](https://github.com/user-attachments/files/17006935/make.txt)

Attached latest make logs.
