### ISSUE TITLE
[Alien Trilogy (Europe) (En,Fr,Es,It) (4S)] Scintillement barre de munition et escalier...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#1561]
Kronos du 20/10/2024

Quand on monte ou descend les escalier, la barre de munition en bas a gauche affiche sur les 2 dernières lignes des munitions, les marches de l’escalier.

https://youtu.be/_fsRGKA-PRA

**Comment by fafling** [comment]
Le bas des balles de la barre de munition est transparent aussi sur la console. Ce n'est pas un bug de Kronos.
