### ISSUE TITLE
[Virtual Open Tennis (USA)] Sprites manquants à l'écran titre et dans les menus

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#1573]
En v2.6.2 publique comme dans la dernière WIP, des sprites sont manquants à l'écran titre et dans les menus (à gauche la dernière WIP, à droite l'affichage correct en v2.5.0 publique) :
![image](https://github.com/user-attachments/assets/4318a855-4e11-4120-adc8-bc115f4b2277)

Ces sprites ne figurent pas dans la liste de commandes du VDP1.

Le problème apparaît en 1ère WIP du 18/12/2023 (341106d) qui fixait la rémanence des crédits de Fighters megamix.

Dans la dernière WIP du 17/12/2023 (145c281) où ils apparaissent, on les voit dans la liste de commande, par exemple sur l'écran titre :
![image](https://github.com/user-attachments/assets/632a3c12-2935-4643-b88f-18d956790830)

Cette même commande dans la dernière WIP :
![image](https://github.com/user-attachments/assets/a0b849f1-8378-4389-82d3-195cc2ca7322)

Testé avec le redump.

**Comment by FCare** [comment]
commit coupable: 5413db5d3e670d2923e29ed882e9ea8ca6d43db3

**Comment by BenjaminSiskoo** [comment]
C'est ok pour moi et toi @fafling ?

**Comment by fafling** [comment]
Oui c'est réglé.
