### ISSUE TITLE
please make an appimage for linux

### ISSUE THREAD

**Issue by Nassi88** [FCare/Kronos#1575]
What's the full name of the game (including region) ?

What's your frontend ? (standalone, libretro, ...) ?

What's your OS ? (windows, linux, OSX, ...) ?

What's your hardware ? (CPU, GPU, ...) ?

What's the storage type of the game (official cd, burned cd or cd image) ?

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)

Are you using any setting different from default ? If so, precise

Did this game work previously ? Do you remember when ? Is it happening with other games ?

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

**Comment by Nassi88** [comment]
please make an appimage for linux

**Comment by FCare** [comment]
Appimage will not be supported. I added .deb package compilation for official releases.

**Comment by Nassi88** [comment]
Please bro appimages are much better for emulators. Its Komplete portable and works on all distros. Think aboud it pleas

**Comment by FCare** [comment]
I am the only maintainer and too much work. I won't add this myself. I am open to merge requests.
