### ISSUE TITLE
OpenGLES still available?

### ISSUE THREAD

**Issue by beudbeud** [FCare/Kronos#1576]
Hi, i try to build libretro core with support of OpenGLES, after many patch for can make build i get segfault.

So can you tell me if this option is still available and work?

Thanks

**Comment by FCare** [comment]
No it is not supported anymore

**Comment by FCare** [comment]
For details, Kronos is based on compute shader which are only supported in openGLES3.1
I did not found an embedded device with enough power which has openGLES3.1 support but not openGL COre 4.3.

A better option than focusing on OpenGLES would be to add vulkan support.

**Comment by beudbeud** [comment]
The raspberry pi 5 support of openGLES3.1, but you think it's not enough pwoerful for make run at 60fps ?

**Comment by FCare** [comment]
Is the support complete? I remember rpi4 openGL support that was buggy. If you port the compute shaders to openGLES3.1, it will run. But I doubt it will go 60 fps everywhere. It does not go 60 fps on some desktop low end PC.

**Comment by beudbeud** [comment]
I tried to build for pi5 I got some issue with shaders I fix it 

https://gitlab.com/recalbox/recalbox/-/blob/b50a09053016cd57ba78b4da9ea927c50d8e3528/package/libretro-kronos/0004-fix-shaders.patch

but at the end for now I have Segfault

**Comment by FCare** [comment]
I think some API need to be rewrited (usage of some buffers). It might compile but openGL function pointers are null, so you got the NPE.

**Comment by beudbeud** [comment]
okay, that it's totally out my competency.

**Comment by beudbeud** [comment]
It will be nice to have Vulkan but the black dot with Vulkan there aren't support of CRT Switchres
