### ISSUE TITLE
[Capcom Generation Vol.4] Problème Porte Hélico...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#18]
UoYabause 0.5.6
![1mercszcp4](https://user-images.githubusercontent.com/12481242/32492197-cbe51690-c3b9-11e7-9af8-a94134219632.JPG)

**Comment by FCare** [comment]
Comment on fait pour arriver a cet ecran?

**Comment by BenjaminSiskoo** [comment]
Tu lances le jeu Mercs 2 (c'est le deuxième dans la liste) et ensuite c'est au début du jeu in game

**Comment by FCare** [comment]
L'helice aussi deconne... Ca a l'air de venir d'un probleme de rotation du rendu...

**Comment by BenjaminSiskoo** [comment]
Corrigé sur la branche rework du 20.04.2019 \o/

**Comment by fafling** [comment]
Dans la WIP du 13/10, tout n'était pas bon. L'hélico était OK dans le 2ème jeu, mais il y avait une anomalie dans l'intro, et les sprites dans le 1er jeu étaient 2 fois trop petits en hauteur.
Le problème sur l'hélico est réapparu en WIP accurate_vdp1 du 15/10. Par contre, le 1er jeu est corrigé.
@BenjaminSiskoo Est-ce que tu peux rouvrir ?

Les sprites sont dessinés dans le framebuffer comme si les jeux étaient affichés à l'horizontale. Le VDP2 demande au VDP1 de lire le framebuffer d'affichage avec une rotation de 90° et avec un downscale pour adapter la largeur du framebuffer à la hauteur de l'écran. En effet, c'est bien le VDP1 qui lit le framebuffer d'affichage et envoie un flux d'octets au VDP2, vu que le VDP2 n'a pas de bus qui le connecte aux framebuffers, mais un il a un canal de communication 8 bit avec le VDP1, et le VDP1 fait ça en parallèle de ses opérations de dessin sur l'autre framebuffer.

Ce sont les paramètres listés p. 159 de la doc du VDP2 qui servent à modifier la lecture du framebuffer par le VDP1. Ils sont pris sur le paramètre de rotation A.
La lecture du framebuffer doit se faire avec les formules qui sont p. 152.
Attention, les paramètres de rotation du VDP2 servent à transformer les coordonnées de l'écran dans le référentiel de la texture, ici le framebuffer, et non l'inverse.

**Comment by BenjaminSiskoo** [comment]
Kronos du 26/03/2020 (commit VF Remix)

L'affichage des sprites et tourné de 90° vers la gauche :

![capcomgen4](https://user-images.githubusercontent.com/12481242/77639359-f10a2300-6f58-11ea-9fd0-f4d2b5942f27.PNG)

savestate :  

[capcomgen4.zip](https://github.com/FCare/Kronos/files/4386683/capcomgen4.zip)

**Comment by BenjaminSiskoo** [comment]
Corrigé avec kronos20231129_ea0eace
