### ISSUE TITLE
[Request] Update some options of newest devmiyax Yaba Sanshiro v2.2.0

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#181]
Since Yaba Sanshiro v2.2.0 has been released, I downloaded it and I see some differences with Kronos. 

The most important, is that Yaba shansiro have an option "Under video options" to set the internal resolution at 4x, and Kronos only can be set at 2x. 

Other options are missing like:
- "Use integer pixel scaling"
- Window resolution
- Fullscreen resoluton
- Triangles using perspective correction.

Under audio settings there are one missing option: Time Synchronization Mode.

I´m sorry but... if Kronos is a fork of Yaba sanshiro... Kronos should include all these options right? At least it will be awesome to include, in order to improve emulation.

Sorry for any inconvenience, and thanks a lot for your awesome work!

**Comment by LuismaSP89** [comment]
Edit:

This is very noticeable specially in 3D rendering, where Yaba Sanshiro looks very good, but Kronos shows a low rendering artifacts:


**Yaba Sanshiro:**
![yaba sanshiro 2](https://user-images.githubusercontent.com/12205048/45592319-e3d6a600-b969-11e8-9020-93e9b466ad10.jpg)

**Kronos:**
![kronos2](https://user-images.githubusercontent.com/12205048/45592316-e33e0f80-b969-11e8-8d7d-492bce9d38a6.jpg)

**Yaba Sanshiro:**
![yaba sanshiro 1](https://user-images.githubusercontent.com/12205048/45592317-e3d6a600-b969-11e8-8f16-c3166041a166.jpg)

**Kronos:**
![kronos1](https://user-images.githubusercontent.com/12205048/45592320-e3d6a600-b969-11e8-9e82-1a586285fd08.jpg)

**Comment by FCare** [comment]
Can you please provide the name of games and the system you are running on (android, windows, linux)?

**Comment by LuismaSP89** [comment]
@FCare Of course, sorry for no provide it before.

The games are: Deep fear (Screenshot of beginning of the game CD1) and Shining Force 3 - Premium disk (This is a disk with a gallery of characters of the game)

My specs:
Windows 10 x64
I7 4790k   4.4Ghz
16GB RAM DDR3
GTX 970 4GB GDDR5
