### ISSUE TITLE
Shortcuts bug

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#183]
It seems that this problem happens too in Yabause sanshiro of devmiyax.

Shorcuts can´t be changed, if you try to change one "For example the exit ctrl+Q" for "Esc" key, it changes only while the emulator is open. When you close it and open again, all the changes are lost, this happens in all the shortchut changes you made.

Other problem is with the savestate/loadstate shortcut... it´s the same! Then, if you try to load a state, it saves and you only can load if you navigate through the menu with your mouse, but can´t use the shortcut for save/load.

**Comment by BenjaminSiskoo** [comment]
Fixed
