### ISSUE TITLE
[Bug Too] Problème d'affichage avec l'écran Pause...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#190]
Kronos 1.4.5 :

Peut être un problème de VDP1.

![kronosbugtoo](https://user-images.githubusercontent.com/12481242/45742519-b009b380-bbe9-11e8-9e7b-eada585619fe.jpg)

**Comment by BenjaminSiskoo** [comment]
Kronos du 20/10/2018 : 

![bugtoo](https://user-images.githubusercontent.com/12481242/47266612-62120380-d539-11e8-8299-03a92acb2e28.PNG)

**Comment by fafling** [comment]
C'est encore un exemple de copie du framebuffer, mais cette fois la destination finale est la VRAM du VDP1. Cette copie est utilisée comme une texture RGB pour redessiner le framebuffer à chaque frame avant de plaquer dessus le sprite "Pause". C'est cette commande qui devrait le dessiner :

![capture_bug_too_pause](https://user-images.githubusercontent.com/7624262/52601529-5edfb200-2e5f-11e9-97c3-40509005bb7c.JPG)

**Comment by BenjaminSiskoo** [comment]
Kronos branche rework  du 17 Avril 2019 Il n'y a plus l'écran noir sur la pause mais ce n'est toujours pas réglé
![bugtoo](https://user-images.githubusercontent.com/12481242/56324556-78f38480-616f-11e9-83d5-568b12c3d0ed.PNG)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 25/04/2019 et visible pour la première fois depuis que yabause existe

**Comment by fafling** [comment]
Il reste des problèmes en fonction de l'option OpenGL size :

- Si elle est réglée sur Original, il y a un léger zoom sur la texture copiée à partir du framebuffer quand on met en pause. La texture copiée à partir du framebuffer est correcte (sans aucun zoom) dans l'écran debug du VDP1. La commande de dessin n'effectue aucun zoom sur la texture. C'est peut-être lié aux tailles de sprites trop grandes détectées dans le HUD de Krazy Ivan.

![Capture_bug_too_opengl_ori](https://user-images.githubusercontent.com/7624262/56813871-33ede300-683e-11e9-841b-0984038ab74e.PNG)

![Capture_bug_too_opengl_ori_2](https://user-images.githubusercontent.com/7624262/56813882-36503d00-683e-11e9-8f67-3fbadca9dc83.PNG)

Texture complète du framebuffer exportée avec l'écran debug du VDP1. En comparant cette texture et ce qu'affiche Kronos, je remarque que l'image est toujours tronquée en haut et en bas de 3 à 4 pixels et sur les côtés de 4 à 5 pixels. Ces pixels sont affichés par la console.
![VDP1_bug_too_pause](https://user-images.githubusercontent.com/7624262/56813987-6e578000-683e-11e9-8e65-751922085942.png)

- Si elle est réglée sur 2x ou plus, la partie inférieure gauche du framebuffer est zoomée par l'émulateur en tant que texture copiée à partir du framebuffer et dessinée par le VDP1 pendant la pause (la texture zoomée est visible dans l'écran debug du VDP1) :

![Capture_bug_too_opengl_size2x](https://user-images.githubusercontent.com/7624262/56812888-25063100-683c-11e9-9f0f-64d583241463.PNG)

![Capture_bug_too_opengl_size2x_2](https://user-images.githubusercontent.com/7624262/56812908-2cc5d580-683c-11e9-8855-a7a112f928cb.PNG)

Un save state pour aller plus rapidement dans le jeu :

[bug_too_level_select.zip](https://github.com/FCare/Kronos/files/3121641/bug_too_level_select.zip)

**Comment by fafling** [comment]
Le problème d'OpenGL size est réglé en WIP du 07/05. Un nouveau bug est créé pour le reste #479
