### ISSUE TITLE
[Touge King Of Spirit 2] Couleur des graphismes étranges.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#197]
Kronos 1.4.5 :

![kronost22](https://user-images.githubusercontent.com/12481242/45953314-2f87f000-bff9-11e8-884d-2db4f74ee0fe.PNG)
![kronst2](https://user-images.githubusercontent.com/12481242/45953315-2f87f000-bff9-11e8-888b-343851d71cdb.PNG)

 Voici la vidéo du jeu sur saturn : https://www.youtube.com/watch?v=LGTmlfirZBU
Vers 5 minutes 10.

**Comment by FCare** [comment]
Le seul probleme est la couleur de la vitre arriere

**Comment by BenjaminSiskoo** [comment]
Les vitres arrières étaient correctes il y a moins de 2 semaines et là c'est plus le cas

**Comment by BenjaminSiskoo** [comment]
Corrigé en WIP du 05/10/2019
