### ISSUE TITLE
[Branche Extui_cache] Test et régression...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#20]
![1whizz](https://user-images.githubusercontent.com/12481242/32719707-94be85aa-c861-11e7-8034-58568ccdb436.JPG)
1) Amélioration :
Test du jeu Whizz : 
- Version de Devmiyax : ne boot pas.
- Version extui_align (FCare) : ne boot pas.
- Version extui_cache (FCare) : le jeu boot, mais les boutons ne semblent pas correctement fonctionner mais le jeu à l'air jouable. Et il dois manquer la vidéo d'intro.

2) Régression avec l'option frameskip limiter. L'option ne fonctionne plus ou est désactiver.

3) Resident Evil : 
- Version extui_align (FCare) : le jeu fonctionne sauf qu'on ne voit pas le menu.
- Version extui_cache (FCare) : le jeu ne boot plus, mais il y a un message d'erreur qui n'existait pas avant. 

Master SH2 invalid opcode

R0 =  00000005	R12 =  00000001
R1 =  FFFFFF80	R13 =  00000000
R2 =  00FFFF00	R14 =  00000002
R3 =  807FFF11	R15 =  060F988C
R4 =  060F9900	SR =   00000100
R5 =  00000006	GBR =  060FFC00
R6 =  060F9888	VBR =  06000000
R7 =  00000000	MACH = FFF00FFE
R8 =  060F988B	MACL = E31FFE5A
R9 =  01102100	PR =   060FDC2C
R10 = 00000000	PC =   060FEF52
R11 = 00000001

**Comment by BenjaminSiskoo** [comment]
Alone In The Dark : 
• Version extui_align (FCare) : la voiture ne bouge pas pendant la vidéo d'intro avant d'entrer dans le jeu. Et ensuite on voir le perso in game les boutons pour afficher l'inventaire fonctionne mais on peut pas déplacer le personnage.
• Version extui_cache (FCare) : on voit l'écran d'intro ou la voiture devrait avancer mais n'avance pas, puis quand on est censé être in game, voir le perso. Et en fait on voit la photo ci dessous.

![1_alone](https://user-images.githubusercontent.com/12481242/32720193-0e2a6912-c863-11e7-8cce-a7b2fd3a2db0.JPG)

**Comment by BenjaminSiskoo** [comment]
Area 51 : ne boot plus avec le cache. Alors que le jeu fonctionne.

**Comment by BenjaminSiskoo** [comment]
Juste des tests à titres d'infos. je sais que tu bosses dessus :)

- Avec les correctifs sorties le jeudi 16/11/2017. Area 51, démarre. Whizz on peut maintenant entrer dans le jeu. Plus de problèmes de contrôles.
- Defcon 5 : plantage juste avant d'entrer dans le train. Alors que le plantage se produit juste après.
- Plus de mémoire sur doom par exemple : on passe de 115 Mo avant le cache aux environs de 215 Mo.

**Comment by FCare** [comment]
Oui et le cache est pourtant désactivé...

**Comment by BenjaminSiskoo** [comment]
Defcon 5 (avec la branche extui-cache) : yabause plante aléatoirement. Ce jeu se lance avec la branche extui-align (le plantage se produit toujours au même moment après avoir pris le train et avoir choisie une destination).

![1errordefcon](https://user-images.githubusercontent.com/12481242/32950923-65c2b0c4-cba8-11e7-9a11-9942198fb5a3.JPG)

**Comment by BenjaminSiskoo** [comment]
Avec la désactivation du cache SH2, defcon 5 retrouve son état normal plus de plantage aléatoire
