### ISSUE TITLE
[BackGuiner - Yomigaeru Yuusha-tachi - Hishou-Hen Uragiri no Senjou] Menu is messed (NBG1 layer ?)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#200]
Kronos 1.4.5

il semblerait que cela vienne du NBG1

![kronosbackguimer](https://user-images.githubusercontent.com/12481242/45962701-fd828800-c010-11e8-9d1f-a031573c304e.png)

**Comment by BenjaminSiskoo** [comment]
Kronos 1.5.0 du 31/10/2018 :

Mieux ?

![back](https://user-images.githubusercontent.com/12481242/47793459-98603780-dd1e-11e8-92c1-9a9ceaa5830d.PNG)

**Comment by fafling** [comment]
Même problème en v1.7.0 et dans la dernière WIP, en bios réel ou émulé (après appui sur A+B+C+start voir #558 ), avec le CD d'origine.

Le NBG1 affiche normalement des fenêtres de dialogue dans les menus de l'écran titre et pendant le jeu.

La corruption est peut-être dû à la combinaison line scrolling / vertical cell scroll sur le NBG1 :
![Capture_backguiner_act_2_VDP2](https://user-images.githubusercontent.com/7624262/62090291-97881200-b26c-11e9-9caa-5a20d0d62b01.PNG)

Problème identique sur le 1er jeu #201 .

**Comment by fafling** [comment]
La combinaison line scrolling / vertical cell scroll est probablement utilisée pour stocker le bitmap du NBG1 de manière contigüe dans la VRAM du VDP2. Il y a d'autres jeux où cela fonctionne sans problème. C'est peut-être un souci de transfert ou d'écriture vers la VRAM car le bitmap doit être mis à jour par les CPU ou le SCU.

**Comment by fafling** [comment]
Toujours présent en WIP du 08/12 dans les 2 noyaux.

**Comment by fafling** [comment]
Fixé en WIP du 20/05/2021 par 51f1ad631760e723dbf1b5292dfb67601ee8ca9a.
