### ISSUE TITLE
[BackGuiner - Yomigaeru Yuusha-tachi - Kakusei-Hen Guiner Tensei] Menu is messed (NBG1 layer ?)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#201]
Kronos 1.4.5

il semblerait que cela vienne du NBG1

![kronosbackguimer](https://user-images.githubusercontent.com/12481242/45962892-7c77c080-c011-11e8-865d-13469a67ea33.png)

**Comment by fafling** [comment]
Fixé en WIP du 20/05/2021 par 51f1ad631760e723dbf1b5292dfb67601ee8ca9a.
