### ISSUE TITLE
[Brain Dead 13] Problème d'affichage (NBG1 ?)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#209]
Kronos 1.4.5 

En désactivant la couche NBG1 le jeu semble ok, ci dessous une photo du problème sans désactiver la couche :

![braindead](https://user-images.githubusercontent.com/12481242/46013060-95887c00-c0ba-11e8-9bce-36be2bd5c7c0.png)

**Comment by fafling** [comment]
Même problème en version WIP du 17/03.

Bizarrement le NBG1 a les mêmes adresses de map que celle du bitmap du NBG0, c'est sûrement pour ça qu'il affiche n'importe quoi : des indices de couleur en guise de pattern name table, ça marche moyen…

Bien sûr, il n'est pas affiché par une vraie console, mais il n'y a rien dans l'écran de debug du VDP2 qui l'explique. C'est peut-être un paramétrage manquant au niveau du registre de VRAM cycle pattern.

![Capture_brain2](https://user-images.githubusercontent.com/7624262/55996833-e3f91300-5cb8-11e9-96c4-bb977aa3a2ec.JPG)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 19.05.2021
