### ISSUE TITLE
[Baroque Report - CD Data File] Artefacts sous le dialogue...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#210]
Kronos 1.4.5

![baroque](https://user-images.githubusercontent.com/12481242/46077996-5160ae80-c182-11e8-8e93-251b87a422fa.PNG)

**Comment by BenjaminSiskoo** [comment]
Kronos du 14.10.2021
Mode CS/OpenGL
Built-in bios / Vrai bios
 Pas corrigé

**Comment by fafling** [comment]
Toujours présent en v2.3.1 publique et dans la dernière WIP, dans les 2 noyaux.

Il s'agit du menu juste après avoir appuyé sur start à l'écran titre.

Dans l'écran debug du VDP2, on voit que la résolution verticale est 256.
![image](https://user-images.githubusercontent.com/7624262/177219720-caa315b3-089a-483c-bc25-c3286af1486a.png)

C'est une résolution illégale en NTSC (donc en 60 Hz). La console l'affiche comme si la résolution verticale était 224 au lieu de 256 (on voit la zone de bordure en haut et en bas de l'écran), et la zone hachurée en bleu que Kronos montre en bas de l'écran n'est pas visible.

Par contre, si on switche la console en 50 Hz, la résolution verticale 256 est affichée en entier et on voit ce qu'affiche Kronos.

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Corrigé avec la WIP kronos20231122_7fa6739 grâce à ce fix je pense : https://github.com/FCare/Kronos/issues/1234
