### ISSUE TITLE
[Daikoukai Jidai Gaiden] Problème d'affichage sur le New Game (VDP1 ?)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#211]
Kronos 1.4.5

En désactivant le VDP1, new game disparait

![daikuke](https://user-images.githubusercontent.com/12481242/46137627-8f6cd980-c239-11e8-98d2-ed63021b40fa.PNG)

**Comment by FCare** [comment]
Fixé le 17 avril 2019

**Comment by fafling** [comment]
Comme signalé par @BenjaminSiskoo , en WIP accurate_vdp1 du 13/10 (et en extui-align du 11/09 dans les 2 noyaux), le sprite "New game" est affiché sur fond noir à l'écran titre, au lieu d'un fond transparent.
![Capture_Daikoukai_Jidai_Gaiden_acc_vdp1_20191013](https://user-images.githubusercontent.com/7624262/66790588-b05da680-eef0-11e9-800b-12bb3cfa8de1.PNG)

Le sprite utilise une texture RGB qui comporte effectivement un fond de pixels noirs (valeur hex 8000, vérifié dans l'éditeur mémoire de Yabause). Au niveau de la commande de dessin, rien ne justifie que ces pixels ne soient pas écrits, et ils ne sont pas tronqués car le framebuffer est sûrement de type 16 bit, sinon les autres pixels seraient corrompus.

Côté VDP2, rien ne justifie que ces pixels soient traités comme transparents par rapport à la couche NBG0 qui affiche le bateau derrière. Les sprites activent la color calculation, mais les pixels RGB ne remplissent pas la condition (priorité à 6 au lieu de 5).
![image](https://user-images.githubusercontent.com/7624262/66790528-670d5700-eef0-11e9-8474-4f384399a034.png)

La situation est donc similaire à la sélection des persos dans Fire pro, voir #643 , sauf qu'il n'y a pas d'invalid opcode cette fois qui justifieraient un état différent de la console. Resterait la possibilité d'un changement de paramètre pendant la période d'affichage, mais on en voit mal l'intérêt.

Ces 2 jeux dessinent donc des pixels RGB noirs et semblent s'attendre à ce que le VDP2 les traite comme transparents alors que rien n'indique qu'il le devrait. Il y a donc peut-être un comportement du VDP2 qui n'est pas documenté.

@FCare  Tu avais parlé de la transparent shadow comme cause possible, est-ce que ces 2 jeux l'activent (registre TPSDSL) ?

Testé avec le CD jap.

**Comment by fafling** [comment]
Fixé en WIP accurate_vdp1 du 28/10 en rendant transparents les pixels à 8000 d'un framebuffer RGB+palette quand la sprite window est activée.

**Comment by fafling** [comment]
Affichage correct dans les 2 noyaux en WIP du 29/11.
