### ISSUE TITLE
[Dark Savior] Ecran noir sur la fenêtre de dialogue...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#213]
Kronos 1.4.5 :

![darksaviordialog](https://user-images.githubusercontent.com/12481242/46139940-533c7780-c23f-11e8-8815-e4ab07cf8a4c.PNG)

**Comment by ner00** [comment]
Issue persists in Kronos 2.0.2, and additionally there is another visible glitch: the title screen transition is not working properly.

The title screen should show a mountain without the game title, and a few seconds later the title is dropped into the mountain. In Kronos, the title appears immediately before the animation ever drops it.

**Comment by BenjaminSiskoo** [comment]
Corrigé

**Comment by ner00** [comment]
> The title screen should show a mountain without the game title, and a few seconds later the title is dropped into the mountain. In Kronos, the title appears immediately before the animation ever drops it.

Seems that this is not fixed.
