### ISSUE TITLE
[Deadalus] Artefacts quand on tourne à droite ou à gauche...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#215]
Kronos 1.4.5 :

![daedalustourne](https://user-images.githubusercontent.com/12481242/46144913-f1373e80-c24d-11e8-9f70-49b738d0f8e4.png)

quand je fais une légère rotation sur la gauche :

![daedalustourne](https://user-images.githubusercontent.com/12481242/46144881-d2d14300-c24d-11e8-90cf-ab2c3d9a8dea.png)

**Comment by fafling** [comment]
Dans l'écran debug du VDP1, il y a des sprites dont les coordonnées dépasse les limites données par la doc du VDP1 (entre -1024 et 1023). Pas facile d'analyser ce qui se passe dans Deadalus car les textures ne sont pas très différenciées.

Par contre, on trouve le même problème dans:

- Night striker SS, quand on sort du tunnel au début du 1er niveau, il faut faire monter le véhicule tout en haut. Il y a une texture de route qui s'affiche en travers du framebuffer. On trouve là aussi des sprites avec ces textures et des coordonnées qui sont en-dehors de [-1024, 1023].

- Linkle liver story  #398 , à l'écran d'entrée du nom, il y a plusieurs sprites de différents alphabets avec des coordonnées là aussi en-dehors de l'intervalle. C'est le cas le plus facile à analyser, le sprite affiché en travers de l'écran a des coordonnées x comprises entre -1104 et -817. Apparemment, Kronos ne considère que les 11 bits de poids fort de la coordonnées -1104, ce qui donne 944. Cela correspond bien à ce qu'affiche Kronos : un zoom latéral x6 avec inversion de la texture traversant tout le framebuffer.

![Capture_linkle_WIP20190419](https://user-images.githubusercontent.com/7624262/56448688-995b4480-6311-11e9-8741-38c5e6701626.PNG)

![Capture_linkle_WIP20190419_2](https://user-images.githubusercontent.com/7624262/56448690-9ceecb80-6311-11e9-8401-7860f01a28ca.PNG)

La doc du VDP1 dit que le traitement de commandes avec des coordonnées dépassant les limites n'est pas garanti. Mais comme ce genre d'artifact ne se produit pas sur la console, c'est que le VDP1 ne procède pas comme ça.

Il y a un [document de Charles MacDonald](https://segaretro.org/Saturn_VDP1_hardware_notes_(2003-05-17)) qui indique qu'on peut utiliser un bit de plus pour les coordonnées que ce qui est marqué dans la doc du VDP1 sans que ça pose de problème (à la fin du document à partir de "Coordinates (CMDXA through CMDYD)"). Donc c'est 12 bits au lieu de 11, ce qui donne l'intervalle [-2048, 2047]. D'après MacDonald, c'est en-dehors de cet intervalle que les textures sont soit affichées de façon anormale, soit pas du tout.

Les coordonnées des sprites dans les 3 jeux ne dépassent pas l'intervalle [-2048, 2047]. Je crois que MacDonald a raison et que le VDP1 a sans doute été implémenté avec un bit de plus pour les coordonnées sans que ce soit documenté.

**Comment by fafling** [comment]
Plus de polygone en travers de l'écran dans la dernière WIP suite à la restriction sur les commandes du VDP1 (voir #500 ).

**Comment by fafling** [comment]
Donc on peut clore...
