### ISSUE TITLE
Kronos freezes at run on GPD Win 2

### ISSUE THREAD

**Issue by tapperp** [FCare/Kronos#216]
Trying to run Kronos 1.4.5 on GPD Win 2 with windows 10 and intel m3-7y30 cpu. 
https://en.wikipedia.org/wiki/GPD_Win_2

When I press f1 to run a game, nothing happens and Kronos just freezes and I must force close it. Same behavior with real or emulated BIOS. Tried all sorts of settings but same thing.

Is Kronos not compatible with this CPU?

NOTE: yaba sanshiro works perfectly on the same system.

**Comment by FCare** [comment]
I do not have such a device so I can not debug...

**Comment by tapperp** [comment]
I understand. :-( Sad though...

**Comment by barbudreadmon** [comment]
@tapperp good news, we might have figured out the deadlock issue on intel gpus
