### ISSUE TITLE
[DOOM] Problème de scintillements et graphismes manquant.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#22]
UoYabause 0.5.6 (commit du 21/11/2017)

En décochant la couche VDP1 les scintillements disparaissent

![1doom](https://user-images.githubusercontent.com/12481242/33073241-8e098680-cec2-11e7-9184-e927afa6dddb.JPG)

**Comment by FCare** [comment]
VDP1 Command table is full of zero...

**Comment by FCare** [comment]
Doom i using clipping method to only refresh part of the vdp1 fb. It is requesting drawcommands multiple time on the same line, on the same vdp1 frame, that can last more than one vdp2 frame. The solution ere is to have Textexue management and levels management dedicated to vdp1 and only do the rendering once the vdp1 frame is swapped, not before.

But, still ground and roof are missing

**Comment by BenjaminSiskoo** [comment]
Le jeu est presque jouable, il manque le sol et le plafond.

**Comment by FCare** [comment]
le sol et le plafond sont la mais la transparence deconne

**Comment by FCare** [comment]
La meme transparence semble se retrouver dans le jeu outrun!

**Comment by fafling** [comment]
C'est le même problème que dans Yaba Sanshiro : il y a une couche NBG1, sans doute entièrement noire, qui doit servir au shading des sprites par effet de transparence VDP2. Elle est intercalée entre les sprites et l'arrière plan affiché par la couche NBG0. Elle a un color calculation ratio à 0:32 pour la rendre invisible quand le plan des sprites n'est pas devant elle. Kronos applique ce ratio sur toute l'image ce qui ne respecte pas les règles de color calculation du VDP2 : ce ratio ne doit s'appliquer que sur les pixels où la couche NBG1 est la top image, c'est-à-dire les pixels où il n'y a devant elle aucune autre couche avec un pixel non transparent (dans le sens pixel contenant autre chose que le transparency code de la couche). Le noir de la couche NBG1 doit donc être opaque quand elle est derrière les sprites.

**Comment by BenjaminSiskoo** [comment]
Si jamais ca t'intéresse de faire la même chose avec d'autres bug report Kronos, ca serait sympa d'en profiter :)

**Comment by fafling** [comment]
Je vais jeter un oeil.

**Comment by FCare** [comment]
Ok, on va le faire en francais. En effet, le Color_replace doit bien utiliser la couche alpha. Le patch que j'ai fait pour Doom genere des regressions, notamment sur NBA Jam Extreme. Je vais faire un revert du patch de Doom.
Le pb vient donc bien du VDP2. Tu saurais m'indiquer dans la doc du vdp2 ou tu as compris que le color ratio 0:32 doit etre opaque dans certaines conditions?

**Comment by barbudreadmon** [comment]
@FCare çà parle aussi de çà ici : http://www.sega-16.com/forum/showthread.php?33231-Saturn-games-with-transparency-and-or-light-source-shading/page3

Edit : c'est aussi mentionné à la page 235 de http://antime.kapsi.fi/sega/files/ST-058-R2-060194.pdf

**Comment by fafling** [comment]
Effectivement c'est p. 234-236 de la doc VDP2 pour le mode normal de color calculation. Le VDP2 travaille toujours pixel par pixel. Pour chaque pixel, la fonction de priorité détermine quelle couche est au-dessus de toutes les autres (c'est la "top image"), et quelle couche est juste derrière (c'est la "second image"), expliqué p. 224 paragraphe "Priority function". Le mode normal de color calculation ne s'applique qu'à ces 2 1ère couches, donc la 2ème couche est opaque à toutes celles en-dessous d'elle.

Le dessin (mal fichu) de la figure 12.2 p. 236 l'illustre. Le screen A recouvre tout l'écran de pixels non transparent, c'est donc toujours la top image. C'est mal fichu car il devrait y avoir un triangle dans le screen B à la 1ère ligne. Ce triangle est la zone non transparente du screen B. Dans l'ordre de priorité, il est au-dessus du carré non transparent du screen C, qui est au-dessus du back screen. La second image est donc composée de tout le triangle du screen B, de la partie du carrée du screen C en-dehors de ce triangle, et du back screen pour le reste. Bien que le screen B porte un ratio de 20:12, il est toujours opaque (le triangle "mange" le carré dans les dessins de la 2ème ligne) car il n'est jamais en top image. Le dessin de droite de la seconde ligne montre que le ratio de 20:12 peut être utilisé pour calculer la transparence dans la zone du triangle si le ratio est pris sur la second image au lieu de la top image (registre CCRTMD p. 241), mais il s'agit toujours de transparence avec la top image, pas avec ce qui est sous la second image.

Dans Doom, le ratio est pris sur la top image. Elle est formée du plan de sprite quand il est non transparent et du plan de shading NBG1 en-dehors. La second image est formée du plan de shading NBG1 quand le plan de sprite est non transparent et du décor NBG0 en-dehors. On est en mode normal de color calculation donc la second image est opaque, donc le NBG1 l'est quand il en fait partie.

**Comment by FCare** [comment]
Le probleme c'est que le CCRTMD vaut toujours 0....

**Comment by fafling** [comment]
Ce qui correspond bien à un ratio pris sur la top image. Donc soit 0:32 quand c'est le NBG1, ce qui le rend invisible par rapport au ciel du NBG0, soit celui de la color bank des sprites ( je crois qu'ils sont toujours en mode palette), qui laisse voir partiellement le noir du NBG1.

Etrangement, le NBG0 porte un ratio de 31:1 avec color calculation active. A priori ce ratio ne sert jamais car cette couche ne fait jamais partie de la top image.

**Comment by fafling** [comment]
En WIP du 17/03, il reste des artifacts au sol et plafond, mais le shading est maintenant correct.
Cela corrige aussi les semi-transparences dans Street racer extra : l'ombre des voitures est maintenant opaque sous un nuage, et les nuages sont opaques derrière un élément semi-transparent du frame buffer, comme la carte ou les polygones proches de la caméra.
L'implémentation de la color calculation de base du VDP2 semble donc conforme à ce que fait la console.

**Comment by BenjaminSiskoo** [comment]
Je ferme le bug report et j'en ouvre un autre.
