### ISSUE TITLE
|Digital Dance Mix Vol. 1 - Namie Amuro] Ecran noir in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#221]
Kronos 1.4.5

![digitila naom](https://user-images.githubusercontent.com/12481242/46244605-8e21e500-c3d0-11e8-939a-5059b591b967.PNG)

**Comment by fafling** [comment]
Je n'ai pas d'écran noir en v1.7.0 publique.
@BenjaminSiskoo Est-ce que tu peux confirmer que c'est bon chez toi aussi ?
![Capture_namie_amuro_1 7 0](https://user-images.githubusercontent.com/7624262/59723781-dbc4d300-9227-11e9-8f21-a2be7de426de.PNG)

**Comment by BenjaminSiskoo** [comment]
Je réponds avec un peu de retard, J'ai toujours l'écran noir chez moi
