### ISSUE TITLE
Musique/SFX manquants dans les jeux...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#229]
3D Baseball : le speaker répéte le nom 2 fois.
Bomberman Wars : musique in game grésille.
Deroon Dero Dero : musique manquante au début.
Fighter Megamix
G Vector : musique manquante.
Hyper 3D Pinball : musique manquante
Independance Day : pas de musique/SFX.
J.League Goal Goal Goal : musique manquante.
Sega Ages : Outrun : autoradio.
Sega Ages : Fantasy Zone : le son boucle in game. Problème de son partout.
Virtual On

**Comment by fafling** [comment]
Aucune musique pendant le jeu dans King of fighters 95 jap, testé en v1.5.0, v1.6.0 et WIP du 17/03/2019 avec bios jap v1.01, que ce soit avec le CD d'origine ou avec une image ISO.
Avec le CD, il y a en plus un gel de Kronos pendant à peu près une minute à chaque fois que la musique devrait changer.
Avec le CD ou l'ISO, la musique peut être écoutée sans problème dans le CD player du bios.
Dans Yabause v0.9.14, avec le même CD, le jeu fonctionne avec la musique sans gel.
Le CD fonctionne sans problème sur console.

Fixé en accurate_vdp1, le son est OK dans la WIP du 05/10.

**Comment by fafling** [comment]
Steamgear Mash : aucun SFX en v1.6.0 et WIP du 17/03/2019 avec le CD d'origine. Les SFX fonctionnent dans Yabause v0.9.14.

Fixé par la WIP du 07/05.

**Comment by fafling** [comment]
Hissatsu : musique des pistes CD manquante dans la dernière WIP, en v1.6.0 et v1.5.0.
La musique peut être écoutée sans problème dans le CD player du bios.

Fixé par la WIP du 08/06.

**Comment by fafling** [comment]
Astal : plus de son pendant le jeu en v1.7.0 publique. Problème apparu en WIP du 30/04, celle du 28/04 a du son.
Le son revient si on met le jeu en pause, puis on sort de la pause.
Fixé en accurate_vdp1, le son est OK dans la WIP du 05/10.

**Comment by fafling** [comment]
Virtua cop : musique des pistes CD manquante dans la WIP du 28/06/2019, en v1.7.0 et v1.6.0.
La musique peut être écoutée sans problème dans le CD player du bios.

Fixé en accurate_vdp1, le son est OK dans la WIP du 05/10.
