### ISSUE TITLE
[Grandia] Carré rouge sur la moitié de l'écran (NBG0 ?)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#233]
Kronos 1.4.5 :

Sur la vidéo uniquement :

![grandia](https://user-images.githubusercontent.com/12481242/46403650-9fc9fc00-c6f2-11e8-8bc3-ec0fafa7809f.PNG)

**Comment by fafling** [comment]
Le problème est toujours présent en v1.7.0.
L'image est aplatie verticalement de moitié.
Affichage correct dans une video sur Youtube :
![Capture_grandia_video_youtube](https://user-images.githubusercontent.com/7624262/59569976-455ea900-9091-11e9-853d-4fe1585d5cc5.PNG)

La video est affichée par le VDP2 avec un bitmap sur le NBG0. Il utilise à la fois du line scrolling et du vertical cell scroll, probablement pour permettre un stockage contigu des lignes du bitmap dans la VRAM.
De plus, la résolution verticale est doublée avec le mode double interlaced. C'est peut-être une mauvaise prise en compte de ce doublement dans les fonctionnalités utilisées par le NBG0 qui cause l'aplatissement de la video.
![Capture_grandia_video_VDP2](https://user-images.githubusercontent.com/7624262/59570005-979fca00-9091-11e9-86a0-1f4f3ab9ff24.PNG)

**Comment by fafling** [comment]
Toujours présent en WIP du 01/12 dans les 2 noyaux.

**Comment by BenjaminSiskoo** [comment]
Présent Wip du 15/01/2020

**Comment by BenjaminSiskoo** [comment]
Kronos 14.10.2021 : idem

**Comment by fafling** [comment]
Fixé par la WIP du 20/09 (9bc596a).
