### ISSUE TITLE
[Hang On GP '95] Problème de taille de texture...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#234]
Kronos 1.4.5 :

![hangon](https://user-images.githubusercontent.com/12481242/46465775-044f8e80-c7b9-11e8-940c-af32fb8b0af2.PNG)

**Comment by BenjaminSiskoo** [comment]
Corrigé sur la branche rework du 15/04/2019

**Comment by BenjaminSiskoo** [comment]
Kronos extui et rework 

Retour du problème.

**Comment by BenjaminSiskoo** [comment]
Présent Wip du 15/01/2020

**Comment by fafling** [comment]
L'affichage est incorrect dans les 2 noyaux.

Les coordonnées du system clipping du VDP1 ne correspondent pas à la fenêtre VDP2 qui porte sur toutes les couches y compris les sprites.
![image](https://user-images.githubusercontent.com/7624262/72572290-60f98e80-38c2-11ea-96da-e8c45fabbe4d.png)
![image](https://user-images.githubusercontent.com/7624262/72572365-9a31fe80-38c2-11ea-9880-86ed2328863a.png)

Comme les graphismes VDP1 et VDP2 sont bien superposés sur la console, c'est qu'il y a une transformation du framebuffer pour lui faire matcher la fenêtre VDP2 : en supposant que la transformation amène le framebuffer exactement dans la fenêtre horizontalement, ce serait un décalage de 4 pixels vers la droite avec un étirement horizontal de 336 à 344 pixels. Comme indiqué par Benjamin, cette transformation n'est pas correcte dans Kronos.

Le framebuffer doit donc être de type rotation16 pour à la fois permettre cette transformation et aussi permettre au VDP1 de dessiner en mode half-transparency l'ombre de la moto.

En vue intérieure, cette transformation effectue en plus une rotation du framebuffer. En effet, cette rotation n'est pas faite par les coordonnées des polygones.
Affichage dans Kronos en noyau CS (3ème course) :
![image](https://user-images.githubusercontent.com/7624262/72573303-8d62da00-38c5-11ea-8c20-e948c15dd61f.png)
Affichage correct par la console :
![image](https://user-images.githubusercontent.com/7624262/72573240-4aa10200-38c5-11ea-8e00-5c7a78da93a1.png)

Cette transformation du framebuffer est paramétrée par les paramètres de rotation A du VDP2 qui sont aussi utilisés pour transformer le RBG0 :
![image](https://user-images.githubusercontent.com/7624262/72572770-e0d42880-38c3-11ea-8eac-997fbc4a49a9.png)

Seule une partie des paramètres de rotation A est utilisée pour transformer le framebuffer (p. 159 du mode d'emploi du VDP2). Le VDP2 envoie ces paramètres au VDP1, probablement à chaque hblank qui précède une ligne affichée à l'écran puisqu'il est possible de les modifier en cours d'affichage (Hang on GP n'a pas l'air de le faire). Le VDP1 utilise ces paramètres pour lire le framebuffer selon les équations données p. 152, et envoie chaque pixels lus au VDP2 au rythme où celui-ci les traite.

**Comment by fafling** [comment]
En WIP du 23/01, c'est en progrès, mais il y a toujours une différence avec la console dans les 2 noyaux (début le la 1ère course) :
- en OpenGL :
![image](https://user-images.githubusercontent.com/7624262/72949078-7e799d00-3d87-11ea-9636-410b1ac90322.png)

- en CS :
![image](https://user-images.githubusercontent.com/7624262/72948887-debc0f00-3d86-11ea-83c9-dca1105d968d.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé en CS mais pas en OpenGL du 03/04/2020

**Comment by BenjaminSiskoo** [comment]
Kronos 2.1.3 

Opengl 

![hangon95opengl](https://user-images.githubusercontent.com/12481242/90137133-7b6eea00-dd75-11ea-9120-103ff4df3053.PNG)

**Comment by BenjaminSiskoo** [comment]
Toujours présent en OpenGl avec la WIP du 20/10/2020

**Comment by BenjaminSiskoo** [comment]
Wip du 03/12/2020

Corrigé in game, il reste un bug 

![hangon95](https://user-images.githubusercontent.com/12481242/100949773-4bf21200-350b-11eb-8ebf-edf5b88898ac.PNG)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 21.05.2021
