### ISSUE TITLE
[HatTrick Hero S] FMV n'est pas affiché correctement (OpenGL)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#235]
Kronos 1.4.5 

![hattrick](https://user-images.githubusercontent.com/12481242/46466512-0581bb00-c7bb-11e8-8809-8620a4699731.PNG)

**Comment by BenjaminSiskoo** [comment]
Kronos 1.5.0 du 22.12.2018

Ca semble venir du RGB0

**Comment by fafling** [comment]
Bizarrement, les tribunes ne sont pas affichées par Kronos que pendant l'intro. Pendant le jeu, il n'y a pas de problème. Et pendant l'intro, le VDP2Viewer est correct alors l'affichage principal ne l'est pas.

![capture3](https://user-images.githubusercontent.com/7624262/52375603-5acb2300-2a60-11e9-9f3f-aea8ac9067cc.JPG)

**Comment by FCare** [comment]
Le vdp2 debug utilise l'implementation du rendu soft alors que l'ecran
utilise le rndu openGL. ce n'est pas la meme stack graphique...

Le mer. 6 févr. 2019 à 22:41, nicolas-charrier <notifications@github.com> a
écrit :

**Comment by fafling** [comment]
Je ne sais pas si ça a un rapport, mais il y a des priorités différentes entre l'intro et pendant le jeu :
- pendant l'intro, l'arrière plan RBG0 a une priorité à 7, la même que les sprites du VDP1 qui utilisent le registre 0.
![capture_hth_intro](https://user-images.githubusercontent.com/7624262/52755528-8d47c380-2ffe-11e9-9f0d-4a2ef1803686.JPG)

- pendant le jeu, l'arrière plan RBG0 a une priorité à 5 alors que tous les registres de priorité du VDP1 sont à 7.
![capture_hth_ingame](https://user-images.githubusercontent.com/7624262/52755539-989aef00-2ffe-11e9-9ed1-f52ed0bfc403.JPG)

**Comment by fafling** [comment]
En WIP du 28/06/2019, le public est affiché pendant l'intro si le nouveau paramètre compute shader est à on. S'il est à off, le problème est toujours présent.

**Comment by fafling** [comment]
Toujours présent en WIP accurate_vdp1 du 12/10.

**Comment by fafling** [comment]
Toujours présent en OpenGL uniquement dans la WIP extui-align du 19/11.

**Comment by BenjaminSiskoo** [comment]
En OpenGL + compute shader on, ca fonctionne il reste un artefact pendant la vidéo.

**Comment by BenjaminSiskoo** [comment]
Kronos du 03/04/2020

en openGL cassé 

![hattrick](https://user-images.githubusercontent.com/12481242/78379956-75048080-75d3-11ea-8489-94f98d95a2ab.PNG)

**Comment by BenjaminSiskoo** [comment]
Toujours présent en OpenGl avec la WIP du 20/10/2020

**Comment by fafling** [comment]
La pelouse du RBG0 devient incorrecte en noyau OpenGL en WIP du 17/12/2020.

**Comment by BenjaminSiskoo** [comment]
La pelouse in game est toujours incorrecte 

![image](https://user-images.githubusercontent.com/12481242/130222914-98b2854c-501a-4336-976c-0f1818b849e3.png)

savestate : 
[T-1102G_000.zip](https://github.com/FCare/Kronos/files/7020995/T-1102G_000.zip)

**Comment by BenjaminSiskoo** [comment]
La pelouse est corrigé. Testé avec la version du 07/10/2021. Il ne reste que la vidéo d'intro qui est toujours cassé.

**Comment by fafling** [comment]
Une autre différence entre le jeu et l'intro sur le RBG0 : le jeu switche de paramètre de rotation à l'aide de la table de coefficient, alors que l'intro utilise la rotation window.

**Comment by BenjaminSiskoo** [comment]
Le gazon in game est correcte en opengl, il reste juste la vidéo d'intro.

![image](https://user-images.githubusercontent.com/12481242/213047509-4b34d039-e29f-4abc-bd4a-0735c7e51b6a.png)

**Comment by BenjaminSiskoo** [comment]
Plus de support OpenGL
