### ISSUE TITLE
[Highway 2000] Problème de taille de texture en OpenGL...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#238]
Kronos 1.4.5 :

![higway2000](https://user-images.githubusercontent.com/12481242/46467935-9c03ab80-c7be-11e8-9bfb-8f402e2f1363.PNG)

**Comment by BenjaminSiskoo** [comment]
Corrigé sur la branche rework du 15/04/2019

**Comment by BenjaminSiskoo** [comment]
Kronos du 20.04.2019
Le soucis est de nouveau présent
![highway2000](https://user-images.githubusercontent.com/12481242/56455093-a9e3dd00-635a-11e9-8941-8274acdcc5d4.PNG)

**Comment by BenjaminSiskoo** [comment]
Corrigé sur CS mais pas en OpenGL le 03/04/2020

**Comment by BenjaminSiskoo** [comment]
Toujours présent avec la version wip du 20.08.2021

**Comment by BenjaminSiskoo** [comment]
Toujours présent avec la version wip du 13.12.2021

**Comment by fafling** [comment]
Toujours présent dans la WIP du 16/03/2022.

Toutes les couches, sprites inclus, ont un affichage limité par la fenêtre W0 qui fait 344 x 205 pixels, plus petite que la résolution horizontale de l'écran à 352 x 224 :
![image](https://user-images.githubusercontent.com/7624262/159790150-b44e3270-72d6-4c00-8ab2-c46decd47f1f.png)
![image](https://user-images.githubusercontent.com/7624262/159789233-7edcd42b-8da2-4662-aa7c-45056a38f6b5.png)

La zone de dessin du VDP1 est limitée à une taille différente de celle de la fenêtre W0 (336 x 256 pixels), et elle n'a pas le décalage horizontal de 4 pixels correspondant au début horizontal de la fenêtre :
![image](https://user-images.githubusercontent.com/7624262/159789324-c9f03e1a-7922-4fd7-a848-3a3b22373fbb.png)

Dans Mednafen, on voit que les bits TVM du registre TVMR du VDP1 valent 2. Le framebuffer est donc de type Rotation 16.
![image](https://user-images.githubusercontent.com/7624262/159788550-f5affee5-b5f7-4799-a4bf-70b13d2054b9.png)

Il y a donc certainement une transformation du framebuffer utilisant les paramètres de rotation A qui le décale, l'étire horizontalement et le compresse verticalement pour faire la taille de la fenêtre W0. Ces paramètres de rotation servent aussi à l'affichage du RBG0 :
![image](https://user-images.githubusercontent.com/7624262/159789046-c1ab9db0-d188-425d-8afc-fa638dc9a9c6.png)

Si on compare l'affichage en CS, qui est correct, à l'affichage en OpenGL, le framebuffer semble être affiché sans transformation en OpenGL : 
![image](https://user-images.githubusercontent.com/7624262/159792015-12fb0428-00da-4ecf-ac19-b2e7c049b1e7.png)
![image](https://user-images.githubusercontent.com/7624262/159792184-ee3cdad0-7302-4fb9-bfec-110cad5ae18b.png)

Testé avec le disque d'origine US.

**Comment by BenjaminSiskoo** [comment]
Plus de support OpenGL
