### ISSUE TITLE
[Jikkyou Powerful Pro Yakyuu S] Now loading n'est pas affiché correctement (VDP1 ?)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#256]
Kronos 1.4.5 :

![proya](https://user-images.githubusercontent.com/12481242/46527830-c1a5b900-c881-11e8-9b43-c67cc972be8d.PNG)

**Comment by FCare** [comment]
Fixé le 20/10/2018

**Comment by BenjaminSiskoo** [comment]
C'est pas corrigé chez moi.
