### ISSUE TITLE
[Joshikousei no Houkago. Pukunpa] Arrière plan manquant sous les portraits...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#257]
Kronos 1.4.5

![joshi](https://user-images.githubusercontent.com/12481242/46528586-a8057100-c883-11e8-9207-8b5b31e7f10c.PNG)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 22.12.2018 - Kronos 1.5.0

**Comment by FCare** [comment]
Polygon
x1 = -63, y1 = 19, x2 = -21, y2 = 19
x3 = -21, y3 = 52, x4 = -63, y4 = 52
Pre-clipping Enabled
User Clipping Enabled
Clipping Mode = 0
Color mode: 4 BPP(16 color bank)
Color bank: 00040000
Color Calc. mode: Gouraud Shading
Gouraud Shading Table = 0000D948

**Comment by FCare** [comment]
Looks like the sprite window shall not work with Gouraud shading...
