### ISSUE TITLE
[Keio Flying Squadron 2] Arrière plan manquant (NBG2)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#259]
Kronos 1.4.5 :

![keio](https://user-images.githubusercontent.com/12481242/46529573-77730680-c886-11e8-876d-d1a501fbb6cf.PNG)

En désactivant le NBG2, il s'affiche.
![keioon](https://user-images.githubusercontent.com/12481242/46529582-7fcb4180-c886-11e8-8cd9-87b92ad8ad88.PNG)

**Comment by FCare** [comment]
Fixé le 20/10/2018
