### ISSUE TITLE
[Krazy Ivan] Problème d'affichage du ciel (RGB0 ?)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#261]
Kronos 1.4.5

![krazy ivan](https://user-images.githubusercontent.com/12481242/46569583-e2841200-c946-11e8-8a34-5220d96bf604.PNG)

**Comment by fafling** [comment]
Une bizarrerie dans les registres du VDP2 : le plan NBG1 a les mêmes adresses de tilemaps que le RBG0, mais avec une profondeur de couleur et une priorité différente. La priorité à 0 du NBG1 fait qu'il n'est pas affiché, ça a peut-être un rapport avec l'absence du RBG0 ?
![capture](https://user-images.githubusercontent.com/7624262/52186496-ef970c00-2827-11e9-88a9-3ae76bbae521.JPG)

**Comment by BenjaminSiskoo** [comment]
Kronos branche rework du 17.04.2019 

Il semble que le ciel soit correcte : 

![krazy](https://user-images.githubusercontent.com/12481242/56323552-878c6c80-616c-11e9-8f99-a82a40ac0b0e.PNG)

**Comment by fafling** [comment]
Oui le ciel correspond bien à ce qu'affiche la console.

Par contre, il y a un problème sur l'affichage des sprites des lettres ou des chiffres du HUD : il n'y a pas d'espace entre eux et avec leurs cadres, alors que sur console il y a toujours au moins un pixel d'espacement. D'après le screenshot de Benjamin, l'affichage de ces sprites était correct en v1.4.5. On ouvre une nouvelle fiche pour ça ou on continue avec celle-ci ?

**Comment by BenjaminSiskoo** [comment]
Tu peux ouvrir un nouveau bug report, vu que c'est diffèrent. Le problème vient peut être d'un filtre ou d'une autre option vidéo. A vérifier, merci pour la confirmation sur le ciel.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 25 Avril 2019
