### ISSUE TITLE
[Kuuso Kagaku Sekai Gulliver Boy] Sorte de voile noir...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#263]
Kronos 1.4.5 :

![gullvier](https://user-images.githubusercontent.com/12481242/46569762-33950580-c949-11e8-9367-49c051c6dff4.PNG)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 10/01/2018

**Comment by BenjaminSiskoo** [comment]
Kronos 20.04.2019

Le voile noir est de retour sur les vidéos.

**Comment by FCare** [comment]
Quand je cherche celui la, je ne vois pas vraiment pourquoi ca deconne... En fait, le VDP1 est en mode RGB, MSB toujours a 1. et la color calculation est activée pour les pixels ou le MSB est a 1 (donc toute l'image). Ca n'utilise pas la color calculation window et la valeur alpha (en color calculation src alpha) vaut 0xF. Au final, on melange donc la moitié de l'image et la moitié du fond d'ecran noir => on tombe sur une luminosité divisée par deux...

**Comment by fafling** [comment]
L'effet de gradation est activé sur la couche de sprites :
![Capture_gulliver_boy_VDP2](https://user-images.githubusercontent.com/7624262/57557098-24f84c00-7379-11e9-8c2e-fb35044a2841.PNG)

Cet effet est décrit (pas très clairement) dans la doc du VDP2 p. 238-240. On trouve une explication plus claire du principe dans le "Saturn overview manual" p. 36-37, paragraphe Blur-Calculation Function.

Une version floutée horizontalement d'un plan qui active cet effet doit être substituée en second image sur les pixels où ce plan est présent en top ou second image.

La formule de calcul du flou horizontal d'un pixel N utilise les 2 pixels à gauche de lui sur la même ligne :
couleur_pixel_N_flouté = 0.25 * couleur_pixel_N-2 + 0.25 * couleur_pixel_N-1 + 0.5 * couleur_pixel_N

Dans Gulliver boy, la color calculation se fait donc avec une version floutée du plan de sprites en second image au lieu du back screen. Il n'y a donc pas d'assombrissement.

D'autre part, le ratio indiqué à 31:1 pour le registre 0 des sprites dans l'écran debug n'est apparemment pas le bon, devrait être à 15:17 pour 0x10 ou bien 16:16 pour 0xF.

**Comment by BenjaminSiskoo** [comment]
J'ai de nouveau le soucis avec les commits du 20/05/2019

**Comment by fafling** [comment]
Pour moi, la gradation est correcte uniquement dans la WIP du 11/05, dès celle du 12 le voile noir (transparence avec le back screen au lieu de la version floutée) est de retour sans gradation.

Texture utilisée par le VDP1 :
![gulliver_texture_VDP1](https://user-images.githubusercontent.com/7624262/57990925-9176f780-7aab-11e9-8504-9c3fe977c045.png)

Affichage du 11/05 sans voile noir et avec gradation :
![Capture_gulliver_boy_video_20190511](https://user-images.githubusercontent.com/7624262/57990947-ac496c00-7aab-11e9-8a49-6012cf395ee5.PNG)

Affichage dernière WIP avec voile noir et sans gradation :
![Capture_gulliver_boy_video_20190520](https://user-images.githubusercontent.com/7624262/57990954-c1be9600-7aab-11e9-8594-1502bb5d0071.PNG)

De même, sur la video de Megaman 8, la gradation n'est présente que dans la WIP du 11/05. Je n'ai jamais vu le voile dessus par contre.

Affichage du 11/05 avec gradation :
![Capture_megaman8_20190511](https://user-images.githubusercontent.com/7624262/57991046-76f14e00-7aac-11e9-9ff4-3c2b351ad195.PNG)

Affichage dernière WIP sans gradation :
![Capture_megaman8_20190520](https://user-images.githubusercontent.com/7624262/57991053-853f6a00-7aac-11e9-8e98-7e9d6f551971.PNG)

**Comment by fafling** [comment]
J'ai vérifié sur la console pour Gulliver boy et Machine head (version US), et je ne retrouve pas le flou qu'il devrait y avoir si ces jeux implémentaient la gradation. Je n'ai pas pu vérifier Megaman 8 car je ne l'ai pas sur CD.

D'après Kronos, Machine head utilise la gradation sur les sprites, et dans la version du 11/05 qui implémente correctement l'effet, on voit la version floue des sprites par transparence à travers le NBG1 :
![Capture_machine_head_20190511](https://user-images.githubusercontent.com/7624262/58073679-8bfcd880-7ba3-11e9-8684-c8c7309d3b6c.PNG)

Comme indiqué, je vois pas cet effet sur console. Une explication possible est que ces 2 jeux n'utilisent pas le type de color RAM nécessaire à l'effet : elle doit être en mode 0 (p.238 de la doc du VDP2), où elle contient 1024 couleurs RGB 15 bit répétées sur sa 2ème moitié (p. 43-46 de la doc du VDP2).

@FCare Est-ce que Kronos implémente cette restriction de la gradation par rapport au type de color RAM ? Et quel est le type de color RAM utilisé par Machine head et Gulliver boy ?

J'ajoute cette info dans celles qu'il faudrait afficher dans l'écran debug du VDP2 ( voir #505 ) car elle conditionne plusieurs règles de color calculation.

**Comment by FCare** [comment]
On ne verifie pas le mode de la RAM. Je corrige.

**Comment by FCare** [comment]
Verification ajoutée, tu peux reverifier de ton coté?

**Comment by fafling** [comment]
Dans la dernière WIP, le type de color RAM est visible, et il a le mauvais type pour Machine head, donc normal qu'il n'y ait pas de gradation.
Par contre, la color RAM a bien le type 0 pour Gulliver boy.

**Comment by fafling** [comment]
Sur Megaman 8, normal aussi que la gradation ne soit pas faite par Kronos, le type de color RAM est à 1.

**Comment by fafling** [comment]
Le commit 5c294db permet l'affichage de la video de Gulliver Boy sans voile noir et avec gradation, ce qui est conforme au registre et à l'affichage sur la console 👍 

@BenjaminSiskoo Est-ce que tu peux confirmer ? Comme on a eu des différences là-dessus...

**Comment by BenjaminSiskoo** [comment]
Corrigé
