### ISSUE TITLE
[Langrisser V] PRoblème graphique sur le menu et les portraits (NBG1)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#268]
Kronos 1.4.5 :

![langrisser 5](https://user-images.githubusercontent.com/12481242/46598906-50f6da80-cad5-11e8-9e61-e72b4b4cc50e.PNG)

En désactivant le NBG1, on voit le portrait :

![langrisser 5_visage](https://user-images.githubusercontent.com/12481242/46599135-f4e08600-cad5-11e8-9df4-c1c46c8c0cb8.PNG)

**Comment by FCare** [comment]
Fixé le 20/10/2018
