### ISSUE TITLE
[Linda^3 Kanzenban] Curseur manquant...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#270]
Kronos 1.4.5

![linda](https://user-images.githubusercontent.com/12481242/46600511-df6d5b00-cad9-11e8-88c7-7cd618df4bd3.PNG)

**Comment by FCare** [comment]
Fixé le 20/10/2018

**Comment by BenjaminSiskoo** [comment]
C'est pas corrigé chez moi.
