### ISSUE TITLE
[Albert Odyssey] Régression : écran noir après l"intro...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#275]
Kronos 1.4.5 du 10/10/2018 :

tout est dans le titre.

**Comment by barbudreadmon** [comment]
Pour celle-ci, je suis presque sûr que çà vient de l'OpenGL(ES), ce jeu faisait parti de mes tests, et il fonctionnait encore il y a 3-4 jours en mode SW sur le port libretro.

**Comment by BenjaminSiskoo** [comment]
Le mode software est cassé sur Kronos (Windows and probablement linux aussi). Les tests sont donc en OpenGL uniquement

**Comment by barbudreadmon** [comment]
Oui, visiblement il y a quelque chose dans le code opengl qui casse le code du mode software, même si on choisit celui-ci dans l'initialisation de l'émulateur. Quand on compile l'émulateur en retirant tout les fichiers liés à l'opengl, le mode software fonctionne.
Je vais essayer de voir si c'est quelque chose qui peut-être corrigé, j'aimerai quand même beaucoup pouvoir forcer le mode software dans le port libretro quand l'opengl(es) n'est pas disponible.

**Comment by BenjaminSiskoo** [comment]
François l'avait remis, mais probablement qu'un des patchs de Devmiyax l'a recassé. De toute manière Devmiyax et François ont travaillé exclusivement sur la partie OpenGL. Le mode software devrait être équivalent à celui de Yabause 0.9.15 de l'époque. Niveau compatibilité ce sera très largement en dessous logiquement.

**Comment by FCare** [comment]
Si have_libgl est defini le rendu soft fait le rendu dans un fbo donc il
faut afficher ce fbo. Sinon, il faut desactiver tout ce qui est déclaré
entre du have_libgl

Le mar. 23 oct. 2018 à 18:02, barbudreadmon <notifications@github.com> a
écrit :

**Comment by barbudreadmon** [comment]
@FCare Ok, dans ces conditions je pense que je vais purement et simplement supprimer le rendu soft du port libretro, à ce niveau il prend juste de la place pour rien. De toute façon avec l'opengles3 et l'opengl3.3 on devrait couvrir 99% des devices où il est vraisemblable que l'émulateur tourne à pleine vitesse...

**Comment by BenjaminSiskoo** [comment]
Il vaudrait peut être mieux le laisser mais qui n'apparaisse plus dans les choix. Si des devs sont intéressé dans le futur pour reprendre la partie software, il y aurait juste à le réactiver !!!
