### ISSUE TITLE
[Virtual Hydlide] La carte n'est pas affiché correctement (NBG1 ?)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#278]
Kronos 1.4.5 du 12/10/2018 :

![virtual](https://user-images.githubusercontent.com/12481242/46861038-f41b5d00-ce11-11e8-8cc7-c7f3f1a300b2.PNG)

**Comment by FCare** [comment]
Le framebuffer du VDP1 est lu juste avant mais il n'est pas ecrit. Sur l'ecran du menu, le vdp1 sert a afficher les meu lui-meme, au moins.
2 possibilités:
1: Le framebuffer vdp1 qui a été lu est utlisé comme source pour le VDP2
2: Le framebuffer vdp1 qui a été lu est utilisé comme sprite pour le VDP1

Il faut trouver ou est ecrit le framebuffer du vdp1...

**Comment by fafling** [comment]
Le framebuffer VDP1 est transféré dans la VRAM du VDP2 quand on appuie sur le bouton de carte. Il est affiché par le NBG0, on le voit dans SSF.
Le transfert est fait après un rendu du framebuffer par le VDP1 sans certains éléments comme le personnage, la boussole, le statut, mais avec la carte.
Après le transfert, le VDP1 n'a plus qu'à dessiner les éléments qui bougent sur la carte (la flèche et la croix) tant que la carte reste affichée.
Le même principe est appliqué pour l'écran du menu.

**Comment by fafling** [comment]
Il y a le même problème dans le menu pause de Tomb raider : le framebuffer VDP1 est transféré dans le NBG1, mais Kronos n'affiche que du noir. 
#427

**Comment by fafling** [comment]
Et même problème dans Burning rangers pour les graphisme semi-transparents affichés par le NBG1 : Ils sont invisibles dans Kronos. 
A chaque frame, le VDP1 les dessine avec un 1er batch de commandes en quart de résolution dans le framebuffer. Le 2ème batch, qui dessine le reste des graphismes, commence par une commande de polygone qui efface la zone dessinée par le 1er batch. Donc cette zone a dû être copiée ailleurs entre les 2 batchs, sûrement vers un buffer intermédiaire finalement copié pendant un VBLANK dans le bitmap du NBG1.
Les commandes de dessin du 1er batch ont des coordonnées bizarres qui dépassent 32000. Normalement les coordonnées sont comprises entre -1024 et 1023.
![capture](https://user-images.githubusercontent.com/7624262/52372253-f73cf780-2a57-11e9-90fb-f1aded34190c.JPG)

**Comment by BenjaminSiskoo** [comment]
Corrigé pour Virtual Hydlide et Tomb Raider en ce jour, @nicolas-charrier si tu pouvais vérifier pour burning ?

**Comment by fafling** [comment]
La copie du framebuffer fonctionne pour Burning rangers aussi, yes !!! Comme il y a aussi d'autres problèmes, je vais ouvrir une fiche séparée.

Concernant Virtual Hydlide, il reste les problèmes suivants :

- Le patch qui permet à la copie du framebuffer de fonctionner semble accompagné d'une régression sur l'ombre du perso (problème absent de la WIP du 21/04) : elle est trop sombre avant affichage de la carte ou de l'inventaire (on dirait un quart de luminance au lieu d'un demi). L'ombre est corrompue après affichage de la carte ou de l'inventaire.

Avant affichage de la carte ou de l'inventaire :
![Capture_virtual_hydlide_ombre_avant_carte_ou_inventaire_20190426](https://user-images.githubusercontent.com/7624262/56824801-d5cdf980-6857-11e9-8c95-9178ee222103.PNG)

Après affichage de la carte ou de l'inventaire :
![Capture_virtual_hydlide_ombre_corrompue_20190426](https://user-images.githubusercontent.com/7624262/56824814-debecb00-6857-11e9-8fc3-4d99a97bed1f.PNG)

La commande de dessin de l'ombre a une texture corrompue dans l'écran debug du VDP1 et une adresse bizarre à 0, ce qui ne devrait pas être possible pour une texture (la commande de dessin du perso qui la suit a les mêmes caractéristiques). Il n'y a pas de changement dans cette commande avant et après affichage de la carte ou de l'inventaire et elle avait les mêmes bizarreries dans les versions précédentes de Kronos où l'affichage était correct :
![Capture_virtual_hydlide_ombre_avant_carte_ou_inventaire_2_20190426](https://user-images.githubusercontent.com/7624262/56825187-c56a4e80-6858-11e9-9bf8-10f8e90f942f.PNG)

- Le 1er affichage de l'inventaire, qui utilise le même principe de copie du framebuffer, est corrompu (les affichages suivants sont corrects) :

![Capture_virtual_hydlide_premier_inventaire_corrompu_20190426](https://user-images.githubusercontent.com/7624262/56824594-301a8a80-6857-11e9-8452-468ff115af53.PNG)

- Même problème que les autres jeux avec copie de framebuffer quand l'option OpenGL size est réglée sur 2x ou plus, la partie inférieure gauche du framebuffer est zoomée par l'émulateur en tant que texture copiée à partir du framebuffer :

![Capture_virtual_hydlide_inventaire_opengl_size_2x_20190426](https://user-images.githubusercontent.com/7624262/56824463-d3b76b00-6856-11e9-997e-287389c93ac7.PNG)

**Comment by fafling** [comment]
Pour l'ombre trop sombre, c'est ce bug #475 .

**Comment by fafling** [comment]
En WIP du 07/05, le problème d'OpenGL size est résolu.

La corruption se produit au 2ème affichage de l'inventaire :
![Capture_virtual_hydlide_inventaire_20190507](https://user-images.githubusercontent.com/7624262/57338439-a8256200-712d-11e9-89b3-e774ead48b3a.PNG)

L'affichage de la carte n'a pas ce problème.

**Comment by FCare** [comment]
Vous pouvez tester a nouveau?

**Comment by BenjaminSiskoo** [comment]
C'est largement mieux, mais il reste des artefacts, le problème c'est quand tu ouvres puis ferme le menu plusieurs fois de suites les artefacts sont différents à chaque fois, j'ai essayé de trouver un exemple parlant avec la photo ci après (au niveau des arbres) pour ce que j'ai pu voir c'est toujours sur les arbres ou aux alentours les artefacts.

![virtualhydlide](https://user-images.githubusercontent.com/12481242/59144045-0023e280-89d2-11e9-9e55-5cc6ee5ac793.PNG)

**Comment by fafling** [comment]
Dans la WIP du 21/11, en OpenGL, il reste des corruptions aléatoires sur l'inventaire. En compute shader, on voit systématiquement une corruption très brève à l'affichage de l'inventaire.

**Comment by BenjaminSiskoo** [comment]
En OpenGL avec Kronos du 23.09.2021. La lame du couteau passe au bleu quand on dégaine ou rengaine.

![virtualhydlide opengl](https://user-images.githubusercontent.com/12481242/134671436-348e5c8e-c02d-4091-905e-5166714b836f.gif)

**Comment by fafling** [comment]
Les étincelles bleues quand on dégaine ou rengaine le couteau sont correctes :
[https://www.youtube.com/watch?v=r1U1A83FapQ&t=141s](https://www.youtube.com/watch?v=r1U1A83FapQ&t=141s)

**Comment by fafling** [comment]
Les corruptions supplémentaires à l'affichage des menu et map ont l'air d'avoir disparu grâce au commit 981ba05.
