### ISSUE TITLE
[Bootleg Sampler] Master SH2 Invalid opcode + vrai bios...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#29]
Master SH2 invalid opcode

R0 =  00000000	R12 =  00000000
R1 =  06010000	R13 =  00000000
R2 =  00000000	R14 =  00000000
R3 =  20000226	R15 =  06002000
R4 =  00000000	SR =   00000000
R5 =  00000000	GBR =  00000000
R6 =  00000000	VBR =  06000000
R7 =  00000000	MACH = 00000000
R8 =  00000000	MACL = 00000000
R9 =  00000000	PR =   00000000
R10 = 00000000	PC =   06010002
R11 = 00000000

**Comment by FCare** [comment]
Bootleg Sampler marche parfaitement chez moi avec le vrai bios.
Le fichier que j'utilise se nomme "253 Bootleg Sampler (U).mdf"

**Comment by BenjaminSiskoo** [comment]
Version Redump (européenne) : 

Avec le bios intégré

Master SH2 invalid opcode

R0 =  00000000	R12 =  06010000
R1 =  00000008	R13 =  060F06E0
R2 =  00000000	R14 =  060FFDD8
R3 =  00000000	R15 =  060FFDB0
R4 =  25E06000	SR =   00000101
R5 =  00001000	GBR =  00000000
R6 =  00000000	VBR =  06000000
R7 =  80410101	MACH = 00000000
R8 =  060FDE00	MACL = 00000000
R9 =  060FAAA8	PR =   0600214C
R10 = 060F08F4	PC =   00000000
R11 = 060F0C68

Avec le vrai bios : 

Master SH2 invalid opcode

R0 =  00000000	R12 =  00000000
R1 =  06010000	R13 =  00000000
R2 =  00000000	R14 =  00000000
R3 =  20000226	R15 =  06002000
R4 =  00000000	SR =   00000000
R5 =  00000000	GBR =  00000000
R6 =  00000000	VBR =  06000000
R7 =  00000000	MACH = 00000000
R8 =  00000000	MACL = 00000000
R9 =  00000000	PR =   00000000
R10 = 00000000	PC =   06010002
R11 = 00000000
