### ISSUE TITLE
[Mr Bones] Problème graphique sur le menu Pause...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#301]
Kronos du 20/10/2018

![mrbones1](https://user-images.githubusercontent.com/12481242/47286635-cd1e1180-d5ef-11e8-99d6-8c7dcea94c42.PNG)

**Comment by FCare** [comment]
Ca semble venir des calculs asynchrone de texture.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 03/04/2020
