### ISSUE TITLE
[Daytona USA] Jeu se fige

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#306]
L'écran SEGA s'affiche 2 fois d'affilés, puis l'écran titre se fige.
Il semble que le problème n'apparaisse pas si on n'utilise pas de bios (donc en mode bios HLE), il y a par contre des bizarreries niveau son j'ai l'impression.
Les autres versions du jeu (Circuit Edition, Net Link Edition, ...) ne semblent pas avoir ce problème, même si j'ai vu l'écran SEGA s'afficher 2 fois également sur la "Net Link Edition".

**Comment by BenjaminSiskoo** [comment]
Le problème doit être assez récent car il y a 2 semaines en gros, il n'y avait pas de problèmes. Je confirmes aussi qu'avec le bios intégré pas de problème.

**Comment by barbudreadmon** [comment]
Pour la version euro (j'ai testé les 3 bons dumps que je connais : http://redump.org/disc/34116/ http://redump.org/disc/21520/ et http://redump.org/disc/10055/). Le premier est détecté comme un cd audio (`Cs2GetRegionID()` retourne 0), les 2 autres ont le même problème que les dumps USA et JAP

**Comment by BenjaminSiskoo** [comment]
Le soucis vient d'un des commits du 27 ou 28 Septembre 2018. Il a a d'autres jeux qui ont régressé (Albert Odyssey, etc...).

**Comment by FCare** [comment]
Depuis le 1er patch du 29 septembre, ca demarre encore...

**Comment by FCare** [comment]
Commit fautif retiré... Les jeux fonctionnent
