### ISSUE TITLE
[Scorcher] Ligne scintillante dans le menu pause (NGB1/VDP1 ?)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#334]
Kronos 1.5.0 : 

![scorcher](https://user-images.githubusercontent.com/12481242/47792184-c42dee00-dd1b-11e8-941b-4fc02aa4c590.PNG)

**Comment by FCare** [comment]
NBG0 mode
16-bit(32,768 colors)
Bitmap(512x256)
Bitmap Address = 20000
Bitmap Palette Address = 0
Screen Scroll x = 0, y = 0
Coordinate Increments x = 1,000000, y = 1,000000
Window disabled whole screen
Color Ram Address Offset = 200
Priority = 3
Color Calculation Enabled
Special Color Calculation Mode = 3
Color Calculation Ratio = 31:1
Color Offset A Enabled
R = 0, G = 0, B = 0
Special Color Calculation 3

**Comment by FCare** [comment]
NBG0 is common. It shall be totally hidden by vdp1. Let's try to see why one VDP1 line is transparent

**Comment by FCare** [comment]
When vdp1 OpenGL framebuffer is cleared, it is not filled with 0. Do the same on the vdp1 memory framebuffer is fixing the line.
In that case, the framebuffer is not filled as transparent but as opaque in a determined color.
