### ISSUE TITLE
[Filtre Vidéo] Problème de texte sur le bios...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#335]
Kronos 1.5.0 : 

Avec l'option OpenGL size --> original. On a le bug sur le texte du bios.

![bios](https://user-images.githubusercontent.com/12481242/47792248-e9baf780-dd1b-11e8-96d0-0aef31c824de.PNG)

**Comment by barbudreadmon** [comment]
Le bug est réglé sur la version libretro, à voir si la technique ne peut pas être appliquée sur la version standalone (respect résolution native pour le framebuffer + stretch).
