### ISSUE TITLE
Kronos 1.5.0 Bicubic Upscale filter is broken

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#338]
The bicubic upscale filter is broken in 1.5.0, the emulator crashes when try to run a game with bicubic (bilinear works properly) bicubic was working perfect in 1.4.5

**Comment by BenjaminSiskoo** [comment]
Hello, 

It' s seems ok. Delete your bkram.bin and start from a fresh kronos.ini (erase all).

**Comment by LuismaSP89** [comment]
Hi, already deleted all (bkram.ini and kronos.ini) and the issue persist. I´m on windows 10.

**Comment by BenjaminSiskoo** [comment]
Hey @LuismaSP89 

Could you give your specs ? Send your kronos.ini ? Is there an error message or just a crash. 

Thanks for your reports :)

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo Hello, first of all, thanks to you, for your help.
Yes, of course, here it is my kronos.ini:

[kronos.zip](https://github.com/FCare/Kronos/files/2542441/kronos.zip)

My specs:

Windows 10 x64
i7 4790k 4.4 Ghz
16 GB DDR3
GTX 970 4GB GDDR5

The emulator exits without an error message. My mouse pointer changes to the "loading" pointer of windows 10, and then, the emulator closes. I´ll try to make a video showing the problem.

**Comment by BenjaminSiskoo** [comment]
Ok thanks for your reports and your info. I tried your kronos.ini and no problem. Anyway others people reported this kind of problem. François will be back next week. So for now, need to wait :)

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo Ok, thanks a lot again for your help. I made a video recording the problem, I don´t know if it can helps, but here it is:

[Kronos 1.5.0.zip](https://github.com/FCare/Kronos/files/2542602/Kronos.1.5.0.zip)

**Comment by BenjaminSiskoo** [comment]
Very ,nice video. Gracias senor Luis :)

**Comment by BenjaminSiskoo** [comment]
Before to leave, François put these commits, but It was untested and not added in Kronos 1.5.0. Not sure about filters crashes

[kronosquad.zip](https://github.com/FCare/Kronos/files/2542771/kronosquad.zip)

**Comment by LuismaSP89** [comment]
At your service, monsieur Benjamin. xD

I also tested the kronosquad you provided, and the same results, it crashes. We must wait then to the Fcare´s return :P

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 

:)

Could you try this  !!!

[kronos.zip](https://github.com/FCare/Kronos/files/2545192/kronos.zip)

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo Tested, but the issue remains :S

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 

Ok It was a try. François will try next week.

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 

Try this exe. 
[kronos.zip](https://github.com/FCare/Kronos/files/2546377/kronos.zip)

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo 

Awesome, this last build works ok ; ) 
Closing this issue...

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 

Great to read :)
