### ISSUE TITLE
Kronos 1.5.0 All Embellishment filters are broken

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#339]
All Embellishment filters crash the emulator when open a game, (HQ4x, 2xbrz, 4xbrz) all was working ok in 1.4.5

**Comment by BenjaminSiskoo** [comment]
Delete bkram.bin and kronos.ini and try again

**Comment by LuismaSP89** [comment]
Done, but like the #338 no changes at all. Kronos still crash when launching a game with any embellisment filter or with bicubic filter. With that disabled all works fine. Retested in 1.4.5 and all was working Ok.

**Comment by LuismaSP89** [comment]
With the build of https://github.com/FCare/Kronos/issues/338 this is almost fixed, Kronos no longer crash by using filters, but there´s some problems, all filters are not working as intended.

The HQ4x and the 4Xbrz are showing some artifacts. And the 2Xbrz looks the same than "none" filter.

Here´s some examples:

**HQ4X:** 

![hq4x](https://user-images.githubusercontent.com/12205048/47972034-3a25b280-e098-11e8-93a8-eed9d08a0778.jpg)

**4Xbrz**

![4xbrz](https://user-images.githubusercontent.com/12205048/47972041-414cc080-e098-11e8-888b-58f3ebd08a2b.jpg)

**2xbrz/None**

![none](https://user-images.githubusercontent.com/12205048/47972048-4dd11900-e098-11e8-85e8-debf0d3715f0.jpg)

**Comment by LuismaSP89** [comment]
Update: With latest build of https://github.com/FCare/Kronos/issues/341 the artifacts gone, but now all the filters works like 2xbrz/none.

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 

This exe fixed FPS with FS. And another try to fix filters. Could you check it ?

[kronos.zip](https://github.com/FCare/Kronos/files/2555583/kronos.zip)

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo 
Ok, this fixes sound from https://github.com/FCare/Kronos/issues/344   good news, ^^ closing.

In the other side, here´s some comparisons:

**1.5.0 in Shining force 3:** (It seems the screen is a bit misplaced as you can see in the comparison screenshots from below)
4Xbrz=none
2xbrz=none
HQ4x=none+artifacts

**1.4.5 in shining force 3:**
4xbrz= works as intended
2xbrz= none
HQ4x= works as intended

**1.5.0 in Deep Fear:**
4Xbrz and 2xbrz= Looks the same, 4xbrz is a bit more "cleaner" 
HQ4x=Ok

**1.4.5 in Deep Fear:**
4xbrz=Looks more fuzzy than 1.5.0 but with less jaggies
2xbrz= None
HQ4x=Similar to 1.5.0 but a bit more fuzzy

**Comment by LuismaSP89** [comment]
And some screenshots comparing 1.5.0 and 1.4.5 (All screenshots with 4xbrz filter)

**1.5.0:**
![1 5-1](https://user-images.githubusercontent.com/12205048/48104990-f36dbf00-e235-11e8-8fcb-19af13d9ddf8.jpg)
![1 5-2](https://user-images.githubusercontent.com/12205048/48104991-f36dbf00-e235-11e8-8edc-bd67ab57e8a5.jpg)
![1 5-3](https://user-images.githubusercontent.com/12205048/48104992-f36dbf00-e235-11e8-969a-3247f83664a3.jpg)

**1.4.5**
![1 4-1](https://user-images.githubusercontent.com/12205048/48105006-054f6200-e236-11e8-891d-9493e91f9a9e.jpg)
![1 4-2](https://user-images.githubusercontent.com/12205048/48105007-054f6200-e236-11e8-82b2-ef461f91a55b.jpg)
![1 4-3](https://user-images.githubusercontent.com/12205048/48105008-054f6200-e236-11e8-9bbc-f3761876094b.jpg)

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 

Nice report :)

Are you interested to improve the spanish language ?

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo Of course, : ) if I can help to improve, test, or translate something just tell me what to do.

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 : in Kronos, you have a trans folder, inside you can found yabause_es.  Use notepad to open it. here an example : 

Thank You|Gracias

Where are you com from ?

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo
Ok, I'll do my best ; )

I'm from Plasencia, a city in the western region of Extremadura.

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 

ok, never heard about this city. Now I know where is it :)

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo Well.. this city is a small one, but it has some Roman architecture and a medieval wall very interesting. If you ever visit my city I would be very pleased to be your guide xD

In another vein, here you go, it was a bit long to translate but I tested it and I think is most accurate than before. I hope you find it well : )

[Spanish Translation.zip](https://github.com/FCare/Kronos/files/2558747/Spanish.Translation.zip)

**Comment by BenjaminSiskoo** [comment]
It will be pleasure to discover the city. Maybe one day. I've never been in spain before. I like roman civilization. London have some old roman wall. it was impressive.

New strings to translate :

CPU Tesselation, GPU Tesselation, Triangles using perspective correction. Stick Down, Stick left button: same as A  Stick right button: same as B  Stick trigger: same as C\, Stick Left, Stick Right, Stick Up, Throttle Down, Throttle Up

Can't initialize Yabause|No se pudo iniciar Yabause    (I left the Yabause reference as it is, but maybe we should change to "Kronos") <-- Yup you can.

[yabause_es.zip](https://github.com/FCare/Kronos/files/2562136/yabause_es.zip)

I could commit your new translation file after your final translation :)

Your changes.doc was perfect :) Really good job.

**Comment by LuismaSP89** [comment]
Perfect, I'll get right on it.

Only one question, there´s a lot of "&" characters in the translation, and I don´t know what it is for. And if you go to the "shortcuts" tab, it looks horrible, because the "&" characters are in the middle of the words like you can see here:

![screenshot](https://user-images.githubusercontent.com/12205048/48213875-0a6bf880-e37f-11e8-8c0b-aa5b3cbed319.jpg)

Is there any reason for that? Or I can delete that characters, I tried to do it and nothing was broken.

**Comment by BenjaminSiskoo** [comment]
&File means if you push F, it open File menu. These & are shortcuts. You can remove it or not.

**Comment by LuismaSP89** [comment]
Ok, then If there´s some function to the "&" then I´ll keep as it is.

I added the "Mission Stick" and "Double Mission Stick" strings (Which were not writen) and his translation too.

Updated translation:
[yabause_es.zip](https://github.com/FCare/Kronos/files/2562801/yabause_es.zip)

Btw, the tesselation options have a blank space at his left, maybe we can add a string with "Tesselation options" or something¿?

![screenshot](https://user-images.githubusercontent.com/12205048/48215607-e7434800-e382-11e8-9f2b-3413c3ec60dc.jpg)

Edit: The string "Can't initialize Yabause" still shows, I changed "Yabause" to "Kronos" in the spanish.yts and default.yts but keeps showing the same, maybe the string key is in other place.

**Comment by BenjaminSiskoo** [comment]
Thanks for your work. Some strings cannot be translated. And I don"t know how to fix them. Pull request done. I add Tesselation\Teselado in your file too.

**Comment by LuismaSP89** [comment]
Nice : ) If I can help to test or improve something else, just tell me.

**Comment by BenjaminSiskoo** [comment]
Do you have a gmail account ? It will be more easy to chat than here :)

**Comment by LuismaSP89** [comment]
Of course: Luismasp89@gmail.com

**Comment by BenjaminSiskoo** [comment]
I added you. We could chat. Remove your mail above.

**Comment by LuismaSP89** [comment]
Update: 
Other tested games with broken/working filters (4xbrz tested only) Hope it helps to debug this issue:

Road rash: Strange case, the filter works in some screens, like the (Press start main screen) and some numbers (Your ranking in the race) But the character´s sprite and all the other numbers or the road/scenarios itself doesn´t work.

Guardian heroes: Doesn´t work, filter are broken and some upscaling issues/artifacts related to https://github.com/FCare/Kronos/issues/341

Megaman 8: Filter works ok in this game.
