### ISSUE TITLE
Kronos 1.5.0 Deep Fear FMV are broken

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#340]
The FMV videos on 1.5.0 are broken in deep fear, this was working Ok in 1.4.5

Examples in 1.5.0:

![8](https://user-images.githubusercontent.com/12205048/47863633-02004480-ddf8-11e8-85c4-a3614ffaefdf.jpg)
![7](https://user-images.githubusercontent.com/12205048/47863635-02004480-ddf8-11e8-8a34-babcfbd3080f.jpg)

**Comment by BenjaminSiskoo** [comment]
Confirmed here too.

**Comment by LuismaSP89** [comment]
Nearly solved by reintroduce the tesellation in (https://github.com/FCare/Kronos/commit/a165cbc72d5b6843879d20da5c98c078290521e1) but it seems it runs choppy/a bit slow with stuttering. 1.4.5 works perfect, even if it doesn´t have the tesellation option.

Edit: That was my problem I had Vdp1 cache enabled, with this disabled it runs at it shoulds, closing issue : )
