### ISSUE TITLE
Kronos 1.5.0 Upscaling Issues 

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#341]
Various upscaling issues in kronos 1.5.0 (2x, 4x, 8x or 16x) tested versus 4x resolution of Yaba Sanshiro v2.2.0 and all works ok (The 4x resolution is used in the images of this thread:  https://github.com/FCare/Kronos/issues/181)

Here it is the kronos 1.5.0 in 8x resolution with artifacts (Artifacts appear in all resolutions):

![3](https://user-images.githubusercontent.com/12205048/47863997-e0538d00-ddf8-11e8-974d-73fcfb63aa41.jpg)
![1](https://user-images.githubusercontent.com/12205048/47863998-e0ec2380-ddf8-11e8-8554-9dd50055bb64.jpg)
![2](https://user-images.githubusercontent.com/12205048/47863999-e0ec2380-ddf8-11e8-8723-f3d13043b485.jpg)

**Comment by LuismaSP89** [comment]
Update:
With the last build of https://github.com/FCare/Kronos/issues/338 this looks a bit better (not perfect) in shining force. Deep fear looks the same.

Some examples:

![deep fear](https://user-images.githubusercontent.com/12205048/47972139-786fa180-e099-11e8-8a8c-0b5532bfd46f.jpg)
![shining](https://user-images.githubusercontent.com/12205048/47972140-786fa180-e099-11e8-9774-03615a7e3c44.jpg)
![shining 2](https://user-images.githubusercontent.com/12205048/47972141-79083800-e099-11e8-9abf-5f0a2ff7dae5.jpg)

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89  Hola/Oi can you test this exe :  
[kronos.zip](https://github.com/FCare/Kronos/files/2551153/kronos.zip)

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo No changes, the upscaling issue persist, maybe it looks a very tiny better in deep fear. The only change is that now the embellishment filters shows no more the artifacts of https://github.com/FCare/Kronos/issues/339 , in fact the filters doesn´t work (All of them = none enabled)

Edit: It seems that solves https://github.com/FCare/Kronos/issues/340 when the Tesselation is enabled, good news, one less problem ; )

**Comment by Tatsuya79** [comment]
Probably the same kind of issue I noticed, comparing Kronos on windows and the RetroArch core vs uoYabause.
In Sega Rally plus some edges are cut, like on each border of the road.

Kronos (RA current core, same in stand-alone 1.5):
![sega_rally_championship_plus-ra](https://user-images.githubusercontent.com/6266038/48315053-db999080-e5d1-11e8-9aaa-998166d8b725.jpg)

uoYabause (2.2):
![uoyabause](https://user-images.githubusercontent.com/6266038/48315054-e5bb8f00-e5d1-11e8-9ea0-0d8ebd66096e.jpg)

2x/4x (and 8x for RA) shows the same problem.
Perspective or tessellation have no impact.

**Comment by barbudreadmon** [comment]
The issue in Sega Rally Plus started with https://github.com/FCare/Kronos/commit/1c1755b5d9f35c4e205a6cd20a70eb5ffd64db5b

It makes sense since it is a commit about polygon lines.

**Comment by FCare** [comment]
Yes, I found the same :-) I am working on it. The global root cause of these issues are due to the way the saturn is filling quads which is different from the openGL. I am trying to get a better fill but it is not really easy to get the right behavior without side effects... I hope I will be able to share some patches next week.

**Comment by LuismaSP89** [comment]
It seems that there´s a different issue then, since the upscaling problems with other games like shining force 3 or deep fear are from long ago (Tested with kronos 1.2.0 and 1.3.0 with 2x Interal res and looks the same) and like I said, in Yaba Sanshiro v2.2.0 at 4x IR works ok.

**Comment by LuismaSP89** [comment]
Updated with current build from 10th Jan 2019 -

![sin titulo2](https://user-images.githubusercontent.com/12205048/50976521-7b9b6980-14f0-11e9-8cf8-a0cfff06bd2a.jpg)
![sin titulo](https://user-images.githubusercontent.com/12205048/50976522-7b9b6980-14f0-11e9-926f-1862d16d74bc.jpg)

**Comment by LuismaSP89** [comment]
Update in this issues with Kronos 2.1.0:

All issues remain and in some cases becomes worse. Some images attached. Testing various video backends/options:

Deep fear, using OpenGL and real BIOS:
![1](https://user-images.githubusercontent.com/12205048/79077951-4427f800-7d05-11ea-9561-be6df626cac0.jpg)

Shining force 3, using OpenGL and real BIOS:
![2](https://user-images.githubusercontent.com/12205048/79077981-75a0c380-7d05-11ea-8661-21464e3a588a.jpg)

Deep fear, using compute shaders backend and real BIOS:
![Compute shaders](https://user-images.githubusercontent.com/12205048/79077988-83564900-7d05-11ea-9f6d-aaf009f44749.jpg)

Deep fear, using OpenGL and emulated BIOS:
![Emulated bios](https://user-images.githubusercontent.com/12205048/79077995-9701af80-7d05-11ea-817b-5295a017d591.jpg)

**Comment by LuismaSP89** [comment]
Seems that all this upscaling issues are no longer present in Kronos 2.1.2 because of the graphics backend revert. 

Only remaining issue for deep fear is the annoying sound "like a choppy TV snow"

https://github.com/FCare/Kronos/issues/556

Closing this and other related issues.
