### ISSUE TITLE
[Filtre Vidéo] OpenGl size..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#346]
Testé avec les options vidéos par défaut (sans filtre).

Avec l'option Original : 

![alonenature](https://user-images.githubusercontent.com/12481242/48132264-432ea380-e293-11e8-88bb-2856a697a437.PNG)

Avec le X2

![capture](https://user-images.githubusercontent.com/12481242/48132231-2003f400-e293-11e8-857c-6c4dc17db44c.PNG)

**Comment by FCare** [comment]
Ca vient du expandVertices qui fixe le drapeau... Le patch du drapeau implique de devoir faire un rendu en taille au moins x2... Je vais voir si je eux regler differement pour le cas rendu original...
