### ISSUE TITLE
[Sega Rally Championship] Version USA se fige à l'écran de logo Sega

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#355]
Testé sur le port libretro.

J'ai testé toutes les autres versions du jeu (versions "Plus" incluses) du set redump, seul "Sega Rally Championship (USA)" semble souffrir de ce problème, et le problème m'a également été confirmé sur des dump USA "non-redump" du jeu.

**Comment by BenjaminSiskoo** [comment]
Windows standalone commit du 20/11/2018 : 

Je confirme le sujet de @barbudreadmon

**Comment by fafling** [comment]
Même problème en version 1.6.0 (testé avec le CD d'origine).

**Comment by fafling** [comment]
Un peu d'archéologie : le jeu a cessé de démarrer en v1.3.0 avec un écran noir après le logo SEGA. A partir de la v1.5.0, le logo reste affiché.

**Comment by barbudreadmon** [comment]
Toujours présent en wip du 26 avril 2020, très embêtant celui-là vu que c'est l'un des jeux les plus populaire de la console et que c'est la version que les utilisateurs ont tendance à lancer.

**Comment by barbudreadmon** [comment]
le commit en cause entre la 1.2 et la 1.3 est https://github.com/FCare/Kronos/commit/e34d30e867742951bff27466deff6b77930501ca

**Comment by barbudreadmon** [comment]
fixé par https://github.com/FCare/Kronos/commit/154cde23c3fbd9259d9f2f4cce623cbbcbf8371f
