### ISSUE TITLE
[Twin advanced ROM system] Fonctionnalité manquante

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#356]
Tombé par hasard dessus : 

https://segaretro.org/Twin_Advanced_ROM_System

En gros c'est une cartouche utilisée sur 2 jeux (KOF95 et Ultraman), et ces jeux ne démarrent pas sans elle.
La fonctionnalité ne me semblant pas trop hardcore à implémenter (nouvelle entrée dans cs0 avec la mécanique pour la lire), je vais voir si je peux faire çà ces jours-ci.

**Comment by FCare** [comment]
Oui c'est sur la liste des trucs exotiques a faire...
KOF95 ne fonctionne meme que sur cartouche, il n'y a pas de CD. J'ai la
cartouche a la maison :-)

Le mar. 13 nov. 2018 à 13:31, barbudreadmon <notifications@github.com> a
écrit :

**Comment by BenjaminSiskoo** [comment]
Je sais pas si les autres ému saturn émule ca !!!

**Comment by barbudreadmon** [comment]
mednafen le fait visiblement

**Comment by barbudreadmon** [comment]
En fait c'est déjà implémenté, et çà fonctionne, il suffit d'utiliser `CART_ROM16MBIT` en carttype et le path vers la rom en cartpath, par contre autant sur le port libretro je m'en sors plutôt bien pour rendre le truc user-friendly, parce que j'ai ajouté un bout de code pour détecter le "game code" du jeu avant de lancer "pour de vrai" l'émulateur : 
> Cs2Init(CART_NONE, CDCORE_ISO, full_path, NULL, NULL, NULL);
Cs2GetIP(1);
saturn_game_code = malloc(strlen(Cs2GetCurrentGmaecode()) + 1);
strcpy(saturn_game_code, Cs2GetCurrentGmaecode());
Cs2DeInit();

Et à partir de ce code je définis des réglages au cas par cas de type/path de cartouches (les roms étant à placer à des endroits pré-définis). Autant pour la version standalone, çà demande beaucoup de manip' pour lancer 1 jeu.

Bon, quoi qu'il en soit, la fonctionnalité n'étant pas manquante, je clos :).
