### ISSUE TITLE
[The Legend of Oasis] Impossible de charger sauvegarde

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#358]
Testé avec le port libretro et la version standalone, on peut sauvegarder, çà crée bien un fichier avec des données sur le jeu (il y a bien des infos comme le nom du jeu quand on ouvre la sauvegarde dans un éditeur hexa) mais la sauvegarde reste invisible quand on souhaite la charger via le menu "continue". 

Plus bizarre encore : quand on est en jeu et qu'on souhaite sauvegarder à nouveau, il voit bien la sauvegarde qu'il refusait de voir dans le menu "continue".

Problème également présent dans la version européenne du jeu (Story of Thor 2), et on m'a également rapporté le même problème sur "Panzer Dragoon Zwei (USA)".

Précision : tests effectués avec la mémoire interne et extend_backup à 0.

**Comment by barbudreadmon** [comment]
Autre info peut-être pertinente : on m'a dit que çà fonctionnait dans YabaSanshiro

**Comment by BenjaminSiskoo** [comment]
Je n'ai pas plus testé que ca, les sauvegardes d'états, je sais qu'elles sont bancales. Tout comme les filtres. Je sais même pas si le réseau fonctionne aussi. On s'est plus concentré sur l'émulation des jeux. Il faudrait au moins 2 dév en plus, pour aider à peaufiner ces parties là. J'ai fait un peu la promotion pour essayer d'avoir du monde, mais ca bougeotte sans de résultat probant pour l'instant. Mais au moins grâce à tes tests, on a des traces, merci pour ca :)

**Comment by barbudreadmon** [comment]
Attention, ce ne sont pas les sauvegardes d'état, c'est les sauvegardes sur la mémoire interne de la saturn

**Comment by BenjaminSiskoo** [comment]
ha au temps pour moi :) Mais c'est pareil j'ai pas testé. Je sais aussi que sur les sauvegardes sur la bkram, le jeu peut être noté "&àçà"àç dans ce genre là.

**Comment by barbudreadmon** [comment]
Pour info la sauvegarde sur mémoire externe fonctionne comme il faut pour les jeux cités, par contre les tailles de fichier ne sont pas cohérentes (exemple : le fichier de sauvegarde fait 1Mo quand on utilise une carte de 512K). Je me demande si ces problèmes ne sont pas liés aux `FF` présents entre chaque caractères dans les fichiers de sauvegarde (et qui n'ont à priori pas lieu d'être ?)

**Comment by barbudreadmon** [comment]
J'ai trouvé un topic très intéressant sur les backup de la saturn : 
- les `FF` sont bien présents sur le support original
- la taille double aussi

source : https://assemblergames.com/threads/sega-saturn-ram-backup-parser.55945/

J'en déduis que le passage de la mémoire interne de 64k à 32k entre yabause et kronos est probablement une erreur et que çà pourrait être la cause de ces problèmes de lecture de mémoire interne sur certains jeux ?

**Comment by barbudreadmon** [comment]
@FCare Très bonne nouvelle, non seulement les sauvegardes internes sur "Legend Of Oasis" et "Panzer Dragoon 2" fonctionnent désormais, mais en plus elles semblent être 100% compatibles avec celles de mednafen !

Pour les sauvegardes externes les `FF` ont bien disparu des fichiers également, mais leur taille va nécessiter une correction (taille double alors que ce n'est plus nécessaire). Je t'envoie un PR dans la matinée avec les correctifs nécessaires + la dernière version du port libretro.

**Comment by barbudreadmon** [comment]
Les changements sur les sauvegardes externes ont été push, testé avec les 4 types de cartouche de backup et pas de soucis de mon côté. 

Détail intéressant, en lançant Panzer Dragoon Saga, je me suis rendu compte qu'il tentait de lire des word/long sur la cartouche (ce qui visiblement n'est pas censé être le cas avec les cartouches de backup, d'ailleurs j'ai désactivé les fonctions dans mon commit), je pense que c'est directement lié à cette mesure anti action replay expliquée ici : https://www.panzerdragoonlegacy.com/articles/panzer-dragoon-saga-action-replay-codes . Le jeu possède visiblement une mesure anti dézonnage via l'action replay.

**Comment by BenjaminSiskoo** [comment]
Tes correctifs sur la les save concernent que le port libretro ?

**Comment by FCare** [comment]
Non, tout le moteur


Le sam. 24 nov. 2018 à 12:15, BenjaminSiskoo <notifications@github.com> a
écrit :

**Comment by BenjaminSiskoo** [comment]
nice, je pourrais mettre quoi dans ce cas pour le changelog ? Correctif sur la bkram (mais concrètement sur quoi) ?

**Comment by barbudreadmon** [comment]
En gros, 2 choses ont été corrigées/améliorées : 
- déjà certains jeux ne fonctionnaient pas avec la sauvegarde interne (les 2 cités plus haut, probablement beaucoup d'autres), logique car il y avait une incohérence entre la taille et le contenu.
- c'est un peu arbitraire, mais on a décidé de optimiser/normaliser les sauvegardes, comme la moitié du contenu du fichier ne servait à rien, on a décidé de le supprimer, et de réduire la taille des sauvegardes par 2, ce qui au passage assure une compatibilité avec les fichiers de sauvegarde de mednafen

**Comment by BenjaminSiskoo** [comment]
@barbudreadmon 

Voilà ce que j'ai avec certains jeux des caractères bizarre : 

![beachdereachbkram](https://user-images.githubusercontent.com/12481242/48968720-b8200e00-eff3-11e8-97b9-5b4da93a730a.PNG)
![bkramastra](https://user-images.githubusercontent.com/12481242/48968721-b8200e00-eff3-11e8-9b6b-37feba1cd342.PNG)

**Comment by BenjaminSiskoo** [comment]
Fichier de sauvegarde : 


[bkram.zip](https://github.com/FCare/Kronos/files/2612270/bkram.zip)

**Comment by FCare** [comment]
Le champ commentaire dans la sauvegarde vaut 0xFFFFFFF... Le reste du fichier est bon...
Est ce que tu peux regarder avec le gestionnaire de la memoire intégré a la saturn? est ce que tu vois le commentaire?

**Comment by FCare** [comment]
![save](https://user-images.githubusercontent.com/14252808/48968916-6b8a0200-eff6-11e8-9e23-084e7a08252a.png)

**Comment by FCare** [comment]
Le champ commentaire n'est pas celui a FFFF. Mais le commentaire est en japonnais, d'ou le pb. Il faudrait passer l'interface en UTF-16 peut etre...
En tout cas, c'est un bug tres mineur.
