### ISSUE TITLE
[Mega Man 8 & X4] Léger problème graphique

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#360]
Bug rapporté sur le port libretro : https://forums.libretro.com/t/issue-with-saturn-kronos-core-as-of-11-18-18/19159

![Mega man 8](https://i.postimg.cc/q7gYCV7f/Mega-Man-8-USA-181119-104437.png)

La barre de vie devrait plutôt ressembler à çà : 
![Mega man 8](https://i.postimg.cc/HxD2Wfc9/Mega-Man-8-USA-181119-112836.png)
(il n'y a pas les traits bizarres sur le côté gauche de la barre)

La seconde image provient de mednafen, il semble que le vieux yabause n'avait pas ce problème non plus.
Mega Man X4 a le même soucis.

**Comment by BenjaminSiskoo** [comment]
Pris avec les derniers commits du 20/11/2018. Testé avec la version Windows standalone. Testé avec différents filtres et sans filtre.

![megaman8](https://user-images.githubusercontent.com/12481242/48811415-ef5d9900-ed2d-11e8-95cb-b4e753cbbdf4.PNG)

La barre de vie est correcte.

**Comment by barbudreadmon** [comment]
Problème toujours présent chez moi, y compris sur standalone (linux), quels que soient les réglages.

**Comment by FCare** [comment]
As-tu bien reussi ton rebase? Les patchs sont bien presents dans ta branche?

Le mer. 21 nov. 2018 à 08:40, barbudreadmon <notifications@github.com> a
écrit :

**Comment by barbudreadmon** [comment]
Le problème est présent pour moi sur la version standalone provenant de ta branche. Pour les différences avec la branche du mirror libretro, il n'y a rien hormis https://github.com/FCare/Kronos/pull/359, les fichiers musashi et zconf pré-générés, et quelques ajouts dans libretro.c que j'enverrai vers ta branche prochainement.

Edit : à noter aussi que le dernier commit provoque à nouveau le problème sur Sega Rally Plus chez moi (il était disparu après ta série de revert)

**Comment by barbudreadmon** [comment]
@FCare Pas mieux avec gcc-8.2, problème lié aux cartes nvidia peut-être ?

**Comment by BenjaminSiskoo** [comment]
@barbudreadmon tu as bien reset ton kronos.ini et virer ta bkram ?

**Comment by barbudreadmon** [comment]
@BenjaminSiskoo oui

**Comment by BenjaminSiskoo** [comment]
@barbudreadmon probablement un soucis sous linux, à un moment donné on avait des petites différences entre windows et linux sur certains jeux (en général ca passe d'abord sous linux et ensuite François corrige pour windows) et dans certtains cas, c'est mieux sous windows que sur linux.

**Comment by barbudreadmon** [comment]
@BenjaminSiskoo j'ai quelqu'un d'autre sous windows (et avec un gpu nvidia) qui me confirme qu'il a le même problème.

**Comment by BenjaminSiskoo** [comment]
@barbudreadmon j'ai vu ton message sur discord, il faudrait trouver quelqu'un d'autre avec une radeon comme moi.

**Comment by barbudreadmon** [comment]
> I wonder if it has to do with odd numbers, I noticed Nvidia accepted them but not AMD cards when cropping the output in mednafen PCE
some kind of rounding at driver level?

@FCare Petit quote du discord libretro, peut-être une piste ?
L'autre chose à laquelle je pensais c'est les appels gl qui ne sont pas en `ARB` dans YabaSanshiro/Kronos, ce qui si je comprend bien signifie qu'ils ne sont pas forcément "standardisés" d'un vendeur gpu à un autre ?

Un petit zoom sur le bug : 
![bug](https://cdn.discordapp.com/attachments/434759979095031840/514776299366121472/Mega_Man_8_Anniversary_Collectors_Edition_USaturn-181121-130623.png)
Détail interessant : les points bleu/rouge apparaissent dans mednafen quand la barre de vie diminue, en fait il semble qu'il manque simplement une barre marron dans kronos.

Autre bug du jeu : 
![bug](https://media.discordapp.net/attachments/434759979095031840/514773882239057920/Mega_Man_8_Anniversary_Collectors_Edition_USaturn-181121-130616.png)
Le haut de l'écran a disparu

@tatsuya79 Thanks for all those screenshots and comments :)

**Comment by barbudreadmon** [comment]
Il semble que le gpu vendor ne soit pas en cause, l'auteur du post sur le forum possède une gtx1060 et çà fonctionne pour lui.

**Comment by BenjaminSiskoo** [comment]
Le problème de la barre je l'ai aussi sous windows, c'est dû à l'openglsize quand tu passe en x2, x4 , etc... Avec l'original pas de soucis avec la barre.

**Comment by barbudreadmon** [comment]
@BenjaminSiskoo pour ma part le problème se produit quelle que soit la résolution (testé ce matin avec les derniers commits, pas de changement), mais c'est bon à savoir que c'est reproduisible sur d'autres configs en changeant la taille du framebuffer, çà pourrait aider à régler le problème au global

**Comment by BenjaminSiskoo** [comment]
@barbudreadmon c'est pour ca que c'est utile. Si tu peux essaye de récupérer les infos sur la partie vidéo (un screen serait suffisant). Mais je ne me rendais pas compte que les filtres pouvaient créer des artefacts à certains moments. Je me souviens de Kega Lazarus qui à ma connaissance n'avait pas ces problèmes de filtres. Encore une fois chapeau ami dév, sacré taff :)

**Comment by fafling** [comment]
Le problème vient de la commande de dessin de la barre et de la façon dont Kronos rétrécit une texture qui n'est pas identique à celle du VDP1.

La commande dessine sur 15 pixels de large une texture qui en fait 16. Il y a donc 1 colonne de pixels de la texture qui n'est pas dessinée. Or cette texture ne comporte que 8 colonnes de pixels visibles qui sont à droite de la texture. La console ne dessine pas une des colonnes transparentes qui se trouve à gauche de la texture, alors que Kronos ne dessine pas la fameuse colonne marron, ce qui laisse une des 8 colonnes quadrillées de la jauge visible.

La commande de dessin de la barre (en plus de s'être planté sur le nombre de pixels à dessiner, les dev de Capcom n'ont pas l'air de savoir qu'on peut faire des textures de 8 pixels de large sur Saturn) :
![Capture_megaman8](https://user-images.githubusercontent.com/7624262/58288614-6db9f700-7db4-11e9-9484-b928f0414409.PNG)

Une des commandes de dessin de la jauge :
![Capture_megaman8_2](https://user-images.githubusercontent.com/7624262/58288636-7f9b9a00-7db4-11e9-88cc-599f8506d073.PNG)

**Comment by fafling** [comment]
Le problème de la barre de vie dans Megaman X4 est réglé en v1.7.0 publique, il venait d'expansions inutiles sur des sprites ou polygones rectangulaires.

Par contre dans Rockman 8, le rétrécissement latéral de la barre de vie est toujours incorrect dans la WIP du 04/09, même avec le noyau compute shader.

**Comment by barbudreadmon** [comment]
Le problème sur la barre de vie de Mega Man 8 existe toujours en noyau OpenGL sur la wip du 26 avril 2020 (noyau CS ok).

**Comment by BenjaminSiskoo** [comment]
@barbudreadmon il me semble que c'est corrigé

**Comment by fafling** [comment]
Le problème est toujours là en OpenGL en WIP du 19/10.

**Comment by BenjaminSiskoo** [comment]
@fafling @barbudreadmon 

Ca semble ok non ?

![image](https://user-images.githubusercontent.com/12481242/136539502-4d58db66-ad56-463b-82e7-bcfc3aac6556.png)

**Comment by BenjaminSiskoo** [comment]
@FCare n'a pas prévu de corriger ce bug ou celui de Sega Rally en OpenGL, à terme, ce core devrait être supprimé. Pour passer sous vulkan.
