### ISSUE TITLE
[Sega Rally Championship] problème avec la poussière derrière la voiture...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#362]
Tout est dans le titre

https://www.youtube.com/watch?v=_x_E1wUvzb4

**Comment by FCare** [comment]
En arcade ca y est:
https://www.youtube.com/watch?v=iroy7m5jQss

En fait je pense que ca doit dependre de la version du jeu...

Le mer. 21 nov. 2018 à 11:50, BenjaminSiskoo <notifications@github.com> a
écrit :

**Comment by BenjaminSiskoo** [comment]
Bien vu :)

**Comment by barbudreadmon** [comment]
En fait quel est le problème ? J'ai l'impression que le rendu de Kronos pour cette poussière est très proche de celui dans la vraie saturn (https://www.youtube.com/watch?v=_x_E1wUvzb4), non ?
En tout cas la version arcade sur Model 2 est très jolie, je comprend mieux pourquoi ils ont choisi de ne pas utiliser le hardware de la model 2 pour la saturn, çà devait coûter un bras du hardware 3D comme çà à l'époque.

**Comment by BenjaminSiskoo** [comment]
Je suis pas sûr que ce soit bon, on dirait que tu as une bande rectangulaire de poussière puis une bande vierge puis une autre bande de poussière. Sinon autre exemple : Après je suis pas assez calé sur ce jeu.

![sega rally](https://user-images.githubusercontent.com/12481242/48844525-603a9a80-ed9a-11e8-87cf-d6a11305646a.PNG)

**Comment by Tatsuya79** [comment]
C'est le même rendu avec mednafen:
2 bandes de poussière séparées avec la plus éloignée du véhicule qui s'élève plus haut régulièrement.
