### ISSUE TITLE
Compatibilité avec profils GL Core

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#363]
J'ai discuté un peu avec @flyinghead à propos de çà, apparemment il ne nous manque pas grand chose.

Déjà dans la gestion des buffers de données, il faudrait les créer, les binder, définir le contenu et ensuite l'attribut, par exemple : 
> glVertexAttribPointer(POSITION, 2, GL_FLOAT, GL_FALSE, 0, (GLvoid *)vertices);

deviendrait
> GLuint vertices_buf;
  glGenBuffers(1, &vertices_buf);
  glBindBuffer(GL_ARRAY_BUFFER, vertices_buf);
  glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STREAM_DRAW);
  glVertexAttribPointer(POSITION, 2, GL_FLOAT, GL_FALSE, 0, (GLvoid *)vertices);

2ème chose, @FCare et moi pensons qu'il nous manque des appels à `glGenVertexArray`/`glBindVertexArray`, un exemple d'utilisation est là : https://stackoverflow.com/questions/27027602/glvertexattribpointer-gl-invalid-operation-invalid-vao-vbo-pointer-usage.

3ème chose, il faut changer les `#version 310 es` dans yglshaderes.c par des `#version 330 core`, et à priori ceux qui sont accompagnés de `#extension GL_ANDROID_extension_pack_es31a : enable` par des `#version 420 core` (rapport à la tesselation), à mon avis garder un moyen de compiler les shaders es via un define serait une bonne idée si on a l'intention de garder une compatibilité avec OpenGLES.

Le reste n'est à priori que de l'initialisation de contexte, j'ai pas mal épluché https://retokoradi.com/2014/03/30/opengl-transition-to-core-profile/ hier et dans l'ensemble je pense qu'on est bon

**Comment by barbudreadmon** [comment]
J'ai tenté de mettre ces choses en place, je n'ai plus d'erreur GL, par contre j'ai un écran noir et au bout d'un moment çà se fige, je soupçonne une histoire de libération de variable, peut-être que quelqu'un réussira à aller plus loin que moi ? Ci-joint les 3 fichiers modifiés dans le codebase + le libretro.c avec l'initialisation du contexte opengl core : https://www.sendspace.com/file/yj7vh2

Edit : j'avais oublié quelques glVertexAttribPointer : https://www.sendspace.com/file/2lfak3 , mais toujours pas mieux.
Edit2: un dernier oubli : https://www.sendspace.com/file/h85wcy , cette fois je pense avoir fait le tour. 

J'en profite pour mettre un diff du debug OpenGL "non-core" vers "core" au cas où çà pourrait donner des pistes : https://pastebin.com/raw/k12AyD3p

**Comment by FCare** [comment]
OpenGL core fonctionne maintenant :-)
