### ISSUE TITLE
[libretro] Pas de limitation de framerate quand le frameskip est activé

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#365]
Testé sur le port libretro.

Il semble que l'option de frameskip ignore la limitation à 50 fps sur les jeux PAL, je ne pense pas que ce problème était présent il y a quelques semaines.

**Comment by FCare** [comment]
Sur le standalone ca marche chez moi... ca ne viendrait pas de ton patch
pour l'init automatique des cartouches?

Le dim. 25 nov. 2018 à 18:05, barbudreadmon <notifications@github.com> a
écrit :

**Comment by barbudreadmon** [comment]
En fait je me rend compte que le problème a toujours été là, quand j'active le frameskip les jeux n'ont plus de limite de fps (je me retrouve à du 150+ fps), je pensais avoir résolu le problème en activant le vsync dans la configuration de retroarch, sauf que visiblement çà ne fait que limiter à 60 fps (et je n'avais pas lancé de jeu pal avec le frameskip activé depuis un bon moment je pense).

Si tu as une idée de ce qui peut causer çà, je suis preneur.

**Comment by FCare** [comment]
Le vsync synchronise a la vitesse de l'ecran, pas du jeu...

Le 25 nov. 2018 19:55, "barbudreadmon" <notifications@github.com> a écrit :

En fait je me rend compte que le problème a toujours été là, quand j'active
le frameskip les jeux n'ont plus de limite de fps (je me retrouve à du 150+
fps), je pensais avoir résolu le problème en activant le vsync dans la
configuration de retroarch, sauf que visiblement çà ne fait que limiter à
60 fps (et je n'avais pas lancé de jeu pal avec le frameskip activé depuis
un bon moment je pense).

Si tu as une idée de ce qui peut causer çà, je suis preneur.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/FCare/Kronos/issues/365#issuecomment-441463295>, or mute
the thread

**Comment by FCare** [comment]
Il faut renvoyer la bonne vitesse de syncho a retroarch dans ce cas la...

**Comment by barbudreadmon** [comment]
Je lui envoie déjà le framerate, mais à mon avis il ne s'en sert pas pour limiter la vitesse de synchro, d'ailleurs j'ai essayé de le régler à `10.0f` pour voir si il y avait une différence, çà n'a rien changé. 
Visiblement je peux jouer avec les multiples réglages vsync de retroarch pour "cacher" le problème, notamment en activant le "hard gpu sync", mais devoir utiliser une configuration spécifique dans retroarch pour un core ne me semble pas une solution viable à long terme.
@Tatsuya79 toi qui t'y connais un peu en sync dans retroarch visiblement, une idée ?

**Comment by Tatsuya79** [comment]
Dernière fois que je testais uoYabause et Kronos stand-alone la vitesse était de x2 sur mon écran G-sync à 120hz et je devais utiliser un limiteur.
Ceci a changé récemment? c'est peut-être la raison.

**Comment by barbudreadmon** [comment]
J'essaie de comprendre l'algo de frameskip, mais j'ai un peu de mal : 
https://github.com/FCare/Kronos/blob/b78efc5e149c0331c78fbe7b66510d9f5e9b7123/yabause/src/scsp.c#L5516-L5536

J'ai un peu l'impression que quand le frameskip n'est pas activé, ce code est exécuté, et qu'il sert à ajuster plusieurs choses si on est en avance sur le framerate attendu du jeu ?

**Comment by FCare** [comment]
Il est utile uniquement pour la pause si je me souviens. La gestion du
framerate est faite dans yabause.c. de ce que j'avais compris retroarch
demande d'executer une trame a chaque appel et le plus vite possible. Ca
n'a pas l'air d'etre le cas... il faudrait creuser le code de retroarch
pour trouver la boucle de synchro et voir ce qui l'active..

Le lun. 26 nov. 2018 à 08:25, barbudreadmon <notifications@github.com> a
écrit :

**Comment by barbudreadmon** [comment]
> Il est utile uniquement pour la pause si je me souviens

Ce serait plutôt bizarre, en dehors d'un bout de code pour changer le format d'affichage du framerate sur l'osd dans vdp1.c, c'est le seul endroit qui utilise `isAutoFrameSkip()`, et les variables `autoframeskipenab` ou `yinit->frameskip` ne sont pas utilisées directement ailleurs.

Sinon oui, retroarch s'attend à exécuter une trame à chaque appel, le plus vite possible et sans correction de timing, car en appuyant sur le bouton de fast forward (par défaut la barre espace), il va essayer d’exécuter le code le plus vite possible en désactivant les éventuelles options de sync (NB : le frameskip de kronos empêche ce fonctionnement quand il n'est pas activé, certainement les corrections de timing liées au code plus haut).

**Comment by FCare** [comment]
Dans le source de retroarch, la boucle d'execution dort effectivement si:

if ((settings->uints.video_frame_delay > 0) && !input_nonblock_state)
retro_sleep(settings->uints.video_frame_delay);
Il faut donc trouver comment regler la valeur video_frame_delay depuis le
moteur kronos...

**Comment by FCare** [comment]
On a ca egalement:
/* Condition for max speed x0.0 when vrr_runloop is off to skip that part */
if (settings->floats.fastforward_ratio || settings->bools.vrr_runloop_enable
)
end:
{
retro_time_t to_sleep_ms;
if (settings->bools.vrr_runloop_enable)
{
struct retro_system_av_info *av_info =
video_viewport_get_system_av_info();
/* Sync on video only, block audio later. */
if (fastforward_after_frames && settings->bools.audio_sync)
{
if (fastforward_after_frames == 1)
command_event(CMD_EVENT_AUDIO_SET_NONBLOCKING_STATE, NULL);
fastforward_after_frames++;
if (fastforward_after_frames == 6)
{
command_event(CMD_EVENT_AUDIO_SET_BLOCKING_STATE, NULL);
fastforward_after_frames = 0;
}
}
/* Fast Forward for max speed x0.0 */
if (!settings->floats.fastforward_ratio && runloop_fastmotion)
return 0;
frame_limit_minimum_time =
(retro_time_t)roundf(1000000.0f / (av_info->timing.fps *
(runloop_fastmotion ? settings->floats.fastforward_ratio : 1.0f)));
}
to_sleep_ms = (
(frame_limit_last_time + frame_limit_minimum_time)
- cpu_features_get_time_usec()) / 1000;
if (to_sleep_ms > 0)
{
*sleep_ms = (unsigned)to_sleep_ms;
/* Combat jitter a bit. */
frame_limit_last_time += frame_limit_minimum_time;
return 1;
} Donc normalement, il devrait bien utiliser le timing.fps pour attendre la
prochaine image. mais il faut que le test if (settings->floats.
fastforward_ratio || settings->bools.vrr_runloop_enable) passe...

**Comment by Tatsuya79** [comment]
C'est ce que j'ai ajouté dans settings>frame throttle>sync to exact content ce "vrr_runloop".
Ça force le timing demandé par le core mais, en dehors des écrans gsync/freesync, le rendu sera en v-sync OFF.

En dehors de cette option, settings>frame throttle>max speed à x1 permet de limiter la vitesse quand FF est off.
Avec l'option "exact sync", c'est fait dans le code. Le max n'est utilisé qu'en FF.

**Comment by barbudreadmon** [comment]
@Tatsuya79 Oui mais on peut faire çà programmatiquement depuis le core ? Le fait d'avoir besoin de changer les réglages vidéos de retroarch spécifiquement pour un core ne me semble pas une super idée d'un point de vue simplicité d'utilisation.

**Comment by Tatsuya79** [comment]
J'explique juste ce que fait cette option, mais non, le core doit gérer tout ça tout seul.

Mais dans le code de Yabause plus haut si tu as (isAutoFrameSkip()==0)) comme condition pour sleep, ça signifie que quand le frameskip est actif il n'y a pas de cadence régulée. (enfin, pas ici du moins)

**Comment by barbudreadmon** [comment]
Encore quelques tests à effectuer mais il semble qu'il y ait du mieux quand frameskip est activé et vsync ne l'est pas. Activer frameskip a l'air de désactiver le limiteur de framerate (pas grand chose à voir avec du frameskip en fait), donc à mon avis il va falloir l'activer par défaut car les limiteurs de framerate sont déconseillés dans retroarch.
Le fait que retroarch ignore le framerate que je lui fournis quand vsync est activé reste assez obscur : ce n'est pas le cas dans mon core fbalpha.

**Comment by FCare** [comment]
clairement SET_GEOMETRY ne s'occupe pas de la valeur FPS:
case RETRO_ENVIRONMENT_SET_GEOMETRY:
      {
         const struct retro_game_geometry *in_geom = NULL;
         struct retro_game_geometry *geom = NULL;
         struct retro_system_av_info *av_info =
            video_viewport_get_system_av_info();

         if (av_info)
            geom = (struct retro_game_geometry*)&av_info->geometry;

         if (!geom)
            return false;

         in_geom = (const struct retro_game_geometry*)data;

         RARCH_LOG("Environ SET_GEOMETRY.\n");

         /* Can potentially be called every frame,
          * don't do anything unless required. */
         if (  (geom->base_width   != in_geom->base_width)  ||
               (geom->base_height  != in_geom->base_height) ||
               (geom->aspect_ratio != in_geom->aspect_ratio))
         {
            geom->base_width   = in_geom->base_width;
            geom->base_height  = in_geom->base_height;
            geom->aspect_ratio = in_geom->aspect_ratio;

            RARCH_LOG("SET_GEOMETRY: %ux%u, aspect: %.3f.\n",
                  geom->base_width, geom->base_height, geom->aspect_ratio);

            /* Forces recomputation of aspect ratios if
             * using core-dependent aspect ratios. */
            command_event(CMD_EVENT_VIDEO_SET_ASPECT_RATIO, NULL);

            /* TODO: Figure out what to do, if anything, with recording. */
         }
         break;

Le lun. 26 nov. 2018 à 13:25, barbudreadmon <notifications@github.com> a
écrit :

**Comment by FCare** [comment]
@Tatsuya79 : comme je n'ai pas ton mail, je pose la question ici. Je pense que dans Kronos, on perd en latence sur les evenements de touches controlleur. Je voudrais savoir comment retroarch mesure l'input lag. Tu aurais des infos la dessus?

**Comment by Tatsuya79** [comment]
En effet, je viens de tester avec Mega Man 8 en mettant pause dans RA, gardant une direction appuyée, et comptant les frames avant d'avoir une réaction à l'écran (K pour next frame step).

4 frames dans beetle saturn
5 frames dans Kronos

**Comment by FCare** [comment]
Ok merci pour le test. Je vais regarder ca...
