### ISSUE TITLE
Megaman 8 specific issue

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#371]
Graphical problem in a specific world of megaman 8, there are some black squares:

This only happens in two areas of Swordsman stage (All the other worlds works perfect) here´s a screenshot of the problem in one of the two areas:
![sin titulo](https://user-images.githubusercontent.com/12205048/49124615-63171d00-f2bd-11e8-98b4-2bc284756819.jpg)

And here´s the savegame in order to test it (USA version)

[bkram.zip](https://github.com/FCare/Kronos/files/2622588/bkram.zip)

**Comment by barbudreadmon** [comment]
Might be related to the issues in https://github.com/FCare/Kronos/issues/360 (sorry it's all french talks).
I see you also have the healthbar issue, may i ask what's your hardware (cpu/gpu) ?

**Comment by LuismaSP89** [comment]
Oh... I didn't noticed the healthbar issue.

Don't worry, I can use google translate to understand what you say in that thread xD

My specs:

Nvidia GTX 970
I7 4790k
16 GB RAM DDR3
Windows 10 x64

**Comment by BenjaminSiskoo** [comment]
Enable/disable layers. Sometimes you can see which layer is bad/incorrect.

**Comment by LuismaSP89** [comment]
It seems the problem is with the third layer (NBG1) but disabling it causes other graphical problems (Images attached)

Here with all layers enabled:
![1](https://user-images.githubusercontent.com/12205048/49156525-dbadc600-f31d-11e8-8030-c5835a164acc.jpg)

And here with the third layer disabled:
![sin titulo2](https://user-images.githubusercontent.com/12205048/49156573-f6803a80-f31d-11e8-85cc-6010822524f4.jpg)

Finally, here´s the image of the area in the first post, but with the third layer disabled:

![sin titulo3](https://user-images.githubusercontent.com/12205048/49156609-0d269180-f31e-11e8-82c4-d94fd8847244.jpg)

**Comment by BenjaminSiskoo** [comment]
By the way, there is a problem with the life bar. With OpenGL size --> Original, life bar is nice. With 2X, it's not good like on the picture above.

**Comment by LuismaSP89** [comment]
Update:
![2](https://user-images.githubusercontent.com/12205048/53645137-86dd5c80-3c38-11e9-8035-2d9975c5b20d.jpg)
![1](https://user-images.githubusercontent.com/12205048/53645138-8775f300-3c38-11e9-8f9a-3643de319f3a.jpg)

There are still issues, but the black square is gone. The problem still with the third layer. The life bar problem is present too.

Note: Using x64 build from 03/01/2019 provided by @BenjaminSiskoo with the new Opengl core

**Comment by fafling** [comment]
The second screenshot is corrected in the last WIP (couldn't get to the first screenshot) :
![Capture](https://user-images.githubusercontent.com/7624262/58290539-6f86b900-7dba-11e9-9f82-9296a7ef52c2.PNG)

**Comment by fafling** [comment]
In public v1.7.0, I confirm that the black squares issue is solved :
![Capture_megaman8_1 7 0](https://user-images.githubusercontent.com/7624262/59393314-4df66d00-8d7b-11e9-85bd-c16123b6f8ed.PNG)

@BenjaminSiskoo Since the life bar issue has its own bug report (#360 ), you can close.

**Comment by LuismaSP89** [comment]
Perfect, can confirm the issue no longer exists ^^
