### ISSUE TITLE
[Support request] Information about BIOS

### ISSUE THREAD

**Issue by ofry** [FCare/Kronos#380]
Please provide more specific information about saturn_bios.bin

That's because at least 8 different firmware versions exist.

https://tcrf.net/Sega_Saturn

Related to https://github.com/libretro/yabause/issues/53

**Comment by FCare** [comment]
All of the 8 bios are valid. Some Bios will only work with US or Japan games.
You can find non zonned bios on the web.

Once you have the bios, you just have to rename it.
