### ISSUE TITLE
[Sega Rally Championship Plus] Disparition de plusieurs indicateurs sur l'écran

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#388]
![sega rally championship plus japan -181222-110407](https://user-images.githubusercontent.com/10391265/50373078-abcea700-05d9-11e9-88f1-b48096451e07.png)

Port : libretro
Edit : Bon, apparemment le bug est présent pour moi depuis le passage à l'OpenGL Core

**Comment by BenjaminSiskoo** [comment]
Ca fonctionne sur le port standalone, j'ai testé si tu désactive la couche NBG2 tu as le résultat de ta photo.

**Comment by barbudreadmon** [comment]
@tatsuya79 n'a pas ce bug non plus sur la version libretro, autre truc bizarre je suis presque sûr que je ne l'avais pas encore quand j'ai testé le jeu pour la dernière fois (et il me semble bien l'avoir testé juste après le passage à l'OpenGL Core)

**Comment by BenjaminSiskoo** [comment]
Tu pu activber/désactiver les couches ?

**Comment by barbudreadmon** [comment]
Pas sur le port libretro, faudrait que je regarde pour ajouter des cores option pour faire çà.

**Comment by barbudreadmon** [comment]
Autre théorie : j'ai mis à jour mes drivers nvidia avant-hier...

**Comment by BenjaminSiskoo** [comment]
Tu as bien testé avec le correctif qu'a supprimé François ce matin, je vais checker Sega Rally sur RA

**Comment by barbudreadmon** [comment]
Oui c'est bien la dernière version avec le fix pour SF3
Edit : ah non, pas vu qu'il y avait eu un autre fix derrière
Edit2 : toujours pareil avec le dernier fix

**Comment by BenjaminSiskoo** [comment]
Ca fonctionne, c'est pas dû au correctif Ati ?


![segarally](https://user-images.githubusercontent.com/12481242/50373511-711c3d00-05e0-11e9-92fb-93fb86d77a51.PNG)

**Comment by FCare** [comment]
Meme version de l'iso? Sega rally a plein de versions differentes...

Le sam. 22 déc. 2018 à 11:55, BenjaminSiskoo <notifications@github.com> a
écrit :

**Comment by BenjaminSiskoo** [comment]
sur RA j'ai du utiliser la version redump, la version non redump ne passe pas sur RA mais passe sur Kronos stand alone.

**Comment by barbudreadmon** [comment]
J'ai utilisé le même iso que d'habitude (redump), j'ai essayé de revenir en arrière sur mon driver nvidia mais çà n'a rien changé

**Comment by barbudreadmon** [comment]
J'ai trouvé le problème : mes correctifs pour prendre possession du contexte OpenGL dans le port libretro.
Par contre si je les retire j'ai des crashs dans certains jeux...

**Comment by barbudreadmon** [comment]
Bizarre, même très très étrange, les problèmes que j'avais il y a quelques jours sans ce patch pour prendre possession du context ont disparu, je suppose que le problème était lié à autre chose et que çà a été corrigé par un autre commit... Je vire çà dans mon prochain PR.

**Comment by FCare** [comment]
Essaie de faire ton appel au depart d'une trame et a la fin d'une trame.
Entre deux le contexte ne change pas de thread

Le sam. 22 déc. 2018 à 13:06, barbudreadmon <notifications@github.com> a
écrit :

**Comment by FCare** [comment]
Ok

Le 22 déc. 2018 13:22, "Francois CARON" <francois.caron.perso@gmail.com> a
écrit :

Essaie de faire ton appel au depart d'une trame et a la fin d'une trame.
Entre deux le contexte ne change pas de thread

Le sam. 22 déc. 2018 à 13:06, barbudreadmon <notifications@github.com> a
écrit :

**Comment by barbudreadmon** [comment]
PR envoyé, je ferme ;)
