### ISSUE TITLE
[NBA Jam - Tournament Edition] Mots tronqués sur le press start screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#407]
Kronos 1.6.0

![nbajamte](https://user-images.githubusercontent.com/12481242/50965689-ff465d80-14d2-11e9-87e9-274a0e5a2401.PNG)

**Comment by fafling** [comment]
En version WIP du 17/03, c'est moins tronqué, mais en fait il manque l'affichage du sprite "head to head".

![Capture_NBAjamTE1](https://user-images.githubusercontent.com/7624262/56070053-381df900-5d86-11e9-9cc1-0c711acc9baf.JPG)
![Capture_NBAjamTE](https://user-images.githubusercontent.com/7624262/56070056-3b18e980-5d86-11e9-9c4e-4a9b16dde234.JPG)

**Comment by fafling** [comment]
Toujours présent en WIP du 20/12 dans les 2 noyaux.
Problème apparu dans uoYabause v0.4.0 avant le fork de Kronos, et toujours present dans Yaba Sanshiro v2.10.3.

**Comment by BenjaminSiskoo** [comment]
Corrigé en CS mais pas en OpenGL le 03/04/2020

**Comment by BenjaminSiskoo** [comment]
Ca a empiré en OpenGl avec la WIP du 20/10/2020

![image](https://user-images.githubusercontent.com/12481242/96523460-156f7900-1276-11eb-8f13-97f6fb8e8bd1.png)

**Comment by BenjaminSiskoo** [comment]
Kronos 14.10.2021

![image](https://user-images.githubusercontent.com/12481242/137474680-2ef9051b-9513-4a33-b234-35647eda1ab4.png)

**Comment by BenjaminSiskoo** [comment]
Kronos du 17.01.2023 
Cs

Ca semble corrigé : 
![image](https://user-images.githubusercontent.com/12481242/213052091-68b48690-355e-4136-8993-da8e891cd6c1.png)

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

Corrigé avec les timing du 14.12.2023
