### ISSUE TITLE
[NBA Jam Extreme] Problème de transparence sur les ombres des joueurs...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#408]
Kronos 1.6.0

![nbajamextreme](https://user-images.githubusercontent.com/12481242/50966136-5436a380-14d4-11e9-9f80-495c777301e3.PNG)

**Comment by fafling** [comment]
Je ne reproduit pas ce problème en V1.6.0 ni WIP du 17/03. Testé avec ISO US, bios jap et bios émulé, avec et sans filtre.

**Comment by BenjaminSiskoo** [comment]
Corrigé sur le rework pour moi.
