### ISSUE TITLE
[NBA Live 98] Problème de couleurs in game et bugs graphiques (VDP1 ?)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#409]
Kronos 1.6.0

![nbalive98](https://user-images.githubusercontent.com/12481242/50966611-bf34aa00-14d5-11e9-87b2-2da8df974b1b.PNG)
![nbalive981](https://user-images.githubusercontent.com/12481242/50966612-bf34aa00-14d5-11e9-80e7-4f3ec331752a.PNG)

**Comment by BenjaminSiskoo** [comment]
Amélioration avec le correctif du 10/01/2019 concernant nekketsu

![nbalive98](https://user-images.githubusercontent.com/12481242/51005149-f8086980-153d-11e9-90d8-5a9841e93585.PNG)

**Comment by fafling** [comment]
Problème supplémentaire dans la WIP du 23/05, les sprites sont semi-transparents :

![Capture_nba_live_98_20190523](https://user-images.githubusercontent.com/7624262/58759972-645a2880-8532-11e9-8eb7-a3bb4a25ce6c.PNG)

Le jeu utilise le type de sprite 1 (décrit un pixel de 16 bits) alors qu'il utilise un framebuffer 8 bits (d'après les coordonnées des sprites dans l'écran debug du VDP1). Kronos n'interprète pas cela de la même façon que la console.

![Capture_nba_live_98_20190523_VDP2](https://user-images.githubusercontent.com/7624262/58760251-b51f5080-8535-11e9-8835-7df6f4a4c6d0.PNG)

A priori le jeu s'attend à ce que les registres 0 de priorité et de color calculation ratio des sprites soient utilisés, car ils ont des valeurs différentes des autres registres :

![Capture_nba_live_98_20190523_VDP2_2](https://user-images.githubusercontent.com/7624262/58760269-fd3e7300-8535-11e9-885b-377acaa7f093.PNG)

On peut supposer que ce que fait la console, c'est d'utiliser le type de sprite indiqué par le jeu, donc sur 16 bits, en remplissant les 8 bits de poids faible avec les 8 bits de chaque pixel du framebuffer, et en mettant les 8 bits de poids fort à 0. Ainsi tous les pixels utilisent les registres 0 de priorité et de color calculation ratio des sprites. Les 3 bits de poids fort de l'adresse de la color RAM seraient aussi à 0, et comme le color RAM offset est à 0, ils sont utilisés tels quels.

Concernant la semi-transparence des sprites, cela montre une différence entre Kronos et la console sur la color calculation. Même si elle est activée sur les sprites avec un registre 0 de color calculation ratio à 15:17 (avec une condition sur le MSB de la color RAM qui n'est peut-être validée que parce que Kronos utilise des adresses dans la color RAM différentes de celles utilisées par la console), cette semi-transparence ne peut pas être affichée par la console : lorsque les sprites sont en top image, le RBG0 est en second image au moins sur le terrain. Il manque l'information du registre du transparent code dans l'écran debug du VDP2 pour savoir si le back screen peut être visible dans les zones noires du RBG0. En tout cas, là où le RBG0 n'est pas noir, comme il est au format palette (256 couleurs), comme la color RAM est de type 1 et comme l'affichage est en haute résolution (640x240), la semi-transparence n'est pas effectuée d'après le tableau 12.1 p. 236 de la doc du VDP2.

Toujours d'après ce tableau, dans ces conditions, la semi-transparence des sprites ne peut être effectuée qu'avec les pixels de la second image au format RGB, ce qui serait le cas si le back screen est visible dans les zones noires du RBG0.

**Comment by fafling** [comment]
En v1.7.0 publique, la semi-transparence incorrecte n'est plus là, mais le RBG0 n'est plus visible, il faut désactiver la couche de sprites pour le voir.
![Capture_nba_live_98_1 7 0](https://user-images.githubusercontent.com/7624262/59392140-e2aa9c00-8d76-11e9-9911-cf0108e022db.PNG)

**Comment by fafling** [comment]
@FCare Mettre les bits de poids fort à 1 donne effectivement les bonnes couleurs pour les sprites. Par contre, il reste un effet de color calculation incorrect. Le terrain (RBG0) est assombri avec la couche de sprites activée :
![image](https://user-images.githubusercontent.com/7624262/97788077-5e98c480-1bb6-11eb-88ac-9d9e401cbebb.png)

Le RBG0 a les couleurs correctes avec la couche de sprites désactivée :
![image](https://user-images.githubusercontent.com/7624262/97788140-e41c7480-1bb6-11eb-8879-b0aa6e9f3b6b.png)

La color calculation ne peut pas avoir lieu entre les sprites et le RBG0 avec la color ram en mode 1 et le RBG0 en mode palette.

**Comment by FCare** [comment]
Le bit TPSDSL est à 0 sur la couche sprite. Ce qui signifie que meme si le code transparent shadow est detecté, l'effet ne doit pas etre appliqué.

**Comment by fafling** [comment]
C'est OK dans les 2 noyaux depuis le 01/11.

**Comment by BenjaminSiskoo** [comment]
Je ferme
