### ISSUE TITLE
(Neon Evangelion - Digital Card Library] Press Start screen problème de VDP1 et FMV problème de NBG1 et artefact...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#411]
Kronos 1.6.0

![neongenesis digital](https://user-images.githubusercontent.com/12481242/50967193-adec9d00-14d7-11e9-9d74-30ce64ec0e9a.PNG)

Sur cette photo juste à côté de la vidéo, il y a un artefact avec plusieurs pixels en vertical. De plus, on le voit pas sur la photo, mais il y a des lignes horizontales sur la vignette de la vidéo qui s'enlève avec le NBG1

![neongenesis digital1](https://user-images.githubusercontent.com/12481242/50967194-ae853380-14d7-11e9-9e41-4a508f02eaba.PNG)

**Comment by fafling** [comment]
L'écran titre est corrigé par le fix du #664 dans la WIP accurate_vdp1 du 28/10.

L'affichage de la video n'est toujours pas correct dans cette WIP ni dans la WIP extui-align du 11/09 pour les 2 noyaux. Par contre l'affichage a changé par rapport à la v1.6.0 :
![image](https://user-images.githubusercontent.com/7624262/67820753-d0799200-faba-11e9-9a8b-ef3bea144464.png)
La video est affichée par le NBG0. Il ya peut-être une prise en compte incorrecte de la fenêtre W0 qui est activée sur cette couche. Le jeu est en haute résolution double interlace.
J'ai essayé de faire un save state, mais l'affichage de la video est modifié quand on le charge.

**Comment by BenjaminSiskoo** [comment]
Kronos 14.10.2021

![image](https://user-images.githubusercontent.com/12481242/137474922-910451aa-7f9a-4308-8763-af446e5068ac.png)

**Comment by fafling** [comment]
Je corrige mon commentaire du 30/10/2019 : la video est affichée par le NBG0, non par le NBG1.
Ne semble pas être un problème de fenêtre, car l'image de la video est en fait aplatie (capture faite en integer scaling).
Il a l'air de manquer la moitié des lignes, avec des trous réduits de moitié entre les lignes visibles affichées par paquet de 2.
Le viewer software n'affiche qu'une partie des lignes, mais l'aspect ratio est correct.
Peut-être que le jeu joue sur le double entrelacement et ne charge dans le bitmap que les lignes visibles sur le champ courant.
![image](https://user-images.githubusercontent.com/7624262/138555168-7820e484-a377-4bef-86fe-4ea5e69ab40b.png)

Possible aussi que le jeu charge une partie du bitmap pendant l'affichage. Dans Mednafen, on voit le cycle pattern de la partition A0 varier entre 4444FEEE et EEEEEEEE, ce qui indique un accès CPU (valeur E sur les 4 1er timings en haute résolution) possible pendant l'affichage sur la moitié supérieure du bitmap (qui occupe les partitions A0 et A1).
![image](https://user-images.githubusercontent.com/7624262/138557657-4a870a2d-a6fa-436e-8b91-526275e56730.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 15/12/2021
