### ISSUE TITLE
[NFL Quarterback Club '97] Les joueurs "pixellisent" en mouvement à certains moments

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#412]
Kronos 1.6.0

![nflquaterback97](https://user-images.githubusercontent.com/12481242/51106402-f368dd00-17eb-11e9-989a-34659b3712f6.PNG)

**Comment by FCare** [comment]
Ca ressemble aux memes artefacts que dans doom

**Comment by fafling** [comment]
Même problème en version WIP du 17/03.
Pas sûr que ce soit la même chose que dans Doom. Là, tous les sprites concernés sont visibles sans artifact dans l'écran debug du VDP1.

**Comment by fafling** [comment]
On dirait bien le même souci dans NBA JAM TE où ça se produit aussi de manière intermittente.

![CaptureNBAjamTE2](https://user-images.githubusercontent.com/7624262/56070615-15411400-5d89-11e9-906b-dc5c3149fe09.JPG)

Peut-être un point commun, dans les 2 cas, il s'agit de sprites 8-bit avec une palette réduite : 64 couleurs pour NFL et 128 pour NBA.

![CaptureNBAjamTE3](https://user-images.githubusercontent.com/7624262/56070618-1eca7c00-5d89-11e9-82db-7775d50d4969.JPG)
![Capture_nflquat97_2](https://user-images.githubusercontent.com/7624262/56070631-2f7af200-5d89-11e9-97d6-2f0eeed5dd15.JPG)

**Comment by fafling** [comment]
Je m'aperçois dans NFL qu'il peut y avoir le problème dans l'autre sens : des sprites affichés correctement à l'écran qui sont corrompus dans la fenêtre debug du VDP1.
Ici, le joueur qui fait le placage :
![Capture_nfl_opengl_ok_soft_ko](https://user-images.githubusercontent.com/7624262/56934305-d252a080-6aeb-11e9-8029-a9e81c60e1a2.PNG)
![Capture_nfl_opengl_ok_soft_ko2](https://user-images.githubusercontent.com/7624262/56934308-d41c6400-6aeb-11e9-94c7-054bdc8c5d56.PNG)

**Comment by BenjaminSiskoo** [comment]
@fafling tu pourrais me dire si tu as toujours la même chose, j'ai l'impression que c'est bon maintenant

**Comment by fafling** [comment]
Effectivement, ça a l'air d'avoir été résolu entre la v2.1.1 et la v2.1.2.

**Comment by BenjaminSiskoo** [comment]
Corrigé
