### ISSUE TITLE
[Night Striker S] Les lignes de la route sont déformés...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#414]
Kronos 1.6.0

![night strike s](https://user-images.githubusercontent.com/12481242/51107515-4f813080-17ef-11e9-9fc3-83852cc37424.PNG)

**Comment by BenjaminSiskoo** [comment]
![nightstriker](https://user-images.githubusercontent.com/12481242/51110217-29ac5980-17f8-11e9-8e52-849ea8c1b3b8.PNG)

**Comment by fafling** [comment]
C'est sûrement dû à une décomposition des quadrangles du VDP1 en triangles. C'est le même genre d'artifact que sur Playstation quand elle rend un quadrangle.
On peut le faire disparaître en changeant le mode de tesselation (il faut redémarrer Kronos, un reset de l'émulation ne suffit pas).
Le problème est présent dans les modes "Triangles using perspective correction" et "CPU tesselation" (en moins prononcé dans ce dernier), et il est absent du mode "GPU tesselation".

Triangles using perspective correction :
![capture_tri](https://user-images.githubusercontent.com/7624262/52510816-d7dfcf00-2bfd-11e9-87ba-c227cd505820.JPG)

CPU tesselation :
![capture_cpu](https://user-images.githubusercontent.com/7624262/52510826-e62deb00-2bfd-11e9-954b-d7f3a27772fe.JPG)

GPU tesselation :
![capture_gpu](https://user-images.githubusercontent.com/7624262/52510833-eb8b3580-2bfd-11e9-8edc-90d875c16258.JPG)

**Comment by BenjaminSiskoo** [comment]
Même si pour l'instant il n'y a pas de réponse (François retravaille une partie du code OpenGL), merci pour tes retours plus détaillé que les miens.

**Comment by fafling** [comment]
Tu as trouvé l'exemple parfait pour signaler ce problème, là c'est particulièrement flagrant.

Pour les devs, je ne sais pas si c'est possible mais ce qui serait bien, ce serait de mettre automatiquement "GPU tesselation" comme valeur par défaut de l'option Tesselation si le GPU le supporte, au lieu de "Triangles using perspective correction".

**Comment by BenjaminSiskoo** [comment]
Les options peuvent mise par défaut. Après je suppose qu'il y a un morceau de code en plus à ajouter pour dire, si votre GPU ne supporte pas alors utilisez l'option X à la place.

François retravaille le code OpenGL, ca te dit de faire tes tests depuis ce fork. Si oui, envoi moi un mail à Siskoo @ tradu - France . com (sans les espaces).

**Comment by FCare** [comment]
Oui ca doit venir du quad en triangle. Mais normalement, on devrait
compenser avec la coordonnee q dans les shaders. En tout ca la version cpu
corrigée ne devrait pas avoir ce pb ou pas autant

Le sam. 9 févr. 2019 à 12:08, BenjaminSiskoo <notifications@github.com> a
écrit :

**Comment by fafling** [comment]
C'est d'accord pour les tests.

Pour les quads en triangle, là ça se comporte comme s'il n'y avait aucune correction de perspective dans les triangles : les lignes ont l'air exactement parallèles aux côtés des quads, comme avec le mapping affine de la Playstation.

**Comment by FCare** [comment]
Je viens de regler le pb de la CPU tesselation sur la branche rework.

**Comment by BenjaminSiskoo** [comment]
Nice, possible fix pour Triangles using perspective correction ou pas ?

**Comment by fafling** [comment]
Effectivement c'est beaucoup mieux pour la CPU tesselation en version WIP du 13/04, on ne voit quasiment plus de zig-zag.

![Capture_night_striker_CPU_WIP20190413](https://user-images.githubusercontent.com/7624262/56246107-598e2600-60a1-11e9-98e4-9aae508ea2f8.PNG)

![Capture_night_striker_CPU_WIP20190413_2](https://user-images.githubusercontent.com/7624262/56246587-b50ce380-60a2-11e9-89e0-be313173313b.PNG)

**Comment by fafling** [comment]
Il faudrait signaler qu'un changement de l'option Video > Tesselation nécessite un redémarrage de
Kronos pour être pris en compte, dans son libellé ou avec une fenêtre de dialogue.

**Comment by FCare** [comment]
Fixé en mode CPU
