### ISSUE TITLE
[Night Warriors - Darkstalkers' Revenge] Persos affichés en noir...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#415]
Kronos 1.6.0

![night dark in game](https://user-images.githubusercontent.com/12481242/51107777-23b27a80-17f0-11e9-985f-4856ea951164.PNG)
![night dark](https://user-images.githubusercontent.com/12481242/51107778-244b1100-17f0-11e9-99c9-e51cb2be3b94.PNG)

**Comment by fafling** [comment]
Je n'ai pas le personnage en noir à la sélection, mais dès que j'appuie sur C pour sélectionner, il n'y a plus que du bruit video. Je rappuie sur C pour sélectionner le mode, on entend l'effet sonore, et ça passe à l'écran Now loading avec des couleurs incorrectes. Pendant le combat, les perso sont soit noirs, soit avec des couleurs incorrectes, les jauges et icones sont aussi corrompues.
![capture](https://user-images.githubusercontent.com/7624262/52187257-bc0ab080-282c-11e9-9184-145adae65d5d.JPG)
![capture2](https://user-images.githubusercontent.com/7624262/52187258-be6d0a80-282c-11e9-80de-e8dca907c416.JPG)
![capture3](https://user-images.githubusercontent.com/7624262/52187260-c036ce00-282c-11e9-8789-905763cd7182.JPG)
![capture4](https://user-images.githubusercontent.com/7624262/52187263-c167fb00-282c-11e9-9dd6-9b0e93eefb39.JPG)

**Comment by BenjaminSiskoo** [comment]
Avec Kronos du 25/04/2019 il semble que ce soit corrigé

![darksaltker](https://user-images.githubusercontent.com/12481242/56771324-956a6f00-67b6-11e9-8f7d-84df24c3a38a.PNG)
![darksaltker1](https://user-images.githubusercontent.com/12481242/56771325-956a6f00-67b6-11e9-8162-e14beffdc4bc.PNG)

**Comment by fafling** [comment]
Oui, je ne vois plus de corruption de couleurs.

**Comment by BenjaminSiskoo** [comment]
Je ferme :) corrigé le 25 Avril 2019

**Comment by fafling** [comment]
De nouveau présent en v2.1.5 publique et dans la dernière WIP, dans les 2 noyaux.
Réapparaît en WIP du 05/06/2019, la précédente du 23/05/2019 n'a pas le problème.
Testé avec le CD US.

Save state au début du 1er combat (atteindre le 1er écran de l'attract mode avec le loup-garou devant la Lune pour le charger) :
[Darkstalkers_revenge_1er_combat.zip](https://github.com/FCare/Kronos/files/6507497/Darkstalkers_revenge_1er_combat.zip)

@BenjaminSiskoo Est-ce que tu peux rouvrir ?

**Comment by BenjaminSiskoo** [comment]
Kronos 14.10.2021

Perso manquant

![image](https://user-images.githubusercontent.com/12481242/137475984-73e7b32f-fc42-4b71-a341-506cd91ed996.png)

**Comment by BenjaminSiskoo** [comment]
Kronos suite au fix de la branche test_screen_sync

![image](https://user-images.githubusercontent.com/12481242/213044620-7bdd3d69-e84e-47f5-818d-3e020ac82351.png)

on a la rémanence de la fenêtre précédente en arrière plan : 
![image](https://user-images.githubusercontent.com/12481242/213045018-988e0373-f678-4d00-9249-65b213bb5c69.png)

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

Corrigé

![image](https://github.com/FCare/Kronos/assets/12481242/adde6818-684e-4322-92df-d8a223e41ab1)
