### ISSUE TITLE
[Nissan Presents - Over Drivin' GT-R] Problème d'affichage in game (RBG0)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#417]
Kronos 1.6.0

En désactivant le RBG0, on a plus l'arrière plan mais le jeu est jouable.

![nissan2](https://user-images.githubusercontent.com/12481242/51109367-5448e300-17f5-11e9-9734-4ab562c80e3a.PNG)

**Comment by fafling** [comment]
@BenjaminSiskoo Est-ce que tu peux rouvrir ? Ce n'est pas résolu en WIP du 21/04, dernière avant que le jeu ne se mette à freezer ( #482 ).

**Comment by fafling** [comment]
Le RBG0 affiche l'arrière-plan et le volant au moyen de 2 paramètres de rotation. Le RBG0 est donc affiché avec 2 priorités différentes et comme il n'utilise pas de special priority, c'est qu'il doit y avoir un interrupt à la moitié de l'écran qui modifie la priorité de cette couche.

![Capture_need_for_speed_volant_VDP2](https://user-images.githubusercontent.com/7624262/57561965-701d5980-738f-11e9-8461-522be8e8f379.PNG)

En v1.6.0, la modif à mi-écran de la priorité est bien prise en compte, par contre le paysage est affiché à la place du volant (ce paysage tourne si on appuie à gauche ou à droite !).

![Need for speed](https://user-images.githubusercontent.com/7624262/57561957-5ed44d00-738f-11e9-8b40-8857325d6224.JPG)

Peut-être que cela indique que l'interrupt sert aussi à modifier l'adresse du bitmap affiché par le 2ème paramètre de rotation (ce qui est curieux car normalement, il n'y a pas besoin d'interrupt pour définir un graphisme différent pour chaque paramètre de rotation), et que la v1.6.0 ne prendrait pas en compte cette modification. Vu les adresse des 3 bitmaps 8 bits affichés par l'écran debug du VDP2, il y a de fortes chances que le volant soit aussi un bitmap 8 bit situé à l'adresse 60000.

En WIP du 21/04, la modif de priorité n'est plus prise en compte par Kronos et le paysage du bas n'est visible que si on désactive le NBG0 et les sprites.

![Capture_need_for_speed_volant](https://user-images.githubusercontent.com/7624262/57561971-7f9ca280-738f-11e9-9df7-a20bc851b54d.PNG)

![Capture_need_for_speed_volant2](https://user-images.githubusercontent.com/7624262/57561976-85928380-738f-11e9-8229-aef0372fa549.PNG)

Il serait utile que l'écran debug du VDP2 affiche les adresse de bitmap ou tilemap de chaque paramètre de rotation utilisé par le RBG0 quand il en utilise 2. Actuellement on n'en voit qu'une seule, or chaque paramètre de rotation peut être associé à des adresses différentes.

**Comment by fafling** [comment]
Toujours présent dans les 2 noyaux en WIP extui-align du 19/11.

**Comment by fafling** [comment]
Toujours présent en WIP du 30/12.

**Comment by fafling** [comment]
Toujours présent en WIP du 04/04, je remarque qu'il y a un progrès par rapport à mes dernières captures d'écran : le volant est maintenant affiché si on désactive les sprites et le NBG0. Il ne reste donc que le changement de priorité du RBG0 en cours d'affichage qui n'est pas émulé.
![image](https://user-images.githubusercontent.com/7624262/78512695-cb75e880-77a6-11ea-84af-aad59d31cd74.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé en ce jour avec la version du 5 Janvier 2021

**Comment by fafling** [comment]
Corrigé par 32833e00610eeabec6603be83d7d62d7623be677

**Comment by BenjaminSiskoo** [comment]
Le volant n'est plus affiché avec la version du 14.10.2021 en OpenGL et CS

**Comment by fafling** [comment]
Le volant n'a disparu qu'en RBG CS. En OpenGL (RBG CS désactivé), il est toujours là.
Le problème apparaît lors du fix des bitmaps en RBG CS du 24-25/09 (voir #537 ) :
- Dans la WIP du 24, le RBG0 disparaît complètement.
- Dans celle du 25, le paysage réapparaît, mais pas le volant.

**Comment by fafling** [comment]
On est dans le même cas de figure que dans la démo de Hellslave #1272 , 2 bitmaps sur le RBG0 en rotation parameter mode 2.

Etant donné qu'un seul paramètre de rotation peut s'afficher correctement sur la console dans cette situation, c'est donc que l'adresse du bitmap est modifiée en milieu d'écran non pas sur le 2ème paramètre de rotation comme je le supposais, mais en fait sur le même paramètre de rotation que celui qui affiche le paysage.

**Comment by fafling** [comment]
@FCare Est-ce que tu peux décommenter le test du registre de map offset MPOFR dans [sameVDP2RegRBG0](https://github.com/FCare/Kronos/blob/9c2fe61a183c301a06c3c03f884bdb6df4e023d0/yabause/src/core/video/opengl/core/src/vidogl.c#L4797) ?
C'est lui qui donne l'adresse de début du bitmap.

Il y a aussi une autre modif qui servirait à Quake dans la même fonction, voir https://github.com/FCare/Kronos/issues/461#issuecomment-754919043

**Comment by fafling** [comment]
Presque bon dans les 2 noyaux en WIP du 10/12/2021.

Il reste un problème en RBG CS off visible sur certaines portions du circuit du désert :
![image](https://user-images.githubusercontent.com/7624262/145658214-0ebcbd7d-dca9-4ef8-8cc0-449fca840164.png)

Le changement de priorité a l'air d'être fait une ligne plus tôt que le changement de graphisme entre le paysage et le volant. Du coup une ligne du paysage apparaît devant le tableau de bord au milieu de l'écran.

Ce problème est déjà présent en v2.2.0 publique.

Save state :
[Nissan_desert.zip](https://github.com/FCare/Kronos/files/7696159/Nissan_desert.zip)

**Comment by fafling** [comment]
La ligne incorrecte apparaît en RBG OpenGL dans les versions de Kronos qui implémentent le changement de priorité en cours d'affichage (ça va ça vient...). On la voit en v1.6.0 par exemple. Même en RBG CS on, le RBG était forcé en OpenGL dans Nissan jusqu'à récemment car le rendu des bitmaps était corrompu en CS (fixé le 24-25/09/2021).

Captures en integer scaling dans la dernière WIP en désactivant les sprites, CS d'abord, OpenGL ensuite :
![Nissan_desert_RBG_CS](https://user-images.githubusercontent.com/7624262/145675087-ac6d6dca-b0d3-458d-be96-89b022863ba7.png)
![Nissan_desert_RBG_OpenGL](https://user-images.githubusercontent.com/7624262/145675074-5896d1ea-9d26-49ce-bb0e-d5553f62d4c9.png)
Il n'y a pas de décalage de texture sur la partie supérieure entre les 2 noyaux, donc c'est le changement de priorité qui est pris en compte une ligne trop tôt en OpenGL.

**Comment by FCare** [comment]
Corrigé le 13/12/2021
