### ISSUE TITLE
[NOeL 3 - Not Digital] Artefact graphique après le start....

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#418]
Kronos  1.6.0

![noel](https://user-images.githubusercontent.com/12481242/51110874-57929d80-17fa-11e9-9f6d-a55dcbc75a8c.PNG)

**Comment by fafling** [comment]
Le problème venait du cycle pattern pour le NBG0.
Corrigé en WIP du 19/05/2021 par fe07ff6250489bd50081f7aced841c79395589b0
