### ISSUE TITLE
Crash on windows 10 with intel gpu HD 615 and 630

### ISSUE THREAD

**Issue by skelton** [FCare/Kronos#419]
Both GPU support openGL 4.5. When I start the emu, it just crash in both Retroarch core and standalone. Last working version was Kronos 1.2.0. I tried different intel drivers with no result. Quite weird because other cores run fine with RA in openGL. If you tell me how to make a log in Retroarch I can send a log to see what happens with this intel devices.

**Comment by barbudreadmon** [comment]
https://docs.libretro.com/guides/generating-retroarch-logs/

**Comment by skelton** [comment]
https://pastebin.com/hfv9twCP

Here is the log from Retroarch. No idea if it's useful or not,

**Comment by barbudreadmon** [comment]
There is no error message, so at the very least your hardware seems compatible and your setup doesn't seem messed up, i'll need more informations : 
- What's the iso format ?
- Is it happening with any game ?
- Is it happening instantly ?
- Did you try changing bios ?

**Comment by skelton** [comment]
Yeah. I tried with all games and BIOS (Bin cue format games that run with
mednafen saturn and yaba sanshiro 2.2.0). It happens inmediately and
retroarch Crash and the log ends. Using your kronos 1.2.0 standalone
everything worked, after that It stopped working, so no idea why. I have
the same retroarch setup on a pc with Nvidia gtx1080 and ganes work, so i
don't think IS a BIOS issue or an ISO problem. I would love to use kronos
in gpd win 2 (the device with this iGPU). My Guess driver IS faulty
somehow.....

**Comment by FCare** [comment]
Gpd win 2 device is using intel core m3. I do not have such hw so it is complicated to know what is crashing. Yaba is using opengles3 driver. Kronos is using opengl3.2 at least. Not the same drivers capability are used. I will setup a standalone kronos version with debug activated in order to get some traces. It looks like the core m3 driver might have some specificity...

**Comment by skelton** [comment]
Hi. Let me know if i can test build. Issue IS not exclusive for hd615 on
Core m3. It happens the same with hd630 that comes with modern Intel CPUs .
In fact, they share GPU drivers and they support OpenGL 4.5.

**Comment by BenjaminSiskoo** [comment]
Delete your bkram.bin (or backup it). Reset your kronos.ini (delete all the strings in the file and save it). Try again

**Comment by skelton** [comment]
I Will try this evening and see if It works.

**Comment by BenjaminSiskoo** [comment]
An old ini can be not working properly with a new release.

**Comment by skelton** [comment]
I did a fresh install. There wasn't a kronos in my folder when i tested. I
use different folder for different builds. Also IS not only with
standalone, but also with retroarch Core.

**Comment by BenjaminSiskoo** [comment]
Remove all the others kronos.ini and bkram.bin (yabause, yaba sanshiro, uoyabause or kronos). You need to have just one kronos.ini and one bkram.bin on your computer.

**Comment by skelton** [comment]
Well. I Will have to remove all. But i use yaba sanshiro and have it
already configured....

**Comment by BenjaminSiskoo** [comment]
Zip it if you want. And delete it. You can found the yabause/kronos path on C:\Users\your_name\AppData\Local\yabause. Check this folder and delete files inside the folder.

**Comment by skelton** [comment]
Ok. Will try this evening. But not sure that kronos Core on retroarch use
that route... Or does It?

**Comment by BenjaminSiskoo** [comment]
I'm not really sure about libretro.  But for stand alone release, this is the way to try. Kronos.ini is really sensitive between 2 releases.

**Comment by skelton** [comment]
Well. My main use was to use it under libretro. Anyway, i will delete
everything and Will try. Kronos 1.2.0 worked at least (slower than yaba but
worked)

**Comment by skelton** [comment]
Just tried again after a clean install of everything, and didn't work on
HD615 or Hd630. I used 1.6.0 standalone and kronos core in Retroarch.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BenjaminSiskoo** [comment]
Could you give me a mail. We have a very very WIP with some traces.

**Comment by skelton** [comment]
Sure,
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BenjaminSiskoo** [comment]
You can delete your mail if you want. I'm going to send you this tonight or tomorrow.

**Comment by skelton** [comment]
Ok. thanks

**Comment by BenjaminSiskoo** [comment]
Check your mail

**Comment by skelton** [comment]
It asks me for vcruntime140D.dll and ucrtbased.dll... I think I have all
vcredist installed, maybe I need something else?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BenjaminSiskoo** [comment]
Dlls added on the link I gave you.

**Comment by skelton** [comment]
Still doesn't work unfortunately. It just says application could not be
started (0xc00007b). It seems my computer is trolling me

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BenjaminSiskoo** [comment]
64 bits or 32 bits ?

**Comment by skelton** [comment]
w10 64 bits. I have all VC redist installed from 2010 to 2017 included.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BenjaminSiskoo** [comment]
O_O

Do you think it's possible to use Temaviewer and test it by myself. ? If yes, not today maybe tomorrow ?

**Comment by skelton** [comment]
I can try to install Teamviewer and try tomorrow evening or night. I have
never used Teamviewer but I can try. Could it be that package was corrupted
for some reason? I downloaded several times and showed no errors but just
in case.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by FCare** [comment]
Try this https://www.google.com/amp/s/wikiclic.com/0xc000007b/amp/

Do you have any trace in debugview?

**Comment by skelton** [comment]
it shows nothing, i am still running scanow command but no errors according
to windows. i will continue tomorrow evening since i have to go now.

**Comment by BenjaminSiskoo** [comment]
When you're ready, tell me, send me a mail.
About TeamViewer, download it.
Launch it
Start Only
Use it personnaly
Click on the button accept
On the next screen, on the left, you give me your id and your password.

**Comment by barbudreadmon** [comment]
@skelton i have a feeling that maybe there is some buggy GL 4.X context here, do you mind testing again the libretro core to see if it works ? I applied some fix that will force GL 3.3 context if gpu tesselation is not set.

**Comment by skelton** [comment]
Hi. Sorry for the delay. I just testes with updated retroarch to 1.7.6 and
i updated kronos core but it hangs retroarch when loading a Game. Log is
the same as in the one i sent you so i don't know. Do yo have a standalone
with that fix i can test? Because for some reason debug standalone doesn't
boot on my pc.

**Comment by barbudreadmon** [comment]
@skelton a fix was commited for shader issues affecting only some devices a few minutes ago, maybe that would be worth giving another try when the new version will be on the libretro buildbot (in a few hours ? it should be the 7c799f72991c5113691b3d9396af3865b256d1b8 version)

**Comment by skelton** [comment]
Just tried but didn't work. I don't send a log because is the same as
previous logs. Maybe it's an intel driver issue but yaba sanshiro works
without issues.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by barbudreadmon** [comment]
Could you test with the following custom build of the core and post the logs ?

[kronos_libretro.zip](https://github.com/FCare/Kronos/files/2999931/kronos_libretro.zip)

**Comment by skelton** [comment]
Didn't work. Here is its the log:

https://pastebin.com/Ti32n2LM

**Comment by barbudreadmon** [comment]
Interesting, apparently it's crashing even before the GL renderer is starting (all gl debug output should be enabled in this custom core, but there is none of them in your logs), so that might not be related to your gpu.
I'll come up with another custom core to see when it's crashing exactly.

**Comment by skelton** [comment]
I don't know, it's strange because I have no problem with other cores in
openGL, even mednafen saturn runs ok. SO no idea if it's a driver issue
(iGPUs drivers are not very good on windows) or maybe something else.
Thanks for checking.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by barbudreadmon** [comment]
Here is the new one, actually i think i might have messed up with the first one, some GL message weren't showing : 
[kronos_libretro.zip](https://github.com/FCare/Kronos/files/3000674/kronos_libretro.zip)

**Comment by skelton** [comment]
New log:

https://pastebin.com/HkKhvMei

Now it shows something different, but it's weird, retroarch hangs and I
have to force close it.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by barbudreadmon** [comment]
That's weird, there should be stuff between every `YabauseEmulate frame X begin` and `YabauseEmulate frame X end` (@FCare i added those msg at the beginning and end of the YabauseEmulate function), let's eliminate the possibility of a threading issue with the following custom core : 

[kronos_libretro.zip](https://github.com/FCare/Kronos/files/3000712/kronos_libretro.zip)

**Comment by skelton** [comment]
I tried a different game this time (my game is fine since it works on my
main PC with nvidia card)

https://pastebin.com/PrfpJvnC

Same results unfortunately. I don't think I can test more today,

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by barbudreadmon** [comment]
@FCare for the sake of comparison, this is the output when running the same core on my windows : https://pastebin.com/WqN48QXm

What i noticed is that every GL CALLBACK messages are missing from @skelton 's logs, including the first ones : 
```
...
[libretro INFO] YglInit(2048,1024,8);
[libretro INFO] GL CALLBACK:  type = 0x8251, severity = 0x826b, message = Buffer detailed info: Buffer object 65 (bound to GL_PIXEL_UNPACK_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) will use SYSTEM HEAP memory as the source for buffer object operations.
[libretro INFO] GL CALLBACK:  type = 0x8251, severity = 0x826b, message = Buffer detailed info: Buffer object 65 (bound to GL_PIXEL_UNPACK_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) has been mapped WRITE_ONLY in SYSTEM HEAP memory (fast).
[libretro INFO] GL CALLBACK:  type = 0x8251, severity = 0x826b, message = Buffer detailed info: Buffer object 66 (bound to GL_PIXEL_UNPACK_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) will use SYSTEM HEAP memory as the source for buffer object operations.
[libretro INFO] GL CALLBACK:  type = 0x8251, severity = 0x826b, message = Buffer detailed info: Buffer object 66 (bound to GL_PIXEL_UNPACK_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) has been mapped WRITE_ONLY in SYSTEM HEAP memory (fast).
[libretro INFO] GL CALLBACK:  type = 0x8251, severity = 0x826b, message = Buffer detailed info: Buffer object 67 (bound to GL_PIXEL_UNPACK_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) will use SYSTEM HEAP memory as the source for buffer object operations.
[libretro INFO] GL CALLBACK:  type = 0x8251, severity = 0x826b, message = Buffer detailed info: Buffer object 67 (bound to GL_PIXEL_UNPACK_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) has been mapped WRITE_ONLY in SYSTEM HEAP memory (fast).
[libretro INFO] PG_VDP2_NORMAL
...
```

Any idea what it could be about ? Judging from his logs, it seems RA is providing the right GL context

**Comment by FCare** [comment]
Based on documentation:

        DEBUG_SEVERITY_HIGH                              0x9146
        DEBUG_SEVERITY_MEDIUM                            0x9147
        DEBUG_SEVERITY_LOW                               0x9148
        DEBUG_SEVERITY_NOTIFICATION                      0x826B 

Those warning are just Debug messages, nothing related to any error.

**Comment by barbudreadmon** [comment]
@skelton i have some news about this : i have a dual boot computer with an intel HD 405, i never bothered trying kronos+windows on it (i always run the machine on linux, kronos is working fine on it) but i did for the first time yesterday, and i got exactly the same issue, so the issue is actually affecting only windows driver for specific intel gpu. 

Intel developpers definitely messed up somewhere, considering the open-source drivers on linux are working for the same machine.

The good news about this : now that i can reproduce the issue on my side, i might be able to figure out what code is causing the issue with those drivers, which might lead to a workaround.

**Comment by skelton** [comment]
Thanks . Intel hd405 IS cherrytrail and hace worse OpenGL support (until
4.1 or 4.2 i think) but probably drivers bug IS the same. It's no surprise
that mesa drivers in Linux are better, i suspected It would be a driver
issue. Thanks for taking a look.

**Comment by eadmaster** [comment]
some issue here on my Intel HD Graphics 610 (on the Intel Pentium G4560)

**Comment by barbudreadmon** [comment]
@skelton @eadmaster good news, we might have figured out the deadlock issue on intel gpus

**Comment by patrici0** [comment]
Hi! I know this is an old issue, but it is not clear if it was fixed already. I have the same problem but, instead of an intel gpu, I'm using a very old NVIDIA 9600 gt video card, which crashes retroarch right after attempting to launch any game using kronos.

If any kronos libretro core devs here are willing to review this, I can share logs and am willing to try stuff out.

On the other hand, the Yaba Sanshiro core does load games, but that core doesn't work very well in every other aspect of running them.

I'm using the latest retroarch version and up-to-date cores on Windows 10 Pro 64bit.

**Comment by barbudreadmon** [comment]
>a very old NVIDIA 9600 gt video card, which crashes retroarch right after attempting to launch any game using kronos.

It's not "crashing", it's closing properly because your gpu doesn't meet the minimum OpenGL requirements (4.2), either buy a new gpu or use another saturn emulator.
