### ISSUE TITLE
Problème de Bios

### ISSUE THREAD

**Issue by Blackninja87** [FCare/Kronos#420]
Bonjour,
Pourquoi je n'arrive pas a garder le bios en Fr.
Je m'explique, je lance Kronos, je lance le bios, je vais dans les options du bios
afin d'avoir accès aux options en FR.
Mais quand je relance Kronos, il a perdu que j'avais mis les options en FR.
Donc pour les jeux avec du Fr, je n'ai pas accès aux FR, le jeux est donc en US.
Quelqu'un à la solution à ce problème ?. 
Merci pas avance !!!

**Comment by fafling** [comment]
Je confirme que le choix de la langue dans le bios n'est pas sauvegardé par Kronos. Pour reproduire :
- Maintenir L+R au démarrage de l'émulation pour accéder à l'écran Memory manager du bios.
- Aller dans l'écran System settings puis Language.
- Sélectionner le français et faire Sortie.
- Maintenir L+R et redémarrer l'émulation.
L'écran Memory manager est de nouveau en anglais dans Kronos, alors qu'il devrait être en français comme sur une vraie console après les manips équivalentes.

Il y a d'autres problèmes dans le bios :

- Aller dans l'écran Memory manager du bios à partir du lecteur CD avec un CD présent, puis faire Exit provoque une erreur :

Error: Master SH2 invalid opcode

R0 =  0000002D	R12 =  00000003
R1 =  00000000	R13 =  00000001
R2 =  00000006	R14 =  00000000
R3 =  0602B93C	R15 =  0601FFB0
R4 =  00000001	SR =   00000100
R5 =  00000001	GBR =  06020000
R6 =  00000800	VBR =  06000000
R7 =  06000248	MACH = 00000000
R8 =  06028520	MACL = 0000004A
R9 =  00200000	PR =   060284E8
R10 = 00000001	PC =   00200000
R11 = FFFFFFFF

- La lecture séquentielle des pistes audio d'un CD n'incrémente pas le numéro de piste (facilement reproductible avec Nights qui commence par plusieurs petites pistes) dans le bandeau bleu à chaque début de piste, n'affiche pas temporairement le numéro de piste en vert au milieu de l'écran, et le temps écoulé ne revient pas à 0 mais affiche le temps depuis le debut de la 1ère piste. Même comportement à l'exception du numéro de piste affiché en vert si on utilise les boutons Skip après avoir lancé la lecture. Par contre si on utilise les boutons Skip à l'arrêt, le numéro de piste et sa durée sont affichée correctement, mais dès qu'on lance la lecture, l'affichage dans le bandeau bleu redevient incorrect.

**Comment by barbudreadmon** [comment]
Pour info, le choix de la langue est en fait sauvegardé dans une zone de mémoire de 4 octet sur le smpc, distincte de la bkram, raison pour laquelle la donnée n'était pas conservée.
Je n'ai pas trouvé d'information sur ce que stockait cette zone de mémoire hormis la langue, donc plutôt que de créer un nouveau fichier de sauvegarde pour cette zone de mémoire, j'ai opté pour forcer la langue à l'initialisation via un nouveau réglage.

**Comment by fafling** [comment]
La structure des 4 octets est décrite par ce document en p. 27, tableau de la macro PER_GS_SM : [https://segaretro.org/File:ST-162-R1-092994.pdf](https://segaretro.org/File:ST-162-R1-092994.pdf)

Les constantes des masques de bits sont définies dans le fichier SEGA_PER.H de la SBL :
- La langue est codée sur les bits 0 à 3.
- L'activation des effets sonores sur le bit 8.
- Stereo/mono sur le bit 9.
- L'activation des labels de boutons sur le bit 10.

La commande INTBACK du SMPC permet de lire ces 4 octets et la commande SETSMEM de les écrire.
Certains jeux japonais mettent à jour ces 4 octets car le bios passe en langue japonaise après leur utilisation.

**Comment by fafling** [comment]
Des exemples de jeux modifiant la langue du bios en japonais :
- Densha de go! ex
- Girl doll toy
- J. League Go Go Goal!
- Japan Super Bass Classic '96 (ne permet pas le reset par A+B+C+start)
- Virtual kyoutei

Dans tous les cas, le changement de la langue du bios est fait au démarrage du jeu. Un reset avec A+B+C+start dès que le jeu le permet affiche le bios avec les textes en japonais, alors qu'il sont en anglais au démarrage de Kronos. Testé avec la v2.1.2 publique.
En WIP v2.1.4 du 16/12/2020, Kronos affiche le bios dans la langue sélectionnée par le paramètre "bios language" au lieu de l'afficher en japonais après un reset dans ces jeux.

**Comment by barbudreadmon** [comment]
Apparemment mon réglage s'en fout, la langue reste celle réglée dans les options quand je fais A+B+C+start. On ne dirait pas que çà pose soucis pour autant.

Sinon il y a des bugs connus avec ces jeux ? Je remarque qu'ils utilisent les commandes CDON et CDOFF du smpc, qui ne sont pas implémentées à l'heure actuelle dans kronos.

**Comment by BenjaminSiskoo** [comment]
Densha Da go affiche ca : 

![denshadago](https://user-images.githubusercontent.com/12481242/81501166-17044080-92d7-11ea-963d-a16c5e6f94bb.PNG)

Girl Doll Toy semble jouable.

En CS (pas testé en opengl) a un problème avec la couche NBG0 en plus des ralentissements.

![virtualkyoutei](https://user-images.githubusercontent.com/12481242/81501200-3dc27700-92d7-11ea-89d0-44d39a086202.PNG)

**Comment by barbudreadmon** [comment]
Densha Da go, sur l'écran que tu montres (je crois que c'est un écran qui demande si t'utilises une manette classique ou https://segaretro.org/Densha_de_Go!_Controller), il suffit d'appuyer sur start

**Comment by BenjaminSiskoo** [comment]
ok fail j'ai pas pensé à appuyer sur Start, le jeu bloque in game : 

![denshadago](https://user-images.githubusercontent.com/12481242/81501531-2c7a6a00-92d9-11ea-9461-a00cf06dc411.PNG)

Pas de message d'erreur dans debugview

**Comment by Blackninja87** [comment]
Merci beaucoup à tous pour vos réponses.
Donc en gros il n'y a pas de solution pour garder la Fr au redémarrage.

**Comment by barbudreadmon** [comment]
@Blackninja87 pour l'instant non car on n'enregistre pas la zone de mémoire concernée, par contre il est possible de forcer la langue via les réglages (sauf que je crois que l'option n'a pas encore été rendu visible dans les réglages de la version standalone ? au pire tu peux utiliser la version libretro)

**Comment by fafling** [comment]
Workaround pour changer la langue du bios avec le paramètre "bios language" mise en place pour #869 .
