### ISSUE TITLE
[Heart Of Darkness] Problème de mémoire...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#421]
Le prototype HOD a un problème de mémoire. Sur mednaffen, il passe avec cart cs1ram16 (dixit VBT).

**Comment by fafling** [comment]
Le jeu fonctionnait dans Kronos v1.5.0 en sélectionnant la RAM de sauvegarde 32 Mbit dans les paramètres (même sans définir de chemin pour le fichier). Le jeu met alors 45-50 secondes à se charger sur mon PC.

A partir de la v1.6.0, ça ne marche plus, et je pense que ça vient d'une correction des capacités des cartouches de sauvegarde qui les divise par 2 (07d034a et c3be431).

Jusqu'à ce fix, la cartouche de sauvegarde 32 Mbit faisait en fait 8 Mo. Le jeu doit seulement contrôler la taille de la cartouche présente, pas son type.

**Comment by barbudreadmon** [comment]
Ces 2 commits retirent le byte de mirrorring des BUP afin d'être compatible avec les BUP mednafen (qui font çà également), ce byte ne sert en théorie à rien, la taille de cartouche détecté par la saturn devrait d'ailleurs être la même (on retire les bytes du fichier enregistré, mais on les insère au niveau du bus), plusieurs choses me viennent à l'esprit : 
- la BUP a-t-elle été effacée avant chaque tests ? ces 2 commits changent le format de celle-ci
- le problème se produit avec tout les formats de BUP ?

2 théories : 
- la BUP 32M est peut-être une exception qui fait usage du byte de mirroring ? NB : je crois que c'est un format non-officiel jamais produit par Sega
- le jeu est peut-être une exception qui fait usage du byte de mirrorring ?

Edit : je dis byte de mirrorring, mais ce n'est peut-être pas le bon terme, quoi qu'il en soit c'est un 0 inséré entre chaque byte, qu'on ne stocke plus dans les fichiers sauvegardés à partir de ces commits

**Comment by BenjaminSiskoo** [comment]
Corrigé le 15/01/2020
