### ISSUE TITLE
[Mystaria - The Realms Of Lore] Priorité entre VDP1 et NBG1 pendant l'intro

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#422]
Pendant la séquence d'intro après avoir sélectionné New game, certains polygones du VDP1 sont affichés devant le plan NBG1 qui affiche du texte.
Les polygones sont en RGB, il utilisent donc le registre de priorité 0 des sprites qui a la valeur 3. La priorité du NBG1 est à 7. Les polygones devraient donc être derrière lui.
![capture](https://user-images.githubusercontent.com/7624262/52185104-12232800-281c-11e9-8658-5bd78537e870.JPG)
![capture2](https://user-images.githubusercontent.com/7624262/52185106-14858200-281c-11e9-9a46-a2fb0ea72f88.JPG)
![capture3](https://user-images.githubusercontent.com/7624262/52185107-16e7dc00-281c-11e9-9758-d44f572cb410.JPG)

**Comment by fafling** [comment]
Le problème reste présent si on désactive et réactive l'une des 2 couches concernées.

**Comment by FCare** [comment]
Fixé sur la branche rework
