### ISSUE TITLE
[Vampire Savior - The Lord Of Vampire] Plantage de Kronos (MH2 Invalide opcode)...

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#423]
Plantage de Kronos v1.5 et 1.6 à l'écran Now loading qui suit le logo Capcom.

**Comment by BenjaminSiskoo** [comment]
Donne nous ta config, mais je suspecte un soucis d'iso !!!

**Comment by barbudreadmon** [comment]
Sur "Vampire Savior (Japan)" du set redump, je suis également incapable de passer le "Now loading", j'ai le droit à une série de "Master SH2 invalid opcode" dans les logs, j'ai également testé différentes config de bios et cart addon, mais j'ai toujours la même chose.

**Comment by fafling** [comment]
Je teste avec un CD d'origine qui marche sans problème sur console.
Kronos est configuré avec la cartouche 32 Mbit Dram. J'utilise comme bios un fichier saturn_bios.bin (je l'ai depuis tellement longtemps que je ne me souviens plus où je l'ai récupéré).
Yaba Sanshiro v2.3.1 bloque aussi au Now loading sur ce jeu.

**Comment by BenjaminSiskoo** [comment]
Effectivement j'ai le même problème j'ai confondu avec un autre jeu.

**Comment by fafling** [comment]
Toujours présent en WIP du 20/12 dans les 2 noyaux.

**Comment by fafling** [comment]
Fixé en WIP du 12/08 dans les 2 noyaux.

**Comment by fafling** [comment]
De nouveau, un écran noir dans Kronos après le "Now loading" dans la dernière WIP et en version publique v2.3.1, dans les 2 noyaux.

Le plantage a un comportement variable, j'ai eu 3 cas de figures :

- L'interface de Kronos n'est pas bloquée, le compteur de fps du VDP1 tombe à 0, mais pas celui du VDP2. Pas d'invalid opcode dans DebugView.

- L'interface de Kronos n'est pas bloquée, ni les compteurs de fps. Dans ce cas, DebugView affiche un invalid opcode au moment de l'écran noir :

Error: Master SH2 invalid opcode

R0 =  00000108 R12 =  FFFFFFFF
R1 =  06000348 R13 =  0604A936
R2 =  FFFFFFFC R14 =  00000000
R3 =  06000900 R15 =  0600894C
R4 =  FFFFFFFC SR =   000000D0
R5 =  25FE00A0 GBR =  00000000
R6 =  060A5F08 VBR =  06000000
R7 =  00000000 MACH = 00000000
R8 =  00000000 MACL = 00000000
R9 =  00000000 PR =   06000928
R10 = 00000000 PC =   060A5F08
R11 = 00000000

- L'interface de Kronos est bloquée et DebugView se bloque tant qu'on ne kille pas Kronos. DebugView affiche ensuite des invalid opcode en cascade, dont le 1er est :

Error: Master SH2 invalid opcode

R0 =  000000F0 R12 =  060B9AEC
R1 =  FFFFFF0F R13 =  00000001
R2 =  000000F0 R14 =  00000000
R3 =  00000101 R15 =  060085F0
R4 =  0000012C SR =   000000F0
R5 =  0600087C GBR =  00000000
R6 =  00000001 VBR =  06000000
R7 =  20200000 MACH = 00000000
R8 =  00000000 MACL = 00000000
R9 =  00000000 PR =   06059C66
R10 = 00000000 PC =   06059C6A
R11 = 00000000

Le jeu ne démarre plus depuis la WIP du 07/09/2021, la dernière WIP dans laquelle il fonctionnait est celle du 30/08/2021.

Rien vu de spécial dans Mednafen au moment du plantage.

Testé avec le CD d'origine et l'ISO redump.

**Comment by FCare** [comment]
2.1.5 : OK
2.2.0 : FAIL (erreurs SH2 en boucle)
2.3.1: comportement reporté

**Comment by FCare** [comment]
Due to patch 8b731e6cc6b0dfeb335a393a7ba5b593df84a33d

**Comment by BenjaminSiskoo** [comment]
kronos20231118_e8b6c1c

![image](https://github.com/FCare/Kronos/assets/12481242/2b9c044a-bc38-49c3-85c1-3af74380d090)

**Comment by BenjaminSiskoo** [comment]
avec la wip du kronos20231122_7fa6739

On passe d'une erreur de Master SH2 à Slave SH2

![image](https://github.com/FCare/Kronos/assets/12481242/2d180df8-d3c7-4c67-803d-59d30a32ff1e)

**Comment by BenjaminSiskoo** [comment]
kronos20231129_ea0eace

![image](https://github.com/FCare/Kronos/assets/12481242/142f42e1-750d-48a8-b5f7-08e909bfe24a)

En passant le slave sh2 error, on va in game, mais les FPS sont entre 45et 50 sur 60.

![image](https://github.com/FCare/Kronos/assets/12481242/8a835013-594b-4de2-b211-9652273c9b0a)

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

Les sprites des persos ne sont pas affichés

![image](https://github.com/FCare/Kronos/assets/12481242/8cfbe14d-c1e0-4295-91a3-e0f5826d6be4)

**Comment by fafling** [comment]
Chez moi le jeu ne va au-delà du now loading qu'à partir de la WIP du 14/12 (70964a7).
Les sprites sont déjà manquants à ce moment-là.
L'absence des sprites est visible dès la présentation qui suit le now loading.
Les commandes de dessin des sprites sont bien présentes dans la liste du VDP1.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.6.1

![image](https://github.com/FCare/Kronos/assets/12481242/c61bcfe0-cb50-4200-b544-c2902006bf3c)
