### ISSUE TITLE
[Tomb Raider] Transparence manquante sur le menu pause...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#427]
![tombraiderpause](https://user-images.githubusercontent.com/12481242/53087246-f51e7280-3506-11e9-9f17-ff1dbf17001d.PNG)

**Comment by FCare** [comment]
readframebuffer function is not working

**Comment by BenjaminSiskoo** [comment]
Corrigé le 25/04/2019 après des années sans que ce soit affiché :^)

**Comment by fafling** [comment]
Il y a des problèmes résiduels :

- Il y a un clignotement quand on sort de la pause : le jeu annule progressivement le color offset et fait rétrécir les objets du menu avant de recommencer à dessiner le jeu normalement mais entre les 2, on voit brièvement au moins une frame assombrie avec parfois des corruptions en haut (on ne voit rien de particulier dans les écrans debug, le VDP1 a repris le dessin du jeu et le VDP2 n'affiche plus rien) :

![Capture_Tomb_raider_fin_pause_20190426](https://user-images.githubusercontent.com/7624262/56818194-68b26800-6847-11e9-9eeb-573ea3b49cf4.PNG)

- Il y a le même problème que dans Bug too, quand l'option OpenGL size est réglée sur 2x ou plus, la partie inférieure gauche du framebuffer est zoomée par l'émulateur en tant que texture copiée à partir du framebuffer :

![Capture_tomb_raider_pause_opengl_2x](https://user-images.githubusercontent.com/7624262/56818486-ff7f2480-6847-11e9-8eda-1872802f125b.PNG)

Un save state pour aller plus rapidement dans le jeu :

[tomb_raider_niv1.zip](https://github.com/FCare/Kronos/files/3121918/tomb_raider_niv1.zip)

**Comment by fafling** [comment]
Le problème d'OpenGL size est réglé en WIP du 07/05. Je crée un nouveau bug #480 pour le clignotement.
