### ISSUE TITLE
[HatTrick Hero S] La MSB shadow écrase le VDP1 en extui-align

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#428]
Le menu pause utilise le mode "MSB on" du VDP1. Dans ce mode, seul le bit le plus significatif des pixels du framebuffer doit être modifié, les autres bits sont inchangés. Ici, on devrait voir les joueurs assombris sous le menu. Au lieu de ça, ils disparaissent.

![capture](https://user-images.githubusercontent.com/7624262/53212653-1f2a7e80-3646-11e9-9f23-3c61864a100b.JPG)

![capture2](https://user-images.githubusercontent.com/7624262/53212659-2487c900-3646-11e9-9eaa-9544053d9101.JPG)

**Comment by barbudreadmon** [comment]
Salut, pour info, depuis quelques semaines @FCare ré-écrit le renderer GL "from scratch", donc ne t'étonnes pas si tu as peu de retour par rapport à tes rapports. En tout cas merci pour ceux-ci car ils sont très précis !

**Comment by FCare** [comment]
En effet, tes bugs sont vraiment bien documentés :-)

Pour venir de reimplementer le shadow MSB:
C'est le VDP1 qui decide de la zone MSB shadow en definissant le bit "MSB On" dans la commande VDP1.
Dans le framebuffer du VDP1, tous les pixels qui n'ont pas une valeur nulle sur les 15 premiers bits, doivent diviser la brightness par deux (14.1 du doc VDP2). Ca revient a appliquer un alpha de 0.5, ou a decaler tous les bits d'un vers la droite.
Dans les scroll screens, le brightness est divisé par deux quand la priorité du scroll screen est un de moins que la priorité du sprite "MSB On", si le framebuffer VDP1 ne comporte que des zeros sur les 15 premiers bits (le VDP1 est transparent dans ce cas la).
Ca c'est la theorie, apres il y a les bugs d'implementation :-)

Si on venait a ne passer que le MSB a 0, ca ne diviserait pas le brightness par deux. Ca ne changerait pas, par exemple les zones deja sombre qui pourraient avoir un MSB deja nul.

Il y a effectivement un bug dans cet ecran. Il faudra que je teste avec la branche rework.

**Comment by fafling** [comment]
Eh bien merci pour votre travail sur l'émulateur, Kronos est prometteur et je le trouve très utile pour comprendre le fonctionnement des jeux.

Pour info, je pars en voyage demain et je n'aurai pas d'accès internet pendant 15 jours.

Pour le mode "MSB on", le VDP1 ne fait rien d'autre que passer le MSB à 1 (et non à 0) sur les pixels du framebuffer où il devrait dessiner les zones non transparente de la texture.

Il est aussi possible de faire écrire par le VDP1 des pixels en mode palette avec le MSB à 1 au moyen de la color bank, dans le but de réduire la luminosité d'une texture entière.

C'est le VDP2 qui se charge de diviser la luminosité par 2 sur ces pixels, après avoir converti les différents plans en RGB, calculé les priorités et traité les semi-transparences. Le VDP2 effectue alors le décalage de bit dont tu parles sur chaque canal RGB avec la règle que tu as décrite.

Cet effet n'est donc pas cumulatif puisque le VDP2 ne le calcule qu'une seule fois par pixel après que le VDP1 a entièrement rendu le framebuffer : écrire plusieurs fois sur un même pixel avec le VDP1 en mode "MSB on" ne rendra pas ce pixel plus sombre qu'une demi luminosité.

**Comment by fafling** [comment]
Sur la WIP du 17/03/2019, les sprites ne sont plus écrasés par le mode "MSB on", mais ils ne sont pas assombris.
![Capture](https://user-images.githubusercontent.com/7624262/54498998-941f6a00-490d-11e9-89d6-3e77b7d85840.JPG)

**Comment by fafling** [comment]
Depuis la WIP du 04/07, les sprites sont de nouveau écrasés par le mode "MSB on" en noyau OpenGL :
![Capture_hattrick_hero_S_rasterizer](https://user-images.githubusercontent.com/7624262/63629862-73beae80-c615-11e9-9d60-f6d32f23bf62.PNG)

Dans  la dernière WIP du 23/08, en noyau compute shader, le mode "MSB on" n'écrase pas les sprites, mais la MSB shadow n'est pas rendue :
![Capture_hattrick_hero_20190823](https://user-images.githubusercontent.com/7624262/63629935-17a85a00-c616-11e9-9be6-56aa0f0aa12c.PNG)

**Comment by fafling** [comment]
En WIP du 02/09, le noyau compute shader se comporte comme le noyau OpenGL : l'ombre est rendue, mais elle écrase les sprites.

**Comment by fafling** [comment]
Fixé en OpenGL dans la WIP accurate_vdp1 du 24/09.

**Comment by fafling** [comment]
Fixé dans les 2 noyaux en WIP extui-align du 19/11.
