### ISSUE TITLE
OpenGLES Support

### ISSUE THREAD

**Issue by blisstik** [FCare/Kronos#429]
Someone notified me in Libretro Discord that you were rewriting the renderer from scratch. I was wondering if the existing `HAVE_GLES=1` will continue to be supported after the rewrite?

**Comment by FCare** [comment]
Hi,

I am not sure yet. Maybe some of the new pipeline function will not be
supported in GLES.

Yaba sanshiro is already focusing on GLES, I do not really see in which
case it can be useful to support GLES. But the question is still open...

On which target are you planning to use libretro kronos whith GLES3 only?

**Comment by blisstik** [comment]
The target device is Odroid N2 which the Mali FB-dev driver supports up to OpenGLES 3.2

**Comment by blisstik** [comment]
I'd like to add the environment is aarch64

**Comment by FCare** [comment]
Ah, N2 is planned :-) I have a XU4.

Ok then maybe I will try to support when I will be able to get one of those
boards...

**Comment by blisstik** [comment]
Yeah I don't think XU4 is supported but that's awesome to hear. So we can have this by end of the month? :) JK

**Comment by FCare** [comment]
No, not end of the month... I am just working almost alone on this
project... Maybe end of the year...

**Comment by blisstik** [comment]
**I was JK lol. I know it takes time**
