### ISSUE TITLE
[ST-V] The implementation might be incomplete

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#440]
Tested in the libretro port but i don't see a reason why standalone would be any different : 
- No input working at all (including service/test/coin/start), the arcade cabinet isn't using any weird controls though
- There is some weird behavior where i get additional credits every time i restart the game.

Latest version of the mame romset was used (vfremix)

**Comment by barbudreadmon** [comment]
Tecmo World Cup '98 might be suffering from a related issue, in this case the game freeze with a black screen, i think the issue is somehow related to the lack of "custom init mecanism", see how each game is initialized differently at https://github.com/mamedev/mame/blob/c4b8aa3a569c9502a7c5be78afe13328d45f5f36/src/mame/drivers/stv.cpp#L477
I think kronos doesn't implement such a mecanism atm.
I'll try to see if i can manage to backport this stuff from mame.

**Comment by barbudreadmon** [comment]
Actually the custom init mecanism is already implemented (only one game is using it atm though : `sanjeon`), comparing mame implementation to kronos implementation, i noticed a few other things : 
- We might be missing support for alternative "i/o boards"
- We might be missing support for alternative "machines" (current code assume every game use the encryption/decryption of the 315-5881 chip, but that might be wrong)
- We might be missing support for the pre-configured eeprom present in the roms (`stvbios.zip` contains `stvbios.nv` which is the default for most game, some other game use alternative `.nv` files)

I'll try to see if i can figure out how to implement this stuff in kronos

**Comment by BenjaminSiskoo** [comment]
It will be nice :)

**Comment by FCare** [comment]
There is one or two games with a different nv file since the cabinet
configuration is different. So the nv file mechanism shall be already
partly implemented


Le dim. 3 mars 2019 à 13:26, barbudreadmon <notifications@github.com> a
écrit :
