### ISSUE TITLE
[Rayman] Les boutons ne répondent pas

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#454]
Avec le CD de Rayman US et bios jap v1.01 ou le bios émulé, le jeu ne répond à aucun bouton : impossible de démarrer le jeu avec start, ou de faire un reset avec A+B+C+ start.
De plus, dans les niveau de demo, quand Rayman ramasse un ting (les boules bleues), l'affichage des sprites clignote. C'est peut-être du aux particules qui devraient être affichées à ce moment-là. Elles n'apparaissent pas dans les commandes du VDP1. Peut-être qu'elles sont dessinées dans le framebuffer directement par les SH2 ou le SCU.
Mêmes problèmes dans Kronos v1.6.0 et WIP du 17/03/2019.
Par contre, dans Yabause v0.9.14, le jeu répond aux boutons. Il n'y a pas de corruption quand on ramasse les tings, mais les particules ne sont pas affichées.

**Comment by fafling** [comment]
Suite au commit 113b2ae , les particules s'affichent sans faire clignoter les sprites, mais par contre les couleurs sont temporairement assombries pour les NBG ou corrompues et partiellement transparentes pour les sprites.
![Capture_rayman_20190606](https://user-images.githubusercontent.com/7624262/58995140-48d17500-87f3-11e9-9c43-a16f521881ab.PNG)
![Capture_rayman_20190606_demo5](https://user-images.githubusercontent.com/7624262/58995790-eb8af300-87f5-11e9-8077-818c9ca2b085.PNG)

**Comment by fafling** [comment]
En WIP du 01/09, le problème d'affichage des particules n'est plus présent qu'en noyau OpenGL.

**Comment by fafling** [comment]
Le jeu ne répond plus au boutons à partir de Kronos v1.3.0.

**Comment by fafling** [comment]
L'affichage des particules est fixé en OpenGL en WIP accurate_vdp1 du 25/09.
Les contrôles ne répondent toujours pas en WIP accurate_vdp1 du 13/10.

**Comment by fafling** [comment]
En WIP extui-align du 24/11, l'affichage des particules est correct dans les 2 noyaux.
Les contrôles ne répondent toujours pas.

**Comment by FCare** [comment]
Read Smpc Byte 63
Write Smpc Byte @0x63 = 0x1
Write Smpc Byte @0x1 = 0x0
Write Smpc Byte @0x3 = 0x8
Write Smpc Byte @0x5 = 0xf0
Write Smpc Byte @0x1f = 0x10
Read Smpc Byte 21
Read Smpc Byte 21
Write Smpc Byte @0x1 = 0x40
COMREG 10
IntBack 40 8
Write Smpc Byte @0x79 = 0x0
Write Smpc Byte @0x7b = 0x0
Write Smpc Byte @0x7f = 0x0
Write Smpc Byte @0x7d = 0x0

**Comment by FCare** [comment]
Le IREG[0] est ecrit a nouveau a 0x40 alors que le intback n'a pas ete executé => Pb de timing

**Comment by FCare** [comment]
Fixé le 12/01/2020

**Comment by fafling** [comment]
Les contrôles marchent dans les 2 noyaux 👍 
@FCare Je ne sais pas si on est dans ce cas, mais les jeux qui n'ont besoin que d'une passe de lecture d'OREG peuvent le faire sans utiliser l'interrupt généré par le SMPC, ils peuvent masquer cet interrupt et font la lecture des OREG au vblank suivant l'écriture de l'IREG pour demander l'interrupt back (p. 16 et 56 du mode d'emploi du SMPC).

**Comment by fafling** [comment]
Le jeu ne répond de nouveau plus aux commandes dans la dernière WIP.
Le problème n'existe pas en v2.5.0 publique.
Difficile de dire depuis quand car il s'est mis à freezer sur la 1ère FMV en WIP du 15/02/2023 (0eee96c). Il répondait aux contrôles dans la WIP précédente (747ad60).
Le jeu ne freeze plus depuis la WIP du 27/10/2023 (67b4a57), mais ne réponde plus aux commandes.

Testé avec le CD US.

**Comment by BenjaminSiskoo** [comment]
kronos20231211_46c12d6

Corrigé
