### ISSUE TITLE
[World heroes perfect] Les boutons ne répondent pas sur les manettes USB

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#455]
Avec le CD d'origine et bios jap v1.01 ou le bios émulé, le jeu ne répond à aucun bouton : impossible de démarrer le jeu, ou de faire un reset avec A+B+C+ start.
Mêmes problèmes dans Kronos v1.6.0 et WIP du 17/03/2019.
Par contre, dans Kronos v1.5.0, le jeu répond aux boutons, mais les sprites ne s'affichent pas.

**Comment by BenjaminSiskoo** [comment]
Il y a entre 5 et 10 jeux à  ma connaissance avec les problèmes de boutons.

**Comment by fafling** [comment]
Toujours présent en WIP du 12/01/2020. Pas de message particulier dans debugView.

**Comment by fafling** [comment]
Même comportement que X-Japan #518 : le jeu ne répond pas si les boutons sont mappés sur une manette USB, par contre il répond s'ils sont mappés sur le clavier.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.5.0

![image](https://user-images.githubusercontent.com/12481242/217036115-85ce136d-a7e4-4ced-bf90-f4bc751ba520.png)

**Comment by BenjaminSiskoo** [comment]
kronos20231206_3006f2d 

Corrigé
