### ISSUE TITLE
[Power drift] Problèmes sur sprites et RBG0

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#456]
Avec le CD d'origine et bios jap v1.01 ou le bios émulé :
- Les sprites ne s'affichent que si on désactive et réactive le RBG0. Problème présent dans Kronos v1.50, v1.6.0 et WIP du 17/03/2019. Yabause v0.9.14 affiche les sprites sans avoir besoin de cette manip.
- Le RBG0 est affiché avec une couleur uniforme qui semble être celle affichée normalement en haut de l'écran. Problème présent dans Yabause v0.9.14, v1.6.0 et WIP du 17/03/2019. Kronos v1.50 affiche le RBG0 correctement.
- Dans les virages, la rotation des sprites est manquante. Problème présent dans Kronos v1.50, v1.6.0 et WIP du 17/03/2019. Yabause v0.9.14 effectue la rotation, mais il répète le framebuffer (bout de route affiché en haut de l'écran), alors que la console ne le fait pas. Cette rotation est effectuée par le VDP2 avec les paramètres de rotation 2D du paramètre de rotation A (le VDP1 ne fait aucune rotation car il n'exécute que des commandes de scaled sprite).

Les captures ci-dessous sont prise après la manip d'affichage des sprites :
- Kronos v1.6.0 et WIP du 17/03/2019 :
![Powerdrift_Kronos1 6 0](https://user-images.githubusercontent.com/7624262/55277714-653cc700-5303-11e9-9488-19a712a95774.JPG)
- Kronos v1.5.0 :
![Powerdrift_Kronos1 5 0](https://user-images.githubusercontent.com/7624262/55277720-784f9700-5303-11e9-8b54-9eed98f55ba6.JPG)
- Yabause v0.9.14 :
![Powerdrift_Yabause](https://user-images.githubusercontent.com/7624262/55277723-84d3ef80-5303-11e9-9516-818b710d0c85.JPG)

**Comment by FCare** [comment]
RBG0 coloration is due to Color Window swap.

**Comment by fafling** [comment]
En version WIP du 19/04, ces problèmes sont quasiment tous résolus. Il reste juste un décalage latéral du framebuffer.

![Capture_powerdrift20190419](https://user-images.githubusercontent.com/7624262/56440241-23db7e00-62e9-11e9-955d-80fcb37a505e.PNG)

**Comment by fafling** [comment]
En WIP du 30/04, le décalage latéral est remplacé par un décalage vertical : les sprites sont trop bas.
![Capture_power_drift_20190430](https://user-images.githubusercontent.com/7624262/57199517-29d78d00-6f80-11e9-8e7a-60c57568f45c.PNG)

**Comment by fafling** [comment]
En fait, quand on tourne à gauche le décalage se fait vers le bas, mais quand ont tourne à droite, il est vers le haut. C'est peut-être le centre de la rotation qui n'est pas bien positionné.
![Capture_power_drift_20190523](https://user-images.githubusercontent.com/7624262/58520439-223e8900-81b8-11e9-867a-068f6568b822.PNG)

**Comment by fafling** [comment]
Je confirme que le centre de rotation du framebuffer a l'air positionné sur le bord gauche de l'écran, au lieu d'être au milieu comme celui du RBG0.
En WIP du 11/09, le problème concerne les 2 noyaux, OpenGL et compute shader.

**Comment by fafling** [comment]
Toujours présent en WIP accurate_vdp1 du 13/10.

**Comment by fafling** [comment]
Presque correct en OpenGL en WIP accurate_vdp1 du 15/10 : la rotation est bien positionnée, par contre, Kronos semble dessiner le framebuffer en-dehors de ses limites. On le voit sur les coins en bas dans les virages. La limite inférieure de la zone dessinée du framebuffer est visible et stable sur la console, or elle clignote dans Kronos. Si on pause l'émulation, on voit des éléments graphiques en trop dans cette zone (ici dans le coin inférieur droit) :
![image](https://user-images.githubusercontent.com/7624262/66878474-50cbcd80-efba-11e9-9222-5fa53ba25025.png)

**Comment by fafling** [comment]
La zone de dessin définie par le system clipping fait 361x256 (il y a un user clipping plus petit à 320x240, mais les commandes de dessin de l'activent pas). Cette zone est plus grande que l'écran, qui fait 320x240, de façon à limiter la taille de la zone vide dans les coins quand le framebuffer tourne.

Rien à voir avec les problèmes d'affichage de Kronos, mais curieusement le polygone d'effacement est trop petit d'une colonne, il devrait aller jusqu'à 360, mais il s'arrête à 359. Sur la console, quand le framebuffer tourne, on voit effectivement que la colonne de pixels la plus à droite de la zone de dessin n'est jamais effacée et garde des pixels des images précédentes.

**Comment by fafling** [comment]
En WIP accurate_vdp1 du 18/10, le côté de la zone de dessin apparaît plus à gauche que sur la console et tronque des pixels de texture qui sont visibles sur console.
![image](https://user-images.githubusercontent.com/7624262/67125089-4c8af480-f1f4-11e9-9e4d-4645ecea1f9e.png)

Il s'agit de la fin de la 1ère démo du jeu. La colonne de pixel jamais effacée est visible sur ce screenshot de la console (le trait noir en biais dans le coin en haut à droite) :
![image](https://user-images.githubusercontent.com/7624262/67125177-7c39fc80-f1f4-11e9-9c68-4837b4ea3ee1.png)

**Comment by fafling** [comment]
En WIP accurate_vdp1 du 19/10, la zone de clipping du framebuffer est plus petite horizontalement et vericalement que sur la console :
![Capture_power drift_acc_vdp1_20191019_2](https://user-images.githubusercontent.com/7624262/67147511-d17a1a80-f295-11e9-8c49-d6f3531ef651.PNG)
![image](https://user-images.githubusercontent.com/7624262/67147529-025a4f80-f296-11e9-8499-a0d6afe46979.png)

**Comment by fafling** [comment]
Situation identique en WIP du 06/12 en OpenGL. En CS, il y a un décalage des sprites vers la gauche visible dès le menu titre :
![image](https://user-images.githubusercontent.com/7624262/70388219-145f9100-19af-11ea-9f7c-736e2766a325.png)
In-game en CS, la rotation du framebuffer est incorrecte et ne correspond pas à celle du RBG0 :
![image](https://user-images.githubusercontent.com/7624262/70388311-31489400-19b0-11ea-9baa-0d65d9244eb6.png)

**Comment by fafling** [comment]
En WIP du 23/01, il y a un décalage des sprites vers la droite en OpenGL :
![image](https://user-images.githubusercontent.com/7624262/72948003-2a20ee00-3d84-11ea-8362-af11c7886f7b.png)

Le décalage des sprites vers la gauche est fixé en CS, mais la différence d'angle de rotation est toujours présente.

**Comment by fafling** [comment]
En WIP du 04/04, du progrès en CS :  quand on tourne, l'angle de rotation correspond au RBG0, et le troncage en bas des sprites est correct. Par contre, le troncage du haut n'est pas assez prononcé. En prenant comme repère le haut de la barre des pilotes, il se situe au début , au lieu d'être au milieu du 3ème pilote.
![image](https://user-images.githubusercontent.com/7624262/78459676-0569c080-76bb-11ea-84d8-fe51de401d47.png)

En OpenGL, il y a un décalage à l'écran titre, et plus aucun rotation du framebuffer quand on tourne :
![image](https://user-images.githubusercontent.com/7624262/78459796-e15aaf00-76bb-11ea-8364-5f7a9dfbf757.png)

**Comment by BenjaminSiskoo** [comment]
Décalage de l'écran titre toujours présent en OpenGl / CS avec la WIP du 20/10/2020

**Comment by BenjaminSiskoo** [comment]
Décalage de l'écran titre toujours présent en OpenGL / CS avec la WIP du 16 Janvier 2021

**Comment by BenjaminSiskoo** [comment]
Kronos du 14.01.2022
Mode OpenGl

Décalage du cadre autour des options.

![image](https://user-images.githubusercontent.com/12481242/149492062-6c2edb0c-1419-4499-82f2-409867470960.png)

savestate : 
[GS-9181_000.zip](https://github.com/FCare/Kronos/files/7869328/GS-9181_000.zip)

**Comment by BenjaminSiskoo** [comment]
Wip du kronos20231122_7fa6739

Correction de l'écran press start screen

![image](https://github.com/FCare/Kronos/assets/12481242/c575a341-37bf-40ff-ad00-93aeda71c04d)

@fafling c'est en ou de la rotation du RBG ?

**Comment by fafling** [comment]
C'est toujours pas tout à fait ça en terme de position du bord de l'image en haut.
Il y a maintenant des traits parasites qui apparaissent quand l'écran s'incline.
![image](https://github.com/FCare/Kronos/assets/7624262/31f2bba6-25f6-4e69-b93e-a61bab9dbc57)

**Comment by fafling** [comment]
Résolu par l'implémentation correcte de la transformation du framebuffer d'affichage quand il est de type rotation au lieu de transformer le framebuffer de dessin (725ce17 et 00bd8cd).
