### ISSUE TITLE
[Doukoku Soshite] Scintillement sur le premier dialogue (NBG0 ?)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#459]
Kronos rework 11.04.2019

J'ai remarqué qu'en désactivant le NBG0, le dialogue était mieux affiché. Sinon le scintillement se produit sur cette écran

![doukoku soshite](https://user-images.githubusercontent.com/12481242/56077191-742e7980-5dd9-11e9-8553-85291697cab9.PNG)

**Comment by fafling** [comment]
Le scintillement n'est plus là depuis la WIP du 04/07.
Par contre il y a un autre souci de transparence depuis le mois de mai sur les 3 quarts de l'écran, voir #568 .

**Comment by BenjaminSiskoo** [comment]
Ca semble corrigé le 10/10/2019
