### ISSUE TITLE
[Quake] Dégradé vers le noir manquant sur le ciel

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#461]
En version WIP du 13/04, il manque un dégradé de transparence vers le noir sur le ciel affiché par le RBG0. L'affichage est correct en v1.6.0.

Ce dégradé est sûrement obtenu par le jeu en faisant varier le "color calculation ratio" du RBG0 à chaque ligne par un interrupt, ce qui rend le back screen noir de plus en plus visible par transparence.

Version WIP :

![quake_niv2_WIP 20190413](https://user-images.githubusercontent.com/7624262/56240767-8e47b080-6094-11e9-9ccb-1b03064cd12c.PNG)

Version 1.6.0 :

![quake_niv2_1 6 0](https://user-images.githubusercontent.com/7624262/56240792-9bfd3600-6094-11e9-8d26-ca40138d0dfd.JPG)

Le save state pour arriver au point du niveau 2 où j'ai fait les captures :

[quake_niv2.zip](https://github.com/FCare/Kronos/files/3086737/quake_niv2.zip)

**Comment by FCare** [comment]
Fixé aujourd'hui. Nicolas, je te laisse verifier et clore le ticket.

**Comment by fafling** [comment]
C'est OK pour la partie transparence progressive, mais le dégradé est terminé par l'interruption de l'affichage du ciel par la fenêtre W1. Comme pour Doom (#470 ), la fenêtre ne fonctionne plus (problème général ?) et le bas du ciel est affiché au lieu d'être caché.

![Capture_quake_ciel_problème_window_WIP](https://user-images.githubusercontent.com/7624262/57031482-283c5b00-6c48-11e9-94a7-eae75da7e1b8.PNG)

![Capture_quake_ciel_problème_window_WIP2](https://user-images.githubusercontent.com/7624262/57031496-2b374b80-6c48-11e9-8b87-0c6277df126e.PNG)

Affichage correct en v1.6.0 :
![Capture_quake_ciel_problème_window](https://user-images.githubusercontent.com/7624262/57031515-3ab69480-6c48-11e9-89a0-ca02a18d2b13.PNG)

**Comment by fafling** [comment]
Le save state pour reproduire le problème de fenêtre :
[quake_niv2_problème_window.zip](https://github.com/FCare/Kronos/files/3135364/quake_niv2_probleme_window.zip)

**Comment by fafling** [comment]
Le problème des lignes en trop est toujours présent en WIP du 06/12 dans les 2 noyaux.

Par contre, après comptage des pixels, je remarque que la taille de la window est plus grande que la zone du RBG0 affichée par Kronos. Le problème ne semble donc pas causé par une prise en compte incorrecte de la window. C'est donc un autre mécanisme qui fait que sur la console l'affichage du RBG0 est soit interrompu (peut-être par un interrupt non géré par Kronos), soit reste sombre en bas du ciel au lieu de revenir au niveau de luminosité qu'il a en haut.

En effet, une possibilité pour expliquer l'affichage incorrect est que Kronos revient peut-être au color calculation ratio que le RBG0 a au départ de la période d'affichage, donc en haut de l'écran, si le jeu cesse de le modifier par des interrupts, au lieu de conserver le dernier CC ratio positionné par interrupt.

**Comment by fafling** [comment]
Régression suite à la correction du color offset appliqué avant la color calculation #690 , le dégradé n'apparaît plus dans le ciel en WIP du 06/03 dans les 2 noyaux :
![image](https://user-images.githubusercontent.com/7624262/76269981-f4708f80-6273-11ea-9e4e-2e198866ce88.png)

Mise à jour du save state qui date un peu :
[quake_niv2_problème_window.zip](https://github.com/FCare/Kronos/files/4309690/quake_niv2_probleme_window.zip)

**Comment by fafling** [comment]
Mise à jour du save state, l'ancien ne marche plus :
[quake_niv2_problème_window.zip](https://github.com/FCare/Kronos/files/5772724/quake_niv2_probleme_window.zip)

@FCare Si c'est bien le color calculation ratio du RBG0 qui varie en cours d'affichage, est-ce que tu peux ajouter le test du registre CCRR dans la fonction sameVDP2RegRBG0 ?

**Comment by BenjaminSiskoo** [comment]
Savestate à jour du 9/12/2021

[MK-081066_000.zip](https://github.com/FCare/Kronos/files/7685972/MK-081066_000.zip)

**Comment by fafling** [comment]
Fixé dans les 2 noyaux en WIP du 10/12/2021.
