### ISSUE TITLE
[Sonic 3D Blast] Problèmes de priorité sprite/NBG0

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#462]
En version WIP du 13/04, Sonic est partiellement ou complètement visible derrière des éléments du décor du NBG0 qui devraient le cacher (rampe de looping, tunnel, puit). En v1.6.0, l'affichage était correct.

Ce problème se produit aussi pour l'eau, et c'était déjà présent en v1.6.0, mais différemment.

Dans les 2 cas, les sprites utilisent le registre 0 de priorité qui a la valeur 2. Le NBG0, dont certaines parties doivent être affichées derrière ces sprites et d'autres devant, a aussi une priorité à 2, ce qui devrait l'afficher systématiquement derrière.

On ne le voit pas dans l'écran debug du VDP2, mais le NBG0 fait sûrement varier sa priorité par pixel grâce à la special priority function : certaines des couleurs qu'il utilise doivent être comprises dans la plage associée à la fonction. Tous les pixels du NBG0 qui ont ces couleurs, et qui font partie de tiles flaggées pour activer la fonction, ont leur priorité qui passe à 3 (le bit le plus faible de la valeur de priorité passe de 0 à 1). Cela les affiche devant Sonic ou l'eau. Les autres pixels du NBG0 restent à une priorité de 2 et sont affichés derrière.

Captures de la version WIP :

![Capture sonic3D3](https://user-images.githubusercontent.com/7624262/56245071-be944c80-609e-11e9-99d3-4cebc4ff5c6e.PNG)

![Capture sonic3D4](https://user-images.githubusercontent.com/7624262/56245095-cce26880-609e-11e9-858a-045a664260b3.PNG)

![Capture sonic3D5](https://user-images.githubusercontent.com/7624262/56245133-e4215600-609e-11e9-824d-2443a0eae9a9.PNG)

![Capture sonic3D8](https://user-images.githubusercontent.com/7624262/56245146-ebe0fa80-609e-11e9-9a9e-93bf0f86ef87.PNG)

![Capture sonic3D9](https://user-images.githubusercontent.com/7624262/56245152-eedbeb00-609e-11e9-9314-6f525f9a64e4.PNG)

Les save states correspondant aux 2 captures :

[sonic3D_niv1-1.zip](https://github.com/FCare/Kronos/files/3086955/sonic3D_niv1-1.zip)

[sonic3D_niv1-2.zip](https://github.com/FCare/Kronos/files/3086957/sonic3D_niv1-2.zip)

**Comment by FCare** [comment]
En effet le NBG0 utilise la fonction special priority by character. C'est
implémenté et ca marche bien.
Le probleme vient du systeme de cache des cells...
Ce cache a un taux non nul de faux positifs... Je vais voir a l'ameliorer.

Le mar. 16 avr. 2019 à 23:30, nicolas-charrier <notifications@github.com> a
écrit :

**Comment by FCare** [comment]
Fixé le 17 avril :-)

**Comment by fafling** [comment]
C'est beaucoup mieux en WIP du 17/04, mais il y a encore des problèmes quand c'est la priorité par pixel qui est nécessaire, pas seulement par tile. C'est très visible dans le 1er tunnel avec Sonic équipé d'un bouclier.

![sonic3d_WIP20190419](https://user-images.githubusercontent.com/7624262/56410126-4c795e80-627c-11e9-9ec5-122fd06f808f.PNG)

[sonic3D_niv1-1_WIP20190417.zip](https://github.com/FCare/Kronos/files/3097177/sonic3D_niv1-1_WIP20190417.zip)

**Comment by fafling** [comment]
Autant pour moi, je viens de vérifier sur la console et l'affichage de Kronos est correct, c'est seulement la priorité par tile qui est utilisée par le jeu. Il n'y a donc plus de problème. Bravo François !

**Comment by FCare** [comment]
Je n'ai pas le jeu et ma console n'est plus branchée pour le moment. Mais
j'avais egalement vu le probleme et les speed runs en video sur youtube
m'ont confirmé que le pb etait bien présent sur la console.

Ca fait plaisir de voir ce jeu qui fonctionne finalement bien :-)

Le ven. 19 avr. 2019 à 08:44, nicolas-charrier <notifications@github.com> a
écrit :
