### ISSUE TITLE
[Decathlete] Chutes de frame rate et problèmes graphiques

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#467]
Dans Decathlete, la version US de Athlete kings, il y a de grosses variations de frame rate : ça tombe à environ 12 FPS et ça remonte à 36 à l'écran titre, et à moins de 5 FPS et ça remonte à 20-25 pendant la demo, avec rechute et plantage de Kronos en fin de démo.

Ma config : processeur Intel Core i3-3220T 2.80GHz, 4Go de RAM, carte Nvidia GeForce GTX 750 Ti, Windows 10 32 bits.

Autres problèmes graphiques dans ce jeu :

- A l'écran titre une barre noire apparaît à droite de l'écran sur le ciel quand le fondu avec le logo commence.

![Capture_decathlete_bordure_noire_titre](https://user-images.githubusercontent.com/7624262/56822659-06129980-6852-11e9-8fcf-727bd858511a.PNG)

- Si je pause l'émulation en cliquant sur le bouton de pause ou bien en affichant un écran à partir du menu de Kronos (debug VDP1 ou VDP2 ou options), les couches VDP2 disparaissent.

En v1.6.0, il n'y avait ni les chutes de frame rate, ni ces 2 problèmes.

**Comment by fafling** [comment]
Vu par @BenjaminSiskoo , les baisses de framerate correspondent à des allocations mémoires qui n'avaient pas lieu en 1.6.0, ni en WIP du 11/02. Elles apparaissent en WIP du 17/03.
Ces allocations se produisent pendant les changement d'écran et semblent coïncider avec des effets de color offset :
- Pendant le color offset d'apparition de l'écran titre, on passe de 245 à 700 Mo.
- Pendant le color offset de début de démo, on passe de 700 à 1280 Mo.
- Pendant le color offset de fin de démo, on passe de 1280 à 1530 Mo et ça plante.

Ces allocation se produisent même avec le bug d'écran noir en cas de pause ou d'affichage de menu (en WIP du 12/05, tout l'écran devient noir, pas seulement les couches VDP2).

Les allocations mémoires et les perf sont les mêmes en OpenGL size 1x, 2x et 4x.

**Comment by fafling** [comment]
Je n'ai pas observé de fuite mémoire et de baisse de framerate sur Virtua Fighter 2 qui est aussi un jeu high res double interlace, mais il n'utilise pas de variation de color offset lors des changement d'écran.

Benjamin m'avait aussi signalé Worldwide Soccer 97 : sur la version US (Worldwide Soccer), il y a effectivement allocation mémoire et baisse de framerate importantes pendant les effets de color offset :
- quand on appuie sur start à l'écran titre : +350 Mo
- si on fait A+B+C+start pour revenir à l'écran titre : +220 Mo
Au bout de 3 aller-retour, Kronos plante autour de 1500 Mo alloués.

Le plantage de Sonic 3D pendant les démos #465 vient de là aussi : il y a un effet de color offset presque à tous les changements d'écran, ça alloue entre 50 et 100 Mo à chaque fois, donc plantage de Kronos vers les 1500 Mo.

**Comment by fafling** [comment]
En WIP du 15/05 :
- Le fix pour Virtua Fighter 2 #492 corrige aussi la disparition des couches VDP2 dans Athlete Kings 👍 
- La barre noire apparaît toujours à droite de l'écran titre, mais elle disparaît si on fait une des actions qui faisaient disparaître les couches VDP2 auparavant (pause puis relance de l'émulation, affichage d'une fenêtre à partir du menu de Kronos).
- Comme vu par @barbudreadmon , le haut de l'écran titre monte et descend (ce problème existait déjà en v1.6.0).

**Comment by fafling** [comment]
Autre exemple, Warcraft 2. Le menu pause effectue un color offset pour assombrir le jeu en arrière-plan. A chaque pause, la mémoire augmente de 7-8 Mo. Si on appuie sur start sans arrêt, Kronos plante au bout de 1 mn 30 s.
Un save state pour aller dans le jeu :
[warcraft.zip](https://github.com/FCare/Kronos/files/3184561/warcraft.zip)

**Comment by barbudreadmon** [comment]
Comme signalé sur discord, la fuite mémoire est introduite par https://github.com/FCare/Kronos/commit/cda5e2cad27b67daf3994af3911122a6d65df193 . 
Le commit précédent (https://github.com/FCare/Kronos/commit/1bcf5ee38cdefacdc46293c81ab000a90f5aba02) ne présentait pas ce problème (utilisation RAM stable et inférieure à 500 Mo chez moi avec ce commit malgré de sévères problèmes graphiques).

**Comment by barbudreadmon** [comment]
Le problème semble être corrigé chez moi avec https://github.com/FCare/Kronos/commit/285c5222deea7dd67c0a7f00707b564ecbcda7ca, le jeu reste gourmand par contre.
PS : j'ai un i7 2600k avec une GTX 960

**Comment by BenjaminSiskoo** [comment]
FPS corrigé

**Comment by fafling** [comment]
En WIP du 16/05, la conso mémoire est stable pour les jeux cités (et nettement plus faible!), plus de plantage et le framerate ne plonge plus 👍 
J'ouvre une nouvelle fiche sur les barres noires constatées dans Athlete Kings.
