### ISSUE TITLE
[Burning rangers] Problèmes sur les graphisme semi-transparents (NBG1) en extui-align

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#468]
En version WIP du 26/04 :

- Comme pour les autres jeux avec copie de framebuffer, il y a un problème quand l'option OpenGL size est réglée sur 2x ou plus. Cette fois les graphismes semi-transparents disparaissent complètement, et ils ne réapparaissent pas quand on remet OpenGL size à Original :

![Capture_burning_rangers_transparence_incorrecte4_opengl_size_2x](https://user-images.githubusercontent.com/7624262/56829568-601c5a80-6864-11e9-889c-3a7695cefb00.PNG)

- Une partie des graphismes semi-transparents affichés par Kronos n'existe pas sur la console : ils ajoutent un voile rouge sur une partie du décor du tutoriel, ici sur le sol.

![Capture_burning_rangers_transparence_incorrecte4_sol_rouge](https://user-images.githubusercontent.com/7624262/56829774-ef297280-6864-11e9-9607-7cb61ed9117d.PNG)

Ce problème est peut-être lié aux coordonnées qui dépassent 32000 sur pas mal de commandes du batch de dessin des graphismes semi-transparents par le VDP1 :

![Capture_burning_rangers_transparence_incorrecte3](https://user-images.githubusercontent.com/7624262/56830280-3ebc6e00-6866-11e9-9716-570e845d2c37.PNG)

- Le traitement de transparence de la console n'utilise que l'addition, sans tenir compte des ratios (le registre Color calculation mode devrait être à 1, mais on ne le voit pas dans l'écran debug du VDP2). C'est visible sur console car le niveau de transparence dépend de la luminosité de la couleur du NBG1 : si le pixel du NBG1 est noir, on ne le voit pas et s'il est blanc, on ne voit pas les sprites. Or dans Kronos, l'addition semble être faite après application du ratio 15:17 aux pixels du NBG1, ce qui fait que les sprites sont toujours partiellement visibles, même derrière un pixel blanc du NBG1.

![Capture_burning_rangers_transparence_incorrecte](https://user-images.githubusercontent.com/7624262/56830190-fdc45980-6865-11e9-8ac9-d7150705df51.PNG)

![Capture_burning_rangers_transparence_incorrecte2](https://user-images.githubusercontent.com/7624262/56830196-00bf4a00-6866-11e9-835d-d1230b85598b.PNG)

Un save state pour aller dans la salle du tutoriel avec les flammes :

[burning_rangers_tuto.zip](https://github.com/FCare/Kronos/files/3122659/burning_rangers_tuto.zip)

**Comment by fafling** [comment]
En WIP du 09/05, il n'y a plus de problème quand on change l'OpenGL size.
La transparence additive est correcte :
![Capture](https://user-images.githubusercontent.com/7624262/57488677-0f6d1e80-72b4-11e9-8bec-0af19b2cc32f.PNG)

Il y avait aussi le même problème de fenêtre qui n'apparaissait pas que dans Doom, c'est réglé aussi.

Il reste donc le problème des graphismes semi-transparents affichés par Kronos qui n'existent pas sur la console.

**Comment by fafling** [comment]
Dégradation de la couche semi-transparente suite à la restriction des coordonnées du VDP1 (commit a60b39d ) : la plupart des flammes ne s'affichent plus, et le voile rouge couvre presque tout l'écran.

Avant le patch :
![Capture_burning_rangers_avant_restriction_coordonnées](https://user-images.githubusercontent.com/7624262/58057623-d52e3780-7b65-11e9-8c4f-b5bb27dd7c66.PNG)

Après le patch :
![Capture_burning_rangers_après_restriction_coordonnées](https://user-images.githubusercontent.com/7624262/58057636-df503600-7b65-11e9-93e4-0efb864a8731.PNG)

Apparemment, de nombreuses commandes du 1er batch qui dessine cette couche ont des coordonnées qui ne respectent pas la règle de sign extension. Comme elles concernent une zone de dessin 2 fois plus petite dans les 2 directions dans le framebuffer, il est possible qu'elles soient obtenues par un décalage à droite des coordonnées de dessin des sprites non transparents. Si c'est le cas, soit c'est Kronos qui n'effectue pas l'opération nécessaire pour que les coordonnées obtenues respectent la règle de sign extension, soit c'est la console qui parvient à afficher de telles commandes, malgré l'entorse à la règle.

**Comment by FCare** [comment]
Ok. La verification telle que je l'ai implémentée hier concerne les CMDX et le user local coordinates qui utilisent la meme representation 10 bits + code extension. Je limite les valeurs des qu'on lit les valeurs.
Or, ces valeurs sont ajoutées avant d'etre effectivement dessinée par le VDP1. L'effet de l'un peut donc annuler l'effet de l'autre...
On doit pouvoir en deduire que l'ALU du VDP1 est bien 16 bits, mais le blitter limite les coordonnees en 10 bits signes.
La verification doit donc etre faite apres la somme des deux parametres...

Ca ca sera a mettre dans les choses non-documentées (ou mal documentées) car le fonctionnement est faux depuis yabause...

**Comment by FCare** [comment]
Nouveau patch poussé. Il faut verifier qu'on a bien recuperé Burning rangers en ayant toujours Holy Ark.

**Comment by fafling** [comment]
C'est pas bon pour Burning rangers : non seulement des éléments transparents ne sont pas dessinés, mais ceux qui restent sont effacés en grande partie par des polygones verticaux.

![Capture_burning_rangers_après_restriction_coordonnées_et_cumul_local](https://user-images.githubusercontent.com/7624262/58123673-aae38500-7c0c-11e9-9359-01c37b67c3d9.PNG)

**Comment by fafling** [comment]
Pas constaté de régression sur les jeux à coordonnées bizarres comme Holy ark.

**Comment by fafling** [comment]
Guère de changement dans la dernière WIP avec le commit 67430b0 .

**Comment by FCare** [comment]
tu peux tester avec les derniers patchs?

**Comment by fafling** [comment]
En v1.7.0 publique, il y a du mieux sur le voile rouge qui n'est plus visible, mais par contre, les éléments semi-transparents sont en grande partie effacés.
![Capture_burning_rangers_training_1 7 0](https://user-images.githubusercontent.com/7624262/59391537-d9203480-8d74-11e9-866b-b504778c539a.PNG)

**Comment by fafling** [comment]
Même situation en WIP accurate_vdp1 du 05/10.

**Comment by fafling** [comment]
Evolution avec la WIP du 07/10, les sprites semi transparents sont là, mais une partie (peut-être tous) des sprites de cache (qui effacent les sprites semi-transparents quand ils sont derrière un sprite opaque) sont opaques au lieu d'être transparents :
![Capture_burning_rangers_acc_vdp1_20191007](https://user-images.githubusercontent.com/7624262/66458444-166ea780-ea73-11e9-8dc5-554a18b7f676.PNG)

**Comment by fafling** [comment]
En fait, le problème c'est que la semi-transparence additive ne fonctionne plus, et donc la couche semi-transparente est opaque. Les polygones de masque utilisent la couleur RGB noir (8000 en hexa), ce qu'on voit ici. Quand la semi-transparence marche, le noir, valant 0 sur tous ses canaux, devient transparent.

J'ai vérifié, ce mode de semi-transparence fonctionne correctement dans d'autres jeux (Megaman X4, Guardian heroes, les special stages de Sonic 3D).

**Comment by fafling** [comment]
En WIP accurate_vdp1 du 10/10, l'arrière plan vert du NBG0 est visible alors qu'il devrait être caché par les sprites.
![Capture_burning_rangers_acc_vdp1_20191010](https://user-images.githubusercontent.com/7624262/66612538-5bedba80-ebc2-11e9-9240-72ba266c3a47.PNG)
La semi-transparence additive avec le NBG1 semble de nouveau correcte.

**Comment by fafling** [comment]
L'affichage des graphismes semi-transparents est fixé pour le noyau OpenGL en WIP accurate_vdp1 du 12/10 👍

**Comment by fafling** [comment]
Fixé en extui-align dans les 2 noyaux par la WIP du 19/11.
