### ISSUE TITLE
[Sonic 3D Blast] RBG1 non visible par transparence dans les special stages en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#469]
Dans Kronos, le RBG1 n'est visible que si on désactive le RBG0. Sur console, il apparaît par transparence additive sans application de ratio. C'est probablement lié au problème observé sur les graphisme semi-transparents de Burning rangers #468 .

![Capture_sonic3d_special_stage](https://user-images.githubusercontent.com/7624262/56831557-aaeca100-6869-11e9-90e1-f94e5698295e.PNG)

![Capture_sonic3d_special_stage2](https://user-images.githubusercontent.com/7624262/56831662-f43cf080-6869-11e9-9834-23209e216e21.PNG)

Une capture de YouTube qui correspond à l'affichage de la console :

![Capture_sonic3d_special_stage_youtube](https://user-images.githubusercontent.com/7624262/56831885-a8d71200-686a-11e9-932d-ec90389078bf.PNG)

Un save state pour aller directement dans le 1er special stage :

[sonic3D_special_stage.zip](https://github.com/FCare/Kronos/files/3122727/sonic3D_special_stage.zip)

**Comment by fafling** [comment]
Attention, le RBG0 utilise la special color calculation par pixel selon le MSB des couleurs dans la color RAM pour que la forêt noire en bas ne soit pas transparente.

**Comment by fafling** [comment]
L'affichage est correct en WIP du 08/05.

![Capture](https://user-images.githubusercontent.com/7624262/57432859-45b88880-7237-11e9-9edf-dc591c831e41.PNG)

**Comment by fafling** [comment]
Problème réapparu dans la 2ème WIP du 03/09, quand le compute shader est activé.
![Capture_sonic_3D_compute_shader_20190903_2](https://user-images.githubusercontent.com/7624262/64215920-fddd0180-ceb6-11e9-8daf-4ef6f8257f8f.PNG)

**Comment by fafling** [comment]
Corrigé en WIP du 04/09.

**Comment by fafling** [comment]
Présent de nouveau en noyau CS uniquement en WIP du 20/12. Réapparu en WIP du 08/12.

**Comment by FCare** [comment]
Ok, le pb n'est pas lié au noyau compute shafer mais a l'opiton RBG en compute shader.

**Comment by FCare** [comment]
Fixé le 25/12/2019

**Comment by fafling** [comment]
Affichage correct en WIP du 25/12, c'est Noël ;-)

**Comment by fafling** [comment]
Présent de nouveau en noyau CS uniquement en WIP du 17/03. Réapparu en WIP du 05/01.
C'est un coriace !

**Comment by fafling** [comment]
re-re-re-fixé en WIP du 19/03.
