### ISSUE TITLE
[Doom] Artefacts dans le jeu au sol...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#470]
Kronos du 27 Avril 2019 :

![doom](https://user-images.githubusercontent.com/12481242/56847264-3c472c00-68d9-11e9-9133-63aab1be7390.PNG)

**Comment by fafling** [comment]
Difficile d'analyser le problème des segments de sol car l'écran debug du VDP1 n'affiche que certains batchs de commandes. En général, pour une frame donnée, on n'arrive à voir qu'un batch de commandes de dessin de sol ou de plafond et ce n'est jamais un secteur à problème.

Voilà comment je pense que se passent les choses dans le rendu des sols et plafonds par la console. Le calcul des textures est forcément effectué par les SH-2 dans la work RAM (je suppose que le développeur ne les fait pas écrire direct dans la VRAM du VDP1, sinon autant mettre à jour directement le framebuffer). Vu la structure des batchs de commandes, qui groupent les lignes par parité des coordonnées y, les 2 SH-2 se répartissent certainement le travail de cette manière : l'un crée les textures et commandes des lignes paires, et l'autre celles des lignes impaires. Il y a de bonnes chances que ce traitement en parallèle sature le bus CPU ce qui expliquerait en partie les mauvaise perf. Comme les batchs de commandes n'ont jamais de textures de différents secteur, les CPU traitent sûrement toutes les lignes d'un secteur, attendent que le VDP1 ait fini de dessiner le batch précédent (ou c'est le VDP1 qui les attend car la taille des batchs varie fortement), puis transfèrent le batch dans la VRAM du VDP1 sans doute via un transfert DMA du SCU. Là encore, les temps d'attente à chaque batch entre les SH-2 et le VDP1 participent aussi aux mauvaises perf.

Dans Kronos, les segments incorrects semblent toujours réutiliser des textures d'autres secteurs de la même frame. Donc soit les textures d'un secteur précédent ne sont pas écrasées dans la work RAM par les SH-2, soit c'est le transfert des textures de la work RAM vers la VRAM qui ne se fait pas (mais les commandes sont transférées, sinon il n'y aurait pas de dessin).

Il y a aussi un problème de clignotement par moment : j'ai trouvé un endroit au 1er niveau où il y a un affichage intermittent de l'arme, la porte qui se trouve au fond et un secteur de plafond. Cela peut indiquer qu'il y a des batchs entiers qui ne sont pas traités, donc là encore ça peut venir d'un problème de transfert de la work RAM vers la VRAM qui ne se fait pas, mais cette fois les commandes sont concernées.

Quand tout est affiché :
![Capture_doom_clignotement_tout_a_lecran](https://user-images.githubusercontent.com/7624262/56856162-03e53380-6955-11e9-993a-2560b2f49e04.PNG)

Sans l'arme ni la porte :
![Capture_doom_clignotement_arme_porte](https://user-images.githubusercontent.com/7624262/56856164-0a73ab00-6955-11e9-8b3c-dec36f6034b3.PNG)

Sans la porte et un secteur du plafond :
![Capture_doom_clignotement_port_plafond](https://user-images.githubusercontent.com/7624262/56856165-119ab900-6955-11e9-9f34-7052b0f61a18.PNG)

Un save state pour arriver au point où il y a ces clignotements :
[doom_niv1_clignotements.zip](https://github.com/FCare/Kronos/files/3124437/doom_niv1_clignotements.zip)

Les 2 problèmes, segments incorrects et clignotements, étaient déjà présents en v1.6.0.

**Comment by fafling** [comment]
Il y a aussi un problème avec le bas des sprites visibles derrière le haut de la tête du Doomguy. Le problème apparaît sur la WIP du 17/03. Normalement, les sprites sont tronqués par la fenêtre W0 en haut de la barre de statut. Ce qui permet de voir que le jeu dessine jusqu'à une vingtaine de lignes derrière la barre de statut qu'on ne voit jamais du fait de la fenêtre.

![Capture_doom_sprite_derrière_barre_statut](https://user-images.githubusercontent.com/7624262/56856506-5d9d2c00-695c-11e9-8b23-9c515bef2145.PNG)

Si on désactive les NBG2 et 3 :
![Capture_doom_sprite_derrière_barre_statut2](https://user-images.githubusercontent.com/7624262/56856509-62fa7680-695c-11e9-9d06-04cd8ed5cbb8.PNG)

![Capture_doom_window](https://user-images.githubusercontent.com/7624262/56856510-67269400-695c-11e9-89c4-37fb9be67c0a.PNG)

**Comment by FCare** [comment]
Les artefacts semblent etre les memes que ceux observables sur Earthworm Jim 2 version US.
J'ai commencé a regarder mais je n'ai encore trouvé aucune piste...

**Comment by fafling** [comment]
Doom utilise aussi des textures 8 bits avec pixel transparent, mais je n'ai pas l'impression de voir le même artifact. Les sprites clignotent complètement dans Doom alors qu'on a une sorte de décalage intermittent dans la lecture de la texture dans NFL, NBA et Earthworm Jim.

**Comment by fafling** [comment]
Je précise que je teste avec la version japonaise du jeu.

**Comment by fafling** [comment]
Le problème de fenêtre est réglé en WIP du 08/05.

**Comment by fafling** [comment]
Problème apparu en 2ème WIP du 19/05 et toujours présent en WIP du 05/06 : des trous apparus en WIP du 12/05 ont disparu, mais il apparaît un grossissement de certaines lignes et colonnes.
On a l'impression qu'une partie de l'image est rendue en demi résolution. Ce n'est pas le cas sur la console.

WIP du 05/06 avec le grossissement :
![Capture_doom_flats_trop_gros_20190605](https://user-images.githubusercontent.com/7624262/59065902-19337300-88ae-11e9-832c-563e44a09ea1.PNG)

1ère WIP du 19/05 sans le grossissement :
![Capture_doom_flats_20190519_2](https://user-images.githubusercontent.com/7624262/59066020-5c8de180-88ae-11e9-8ad6-51a69a50ec3b.PNG)

**Comment by fafling** [comment]
Le noyau compute shader n'est pas concerné par le problème de grossisement, par contre les clignotements sont présents.

Surtout, les corruptions de textures du sol sont beaucoup plus fréquentes avec ce noyau :
![Capture_doom_rasterizer](https://user-images.githubusercontent.com/7624262/63637008-a5686180-c677-11e9-9e7f-ff1c2c804046.PNG)

On voit la bonne texture dans l'écran debug du VDP1 :
![Capture_doom_rasterizer_VDP1](https://user-images.githubusercontent.com/7624262/63637011-a7cabb80-c677-11e9-933d-e3739447b569.PNG)

Un save state pour accéder directement à cet endroit :
[Doom_texture_sol_rasterizer.zip](https://github.com/FCare/Kronos/files/3537153/Doom_texture_sol_rasterizer.zip)

**Comment by fafling** [comment]
En WIP du 08/12 :
- Les corruptions de textures du sol sont présentes dans les 2 noyaux, très fréquentes en compute shader, beaucoup moins en OpenGL.
- Les clignotements sont présents dans les 2 noyaux.
- Le grossissement des textures des sols et plafonds n'existe qu'en OpenGL.

**Comment by fafling** [comment]
Le grossissement des textures des sols et plafonds en OpenGL a été fixé en WIP du 02/05.
