### ISSUE TITLE
Demi-transparences RGB et shadow RGB du VDP1 incorrectes en extui-align

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#475]
En WIP du 30/04, il y a des effets de transparence incorrects vers un arrière-plan VDP2 dans de nombreux jeux sur des pixels du framebuffer qui utilisent les effets de color calculation du VDP1 half transparency ou shadow.

Dans tous les jeux concernés, le problème se produit quand le color offset est activé sur le plan de sprite (même avec des valeurs à 0).

Il y a le même problème en bios réel ou émulé depuis le version WIP du 26/04. En WIP du 21/04, le problème ne se produit que si le color offset a une valeur différente de 0, et ce, depuis la WIP du 17/03. La WIP du 11/02 n'a pas ce problème du tout.

Exemple dans Mystaria euro, premier dialogue après l'intro (les ombres utilisent le mode shadow, et la fenêtre bleue le mode half transparency) :

![Capture_mystaria_bug_shadow_transparences_RGB_VDP1](https://user-images.githubusercontent.com/7624262/57123756-4195f200-6d83-11e9-9c2d-de92c05b2e1b.PNG)

L'affichage correct est celui-ci :
![Capture_mystaria_bug_shadow_transparences_RGB_VDP1_20140420](https://user-images.githubusercontent.com/7624262/57124065-88381c00-6d84-11e9-990f-880b0c0c84e1.PNG)

Autres jeux concernés :
- Le bios (ombre des boutons, fenêtre de message)
- Duke Nukem (ombre des ennemis, emplacements d'objets dans le menu pause)
- Panzer Dragoon (rayons)
- Powerslave (fenêtre des message sur la carte, ombre des ennemis)
- Sonic R ("R" à l'écran titre, le bouclier et la trainée d'accélération pendant la course)
- Sonic Z-treme (ombre de Sonic)
- Virtual Hydlide (ombre du perso)

Le seul jeu que j'ai trouvé qui utilise ces traitements de color calculation RGB du VDP1 sans problème, c'est Bug too, et il n'active pas le color offset (les effets d'assombrissement sur le framebuffer pendant les transitions sont obtenus en redessinant le contenu du framebuffer avec du Gouraud shading).

**Comment by fafling** [comment]
Un truc marrant, voilà le genre de sprite qui sert à dessiner les ombres des ennemis dans les jeux Lobotomy Software (Powerslave et Duke Nukem 3D) :

![Capture_powerslave_bug_shadow_RGB_VDP1_20190430_debug_VDP1](https://user-images.githubusercontent.com/7624262/57170127-fa534400-6e0a-11e9-8bd0-d273abfac3a3.PNG)

**Comment by BenjaminSiskoo** [comment]
:o

**Comment by FCare** [comment]
Vuos pouvez reverifier celui la, ca me semble bon maintenant...

**Comment by fafling** [comment]
Avec le dernière WIP du 12/05, j'ai toujours le même souci dans le bios et Mystaria. @BenjaminSiskoo Est-ce que tu peux tester ça, on aura peut-être encore une différence là-dessus ?

**Comment by BenjaminSiskoo** [comment]
Ce soir je suis en formation ^^

**Comment by FCare** [comment]
C'est quoi le pb dans le bios dont tu parles?

**Comment by fafling** [comment]
Je vois le starfield d'arrière-plan en transparence par l'ombre des boutons et la fenêtre de description en bas.

Dernière WIP :
![Capture](https://user-images.githubusercontent.com/7624262/57648684-6df11000-75c6-11e9-8976-d45e36d5d446.PNG)

Affichage correct en WIP du 21/04 :
![Capture2](https://user-images.githubusercontent.com/7624262/57648802-bc9eaa00-75c6-11e9-8a22-9582ce256551.PNG)

**Comment by BenjaminSiskoo** [comment]
avec le wip d'aujourd'hui 
![bios](https://user-images.githubusercontent.com/12481242/57797517-eda7e780-774a-11e9-9576-51c31702b884.PNG)

**Comment by fafling** [comment]
C'est toujours pas bon pour moi avec la WIP du 15/05.

**Comment by FCare** [comment]
efface ton .ini et re-teste. C'est bon chez moi aussi et il semble que tu as des pb de transparence un peu partout. Comme ca on sera sur.

**Comment by fafling** [comment]
J'ai supprimé l'ini et ça ne change rien. D'ailleurs, Kronos ne l'a pas recréé, est-ce que c'est dû à la release x86 qui ne crée pas ce fichier ?
Faudrait voir si @barbudreadmon a le même problème, possible que ce soit un souci de compatibilité au niveau transparences avec les cartes Nvidia.

**Comment by fafling** [comment]
Le problème est toujours présent en v1.7.0 publique.

On peut le voir aussi dans le menu titre de Quake : le VDP1 dessine un polygone marron semi transparent sur tout le décor avant de dessiner le menu. Dans Kronos v1.7.0, le ciel (RBG0) et le back screen noir sont visible par transparence sur tout l'écran sauf ce qui est dessiné par-dessus ce polygone. C'est encore un jeu qui active le color offset (avec des valeurs à 0 sur l'écran titre).

Affichage incorrect dans Kronos v1.7.0 :
![Capture_quake_menu_titre_1 7 0](https://user-images.githubusercontent.com/7624262/59569206-9917c500-9086-11e9-91bb-e4abcd8c88bf.PNG)

Affichage correct :
![Capture_quake_menu_titre_correct](https://user-images.githubusercontent.com/7624262/59569213-ab91fe80-9086-11e9-8c91-84aa85697186.PNG)

Commande de dessin du polygone marron semi-transparent :
![Capture_quake_menu_titre_1 7 0_VDP1](https://user-images.githubusercontent.com/7624262/59569216-bf3d6500-9086-11e9-9584-5493aa093dcc.PNG)

**Comment by fafling** [comment]
Le même problème qu'à lécran titre est visible dans Quake pendant la pause et sur le menu de sauvegarde de fin de niveau.

Dans Wipeout, même souci à l'écran pause, le VDP1 dessine un polygone noir semi-transparent. Dans Kronos v1.7.0, le ciel (RBG0) est visible par transparence sur tout l'écran sauf ce qui est dessiné par-dessus ce polygone. Testé avec le CD japonais.

Affichage incorrect dans Kronos v1.7.0 :
![Capture_wipeout_pause_1 7 0](https://user-images.githubusercontent.com/7624262/59571511-c45ddc80-90a5-11e9-8b21-9e229dc61ce1.PNG)

Affichage correct :
![Capture_wipeout_pause_1 6 0](https://user-images.githubusercontent.com/7624262/59571515-d5a6e900-90a5-11e9-9557-980a0f41e57b.PNG)

**Comment by fafling** [comment]
Problème en grande partie réglé par la WIP rasterizer.
Sur la half-transparency VDP1, il reste le polygone marron qui recouvre le décor à l'ecran titre de Quake qui n'est pas complètement correct : sur la zone où il recouvre les pixels transparents du framebuffer, il est bien opaque, mais sa couleur est assombrie comme s'il héritait de la color calculation que fait le VDP2 sur le ciel du RBG0 par rapport au back screen noir.
![Capture_quake_rasteriser2_half_transparency](https://user-images.githubusercontent.com/7624262/63574268-ade16f00-c587-11e9-9903-a6d48e3410d5.PNG)

**Comment by fafling** [comment]
Fixé en OpenGL dans la WIP accurate_vdp1 du 24/09.

**Comment by fafling** [comment]
Résolu en WIP du 24/11 dans les 2 noyau.
