### ISSUE TITLE
[Guardian Heroes] La normal shadow ne s'affiche plus

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#476]
En WIP du 30/04, on ne voit pas les cadres assombris dans les écrans de sélection du support de sauvegarde et de sélection du personnage. Je teste avec la version US de Guardian Heroes.

Pour obtenir cet écran dès le démarrage du jeu, il faut sélectionner une backup RAM comme cartouche :
![Capture_guardian_heroes_shadow_20190430](https://user-images.githubusercontent.com/7624262/57185322-406edd00-6ec9-11e9-9fbc-f6b18bf561e1.PNG)

Affichage correct en v1.6.0 :
![Capture_guardian_heroes_shadow_1 6 0](https://user-images.githubusercontent.com/7624262/57185276-87100780-6ec8-11e9-878c-957142b47258.PNG)

Le cadre est dessiné par le VDP1 :
![Capture_guardian_heroes_shadow_debug_VDP1](https://user-images.githubusercontent.com/7624262/57185299-fe459b80-6ec8-11e9-9c7f-7d38462fb0f3.PNG)

L'assombrissement est sans doute réalisé par le VDP2 au moyen de la normal shadow car on voit que le traitement de shadow est activé dans l'écran debug du VDP2. De plus, la color calculation n'est pas activée sur les sprites, il n'y a donc que la normal shadow qui puisse assombrir la couche VDP2 qui est derrière les sprites.

![Capture_guardian_heroes_shadow_debug_VDP2](https://user-images.githubusercontent.com/7624262/57185236-06510b80-6ec8-11e9-958b-b24b19a2dc85.PNG)

Le problème est présent depuis la WIP du 17/03.

**Comment by FCare** [comment]
Reglé aujourd'hui. Merci de verifier de votre coté :-)

**Comment by fafling** [comment]
L'effet de shadow est correct 👍
