### ISSUE TITLE
Problème sur les commandes VDP1 de line et polyline

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#477]
En WIP du 30/04, et depuis la v1.6.0, dans Guardian Heroes (version US), il manque une bordure blanche autour des fenêtres des écran de choix de support de sauvegarde et de player select (en WIP, la fenêtre est manquante également).

Pour obtenir cet écran dès le démarrage du jeu, il faut sélectionner une backup RAM comme cartouche :

![Capture_guardian_heroes_shadow_20190430](https://user-images.githubusercontent.com/7624262/57200154-3e1f8800-6f88-11e9-8425-7b4b3e690243.PNG)

Affichage correct en v1.5.0 :

![Capture_guardian_heroes_shadow_1 5 0](https://user-images.githubusercontent.com/7624262/57200168-745d0780-6f88-11e9-92f7-acd317050543.PNG)

La bordure est dessinée par une commande de polyline :

![Capture_guardian_heroes_polyline_VDP1_debug](https://user-images.githubusercontent.com/7624262/57200172-8fc81280-6f88-11e9-966c-416c1e3fee35.PNG)

**Comment by nicolas-charrier** [comment]
Peut-être le même problème que celui de la carte dans Doom #470 , qui date de la v1.6.0 aussi.

**Comment by fafling** [comment]
C'est sans doute un problème général, je regroupe donc des jeux différents avec les mêmes problèmes de pixels manquant ou de lignes complètement manquantes sur des commandes VDP1 de line ou polyline, tous depuis la v1.6.0.

**Comment by fafling** [comment]
Il y a des problèmes sur la carte des niveaux dans Doom (version jap) : depuis la v1.6.0, il manque de nombreux segments et des pixels dans les segments affichés. Ici, la carte du niveau 25 Perfect hatred (presque injouable sur console, ça lag moins dans Kronos 👍 ) :

![Capture_doom_map_perfect_hatred_WIP](https://user-images.githubusercontent.com/7624262/56935053-067b9080-6aef-11e9-8842-9d841b913a5c.PNG)

Affichage impec en v1.5.0 :

![Capture_doom_map_perfect_hatred](https://user-images.githubusercontent.com/7624262/56935067-18f5ca00-6aef-11e9-901f-9194fcc98bcf.PNG)

Le save state (compatible v1.5.0 et WIP, re 👍 , appuyer sur Z pour afficher la carte) :

[doom_perfect_hatred.zip](https://github.com/FCare/Kronos/files/3129601/doom_perfect_hatred.zip)

**Comment by fafling** [comment]
Même problème dans les jeux Battlezone et Tempest dans The Atari Collection (version euro).

**Comment by fafling** [comment]
L'affichage des 3 jeux est OK en WIP du 07/05.

**Comment by FCare** [comment]
Fixé aujourd'hui. Merci de verifier de votre coté :-)
