### ISSUE TITLE
[Guardian Heroes] Transparence additive incorrecte

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#478]
En version WIP du 07/05, les sprites semi-transparents sont rendus avec un effet de demi-transparence (version US du jeu) :

![Capture_guardian_heroes_debut_WIP20190507](https://user-images.githubusercontent.com/7624262/57262249-abf0b000-706b-11e9-9d65-a6376bcf9c88.PNG)

C'est incorrect car Guardian Rangers utilise le mode de color calculation additive du VDP2, il y a donc saturation des pixels concernés quand le sprite est de couleur vive, et au contraire moins d'effet plus le pixel du sprite est foncé. L'affichage en v1.6.0 est correct :

![Capture_guardian_heroes_debut_1 6 0](https://user-images.githubusercontent.com/7624262/57262283-cdea3280-706b-11e9-8250-d4c1ac7b1923.PNG)

Le problème apparaît dans la WIP du 17/03. Même comportement en bios réel et bios émulé. Problème similaire à celui de Burning Rangers #468 pour le rendu des effets de transparence par le VDP2.

Les captures sont prises sur la 1ère scène après le dialogue. Maintenir R enfoncé et appuyer sur C pour faire défiler le dialogue rapidement. Malheureusement, les save states ne semblent pas fonctionner pour ce jeu.

**Comment by FCare** [comment]
fixé aujourd'hui. J'espere qu''il n'ya pas de regresions...

**Comment by fafling** [comment]
C'est mieux , mais l'effet de transparence est cette fois trop faible car il y a encore un coefficient appliqué sur les pixels de la "second image", voir commentaire sur le commit bed996f99c815de5d867378239538b7ac85dd47c.
![Capture_guardian_heroes_20190507](https://user-images.githubusercontent.com/7624262/57336267-9344d080-7125-11e9-945c-b5eeb1d4960b.PNG)

**Comment by FCare** [comment]
La je ne comprends pas ta remarque... Il faut de la transparence ou pas du tout?

**Comment by barbudreadmon** [comment]
Si je comprend bien la phrase de la doc ainsi que la trad de @nicolas-charrier, j'imagine que la ligne est censé ressembler à çà ?
```
"  finalColor = vec4( topImage.rgb + secondImage.rgb, 1.0); \n"
```

**Comment by FCare** [comment]
En fait, on va avoir:

"  if (modetop == 1) topImage = vec4(colortop.rgb, 1.0); \n"
"  if (modetop == 2) topImage = vec4(colortop.rgb, 0.0); \n"
"  if (modetop == 3) topImage = vec4(colortop.rgb*alphatop, alphatop); \n"
"  if (modetop == 4) topImage = vec4(colortop.rgb*alphasecond,
alphasecond); \n"

"  finalColor = vec4( topImage.rgb + (1.0 - topImage.a) * secondImage.rgb,
1.0); \n"

et pour mx4, au lieu d'etre en modetop = 2, on sera en modetop = 1 avec la
colorcalculation et ca devrait le faire...

Le mer. 8 mai 2019 à 10:39, barbudreadmon <notifications@github.com> a
écrit :

**Comment by fafling** [comment]
En WIP du 08/05, c'est OK.
