### ISSUE TITLE
[Bug too] Problème sur le menu pause (écran agrandie)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#479]
Kronos du 07.05.2019 :

Quand on appuie sur pause, l'écran s'élargit d'1 pixel ?!? vers le haut et le bas, et la gauche et la droite.

![bugtoo](https://user-images.githubusercontent.com/12481242/57337207-cccb0b00-7128-11e9-9114-db54990047bd.PNG)
![bugtoopause](https://user-images.githubusercontent.com/12481242/57337208-cccb0b00-7128-11e9-9cfd-e4673bf5a5cf.PNG)

**Comment by fafling** [comment]
Il y a un léger zoom sur la texture copiée à partir du framebuffer quand on met en pause. La texture copiée à partir du framebuffer est correcte (sans aucun zoom) dans l'écran debug du VDP1. La commande de dessin n'effectue aucun zoom sur la texture. C'est peut-être lié aux tailles de sprites trop grandes détectées dans le HUD de Krazy Ivan.

![Capture_bug_too_opengl_ori](https://user-images.githubusercontent.com/7624262/56813871-33ede300-683e-11e9-841b-0984038ab74e.PNG)

![Capture_bug_too_opengl_ori_2](https://user-images.githubusercontent.com/7624262/56813882-36503d00-683e-11e9-8f67-3fbadca9dc83.PNG)

Texture complète du framebuffer exportée avec l'écran debug du VDP1. En comparant cette texture et ce qu'affiche Kronos, je remarque que l'image est toujours tronquée en haut et en bas de 3 à 4 pixels et sur les côtés de 4 à 5 pixels. Ces pixels sont affichés par la console.
![VDP1_bug_too_pause](https://user-images.githubusercontent.com/7624262/56813987-6e578000-683e-11e9-8e65-751922085942.png)

Apparemment c'est dû à l'overscan style CRT introduit par 09fe6d9e28024dddb49eb2850a13df0fd4b4838a. Cet effet devrait être facultatif et activé par une option, comme pour les scanlines ou l'aspect ratio.

Un save state pour aller plus rapidement dans le jeu :

[bug_too_level_select.zip](https://github.com/FCare/Kronos/files/3121641/bug_too_level_select.zip)

**Comment by fafling** [comment]
Le fix sur Krazy Ivan ( #463 ) n'a pas résolu le problème des distorted sprites rectangulaires trop gros quand le HSS (high speed shrink) n'est pas activé. C'est le cas du dessin du menu pause de bug too, et on le voit aussi dans le texte des fenêtres de Shining Force 3 :

![Capture_sf3_taille_sprites](https://user-images.githubusercontent.com/7624262/57660336-6e999e80-75e6-11e9-84eb-e549915a5f78.PNG)

Il devrait y avoir 2 pixels entre les chiffres 6 et 7 en haut à droite, or Kronos les représente collés :

![Capture_sf3_taille_sprites_6](https://user-images.githubusercontent.com/7624262/57660400-b9b3b180-75e6-11e9-8377-479bfdc42db9.PNG)

![Capture_sf3_taille_sprites_7](https://user-images.githubusercontent.com/7624262/57660407-bf10fc00-75e6-11e9-8256-51827273358d.PNG)

Un save state (à charger à l'écran "Now loading" qui débute le jeu, après il ne fonctionne pas) :

[sf3_taille_sprites.zip](https://github.com/FCare/Kronos/files/3175167/sf3_taille_sprites.zip)

**Comment by fafling** [comment]
En WIP du 15/05, l'overscan est supprimé.

**Comment by BenjaminSiskoo** [comment]
Avec la WIP 7, plus de soucis sur Bug

**Comment by fafling** [comment]
Je confirme, et c'est aussi correct pour les textes dans Shining Force 3.

**Comment by BenjaminSiskoo** [comment]
On ferme :)
