### ISSUE TITLE
Corruption de textures avec tesselation "Triangles using perspective correction"

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#481]
Je donne l'exemple de Quake parce que c'est le plus flagrant, mais je pense que c'est un problème général car je l'ai vu aussi dans Daytona USA et Virtual Hydlide.

Suite au fix du mode de tesselation "Triangles using perspective correction" pour corriger le problème de zig-zags ( #414 ), des textures de polygones sont corrompues dans ce mode en WIP du 08/05. Elles affichent de manière intermittente un motif en triangle, principalement sur la gauche de l'écran. Le problème n'existe que dans ce mode de tesselation.

Dans le niveau de sélection de Quake (version US) :
![Capture_quake_bug_fix_triangle_20190508_2](https://user-images.githubusercontent.com/7624262/57413176-81c9fa00-71f3-11e9-97ec-837506e4c834.PNG)

Il n'y a pas de corruption de la texture dans l'écran debug du VDP1.

Le problème ne se produit pas dans la WIP précédente. Il existe avec le bios réel et le bios émulé.

Un save state pour aller plus vite dans le jeu (il suffit de se promener dans la salle pour reproduire) :
[quake_début.zip](https://github.com/FCare/Kronos/files/3159548/quake_debut.zip)

**Comment by BenjaminSiskoo** [comment]
J'ai vu ca aussi sur l'écran press start screen de Krazy Ivan.

**Comment by barbudreadmon** [comment]
J'ai vu des choses similaires sur Shining Force 3 en le re-testant ce matin.

**Comment by fafling** [comment]
Dans l'avant-dernière WIP du 12/05, retour du fix pour les zig-zag, il reste quelques corruptions de textures intermittentes dans Quake, mais beaucoup moins que la 1ère fois.

Par contre, je remarque un problème dans Mystaria de déformation permanente sur des polygones pincés pour former des triangles pour le toit des tours du château de l'intro. Malheureusement, je crois qu'il s'agit du talon d'Achille de la correction de perspective, vu qu'elle doit être basée sur le pincement des polygones, le VDP1 n'ayant pas de coordonnée de profondeur. Si des polygones sont pincés de part leur modélisation (trapèzes ou triangles), leur texture va subir une correction permanente, d'autant plus prononcée que le pincement est fort (les triangles étant le cas extrême).

![Capture_mystaria_fix_zizag](https://user-images.githubusercontent.com/7624262/57601169-0ef6b100-755c-11e9-9eae-125663452a65.PNG)

Sans le fix :

![Capture_mystaria_fix_zizag_OK](https://user-images.githubusercontent.com/7624262/57601190-1fa72700-755c-11e9-8566-185354bbadf4.PNG)

Les coordonnées d'une commande :

![Capture_mystaria_fix_zizag_VDP1](https://user-images.githubusercontent.com/7624262/57601215-2e8dd980-755c-11e9-9394-5962164b5713.PNG)

Un save state pour y aller un peu plus rapidement (à charger après avoir fait new game sur l'écran titre, sinon marche pas) :

[mystaria_fix_zizag.zip](https://github.com/FCare/Kronos/files/3171448/mystaria_fix_zizag.zip)

**Comment by BenjaminSiskoo** [comment]
J'ai cru voir ce type de problème sur Tomb Raider hier

**Comment by fafling** [comment]
Effectivement, Tomb raider utilise des polygones triangulaires dont la texture est déformée en permanence. Il y a aussi pas mal de corruption intermittente, plus que dans Quake. Une corruption permanente (polygone non triangulaire) est visible dans le menu de l'écran titre quand le passeport est ouvrert :
![Capture_tomb_raider_carnet](https://user-images.githubusercontent.com/7624262/57812871-99166380-776e-11e9-95c9-7d261c867856.PNG)

![Capture_tomb_raider_carnet_VDP1](https://user-images.githubusercontent.com/7624262/57812864-9582dc80-776e-11e9-9f89-d5f474397cb0.PNG)

**Comment by FCare** [comment]
Tu peux reverifer? Je ne l'ai plus chez moi

**Comment by fafling** [comment]
Dans la dernière WIP, les corruptions permanentes sont corrigées dans Tomb Raider et Mystaria.
Par contre, les corruptions intermittentes sont redevenues fréquentes dans Quake.

**Comment by fafling** [comment]
Corruption avec les triangles sur le logo Police de l'hélico dans l'intro (la corruption disparaît avec un autre mode de tessellation) :
![Capture_die_hard_arcade_helico](https://user-images.githubusercontent.com/7624262/58125110-1da22f80-7c10-11e9-882e-a8ce1717a4c6.PNG)

Le bas du logo est dessiné avec 2 textures très allongées (96 x 3 pixels) :
![Capture_die_hard_arcade_helico_VDP1](https://user-images.githubusercontent.com/7624262/58125186-49bdb080-7c10-11e9-8702-9703964e5046.PNG)

**Comment by BenjaminSiskoo** [comment]
Dir hard arcade est ok maintenant, @nicolas-charrier tu peux confirmer que je puiss fermer le bug report ?

**Comment by BenjaminSiskoo** [comment]
Toujours le même problème pour Die Hard Arcade avec Kronos 1.7.0 Wip du 10.06.2019 et l'option triangles using…

**Comment by fafling** [comment]
Ce problème ne concerne que le noyau OpenGL.

**Comment by fafling** [comment]
Toujours présent en WIP du 01/12.

**Comment by fafling** [comment]
Core OpenGL abandonné.
