### ISSUE TITLE
[The Need For Speed] Freeze temporaire de Kronos en noyau OpenGL en extui-align

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#482]
En WIP du 09/05, et depuis celle du 26/04, Kronos freeze en fin de video d'intro (ou bien si on appuie sur start avant).
Même chose avec en bios réel ou émulé.
Je teste avec la version US du jeu.

@BenjaminSiskoo Est-ce que tu peux tester avec la version jap, Nissan Presents - Over Drivin' GT-R ?

**Comment by BenjaminSiskoo** [comment]
@nicolas-charrier même comportement

**Comment by fafling** [comment]
J'ai toujours un écran noir et blocage de l'interface au lieu d'afficher l'écran de loading :
![Capture](https://user-images.githubusercontent.com/7624262/57489887-b99a7580-72b7-11e9-9ff7-5cbaf3983490.PNG)

**Comment by fafling** [comment]
Il s'agit en fait d'un freeze temporaire qui dure environ 2 mn sur mon PC. La durée peut varier si on utilise une autre application en même temps.
Il y a aussi 2 freezes successifs quand on lance ensuite une partie, qui durent chacun environ 1 mn 30 s.
Ce comportement est présent en v1.7.0 publique.
Depuis la WIP du 29/08, ce problème est réglé en noyau compute shader. Il n'existe plus qu'en noyau OpenGL.

**Comment by fafling** [comment]
Réglé en WIP accurate_vdp1 du 01/10.

**Comment by fafling** [comment]
Fixé dans les 2 noyaux en WIP extui-align du 19/11.
