### ISSUE TITLE
Kronos 1.6.0 crash (i can't initialing yabause)

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#483]
Hi,

Config system :

AMD Athlon II X2 P360
8 Go DDR3
AMD (ATI) Radeon HD 4200
Windows 7 Pro 64 bits
Direct X 10
OpenGL 3.3

**Comment by fafling** [comment]
I reproduce this message in v1.6.0 with those settings :
- General>bios set to "Enable bios emulation"
- Cart/Memory>Memory set to the same value as the same setting in Yaba Sanshiro (for exemple the default value C:/Users/\<username>/AppData/Local/yabause/bkram.bin)
- In Yaba Sanshiro, setting Cart/Memory>"Extend internal backup memory to 8MB" is ticked.

When starting emulation without a CD mounted, Kronos displays "Can't initialize Yabause" dialog.
If the log window is enabled, it displays "Internal backup file format is detected as extended save format - Force to use extended save format".
When using a real bios, it just displays this message in the log window and runs the bios.

In both case, when running Quake, the game displays a dialog saying "Save file cannot be read, delete it?" if a save was created with Yaba Sanshiro beforehand.

This is tested with Yaba Sanshiro 2.5 Alpha.
Kronos latest WIP also displays "Can't initialize Yabause" with those settings, however the log window doesn't work.

**Comment by fafling** [comment]
Correction : "Can't initialize Yabause" is displayed when emulated bios is used without CD mounted. This is independent of a conflict with Yaba Sanshiro over backup RAM format.

In the last WIP, the default directory is changed to C:/Users/\<username>/AppData/Local/kronos to avoid conflict with Yaba Sanshiro or Yabause (commit 6058019).

**Comment by FCare** [comment]
Hi,

The emulated bios is not totally functional. Many bios services are not
emulated or not well emulated. Always prefer a real Bios image if you have
one.

Le sam. 18 mai 2019 à 12:34, nicolas-charrier <notifications@github.com> a
écrit :

**Comment by FCare** [comment]
Also the backup ram file is not compatible with yabause one. It might be compatible with mednafen one so please, use a dedicated bram file for kronos
