### ISSUE TITLE
[Jikkyou Oshaberi Parodius - Forever With Me] Transparence incorrecte au menu de l'écran titre

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#485]
En WIP du 09/05, la fenêtre du menu de l'écran titre désactive la transparence additive du NBG2 par rapport au NBG1.

![Capture_parodius_forever](https://user-images.githubusercontent.com/7624262/57569644-3fbdd580-73f8-11e9-8cf2-11429a1b04da.PNG)

Sur la console, l'effet de transparence additive a lieu aussi derrière la fenêtre :
[https://youtu.be/uFstPageTKs?t=199](https://youtu.be/uFstPageTKs?t=199)

La fenêtre est dessinée par le VDP1 avec un polygone :

![Capture_parodius_forever_VDP1](https://user-images.githubusercontent.com/7624262/57569691-06d23080-73f9-11e9-9388-2aa9343bcd5e.PNG)

Il n'y a rien de marqué dans l'écran debug du VDP2, mais la fenêtre est certainement une normal shadow, car elle est devenue semi-transparence avec le fix de la normal shadow pour Guardian Heroes.

![Capture_parodius_forever_VDP2](https://user-images.githubusercontent.com/7624262/57569707-397c2900-73f9-11e9-8a24-9727c953c705.PNG)

Si c'est bien une normal shadow, elle ne doit pas être considérée comme une couche supplémentaire dans la color calculation. Pour la color calculation, les pixels du framebuffer qui portent le code de la normal shadow sont transparents. Le traitement de shadow du VDP2 est effectué après la color calculation.

**Comment by fafling** [comment]
Le problème est identique en bios réel et émulé.
Un save state pour aller plus vite à l'écran titre :
[parodius_forever_écran_titre_bios_jap.zip](https://github.com/FCare/Kronos/files/3169024/parodius_forever_ecran_titre_bios_jap.zip)

**Comment by FCare** [comment]
La normal shadow a ete fixée :-)

**Comment by fafling** [comment]
@FCare Chez moi, le fix rend la normal shadow opaque, alors qu'il fonctionne pour @BenjaminSiskoo . J'ai testé avec une installation de Kronos dans un autre répertoire, ça ne change rien.
![Capture_parodius_shadow_opaque_20190515](https://user-images.githubusercontent.com/7624262/57802275-e0dcc100-7755-11e9-8e45-10c82d33cb68.PNG)

La normal shadow est aussi devenue opaque dans Guardian Heroes.
![Capture_guardian_heroes_shadow_opaque_20190515](https://user-images.githubusercontent.com/7624262/57802286-e508de80-7755-11e9-8929-d83a43d97407.PNG)

**Comment by barbudreadmon** [comment]
J'ai également cette opacité

**Comment by fafling** [comment]
@FCare Est-ce que tu peux rouvrir cette fiche ? Il y a un comportement différent chez @BenjaminSiskoo (carte ATI) qui voit la normal shadow translucide, et chez @barbudreadmon et moi (carte Nvidia) qui la voyons opaque.

**Comment by FCare** [comment]
Je la vois translucide sur mon intel graphics.

**Comment by fafling** [comment]
Même problème dans les 2 WIP d'aujourd'hui.

**Comment by FCare** [comment]
Vous pouvez tester a nouveau? je pense que l'un d'entre vous etait en GPu tesselation.

**Comment by BenjaminSiskoo** [comment]
Pas de soucis chez moi

**Comment by fafling** [comment]
La normal shadow opaque est indépendante du mode de tesselation.
J'ai toujours le problème en v1.7.0 publique.

Le problème est présent aussi dans Decathlete sur les ombres des persos : elles sont devenues semi-transparentes en WIP du 07/05 et redevenues opaques le 12/05, mêmes dates que les autres jeux. Elles utilisent donc sûrement la normal shadow, même si, de même que pour Parodius, l'utilisation de la normal shadow n'est pas indiquée dans l'écran debug du VDP2.

En v1.7.0 publique :
![Capture_decathlete_normal_shadow_opaque_1 7 0](https://user-images.githubusercontent.com/7624262/59313923-318efd80-8cb3-11e9-87f6-93299a0c1e24.PNG)

Ombre correcte en WIP du 7 au 12 mai :
![Capture_decathlete_normal_shadow_opaque_20190512_4](https://user-images.githubusercontent.com/7624262/59313948-51262600-8cb3-11e9-9129-db750044cdb4.PNG)

**Comment by fafling** [comment]
Problème fixé par la WIP rasterizer, la normal shadow n'est plus opaque sur les matériels Nvidia.
