### ISSUE TITLE
With Autostart Glew can not init

### ISSUE THREAD

**Issue by cyberconan** [FCare/Kronos#486]
Hi!
I compiled last git version in linux and when I'll use autostart (from command line with -a or with .ini setting) always show an error with "Glew can not init". With windows version under Wine I showed same error. Can be fixed easily?
Thanks!

**Comment by FCare** [comment]
Hi, the linux simple client is used for some debugging. Not sure it is
fonctional. It should be better to use the retrolib version or the qt port.
