### ISSUE TITLE
Nights ne demarre plus

### ISSUE THREAD

**Issue by FCare** [FCare/Kronos#489]

**Comment by fafling** [comment]
Il marche avec la WIP de dimanche soir (version US), ça doit venir d'un changement récent.

**Comment by barbudreadmon** [comment]
Pareil sur toutes les versions visiblement, y compris les versions "Christmas" (qui affichent néanmoins l'écran du choix de date correctement, mais écran noir ensuite).

**Comment by barbudreadmon** [comment]
Rectification, toutes les versions de nights fonctionnent chez moi, il faut juste skip l'intro en appuyant sur start. Par contre je ne sais pas depuis combien de temps c'est comme çà, il semble que le problème était déjà présent juste après que rework soit merge dans master, çà ressemble au problème dans deep fear.

Edit : Problème déjà présent en 1.6.0 d'après mes tests, je ne pense pas que çà sert à quelque chose que je remonte encore plus loin.

**Comment by fafling** [comment]
Pas de problème de démarrage chez moi en WIP du 08/12.
