### ISSUE TITLE
[Shining Force 3] Trous entre polygones 

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#490]
Le 1er fix pour corriger les distorted sprites rectangulaires trop gros ( #463 ) (fix qui les représentait trop petits) a introduit un rétrécissement sur des distorted sprites non rectangulaires qui laisse des trous entre polygones dans Shining Force 3. Le fix suivant qui représente correctement les distorted sprites rectangulaires avec HSS a laissé ce rétrécissement.

![Capture_sf3_taille_sprites](https://user-images.githubusercontent.com/7624262/57660761-68a4bd00-75e8-11e9-9958-c18d3741f20d.PNG)

Les commandes concernées utilisent le HSS.

Un save state (à charger à l'écran "Now loading" qui débute le jeu, après il ne fonctionne pas) :

[sf3_taille_sprites.zip](https://github.com/FCare/Kronos/files/3175167/sf3_taille_sprites.zip)

**Comment by barbudreadmon** [comment]
> Un save state (à charger à l'écran "Now loading" qui débute le jeu, après il ne fonctionne pas)

Ok, merci pour l'info, çà explique pourquoi je ne réussissais pas à les faire fonctionner.

**Comment by fafling** [comment]
Dans la dernière WIP, l'expansion semble avoir été remise sur les distorted sprites non rectangulaires, je ne vois plus de trous. @FCare Est-ce que tu confirmes ?

**Comment by fafling** [comment]
Les trous sont de retour en mode de tesselation CPU et GPU suite à la désactivation de l'expansion des polygones non rectangulaires dans ces modes (commit 82422ac ).

**Comment by FCare** [comment]
Ok, j'ai fait un revert sur le patch.

Le jeu. 23 mai 2019 à 03:15, nicolas-charrier <notifications@github.com> a
écrit :

**Comment by fafling** [comment]
Problème réglé dans tous les modes de tesselation dans la dernière WIP.
![Capture](https://user-images.githubusercontent.com/7624262/58275245-e01adf00-7d94-11e9-8d6c-f37028eeebeb.PNG)
