### ISSUE TITLE
[Shining Force 3] Divers soucis de rendu

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#491]
Testé avec la fantrad du scenario 1 par Shining Force Central, comparé avec mednafen : 
**Avec Kronos**
![Shining Force III - Scenario 1 - The Titan of Aspia (USA)  T-En by Shining Force Central v13   n -190514-103205](https://user-images.githubusercontent.com/10391265/57684032-3e2d2100-7635-11e9-9a59-bc834b1e5c18.png)
![Shining Force III - Scenario 1 - The Titan of Aspia (USA)  T-En by Shining Force Central v13   n -190514-103237](https://user-images.githubusercontent.com/10391265/57684035-408f7b00-7635-11e9-9168-fea3767ba388.png)
![Shining Force III - Scenario 1 - The Titan of Aspia (USA)  T-En by Shining Force Central v13   n -190514-103745](https://user-images.githubusercontent.com/10391265/57684347-e80cad80-7635-11e9-9c8c-8101258761d8.png)

**Avec Mednafen**
![Shining Force III - Scenario 1 - The Titan of Aspia (USA)  T-En by Shining Force Central v13   n -190514-103413](https://user-images.githubusercontent.com/10391265/57684064-53a24b00-7635-11e9-8792-2829a20a9ffa.png)
![Shining Force III - Scenario 1 - The Titan of Aspia (USA)  T-En by Shining Force Central v13   n -190514-103432](https://user-images.githubusercontent.com/10391265/57684071-58ff9580-7635-11e9-8ec0-f973d92b9cca.png)
![Shining Force III - Scenario 1 - The Titan of Aspia (USA)  T-En by Shining Force Central v13   n -190514-103616](https://user-images.githubusercontent.com/10391265/57684384-f955ba00-7635-11e9-8627-7cfd9d56487f.png)

Sur les 2 premiers screenshots, on remarque qu'il y a des choses tronquées à gauche et à droite, non seulement vis à vis de l'écriture mais aussi sur l'image d'arrière plan de l'écran titre.
Sur le 3ème screenshot, il y a des gros soucis de netteté sur les textes, si on upscale çà va mieux mais on se retrouve avec un problème sur les fonds des panneaux : 
![Shining Force III - Scenario 1 - The Titan of Aspia (USA)  T-En by Shining Force Central v13   n -190514-105112](https://user-images.githubusercontent.com/10391265/57685211-ba286880-7637-11e9-986f-18bed918ba49.png)

Screenshots sans upscaling hormis le dernier, pris avec le port libretro, tout se passe avant de lancer une partie donc pas besoin de savestate.

**Comment by CloudFR** [comment]
Ce sont des réglages vidéos à ajuster dans kronos, si tu as modifié opengl size à partir de 2X ça zoom automatiquement et donc les textes sont pixélisés et ça déborde sur les cotés.

Alors qu'au contraire mednafen emule la config de la saturn, c'est à dire tout dégueulasse, pixélisé et la 3d polygonisé.

Le prob avec SF3 c'est qu'il y a à la fois de la 2D et de la 3D, et je n'ai pas trouvé comment peaufiné les deux à la fois.

J'ai fais des dizaines et des dizaines de bench sur différents réglages pour avoir SF3 le plus jolie possible (HD LIKE).

Perso ma config est :

core opengl
software osd
strech to windows
start in fullscreen

upscale filter : rien
embellishement filter : rien
opengl size : 16X (si ton PC le permet) sinon 4X c'est déjà 4X mieux ;)
tesselation : par defaut

juste de 4X à 16X opengl size les lignes 3D sont vraiment plus jolie, les bords moins pixélisé et dégueulasse comme medfaden

**Comment by fafling** [comment]
Le troncage du tour de l'écran est dû à l'overscan style CRT introduit par 09fe6d9e28024dddb49eb2850a13df0fd4b4838a, repéré aussi sur Bug too #479. 
@FCare Faudrait vraiment le rendre optionnel, sinon les joueurs vont se demander pourquoi Kronos tronque l'image.

Les commandes VDP1 de dessin des lettres ne font aucun zoom ni distortion sur la texture. L'affichage irrégulier du texte est dû à l'expansion par Kronos des distorted sprites pour éviter des trous entre les jointures de polygones. Il y a eu un patch récemment qui a désactivé en partie cette expansion, normalement uniquement sur les sprites rectangulaires (mais pas que #490 ), mais l'expansion a toujours lieu quand le high speed shrink du VDP1 est désactivé comme dans Shining Force 3 (problème décrit ici #479 ).

**Comment by fafling** [comment]
Le troncage est supprimé par 4f161d3 .

**Comment by barbudreadmon** [comment]
Je confirme, vu que le problème restant est déjà mentionné dans #479, je clos celle-ci.
