### ISSUE TITLE
[Virtua Fighter 2] Graphismes manquants

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#492]
Le jeu fonctionnait plutôt bien il y a quelques mois, désormais le menu de sélection de personnage n'est plus très utilisable : 
![Virtua Fighter 2 (USA)-190514-124302](https://user-images.githubusercontent.com/10391265/57692205-7e48cf80-7646-11e9-880a-fca9c9ffbf80.png)
 
Chose étrange, le ciel disparaît dans l'attract mode si on revient à l'écran d’accueil après être allé dans le menu de sélection de perso :

![Virtua Fighter 2 (USA)-190514-124530](https://user-images.githubusercontent.com/10391265/57692337-cff15a00-7646-11e9-9633-34562c96702e.png)

Si on laisse l'attract mode tourner avant d'aller dans le menu de sélection, il ne semble pas qu'il y ait ce problème.

En match le problème du ciel noir est systématique (logique je suppose vu que c'est l'écran de sélection de perso qui semble "corrompre" quelque chose)

Le bug m'a été signalé dans https://github.com/libretro/yabause/issues/69

Comme pour l'issue sur SF3 : screenshots sans upscaling, avec le port libretro, et tout se passe dans les menus du début donc pas besoin de savestate.

**Comment by fafling** [comment]
Je ne reproduit pas ce problème sur le ciel pendant un combat en WIP du 12/05 sans manip spécifique :
- Avec OpenGL size 1x, le ciel ne disparaît que si je change l'OpenGL size pendant un combat.
- Avec OpenGL size 2x, le ciel disparaît aussi si je pause l'émulation puis sort de pause, ou si j'affiche une fenêtre du menu (settings, écrans debug…) et que je la ferme.

De même, je ne reproduit le problème sur le menu de sélection de personnage que si je change d'OpenGL size quand il est affiché.

J'ai vu une corruption du menu de l'écran titre en OpenGL 2x :
![Capture_VF2](https://user-images.githubusercontent.com/7624262/57738714-e92ef080-76b0-11e9-8bda-581ccca54356.PNG)

Affichage correct en OpenGL 1x :
![Capture_VF2_1x](https://user-images.githubusercontent.com/7624262/57738755-14194480-76b1-11e9-9fb9-bc4b070316e0.PNG)

Le texte corrompu est affiché par le NBG1 (peut-être un problème de fenêtre, il y en a une d'activée) :
![Capture_VF2_VDP2](https://user-images.githubusercontent.com/7624262/57738869-8f7af600-76b1-11e9-9c20-6d99a9cc2cd8.PNG)

Testé avec le CD version US et vrai bios.

**Comment by barbudreadmon** [comment]
> De même, je ne reproduit le problème sur le menu de sélection de personnage que si je change d'OpenGL size quand il est affiché.

Intéressant, il semble en effet que ce soit les multiples appels à `VIDCore->SetSettingValue(VDP_SETTING_RESOLUTION_MODE, value);` dans le port libretro qui causent le problème, et ceci alors même que `value` est toujours à 1. @FCare J'ai balancé un PR (https://github.com/FCare/Kronos/pull/493) mais je ne suis pas certain que ce soit la meilleure façon de régler le problème ?

**Comment by barbudreadmon** [comment]
> Le texte corrompu est affiché par le NBG1 (peut-être un problème de fenêtre, il y en a une d'activée)

Vu avec @FCare, il semble effectivement probable qu'il y ait un problème de fenêtre sur le NBG1 dans VF2

**Comment by barbudreadmon** [comment]
Le bug du ciel manquant et de la sélection des persos quand l'opengl size change (ou pas d'ailleurs) a été corrigé dans https://github.com/FCare/Kronos/commit/6ca53af928cddc137da2f5e3590c27fd6bf57331

**Comment by fafling** [comment]
Je confirme, le ciel et l'arrière-plan de la sélection des persos ne disparaissent plus en WIP du 15/05.

**Comment by fafling** [comment]
La corruption du texte du menu est corrigé en WIP du 16/05.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 15 Mai 2019
