### ISSUE TITLE
Comment compiler la dernière version de kronos ?

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#494]
Bonjour,

Peut-on compiler la dernier version de kronos ainsi que les patchs en cours sur le github pour windows ?

Si oui comment, car j'ai essayé d'utiliser la méthode de yabause ici :
https://wiki.yabause.org/index.php5?title=Readme_QT

Mais cela ne fonctionne pas sur deux PC différent, il y a une erreur à chaque fois pendant le processus à partir de la ligne cmake -G"MSYS Makefiles" ../Kronos/yabause

**Comment by BenjaminSiskoo** [comment]
Bonjour, 

J'essaye de faire ca ce WE ou le WE prochain (si le we prochain c'est pas fait, redis le moi).

**Comment by CloudFR** [comment]
Bonjour, y a t il une nouvelle version ?
Je lis souvent "dernière version de WIP" et des screenshot ayant la version 1.7.0 mais je ne sais pas où le télécharger ?

**Comment by FCare** [comment]
Seules les versions officielles sont publiquement partagées. Les wip dont
tu vois les messages sont des versions intermediaires que certains
compilent eux mêmes et s'echangent ensuite.

**Comment by CloudFR** [comment]
merci pour ta réponse, mais comment vous faites pour compiler ? il y a un tuto quelque part que je puisse lire pour le faire chez moi ?

**Comment by CloudFR** [comment]
Bonsoir y a t il une WIP de dispo pour une nouvelle version 1.7.0+ ?

**Comment by BenjaminSiskoo** [comment]
La version 2.0.1 est sortie sur www.tradu-france.com

**Comment by CloudFR** [comment]
Ok car je ne vois jamais sur le site la nouvelle release, ni dans le github... bravo pour votre travail !

**Comment by BenjaminSiskoo** [comment]
Merci :)
