### ISSUE TITLE
[Decathlete / Athlete Kings] Barre noire à l'écran titre et variation du haut de l'écran

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#497]
A l'écran titre une barre noire apparaît à droite de l'écran sur le ciel quand le fondu avec le logo commence. Le problème est absent dans la WIP du 21/04 et apparaît dans celle du 26/04.

![Capture_decathlete_bordure_noire_titre](https://user-images.githubusercontent.com/7624262/56822659-06129980-6852-11e9-8fcf-727bd858511a.PNG)

Comme vu par @barbudreadmon , le haut de l'écran monte et descend. Ce problème existait déjà en v1.5.0.

[Athlete_Kings_Europe-190515-090118.mkv.zip](https://github.com/FCare/Kronos/files/3188639/Athlete_Kings_Europe-190515-090118.mkv.zip)

**Comment by FCare** [comment]
J'ai plus la barre sur le coté dans la version d'aujourd'hui. Vous pouvez metre a jur avec ce que vous voyez chez vous?

**Comment by fafling** [comment]
Elle est toujours là dans la WIP de cet après-midi.
Dans la release x86 de ce soir, elle se met en haut de l'écran :
![Capture_Decathlete_release_20190517](https://user-images.githubusercontent.com/7624262/57957552-f6401f80-78fc-11e9-80f7-7ef75a88ee17.PNG)

**Comment by FCare** [comment]
Je viens de tester sous windows intel et AMD, pas de soucis chez moi. Sous linux non plus...

**Comment by fafling** [comment]
Peut-être encore un problème spécifique aux cartes Nvidia, faut voir ce qu'en disent @BenjaminSiskoo  et @barbudreadmon.

Je ne sais pas si ça peut avoir un lien, mais toutes les couches du VDP2 sont affichées à l'intérieur d'une line window.
![Capture_decathlete_VDP2](https://user-images.githubusercontent.com/7624262/57973580-4b3a6f00-79ab-11e9-9299-d5fa947da62d.PNG)

**Comment by FCare** [comment]
Vous pouvez regarder sur Mednafen si ca clignote en haut?

**Comment by BenjaminSiskoo** [comment]
Pas de soucis avec mednafen on voit des bandes noires au dessus et en dessous : 

![ak](https://user-images.githubusercontent.com/12481242/58037191-2837c880-7b2d-11e9-80a0-1c4f02eba29e.PNG)

Quand j'appuie sur start, j'ai ca (des bandes noires) :

![ak1](https://user-images.githubusercontent.com/12481242/58037416-b0b66900-7b2d-11e9-8df0-e2baf16c1b5e.PNG)

**Comment by fafling** [comment]
Sur la console, le haut de l'écran est bien fixe.
Peut-être une mauvaise prise en compte du double interlace dans le code de Kronos qui gère la line window.
P. 185 de la doc VDP2, la table de la line window stocke les lignes de 2 champs successifs en double interlace.
Elle est 2 fois plus grosse qu'en single interlace ou en progressif, faut lire une ligne sur 2 pour un champ.

**Comment by fafling** [comment]
La variation en haut de l'écran est toujours présente par moment en WIP du 19/11 dans les 2 noyaux.

**Comment by fafling** [comment]
Fixé en WIP du 26/11 par 03eb218
