### ISSUE TITLE
[Quake] Ecrans de logo et de chargement manquants

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#498]
En WIP du 16/05, seul le 1er écran avec le symbole de Quake est affiché. Le 2ème logo Quake avec les infos de trademark n'apparaît pas, au lieu de ça Kronos affiche le 1er logo avec des couleurs corrompues, ou bien le ciel.
![Capture_quake_ecran_logo_corrompu](https://user-images.githubusercontent.com/7624262/57885917-574bf280-782c-11e9-878c-4792b4df837f.PNG)

![Capture_quake_ecran_logo_ciel](https://user-images.githubusercontent.com/7624262/57886015-91b58f80-782c-11e9-82a7-ccf7b3f7f00b.PNG)

Affichage correct :
![Capture_quake_ecran_logo_youtube](https://user-images.githubusercontent.com/7624262/57885934-60d55a80-782c-11e9-883b-ccfb9190b104.PNG)

Même problème pour les écrans de chargement qui n'affichent que la barre de chargement :
![Capture_quake_ecran_logo_chargement](https://user-images.githubusercontent.com/7624262/57886281-24eec500-782d-11e9-9e45-42937bd97248.PNG)

Affichage correct pour le 1er ecran de chargement quand on fait "New Game" :
![Capture_quake_ecran_logo_youtube2](https://user-images.githubusercontent.com/7624262/57886321-38019500-782d-11e9-9115-e170b11565ca.PNG)

Dans l'écran débug du VDP2, soit les autres couches n'apparaissent pas pendant ces écrans, soit le RBG0 affiche le ciel et le NBG0 n'affiche rien (une fenêtre le masque complètement).
Sur le 1er et seul logo qui s'affiche, impossible de désactiver aucune couche (le basculement du framebuffer est peut-être interrompu) et dans l'écran debug du VDP1, on ne voit qu'une commande de normal sprite skipped, donc pas exécutée.
On voit aussi des commandes de normal sprite skipped quand les autres logos devraient s'afficher.

Dans SSF, ces écrans sont affichés par les sprites.

Mêmes problèmes en bios vrai ou émulé. Ces écrans ne s'affichaient pas non plus en v1.6.0.

**Comment by fafling** [comment]
Problème similaire dans Duke Nukem 3D, les logos (Deep Water, 3D Realms et Lobotomy Software) ne s'affichent pas au démarrage du jeu. A la place du 1er logo, on voit le logo SEGA réapparaître.

**Comment by fafling** [comment]
Dans Mednafen, pour Quake :
- 1er écran (visible dans Kronos) : sur les sprites, TVMR constant à 0, FBCR 3, EWLR 0x0000, EWRR 0x0001
- 2ème écran (non visible dans Kronos) : sur les sprites, TVMR alterne 0 et 8, FBCR 3, EWLR 0x0000, EWRR 0x0001
- Ecran de chargement (non visible sauf barre de progression dans Kronos) : sur les sprites, TVMR alterne 0 et 8, FBCR 3, EWLR 0x0000, EWRR 0x0001

Dans les 2 cas incorrects dans Kronos, le vblank erase est utilisé, et il ne devrait effacer que la zone comprise entre [0, 0] et [7, 1], donc 16 pixels en haut à gauche de l'écran.

Dans Duke Nukem, les écrans manquant sont aussi sur les sprites et les valeurs des registres sont les mêmes que pour les écrans manquants de Quake.

Dans Powerslave, il manque aussi l'image de fond de l'écran de loading qui suit la sélection d'un niveau sur la carte. Même principe que sur les écrans manquants des 2 autres jeux.

C'est donc encore un cas de non respect des coordonnées de l'erase/write, voir #1364, #1363, #1351, #1327, #1072 et #90.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.5.0 Cs

Après le première écran Quake, le suivant est affiché partiellement 
![image](https://user-images.githubusercontent.com/12481242/217262369-e4f6d617-958b-41e4-b556-3f680a05ab5a.png)

**Comment by BenjaminSiskoo** [comment]
@fafling Les écrans de chargement sont ok à priori. 

> Dans Mednafen, pour Quake :
> 
>     * 1er écran (visible dans Kronos) : sur les sprites, TVMR constant à 0, FBCR 3, EWLR 0x0000, EWRR 0x0001
> 
>     * 2ème écran (non visible dans Kronos) : sur les sprites, TVMR alterne 0 et 8, FBCR 3, EWLR 0x0000, EWRR 0x0001
> 
>     * Ecran de chargement (non visible sauf barre de progression dans Kronos) : sur les sprites, TVMR alterne 0 et 8, FBCR 3, EWLR 0x0000, EWRR 0x0001
> 
> 
> Dans les 2 cas incorrects dans Kronos, le vblank erase est utilisé, et il ne devrait effacer que la zone comprise entre [0, 0] et [7, 1], donc 16 pixels en haut à gauche de l'écran.
> 
> Dans Duke Nukem, les écrans manquant sont aussi sur les sprites et les valeurs des registres sont les mêmes que pour les écrans manquants de Quake.
> 
> Dans Powerslave, il manque aussi l'image de fond de l'écran de loading qui suit la sélection d'un niveau sur la carte. Même principe que sur les écrans manquants des 2 autres jeux.
> 
> C'est donc encore un cas de non respect des coordonnées de l'erase/write, voir #1364, #1363, #1351, #1327, #1072 et #90.

Toujours le problème pour ca ?

**Comment by fafling** [comment]
Je confirme, les écrans de chargement sont présents.
![image](https://github.com/FCare/Kronos/assets/7624262/28dbc3a6-173d-4fa0-af68-18148a64a6ed)
