### ISSUE TITLE
Quels sont les configs minimal compatible avec kronos ?

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#499]
Bonjour,

Je reviens vers vous pour savoir si il y avait des données officiels de kronos, c'est à dire configuration minimal à posséder pour faire fonctionner kronos sans crash ou lenteur ?

En effet j'ai eu beau chercher sur le net je n'ai jamais rien trouvé.

Type de processeur /architecture processeur à posséder
Ram
Carte graphique
Directx
OpenGL
Etc

**Comment by FCare** [comment]
Pour bien, il faut un processeur a 4 couers (au moins virtuel). La frequence du coeur est egalement important. 2Ghz au moins. Pour la carte graphique, elle doit supporter l'openGL 3.2, pour la tesselation , il faut l'openGL 4.2

Donc un core i3 avec chip integré est le minimum recommandé. La config conseillée serait un corei5 avec une carte dediée.

**Comment by barbudreadmon** [comment]
Attention aux gpus intégrés, on a des soucis sur certains gpus intel.
