### ISSUE TITLE
[Shining The Holy Ark] bugs graphiques

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#500]
Bonjour,

J'ai remarqué 2 bugs graphiques importants :

1) effet de transparence je pense que ça ne fonctionne pas (début du jeu lorsque les esprits vous parlent dans la mine) il y a un écran marron et je suppose qu'on devrait voir les esprits en arrière plan.

![stha1](https://user-images.githubusercontent.com/50514097/57925426-83a55480-78a8-11e9-8b39-a679dc925624.jpg)

2) Clignotement des textures lorsqu'on se déplace hors de la mine.

![stha2](https://user-images.githubusercontent.com/50514097/57925428-83a55480-78a8-11e9-9ed1-e996c7a1d5a6.jpg)
![stha3](https://user-images.githubusercontent.com/50514097/57925430-83a55480-78a8-11e9-9e7b-cd4b4b9dbd5d.jpg)

parties rapides
[MK-81306.zip](https://github.com/FCare/Kronos/files/3191255/MK-81306.zip)

**Comment by BenjaminSiskoo** [comment]
Merci pour les retours

**Comment by fafling** [comment]
Pour le 1er screen, voilà ce qu'on devrait voir :
![Capture_shining_the_holy_ark_youtube](https://user-images.githubusercontent.com/7624262/57975990-38895f80-79d6-11e9-89de-91120cfd19d8.PNG)

Il y a bien une effet de transparence, mais il est géré par le VDP1 (artifacts en marche d'escalier à l'intérieur).
L'écran marron est dessiné par le VDP1 et disparaît si on désactive la couche de sprites dans Kronos.

En fait, les 2 problèmes signalés ont sûrement la même cause : dans les 2 cas, il y a des coordonnées dans les commandes VDP1 qui dépassent les limites indiquée par la doc (entre -1024 et 1023). Pour l'instant, Kronos ne gère pas ce cas de figure comme le fait la console et dessine certaines de ces commandes en travers de l'écran (déjà décrit pour plusieurs autres jeux, voir #215 ).

Voilà probablement une des textures qui recouvrent l'écran dans le 1er screenshot :
![Capture_shining_the_holy_ark](https://user-images.githubusercontent.com/7624262/57975923-a5035f00-79d4-11e9-86dc-d556329d8df4.PNG)

**Comment by CloudFR** [comment]
OK merci pour tes précisions, y aura t il un correctif natif directement dans l’émulateur sans être obliger de passer dans les commandes ?

**Comment by fafling** [comment]
Je parle des commandes de dessin que traite le processeur VDP1. Elles sont produites par le jeu et on peut seulement les consulter dans l'écran VDP1.
Il n'y a actuellement pas de moyen de contourner ce problème d'affichage de Kronos. Ce n'est pas un problème simple à résoudre car il nécessite de programmer des tests sur la console.

**Comment by FCare** [comment]
Les coordonnées trop grandes, c'est du a un bug dans la couche de debug qui ne prend pas en compte comme il faut le bit de signe...
Je viens de le regler, mais ca ne regle pas le pb dans le jeu....

**Comment by FCare** [comment]
En fait, je pense que ce n'est pas le fait que ca soit hors de l'ecran.
Il y a des surfaces tellement grande que le vdp1 ne doit pas avoir le temps de les calculer sur la veritable saturn.
voila une des dernieres surfaces:
A {817,000000 569,000000}, B {-402,000000 -881,000000} C{-567,000000 -541,000000} D{761,000000 751,000000} A elle seule, cette surface doit bouffer toute la capacité de pixel rate du vdp1...
Je vais essayer de limiter le nombre de commandes au nombre de pixels effectivement ecrit, a la grosse...

**Comment by fafling** [comment]
@FCare C'est bien d'aligner l'écran debug sur les coordonnées utilisées par Kronos, mais je ne crois pas que l'hypothèse d'une interruption du dessin du VDP1 par le jeu soit la bonne.
Si c'était le cas, sur la console, on verrait des bout de polygones partiellement dessinés, or il n'y en a pas. Et puis ça supposerait que les développeurs du jeu ont calculé les derniers polygones n'importe comment, ce qui n'est pas très plausible.

**Comment by FCare** [comment]
@nicolas-charrier :
D'apres la doc CMDXA par exemple est un registre 16 bits. Les 5 bits de poids forts doivent etre la copie du bit 10. Du Bit 10 au bit 0, on a un entier signé en complément a 2.

Dans le cas de ces surfaces, le bit 10 est à 1, ce qui devrait correspondre a un chiffre negatif, neanmoins, les bits de poids forts sont a 0, ce qui sous entend que ca ne respecte pas la spec.

Si l'ALU du VDP1 est 16 bits, elle va donc considerer une valeur au dela des limites. Si elle est 10 bits, elle s'en fiche.

Dans le code, on a consideré qu'elle etait 10 bits, on se preoccupe pas des poids forts. 

Peut etre que l'erreur vient de la, mais il va falloir tester intensément la modif...

**Comment by fafling** [comment]
@FCare Je pense que ça vaut le coup de tester l'hypothèse que l'entier signé fait un bit de plus que ce que dit la doc.

**Comment by FCare** [comment]
C'est pas qu'il fait un bit de plus, c'est surtout que les bits de poids fort doivent obligatoirement etre le meme que le bit 10, sinon la surface n'est pas valide car hors framebuffer

**Comment by FCare** [comment]
I pushed the patch, please test on your side.

**Comment by fafling** [comment]
Plus de polygone en travers de l'écran dans la dernière WIP suite à cette restriction sur les commandes du VDP1.

**Comment by BenjaminSiskoo** [comment]
Je ferme
