### ISSUE TITLE
[Shining The Holy Ark] bug chargement de state après relance de kronos

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#501]
Bonjour,

Lorsqu'on quitte kronos et qu'on relance le jeu à partir de now loading ou plus et qu'on charge une state sauvegardée, j'ai une erreur d'instruction.

Ça me fait un peu chier parce qu’entre la sauvegarde normal et la state j'ai deux bonnes heures de jeu...

![bug](https://user-images.githubusercontent.com/50514097/57935207-94ae8f80-78c1-11e9-88a3-469ddbc7c65f.jpg)

**Comment by fafling** [comment]
Avec le save state MK-81306_000.yss fourni dans l'archive du bug report #500 , le message d'erreur se produit après avoir fait défiler le dialogue :

![Capture_shining_the_holy_ark_erreur_save_state](https://user-images.githubusercontent.com/7624262/57975879-4ab5ce80-79d3-11e9-89e3-27292d0f3a56.PNG)

En v1.6.0 avec la fenêtre de log, ou en WIP avec debugview, au moment où le message s'affiche à l'écran :

Error: Master SH2 invalid opcode

R0 =  00075365	R12 =  060FF74C
R1 =  06052000	R13 =  00000084
R2 =  00000002	R14 =  060FF740
R3 =  FFFFFF00	R15 =  060FF714
R4 =  00000020	SR =   00000001
R5 =  00009C71	GBR =  060FFC00
R6 =  00000008	VBR =  06000000
R7 =  00000101	MACH = 0000001E
R8 =  06021C84	MACL = FFC401A4
R9 =  060FF758	PR =   0604B4E2
R10 = 060BA004	PC =   000754E7
R11 = 0604D704

Testé avec le CD version US. Même comportement en bios réel ou émulé.

**Comment by CloudFR** [comment]
Bonjour,

Petite précision, je joue avec la version EUR et non US.

**Comment by fafling** [comment]
Avec la version EUR, je ne constate plus d'erreur en v1.7.0 publique quand je charge les 2 save state de l'archive.

**Comment by fafling** [comment]
Je précise que j'ai chargé le 2ème save state en plein jeu sans avoir de problème.

**Comment by BenjaminSiskoo** [comment]
ca devrait être corrigé.
