### ISSUE TITLE
[Off-World Interceptor Extreme] Ecran noir dans le jeu

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#502]
Kronos 1.7.0

![image](https://user-images.githubusercontent.com/12481242/57968107-97af8b80-7966-11e9-88c2-5d785f22f890.png)

**Comment by fafling** [comment]
On n'arrête pas d'avoir des différences en ce moment ! Moi je vois le ciel :
![Capture_off_world](https://user-images.githubusercontent.com/7624262/57975496-610b5c80-79ca-11e9-8d36-9f49ad84969e.PNG)

Les commandes de dessin des sprites sont présentes dans l'écran début du VDP1.
Truc curieux dans l'écran debug du VDP2 : les priorités de tous les registres des sprites sauf le 0 sont à 0. Si un pixel a une priorité de 0, il est considéré comme transparent par le VDP2.
![Capture_off_world_VDP2](https://user-images.githubusercontent.com/7624262/57975518-d0814c00-79ca-11e9-9a82-a68d23cf8e28.PNG)

**Comment by fafling** [comment]
Testé avec le CD version US.

**Comment by BenjaminSiskoo** [comment]
Effectivement bizarre, j'ai testé aussi la version US au cas ou et je ne vois pas le ciel non plus.

**Comment by FCare** [comment]
Le jeu utilise la fnction readframebuffer et writeframebuffer.

Le read marche bien, le write semble faire du noir...

Le dim. 19 mai 2019 à 11:24, Benjamin Siskoo <notifications@github.com> a
écrit :

**Comment by BenjaminSiskoo** [comment]
Pour moi c'est corrigé, si @nicolas-charrier ca déconne dis le moi et j'ouvrirais le post de nouveau

**Comment by fafling** [comment]
@BenjaminSiskoo Pas bon chez moi. Les sprites sont maintenant visibles, mais semi-transparent à l'arrière-plan VDP2 (RBG0 ou back screen) :
![Capture_off_world_interceptor_20190606](https://user-images.githubusercontent.com/7624262/58996721-bed8da80-87f9-11e9-9a5b-69b78b8af652.PNG)

**Comment by BenjaminSiskoo** [comment]
J'attends ton retour avec la dernière wip sinon j'ouvre de nouveau

**Comment by fafling** [comment]
La semi-transparence incorrecte est toujours là en v1.7.0 publique.

**Comment by fafling** [comment]
Si on laisse la jauge de temps rouge se remplir, le véhicule explose. Jusqu'à l'explosion, l'affichage est incorrect, mais après un effet de color offset bleu/vert, les sprites sont affichés correctement pendant la fin de l'explosion. Un save state de la version US fait avec la WIP du 12/07 :
[off_world_time_critical.zip](https://github.com/FCare/Kronos/files/3389948/off_world_time_critical.zip)

**Comment by fafling** [comment]
En WIP du 29/08, la semi-transparence incorrecte n'existe qu'avec le noyau OpenGL. Le noyau compute shader est correct de ce point de vue.

**Comment by fafling** [comment]
Fixé en OpenGL sur la branche accurate_vdp1 depuis la WIP du 25/09.
