### ISSUE TITLE
[Interface QT] La fenêtre de log ne s'affiche plus

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#503]
Dans la dernière WIP, l'option Visualiser>"Afficher la fenêtre journal" n'active plus la fenêtre de log quand "Sur le message" est coché. C'est la cas depuis la WIP du 17/03.

Par exemple, en v1.6.0, le message "Saturn Emulation mode" s'affichait dans la fenêtre au lancement de l'émulation, ce n'est plus le cas dans la WIP. Idem pour les messages d'erreur quand ils se produisent comme avec Vampire Savior ( #423 ).

**Comment by BenjaminSiskoo** [comment]
Pour les messages je crois que c'était pour les debugs, il a dû enlever ca. Si je dis pas de bêtise avec l'interpreteur SH2 kronos tu n'as plus les messages Master/Slave sh2 error, mais tu les as normalement avec l'interpreteur SH2 de base

**Comment by FCare** [comment]
En effet l'interface qt a besoin d'un nettoyage...

Le sam. 18 mai 2019 à 14:07, Benjamin Siskoo <notifications@github.com> a
écrit :

**Comment by fafling** [comment]
Dans la WIP, il n'y a aucun affichage de la fenêtre de log, quelque soit l'interpréteur SH2 sélectionné.

**Comment by FCare** [comment]
J'ai juste oublié de retirer purement et simplement la fenetre de log. 
Pour avoir les messages de debug sous windows, vous devez maintenant installer DebugView https://docs.microsoft.com/en-us/sysinternals/downloads/debugview sous windows et sous linux, utiliser la fenetre de shell.
J'ai aligné les debugs sur les mecanisme standard des OS.
