### ISSUE TITLE
[Interface QT] Infos manquantes ou incorrectes dans l'écran debug du VDP2

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#505]
Dans la video d'intro de Gulliver boy, l'effet de gradation utilise le color calculation ratio du registre 0 des sprites. Le ratio indiqué à 31:1 pour le registre 0 des sprites dans l'écran debug n'est pas le bon, d'après @FCare, il devrait être à 15:17 pour 0x10 ou bien 16:16 pour 0xF, et c'est le registre CCRNA (ratio des couches NBG0 et NBG1) au lieu du registre CCRSA qui est affiché.

D'autre part l'effet de gradation n'est pas indiqué sur le NBG0 dans Megaman 8 alors qu'il est utilisé.

**Comment by fafling** [comment]
Il faudrait que cet écran affiche l'info du type de color RAM utilisé (registres CRMD0 et CRMD1, p. 46 de la doc du VDP2). Cette info conditionne plusieurs effets de color calculation comme la gradation, voir #263 .

**Comment by FCare** [comment]
En effet, je vais rajouter l'info.

**Comment by FCare** [comment]
Ajouté  le 21/05/2019

**Comment by fafling** [comment]
Le type color RAM est bien affiché dans la dernière WIP.

Il y aurait besoin d'afficher aussi l'activation du line color screen par une couche, il intervient aussi dans la color calculation.

**Comment by fafling** [comment]
@FCare Les ratios affichés pour Gulliver boy sont toujours à 31:1 pour les sprites, et l'info de gradation n'est pas affichée dans Megaman 8. Est-ce que tu peux rouvrir ?

**Comment by fafling** [comment]
Pour les ratios des sprites et l'info de gradation c'est OK dans la dernière WIP.

**Comment by fafling** [comment]
Info d'activation du line color screen OK en WIP du 23/03.
