### ISSUE TITLE
[Steep Slope Sliders] Textures transparentes

### ISSUE THREAD

**Issue by Tatsuya79** [FCare/Kronos#506]
La piste est transparente par endroit, c'est plus ou moins évident selon les courses.
Très visible sur la 2ème:

![sss-190521-191639](https://user-images.githubusercontent.com/6266038/58116800-7a481f00-7bfd-11e9-8bd5-2035057b76a8.png)

Gpu tesselation ou non, résolution originale, pas de différence.
Ce problème n'était pas présent auparavant (dernière fois que j'ai essayé... plusieurs mois?).

libretro win7 x64 nvidia GTX770

**Comment by fafling** [comment]
Effectivement, la v1.6.0 n'a pas ce problème, il apparaît avec le rework (WIP du 17/03).
Dans l'écran debug du VDP2, il n'y a pas d'autre couche que les sprites et le décor de fond.
La color calculation est activée sur les sprites avec différents ratios. La transparence vers le blanc est sûrement obtenue par la console en insérant le line color screen en second image quand les sprites sont en top image (et peut-être une variation de palettes de couleur), voir doc du VDP2 p. 230-231.

![Capture_steep_slope_slider_VDP2](https://user-images.githubusercontent.com/7624262/58127701-3c0b2980-7c16-11e9-92de-799dbbd72b62.PNG)

Affichage correct :
![Capture_steep_slope_slider_youtube](https://user-images.githubusercontent.com/7624262/58127708-4299a100-7c16-11e9-9cfa-da5cff9f43e2.PNG)

Ce serait intéressant d'afficher si une couche active le line color screen dans l''écran debug du VDP2 (voir #505 ).

**Comment by fafling** [comment]
L'affichage est correct en WIP du 12/07 :
![Capture_steep_slope_sliders_20190712](https://user-images.githubusercontent.com/7624262/61164260-f2eb9d80-a513-11e9-83ae-bf13714d74e3.PNG)

**Comment by Tatsuya79** [comment]
En effet problème résolu, testé sur kronos libretro win64 de ce jour.
:+1:
