### ISSUE TITLE
Forte régression des perfs en 4x et plus

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#508]
Depuis https://github.com/FCare/Kronos/commit/d7f7bbacf8be6f720de9186b532e6675bcbf5637 , les requirements pour du rendu en 4x et 8x ont très fortement augmenté, une GTX 770 ne semble plus capable de faire fonctionner à pleine vitesse un jeu en 4x alors qu'avant ce commit elle le faisait tourner à 75fps en 8x. Y a-t-il une méthode (peut-être un speedhack quelconque qui pourrait être activé manière optionnelle) qui pourrait être implémenté pour améliorer un peu les perfs sur du GPU milieu de gamme ?

**Comment by CloudFR** [comment]
Salut, je joue en 16X sans problème de perf chez moi.
J'ai une GTX 1050.

**Comment by barbudreadmon** [comment]
Encore une carte un peu moins puissante que la gtx 770 qui n'a pas ce problème (ou bien moindre), je me demande si çà ne pourrait pas être plutôt un soucis de driver.

**Comment by FCare** [comment]
Peut etre en effet. C'est quoi la conf exacte, la version du driver Nvidia
et la version de windows?

Le mer. 22 mai 2019 à 10:38, barbudreadmon <notifications@github.com> a
écrit :

**Comment by Tatsuya79** [comment]
Salut, c'est moi qui ait ce problème.

Win7 x64, nvidia GTX770 417.71 , i5-3570K.

J'ai essayé tout par défaut dans le panneau nvidia ou en forceant "threaded optimization" on ou off, toujours pareil: GPU utilisé à 100% en 4x en 8x.
Même dans Rockman 8 qui est un simple jeu 2D je passe de 60+fps en 8x à 15~20fps depuis https://github.com/FCare/Kronos/commit/d7f7bbacf8be6f720de9186b532e6675bcbf5637.
Je peux juste utiliser 2x max maintenant.

**Comment by FCare** [comment]
Reteste avec les derniers patchs, il y avait qques pb d'implémentation,
genre on premanit des infos dans la mauvaise texture (qui pouvait ne pas
avoir ete uploadée sur le GPU). Ca vient peut etre de la...

De mon coté, sur AMD et sur intel graphics, ca n'a pas généré de chute de
FPS aussi flagrant...

**Comment by barbudreadmon** [comment]
> Salut, c'est moi qui ait ce problème.

Je l'ai aussi dans une moindre mesure (performances 4x sur la dernière WIP inférieures aux performances 8x que j'avais avant ce commit, mais dans mon cas çà reste au dessus de 60fps), je suis en drivers 418.56 (sous linux par contre).

J'ai remarqué un autre truc aussi, çà c'est ta carte : 
>Memory Interface Width : 256-bit
Memory Bandwidth (GB/sec) : 224.3

Et çà c'est la GTX960 et la GTX1050 : 
>Memory Interface Width : 128-bit
Memory Bandwidth (GB/sec) : 112

Il y a clairement une différence d'architecture sur la mémoire, est-ce que çà peut jouer ?

**Comment by Tatsuya79** [comment]
Pas de différence à ce commit:
https://github.com/libretro/yabause/commit/600cd6bc6c4461cd60f715b368bc038981d14ca1

**Comment by barbudreadmon** [comment]
Un peu mieux pour moi mais rien d'énorme (on est sur du gain de 5% en perf). Les drivers ne semblent pas être en cause (je suis passé en 430.14 et je n'ai pas vu de différence). Dans mon cas, mes perfs en 4x restent très honorables sur la plupart des jeux, donc c'est pas gênant.

@Tatsuya79 à mon avis il faudrait que tu teste avec le standalone pour voir si t'as des résultats équivalents (il y a toujours un léger overhead avec retroarch mais ce n'est pas censé être ouf non plus, d'ailleurs j'ai constaté de meilleures perfs avec `glcore` qu'avec `gl` en video_driver dans retroarch)

**Comment by Tatsuya79** [comment]
Un exe récent quelque part pour windows?

**Comment by FCare** [comment]
il y en aura un ce soir.

**Comment by CloudFR** [comment]
Bonsoir, On pourra le télécharger où ?

**Comment by Tatsuya79** [comment]
Même résultat que sous libretro avec stand-alone 2.0.1, OpenGL CS.
720p est limité à 50fps sur la démo de sega rally.

**Comment by barbudreadmon** [comment]
Il doit y avoir une instruction mal supportée sur cette génération de carte, chez moi sur cette démo je suis à 110-120fps en 1080p sur ma GTX960 (censée être moins puissante), juste une baisse à 80fps sur le départ du circuit en ville (monaco ?)

**Comment by BroKill** [comment]
Sorry for not replying in French but I'm not able to do it.
I have a GTX 770 2gb and today I updated the driver version to 441.87. 
Now I can put internal resolution to 720p without problem using last Kronos core version with Vulkan driver.

**Comment by barbudreadmon** [comment]
@BroKill thanks for the heads up !

**Comment by Tatsuya79** [comment]
No difference with 441.87 after a full driver cleaning in safe mode before testing.
And there's no vulkan support in kronos.

**Comment by FCare** [comment]
@Tatsuya79 Can you run a benchmark tool on your graphic card to validate your HW? There might be performance impact, for sure, but a so huge impact looks really strange. A benchmark like https://geeks3d.com/furmark/ might be able to show if your graphic card is in the usual range of other GTX 770. I personnaly have a GTX550, and I am far from 50fps on sega rally... 

Can yo ualso check in the nvidia driver configuration that you let the application to choose the right 3D parameters? I know Nvidia drivers can overite some parameters like the setSwapInterval. It has to be 0 otherwise, you will stay at the frequency of your LCD panel.

**Comment by barbudreadmon** [comment]
Another theory would be that the gpu stays in "power saving" mode for whatever reason

**Comment by BroKill** [comment]
I have a Palit GTX 770 2gb and I repeat, with driver version 441.87 I can run Kronos inside RA with 720p resolution without problems ( Vulkan driver ).
Before the driver update I had problems with resolution 480p.
Now it runs good!

Since I am not at home, later I will post Kronos settings.

**Comment by barbudreadmon** [comment]
> Vulkan driver

There is no vulkan support (yet) in kronos though, retroarch is just silently switching to glcore
```
...
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: "vulkan" saved as cached driver.
[INFO] [Video]: Forcing "glcore" driver.
...
```

**Comment by BroKill** [comment]
> There is no vulkan support (yet) in kronos though, retroarch is just silently switching to glcore
> 
> ```
> ...
> [INFO] [Video]: Using HW render, OpenGL driver forced.
> [INFO] [Video]: "vulkan" saved as cached driver.
> [INFO] [Video]: Forcing "glcore" driver.
> ...
> ```

Ok, didn't know that but the fact is I got a boost from the nvidia driver update.

Thanks for the good work dear guys, much appreciated!

**Comment by barbudreadmon** [comment]
@Tatsuya79 tu en es où niveau perf ? il y a du mieux sur les dernières versions ?

**Comment by Tatsuya79** [comment]
OpenGL CS shows around 30fps in sega rally (which means really 15fps or even less) in 1080p.
Open GL seems to be full speed at that res.

**Comment by barbudreadmon** [comment]
Ok, tes performances m'ont l'air d'être revenue à la normale donc (un peu meilleure que sur ma GTX 960, comme çà devrait l'être), OpenGL CS est ultra gourmand sur Sega Rally, ce qui j'imagine est assez logique vu que c'est l'un des jeux qui en tire le plus parti. Malheureusement c'est aussi la seule façon d'émuler correctement le jeu.

Vu que le problème (performance plus basses que chez moi alors que ta carte est plus puissante) est résolu, je ferme le ticket.
