### ISSUE TITLE
Ecrans figés ou framerate très faible avec la synchro verticale

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#510]
Depuis le commit 81f0686 , quand la synchro verticale est activée (toutes les options à leurs valeurs par défaut), j'ai des écrans noirs ou figés, et des framerates très faibles :
- bios : écran noir pendant le nuage de polygones.
- Contra : écran noir pendant la video, framerate très faible pendant le jeu (5-10 fps au lieu de 40-45 sans vsync). Pendant le jeu, si on met en pause, l'écran reste figé en sortie de pause.
- Steep slope slider : écran loir pendant la démo, menu figé pendant le jeu.

Ma config : Core i3 2.80GHz, 4Go de RAM, Nvidia GTX 750 Ti, Windows 10 32 bit.

**Comment by FCare** [comment]
Salut, en effet j'ai du me melanger les pinceaux... Je vais revoir le patch.

Il semble que la vsync active egalement la vrai mecanisme de frame drop,
qui est instable et qui ne doit pas etre activé normalement...

Le jeu. 23 mai 2019 à 00:36, nicolas-charrier <notifications@github.com> a
écrit :

**Comment by FCare** [comment]
Je viens de pousser un patch pour le desactiver, quoi qu'il arrive.
Reteste pour voir si ca s'ameliore... ca peut etre lié au pb de
ralentissement et de perfs qu'on a vu par ailleurs...

**Comment by fafling** [comment]
Problème réglé avec la dernière WIP.
