### ISSUE TITLE
[Krazy Ivan] Gouraud shading incorrect avec tesselation CPU en noyau OpenGL

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#511]
Dans la dernière WIP, Kronos affiche pendant le jeu un Gouraud shading discontinu avec la tesselation CPU. Les 2 autres modes de tesselation n'ont pas ce souci. Ce problème était déjà présent en v1.6.0.
![Capture_krazy_ivan_20190523](https://user-images.githubusercontent.com/7624262/58216498-1d349200-7cff-11e9-9669-9ff0958766b3.PNG)

Affichage correct avec tesselation GPU :
![Capture_krazy_ivan_20190523_2](https://user-images.githubusercontent.com/7624262/58216518-2e7d9e80-7cff-11e9-8f3c-33cc06a454e4.PNG)

Testé avec le CD euro du jeu.

**Comment by fafling** [comment]
Un save state pour aller plus vite dans le jeu :
[krazy_ivan.zip](https://github.com/FCare/Kronos/files/3209780/krazy_ivan.zip)

**Comment by FCare** [comment]
Ca a l'air fixé

**Comment by BenjaminSiskoo** [comment]
Corrigé

**Comment by fafling** [comment]
Toujours le même problème chez moi dans la dernière WIP.

**Comment by fafling** [comment]
Toujours présent en WIP du 29/11 en noyau OpenGL (sans objet en noyau CS puisqu'il n'y a plus de tesselation).

**Comment by BenjaminSiskoo** [comment]
![image](https://user-images.githubusercontent.com/12481242/216204673-c80ebd83-b2a0-434b-9034-b2ee2e12b64d.png)

c'est bon pour toi @fafling ?

**Comment by fafling** [comment]
Non, il n'y a aucun changement.

**Comment by BenjaminSiskoo** [comment]
OpenGL n'est plus
