### ISSUE TITLE
Non GL builds, complete fail, all sorts of dependencies behinds ifdef guards

### ISSUE THREAD

**Issue by dmiller423** [FCare/Kronos#512]
Not much to add,  there are enums etc in ygl.h behind HAVE_LIBGL ifdef guards that are required in  vdp for a start.   There are a great many errors, that are not present in mainline yabause and less so in 'sanshiro'.   You might forcefully disable HAVE_LIBGL and build w.o it for soft render to easily fix other build environments.

**Comment by FCare** [comment]
Kronos is not intended to support non opengl environnement for the moment.
The sw renderer has many bugs and I do not have time to fix. For sw
rendering i would recommend mednafen.

Le jeu. 23 mai 2019 à 05:25, David Miller <notifications@github.com> a
écrit :
