### ISSUE TITLE
OpenGL size incorrecte après passage en plein écran pendant le jeu

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#513]
Dans la dernière WIP, si on a réglé l'OpenGL size à plus de 2x, et qu'on passe en plein écran pendant le jeu (après le logo SEGA du bios), l'affichage est fait en OpenGL size 2x (l'option est toujours à plus de 2x dans les paramètres).

Cela inclut le cas d'un démarrage de l'émulation en plein écran, où l'affichage est en plus de 2x, suivi d'un basculement en fenêtré et d'un retour en plein écran : l'affichage est en 2x.

Reproduit avec Sega Rally Plus, Decathlete et Steep slope sliders (tous en CD version US).

Le problème est présent depuis la WIP du 16/05.

**Comment by FCare** [comment]
Tu peux essayer a nouveau?

**Comment by fafling** [comment]
Le problème est réglé en WIP du 04/07.
