### ISSUE TITLE
Polygones rectangulaires trop gros

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#514]
Dans la dernière WIP, et depuis le rework, l'expansion est activée sur les polygones non texturés rectangulaires alors que ce n'est pas nécessaire puisque ça n'évite pas de trous.

C'est visible dans Quake (CD version US) au démarrage du jeu s'il n'y a pas de sauvegarde :
![Capture_quake_polygone_tros_gros](https://user-images.githubusercontent.com/7624262/58291645-6dbef480-7dbe-11e9-8449-04fbeb30778a.PNG)

Le fond des 2 boutons est dessiné par une commande de polygone qui a les mêmes coordonnées qu'une commande de polyline qui en dessine le tour en noir. Les polygones ne devraient donc pas dépasser de la polyline.
![Capture_quake_polygone_tros_gros_VDP1_1](https://user-images.githubusercontent.com/7624262/58291737-c8585080-7dbe-11e9-913e-b2b6ca1e5abe.PNG)

![Capture_quake_polygone_tros_gros_VDP1_2](https://user-images.githubusercontent.com/7624262/58291743-cd1d0480-7dbe-11e9-9846-74b0fe15c50c.PNG)

Visible également dans :
- Le bios (rectangles de sélection dans les menus)
- Guardian heroes (écrans de sélection de support de sauvegarde, du perso, barres de vie)
- Megaman X4 (barre de vie)
- Shining the holy ark (fenêtres de dialogue)

**Comment by FCare** [comment]
La valuer de distorted n'etait pas bonne la...

**Comment by fafling** [comment]
La taille des polygones rectangulaire est OK dans la dernière WIP.
![Capture_quake_polygones_20190608](https://user-images.githubusercontent.com/7624262/59139310-a3ed9e00-8992-11e9-9c48-62c3f95362f6.PNG)
