### ISSUE TITLE
[2do Aru Koto wa Sando R] Freeze du jeu

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#515]
Dans la dernière WIP (bios réel ou émulé), le cycle de démo fonctionne correctement, mais si on démarre une partie (appuyer 3 fois sur start), l'affichage est gelé après quelques secondes de jeu. La musique continue, et l'interface de Kronos continue de fonctionner.

Endroit où le freeze se produit systématiquement :
![Capture](https://user-images.githubusercontent.com/7624262/58372863-995bef00-7f24-11e9-82ea-e64643968f05.PNG)

Testé avec un CD d'origine qui fonctionne sans  problème sur la console.

Le même freeze existait déjà dans Kronos v1.5.0.

**Comment by fafling** [comment]
Toujours présent en WIP du 12/01/2020.

En noyau compute shader, le freeze se produit immédiatement au début du jeu :
![image](https://user-images.githubusercontent.com/7624262/72228677-2f728180-35a9-11ea-97ed-63800f43685e.png)

Pas d'affichage dans debugView au moment des freezes.

**Comment by BenjaminSiskoo** [comment]
Kronos Wip 14.10.2021
Mode CS

Le jeu fonctionnait avec la correction des timings.

https://youtu.be/Kl_uVyztu2U

**Comment by fafling** [comment]
Problème toujours présent dans la dernière WIP.
Au moment du blocage, le framerate du VDP1 tombe à 0.
Pas de message dans DebugView.
Pas de changement avec une 2ème manette.
Dans Mednafen, on voit que le registre FBCR du VDP1 est constamment à 0x3 (manual mode (change)).

**Comment by fafling** [comment]
Activer le cache SH2 ne change rien à part ralentir l'émulation à mort (je ne dépasse pas 4 fps).
La WIP qui fixait le blocage grâce aux timings était celle du 07/09/2021. Le problème était présent dans la WIP précédente du 30/08/2021.
Le blocage réapparaît en WIP du 20/09/2021.

**Comment by BenjaminSiskoo** [comment]
Légère amélioration avec kronos20230110_88b37e9 et avec ce commit et les versions d'avant, le personnage se bloquait un peu avant

![image](https://user-images.githubusercontent.com/12481242/211604986-feed400d-e7d8-4d3e-8c03-87cbb258dac4.png)

**Comment by BenjaminSiskoo** [comment]
Avec les fixs du 11.01.2023, le jeu est presque jouable, il reste encore des freeze aléatoire. Amélioration grâce au scu dma du fix de virtua fighter remix du 11.01.2023

**Comment by FCare** [comment]
il attend 0x80 sur le registre FTCSR du MSH2.

donc pb de com avec le slave SH2

**Comment by BenjaminSiskoo** [comment]
Kronos 2.5.0
Cs

Freeze toujours mais on gagne quelques frames

**Comment by BenjaminSiskoo** [comment]
Finally the game is playable :)
