### ISSUE TITLE
[X Japan Virtual Shock 001] Les boutons ne répondent pas sur les manettes USB

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#518]
Dans la dernière WIP (bios réel ou émulé), le jeu ne répond à aucun bouton : impossible de démarrer le jeu avec start, ou de faire un reset avec A+B+C+ start.

Testé avec un CD d'origine qui fonctionne sans problème sur console.

Ce problème existait déjà en v1.6.0, mais pas en v1.5.0.

**Comment by fafling** [comment]
Problème présent en v2.0.1 publique et en WIP du 15/01.
Les boutons ne répondent pas avec une manette USB (testé avec 2 manettes), mais ils répondent s'ils sont mappés sur des touches du clavier.
Même problème dans Heart of darkness.

**Comment by BenjaminSiskoo** [comment]
Toujours présent en WIP 2.14

**Comment by BenjaminSiskoo** [comment]
kronos20231206_3006f2d

Corrigé
