### ISSUE TITLE
[True Pinball] Graphismes manquants dans le menu d'options en noyau compute shader 

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#519]
Dans la dernière WIP (bios réel et émulé), des sprites ne sont pas affichés par Kronos dans le menu d'options :
![Capture_true_pinball_options_20190523](https://user-images.githubusercontent.com/7624262/58388109-84fa1e00-801a-11e9-8023-f481d638bcdc.PNG)

Tous les sprites manquants utilisent le Gouraud shading alors que cet effet n'est pas exécuté par le VDP1 dans un framebuffer 8 bit (p. 93 de la doc du VDP1) :
![Capture_true_pinball_options__VDP1_20190523](https://user-images.githubusercontent.com/7624262/58388040-52035a80-8019-11e9-805f-f1797ae1493c.PNG)

Il s'agit d'un framebuffer high resolution vu les coordonnées des sprites. Ce serait une info utile à afficher dans l'écran debug du VDP2.

Sur la console, ces sprites sont affichés tels quels sans effet de Gouraud :
![Capture_true_pinball_options_youtube](https://user-images.githubusercontent.com/7624262/58388057-aad2f300-8019-11e9-8c50-d8252c0cc7f9.PNG)

Ce problème est déjà présent en v1.5.0 et v1.6.0.
Il est identique sur la version européenne et la version japonaise du jeu.

**Comment by FCare** [comment]
En v1.7.0, avec les derniers commits, ca devrait etre bon :-)

**Comment by BenjaminSiskoo** [comment]
Nice catch c'est bon chez moi

**Comment by fafling** [comment]
@BenjaminSiskoo Il y a le même problème en noyau CS uniquement en WIP du 04/09, est-ce que tu peux rouvrir ?

**Comment by fafling** [comment]
En WIP du 10/12, les graphismes sont partiellement visibles en CS :
![image](https://user-images.githubusercontent.com/7624262/70578054-ec3d8100-1bac-11ea-8122-dfe574ac849d.png)

**Comment by BenjaminSiskoo** [comment]
Même problème avec Kronos du 15.01.2021 en CS

**Comment by BenjaminSiskoo** [comment]
Corrigé depuis la branche fb access
