### ISSUE TITLE
[tesselation GPU] Shadow RGB et half luminance du VDP1 incorrectes ou absentes en extui-align

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#521]
Dans la dernière WIP, quand la tesselation GPU est sélectionnée, les sprites dessinés par le VDP1 avec le mode de color calculation shadow sont soit absents, soit dessinés sans tenir compte des pixels transparents, ils occupent donc tout le polygone qui les contient. Ils sont affichés correctement dans les autres mode de tesselation  (au bug de transparence près #475 ).

Les ombres en polygone pleins sont visibles dans Mystaria, Powerslave / Exhumed et Duke Nukem 3D. Dans Virtual Hydlide, l'ombre du perso est absente.

C'est affiché de cette manière depuis le rework. En v1.6.0, les ombres ne s'affichaient pas avec la tesselation GPU.

Même problème en bios réel ou émulé (Virtual Hydlide et Duke Nukem 3D ne démarrent pas en bios émulé).

Dans Duke Nukem 3D, c'est visible dès le menu de départ si on n'a pas fait de sauvegarde :
![Capture_duke_20190523_GPU_shadow](https://user-images.githubusercontent.com/7624262/58519605-b1e23880-81b4-11e9-8d86-258250995492.PNG)

Affichage correct :
![Capture_duke_20190523_triangle_shadow](https://user-images.githubusercontent.com/7624262/58519629-c45c7200-81b4-11e9-8c96-5c8dac750d28.PNG)

En jeu :
![Capture_duke_20190523_GPU_shadow_2](https://user-images.githubusercontent.com/7624262/58519690-f1a92000-81b4-11e9-8433-38e85d517509.PNG)

Affichage correct :
![Capture_duke_20190523_triangle_shadow_2](https://user-images.githubusercontent.com/7624262/58519696-fa99f180-81b4-11e9-80d7-6ea5a7fcbe25.PNG)

Dans Mystaria :
![Capture_mystaria_20190523_GPU_shadow](https://user-images.githubusercontent.com/7624262/58519720-11404880-81b5-11e9-8d4d-8883453cf43e.PNG)

Dans Powerslave :
![Capture_powerslave_20190523_GPU_shadow](https://user-images.githubusercontent.com/7624262/58519732-1d2c0a80-81b5-11e9-8908-d2e765b8c98f.PNG)

Ombre manquante dans Virtual Hydlide :
![Capture_virtual_hydlide_20190523_GPU_shadow](https://user-images.githubusercontent.com/7624262/58519756-2b7a2680-81b5-11e9-8d44-6d1546b6df4c.PNG)

**Comment by FCare** [comment]
Tu peux tester a nouveau, chez moi je ne le vois pas...

**Comment by fafling** [comment]
J'ai regardé dans Duke Nukem et Virtual Hydlide, toujours les mêmes problèmes dans la dernière WIP.

**Comment by BenjaminSiskoo** [comment]
Je confirmes pour Virtual Hydlide même soucis avec le GPU Tesselation

**Comment by BenjaminSiskoo** [comment]
A gauche kronos 1.6.0 du 30 avril 2019 avec le gpu tesselation à droite wip d'hier

![virtua](https://user-images.githubusercontent.com/12481242/59144131-3ada4a80-89d3-11e9-98a2-86b3780ce5ff.PNG)

**Comment by fafling** [comment]
Les sprites concernés utilisent le mode half luminance du VDP1.

**Comment by BenjaminSiskoo** [comment]
Duke Nukem 3D - Kronos wip du 10/06/2019 avec le GPU Tesselation 

Toujours des soucis

![dukenukem3d](https://user-images.githubusercontent.com/12481242/59165525-7e40d000-8b1d-11e9-934f-0a857e8b8de9.PNG)

![dukenukem3dingame](https://user-images.githubusercontent.com/12481242/59165537-afb99b80-8b1d-11e9-8f25-f4ea564b62ae.PNG)

**Comment by BenjaminSiskoo** [comment]
Mystaria - Kronos wip du 10/06/2019 avec le GPU Tesselation

Je pense que c'est corrigé, @nicolas-charrier devrait confirmer

![mystaria](https://user-images.githubusercontent.com/12481242/59165551-f909eb00-8b1d-11e9-8096-30ba87f23372.PNG)

**Comment by BenjaminSiskoo** [comment]
Virtual Hydlide - Kronos wip du 10/06/2019 avec le GPU Tesselation

Manque l'ombre

![virtual hydlide](https://user-images.githubusercontent.com/12481242/59165572-48501b80-8b1e-11e9-8e9b-40b94110c0ba.PNG)

**Comment by fafling** [comment]
Ce n'est toujours pas bon dans Mystaria. Dans ce jeu, le problème en tesselation GPU c'est la forme des ombres : elles sont carrées au lieu d'être rondes.
La couleur incorrecte des transparences de sprites sur mon screenshot vient d'un autre problème indépendant de la tesselation, mais qui n'apparaît que sur carte nvidia (#475 ).

Par contre, le menu de Virtual Hydlide est correct dans tous les modes de tesselation en v1.7.0 publique :
![Capture_virtual_hydlide_menu_1 7 0](https://user-images.githubusercontent.com/7624262/59235403-5327b080-8bf1-11e9-8757-b6efb4a45671.PNG)

**Comment by FCare** [comment]
Avec les derniers commits, le pb n'existe plus chez moi. Vous pouvez tester?

**Comment by fafling** [comment]
Pas d'amélioration chez moi dans la WIP du 04/07.

**Comment by fafling** [comment]
Fixé dans la WIP accurate_vdp1 du 24/09.

**Comment by fafling** [comment]
Fixé en extui-align.
