### ISSUE TITLE
[Off-World Interceptor Extreme] Problème d'affichage des particules...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#524]
Kronos 1.7.0 Wip du 05/06/2019

Sur la photo, j'ai raté de peu l'image mais on a bien sur le loading sur Kronos mais pas les particules autour comme sur mednaffen 

![offworld2](https://user-images.githubusercontent.com/12481242/58970824-74843900-87ba-11e9-8de0-8f609c763676.PNG)

**Comment by fafling** [comment]
Les particules sont dessinées par le VDP1 avec des commandes de line avec des coordonnées de départ et de fin égales. Kronos ne les affiche pas.
![Capture_off_world_interceptor_particules](https://user-images.githubusercontent.com/7624262/58997596-9fdc4780-87fd-11e9-90b9-9768a81662c5.PNG)

**Comment by BenjaminSiskoo** [comment]
Semble corrigé aussi :)

**Comment by fafling** [comment]
Le commit 186b299 permet effectivement de rendre visible les particules.
Les croix des adversaires deviennent aussi visibles sur le radar de Krazy Ivan car ces croix sont dessinées point par point avec des commandes de line.
![Capture_krazy_ivan_lines_20190607](https://user-images.githubusercontent.com/7624262/59131091-a55a9e80-8971-11e9-91bf-299cba55fd2a.PNG)

@FCare Si je comprend bien le code, toutes les commandes qui dessinent des lignes verticales ou horizontales sont modifiées. J'ai remarqué des décalages d'un pixel dans l'interface de Off world qui rendent des lignes disjointes alors qu'elles devraient se toucher. Peux-tu restreindre le changement aux commandes de line qui dessinent seulement un point ?

WIP du 05/06 sans décalage :
![Capture_off_world_interceptor_20190605](https://user-images.githubusercontent.com/7624262/59131539-f6b75d80-8972-11e9-8284-db1298dd88d5.PNG)

WIP du 07/06 avec décalage (le fix sur les polygones trop gros améliore bien les choses !) :
![Capture_off_world_interceptor_20190607](https://user-images.githubusercontent.com/7624262/59131565-059e1000-8973-11e9-9881-1ad15b5ebb7a.PNG)

**Comment by FCare** [comment]
@nicolas-charrier : patch poussé pour gerer uniquement le point.

**Comment by fafling** [comment]
Suite à la correction sur le grossissement des lines, elles sont positionnées correctement. Je n'ai pas vu de régression suite à ce fix dans d'autres jeux qui utilisent des lines, notamment la carte de Doom est dessinée correctement.

Par contre, les lines qui dessinent les points sont maintenant trop grosses, elles occupent plusieurs pixels. @FCare Il n'y a peut-être plus besoin du fix sur la taille des points suite au changement sur l'épaisseur des lines, si ça se trouve ils sont maintenant visibles sans.
Dans off world, les particules sont des petits traits :
![Capture_off_world_interceptor_particules_20190608](https://user-images.githubusercontent.com/7624262/59139510-b61c0c00-8993-11e9-864c-bb50f648c27e.PNG)
Dans Krazy Ivan, les croix sur le radar ont grossi :
![Capture_krazy_ivan_lines_20190608](https://user-images.githubusercontent.com/7624262/59139516-c03e0a80-8993-11e9-9e4c-00828851f626.PNG)

**Comment by BenjaminSiskoo** [comment]
Krazy Ivan corrigé avec Kronos 1.7.0 Wip du 07/06/2019
