### ISSUE TITLE
[Off-World Interceptor Extreme] Problème d'affichage des highlights sur les menus

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#525]
Kronos Wip du 05/06/2019

Il semble que les traits soit un peu gros

![offworld](https://user-images.githubusercontent.com/12481242/58970948-b7dea780-87ba-11e9-976f-7c8a2b40dcae.PNG)

**Comment by fafling** [comment]
C'est le problème des polygones rectangulaires trop gros voir #514 .
![Capture_off_world_interceptor_polygone_menu](https://user-images.githubusercontent.com/7624262/58996933-884f8f80-87fa-11e9-8a9f-d5ba972a26eb.PNG)

**Comment by BenjaminSiskoo** [comment]
J'ai l'impression que c'est corrigé

**Comment by fafling** [comment]
Oui, c'était bien dû à l'expansion des polygones rectangulaire réglé par le commit 679e8b6 .

**Comment by BenjaminSiskoo** [comment]
Je ferme
