### ISSUE TITLE
[Pandemonium] Problème d'affichage sur la sélection du perso...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#528]
Kronos 1.7.0 du 10/06/2019

A gauche Kronos 1.7.0 du 9 Juin 2019 compilé vers 17H00

![pandemonium](https://user-images.githubusercontent.com/12481242/59186125-63e51180-8b72-11e9-85d2-281d21bc7f7e.PNG)

Le problème vient de ce commit : https://github.com/FCare/Kronos/commit/f81f77f403efbd5b384f2d2c42efce3a991c9581

Mais il corrige les trous dans Sega Rally.

**Comment by fafling** [comment]
@BenjaminSiskoo Est-ce que le problème n'est présent qu'en tesselation triangles using perspective correction? Si oui, c'est un autre exemple de #481 .

**Comment by BenjaminSiskoo** [comment]
@nicolas-charrier oui avec le triangles :)

**Comment by fafling** [comment]
@BenjaminSiskoo Je crois que tu parles de la version du 7 juin, pas du 9 pour le screen de gauche.
Le problème apparaît dans la WIP compilée le 8 vers 1h du matin.
Le commit dont tu parles est effectivement entre les 2.

Je constate aussi la réapparition dans cette WIP de la corruption sur le passeport dans le menu de l'écran titre de Tomb raider :
![Capture_tomb_raider_corruption_passeport_1 7 0](https://user-images.githubusercontent.com/7624262/59307463-db17c400-8c9e-11e9-9a9d-3b129b3e910e.PNG)

**Comment by BenjaminSiskoo** [comment]
Kronos du Wip du 15/07/2019 : toujours le même problème sur Pandemonium.

**Comment by BenjaminSiskoo** [comment]
Pandemonium est maintenant corrigé avec le rasterizer.
