### ISSUE TITLE
[Vrai bios] Problème de boot...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#53]
Astal ne démarre pas avec le vrai bios. Mais démarre avec le bios intégré.

**Comment by barbudreadmon** [comment]
Je confirme avoir le problème sur 2 dumps JAP, et j'ai aussi testé 1 dump USA qui ne détecte pas le code région (`Cs2GetRegionID()` retourne 0, j'ai le soucis sur quelques dumps) donc çà me renvoie au CD player.
PS : testé avec le port libretro sous linux et win64, dump provenant du set redump.

**Comment by jmfergeau** [comment]
Merci pour ce post. Je n'aurais jamais trouvé le problème sans. ^^

**Comment by fafling** [comment]
Problème présent dans la dernière WIP, avec les 2 noyaux.
Depuis la v1.6.0, le jeu reste figé sur le logo SEGA, au lieu de faire un écran noir après.
Pas d'invalid opcode.
Le problème remonte à Yabause.
Testé avec le CD US.

**Comment by fafling** [comment]
Problème toujours présent en WIP du 19/11.

**Comment by BenjaminSiskoo** [comment]
Toujours présent - Kronos du 26/03/2020 (commit VF Remix)

**Comment by BenjaminSiskoo** [comment]
Astal avec le vrai bios ne fonctionne toujours pas avec la version du 14.10.2021

**Comment by FCare** [comment]
Astal fonctionne avec le vrai bios, il faut neanmoins activé le support experimental du cache.

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

En cochant l'option ca en fonctionne pas

**Comment by BenjaminSiskoo** [comment]
Astal ok avec l'option
