### ISSUE TITLE
[Fighting vipers] Ecran noir si bios réel raccourci

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#531]
En v1.7.0 publique, si on appuie sur start pendant l'animation du bios, l'écran reste noir après le logo Sega.
Si on n'interrompt pas l'animation du bios, le jeu démarre correctement.
Problème apparu en WIP du 07/05.
Testé avec le CD japonais.

**Comment by fafling** [comment]
Corrigé pour moi en WIP du 28/06/2017.
@BenjaminSiskoo Est-ce que tu peux vérifier si c'est OK chez toi aussi ?

**Comment by BenjaminSiskoo** [comment]
C'est bon pour moi
