### ISSUE TITLE
[Kronos 1.7.0] On a perdu le frameskip limiter ?

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#533]
Bonjour,

Je viens de tester la dernière version, pour l'instant je ne vois aucune anomalie et ni même d'amélioration sur SF3 et Shining Holy Ark.

Par contre je me suis rendu compte que mon jeu allé beaucoup trop vite, et je me suis aperçu qu'on a perdu l’option frameskip limiter.

**Comment by CloudFR** [comment]
Kronos 1.6.0
![image](https://user-images.githubusercontent.com/50514097/59861078-71737600-9380-11e9-9b86-0b87e3b09e11.png)

Kronos 1.7.0
![image](https://user-images.githubusercontent.com/50514097/59861094-7801ed80-9380-11e9-95c1-9c6efc873d29.png)

Finalement peut être c'est juste la traduction qui est foireuse  ? car l'icone est le même sur les deux écrans.

**Comment by BenjaminSiskoo** [comment]
Hello, 

En fait, le nom a changé car le fonctionnement d'un frameskip limiter ne correspondait pas à ce qui est implémenté dans Kronos (Yaba ou Yabause).  C'est la raison du changement de nom :)

**Comment by fafling** [comment]
@CloudFR Quand elle est activée, l’option Vertical synchronisation limite le frame rate à 60 pour les jeux NTSC et 50 pour les jeux PAL. Est-ce que tu as toujours un jeu trop rapide quand l'option "Activer la synchronisation verticale" est cochée dans Fichier > Paramètres > Général ?

**Comment by CloudFR** [comment]
Bonjour Nicolas, Quand je lance un jeu non, mais j'ai réussi à le provoquer la première de la manière suivante :+1:  (je n'ai pas encore retesté mais je vais le faire)

Tout est coché par défaut dans option général et le F4.

1) Je charge un jeu PAL je joue vite fait.
2) Ejecte le jeu.
3) Je charge un jeu NTSC-J et je fais pareil, mon jeu doit être à 150 / 200%.

**Comment by FCare** [comment]
Ca c'est parce que le temps de chargement est considerer comme un ralentissement du jeu, donc apres, il court apres le temps pour rattraper le bon framerate (la moyenne interne du fps chute et donc pendant quelque temps, ca va a fond pour faire remonter la moyenne de fps). C'est effectivement un bug. MAi jecrois qu'il doit deja etre repertorié dans la liste des bugs

**Comment by fafling** [comment]
C'est peut-être la même chose que j'ai vu sur l'écran titre de Sonic 3D (#466 ).
