### ISSUE TITLE
[libretro] The emulator has a great decrease of performance after last month update on Ubuntu 18.04

### ISSUE THREAD

**Issue by emersonnovais** [FCare/Kronos#534]
Hi, guys and thanks for this great emulator. Since the last month actualization the emulator (core) had a huge slowdown and a decrease of performance . Are the requirements of the system changed or it's a bug? 

I tested games like Virtua Fighter 2 and Terra Cresta and the perfomance is too or more slow than Yabause in my machine.

Thanks!

_My specifications:
Ubuntu 18.04 (64 bits)
Processor: Intel Core i5 460M
Video card: Nvidia GT310M with 340.107 driver_

**Comment by FCare** [comment]
What is your graphic options setup?

I have rewritten the full opengl stack to cover some uncoverable use cases
in the last opengl stack. It means, that for some games, performance is
better but for others it is worse.

In your case, the graphic card is really the bottleneck, you should stick
with almost default video settings.


Le sam. 22 juin 2019 à 03:05, emersonnovais <notifications@github.com> a
écrit :

**Comment by barbudreadmon** [comment]
With the improvements, the emulator now needs a more powerful gpu, especially on Hi-Res games like VF2. Actually i'm impressed it was previously running fine with this gpu, on nvidia website it's marked as an OpenGL3.1 gpu while the emulator requires 3.3

**Comment by barbudreadmon** [comment]
Actually with those low specs, maybe you should give a try to either Kronos standalone (it might run slightly faster without the libretro overhead), or to the yabasanshiro libretro core (the requirements are lower since it's mainly targeted at mobile devices)

**Comment by emersonnovais** [comment]
Ok. Thanks for the information. Must I close this issue?

**Comment by fafling** [comment]
Yabause 0.9.1.4  emulates VF2 incorrectly as a progressive standard definition game instead of double interlaced high resolution, so it emulates 4 times less pixels than Kronos.
![Capture_virtua_fighter2_yabause_0 9 1 4](https://user-images.githubusercontent.com/7624262/59970268-e2be4f00-9561-11e9-93f9-a61c9ca93be1.PNG)
![Capture_virtua_fighter2_1 7 0](https://user-images.githubusercontent.com/7624262/59970269-e520a900-9561-11e9-81f5-2482353ea9f7.PNG)

**Comment by emersonnovais** [comment]
oh, great work! When I will buy a new computer, I will return to Kronos to report some issues that I found.
I will close the issue.
