### ISSUE TITLE
[Compute shader] Corruption RBG0 en mode bitmap

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#537]
En WIP du 28/06/2019, avec l'option Compute shader à on, Kronos affiche des graphismes corrompus sur la couche RBG0 quand elle est en mode bitmap (je n'ai que des exemples en 8 bpp).

Même problème avec le bios réel ou émulé. La corruption change avec la taille OpenGL.

Les jeux suivants sont concernés (tous CD d'origine) :
- Duke Nukem 3D (US) : arrière-plan en jeu.
- Gale racer : arrière-plan en  jeu.
- Powerslave : arrière-plan en jeu.
- Shining the holy ark (US) : arrière-plan de la sélection de la sauvegarde.

Exemple sur Powerslave :
![Capture_powerslave_RBG0_20190628_compute_shader](https://user-images.githubusercontent.com/7624262/60389806-f3724600-9ac8-11e9-8c5c-9e74aefa4a5f.PNG)

**Comment by fafling** [comment]
Mass destruction (E) est aussi concerné.

**Comment by fafling** [comment]
Off-World Interceptor Extreme (U) aussi.

**Comment by FCare** [comment]
Difficile a debugger celui la...

**Comment by fafling** [comment]
Visible dans Grandia et Gungriffon sur le logo Game arts.

Aussi visible dans Mystaria sur l'écran titre ainsi que sur les textes qui présentent les personnages pendant le jeu.
Concernant le texte, c'est un affichage basique du bitmap, le paramètre de rotation ne sert probablement qu'à le scroller. Je pense qu'il doit y avoir un problème de lecture du bitmap en compute shader pour que ça se manifeste même dans cette situation.

Affichage en compute shader :
![Capture_mystaria_CS_texte_20190902](https://user-images.githubusercontent.com/7624262/64136046-01a55100-cdef-11e9-90b5-d7aaf7137aea.PNG)

Affichage correct sans compute shader :
![Capture_mystaria_CS_texte_correct_20190902](https://user-images.githubusercontent.com/7624262/64136103-77a9b800-cdef-11e9-8d66-6accaae0a42f.PNG)

**Comment by fafling** [comment]
Un save state pour accéder à cet écran dans Mystaria :
[mystaria_aragon.zip](https://github.com/FCare/Kronos/files/3567300/mystaria_aragon.zip)

**Comment by fafling** [comment]
Visible aussi dans Shining Force 3, sur l'arrière-plan du menu après l'écran titre, la mer qui entoure la ville de départ, la lave dans les dongeons, et le sol dans les combats.

**Comment by fafling** [comment]
Visible sur l'arrière-plan pendant les courses dans The need for speed / Nissan Presents - Over Drivin' GT-R (et sur le volant s'il était affiché).

**Comment by fafling** [comment]
Visible dans J. League Victory Goal '96 sur l'écran titre (bitmap 16 bpp).

**Comment by fafling** [comment]
Visible sur le ciel dans F1 challenge.

**Comment by fafling** [comment]
Toujours présent en WIP du 08/12.
J'ai trouvé un cas de RBG0 en mode bitmap qui n'a pas cette corruption depuis l'introduction du compute shader : dans F1 challenge, le sol du stand avant la course. La seule chose qui change dans l'écran debug du VDP2 entre le sol du stand, correct, et le ciel en course, corrompu, c'est la Bitmap Palette Address qui passe de 30 à 40.

**Comment by fafling** [comment]
Fixé par un workaround en v2.0.1 publique qui désactive automatiquement le compute shader sur le RBG0 s'il est en mode bitmap.

**Comment by fafling** [comment]
Fixé en WIP du 24-25/09.
