### ISSUE TITLE
[Compute shader] RBG0 incorrect en high res progressif avec OpenGL size 2x ou plus

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#538]
En WIP du 28/06/2019, avec l'option Compute shader à on et OpenGL size est réglé à 2x ou plus, Kronos affiche des graphismes aplatis et décalés sur la couche RBG0 dans les jeux en haute résolution non entrelacé (resolution doublée uniquement horizontalement). Aucun problème en OpenGL 1x.

Même problème avec le bios réel ou émulé.

Les jeux suivants sont concernés (tous CD d'origine) :
- Die hard arcade (US) : arrière-plan pendant la démo, sol et plafond en jeu.
- Pinball graffiti (J) : table des flippers.
- Virtua fighter remix (J) : sol pendant les combats.
- Winter heat (E) : sol du short track.

Exemple dans Pinball graffiti :
![Capture_pinball_graffiti_compute_shader_RBG0_20190628](https://user-images.githubusercontent.com/7624262/60390179-26b8d300-9ad1-11e9-8885-de426bf9f1ec.PNG)

![Capture_pinball_graffiti_compute_shader_RBG0_VDP2_20190628](https://user-images.githubusercontent.com/7624262/60390181-2caeb400-9ad1-11e9-833b-738f193394e4.PNG)

**Comment by fafling** [comment]
En plein écran (résolution de mon écran 1920x1080), le problème n'apparaît qu'à partir de l'OpenGL size 4x.

**Comment by FCare** [comment]
Je viens de fixer chez moi, tu peux mettre a jour et confirmer?

**Comment by fafling** [comment]
C'est réglé chez moi aussi.
