### ISSUE TITLE
[Steep Slope Sliders] Improved Mesh mode : les ombres disparaissent

### ISSUE THREAD

**Issue by FCare** [FCare/Kronos#541]
Dans le jeu, sous le joueur, en mesh mode original, on voit bien l'ombre.
En mesh mode improved, elle disparait quasiment tout le temps...

**Comment by fafling** [comment]
Je ne vois pas d'amélioration par rapport à la WIP précédente, l'ombre est presque toujours absente pendant l'intro en mode amélioré.
![Capture_steep_slope_sliders_20190704](https://user-images.githubusercontent.com/7624262/60689137-707f3000-9eba-11e9-97c0-bc96c3373c05.PNG)

**Comment by fafling** [comment]
En WIP du 12/07, c'est OK chez moi.
![Capture_steep_slope_sliders_20190712](https://user-images.githubusercontent.com/7624262/61164237-cafc3a00-a513-11e9-9adc-1554e5ed8bad.PNG)
