### ISSUE TITLE
[Virtua cop] Sprites entièrement absents

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#542]
En WIP du 28/06/2019, bios réel (le bios émulé plante), les sprites sont invisibles à partir de l'écran qui suit le choix du niveau (on devrait voir le titre du niveau) et pendant le jeu.

Il y a le même problème sur les 3 niveaux.

Les sprites sont visibles pendant l'attract mode et le choix du niveau. La différence est que les sprites devraient être affichés dans la fenêtre W0 quand ils sont invisibles.

![Capture_virtua_cop_20190628](https://user-images.githubusercontent.com/7624262/60632624-f2ae1c80-9e06-11e9-82ab-89cfd75a772f.PNG)

![Capture_virtua_cop_20190628_VDP2](https://user-images.githubusercontent.com/7624262/60632626-f641a380-9e06-11e9-8192-85b5f58e1fb9.PNG)

Le problème est présent en v1.7.0 publique et depuis la 2ème WIP du 08/05.

Testé avec la version US du jeu.

**Comment by FCare** [comment]
Fixé le 04/07/19
