### ISSUE TITLE
Kronos is crashing in latest WIP builds

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#544]
Downloaded wip build from http://www.tradu-france.com/Kronos/ (2019-07-04) and Kronos crash when a game is loaded.

This doesn´t happen in older build from two days ago ((2019-07-02) and all was working as intended, so. There´s some problem in a PR between these two days.

**Comment by LuismaSP89** [comment]
Windows 10 x64
i7 4790k
16 GB DDR3
GTX 970

**Comment by fafling** [comment]
Was it the WIP from 4th july in the morning or in the evening ?
With the morning one, I also experienced crashes with it when starting emulation. The WIP compiled in the evening was working.
Can you try with the las WIP ?

**Comment by LuismaSP89** [comment]
Ok, problem solved. Tested with today's WIP. Closing
