### ISSUE TITLE
Scorcher - black screen

### ISSUE THREAD

**Issue by FCare** [FCare/Kronos#545]
Recent regression:
R0 =  00000000	R12 =  00000000
R1 =  FFFF8888	R13 =  00000000
R2 =  060FDCE8	R14 =  06005F88
R3 =  00226824	R15 =  060D2C9C
R4 =  00000000	SR =   000002F3
R5 =  00000000	GBR =  FFFFFE00
R6 =  E0000000	VBR =  06000400
R7 =  E0000000	MACH = 00000036
R8 =  00000000	MACL = 00003FC1
R9 =  00000000	PR =   00000212
R10 = 00000000	PC =   E000022E
R11 = 00000000

Error: Master SH2 invalid opcode

R0 =  25C04D00	R12 =  00000000
R1 =  060129C0	R13 =  00000000
R2 =  25C04D00	R14 =  060D0C48
R3 =  25C04D00	R15 =  060D0B7C
R4 =  060D0C24	SR =   00000020
R5 =  00000018	GBR =  060CFC40
R6 =  060F0EAC	VBR =  06000000
R7 =  060FC9F4	MACH = 000E4236
R8 =  060FC9FC	MACL = 00000048
R9 =  00000000	PR =   0600AC14
R10 = 00000000	PC =   060129C0
R11 = 00000000

**Comment by fafling** [comment]
Le problème apparaît en v1.7.0 publique, il n'y a ni écran noir, ni invalide opcode dans la WIP précédente du 08/06 (bios réel, CD US d'origine).

**Comment by FCare** [comment]
Fix en cause:

Auteur: LeCare <francois.caron.perso@gmail.com>  2019-06-09 16:38:14
Validateur: LeCare <francois.caron.perso@gmail.com>  2019-06-09 16:38:14
Parent: beaf67c5353436af3f1f368a11ce37a592012667 (Fix hal luminance with GPU Tesselation)
Enfant:  2225480579f06c2b7a075b7b1ae9e7ffdc7ac67a (QT5 compilation shall be easier)
Branche: ati-pb, rbg_compute, remotes/origin/ati-pb, remotes/origin/extui-align, remotes/origin/rbg_compute, remotes/origin/test_sync, remotes/origin/testvdp2, remotes/origin/vdp2_compute, test_sync, testvdp2, vdp2_compute
Suit: 1.7.0
Précède: 

    COPR has the effective dress of the current command proceed - Fix Noon

**Comment by fafling** [comment]
Chez moi, c'est redevenu visible in-game avec la 2ème WIP du 14/07.

**Comment by fafling** [comment]
Plus d'invalid opcodes en WIP du 08/12.
