### ISSUE TITLE
[Last bronx] User clipping pas pris en compte à la sélection du perso

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#546]
En WIP du 12/07 (bios réel ou émulé), la tête du perso sélectionné dépasse du rectangle rouge en arrière plan :
![Capture_last_bronx_select_perso_20190712](https://user-images.githubusercontent.com/7624262/61171449-c7020380-a577-11e9-8a28-0b6953a24e4b.PNG)

Le problème apparaît avec le rework (WIP du 17/03). L'affichage était correct en v1.6.0 :
![Capture_last_bronx_select_perso_v1 6 0](https://user-images.githubusercontent.com/7624262/61171456-ee58d080-a577-11e9-9cc2-e29992c37b2a.PNG)

Dans l'écran debug du VDP1, il y a une commande de user clipping dont les coordonnées correspondent à celles du rectangle rouge. Elle est suivie d'une commande de local coordinates qui place l'origine des coordonnées au milieu du rectangle rouge au lieu de (0, 0). Toutes les commandes de dessin qui suivent ont le user clipping activé.

**Comment by fafling** [comment]
Testé avec le CD US.

**Comment by FCare** [comment]
Reglé en WIP du 16/07/19

**Comment by fafling** [comment]
Effectivement, le problème est résolu dans Last Bronx, mais le fix cause des régression dans d'autres jeux comme signalé par @BenjaminSiskoo :
- Dans Virtual Hydlide, certaines commandes de dessin du VDP1 ne sont pas traitées : il manque le fond vert sur certaines fenêtres, la 1ère lettre de certains mots (sur l'écran titre, manque le P de "Press start button", sur l'écran de chargement, le N de "Now loading"). Le menu d'inventaire in game cause une corruption dès la 1ère utilisation au lieu de la 2ème.
![Capture_virtual_hydlide_titre_manque_P_20190716](https://user-images.githubusercontent.com/7624262/61337378-669fea00-a835-11e9-9cad-9d30a522ceda.PNG)
![capture_virtual](https://user-images.githubusercontent.com/7624262/61337409-820af500-a835-11e9-9b5d-72efd0406905.png)

- Dans DX Nippon Tokkyuu Ryokou Game - Let's Travel in Japan, ce sont des commande de sprites qui dessine le fond de l'écran qui ne sont pas traitées.
![capture_dx_nippon](https://user-images.githubusercontent.com/7624262/61337362-5be55500-a835-11e9-83bb-8e9aaf3e9194.png)

Ces problèmes n'existaient pas dans la WIP précédente.

**Comment by fafling** [comment]
Les commandes touchées par le bug sont en fait traitées et effacent les pixels non transparents compris dans le polygone de leurs coordonnées. C'est visible dans Sega rally où les panneau noir Lancia sont remplacés par du vide. On le voit aussi sur des spectateurs.
Cela explique que ce bug n'engendre pas de problème d'effacement du framebuffer car même si les commandes d'effacement sont touchées, le bug ne change pas leur effet.

Panneaux Lancia noirs remplacés par du vide :
![Capture_sega_rally_problème_clipping1](https://user-images.githubusercontent.com/7624262/62815064-98932c00-bb15-11e9-8b33-883bcaffe797.PNG)

Panneaux visibles si on bouge un peu, car l'ordre des commandes a changé :
![Capture_sega_rally_problème_clipping2](https://user-images.githubusercontent.com/7624262/62815065-9d57e000-bb15-11e9-92ec-7c080127ffe0.PNG)

Pour les commandes que j'ai pu localiser à l'écran, un schéma semble se répéter : ce sont des commandes dont l'activation du user clipping diffère de celle de la commande précédente :
- Une commande n'activant pas le user clipping et suivant une commande qui l'active est transformée en commande d'effacement.
- Une commande activant le user clipping et suivant une commande qui ne l'active pas est aussi transformée en commande d'effacement.
- Cela inclut apparemment aussi la 1ère commande d'un batch de commande (il n'y a pas de commande précédente) : c'est le cas du P de "Press start button" à l'écran titre de Virtual Hydlide.

Cela expliquerait que les jeux qui alternent fréquemment les commandes activant ou pas le user clipping soient très touchés : c'est le cas de Sega rally et Daytona USA circuit edition.

Cela explique aussi que ce ne sont pas toujours les mêmes commandes qui sont touchées vu que cela dépend de l'ordre des commandes, or cet ordre change dès qu'on bouge un peu dans un jeu en 3D.

**Comment by fafling** [comment]
Dans la WIP du 24/08, les régressions sont corrigées et le user clipping de Last Bronx est correct dans les 2 noyaux videos.
