### ISSUE TITLE
[Last bronx] Clignotement du RBG0

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#547]
En WIP du 12/07 (bios réel ou émulé), avec le compute shader desactivé, les pixels du RBG0 clignotent comme si le désentrelacement (le jeu est en double interlaced) était fait en doublant l'épaisseur des lignes de cette couche, ce qui fait se superposer un champ sur l'autre, or dans ce jeu, les 2 champs successifs d'une même frame sont différent sur le RBG0.

C'est visible si on pause l'émulation, le RBG0 semble avoir 240 lignes de résolution verticale :
![Capture_last_bronx_RBG0_20190712](https://user-images.githubusercontent.com/7624262/61172301-a8edd080-a582-11e9-8a5e-38cdd0af618c.PNG)

Sur la console, ce clignotement n'existe pas et le RBG0 a une résolution verticale de 480 lignes. Il n'est restreint à la résolution standard qu'en horizontal (limitation du VDP2 sur cette couche).

Problème déjà présent en v1.6.0. Testé avec le CD US.

**Comment by FCare** [comment]
En effet l'entrelacement dans yabause/yaba/kronos se base sur un doublement des resolutions quand on a besoin... Donc un 480i et en fait un 240p upscalé... pas top mais pas eident a afficher une ligne sur deux sans créer un effet flou assez degueu... Il faudrait faire un désentrelacement , ca risque de bouffer le CPU... Peut etre un BOB.
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/bob-deinterlacing-algorithm

**Comment by fafling** [comment]
Au lieu de désentrelacer, on pourrait calculer le RBG0 à chaque champ sur 480 lignes au lieu de 240 quand le VDP2 est en double interlace. C'est ce qui a l'air d'être fait sur le VDP1 quand il est aussi en double interlace.

Comme tu l'as signalé, le RBG0 tremblote effectivement verticalement avec le compute shader activé.

**Comment by fafling** [comment]
Problème toujours présent en WIP du 19/11.

**Comment by BenjaminSiskoo** [comment]
j'utilise desentrelacement du scanline maintenant @FCare
