### ISSUE TITLE
[Last bronx] Résolution horizontale incorrecte pour le VDP1

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#548]
Dans la WIP du 12/07 (bios réel et émulé), en taille OpenGL identique à la console, la couche de sprites du VDP1 a une résolution horizontale égale à celle du VDP2 (704 pixels).
![Capture_last_bronx_VDP2](https://user-images.githubusercontent.com/7624262/61172549-367eef80-a586-11e9-9cf8-ef44d0542401.PNG)

Capture plein écran pour bien compter les pixels ;-)
![last_bronx_plein_écran_1x_compute_shader_off](https://user-images.githubusercontent.com/7624262/61172582-8bbb0100-a586-11e9-9611-341c67246f56.png)

La commande de system clipping montre que la résolution horizontale du framebuffer est en fait 2 fois plus faible (352 pixels).
![Capture_last_bronx_VDP1](https://user-images.githubusercontent.com/7624262/61172520-beb0c500-a585-11e9-817b-11617471f766.PNG)

Le framebuffer est probablement de type rotation16 et il est doublé par le VDP2. Normalement, la transformation du framebuffer est paramétrée dans la partie 2D du paramètre de rotation A (voir p. 159 de la doc du VDP2). A voir comment c'est paramétré car il y a déjà un doublement automatique du RBG0, qui utilise ce paramètre, en high resolution. Ce doublement horizontal est peut-être automatique aussi sur le framebuffer à partir du moment où il est de type rotation et que le VDP2 est en mode high resolution.

Problème déjà présent en v1.6.0. Testé avec le CD US.

**Comment by FCare** [comment]
Donc si je comprends bien, on devrait avoir un FB de 352x512 et le VDP2 duplique horizontalements les pixels du vdp1? Je peux le faire, ca va etre tres moche...

On n'est pas en mode rotation au niveau du FB VDP1

**Comment by FCare** [comment]
![last bronx](https://user-images.githubusercontent.com/14252808/61214884-73272400-a709-11e9-9c39-daf730fc69af.png)

**Comment by fafling** [comment]
Bon, c'est que le doublement horizontal doit être automatique en high resolution VDP2 pour un framebuffer de 512 pixels de large quelque soit son type. Ni la doc du VDP2, ni les technical bulletins 22 et 24 ne le précisent.

La résolution de la capture semble être de 176x512 pour le VDP1 au lieu de 352x512.

**Comment by fafling** [comment]
Je confirme que c'est correct dans la dernière WIP.

**Comment by fafling** [comment]
Pas de problème en changeant la taille OpenGL.

**Comment by fafling** [comment]
La résolution horizontale du VDP1 est redevenue 2 fois trop élevé en WIP du 19/11 dans les 2 noyaux.
L'affichage était correct en WIP extui-align du 11/09.

**Comment by fafling** [comment]
OK en WIP du 04/04.
