### ISSUE TITLE
[Scorcher] Corruption intermittente sur menu pause en noyau OpenGL

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#550]
Dans la dernière WIP (bios réel et émulé), j'ai une corruption visible par semi-transparence dans le menu pause pendant une course.

![Capture_scorcher_pause_20190715](https://user-images.githubusercontent.com/7624262/61254756-fe360780-a765-11e9-90bc-82e0b3e2c365.PNG)

La corruption disparaît si on désactive le NBG0. Le menu pause est sans doute affiché sur le VDP1. Le NBG0 est en mode bitmap 16 bpp, c'est peut-être un reste d'un essai de menu pause à la Tomb raider / Virtual Hydlide où le framebuffer est transféré vers un NBG bitmap. Le NBG0 n'est pas visible sur la console, soit parce que le framebuffer est complètement opaque, ou bien parce qu'il est mal paramétré dans le registre de VRAM cycle pattern (p. 31-42 de la doc du VDP2).

![Capture_scorcher_pause_VDP2_20190715](https://user-images.githubusercontent.com/7624262/61255086-74873980-a767-11e9-85a0-fdcc729e3f13.PNG)

Cette corruption était visible en v1.6.0, sans effet de semi-transparence. Cet effet apparaît dans les WIP de fin avril, à peu près en même temps que les problème de half-transparency et shadow VDP1 (#475 ). Comme ces problèmes n'apparaissent pas chez tout le monde en fonction du matériel, possible que ce soit le cas ici aussi.

Testé avec le CD US d'origine.

**Comment by fafling** [comment]
La corruption n'est visible qu'avec le noyau OpenGL. En WIP du 02/09, elle est différente :
![Capture_scorcher_pause_OpenGL_20190902](https://user-images.githubusercontent.com/7624262/64205915-6cab6200-ce99-11e9-9c83-2c8abe84ba49.PNG)

**Comment by fafling** [comment]
En WIP accurate_vdp1 du 13/10, il reste une ligne clignotante :
![image](https://user-images.githubusercontent.com/7624262/66719330-9176eb80-edee-11e9-81d3-346a4fe9dd2b.png)

**Comment by fafling** [comment]
Par contre, il y a une corruption temporaire de l'écran à chaque fois qu'on change d'item sur le menu :
![image](https://user-images.githubusercontent.com/7624262/66719412-a6a04a00-edef-11e9-9a9e-4e246105d72e.png)

**Comment by fafling** [comment]
Même corruption temporaire au changement d'item en WIP du 08/12 dans les 2 noyaux.

**Comment by fafling** [comment]
En WIP du 04/04, c'est OK en noyau CS. Le problème est toujours présent en OpenGL.

**Comment by BenjaminSiskoo** [comment]
Même problème en OpenGL avec Kronos du 15.01.2021

**Comment by fafling** [comment]
En WIP du 04/01/2022 :
- La corruption temporaire du menu pause au changement d'item est toujours là en OpenGL uniquement.
- Problème supplémentaire dans les 2 noyaux apparu en WIP du 10/12/2021 (qui fixe le gradient du ciel de Quake dans les 2 noyaux #461 ), le ciel est corrompu quand on sort de la pause :
![image](https://user-images.githubusercontent.com/7624262/148654476-499171a3-be0e-4206-933d-c04b1710f26e.png)

**Comment by fafling** [comment]
J'ajoute que les corruptions qu'on observe pendant les changement d'item du menu pause pourraient bien provenir du RBG1, avec des couleurs et une position différentes de celles qu'on voit en sortie de pause.

**Comment by fafling** [comment]
C'est fixé dans les 2 noyaux chez moi dans la dernière WIP.
@BenjaminSiskoo Est-ce que tu confirmes ?

**Comment by BenjaminSiskoo** [comment]
pour moi c'est bon aussi 
 J'attendais ton retour, ca ron a des diff parfois
