### ISSUE TITLE
[Scorcher] RBG0 non visible

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#551]
Dans la dernière WIP (bios réel et émulé), les nuages en rotation 3D affichés par le RBG0 ne sont visible que si on désactive le ciel affiché par le RBG1.

Sans désactivation du RBG1 :
![Capture_scorcher_RBG1_20190715](https://user-images.githubusercontent.com/7624262/61255313-4bb37400-a768-11e9-978d-ca4aede0b26e.PNG)

Avec désactivation du RBG1 :
![Capture_scorcher_RBG0_20190715](https://user-images.githubusercontent.com/7624262/61255335-6554bb80-a768-11e9-9ab4-8d5f904a5fa5.PNG)

Sur la console, le RBG0 apparaît avec un effet de semi-transparence sur une partie du RBG1, grâce à un effet de special color calculation qui rend semi-transparents les pixels du RBG1 dont la couleur en color RAM a un MSB à 1.

![Capture_scorcher_RBG_VDP2_20190715](https://user-images.githubusercontent.com/7624262/61255426-caa8ac80-a768-11e9-85db-b440d959e9c3.PNG)

Ce problème existait déjà en v1.6.0.

Testé avec le CD US d'origine.

**Comment by fafling** [comment]
Le test est fait sans compute shader car sinon le RBG0 est corrompu : il est en mode bitmap, voir #537 .

**Comment by fafling** [comment]
Dans la WIP du 02/09, le problème existe dans les 2 noyaux, OpenGL et compute shader.

**Comment by fafling** [comment]
Toujours présent en WIP accurate_vdp1 du 13/10.

**Comment by fafling** [comment]
Toujours présent en WIP du 08/12 dans les 2 noyaux.

**Comment by fafling** [comment]
En WIP du 29/12, l'affichage est correct en noyau compute shader.

**Comment by fafling** [comment]
Problème présent de nouveau en CS en WIP du 04/04, réapparu en WIP du 05/01.

**Comment by fafling** [comment]
Fixé en WIP du 07/08/2021.

**Comment by fafling** [comment]
De retour en noyau OpenGL seulement en WIP du 04/01/2022 et depuis celle du 09/12/2021 qui fixe le gradient du ciel de Quake en OpenGL #461 .

**Comment by BenjaminSiskoo** [comment]
Kronos 2.5.0
OpenGL

![image](https://user-images.githubusercontent.com/12481242/217037269-fcf4218c-c1af-40c4-a7c6-deaebf302769.png)


semble ok, je réouvre si besoin
