### ISSUE TITLE
[Deep Fear + Resident Evil] Sound glitches with Kronos 1.7.0

### ISSUE THREAD

**Issue by curseofnight** [FCare/Kronos#556]
Hello. Benjamin Siskoo asked me to do this, so blame him if I'm posting this in the wrong area or wrong way. :)

Ok, jokes aside, when I run Deep Fear or Resident Evil on Kronos 1.7.0 64 bit or 32bit the sound glitches constantly. Here are my PC specs:

Windows 10 64 bit
HP Pavilion Gaming Desktop 690-xxx
AMD Ryzen 5 2400G 3600 MHz 4 Cores
8 gigs of RAM
GeForce GTX 1050 2 gb driver ver. 391.25

I did some experimenting trying to fix the sound issues by changing various settings (toggling multi-threading on/off, changing bios region, etc.,etc.) and I noticed the sound issues where worse with v-sync off. V-sync seemed to be the only setting that affected it at all.

The various graphics settings and filters seem to be broken as well in both versions(they don't appear to do anything).

Kronos 1.6.0 runs both games perfect on this PC, btw. No sound issues and all the neat graphics options work quite well.

Anyway, that's all I got. :)

**Comment by fafling** [comment]
Indeed, I hear sound glitches at regular intervals in public v1.7.0 with Deep fear (japanese CD) with real and emulated bios. This problem doesn't exist from the 27th june WIP on.

However, I find no sound issue for Resident evil (US redump) other than skipping due to the framerate (around 40 on my PC). This skipping also exists in v1.6.0.

**Comment by fafling** [comment]
Deep fear sound glitch has reappeared in the accurate_vdp1 branch in the 28th september WIP. As @LuismaSP89 found out in #688 , it's been merged in the extui-align branch.

**Comment by LuismaSP89** [comment]
Seems that kronos is not the only one affected. I tested some minutes ago with retroarch + yabause & yabasanshiro cores and both of them have this issue also. Makes sense, since kronos and yabasanshiro take the base code of yabause, so, the problem is inherited from yabause.

**Comment by LuismaSP89** [comment]
Seems that this is now fixed on latest nightly Kronos : )

**Comment by fafling** [comment]
I still hear the sound glitch in the 30th august WIP.

**Comment by LuismaSP89** [comment]
For me at least, I can hear the sound but only 1/10 times. I don't know what's the reason but with the latest WIP is working fine except sometimes. If I close the emulator and load again the game, it's solved.

**Comment by LuismaSP89** [comment]
In the 24th september build this is "fix" was reverted, the annoying sound is back again.

**Comment by LuismaSP89** [comment]
FIXED on the most recent build at november 16th 2022 : )

**Comment by BenjaminSiskoo** [comment]
thanks @LuismaSP89
