### ISSUE TITLE
[Windows 64 Bits] Perte de FPS après tests de jeux...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#564]
Quand je teste plusieurs jeux, les FPS diminuent d'un coup. Je suis obligé de rebooter.

Testé avec le fork extui align du 9 Aout 2019

**Comment by FCare** [comment]
Tu peux regarder avec le gestionnaire de taches la conso memoire au fur et a mesure que tu changes de jeu?

**Comment by BenjaminSiskoo** [comment]
J'avais regardé justement, et il n'y avait rien d'anormal a première vue.
