### ISSUE TITLE
[Policenauts] Blank Backgrounds

### ISSUE THREAD

**Issue by fragmental** [FCare/Kronos#566]
Sorry, I don't speak French.

I'm using Kronos v1.7.0 03932d4 core in Retorach 1.7.7 and the screen is mostly black.  I can still click on things and interact with them, but I mostly can't see them.   Here is a screenshot.
![Imgur](https://i.imgur.com/zMbWbzH.png)

Here is a screenshot, of what it looks like in the YabaSanshiro core
![Imgur](https://i.imgur.com/QUDgsHC.png)

**Comment by fafling** [comment]
Hello, this was due to a general regression when fixing a clipping bug on Last bronx #546. Its is fixed since august 24th on the main branch of Kronos.

**Comment by fragmental** [comment]
Thank you for your response!

I updated the core, and tested it and it seems to be fixed now.  The version number in retroarch is v1.7.0 b5fbe1d.
