### ISSUE TITLE
Normal shadow et MSB shadow visibles par-dessus des couches VDP2 de priorité plus élevées en extui-align

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#574]
Dans la dernière WIP rasterizer, dans Decathlete ou Legend of oasis, la normal shadow est dessinée même quand les sprites ne sont pas en top image.

Dans Decathlete, au cours de la demo, on la voit passer par-dessus les temps de la couche NBG0, de priorité 7, alors qu'elle est en priorité 5 :
![Capture_decathlete_rasterizer4_shadow](https://user-images.githubusercontent.com/7624262/63573842-b1c0c180-c586-11e9-9195-6ae3dbcff48f.PNG)

Dans Legend of oasis, sur l'écran de pause affiché par le NBG1, l'ombre des personnages est visible :
![Capture_legend_of_oasis_rasterizer4_shadow](https://user-images.githubusercontent.com/7624262/63573939-e7fe4100-c586-11e9-9765-bbc122053139.PNG)

**Comment by fafling** [comment]
Le problème est indépendant du matériel.

**Comment by fafling** [comment]
Pour préciser, la normal shadow ne doit pas être visible même si la couche VDP2 qui est devant est semi transparente. Elle n'est rendue que sur les pixels où les sprites sont en top image (p. 256 de la doc du VDP2 ). C'est la même chose pour la MSB shadow.

**Comment by fafling** [comment]
Dans Legend of oasis, le problème n'est visible que si l'ombre n'est pas orange, voir #529 .

**Comment by FCare** [comment]
Pas specifique au rasterizer. C'est un pb global. Je le traiterais apres la stabilisation du rasterizer

**Comment by fafling** [comment]
Problème visible aussi dans Last Bronx :
![Capture_last_bronx_shadow_20190824](https://user-images.githubusercontent.com/7624262/63900169-f7a2dd00-c9ff-11e9-96d6-e40cb33489d4.PNG)

**Comment by fafling** [comment]
Même problème sur la MSB shadow dans Astal, visible par-dessus le RBG0 qui devrait la cacher :
![Capture_astal_msb_shadow_20190911](https://user-images.githubusercontent.com/7624262/64739913-cd6b1800-d4f3-11e9-9f32-7cfc1e65b328.PNG)

**Comment by fafling** [comment]
Fixé en OpenGL dans la WIP accurate_vdp1 du 24/09.

**Comment by fafling** [comment]
Fixé dans les 2 noyaux en WIP extui-align du 19/11.
