### ISSUE TITLE
CMake build fail macOS

### ISSUE THREAD

**Issue by mhamilt** [FCare/Kronos#575]
Using CMake to build on macOS there are errors relating to [`Unknown type name ‘off64_t’](https://stackoverflow.com/questions/22663897/unknown-type-name-off64-t/34853360)

##### Machine

Macbook Pro 2017 13-inch, 2017
Macbook Pro Retina 2012

##### OS

High Sierra 10.13.6 
Mojave 10.14.0 

***

### Errors

**Error Log**

```
OFF64_T.c:25:12: error: use of undeclared identifier 'off64_t'
  ('0' + ((SIZE / 10000)%10)),
           ^
OFF64_T.c:23:22: note: expanded from macro 'SIZE'
#define SIZE (sizeof(off64_t))
                     ^
OFF64_T.c:26:12: error: use of undeclared identifier 'off64_t'
  ('0' + ((SIZE / 1000)%10)),
           ^
OFF64_T.c:23:22: note: expanded from macro 'SIZE'
#define SIZE (sizeof(off64_t))
                     ^
OFF64_T.c:27:12: error: use of undeclared identifier 'off64_t'
  ('0' + ((SIZE / 100)%10)),
           ^
OFF64_T.c:23:22: note: expanded from macro 'SIZE'
#define SIZE (sizeof(off64_t))
                     ^
OFF64_T.c:28:12: error: use of undeclared identifier 'off64_t'
  ('0' + ((SIZE / 10)%10)),
           ^
OFF64_T.c:23:22: note: expanded from macro 'SIZE'
#define SIZE (sizeof(off64_t))
                     ^
OFF64_T.c:29:12: error: use of undeclared identifier 'off64_t'
  ('0' +  (SIZE    % 10)),
           ^
OFF64_T.c:23:22: note: expanded from macro 'SIZE'
#define SIZE (sizeof(off64_t))
```

###### Notes

On a side note, the [Mac install readme](https://github.com/FCare/Kronos/blob/extui-align/yabause/README.MAC) is out of date, referencing a missing `src/cocoa` directory. so, separate build instructions might be worthwhile

**Comment by FCare** [comment]
Hi, thanks for testing Kronos on a MacOS. I have no macOS devices, so I am not able to maintain the MacOS port.
If you have some patches to fix this on macOS, do not hesitate to propose a pull request and I will merge them.

**Comment by mhamilt** [comment]
I'll see what I can come up with, but it will likely take a while. Though, [barbudreadmon](https://github.com/barbudreadmon) fairly active on that front.
