### ISSUE TITLE
[Bug Too] - Fork Rasterizer - Menu pause corrompue... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#578]
![bugtoo](https://user-images.githubusercontent.com/12481242/63582180-df166b00-c598-11e9-82f8-d1d51f66b063.PNG)

**Comment by fafling** [comment]
Dans la WIP du 23/08, le problème se produit uniquement en noyau compute shader.

**Comment by fafling** [comment]
Dans la WIP du 29/08, le contenu du framebuffer hors pause s'affiche de nouveau en pause, mais il reste des différences entre les 2 :
- Le haut et le bas sont tronqués.
- Il y a un décalage vertical.
- Il y a un changement de pixellisation.
![Capture_bug_too_pause_rasterizer_20190829](https://user-images.githubusercontent.com/7624262/63971883-dd243e80-caa7-11e9-920b-142280a636f5.PNG)

**Comment by fafling** [comment]
Testé avec le CD version PAL.

**Comment by fafling** [comment]
En progrès sur la 2ème WIP, il ne reste plus que les trous en bas de l'image.

**Comment by fafling** [comment]
Corrigé en WIP du 01/09.
