### ISSUE TITLE
[Virtual Hydlide] - Fork Rasterizer - Menu in game corrompue... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#581]
![virtual](https://user-images.githubusercontent.com/12481242/63582836-19ccd300-c59a-11e9-94b5-35ef31fe462d.PNG)

**Comment by fafling** [comment]
Dans la WIP du 29/08, avec le noyau compute shader, le 1er affichage du plan ou de l'inventaire est presque correct, avec un petit décalage vertical. Par contre, les affichages suivants sont corrompus :
![Capture_virtual_hydlide_plan_rasterizer_20190829](https://user-images.githubusercontent.com/7624262/63976507-c7b41200-cab1-11e9-852c-6c0db523a9c6.PNG)
![Capture_virtual_hydlide_inventaire_rasterizer_20190829](https://user-images.githubusercontent.com/7624262/63976520-cda9f300-cab1-11e9-8812-7f49516f2156.PNG)

Testé avec le CD US.

**Comment by fafling** [comment]
Dans la WIP du 01/09, il n'y a plus de corruption sur l'écran de cartes.
Il reste une corruption au 1er ou 2ème affichage de l'inventaire, mais pas les affichages suivant.

**Comment by BenjaminSiskoo** [comment]
Wip du 02/09/2019
![virtualhydlide](https://user-images.githubusercontent.com/12481242/64125654-08aa7000-cdab-11e9-97c0-fa1aca207d5a.PNG)

**Comment by BenjaminSiskoo** [comment]
Ca semble corrigé le 10/10/2019

**Comment by fafling** [comment]
Pas d'accord pour la clôture, j'ai de nouveau eu la même corruption au 1er affichage de l'inventaire.

**Comment by BenjaminSiskoo** [comment]
Le fork rasterizer est kaput.
