### ISSUE TITLE
[Wing Arms] - Nuages noir

### ISSUE THREAD

**Issue by backgamon** [FCare/Kronos#582]
Sur la version Beta du 23/08/19.
Le jeu fonctionne BEAUCOUP mieux que sur Yaba, mais les nuages sont noir:
![Screenshot - 23_08_2019 , 20_02_24](https://user-images.githubusercontent.com/39404647/63613593-6a1b5380-c5e1-11e9-949b-724b8e747d42.jpg)

**Comment by BenjaminSiskoo** [comment]
Bizarre pas de soucis avec les nuages : tu as mis des filtres en particulier ?
![wingarms](https://user-images.githubusercontent.com/12481242/63614320-03973500-c5e3-11e9-97a7-1168b4a94d4c.PNG)

**Comment by BenjaminSiskoo** [comment]
PS je savais pas qu'il y avait une vue autre que cockpit ^^

**Comment by backgamon** [comment]
Et j'ai finalement trouvé le problème -> Transparence de trame = originale...
J'avais amélioré :/

**Comment by FCare** [comment]
Ok donc pb avec le resize...

**Comment by FCare** [comment]
C'est pas un pb avec le resize mais un pb avec le mode mesh improved...

**Comment by FCare** [comment]
FIxé le 23/08/2019
