### ISSUE TITLE
  [3D Baseball] - Rasterizer - Transparence dans les menus manquantes... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#587]
![3dbaseball](https://user-images.githubusercontent.com/12481242/63635189-fc623c80-c65f-11e9-9222-de7d2b56e109.PNG)

J'étais en train de tester la version 64 bits pour voir les fps donc pas besoin de s'occuper de la question pourquoi il y a 2 photos.

**Comment by BenjaminSiskoo** [comment]
Même problème avec la WIP du 29.08.2019

**Comment by FCare** [comment]
Pb sur le core openGL egalement
