### ISSUE TITLE
[BlamMachineHead] - Rasterizer - Problème d'affichage du ciel en arrière plan...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#589]
![blam](https://user-images.githubusercontent.com/12481242/63635406-8dd2ae00-c662-11e9-91a9-37607a24bb3f.PNG)

**Comment by BenjaminSiskoo** [comment]
Même problème avec la WIP du 29.08.2019

**Comment by FCare** [comment]
les polygones sont des triangles ou C=D

**Comment by FCare** [comment]
a priori, reglé ou presque le 01/09/2019

**Comment by fafling** [comment]
En WIP du 02/09, les traits verticaux sont encore présents dans la partie la plus ombre de l'arrière-plan :
![Capture_machine_head_CS_traits_verticaux_ciel_20190902](https://user-images.githubusercontent.com/7624262/64132726-17584d80-cdd2-11e9-8dd6-49ed90a4b5da.PNG)

Les traits disparaissent si on tourne.

Quand on est immobile, cette partie est dessinée par une série de polygones avec des côtés verticaux, qui utilisent mesh et Gouraud shading :
![Capture_machine_head_CS_traits_verticaux_ciel_20190902_VDP1](https://user-images.githubusercontent.com/7624262/64132773-64d4ba80-cdd2-11e9-9482-273afc3078e9.PNG)

Vu les coordonnées, le VDP1 les dessine par colonne de pixels.

**Comment by BenjaminSiskoo** [comment]
Toujours présent avec la WIP du 25/11/2019

**Comment by BenjaminSiskoo** [comment]
Toujours présent avec la wip du 15/12/2019

**Comment by BenjaminSiskoo** [comment]
Corrigé le 28/12/2019
