### ISSUE TITLE
[Crows - The Battle Action] - Rasterizer - Ombres manquantes sous les persos... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#593]
![crows the battle action](https://user-images.githubusercontent.com/12481242/63635706-d9d32200-c665-11e9-8392-6e528af13b83.PNG)

**Comment by BenjaminSiskoo** [comment]
Même problème avec la WIP du 29.08.2019

**Comment by FCare** [comment]
Fixé le 01/09/2019
