### ISSUE TITLE
[Dragon Ball Z] - Rasterizer - Natif moins précis...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#594]
Ca touche tous les jeux j'ai l'impression, je suis en natif sur les 2 émulateurs sans aucun filtre.

A gauche la version Rasterizer on dirait qu'il y a un flou sur les lettres. A droite la version 1.7.0 public.

![dragonballZ](https://user-images.githubusercontent.com/12481242/63635854-a5606580-c667-11e9-8ff4-0ba8f4b915bc.PNG)

**Comment by BenjaminSiskoo** [comment]
NoonSuiko Enbu ou Slam & Jam 
![nbajam](https://user-images.githubusercontent.com/12481242/63636044-5667ff80-c66a-11e9-9281-4c23ed6710f8.PNG)

**Comment by FCare** [comment]
Pas present le 0/09/2019 sur Linux 64bits, Intel

**Comment by BenjaminSiskoo** [comment]
Corrigé le 02/09/2019
