### ISSUE TITLE
[Gex] - Rasterizer - Problème d'affichage sur la pause...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#595]
![gex](https://user-images.githubusercontent.com/12481242/63635936-be1d4b00-c668-11e9-8a7a-f221eb0712e2.PNG)

**Comment by BenjaminSiskoo** [comment]
Wip du 29/08/2019

![gex](https://user-images.githubusercontent.com/12481242/63963994-6af72e00-ca96-11e9-9eab-d859cd025dcc.PNG)

**Comment by FCare** [comment]
Present sur le core OpenGL egalement.

**Comment by BenjaminSiskoo** [comment]
Pareil avec la Wip du 15/01/2020

**Comment by fafling** [comment]
Toujours présent en WIP du 03/03 dans les 2 noyaux.

Peut-être un problème d'erase incorrect du framebuffer car le contenu des sprites avant la pause est effacé dans Kronos et seul est affiché ce qui est dessiné par-dessus comme le mot "PAUSED" (on ne voit que ces commandes de dessin pendant la pause).

Le jeu n'utilise pas de commande d'effacement, mais les sprites opaques de l'arrière-plan recouvre tout l'écran, donc il n'utilise pas forcément la fonction d'erase du VDP1.

Un save state pour aller plus vite en jeu :
[gex_debut_jeu.zip](https://github.com/FCare/Kronos/files/4295908/gex_debut_jeu.zip)

Testé avec la version PAL.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 03/04/2020
