### ISSUE TITLE
[Tomb Raider] - Rasterizer - Transparence du menu pause...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#596]
![tomb raider](https://user-images.githubusercontent.com/12481242/63636109-3553de80-c66b-11e9-96c3-95fb31f157f3.PNG)

**Comment by BenjaminSiskoo** [comment]
Wip du 29/08/2019

Lignes verticales dans le menu pause

![tomb raider](https://user-images.githubusercontent.com/12481242/63963751-00de8900-ca96-11e9-9d20-edca213bda97.PNG)

**Comment by fafling** [comment]
On a une différence, je ne vois des lignes que dans des trous dans l'image copiée du framebuffer. Dans la 1ère pause, c'est uniquement sur le côté, où il n'y a pas d'image hors pause.
![Capture_tomb_raider_pause_20190829_1](https://user-images.githubusercontent.com/7624262/63975704-e913fe80-caaf-11e9-976a-c0f23219fd2d.PNG)

Dans les pauses suivantes, des trous avec des lignes verticales apparaissent en bas :
![Capture_tomb_raider_pause_20190829_2](https://user-images.githubusercontent.com/7624262/63975711-ec0eef00-caaf-11e9-93c8-aecb3c971a6e.PNG)

Testé avec le CD US.

**Comment by BenjaminSiskoo** [comment]
Réglé pour moi j'attends la confirmation de @nicolas-charrier

**Comment by fafling** [comment]
Pas réglé, les lignes verticales ont disparu, mais j'ai quasiment les mêmes trous à la 2ème pause.
![Capture_tomb_raider_pause_20190829_2_2](https://user-images.githubusercontent.com/7624262/63982858-7a8d6b80-cac4-11e9-8a22-90fee597c2f6.PNG)

**Comment by fafling** [comment]
Problème réglé en WIP du 01/09.
