### ISSUE TITLE
Bordures de polygones incorrectes en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#598]
Dans Sonic 3D en WIP du 24/08, avec le noyau compute shader uniquement, il y a des trous entre les polygones dans la piste du special stage.
![Capture_sonic3d_special_stage_rasterizer_20190824](https://user-images.githubusercontent.com/7624262/63898405-2cf7fc80-c9f9-11e9-95ec-7a2c5afff1a4.PNG)

Commandes des polygones de chaque côté des trous alignés à gauche de la piste :
![Capture_sonic3d_special_stage_rasterizer_20190824_VDP1_1](https://user-images.githubusercontent.com/7624262/63898409-2f5a5680-c9f9-11e9-83dd-3742428445db.PNG)
![Capture_sonic3d_special_stage_rasterizer_20190824_VDP1_2](https://user-images.githubusercontent.com/7624262/63898412-32554700-c9f9-11e9-8786-74312a9bc0ce.PNG)

Les coordonnées se chevauchent. Il devrait y avoir un chevauchement d'un pixel au lieu d'un trou d'un pixel entre les 2 polygones.

Le save state pour afficher le special stage directement.
[sonic3D_special_stage_trous_rasterizer.zip](https://github.com/FCare/Kronos/files/3553193/sonic3D_special_stage_trous_rasterizer.zip)

Testé avec le CD japonais.

**Comment by FCare** [comment]
Aucun trou dans la WIP du 01/09/2019 sous linux 64 bits, qt, intel HD

**Comment by fafling** [comment]
Je vois les mêmes trous dans la WIP du 02/09.

**Comment by fafling** [comment]
Toujours présent en WIP du 01/12.

**Comment by fafling** [comment]
Les trous ont disparu en WIP du 20/12, Par contre, des bordures de polygones incorrectes apparaissent dans cette WIP :
![image](https://user-images.githubusercontent.com/7624262/71299697-089ca300-238f-11ea-8fe0-6320125644a6.png)

Save state :
[sonic3D_special_stage_bordures_polygones_incorrectes_CS.zip](https://github.com/FCare/Kronos/files/3990787/sonic3D_special_stage_bordures_polygones_incorrectes_CS.zip)

**Comment by fafling** [comment]
En WIP du 30/12, le même problème de bordure de polygones incorrecte en noyau CS est visible dans Shining Force 3 (PAL) pendant le survol de la carte pendant l'intro :
![image](https://user-images.githubusercontent.com/7624262/71596293-3e841900-2b3f-11ea-999a-84c88d3c6052.png)

Save state :
[sf3_survol_carte_intro.zip](https://github.com/FCare/Kronos/files/4010726/sf3_survol_carte_intro.zip)

**Comment by fafling** [comment]
Des bordures blanches en bas des murs sont visibles de manière intermittente dans Powerslave. Ce ne sont pas des trous car l'arrière-plan VDP2 est noir.
![image](https://user-images.githubusercontent.com/7624262/71599040-8f007400-2b49-11ea-8099-18844eb92fe4.png)

Save state :
[powerslave_bordures_polygones.zip](https://github.com/FCare/Kronos/files/4010900/powerslave_bordures_polygones.zip)

**Comment by fafling** [comment]
Visible aussi dans Duke Nukem (U) :
![image](https://user-images.githubusercontent.com/7624262/71601734-0a1b5780-2b55-11ea-9e54-48ada7bce0ca.png)

**Comment by fafling** [comment]
Problème en grande partie réglé par le rendu par ligne en WIP du 16/03. Les bordures incorrectes ne sont plus visibles que dans Powerslave et Duke Nuke 3D :
![image](https://user-images.githubusercontent.com/7624262/76810763-84bc5080-67ef-11ea-956a-94ec7cebedc0.png)
[powerslave_bordures_polygones_CS_20200317.zip](https://github.com/FCare/Kronos/files/4340926/powerslave_bordures_polygones_CS_20200317.zip)

**Comment by fafling** [comment]
Les dernières bordures incorrectes ont été fixés en WIP du 19/03.

**Comment by BenjaminSiskoo** [comment]
Kronos 14.01.2022
Mode CS

Trou dans le sol 

Savestate : 
[MK-8106250_000.zip](https://github.com/FCare/Kronos/files/7869729/MK-8106250_000.zip)
