### ISSUE TITLE
[Sonic 3D] Gouraud shading incorrect en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#599]
Dans la WIP du 24/08, avec le noyau compute shader uniquement, le Gouraud shading est incorrect dans le special stage sur l'oeil de Sonic.
![Capture_sonic3d_gouraud_shading_special_stage_rasterizer_20190824](https://user-images.githubusercontent.com/7624262/63898802-b8be5880-c9fa-11e9-9ca2-fcf4ab2c5d77.PNG)

Affichage correct en noyau OpenGL :
![Capture_sonic3d_gouraud_shading_special_stage_correct_20190824](https://user-images.githubusercontent.com/7624262/63898804-bbb94900-c9fa-11e9-99b8-d42a349cead6.PNG)

Le save state pour afficher ce point du special stage directement.
[sonic3D_special_stage_gouraud_shading_rasterizer.zip](https://github.com/FCare/Kronos/files/3553200/sonic3D_special_stage_gouraud_shading_rasterizer.zip)

Testé avec le CD japonais.

**Comment by FCare** [comment]
Fixé le 01/09/2019

**Comment by fafling** [comment]
C'est OK dans la WIP du 02/09.
