### ISSUE TITLE
[Sakura Taisen 2] Problème d'affichage avec les vidéos...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#60]
UoYabause 1.3.1
Fork : François/Devmiyax

Problème avec les vidéos (intro et in game). Les vidéos s'étirent sur la largeur. Sorte de scintillements.

![1salurataisenvideointro](https://user-images.githubusercontent.com/12481242/35680256-ba78d302-0751-11e8-99ec-717c4a9d1dc1.JPG)
![1sakurataisonintro2](https://user-images.githubusercontent.com/12481242/35680250-b5fb8a54-0751-11e8-8edb-2f6be61ba086.JPG)

**Comment by BenjaminSiskoo** [comment]
Même genre de problème avec World Advanced Daisenryaku - Sakusen File. Mais in game.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 1er Février 2018

**Comment by FCare** [comment]
J'ai du retirer le patch, il casse Albert Odyssey

**Comment by BenjaminSiskoo** [comment]
Le problème de vidéo étiré est réglé.
