### ISSUE TITLE
[Last Bronx] Trous entre les sprites dans l'écran de chargement en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#600]
Dans la WIP du 24/08, avec le noyau compute shader uniquement, le 1er écran de chargement comporte des trous entre les côtés verticaux des sprites.
![Capture_last_bronx_loading_trous_rasterizer_20190824](https://user-images.githubusercontent.com/7624262/63899778-77c84300-c9fe-11e9-857b-289c25926ea7.PNG)

Il ne devrait pas y avoir de trous car la coordonnée X des normal sprites ajoutées à la largeur de texture donne une coordonnées X adjacente à celle du normal sprite situé à droite.

Testé avec le CD US.

**Comment by FCare** [comment]
Fixé le 01/09/2019

**Comment by fafling** [comment]
C'est OK en WIP du 02/09.
