### ISSUE TITLE
[Scorcher] Ligne scintillante dans le menu pause...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#605]
WIP du 29.08.2019
![scorcher](https://user-images.githubusercontent.com/12481242/64062154-950a3680-cbe3-11e9-8350-38fbd2530499.PNG)

**Comment by fafling** [comment]
Doublon du br #550 .

**Comment by fafling** [comment]
Toujours présent en WIP du 08/12 dans les 2 noyaux.

**Comment by BenjaminSiskoo** [comment]
CCorrigé le 03/04/2020 en CS mais pas en Opengl
