### ISSUE TITLE
[Sky target] Artefacts sur le NBG0

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#608]
En WIP du 03/09, il y a des artefacts sur le NBG0 pendant le jeu du côté gauche de l'écran :
![Capture_sky_target_artefacts_NBG0_20190903](https://user-images.githubusercontent.com/7624262/64215090-6b872e80-ceb3-11e9-81a5-a6231e86a958.PNG)

Problème présent dans les 2 noyaux.
Il existait déjà en v1.6.0.

Testé avec le CD jap.

**Comment by BenjaminSiskoo** [comment]
2-3 autres jeux ont ce problème

**Comment by fafling** [comment]
Toujours présent dans la WIP vdp1_accurate du 13/10.

**Comment by fafling** [comment]
Toujours présent dans les 2 noyaux en WIP du 08/12.

**Comment by fafling** [comment]
Toujours présent en WIP du 21/05/2021.

**Comment by BenjaminSiskoo** [comment]
Corrigé l e 21.05.2021
