### ISSUE TITLE
[True Pinball] - CS - la table n'est plus affiché... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#609]
Kronos WIP du 03/09/2019, testé avec le CS (bug introduit avec les correctifs de Devmiyax).
![truepinball](https://user-images.githubusercontent.com/12481242/64248911-b2f0d780-cf12-11e9-8d90-49afbec60d27.PNG)

**Comment by fafling** [comment]
Probablement causé par une implémentation basique du registre de cycle pattern du VDP2.
