### ISSUE TITLE
[Dark Savior] - CS : menu manquant...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#610]
Kronos WIP du 03/09/2019, testé avec le CS (bug introduit avec les correctifs de Devmiyax).
![darksavior](https://user-images.githubusercontent.com/12481242/64248998-f0edfb80-cf12-11e9-9cbb-818fb24a3204.PNG)

**Comment by fafling** [comment]
Probablement causé par une implémentation basique du registre de cycle pattern du VDP2.
