### ISSUE TITLE
[Wing arms] RBG0 corrompu en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#611]
Suite à la 2ème WIP du 03/09, dans les 2 noyaux :
- le NBG1 disparaît dans l'écran titre et les menus qui suivent :
![Capture_wing_arms_titre_NBG1_manquant_CS_20190904](https://user-images.githubusercontent.com/7624262/64292795-71404b00-cf6b-11e9-924f-02ecdecb639b.PNG)
- le NBG0 disparaît pendant le jeu (trous bleus dans le cockpit) :
![Capture_wing_arms_cockpit_NBG0_manquant_CS_20190904](https://user-images.githubusercontent.com/7624262/64292786-6e455a80-cf6b-11e9-947e-0f274e608e03.PNG)

Testé avec le CD US.

**Comment by fafling** [comment]
Dans les 2 noyaux, si l'option compute shader est décochée, le RBG0 est corrompu :
![Capture_wing_arms_corruption_RBG0_OGL_20190904](https://user-images.githubusercontent.com/7624262/64293105-35f24c00-cf6c-11e9-9cab-ff415d23882d.PNG)

**Comment by fafling** [comment]
En WIP du 10/09, il n'y a plus de couche manquante. Le problème était dû à un début de prise en compte du registre de cycle pattern du VDP2 pour déterminer si une couche NBG est affichée par la console (commit d0e27f7 annulé par 1b93469). Il faudrait afficher le contenu de ce registre dans la fenêtre debug du VDP2 pour savoir si la disparition incorrecte des couches NBG venait d'une mauvaise alimentation de ce registre par Kronos, ou bien d'un bug dans la prise en compte de sa valeur.
Par contre, le RBG0 est toujours corrompu sans l'option compute shader. Ce problème est aussi apparu dans la WIP du 03/09.

**Comment by fafling** [comment]
Toujours présent en WIP accurate_vdp1 du 13/10.
Le RBG0 utilise la table de coefficient qui est impactée par le patch f8f0d11 :
![image](https://user-images.githubusercontent.com/7624262/66714382-74262b00-edb6-11e9-8f8c-e02f4a55138b.png)

**Comment by fafling** [comment]
En 2ème WIP du 08/12, la corruption est inchangée en OpenGL, par contre en compute shader, le RBG0 devient monochrome et clignote (problème absent dans la 1ère WIP) :
![image](https://user-images.githubusercontent.com/7624262/70390151-c5bef080-19c8-11ea-82a2-05c8501bd99c.png)

**Comment by fafling** [comment]
En WIP du 30/12, le noyau compute shader affiche une corruption qui se rapproche de celle du noyau OpenGL :
![image](https://user-images.githubusercontent.com/7624262/71601451-c83de180-2b53-11ea-9205-42eff7d6bf04.png)

**Comment by fafling** [comment]
Fixé en noyau OpenGL en v2.0.1 publique. La corruption est toujours présente en noyau CS.

**Comment by BenjaminSiskoo** [comment]
@fafling ca semble corrigé avec la Wip du 15/10/2020

**Comment by fafling** [comment]
Non, on est revenu au RBG0 monochrome clignotant de la WIP du 08/12.
Attention de mettre Compute shader à on en noyau CS.

**Comment by fafling** [comment]
Réglé en WIP du 19/03.
