### ISSUE TITLE
[Shining Force 3] Artefacts sur le texte en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#613]
En WIP du 04/09, avec le noyau compute shader uniquement, des points blancs sont visibles dans les textes (la corruption de l'arrière-plan est due au bug #537) :
![Capture_sf3_debut_CS_20190904](https://user-images.githubusercontent.com/7624262/64407553-e2275600-d084-11e9-8a7e-2d6b61bdfff1.PNG)

Les lettres sont dessinées par des commandes de distorted sprites qui utilisent l'end code :
![Capture_sf3_debut_CS_20190904_VDP1](https://user-images.githubusercontent.com/7624262/64407567-eb182780-d084-11e9-8be2-4278e80965c0.PNG)

Testé avec le CD PAL.

**Comment by FCare** [comment]
On utilise un distorted sprite mais dans les faits, la texture n'est pas
distorted, il faut que je le detecte et que j'utilise un appel "normal
sprite" a la place.

Le ven. 6 sept. 2019 à 09:01, nicolas-charrier <notifications@github.com> a
écrit :

**Comment by fafling** [comment]
Toujours présent en WIP du 10/12.

**Comment by fafling** [comment]
En WIP du 17/12, l'affichage du texte est correct, mais la fée disparaît partiellement :
![image](https://user-images.githubusercontent.com/7624262/71045783-9cbffd80-2136-11ea-883e-f1218196b1b4.png)

**Comment by FCare** [comment]
Fixé le 25/12/2019
