### ISSUE TITLE
[Tama] Transparence incorrecte du logo Time Warner en extui-align

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#620]
En WIP du 11/09, dans les 2 noyaux, bios réel ou émulé, le fond du logo Time Warner est transparent au lieu d'être blanc. On voit la couche VDP2 qui se trouve derrière :
![Capture_tama_logo_time_warner_20190911](https://user-images.githubusercontent.com/7624262/64826881-65cfce00-d5c2-11e9-978e-ff4ebe9b8843.PNG)

Affichage correct dans Yabause v0.9.14 :
![Capture_tama_logo_time_warner_yabause](https://user-images.githubusercontent.com/7624262/64826865-5a7ca280-d5c2-11e9-9381-7255b8ed08bc.PNG)

Le problème existe en v1.7.0 publique, et remonte à Kronos v1.0.0. Je n'ai pas trouvé de version de UOYabause avec le même problème, bien que la WIP 0.5.2 du 06/08/2017 n'affiche plus le logo.

Dans Yabause, le fond blanc fait partie de la couche de sprites. Donc soit Kronos ne dessine pas ce fond blanc, soit il considère de manière incorrecte cette couleur blanche comme transparente.
Dans la fenêtre debug du VDP1, il n'y a pas de commande de dessin remplissant de blanc le framebuffer. Soit c'est un autre batch de commandes qui fait ce remplissage, soit il est fait par la fonction VDP1 d'effacement du framebuffer d'affichage.

Testé avec le CD jap.

**Comment by FCare** [comment]
reglé dans la branche vdp1_accurate

**Comment by fafling** [comment]
En fait c'est fixé depuis la 1ère WIP accurate_vdp1 du 14/09, mais dans la WIP accurate_vdp1 du 23/09, seul le fond blanc s'affiche.

**Comment by fafling** [comment]
De nouveau correct en OpenGL en accurate_vdp1 dans la WIP du 24/09.

**Comment by fafling** [comment]
Fixé dans les 2 noyaux en WIP extui-align du 19/11.
