### ISSUE TITLE
[Tama] Freeze au début de l'intro

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#621]
En WIP du 11/09, dans les 2 noyaux, bios réel ou émulé, l'intro se fige dès le début. Le jeu ne répond plus aux commandes, mais l'interface de Kronos n'est pas bloquée.

Le problème est présent en v1.7.0 publique. Le problème n'existe pas dans Yabause v0.9.14 et apparaît dans UOYabause v0.5.0.

Testé avec le CD jap.

**Comment by fafling** [comment]
Toujours présent en WIP accurate_vdp1 du 12/10.

**Comment by fafling** [comment]
Toujours présent en WIP extui-align du 19/11.

**Comment by BenjaminSiskoo** [comment]
Tama boot maintenant !

**Comment by BenjaminSiskoo** [comment]
Kronos Wip du 14.10.2021
Mode CS
Bios intégré / Vrai Bios

Le jeu freeze sur l'intro vidéo.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 04.02.2022

Le jeu va un peu plus loin mais reste bloqué avec le correctif du 3 Février 2022

Savestate : [T-4801G_000.zip](https://github.com/FCare/Kronos/files/8003347/T-4801G_000.zip)

**Comment by BenjaminSiskoo** [comment]
Kronos 2.5.0
Cs

Freeze ici : 
![image](https://user-images.githubusercontent.com/12481242/217037952-0c8f754d-c02d-4b3d-bfeb-683259bd5570.png)

**Comment by fafling** [comment]
Fixé en extui-align depuis le merge de la branch syncTiming le 23/08/2023.
