### ISSUE TITLE
[Panzer dragoon] Effet de lumière manquant sur le RBG0

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#624]
En WIP du 11/09, dans les 2 noyaux, il manque un effet d'éclaircissement progressif vers l'horizon sur le plan 3D affiché par le RBG0 dans le 1er niveau du jeu. Le problème apparaît en v1.4.0, l'affichage était correct en v1.3.0 :
![Capture_panzer_dragon_1 3 0_20190911](https://user-images.githubusercontent.com/7624262/64990312-dda63d00-d8cf-11e9-8188-ac582d626c57.PNG)

L'effet est probablement obtenu par une semi-transparence additive (sans tenir compte des ratio, mode "as-is") du RBG0 vers le line color screen qui doit être activé sur cette couche, couplé à une modification progressive de la couleur du line color screen par la table de coefficient associée au paramètre de rotation du plan 3D. Seul ce mécanisme peut expliquer l'éclaircissement progressif qui s'incline avec le RBG0 et qui ne correspond ni à la couleur du back screen qui se trouve derrière le RBG0, ni au ratio de color calculation du RBG0.

Testé avec le CD jap.

**Comment by fafling** [comment]
Toujours présent en WIP accurate_vdp1 du 13/10.

**Comment by fafling** [comment]
Toujours présent en extui-align du 21/11.

**Comment by FCare** [comment]
yaba utilise Yglprg_rgb_cram_line_f.... A creuser

**Comment by fafling** [comment]
Fixé en OpenGL en WIP du 22/03.

**Comment by BenjaminSiskoo** [comment]
@faffling il semble que ce soit corrigé non ?

**Comment by fafling** [comment]
En WIP du 01/04, en GPU RBG off c'est correct (screen de gauche), mais en GPU RBG on, l'effet vire au bleu au lieu du blanc et il y a des lignes sans l'effet au niveau de l'horizon et juste en-dessous.
![image](https://user-images.githubusercontent.com/7624262/78193248-5fc80e80-747a-11ea-8663-79a1bd8442b8.png)

**Comment by fafling** [comment]
OK en CS en WIP du 02/04.
