### ISSUE TITLE
Branch accurate VDP1 régression...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#625]
Texte manquant sur le bios. OpenGL aucun filtre activé.

![bios](https://user-images.githubusercontent.com/12481242/65465735-4b68e080-de5d-11e9-9477-3b3751cf5dba.PNG)

**Comment by fafling** [comment]
Chez moi le nuage de polygones ne s'affiche pas au démarrage du bios, et sur l'écran du CD player, seules les commandes VDP1 avec half transparency s'affichent :
![Capture_bios_acc_VDP1_20190923](https://user-images.githubusercontent.com/7624262/65467166-1eb6c800-de61-11e9-9229-3022e3ecfccd.PNG)

**Comment by fafling** [comment]
A part le R qui utilise l'effet de half transparency sur l'écran titre de Sonic R, aucun sprite ne s'affiche.
Aucun sprite non plus dans Guardian heroes et Decathlete.

**Comment by BenjaminSiskoo** [comment]
Doukoku Soshite scintillements sur l'écran suivant :

![doukokusoshite](https://user-images.githubusercontent.com/12481242/65521725-f7f0a400-dee9-11e9-8f97-1a21457c81a3.PNG)

**Comment by BenjaminSiskoo** [comment]
Mr Bones : personnage manquant : Il semble que ce soit un problème de NBG0.
![mrbones](https://user-images.githubusercontent.com/12481242/65522025-69c8ed80-deea-11e9-9f03-c9bbcd44f3b7.PNG)

**Comment by BenjaminSiskoo** [comment]
Peebel Beach Golf : les FPS chutent sur cette écran puis le jeu se relance au bout de quelques secondes...
![peblee](https://user-images.githubusercontent.com/12481242/65522896-bf51ca00-deeb-11e9-91ec-0b2b57bc75b9.PNG)

**Comment by BenjaminSiskoo** [comment]
QuoVadis 2 :


![quovadis2](https://user-images.githubusercontent.com/12481242/65523900-36d42900-deed-11e9-8f8f-a1290ac17a02.PNG)

Savestate : 
[quovadis2.zip](https://github.com/FCare/Kronos/files/3648086/quovadis2.zip)

**Comment by fafling** [comment]
Dans la WIP du 24/09, on voit dans le bios un bug de Gouraud shading apparu sur l'extui-align le 01/09 en OpenGL seulement : quand le lecteur est vide, la surface des 2 cubes n'est pas uniforme comme sur la console, on voit des pixels plus clair au centre.
![Capture_bios_acc_VDP1_20190924](https://user-images.githubusercontent.com/7624262/65530516-676d9000-def8-11e9-9582-b8112ffcb5bb.PNG)

**Comment by fafling** [comment]
La trainée d'accélération dans Sonic R est affiché comme une mesh alors qu'elle devrait être en Gouraud shading + half transparency.
![Capture_sonic_r_accélérateur_VDP1_acc_20190924](https://user-images.githubusercontent.com/7624262/65531251-c54ea780-def9-11e9-98c3-0a09f762475e.PNG)
Un save state pour reproduire (version japonaise), il suffit d'accélérer, c'est tout droit :
[sonic_r_accelerateur.zip](https://github.com/FCare/Kronos/files/3648301/sonic_r_accelerateur.zip)

Fixé en WIP du 25/09.

**Comment by fafling** [comment]
Corruption du ciel dans Quake seulement en OpenGL depuis la WIP extui-align du 03/09 :
![Capture_quake_ciel_VDP1_acc_20190924](https://user-images.githubusercontent.com/7624262/65540169-23d05180-df0b-11e9-860d-39b42bc28b44.PNG)

**Comment by fafling** [comment]
Le mesh mode improved ne fonctionne ni dans Sonic 3D, ni dans Megaman X4.
![Capture_sonic_3d_mesh_mode_VDP1_acc_20190924](https://user-images.githubusercontent.com/7624262/65545784-60ee1100-df16-11e9-8eca-4df87670534f.PNG)
![Capture_megamanX4_mesh_mode_VDP1_acc_20190924](https://user-images.githubusercontent.com/7624262/65545847-83802a00-df16-11e9-937f-fd8fb99cfbeb.PNG)

**Comment by fafling** [comment]
Dans Bug too, quand on saute sur un fantôme semi-transparent, il cumule half-transparency et Gouraud, et Kronos n'affiche qu'un rectangle semi-transparent à la place.
![Capture_bug_too_fantome_VDP1_acc_20190924](https://user-images.githubusercontent.com/7624262/65549070-0f955000-df1d-11e9-863c-2a337f96dd34.PNG)
Un save state pour reproduire (version PAL) :
[bug_too_fantome.zip](https://github.com/FCare/Kronos/files/3649401/bug_too_fantome.zip)

Même problème sur la poussières des coups de poings dans Hexen.

Fixé en WIP du 25/09.

**Comment by fafling** [comment]
Dans Panzer dragoon, le radar ne s'affiche que s'il est superposé à un sprite qui utilise la half-transparency (les rayons) :
![Capture_panzer_dragoon_radar_VDP1_acc_20190924](https://user-images.githubusercontent.com/7624262/65556693-cd760980-df30-11e9-9773-02173bb72d45.PNG)
Le radar cumule mesh, Gouraud et half-transparency :
![Capture_panzer_dragoon_radar_VDP1_acc_20190924_VDP1](https://user-images.githubusercontent.com/7624262/65556726-eb436e80-df30-11e9-9c67-1c6794e67318.PNG)
Un save state pour reproduire (version japonaise, le jeu est en pause et Kronos n'affiche les sprites que si on sort de la pause) :
[panzer_dragoon_radar.zip](https://github.com/FCare/Kronos/files/3649822/panzer_dragoon_radar.zip)

Fixé en WIP du 25/09.

**Comment by fafling** [comment]
Pour Doukoku soshite, c'est déjà incorrect en extui-align, voir #568 
Pour moi, c'est un problème de color calculation window du VDP2 qui ne fonctionne plus depuis le 16/05 et qui devrait limiter la zone de l'effet aux curseurs. La semi-transparence est sans doute additive, car le ratio du NBG0 ne varie pas, et faite par rapport au line color screen vu qu'il n'y a rien d'autre qui vire au blanc derrière le NBG0.

**Comment by BenjaminSiskoo** [comment]
Touge King of Spirit 2 : le jeu ne va plus in game.  Kronos ferme.

Sauvegarde d'état : il reste juste a appuyé sur le bouton.

[tougekingofspirit2.zip](https://github.com/FCare/Kronos/files/3665301/tougekingofspirit2.zip)

**Comment by BenjaminSiskoo** [comment]
Shoujo Kakumei Utena - Itsuka Kakumei Sareru Monogatari : Régression sur le press start screen + fermeture de kronos  si tu n'appuie sur aucun bouton.

![shoujo](https://user-images.githubusercontent.com/12481242/65815169-19a0a280-e1ec-11e9-9707-d4cde6b066d0.PNG)

Sauvegarde d'état sur le press start screen.

[shoujo.zip](https://github.com/FCare/Kronos/files/3665340/shoujo.zip)

**Comment by BenjaminSiskoo** [comment]
Shellshock - Jus' Keepin' Da Peace : écran noir in game : 

![shellschok](https://user-images.githubusercontent.com/12481242/65815313-3e961500-e1ee-11e9-8cfe-312a706556de.PNG)

Sauvegarde d'état : 
[shellchcok.zip](https://github.com/FCare/Kronos/files/3665352/shellchcok.zip)

**Comment by barbudreadmon** [comment]
La trace pour le crash d'utena : https://pastebin.com/raw/zgw1LjwW
Impossible de reproduire celui sur Touge 2 donc c'est peut-être un soucis spécifique ati et/ou windows

J'ai aussi l'interface de RetroArch qui part en couille, çà arrive sur les core en opengl si l'état d'opengl n'est pas "propre" (remis à zéro) entre les frames, il semble que l'instruction manquante soit `glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);` (le bug d'interface disparaît quand je l'ajoute dans le port libretro après le rendu de frame)

**Comment by FCare** [comment]
Pour utena c'est un pb de compilation open gl. Il faut activer les traces
pour avoir la nature de l'erreur

Le sam. 28 sept. 2019 à 13:36, barbudreadmon <notifications@github.com> a
écrit :

**Comment by fafling** [comment]
Crash de Kronos sur la demo SAGE 2019 de XL2 dès qu'on commence à bouger après le chargement du niveau. Le crash se produit depuis la WIP du 24/09. Pas de problème dans la WIP du 16/09 ni en extui-align.
[https://www.sonicfangameshq.com/forums/attachments/project-z-treme-sage-2019-demo-zip.3630/](https://www.sonicfangameshq.com/forums/attachments/project-z-treme-sage-2019-demo-zip.3630/)

Plus de crash dans la WIP du 29/09.

**Comment by BenjaminSiskoo** [comment]
Je viens de tester avec la WIP du 29/09/2019 (11h15) et le jeu se lance.

**Comment by BenjaminSiskoo** [comment]
Peeble Beach Golf : les FPS chutent sur cette écran puis le jeu se relance au bout de quelques secondes...

![peblee](https://user-images.githubusercontent.com/12481242/65522896-bf51ca00-deeb-11e9-91ec-0b2b57bc75b9.PNG)

Savestate : 

[pebble.zip](https://github.com/FCare/Kronos/files/3648079/pebble.zip)

**Comment by BenjaminSiskoo** [comment]
Shellshock - Jus' Keepin' Da Peace : écran noir in game : 

![shellschok](https://user-images.githubusercontent.com/12481242/65815313-3e961500-e1ee-11e9-8cfe-312a706556de.PNG)

Sauvegarde d'état : 
[shellchcok.zip](https://github.com/FCare/Kronos/files/3665352/shellchcok.zip)
