### ISSUE TITLE
[Transport Tycoon] Menu n'est pas affiché correctement..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#626]
Testé avec la branche VDP1 accuracy, Par rapport à la version public, amélioration avec le cadre qui entoure le menu. Mais il est noir.

![transport](https://user-images.githubusercontent.com/12481242/65814681-574dfd00-e1e5-11e9-9d2c-7a401ea26a9b.PNG)

![transporttycoon](https://user-images.githubusercontent.com/12481242/65814682-57e69380-e1e5-11e9-869d-a102abc782c2.PNG)

![transporttycoon1](https://user-images.githubusercontent.com/12481242/65814743-f8d54e80-e1e5-11e9-9399-ac507535db4d.PNG)

Sauvegarde d'état :  

[transporttycoon.zip](https://github.com/FCare/Kronos/files/3665298/transporttycoon.zip)

**Comment by fafling** [comment]
Les polygones du menu étaient corrects jusqu'à UOYabause 0.5.2 et deviennent incorrects dans Kronos 1.0.0 : 
- Ils sont noirs ou traités en commandes d'effacement jusqu'en WIP 1.7.0 du 20/04.
- Ils sont non dessinés de la WIP 1.7.0 du 21/04 à la WIP accurate_vdp1 du 16/09.
- Ils redeviennent noirs ou traités en commandes d'effacement depuis la WIP accurate_vdp1 du 24/09.

Les sprites du tour d'écran étaient corrects jusqu'en WIP 1.7.0 du 19/05. Depuis celle du 20/05, ils ne sont plus dessinés.
Exemple de commande non dessinée en haut de l'écran :
![Capture_transport_tycoon_VDP1_acc_20190928](https://user-images.githubusercontent.com/7624262/65816576-aef86280-e1fd-11e9-801f-501bf18ec65a.PNG)

**Comment by fafling** [comment]
Un possibilité pour le menu : les polygones du menu sont en RGB, leur priorité doit être automatiquement celle du registre 0 de priorité des sprites, qui vaut 3. Si jamais Kronos utilise le numéro du registre comme priorité et non sa valeur, ou bien la valeur d'un des autres registres de priorité qui sont tous à 0, alors les polygones sont considérés de manière incorrecte comme transparents du point de vue du VDP2.

**Comment by FCare** [comment]
les coordonées exprimées en CMDXA et CMDXB sont du type (1fe3x1ff7) ce qui est un format normalement mal exprimé suivant la partie 6.7 de la spec VDP1...
Donc depuis un moment, on considere ca comme invalid command...

**Comment by fafling** [comment]
Fixé en WIP du 06/10, mais le fix provoque des régressions sur les jeux avec des coordonnées de texture problématiques, voir #642 .
