### ISSUE TITLE
[Digital Ange - Dennou Tenshi SS] La fenêtre de dialogue reste affiché...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#628]
Kronos Wip du 28/09/2019 (VDP1 accuracy) : 

![digitalange](https://user-images.githubusercontent.com/12481242/65829347-e53ced00-e2a4-11e9-9dc6-bbb5fd35bc74.PNG)

Sauvegarde d'Etat : 

[digitalange.zip](https://github.com/FCare/Kronos/files/3666536/digitalange.zip)

**Comment by fafling** [comment]
En WIP accurate_vdp1 du 09/10, il y a probablement des problèmes similaires à ce qu'on voit dans Doukoku soshite #568, avec une inversion de la color calculation window, qui semble utilisée dans ce jeu aussi, là encore sûrement avec le line color screen qui a l'air activé sur le NBG0.
La color calculation window à l'air composée de 2 fenêtres qui se chevauchent ce qui expliquerait les 2 zones qu'on observe en ce moment : une qui correspond à la fenêtre de dialogue, et les côtés de cette fenêtre.

1er dialogue :
![Capture_digital_ange_VDP1_acc_20191009](https://user-images.githubusercontent.com/7624262/66530326-99414200-eb07-11e9-895a-49deec78d9d6.PNG)

Affichage de la console :
![Capture_digital_ange_youtube](https://user-images.githubusercontent.com/7624262/66530346-ad853f00-eb07-11e9-9121-1fc7b6cc986b.PNG)

Comme dans Doukoku, le ratio de color calculation sur le NBG0 ne correspond pas à l'effet, donc c'est peut-être le mode "as-is" qui est utilisé, ou bien les ratios sont peut-être pris sur la second image, donc sur le line color screen.

J'en suis réduit à faire des hypothèses, car il manque beaucoup d'info dans l'écran debug, et ce jeu les cumule : activation de la color calculation window, quelles fenêtres la compose, avec quelle logique, quelles couches activent le line color screen, quel est le ratio du line color screen, quel est le color calculation mode, quel est le color calculation ratio mode...

**Comment by fafling** [comment]
En WIP du 10/10 l'inversion de la color calculation window est corrigée.

**Comment by fafling** [comment]
En WIP du 28/10, la fenêtre de dialogue reste affichée alors qu'elle devrait disparaître.

**Comment by BenjaminSiskoo** [comment]
Kronos 14.10.2021
idem

**Comment by BenjaminSiskoo** [comment]
Régression avec kronos 2.2.0 du 15.12.2021

![image](https://user-images.githubusercontent.com/12481242/146226893-a252b818-9e9a-4436-b1b1-3c1343d8aa8f.png)

Savestate : 
[Uploading T-33003G_000.zip…]()

**Comment by BenjaminSiskoo** [comment]
C'est un des patch entre 11h11 et 16h34 en date du 15/12/2021

**Comment by fafling** [comment]
Apparemment la color calculation window est encore buggée, étonnant alors qu'elle est maintenant correcte dans Air management #1002 . Sans info debug sur la color calculation window, difficile de voir ce qui ne va pas.

**Comment by fafling** [comment]
En WIP du 03/01, la forme de la fenêtre de dialogue est fixée dans les 2 noyaux avec la correction de l'inversion de la color calculation window (a3f9503779441d4be6a7b536b5325bd13fd376e9).
Il reste donc le problème d'origine, la persistance de cette fenêtre de dialogue alors qu'elle devrait disparaître.
C'est un problème général lorsque le color calculation ratio est pris sur la 2nd image et que celle-ci est le line color screen, le ratio est inversé par Kronos.
Problème identique dans Doukoku soshite #700 , et Bishoujo Hanafuda Kikou #905 .
Je crée un br #1296 sur l'affichage des ratios quand ils sont pris sur la 2nd image afin de faciliter l'analyse de ce type de problème.

**Comment by BenjaminSiskoo** [comment]
Correction du 18.01.2022
