### ISSUE TITLE
[Quake] Traits verticaux dans le ciel...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#631]
Corruption du ciel dans Quake seulement en OpenGL depuis la WIP extui-align du 03/09 :

![Capture_quake_ciel_VDP1_acc_20190924](https://user-images.githubusercontent.com/7624262/65540169-23d05180-df0b-11e9-860d-39b42bc28b44.PNG)

**Comment by fafling** [comment]
Toujours présent en WIP accurate_vdp1 du 13/10.
Le RBG0 utilise la table de coefficient qui est impactée par le patch f8f0d11 :
![image](https://user-images.githubusercontent.com/7624262/66714630-2ced6980-edb9-11e9-8bee-c9036c35ffa8.png)
Problème probablement identique dans Wing arms #611 .

**Comment by BenjaminSiskoo** [comment]
semble corrigé avec la wip du 25/11/2019

**Comment by fafling** [comment]
@BenjaminSiskoo C'est toujours présent chez moi. Est-ce que tu es bien en OpenGL ?

**Comment by fafling** [comment]
En 2ème WIP du 08/12 en noyau CS, le RBG0 est devenu monochrome et clignote, comme dans Wing Arms. Corruption inchangée en OpenGL.
![image](https://user-images.githubusercontent.com/7624262/70391051-32d68400-19d1-11ea-97e6-2eb33d3dae3a.png)

**Comment by fafling** [comment]
Fixé en noyau OpenGL en v2.0.1 publique.
Le problème en noyau CS est suivi par un br dédié (#721).
