### ISSUE TITLE
[Three Dirty Dwarves] Problème faisceau du lampadaire...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#632]
Avec la Wip VDP1 accuracy du 29/09/2019 (14h00) : 

Avec la version public 1.7.0, le faisceau de lumière n'est pas affiché
Avec la version WIP, il y a un faisceau de lumière mais noir. 

![threedirtydwarves](https://user-images.githubusercontent.com/12481242/65832806-17f8dc80-e2c9-11e9-8c7d-29b7dd04e855.PNG)

Sauvegarde d'état : 

[threedirtydwarves.zip](https://github.com/FCare/Kronos/files/3667339/threedirtydwarves.zip)

**Comment by FCare** [comment]
Polygon
x1 = 96, y1 = 54, x2 = 102, y2 = 54
x3 = 200, y3 = 205, x4 = 99, y4 = 205
Pre-clipping Enabled
Color mode: 8 BPP(256 color bank)
Color bank: 00004000
Color Calc. mode: Replace

**Comment by fafling** [comment]
La valeur affichée par l'écran debug est buggée quand le color mode correspond à un mode palette : elle est décalée inutilement de 3 bits vers la gauche. Donc 4000 en hex, qui donne en binaire 0100 0000 0000 0000, doit être décalé de 3 bits vers la droite pour avoir la valeur CMDCOLR réellement portée par la commande de dessin, à savoir 0000 1000 0000 0000.

Comme le type de sprite est à 3, le seul bit à 1 correspond au bit CC0, donc le pixel utilise le ratio du  registre de color calculation 1 des sprites, à savoir 11:21.
![Capture_3_dirty_dwarves_VDP1_acc_20190929](https://user-images.githubusercontent.com/7624262/65921612-03106c00-e3e3-11e9-98fd-63e5f9e5c8a2.PNG)

Comme la condition de color calculation est le MSB de la couleur dans la color RAM, et comme le color RAM offset des sprites est à 0, c'est donc que la couleur qui se trouve à l'adresse 000 0000 0000 de la color RAM (au sens VDP2, donc sans le décalage dû à la profondeur de couleur de la color RAM) a son MSB à 1.

**Comment by fafling** [comment]
Je précise que le color mode ne sert à rien sur les commande non texturées. La doc du VDP indique qu'il devrait être positionnée à 000B, soit 16 color bank, mais dans les faits, le VDP1 ne semble pas le vérifier, la preuve sur Three dirty dwarves.
Tout traitement de Kronos qui dépendrait du color mode sur ce type de commandes ne correspondrait pas à ce que fait la machine.
En l'occurrence, le color mode pourrait avoir n'importe quelle autre valeur que 8 BPP, cela ne changerait pas l'affichage sur la console.

**Comment by fafling** [comment]
L'affichage de l'écran debug VDP1 sur les commandes non texturées prête particulièrement à confusion : en plus du décalage de 3 bits qui ne sert à rien sur la color bank, il affiche le color mode alors qu'il est sans signification.

**Comment by fafling** [comment]
Fixé en WIP du 01/10.
