### ISSUE TITLE
[Bios] Gouraud shading incorrect sur les cubes en noyau OpenGL

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#634]
En WIP vdp1_accurate du 29/09 et extui-align du 11/09, on voit dans le bios un bug de Gouraud shading apparu sur l'extui-align le 01/09 en noyau OpenGL seulement : quand le lecteur est vide, la surface des 2 cubes n'est pas uniforme comme sur la console, on voit des pixels plus clair au centre.
![Capture_bios_acc_VDP1_20190924](https://user-images.githubusercontent.com/7624262/65530516-676d9000-def8-11e9-9582-b8112ffcb5bb.PNG)

Affichage correct avec le noyau compute shader :
![Capture_bios_extui-align_20190911](https://user-images.githubusercontent.com/7624262/65839936-7dbd8680-e312-11e9-8928-e5f70a836673.PNG)

**Comment by fafling** [comment]
Le bug dépend de la tessellation. La capture a été faite avec le mode "Triangles using perspective correction". Le problème est présent aussi en tessellation CPU, mais s'affiche différemment. Par contre, l'affichage est correct en tessellation GPU.

**Comment by fafling** [comment]
Toujours présent en WIP du 24/11.

**Comment by BenjaminSiskoo** [comment]
Support OpenGl arrêté
