### ISSUE TITLE
[After burner II] Sprites du sol non rendus

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#635]
En WIP extui-align du 11/09, dans les 2 noyaux, et en WIP accurate_vdp1 du 29/09, les scaled sprites du sol ne sont pas rendus, sauf très brièvement en début de démo ou de jeu.
Dans la 1ère démo :
![Capture_after_burner_2_extui_align_20190911](https://user-images.githubusercontent.com/7624262/65904174-312f8500-e3be-11e9-8866-a3e6ad9aad17.PNG)

Le problème apparaît en WIP extui-align du 15/07.
Affichage correct en v1.7.0 publique :
![Capture_after_burner_2_1 7 0](https://user-images.githubusercontent.com/7624262/65904453-cd598c00-e3be-11e9-831c-2e0a228d755f.PNG)

Dans l'écran debug du VDP1, les commandes de dessin du sol, normalement de type scaled sprite, ne sont plus là et sont remplacées par des commandes de normal sprites skippées.

Un save state pour aller plus rapidement sur la demo (chez moi il y a un freeze temporaire d'une minute mais la demo finit par se lancer; si on ne passe pas par le save state en accurate_vdp1, le freeze ne se produit pas, mais il y a une corruption des NBG0, 2 et 3 qui cache les sprites, pour les voir il faut désactiver ces couches) :
[afterburner_demo1.zip](https://github.com/FCare/Kronos/files/3672657/afterburner_demo1.zip)

Testé avec le CD japonais.

**Comment by BenjaminSiskoo** [comment]
Wip du 12/10/2019 : 

![afterburner](https://user-images.githubusercontent.com/12481242/66699934-9a32c900-eceb-11e9-91c2-26c79bb71037.PNG)

**Comment by BenjaminSiskoo** [comment]
Identique avec la WIP du 22/10/2019.

**Comment by FCare** [comment]
Fixé le 24/10/2019

**Comment by fafling** [comment]
Correct aussi dans les 2 noyaux en WIP extui-align du 19/11.
