### ISSUE TITLE
[Fire Pro Gaiden Blazing Tornado] Menu de sélection des personnages cassés (Read/write FB ?)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#639]
Wip du 05/10/2019 : 
![firepro](https://user-images.githubusercontent.com/12481242/66252531-32193b80-e75d-11e9-96e8-7b2f53ad5a82.PNG)

Savestate : 
 
[firepro.zip](https://github.com/FCare/Kronos/files/3693020/firepro.zip)

**Comment by BenjaminSiskoo** [comment]
Faut pas laisser l'option CS activé.

**Comment by fafling** [comment]
C'est en CS que ça se produit. C'est un autre exemple du bug #537 .
