### ISSUE TITLE
[Firestorm - Thunderhawk 2] Les boutons ne répondent plus...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#640]
Kronos WIP du 05/10/2019

Savestate : 

[firestorm thunderhawk2.zip](https://github.com/FCare/Kronos/files/3693040/firestorm.thunderhawk2.zip)

**Comment by BenjaminSiskoo** [comment]
Kronos 14.10.2021 : idem

**Comment by fafling** [comment]
Les boutons ne répondent pas avec une manette USB, mais ils répondent s'ils sont tous mappés sur des touches du clavier.

Ce problème existait déjà en v1.6.0, mais pas en v1.5.0.

Possiblement lié à l'utilisation du mode direct de collection d'inputs par le SH2.

Même problème que pour X-Japan #518 , World heroes perfect #455 , Shockwave Assault #738 , la traduction de Ogre battle #1370 ainsi que Heart of darkness.

**Comment by BenjaminSiskoo** [comment]
kronos20231206_3006f2d

Corrigé
