### ISSUE TITLE
Musique/SFX manquants dans les jeux...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#641]
Kronos WIP du 05/10/2019

3D Baseball : le speaker répète le nom 2 fois.
Fighter mégamix : le volume est bas pour les musiques/SFX.
Hyper 3D Pinball : musique manquante.
Independance Day : pas de musique/SFX.
Sega Ages : Outrun : autoradio.
Sega Ages : Fantasy Zone : pas de musique/SFX

**Comment by fafling** [comment]
King of fighters 95 : Aucune musique pendant le jeu dans jap, testé en v1.5.0, v1.6.0 et WIP du 17/03/2019 avec bios jap v1.01, que ce soit avec le CD d'origine ou avec une image ISO.
Avec le CD, il y a en plus un gel de Kronos pendant à peu près une minute à chaque fois que la musique devrait changer.
Avec le CD ou l'ISO, la musique peut être écoutée sans problème dans le CD player du bios.
Dans Yabause v0.9.14, avec le même CD, le jeu fonctionne avec la musique sans gel.
Le CD fonctionne sans problème sur console.

Pour King of fighters 95, c'est fixé en accurate_vdp1, le son est OK dans la WIP du 05/10.

**Comment by BenjaminSiskoo** [comment]
ok je supprime alors

**Comment by fafling** [comment]
Steamgear Mash est fixé depuis la WIP du 07/05.
Hissatsu depuis celle du 08/06.

**Comment by fafling** [comment]
Die hard arcade (US) : la musique s'arrête quand commence le 1er combat, en WIP accurate_vdp1 du 28/10 et extui-align du 11/09.

**Comment by fafling** [comment]
Thunder Force gold pack 2 : pas de son in game depuis la WIP du 03/09, problème peut-être importé de uoYabause car cette version en a intégré certains patchs (voir [https://github.com/devmiyax/yabause/issues/678](https://github.com/devmiyax/yabause/issues/678) ).

**Comment by BenjaminSiskoo** [comment]
**Die Hard Arcade** (quelqu'un avait mis ca sur le wiki : Playable. - (With a few graphical glitches and no sound in some stages) 
**Mortal Kombat Trilogy** (pareil pou ca) : Playable, sounds bugs with the narrator of the fight (sounds really fast when you win a round or make a finisher, fatality, etc) 
**Sega Ages - I Love Mickey Mouse - Fushigi No Oshiro Daibouken & I Love Donald Duck - Georgia Ou No Hihou** : le son est très mauvais (grésillement !!!)
**Sega Ages - Phantasy Star Collection** : problème de son.
**Sega Saturn Choice Cuts** : problème de son.
**Soeldnerschild** : problème de son.
**Sokkou Seitokai - Sonic Council** : problème de son.
**Zanma Chou Ougi Valhollian** : problème de son.
**Black Matrix** : les voix ne sont pas compréhensible
**Refrain Love - Anata Ni Aitai** : les voies sont trop rapide (comme les chipmunk)
**Independence Day - The Game** : pas de SFX/Music
**NHL '97** : pas de musique sur les vidéo.

**Comment by fafling** [comment]
Problèmes présents en  en v2.0.1 publique :
**Mystaria (PAL)** : Kronos répète 7 fois l'effet sonore lorsqu'on appuie sur start au choix "New game". L'effet n'est joué qu'une fois sur la console. Testé avec le CD d'origine et reproduit avec l'ISO redump.
**Jikkyou Oshaberi Parodius - Forever with Me** : saccades ou répétitions sur les digits vocales et une partie des musiques. C'est le cas pendant toute l'intro. Testé avec le CD d'origine et reproduit avec l'ISO redump.

**Comment by fafling** [comment]
**After burner II** : plus de son depuis la WIP du 05/01.

**Comment by BenjaminSiskoo** [comment]
@fafling j'ai crée un nouveau br. Pourrais tu me confirmer que Jikkyou Oshaberi Parodius est ok pour toi ? Sinon, rajoute sur le nouveau BR

**Comment by fafling** [comment]
Je confirme que les digits sonores sont OK dans Jikkyou Oshaberi Parodius dans la dernière WIP, et depuis celle du 19/02.
