### ISSUE TITLE
[Linkle liver story] Sprite en travers de l'écran en accurate_vdp1

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#642]
En WIP accurate_vdp1 du 07/10, à la saisie du nom du perso, quand on fait défiler les claviers virtuels, certains s'affichent extrêmement étirés et recouvrent celui qui devrait s'afficher (appuyer 2 fois sur R pour avoir le 1er problème).

Le problème apparaît sur la WIP du 06/10.

![Capture_linkle_clavier_VDP1_acc_20191007](https://user-images.githubusercontent.com/7624262/66351605-2f396900-e95e-11e9-9e03-7257f1c08a92.PNG)

Dans les commandes du VDP1, on trouve 2 fois cette texture avec des coordonnées qui ne correspondent pas à un étirement pareil.
Pour obtenir le même étirement dans un logiciel de dessin, il faut inverser la texture horizontalement et l'étirer sur au moins 4000 pixels de large !

![Capture_linkle_clavier_3_VDP1_acc_20191007](https://user-images.githubusercontent.com/7624262/66351961-f4840080-e95e-11e9-9c0e-7a21dbd911b0.PNG)
![Capture_linkle_clavier_2_VDP1_acc_20191007](https://user-images.githubusercontent.com/7624262/66351966-f6e65a80-e95e-11e9-9e7e-cf5ae8d6c3f9.PNG)

Les coordonnées de cette texture dans l'écran debug sont les mêmes en WIP du 05/10. Ce qui est bizarre, c'est que la 2ème commande devrait être partiellement affichée sur l'écran, or ce n'est pas le cas.
Affichage correct en WIP du 05/10 :
![Capture_linkle_clavier_VDP1_acc_20191005](https://user-images.githubusercontent.com/7624262/66352217-74aa6600-e95f-11e9-8f69-cb829be9c2bc.PNG)

Un save state pour aller directement au 1er clavier mal affiché :
[linkle_clavier3.zip](https://github.com/FCare/Kronos/files/3699717/linkle_clavier3.zip)

Testé avec le CD jap.

**Comment by fafling** [comment]
En fait on retrouve le même genre de problème que dans le br #215 .

Dans Robotica, des polygones barrent temporairement l'écran quand on bouge :
![Capture_robotica_VDP1_acc_20191007](https://user-images.githubusercontent.com/7624262/66353566-9b1dd080-e962-11e9-908d-fb9ab373fac5.PNG)
Un save state pour reproduire (version US) :
[robotica_polygone_en_travers.zip](https://github.com/FCare/Kronos/files/3699879/robotica_polygone_en_travers.zip)

Dans Night striker S, c'est la route qui s'affiche en travers de l'écran quand on monte tout en haut :
![Capture_night_striker_VDP1_acc_20191007](https://user-images.githubusercontent.com/7624262/66353888-74ac6500-e963-11e9-8f06-8a9bc5f98056.PNG)
Un save state pour reproduire :
[night_striker_route_en_travers.zip](https://github.com/FCare/Kronos/files/3699904/night_striker_route_en_travers.zip)

Les 2 problèmes n'existent pas en WIP du 05/10.

**Comment by fafling** [comment]
En WIP accurate_vdp1 du 09/10, le problème est partiellement réglé, mais on voit toujours des polygones partiellement en travers de l'écran dans Robotica ou Night Striker (visibles sur les save states).

Dans Linkle liver story, il n'y a plus de problème si on fait défiler les clavier vers la droite. Par contre, il y a un souci quand on les fait défiler 2 fois vers la gauche :
![Capture_linkle_clavier_gauche_VDP1_acc_20191009](https://user-images.githubusercontent.com/7624262/66525119-c33d3900-eaf4-11e9-9e93-438cfdf6f586.PNG)

La clavier qui apparaît derrière est probablement cette texture dont les coordonnées dans l'écran debug ne correspondent pas à ce qu'on voit à l'écran (elles ne sont pas correctes non plus, car si elles étaient utilisées par Kronos, on verrait le clavier déborder à gauche de l'écran au lieu de la droite) :
![Capture_linkle_clavier_gauche_2_VDP1_acc_20191009](https://user-images.githubusercontent.com/7624262/66525260-2dee7480-eaf5-11e9-9b73-1f2a1529d9f6.PNG)

 Le save state correspondant :
[linkle_clavier_gauche.zip](https://github.com/FCare/Kronos/files/3709659/linkle_clavier_gauche.zip)

**Comment by BenjaminSiskoo** [comment]
@fafling je ne vois plus le soucis pour linkle en opengl et cs, tu peux confirmer/infirmer ?

**Comment by fafling** [comment]
C'est toujours présent chez moi dans la dernière WIP.

**Comment by fafling** [comment]
Problèmes fixés par [0a26fe6](https://github.com/FCare/Kronos/commit/0a26fe61260010386d2e15a8e03f1fc5b0ac2d61) avec l'implémentation des 4 1ères observations parmi les suivantes faites sur les coordonnées des commandes de dessin du VDP1 :
- Le VDP1 comprend les coordonnées signées sur 12 bits en non 11, donc -2048, 2047.
- Le bit de signe est donc le bit 12 et non 11 (en commençant à 1).
- Le bit 13 doit avoir la même valeur que le bit 12 sinon le dessin bugge.
- La valeur des bits 14, 15 et 16 n'a aucun effet.
- Le dessin "wrappe" dans l'espace de coordonnées -1024, 1023.
- Comme dit la doc, le dessin n'est pas garanti en-dehors des coordonnées -1024, 1023 en particulier quand on se rapproche des limites de l'intervalle -2048, 2047.
- Le dessin bugge à coup sûr pour des lignes de dessin dépassant 2048 pixels.

Ces observations ont été faites avec le programme suivant (source inclus, à compiler dans le répertoire sample de jo engine mais n'utilise que SGL) :
[demo - VDP1 coordinates.zip](https://github.com/FCare/Kronos/files/13710073/demo.-.VDP1.coordinates.zip)
