### ISSUE TITLE
[Fire Pro Gaiden Blazing Tornado] Portraits en noir...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#643]
![firepro](https://user-images.githubusercontent.com/12481242/66509197-d6d7a800-ead2-11e9-83ea-41211f301a0b.PNG)

Savestate : 
[firepro.zip](https://github.com/FCare/Kronos/files/3708862/firepro.zip)

**Comment by BenjaminSiskoo** [comment]
L'intro n'est plus correcte :

![fireprog](https://user-images.githubusercontent.com/12481242/66516661-d98dc980-eae1-11e9-84d1-8cdd6b0591ac.PNG)

**Comment by fafling** [comment]
Le problème du portrait noir est à nouveau là en WIP accurate_vdp1 du 11/10.
Sur la console, la zone noire est complètement transparente.
![Capture_blazing_tornado_youtube](https://user-images.githubusercontent.com/7624262/66689318-9b7fd980-ec8a-11e9-8e4a-2c6e5feb8333.PNG)

Les portraits se trouvent sur la couche RBG0.
La commande de polygone qui dessine la zone noire utilise effectivement la couleur RGB noir (8000 en hexa).
![Capture_blazing_tornado_acc_vdp1_20191011](https://user-images.githubusercontent.com/7624262/66689322-a33f7e00-ec8a-11e9-91b5-3dadf9c21176.PNG)

Il n'y a pas de commande de dessin qui efface ce noir ensuite : il y a des commande de normal sprite pour dessiner le tour des portraits, mais le milieu est transparent et le transparent code est activé.

Les paramètres du VDP2 définissent bien le framebuffer en RGB+palette, et il n'y a pas d'effet de color calculation sur les pixels RGB car ils ne satisfont pas la condition de CC qui est d'avoir une priorité à 5 (la leur est à 6).
![Capture_blazing_tornado_2_acc_vdp1_20191011](https://user-images.githubusercontent.com/7624262/66689329-a9355f00-ec8a-11e9-941b-80f9a9c0f998.PNG)

Le framebuffer est 16 bit donc il n'y a pas de troncage des pixels.

Le problème est donc que l'affichage de Kronos correspond bien à ce qui est dans les écrans debug, mais ça ne match pas avec la console. Donc soit l'affichage du debug est incorrect, ou bien il y a un interrupt qui vient modifier les paramètres du VDP2 pendant la période d'affichage.

**Comment by fafling** [comment]
Le fonctionnement du menu est peut-être perturbé par des invalid opcodes qui se produisent avant son apparition, voir #651 .

**Comment by fafling** [comment]
@BenjaminSiskoo Est-ce que tu peux rouvrir ?

**Comment by fafling** [comment]
Fixé en WIP accurate_vdp1 du 28/10 en rendant transparents les pixels à 8000 d'un framebuffer RGB+palette quand la sprite window est activée.

**Comment by fafling** [comment]
Le fix du 28/10 entraîne une régression dans Mystaria où le noir devient transparent aussi :
![image](https://user-images.githubusercontent.com/7624262/69389440-4fce4000-0ccc-11ea-9b69-d9c9010c4a73.png)
Dans la WIP extui-align du 21/11, le problème est présent dans les 2 noyaux.

Dans l'écran debug du VDP2, le type de sprite est à 1. Ce type ne comporte pas de bit de shadow/sprite window sur le MSB. Je pense qu'il faudrait restreindre le fix aux types de sprite qui peuvent activer la sprite window avec leur MSB, donc les types de 2 à 7.

Le save state correspondant à la capture :
[mystaria_debut.zip](https://github.com/FCare/Kronos/files/3877453/mystaria_debut.zip)

Testé avec le CD PAL.
