### ISSUE TITLE
[Digital Ange - Dennou Tenshi SS] Sorte de voile gris...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#644]
![digitalange](https://user-images.githubusercontent.com/12481242/66509324-1a321680-ead3-11e9-81fa-31f23fa42add.PNG)

Savestate : 

[digitialdance.zip](https://github.com/FCare/Kronos/files/3708868/digitialdance.zip)

**Comment by fafling** [comment]
Il y a un cumul de problemes analysé sur le br #628 .
