### ISSUE TITLE
[BlamMachinehead] Les montagnes ne sont plus affichés en arrière plan...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#645]
![blam](https://user-images.githubusercontent.com/12481242/66517508-8a489880-eae3-11e9-93fd-8c2d9e38181f.PNG)

Savestate : 

[blammachinhead.zip](https://github.com/FCare/Kronos/files/3709282/blammachinhead.zip)

**Comment by fafling** [comment]
Je ne reproduit ce problème dans aucune WIP. Même dans la dernière, où l'écran est trop sombre, je vois les montagnes au fond.
![Capture_blam_acc_vdp1_20191010](https://user-images.githubusercontent.com/7624262/66611245-2f37a400-ebbe-11e9-997d-2f6075fcdcf7.PNG)
