### ISSUE TITLE
[Blammachine Head] Ecran assombrie sur tout le jeu...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#647]
![blam](https://user-images.githubusercontent.com/12481242/66608290-86d21180-ebb6-11e9-9402-01e9127319fc.PNG)

savestate : 

[blammachinehead.zip](https://github.com/FCare/Kronos/files/3714712/blammachinehead.zip)

**Comment by fafling** [comment]
Je ne sais pas si c'est lié, mais dans l'écran debug du VDP2, on voit que la sprite window est activé alors que le framebuffer est de type "RGB and palette". Le registre d'activation de la sprite window n'est effectif que lorsque le framebuffer est de type "palette only", voir p. 188 de la doc du VDP2.
![Capture_blam_vdp2_acc_vdp1_20191010](https://user-images.githubusercontent.com/7624262/66612401-f7caf680-ebc1-11e9-8818-b839fcdd7fc0.PNG)

**Comment by fafling** [comment]
Affichage correct en WIP du 11/10.
