### ISSUE TITLE
[Breakpoint Tennis] Régression avec les lignes sur le terrain...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#649]
![breakpoint tennis](https://user-images.githubusercontent.com/12481242/66677172-62833d00-ec69-11e9-8247-936d3421ccd0.PNG)

Save State : 

[breakpoint tennis.zip](https://github.com/FCare/Kronos/files/3719225/breakpoint.tennis.zip)

**Comment by fafling** [comment]
Pour moi il n'y a pas de régression. Ces polygones ne sont pas affichés en accurate_vdp1 comme en extui-align, avec le noyau OpenGL. Il n'y a qu'avec le noyau compute shader qu'elles sont correctes en extui-align.

**Comment by FCare** [comment]
Totalement d'accord. C'est du a la gestion des triangles. Seul le calcul en core compute shader peut regler le pb...
