### ISSUE TITLE
[World Advanced Daisenryaku - Sakusen File]Problème d'image qui s'étire in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#65]
UoYabause 1.3.1
Fork : François

Il semblerait que le problème vienne du NBG3. En le désactivant ca efface des textes, mais plus d'image qui s'étire.

![1worldadvancedingame](https://user-images.githubusercontent.com/12481242/35710157-dacc5636-07ad-11e8-87cb-8ec20bca1a2a.JPG)

**Comment by FCare** [comment]
J'ai le probleme par intermittence sur l'animation de boot du bios. Je ne sais pas si c'est du au patch sur l'aspect ratio ou seulement le fait qu'on voit le bug depuis qu'on ne dessine plus sur tout l'ecran...

**Comment by BenjaminSiskoo** [comment]
Encore un léger scintillement mais presque réglé :)

**Comment by BenjaminSiskoo** [comment]
Semble corrigé en ce jour
