### ISSUE TITLE
[Panzer Dragoon] Mauvais rafraîchissement sur version euro

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#653]
Bizarrerie découverte déjà depuis un certain temps, Kronos exécute Panzer Dragoon (Europe) en 60Hz alors qu'il devrait le faire en 50Hz. Confirmé par @BenjaminSiskoo aussi en version standalone, et @nicolas-charrier confirme que tout les jeux euro sont bien censé s’exécuter en 50Hz, donc çà doit être un bug dans Kronos.
Le jeu s’exécute bien en 50Hz sur mednafen.

**Comment by FCare** [comment]
lié a la detection de zone. Fixé
