### ISSUE TITLE
[Asuka 120% Limited] Persistence du character selection...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#654]
![asuka](https://user-images.githubusercontent.com/12481242/66700753-a1120980-ecf4-11e9-9d5c-799eb50e3559.PNG)

**Comment by fafling** [comment]
Pendant la persistance, toutes les couches du VDP2 sont désactivées, l'écran debug est vide.

**Comment by fafling** [comment]
Toujours présent en WIP du 13/10.
La rémanence est difficile à voir si l'arrière-plan de la fenêtre est clair.
Curieusement, si on réduit la fenêtre de Kronos dans la barre des tâches après l'avoir mis en pause, puis on la restaure, la rémanence est plus visible :
![image](https://user-images.githubusercontent.com/7624262/66715220-d84dec80-edc0-11e9-92f4-f8e6bbb23716.png)

**Comment by BenjaminSiskoo** [comment]
Semble corrigé en opengl et en CS

**Comment by fafling** [comment]
@BenjaminSiskoo Pour moi c'est toujours présent dans les 2 noyaux, et toujours accentuée après une réduction dans la barre des tâches avec l'émulateur en pause.
C'est aussi accentué en plein écran, sans avoir besoin de mettre en pause.

**Comment by BenjaminSiskoo** [comment]
Je réouvre si c'est pas bon pour toi

**Comment by fafling** [comment]
En WIP du 03/01, je ne perçois plus cette rémanence, contrairement à celle de MegamanX3 #1289 .

**Comment by BenjaminSiskoo** [comment]
Corrigé le 18.01.2022
