### ISSUE TITLE
Freezes avec la synchro verticale activée

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#655]
Kronos freeze aléatoirement pendant les jeux avec la synchro verticale activée. Ces freezes ne se produisent pas si l'option est désactivée (testé pendant plus d'un mois, aucun freeze de ce type).

Les autres options n'ont pas l'air d'influencer ce problème.

Ne semble pas affecter des jeux en particulier, s'est produit en WIP accurate_vdp1 du 13/10 dans Shining force 3 (2 mn pendant l'intro du jeu) et Sonic 3D (1 mn pendant la video).

**Comment by fafling** [comment]
Freeze dans Panzer Dragoon (jap) au bout de 2 mn en mettant en pause.

**Comment by fafling** [comment]
Freeze dans Sky target au bout de 7 mn.

**Comment by fafling** [comment]
Freeze à l'écran Sega Saturn de fin d'animation du bios alors que j'avais maximisé une autre fenêtre que Kronos.

**Comment by fafling** [comment]
Freeze Rayman (US) pendant le cycle de demo au bout de 6 mn. Rien d'affiché dans debugview au moment du freeze.

Affichage du journal d'événement :

Le programme kronosvdp1_20191013 fix end code Tomb raider.exe version 0.0.0.0 a cessé d'interagir avec Windows et a été fermé. Pour voir si plus d'informations sur le problème sont disponibles, vérifiez l'historique des problèmes dans le Panneau de configuration Sécurité et maintenance.
 ID de processus : 4f20
 Heure de début : 01d581c362c1fb05
 Heure d'arrêt : 18
 Chemin d'accès à l'application : C:\Users\Nicolas\Documents\Téléchargements\émulateurs\Kronos 2.0 acc VDP1\kronosvdp1_20191013 fix end code Tomb raider.exe
 ID de rapport : f502733e-37a5-4cfd-b7af-0fd39428a415
 Nom complet du package défectueux : 
 ID de l'application relative à un package défectueux : 
 Type de blocage : Unknown

**Comment by fafling** [comment]
Freeze au bout de 2 mn dans la video de J. League Victory Goal '96 (redump, alors que les tests précédents sont fait sur CD).

Une fois que le freeze s'est produit, la charge CPU et GPU de Kronos tombe à 0%. Le freeze s'est produit au moment ou j'ai fait un clic doit sur l'icône du menu démarrer pour déclencher le gestionnaire des tâches (bien sûr, c'est non reproductible, ce serait trop simple).

**Comment by fafling** [comment]
Problème toujours présent en WIP extui-align du 19/11, reproduit dans Burning rangers au bout de 5-6 minutes de jeu dans les 2 noyaux.

**Comment by paul-met** [comment]
The same issue.
**My PC specs:**
- Win 10 x64 Pro
- QuadCore Intel Core i5-2500K, 4500 MHz (45 x 100)
- GeForce GTX 1060 6GB
- 16 GB DDR3 SDRAM
- USB SVEN X-Pad

**Comment by fafling** [comment]
jomanakk a signalé avoir ce problème sur le Discord Kronos dans Sonic 3D blast avec Kronos v2.3.1. Les specs de son PC :
Windows 10
Intel core I5 12400F
GTX 1650 4gb

J'ai reproduit également en v2.3.1 avec Mystaria (PAL). Mes specs :
Windows 10 64 bit
Intel Core i3 2.80GHz
16 Go de RAM
Nvidia GTX 750 Ti 2 Go

Quand l'option de synchro verticale de Kronos est désactivée, il est possible de limiter le framerate de Kronos à la fréquence de l'écran en activant la synchronisation verticale dans le panneau de configuration Nvidia. Dans mon cas, cela limite le framerate de Kronos à 60.

**Comment by vbt1** [comment]
same here 
Windows 7 64bits
amd 3300x
nvidia 1660 super
32go ram

**Comment by vbt1** [comment]
semble corrigé avec le dernier wip après la 2.6
