### ISSUE TITLE
[The need for speed] Ecran de chargement corrompu en accurate_vdp1

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#657]
En WIP accurate_vdp1 du 13/10, il y a une corruption de l'écran de chargement quand on appuie sur start pour interrompre la video des logos ou d'intro.
![image](https://user-images.githubusercontent.com/7624262/66719023-dbf66900-edea-11e9-9250-d84918ec485a.png)

Affichage correct en extui-align (après un freeze de 2 mn en OpenGL) :
![image](https://user-images.githubusercontent.com/7624262/66719074-7c4c8d80-edeb-11e9-898d-9e1f8a5d92d7.png)

L'écran de chargement est probablement affiché par la couche de sprites avec gel du basculement du framebuffer car il est impossible de le désactiver, et il disparaît si on pause l'émulation et qu'on la relance, ou si on affiche puis ferme une fenêtre de menu de Kronos, voir #552 .

Testé avec le CD US.

**Comment by fafling** [comment]
Toujours présent en WIP accurate_vdp1 du 22/10.

**Comment by FCare** [comment]
Fixé le 24/10/19
