### ISSUE TITLE
[Mass Destruction] Régression sur la carte in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#659]
La carte est affiché que sur la moitié.

![massdestruction](https://user-images.githubusercontent.com/12481242/67297939-daaff500-f4ea-11e9-8b10-39b6cbba1d39.PNG)

Savestate : 

[massdestruction.zip](https://github.com/FCare/Kronos/files/3756368/massdestruction.zip)

**Comment by FCare** [comment]
Fixé le 24/10/2019
