### ISSUE TITLE
Régression avec les correctifs du 1er Février...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#66]
3D Baseball : Yabause plante après l'intro vidéo. Pas de soucis avec les fixs du 30 Janvier 2018. J'ai redo le fix suivant : https://github.com/FCare/yabause/commit/0fd0f10cc78124691fa5d1b727b4eaf6101a44dc et le jeu plante plus.

**Comment by FCare** [comment]
Je ne le reproduit pas chez moi....

**Comment by FCare** [comment]
Fixé avec https://github.com/FCare/yabause/commit/a8ee29c6c2dcbea2ec2647f34312415dc4940fae

**Comment by BenjaminSiskoo** [comment]
Corrigé
