### ISSUE TITLE
[Neon Genesis - Digital Card Library] Décalage de l'arrière plan..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#660]
WIP du 22/10/2019

![neondigital](https://user-images.githubusercontent.com/12481242/67305620-e7861600-f4f5-11e9-9e0a-a7649546665e.PNG)

Savestate : 
[neongenesisdigital.zip](https://github.com/FCare/Kronos/files/3756956/neongenesisdigital.zip)

**Comment by FCare** [comment]
Fixed Wip 24/10/19
