### ISSUE TITLE
[Kuro no Danshou - The Literary Fragment] Le titre passe sous l'écran...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#661]
Wip du 24/10/2019 - OpenGL sans filtre

![kuro](https://user-images.githubusercontent.com/12481242/67616226-90729080-f7d6-11e9-8778-7844afa4c2bc.PNG)

Savestate : 

[kuro.zip](https://github.com/FCare/Kronos/files/3774576/kuro.zip)

**Comment by BenjaminSiskoo** [comment]
![kuro1](https://user-images.githubusercontent.com/12481242/67616638-9323b480-f7db-11e9-85ae-4c99413a34e5.PNG)

**Comment by fafling** [comment]
C'est un problème général sur la branche accurate_vdp1 sur les jeux en haute résolution non entrelacé. Die hard arcade et NBA live 98 ont le même problème d'upscale vertical incorrect des sprites.

**Comment by fafling** [comment]
Le problème d'upscale vertical est réglé dans les 3 jeux en WIP du 28/10.
