### ISSUE TITLE
[Doom] Fenêtre incorrecte pour les sprites

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#665]
En WIP accurate_vdp1 du 26/10, les côtés de la fenêtre qui limite les sprites ont un décalage par rapport aux côtés de la barre de statut de 7 pixels à gauche et un pixel à droite :
![image](https://user-images.githubusercontent.com/7624262/67626833-55617300-f851-11e9-839d-85d672b1e280.png)
Ce problème apparaît en WIP du 22/10.

En WIP extui-align du 11/09, dans les 2 noyau, ce n'est pas correct non plus : il y a un décalage d'un pixel à droite par rapport à la barre de statut :
![image](https://user-images.githubusercontent.com/7624262/67626864-d6206f00-f851-11e9-9e1e-5f958d6fef20.png)
Ce problème est présent en v1.7.0 publique.

Sur la console, les côtés de la fenêtre des sprites sont alignés avec ceux de la barre, il n'y a aucun décalage.

Un save state pour reproduire :
[Doom_debut_niv1.zip](https://github.com/FCare/Kronos/files/3775331/Doom_debut_niv1.zip)

Testé avec le CD jap.

**Comment by fafling** [comment]
En WIP du 06/12, il reste le décalage de 1 pixel à droite dans les 2 noyaux.

**Comment by fafling** [comment]
OK dans les 2 noyaux en WIP du 13/04, le fix date de la WIP du 02/04.

**Comment by fafling** [comment]
Dans la dernière WIP, et depuis la 3ème WIP du 15/12, dans les 2 noyaux, il y a de nouveau une colonne d'un pixel en moins à droite des sprites par rapport à la barre de statut (capture en integer scaling en noyau CS) :
![image](https://user-images.githubusercontent.com/7624262/147887676-d81c4501-549a-4572-9c9b-45041cdddfe6.png)

Testé avec le CD jap.

Save state créé avec la WIP du 31/12, incompatible avec la v2.2.0 publique :
[Doom_debut_niv1_20211231.zip](https://github.com/FCare/Kronos/files/7799690/Doom_debut_niv1_20211231.zip)

**Comment by BenjaminSiskoo** [comment]
Correction de la ligne de pixel en trop le 18.01.2022
