### ISSUE TITLE
[M (emu) Kimo wo Tsutaete (J)] Régression avec le VDP1...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#667]
Wip du 27/10/2019 : en désactivant la couche VDP1, on voit l'arrière plan rose.

![m](https://user-images.githubusercontent.com/12481242/67632086-f7f41300-f89e-11e9-8e29-22a5b68b2e2b.PNG)

Save state : 
[m.zip](https://github.com/FCare/Kronos/files/3775643/m.zip)

**Comment by fafling** [comment]
Le framebuffer est de type RGB + palette. Il n'y a pas de color calculation d'activée sur les couches concernées (sprites et NBG0). Le NBG0 (priorité 4) est bien sensé être derrière les sprites (priorité 5).
Le problème qui apparaît avec le fix de la couleur du VBLANK erase (voir #662 ). Si on suppose que ce fix est correct, c'est peut-être encore un autre cas de jeu qui s'attend à ce que le noir RGB soit transparent (voir #643 et #211 ).
Est-ce que la couleur du registre erase/write data EXDR du VDP1 est bien du noir RGB ?
Si oui, est-ce que la transparent shadow est activée (registre TPSDSL du VDP2) ?

**Comment by fafling** [comment]
Et est-ce que le framebuffer est bien en 16 bpp, comme le type de sprite le laisse supposer ?

**Comment by BenjaminSiskoo** [comment]
Corrigé le 28/10/2019

**Comment by fafling** [comment]
Fixé en WIP accurate_vdp1 du 28/10 en rendant transparents les pixels à 8000 d'un framebuffer RGB+palette quand la sprite window est activée.

**Comment by fafling** [comment]
Correct aussi dans les 2 noyaux en WIP extui-align du 19/11.
