### ISSUE TITLE
[Scorcher] Ecran noir in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#668]
Savestate

[scorcher.zip](https://github.com/FCare/Kronos/files/3776082/scorcher.zip)

**Comment by fafling** [comment]
Il y a 2 invalid opcodes en début de course qui apparaissent avec l'écran noir depuis la WIP du accurate_vdp1 du 25/10 :

Error: Slave SH2 invalid opcode

R0 =  00000000 R12 =  00000000
R1 =  FFFF8888 R13 =  00000000
R2 =  060FDF08 R14 =  06005F88
R3 =  00226824 R15 =  060D2FB4
R4 =  00000000 SR =   000002F3
R5 =  00000000 GBR =  FFFFFE00
R6 =  E0000000 VBR =  06000400
R7 =  E0000000 MACH = 00000033
R8 =  00000000 MACL = 00003FC1
R9 =  00000000 PR =   00000212
R10 = 00000000 PC =   E000022E
R11 = 00000000

Error: Master SH2 invalid opcode

R0 =  25C04D00 R12 =  00000000
R1 =  06012908 R13 =  00000000
R2 =  25C04D00 R14 =  00000000
R3 =  25C04D00 R15 =  060D0EA0
R4 =  060D0F3C SR =   00000020
R5 =  00000018 GBR =  060CFF58
R6 =  060F112C VBR =  06000000
R7 =  060FCC14 MACH = 000E4236
R8 =  002802B4 MACL = 00000048
R9 =  00000000 PR =   0600ABE0
R10 = 00000000 PC =   06012908
R11 = 00000000

**Comment by fafling** [comment]
Testé avec le CD version US.

**Comment by fafling** [comment]
Fixé en WIP du 08/12 dans les 2 noyaux.
Doublon de #545 .
