### ISSUE TITLE
[Taito Chase HQ SCI] Problème de VDP1...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#669]
Wip duy 27/10/2019 : 

![taitochase](https://user-images.githubusercontent.com/12481242/67637559-fbf25600-f8db-11e9-9dc7-77ee44f4de88.PNG)
![taitochaseingame](https://user-images.githubusercontent.com/12481242/67637561-ff85dd00-f8db-11e9-8958-0d95de3f7d78.PNG)

Savestate : 

[taito.zip](https://github.com/FCare/Kronos/files/3776094/taito.zip)

**Comment by fafling** [comment]
Le jeu utilise un polygone d'effacement avec la couleur hexa 8000.
Le framebuffer est de type palette only et le type de sprite est 3. Dans ce type de framebuffer, quand le MSB du type de sprite est un bit de shadow/sprite window, un pixel avec la valeur hexa 8000 est considéré comme transparent, comme ceux avec la valeur 0000. La différence est que les pixels à 8000 sont inclus dans la sprite window ou la transparent shadow si ces traitements sont activés.

**Comment by FCare** [comment]
suffisait de le dire :-) Fixé

**Comment by BenjaminSiskoo** [comment]
Merveilleux ^^
