### ISSUE TITLE
[Athlete Kings] Logo manquant sur le press start screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#67]
UoYabause 1.3.1
Fork : François

Il n'y a plus le logo, probablement cassé avec la branche timing, mais pas avec les fixs vidéos (wing arms).

![1athletekings](https://user-images.githubusercontent.com/12481242/35710751-0a03fb22-07b1-11e8-8c81-e10d8bf138e3.JPG)

**Comment by FCare** [comment]
PAtch poussé. Réglé chez moi

**Comment by BenjaminSiskoo** [comment]
Corrigé le 2 février 2018
