### ISSUE TITLE
[The need for speed] Ecran de chargement manquant en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#677]
En WIP extui-align du 19/11, seulement dans le noyau CS, l'écran de chargement ne s'affiche pas quand on appuie sur start pour interrompre la video des logos ou d'intro.

Affichage correct en noyau OpenGL :
![image](https://user-images.githubusercontent.com/7624262/69199929-e74f5980-0b39-11ea-9921-855b07d65a8e.png)

**Comment by fafling** [comment]
Toujours présent en WIP du 30/12.

**Comment by BenjaminSiskoo** [comment]
@fafling ca semble corrigé avec la WIP du 15/01/2020

**Comment by fafling** [comment]
Oui, c'est réglé.
