### ISSUE TITLE
[Bug Too/Touge King Of Spirit] Yabause plante (uniquement sur Windows)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#68]
UoYabause 1.3.1
Fork : François

Fonctionne sous Linux mais pas sous windows. 

Yabause plante avant l'écran press start. Régression à cause de ce commit : https://github.com/FCare/yabause/commit/c7a767065553f14cfac372d91f503261acae89bc

**Comment by FCare** [comment]
Pas de pb chez moi...

**Comment by BenjaminSiskoo** [comment]
Plante toujours.

**Comment by FCare** [comment]
Ca crashe ou ca bloue sur un ecran noir? Je refais encore et encore le test, je vois des ralentissements dans l'emulation apres la video mais si on attend assez, on arrive a l'ecran start...

**Comment by BenjaminSiskoo** [comment]
Ca plante l'émulateur. il ne répond plus.

**Comment by FCare** [comment]
La fonction VDP1ReadFramebuffer etait bloquante parce qu'elle generait toujours des erreurs... J'ai fixé, chez moi, j'arrive plus vite a l'ecran start, je pense que chez toi ca devrait regler le blocage...

**Comment by BenjaminSiskoo** [comment]
Corrigé
