### ISSUE TITLE
Testing various issues with latest build of Kronos

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#688]
[2019-11-27 20-44-09.zip](https://github.com/FCare/Kronos/files/3898775/2019-11-27.20-44-09.zip)

[2019-11-27 20-49-24.zip](https://github.com/FCare/Kronos/files/3898791/2019-11-27.20-49-24.zip)

[2019-11-27 20-54-48.zip](https://github.com/FCare/Kronos/files/3898802/2019-11-27.20-54-48.zip)

I recorded some videos testing the latest Kronos WIP build (From 26/11/2019) 

Some games just crash when loading (Road Rash, and Guardian Heroes)

Some others have graphical problems (Upscaling issues like the character's face in shining force 3, the horrible upscaling of the characters in deep fear, and some issues with the screen (on deep fear too)

You can see all the issues in the videos attached. Hope it helps.

**Comment by LuismaSP89** [comment]
Here's the last one, I uploaded to google drive since the size is more than 25mb and can't be attached in github:

https://drive.google.com/drive/folders/1LOAFdvUTPuNz2Hkz8ZfgRM-gyGYrMRKm?usp=sharing

**Comment by LuismaSP89** [comment]
PS: The upscaling issues in deep fear and shining force are happening from long time ago, there are not issues related with the latest build.

**Comment by LuismaSP89** [comment]
I forgot o mention that deep fear have sound issues too in this builds, in one of the videos you can hear the sound (Annoying sound) like a choppy TV snow.

**Comment by fafling** [comment]
The current WIP is supposed to be tested only with original resolution, the upscale is not ready yet.

Deep fear sound glitch was listed in #556 , and was temporarily fixed. As you found out, it has reappeared 2 months ago.
