### ISSUE TITLE
[Fonctionnalités] Problème sauvegarde/chargement d'état...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#69]
UoYabause 1.3.1
Fork : François

Possible qu'il y ai un rapport avec tes correctifs sur le backup manager.

Quand on sauvegarde un jeu (Save State) et que l'on recharge (Load State). Message d'erreur qui dit couldn't load a state.

**Comment by FCare** [comment]
Patch a l'aveugle poussé

**Comment by BenjaminSiskoo** [comment]
Ce n'est pas corrigé.
