### ISSUE TITLE
Superposition de half-transparency VDP1 incorrecte en noyau OpenGL

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#691]
Dans Powerslave, en WIP du 29/11, avec la tessellation CPU ou GPU en noyau OpenGL, il y a un bruit video sur la fenêtre qui entoure le nom du niveau.
![image](https://user-images.githubusercontent.com/7624262/69907895-d2e34a80-13de-11ea-9f53-1bd878873ace.png)

En tessellation triangles with perspective correction la fenêtre n'est pas assez sombre :
![image](https://user-images.githubusercontent.com/7624262/69907900-fb6b4480-13de-11ea-8444-838227ad36e9.png)

Affichage correct en noyau CS :
![image](https://user-images.githubusercontent.com/7624262/69907945-bb589180-13df-11ea-8023-c1212ce3a7c4.png)

La fenêtre est dessinée par 2 commandes successives de polygone noir sur les mêmes coordonnées avec un effet de half-transparency :
![image](https://user-images.githubusercontent.com/7624262/69907947-cd3a3480-13df-11ea-9a42-83fae1f9c94b.png)

Comme la half transparency du VDP1 est cumulative, l'effet final doit être d'un quart de luminance sur la zone de la carte modifiée par les polygones.

Testé avec le CD US.

**Comment by FCare** [comment]
Les commandes se suivent, le meme programme openGL s'occupe des memes triangles. seul le dernier triangle "gagne"... c'est inherent a la stack openGL, si un triangle modifie le framebuffer, et, dans le meme programme, un autre triangle modifie le meme pixel, seule le deuxieme calcul est prit en compte. il faudrait separer les programmes et donc faire baisser la performance pour regler le pb. Je le laisse de coté pour l'instant.

**Comment by fafling** [comment]
En WIP du 09/04, en OpenGL seulement, probablement le même problème sur le menu pause de NBA jam extreme qui superpose 2 polygones en mesh, un noir puis un blanc, utilisant la half transparency. Le polygone blanc du dessus comporte des carrés clignotants dans une zone triangulaire en bas à gauche, le reste est correct :
![image](https://user-images.githubusercontent.com/7624262/78931241-ed70b300-7aa5-11ea-999d-e3bf3535f36c.png)

Testé avec le CD PAL.

**Comment by fafling** [comment]
Le bruit video dans Powerslave est réglé en WIP du 19/05. Le niveau de transparence reste incorrect.
Le problème reste inchangé dans NBA jam extreme.

**Comment by BenjaminSiskoo** [comment]
Kronos du 13.12.2021

Pour NBA Jam Extreme, le problème a changé, les carrés clignotants sont situés sur la première moitié haute de la pause : 

![image](https://user-images.githubusercontent.com/12481242/145836126-0954ce3f-f1b0-44fe-9e88-4d798c8de7c0.png)

Savestate : 

[T-8120H-50_000.zip](https://github.com/FCare/Kronos/files/7704726/T-8120H-50_000.zip)

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 13.12.2021 https://github.com/FCare/Kronos/commit/167843a84c35b6aae52aca3102e1a9eff8776258

![image](https://user-images.githubusercontent.com/12481242/145852183-b457056e-fb92-479d-a764-dcf3141036a0.png)

**Comment by fafling** [comment]
Chez moi, les clignotements sont maintenant sur tout le polygone blanc :
![image](https://user-images.githubusercontent.com/7624262/145910609-99ea1392-8029-4de9-9991-a6abc774b078.png)

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 03.01.2022
Mode CS
Mesh ON

![image](https://user-images.githubusercontent.com/12481242/147995412-a23e8249-1800-432e-b869-3427d139689c.png)

OpenGL je suis mode sapin de Noël : 

![image](https://user-images.githubusercontent.com/12481242/147995665-259e7235-f528-49a8-b468-29d21fda5476.png)

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 03.01.2022
Mode CS
Triangles using perspective correction

![image](https://user-images.githubusercontent.com/12481242/147995542-de9746d4-783a-470b-a4cc-ceba915db8b2.png)

**Comment by BenjaminSiskoo** [comment]
Kronos du 04.01.2022
Mode CS
Mesh On

![image](https://user-images.githubusercontent.com/12481242/148085312-41be8439-5507-41ee-9ca1-ce48f84d5941.png)

Mode CS
Mesh Off

![image](https://user-images.githubusercontent.com/12481242/148085564-b87cb27d-c508-46c2-be3b-46808c057037.png)

Mode OpenGL
Mesh On

![image](https://user-images.githubusercontent.com/12481242/148085808-8e687092-091f-4673-86d8-07f6bde7abbc.png)

Mode OpenGL
Mesh Off

Clignote de tous les côtés 

![image](https://user-images.githubusercontent.com/12481242/148085883-b5fc4104-f789-4f4e-892c-444ad40f03c6.png)

**Comment by BenjaminSiskoo** [comment]
Support OpenGL supprimé
