### ISSUE TITLE
[Interface QT] Freeze quand on "mute" le son

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#693]
En WIP du 01/12 dans les 2 noyaux, comme en v1.7.0 publique, quand on clique sur l'icône son et qu'on décoche la case "Mute/Unmute sound" pendant que l'émulation fonctionne, Kronos freeze. si on le fait avant de lancer l'émulation, Kronos freeze au démarrage de l'émulation.

**Comment by fafling** [comment]
Toujours présent en WIP du 07/09/2021.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 13.09.2021

**Comment by fafling** [comment]
Fixé en WIP du 14/09.
