### ISSUE TITLE
[Sonic Jam] Interrupt non émulé dans Sonic 3

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#695]
En WIP du 01/12 dans les 2 noyaux, dans le 1er niveau de Sonic 3, tout l'écran prend une teinte bleutée quand l'eau est visible, au lieu de n'afficher cette teinte que dans la partie de l'écran sous l'eau.
![image](https://user-images.githubusercontent.com/7624262/69924691-f2e13f80-14ac-11ea-8180-751f298266cf.png)

Affichage correct :
![image](https://user-images.githubusercontent.com/7624262/69924571-777f8e00-14ac-11ea-89ae-fa86569b682b.png)

L'effet est certainement obtenu par une modification de paramètres du VDP2 pendant la période d'affichage déclenchée par un interrupt (changement de palette dans la color RAM ou bien modification de color RAM offset).

Problème déjà présent en v1.7.0 et v1.6.0 publiques. 

Un save state pour arriver directement à cet endroit :
[sonic_jam_sonic3_interrupt_eau.zip](https://github.com/FCare/Kronos/files/3909073/sonic_jam_sonic3_interrupt_eau.zip)

Testé avec le CD US.

**Comment by FCare** [comment]
La colorRam est modifiée a la ligne 69. PAs sur que ca soit pris en compte en cours de route

**Comment by fafling** [comment]
Fixé en WIP du 06/12 dans les 2 noyaux.

**Comment by fafling** [comment]
Je réouvre car Kronos n'applique pas le changement de couleur aux sprites, qui devrait prendre une teinte bleu-vert sous l'eau.

Je n'ai pas trouvé de version de Kronos où ça fonctionnait. A priori ça n'a jamais marché.

C'est nettement visible sur la console, notamment sur les troncs qui tombent de la cascade ont une moitié inférieure changeant nettement de couleur quand ils touchent l'eau (à gauche Kronos, à droite la console) :
![image](https://github.com/FCare/Kronos/assets/7624262/57baa08d-deb0-41c1-9d5c-171d09e600d3)

Save state (incompatible avec la v2.5.0 publique) :
[sonic_jam_sonic_3_interrupt_eau_v2.5.0_20231116.zip](https://github.com/FCare/Kronos/files/13384782/sonic_jam_sonic_3_interrupt_eau_v2.5.0_20231116.zip)

**Comment by BenjaminSiskoo** [comment]
J'ai mis à jour la savestate avec la dernière WIP du 23 Aout 2024

[sonicjam-sonic3.zip](https://github.com/user-attachments/files/16746375/sonicjam-sonic3.zip)
