### ISSUE TITLE
[All-Star Baseball '97 featuring Frank Thomas] Régression mais amélioration

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#697]
Testé avec la version 64 bits du 6 Décembre 2019
Testé avec la version 64 bits du 8 Décembre 2019

![allstarbaseball](https://user-images.githubusercontent.com/12481242/70388919-956f5600-19b8-11ea-8515-84c4de28d4b1.PNG)

Avec la version du 6 décembre le sol in game est noir mais pas de chute de FPS
Avec la version du 8 décembre pas de soucis graphique mais chute de FPS en changeant d''écran

save state : 

[allstarbaseball98.zip](https://github.com/FCare/Kronos/files/3936181/allstarbaseball98.zip)

**Comment by FCare** [comment]
VDP1 CMD 6 added in loop.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 17/12/2019
