### ISSUE TITLE
[Scorcher] Sprites manquants

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#698]
En WIP du 08/12 dans les 2 noyaux, il manque les sprites qui sont dessinés en dernier : compte tour, pace en course, messages.
![Capture](https://user-images.githubusercontent.com/7624262/70389264-51328480-19bd-11ea-8147-e79c57ed7285.PNG)

Ces éléments sont forcément dessinés dans le framebuffer, car aucune couche VDP2 ne peut les afficher vu que les RBG0 et RBG1 servent à l'arrière plan.

L'écran débug n'affiche pas ces commandes, la dernière est celle de la carte du circuit. Elles sont probablement envoyée au VDP1 dans un batch de commandes séparé.

Testé avec le CD US.

**Comment by FCare** [comment]
En effet, il manque des commandes. je ne les vois jamais dans le VDP1, dans la stack openGL. On doit sauter une commande du VDP1. On les as deja affiché a un moment dans kronos ou dans yaba?

**Comment by fafling** [comment]
Yabause 0.9.14 en affiche une partie, et la 0.9.15 les affiche toutes.
UoYabause les affichait toutes jusqu'en 0.3.9, la 0.4.0 n'affiche plus rien.

**Comment by fafling** [comment]
Une autre possibilité est que les sprites manquants soient dessiné directement par les CPU dans le framebuffer. Les programmeurs de ce jeu sont du genre a avoir tenté ça.
Apparemment l'émulation de la mémoire du framebuffer ne fonctionne plus dans Kronos.

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 05.01.2022
Mode Cs
Option vidéo par défaut

Amélioration pour la première du HUD. On voit le compteur de temps. On note l'arrivée d'un artefact en haut de l'écran et des scintillements au début de la course sur le HUD.

![image](https://user-images.githubusercontent.com/12481242/148360290-41a1b269-1925-49fe-8198-17fa4abfba9d.png)

Après avoir pressé sur Start pour faire une pause et en revenant sur le jeu, le ciel est affiché de manière incorrecte. En allant dans le menu pause et en pressant sur restart, le ciel revient à la normal.

![image](https://user-images.githubusercontent.com/12481242/148360697-5e938f2b-7b8b-4968-9308-10380094b8a8.png)

Savestate : 
[MK-81214_000.zip](https://github.com/FCare/Kronos/files/7820793/MK-81214_000.zip)

**Comment by BenjaminSiskoo** [comment]
Presque corrigé : 
![image](https://user-images.githubusercontent.com/12481242/216206131-40582dfb-837e-43b1-9649-5a06cf9f81de.png)

Encore quelques scintillements sur le compteur de droite

**Comment by BenjaminSiskoo** [comment]
Réglé en mode CS. Le compteur de chiffre (35) clignote en OpenG lmais OpenGl n'est plus assuré par @FCare  je ferme
