### ISSUE TITLE
[Doukoku soshite] Ratio de semi transparence trop faible sur dialogues et sélections

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#700]
En WIP du 08/12 dans les 2 noyaux, les fenêtres de dialogues et les rectangles de sélections semi-transparents sont nettement moins visibles que sur la console :
- Saisie du nom :
![image](https://user-images.githubusercontent.com/7624262/70398234-a43a2500-1a19-11ea-96ae-0a5fa1b1a1bd.png)

- 1er dialogue :
![image](https://user-images.githubusercontent.com/7624262/70398253-c5027a80-1a19-11ea-848c-e4b8cd021082.png)

- Sélection d'un choix :
![image](https://user-images.githubusercontent.com/7624262/70398283-11e65100-1a1a-11ea-8a34-9a0badfad4d6.png)

Les save states correspondants :
[doukoku.zip](https://github.com/FCare/Kronos/files/3937299/doukoku.zip)

Le problème existait déjà en v1.7.0 publique.

Testé avec le CD.

**Comment by BenjaminSiskoo** [comment]
Problème toujours présent Kronos 2.2.0 du 13.12.2021

**Comment by fafling** [comment]
Fixé en WIP du 18/01/2022 dans les 2 noyaux.
