### ISSUE TITLE
[Ponut64 demo] Bitmap manquant sur le NBG1

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#702]
En WIP du 08/12 dans les 2 noyaux, il manque l'affichage du bitmap de la carte sur la couche NBG1.
![image](https://user-images.githubusercontent.com/7624262/70400489-7cec5380-1a2b-11ea-8ecd-def4b5ec20d1.png)

Le VDP2 est en hi-res, et le bitmap en 16 bpp RGB. Il s'affiche bien sur la console.

L'ISO de la demo est dans le br #701 .

**Comment by BenjaminSiskoo** [comment]
Toujours présent sur la Wip du 31/03/2020 (commits 2605)

**Comment by BenjaminSiskoo** [comment]
Toujours présent sur Kronos 2.2.0  du 13/12/2021

**Comment by fafling** [comment]
La carte n'est pas à l'écran parce que le NBG1 est zoomé verticalement de façon incorrecte quand il est en mode bitmap et quand le VDP2 est en double interlace.

**Comment by fafling** [comment]
Réglé par https://github.com/FCare/Kronos/commit/8badbddbfdc21149082998c0ff4ef13a5c1e497f
