### ISSUE TITLE
 [Nights] Vortex incorrect pendant les boucles (NBG3)

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#704]
En WIP du 08/12 dans les 2 noyaux et en v1.7.0 publique, le vortex n'est pas affiché par Kronos quand Nights fait une boucle :
![image](https://user-images.githubusercontent.com/7624262/70487282-1f243e00-1af5-11ea-8c5a-fc9a267f108c.png)

Affichage correct en v1.6.0 :
![image](https://user-images.githubusercontent.com/7624262/70486895-c011f980-1af3-11ea-9934-094a2a0d75c2.png)

Le vortex est affiché par le NBG3. Il combine les 2 fenêtres W0 et W1 en mode line window pour le délimiter :
![image](https://user-images.githubusercontent.com/7624262/70487047-4af2f400-1af4-11ea-9c19-6f775af8b45d.png)

Un save state correspondant à cette capture :
[nights_vortex.zip](https://github.com/FCare/Kronos/files/3942563/nights_vortex.zip)

Testé avec le CD US.

**Comment by fafling** [comment]
En WIP du 17/12, les vortex sont de nouveau visibles dans les 2 noyaux, par contre leur contour n'a pas l'air toujours correct :
![image](https://user-images.githubusercontent.com/7624262/71045143-3043ff00-2134-11ea-8bbe-418390e0fb2b.png)

Il y a un rectangle en haut du vortex qui n'apparaît pas en v1.6.0 :
![image](https://user-images.githubusercontent.com/7624262/71045090-fd9a0680-2133-11ea-8c04-92940fd93741.png)

Save state :
[nights_vortex_rectangle.zip](https://github.com/FCare/Kronos/files/3976040/nights_vortex_rectangle.zip)

**Comment by BenjaminSiskoo** [comment]
Megaman X3 serait peut être concerné avec le projecteur qui disparait partiellement :  https://www.youtube.com/watch?v=-TJwyCYmyKg&feature=youtu.be&t=254

**Comment by fafling** [comment]
Nouveau save sate pour Nights (US), l'ancien ne marche plus en WIP :
[nights_vortex_rectangle_20201205.zip](https://github.com/FCare/Kronos/files/5647166/nights_vortex_rectangle_20201205.zip)

Et pour Megaman X3 (PAL) :
[megaman_x3_projecteur.zip](https://github.com/FCare/Kronos/files/5647167/megaman_x3_projecteur.zip)

Le problème en mouvement : [https://youtu.be/-TJwyCYmyKg?t=254](https://youtu.be/-TJwyCYmyKg?t=254)

Sur Megaman, comme dans Nights, le problème est présent dans les 2 noyaux et touche un NBG qui utilise la line window :
![image](https://user-images.githubusercontent.com/7624262/101245050-81b11980-370a-11eb-8577-a0fbf7c0fe46.png)

**Comment by fafling** [comment]
L'affichage des vortex est correct dans les 2 noyaux dans la dernière WIP, et depuis la 3ème du 15/12 qui corrige les combinaisons de fenêtres. C'était donc le même problème que #986 .
