### ISSUE TITLE
Dragon Force II graphic issue

### ISSUE THREAD

**Issue by randalltlc** [FCare/Kronos#711]
the graphic look ok when opened in yabause thou alot of problem so using kronos instead... wonder if there is any solution for this?

![DF2 error](https://user-images.githubusercontent.com/58886630/70851692-70f10d80-1ed3-11ea-84f4-0b51066029e2.png)

got the game from here if need to test:
https://www.nextgenroms.com/topic/5621-%E3%80%90dragon-force-2%E3%80%91%E3%80%90english-patched%E3%80%91%E3%80%90ntsc-jp-tnw%E3%80%91/

**Comment by randalltlc** [comment]
![df2 map](https://user-images.githubusercontent.com/58886630/70851762-5e2b0880-1ed4-11ea-9161-0c54c7be7c03.png)
suppose to be this color if loaded correctly for the graphics... only on the main map thou, when in battle the color comes back.

**Comment by randalltlc** [comment]
also time to time the emulator will hang

**Comment by FCare** [comment]
It is fixed in the current work in progress. It will be released soon as 2.0 version.
