### ISSUE TITLE
[Zap Snowboarding 98] Baisse des FPS sur certains jeux...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#714]
Wip du 20/12/2019

Concerne vandal hearts, Digital Ange - Dennou Tenshi SS 

[zapsnow.zip](https://github.com/FCare/Kronos/files/3989371/zapsnow.zip)

**Comment by fafling** [comment]
Pas de baisse chez moi en CS par rapport aux versions précédentes sur Zap Snowboarding 98, avec ou sans la synchro. Une différence ATI/Nvidia ?
