### ISSUE TITLE
[Real Bout] Last version of Kronos for Retroarch

### ISSUE THREAD

**Issue by Anths2016** [FCare/Kronos#715]
Everything freezes at the Saturn screen.

**Comment by FCare** [comment]
Are you using a real bios or the emulated one? Did you tried the standalone version of kronos? The redump image is working well on my side with real bios.

**Comment by Anths2016** [comment]
No, I used the Retroarch version.

**Comment by barbudreadmon** [comment]
@Anths2016 that's an impressive bug report i'm seeing here, in a really bad way : 
- no information about the iso format
- no information about your hardware
- no information about your OS
- no information about your settings
- no logs
- did it work previously ? is it happening with other games ?
- even the name of the game is incomplete !!!

FWIW, i tried all games that might match "real bout" on kronos retroarch, they all worked properly.

**Comment by BroKill** [comment]
I have the same problem as the Anths2016, it freezes at Saturn screen logo.
I'm using RetroArch 1.8.1 stable and roms are cue/bin format ( they work good using Beetle core ).
I have 2 bios in the system/kronos directory, saturn_bios.bin and stvbios.zip
My hardware is i7 4790k @4.5ghz, GTX 770 2gb ram, 16 gb DDR3, roms are stored on a SSD 1tb.
Running Win10 x64.
It freezes with every video driver ( all gl, vulkan and d3d11 ).
The only version of the core that works on my machine is 1.5.0.

Hope you guys will help me to run last Kronos core version.
Thanks

**Comment by FCare** [comment]
Are you loading the game using directly the bin file or are you using the cue file? Can you try loading the bin file directly? can you share the cue file?

**Comment by BroKill** [comment]
Ok, I will try...

Edit:
downloaded last version, 2.0...same result, it freezes at Saturn screen logo.
Was wrong about roms format, they are cue/iso + wave tracks.
Tried to load a game from iso file but have no luck.
Cue files are good, nothing wrong I think, here an example : 

Shinobi X 

FILE "Track.iso" BINARY
    TRACK 01 MODE1/2048
              INDEX 01 00:00:00
FILE "Track02.wav" WAVE
   TRACK 02 AUDIO
       PREGAP 00:02:00
       INDEX 01 00:00:00
FILE "Track03.wav" WAVE
   TRACK 03 AUDIO
      INDEX 01 00:00:00

**Comment by BroKill** [comment]
@FCare, 
 
I edited previous msg with cue file example.

**Comment by barbudreadmon** [comment]
> Was wrong about roms format, they are cue/iso + wave tracks.

I'm not sure this format is properly supported, could you try converting it to cue/bin using cdmage ?

- Get [CDMage 1.02.1](https://www.videohelp.com/software/CDMage) (freeware & no ads)
- File > Open > select your iso (NB : for multi-track, select the .cue file, not the .iso file)
- File > Save As > write the name of your new file
- Make sure you select MODE1/2352 in the second drop-down
- Press OK, wait for the process to finish (a few seconds on my computer)

**Comment by BroKill** [comment]
Ok, I will try the conversion but with core version 1.5.0 everything is ok with the exception of the SV-T games, always an error msg related to the rom...they work good with MAME core.
Will let you know...

**Comment by Anths2016** [comment]
Now you're going to do a lot of laps for nothing.

**Comment by Anths2016** [comment]
I have BIN + CUE. But then it worked before, now it didn't. Isn't this enough?

**Comment by BroKill** [comment]
No luck, same problem, freezes at Saturn screen logo.
I tried to load the .bin but RetroArch doesn't list Kronos as a core that can loads .bin files.
Tried also ST-V games ( Motor Raid Twin and Golden Axe Duel, they work good with MAME core ) and it doesn' t load the games but it loads the Saturn bios and then it freezes.

**Comment by BroKill** [comment]
Fortunately I have a backup of the 1.5.0 that It works with exception of ST-V games.
If you guys need more infos let me know.
For now thanks!

**Comment by FCare** [comment]
Kronos 1.5 was only looking first bin file exposed in cue file. So there was no issue with wave files but sounds were missing. Do you have in the directory the iso file and the wav files? If you do not have the wav files, try to remove the corresponding wav entries in the cue file and try again. Kronos is exepecting all files listed in the cue to be present at the right place.

**Comment by BroKill** [comment]
Version 1.5 is good here and I have all wav files in the same directory of the cue and iso files.
Tried the conversion in bin and have had no luck because last version freezes at Saturn screen logo and last version can't load bin files, at least here using RetroArch 1.8.1...thanks anyway!

**Comment by FCare** [comment]
Are you able to share the full image for debug?

**Comment by BroKill** [comment]
The full image of the rom?
I can link you where I got it if you want, can't do an upload right now but I repeat, the v1.5.0 has no problem with those roms.

**Comment by FCare** [comment]
A link shall be ok

**Comment by BroKill** [comment]
I see you are French and the site where I got the Saturn roms speak your lang, maybe you already know it.
Can you confirm I can share a link for download? No break rules?

**Comment by FCare** [comment]
Send it here

**Comment by BroKill** [comment]
Ok...will do.

**Comment by BroKill** [comment]
Sent it, check your email.

**Comment by FCare** [comment]
Ok. Thx

**Comment by BroKill** [comment]
I forgot to tell you if you get ape audio file you need to convert those files in wave format using something like foobar2000...I did that with some roms because the Saturn system doesn't load ape file format.

**Comment by barbudreadmon** [comment]
I'll double check kronos libretro on windows tomorrow. Last time i tried it was working properly but maybe there is some kind of regression (linux is fine).

**Comment by FCare** [comment]
standalone version is working fine with this iso. Which version did you used? 1.7.0 or you compiled your port directly from source?

**Comment by Anths2016** [comment]
Are you the programmer? It is not possible to ask such a question, the standalone version dates back to several months ago, the one for Retroarch is recently updated.

**Comment by FCare** [comment]
I am the programmer of the standalone version, a new one is expected in the next days, a major version :-). So you used a core from the retro arch build system, so we can exclude a potential bug that would have been already fixed.
@barbudreadmon If you want the link for the rom just ask me.

**Comment by BroKill** [comment]
I'm using the RetroArch core v2.0 but versions after 1.5 don't work on my system.
Happy New Year!!!

**Comment by FCare** [comment]
@Anths2016 just for info all the improvements of 2.0.1 version are already available on retroarch core. It is the same team working on both standalone and retroarch port. Standalone is not updated too often to be sure to get the better reliabilty at a time, without regressions. Instead of complaining, you should better compile a wip version or join the discord channel...

**Comment by BroKill** [comment]
I'm not a programmer...I am good to bypass something using hex editor but not good in compiler...maybe will join that channel for understanding more than what I know!

**Comment by barbudreadmon** [comment]
@BroKill it appears i broke win64 when trying to fix win32 a few weeks ago, a fix will be available later today.

I can't reproduce the stv issue, all stv games i tried are loading for me, on both linux & windows, could you post your logs ?

**Comment by BroKill** [comment]
I will post later the log because I'm not at home right now.
Could you please tell me how to generate a log? Problem is it freezes when I load ST-V games so dunno if the log will be generated...I need to kill the RA process when it freezes.
Enlight me please...thanks.

**Comment by BroKill** [comment]
I tried also different stvbios.zip, same result...maybe you can send me yours.
What kind of rom format you are using for ST-V games? I'm using MAME versions...

**Comment by barbudreadmon** [comment]
https://docs.libretro.com/guides/generating-retroarch-logs/

MAME is the format expected, i think it's not seeing your romset, the possible reasons : 
- wrong extension ? only `zip` is supported, not `7z`
- a "bad path" ? try to keep the path short with no special characters or spaces
- a bad romset ? use latest mame romsets

**Comment by barbudreadmon** [comment]
@BroKill the fixed kronos core should be available from the libretro buildbot

**Comment by BroKill** [comment]
@barbudreadmon,
will try later and I will let you know.
Thanks!

**Comment by BroKill** [comment]
@barbudreadmon,
your fixed Kronos works good now with Saturn games but I still have problems with ST-V games, cartridge errors and no input ( it doesn't work gamepad/keyboard/mouse control and no RA menu, it needs to be killed )
In the link below there's the logs so you can check the issue :
[retroarch.log](https://github.com/FCare/Kronos/files/4017545/retroarch.log)

**Comment by Anths2016** [comment]
Yes !! Now works!! 
P.S. But how can I launch ST-V games on Retroarch?
P.P.S. Please fix Tecmo world cup '98!!

**Comment by barbudreadmon** [comment]
@BroKill golden axe the duel is known for having input issues (see https://github.com/FCare/Kronos/issues/676)

@Anths2016 same for tecmo world cup 98 (see https://github.com/FCare/Kronos/issues/440)

**Comment by BroKill** [comment]
Ok, thanks.
Could you please tell me the ST-V games that working?
Is there a compatibility list for Kronos ST-V games?

Another thing,
is there a way to swap disks with Kronos core? I need this feature for Panzer Dragoon Saga.
Thanks again!

**Comment by barbudreadmon** [comment]
Sorry i don't have a list, i think about half of them work atm, i remember playing radiant silvergun, die hard and cotton without major issues.

I'll look into the swap disks stuff this week-end, iirc i didn't implement it.

**Comment by zkvsky** [comment]
@BroKill PDS doesn't need disk swap, you just save as it says, load the next disc and it will allow you to load that save. I'm playing it currently

**Comment by BroKill** [comment]
Ok...hope you will be able to add swap disks in Kronos.

**Comment by BroKill** [comment]
@barolo,
good news, will try this tomorrow, thanks for the heads up!
I asked this feature also because it's a game with 4 disks and right now I added to my Saturn playlist only the .m3u file I created ( I load it using the Beetle core ) to keep things neat, lol.

**Comment by barbudreadmon** [comment]
@BroKill i figured out the issue affecting inputs in several stv games, it seems there was a big misunderstanding on how saturn/st-v actually handle inputs, it should be fixed in the latest version from the libretro buildbot

**Comment by BroKill** [comment]
@barbudreadmon,
great news, you are doing a nice job...thank you!
So, new fixed version is already available?

EDIT:
downloaded last core version, tested it and it works Golden Axe Duel but is a bit slow. 
RA shows 60 FPS but it's more slower than MAME emulation.
Can you fix this?

**Comment by BroKill** [comment]
Tested Virtua Fighter Kids and it's ok but sound volume is too low and there's no option to maxed it out in the cabinet settings.
@barbudreadmon, can you help me to fix the sound volume?

**Comment by BroKill** [comment]
Another game tested is Tecmo World Cup '98...black screen after SEGA System Checking.
This one needs to be fixed too.

**Comment by BroKill** [comment]
In these days I will test every ST-V games around the web and I will post a compatibility list for the Kronos core.
I think it's useful for both core developers and players only.

**Comment by barbudreadmon** [comment]
@BroKill 
For `twcup98`, the issue is already known.
For `vfkids`, there might be some hidden setting in the cabinet, i'll investigate, for now you can try using volume gain in retroarch's audio settings.
For `gaxetheduel`, the speed doesn't seem right indeed, and it's probably not a performance issue, it'll need further investigation

Thanks for the reports :)

**Comment by BroKill** [comment]
Thanks to you @barbudreadmon
