### ISSUE TITLE
[Mass Destruction] Lignes autour du radar in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#717]
![massdestruction](https://user-images.githubusercontent.com/12481242/71549125-8b89b300-29b8-11ea-9113-51a3efddba38.PNG)

savestate :

[T-18007G_000.zip](https://github.com/FCare/Kronos/files/4007423/T-18007G_000.zip)

**Comment by FCare** [comment]
Probleme de window. Le NBG1 sert a afficher le radar. La premiere et la derniere ligne semble avoir un soucis.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 29/12/2019
