### ISSUE TITLE
[Sega rally] NBG2 en grande partie manquant

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#722]
En WIP du 30/12, le HUD n'est plus affiché sur le NBG2 sur les 2 noyaux, mise à part le 3ème temps. Problème apparu en WIP du 17/12.

![image](https://user-images.githubusercontent.com/7624262/71600330-be65af80-2b4e-11ea-90a7-48d4a2fff062.png)

Affichage correct :
![image](https://user-images.githubusercontent.com/7624262/71600348-cde4f880-2b4e-11ea-9791-b061cbcd73ce.png)

Le NBG2 utilise une window et l'affichage est à l'extérieur :
![image](https://user-images.githubusercontent.com/7624262/71600524-9dea2500-2b4f-11ea-8cd3-9bc2d3b3441a.png)

Testé avec le CD US Sega rally championship plus.

**Comment by fafling** [comment]
Save state :
[sega_rally_debut_course.zip](https://github.com/FCare/Kronos/files/4011006/sega_rally_debut_course.zip)

**Comment by FCare** [comment]
Verifié fixé le 12/01/2020
