### ISSUE TITLE
[Krazy Ivan] User clipping de la carte incorrect en noyau Compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#723]
En WIP du 30/12, en noyau OpenGL uniquement, la carte déborde des lines qui l'entoure en bas et à droite.
![image](https://user-images.githubusercontent.com/7624262/71602256-b6f6d400-2b57-11ea-8bd7-f82db02fca13.png)

Il s'agit d'un distorted sprite limité par un user clipping.

Testé avec le CD PAL.

**Comment by fafling** [comment]
Corrigé en v2.0.1 publique.

**Comment by fafling** [comment]
De retour mais cette fois en noyau CS seulement, depuis la WIP du 02/04.

**Comment by BenjaminSiskoo** [comment]
Toujours présent en CS avec kronos wip 2.14

![krazyivan](https://user-images.githubusercontent.com/12481242/99327514-61640c80-287a-11eb-8dea-bbf2ad653650.PNG)

**Comment by BenjaminSiskoo** [comment]
Kronos 2.1.5 du 05.01.2021 : même problème

**Comment by BenjaminSiskoo** [comment]
Kronos 2.1.5 du 09.09.2021 : même problème

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 13.12.2021 : même problème
