### ISSUE TITLE
[Code R] Missing Character and transparencie is not correct...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#724]
Kronos 2.0.0

Vidéo YouTube : 
https://www.youtube.com/watch?v=DxRTcncT_b4

![coder](https://user-images.githubusercontent.com/12481242/71623078-5066ca00-2bda-11ea-99e1-a9cb1b0c3e98.PNG)

Save states :

[coder.zip](https://github.com/FCare/Kronos/files/4012761/coder.zip)

**Comment by fafling** [comment]
Le personnage est dessiné par le VDP1, on voit les commandes de dessin qui ne sont pas rendues par Kronos :
![image](https://user-images.githubusercontent.com/7624262/71702611-c3d22c80-2dd0-11ea-93c3-451ae7b7bf1b.png)

D'après les coordonnées de clipping, le VDP1 est en haute résolution double interlaced :
![image](https://user-images.githubusercontent.com/7624262/71702635-efedad80-2dd0-11ea-8ffe-de919e60436c.png)

Le polygone semi transparent de la fenêtre de dialogue dans la video est en fait une mesh haute résolution lissée par la sortie analogique de la console. L'affichage de Kronos est correct aux irrégularité près de la mesh dues à un zoom non entier. On peut obtenir le même effet que la video en passant les mesh en mode improved.

**Comment by BenjaminSiskoo** [comment]
Amélioration avec la wip du 13/01/2019, le perso est affiché. Il manque juste la transparence.

![coder](https://user-images.githubusercontent.com/12481242/72303100-79706b80-366c-11ea-80ae-a58face2a26a.PNG)

**Comment by fafling** [comment]
@BenjaminSiskoo la fenêtre de dialogue c'est une trame, l'affichage de  Kronos est correct.

**Comment by barbudreadmon** [comment]
@fafling pas certain que la fenêtre soit bonne, il est possible que des patterns de mesh soient erronés sur kronos (j'ai ce doute sur plusieurs jeux, genre sur l'ombre de sonic dans sonic jam, sans tester sur hardware original difficile de confirmer), à titre comparatif voilà à quoi cet écran ressemble sur mednafen/beetle : 
![Code R (Japan)-200114-104200](https://user-images.githubusercontent.com/10391265/72332825-03472580-36bb-11ea-858b-62896a60d624.png)

Ou bien le pattern est un réglage dans le jeu, vu que les dialogues sont en japonais je ne suis sûr de rien.

**Comment by BenjaminSiskoo** [comment]
Dans ce cas là elle semble incorrecte, j'ai trouvé une autre vidéo : https://www.youtube.com/watch?v=H4GNnXRw7gU

**Comment by fafling** [comment]
@BenjaminSiskoo L'affichage de Mednafen est encore moins correct que celui de Kronos. L'affichage de la console est un damier régulier de pixels noirs et de pixels transparents. Il est lissé horizontalement par la sortie analogique sur une télé cathodique, qui n'a pas de pixels fixes contrairement aux écrans digitaux modernes. De plus, la sortie video de la console donne des pixels qui ne sont pas carrés : de mémoire en NTSC, le ratio des pixels est d'environ 0,9 en résolution horizontale 320/640 et 0,83 en 352/704.

**Comment by BenjaminSiskoo** [comment]
Je ferme le br pour toi ?

**Comment by fafling** [comment]
Oui. Le problème des trames n'est pas spécifique à ce jeu. Si tu veux, tu peux ouvrir un br général sur l'affichage irrégulier des trames.
Derrière ça, il y a la façon dont Kronos zoome l'affichage : est-ce qu'il doit utiliser un zoom entier, ou faire de l'interpolation ? Est-ce qu'il doit respecter l'aspect ratio des pixels tel qu'il est sur la sortie video de la console, ou bien les afficher carrés ?

**Comment by BenjaminSiskoo** [comment]
Tu pourrais faire le BR vu que la partie technique parlera plus à François que moi avec c'est incorrecte :)

**Comment by FCare** [comment]
Aujourd'hui, les shaders utilises bien un cadrillage par pixel. Les effets
que vous observez sont du au reechantillongage due au rescale. Le seul
moyen serait d'utiliser un scale par entier.

Cet effet s'appelle un moiré...

Si vous devez faire un br, c'est celui de demander un resize en entier.
