### ISSUE TITLE
[ST-V][Golden Axe The Duel] Déplacements lents des personnages

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#731]
- romset `gaxeduel` sur ST-V
- libretro sous linux avec i7 2600k et GTX 960

Les déplacements des combattants sont très lents (le reste a l'air de fonctionner à la bonne vitesse), à en juger par https://www.youtube.com/watch?v=ZGRA_z29SlQ ce n'est pas normal.
NB : MAME l’exécute à la bonne vitesse sans utiliser de workarounds particuliers au niveau de l'initialisation de la borne.

**Comment by fafling** [comment]
En v2.0.1 publique, la vitesse de Golden axe version STV est 2 fois plus lente que la version Saturn jap :
- L'intro dure 55 secondes en STV contre 27 en Saturn.
- Le combat de demo dure 40 secondes en STV contre 20 en Saturn.

Les tests sont faits avec les options par défaut, le framerate est resté à 60/60 en permanence.
La vitesse de la version Saturn sous Kronos est conforme à celle du jeu sur la console.

**Comment by barbudreadmon** [comment]
Comme mentionné dans https://github.com/FCare/Kronos/issues/819, le bug a été résolu, j'imagine que c'est lié à un des fix du scu ou du sh2, si j'ai le temps j'essaierai de trouver le commit exact, en attendant je ferme :)

**Comment by barbudreadmon** [comment]
Bug corrigé par https://github.com/FCare/Kronos/commit/cfca0b8cca2d364c99296c4f4f556a6744bca7cf
