### ISSUE TITLE
[Metal slug] Sprites incorrects intermittents lors de l'affichage du score

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#732]
En v2.0.1 publique, dans les 2 noyaux, l'affichage du score en fin de niveau est corrompu par intermittence : des sprites affichent temporairement une autre texture. Les textures affichée à ce moment-là par l'écran debug du VDP1 sont correctes.
![image](https://user-images.githubusercontent.com/7624262/71765967-de082980-2efa-11ea-9003-7377e04d0dea.png)

Problème déjà présent en v1.7.0 publique.

Testé avec le CD jap.

Save state :
[metal_slug_fin_niveau_1.zip](https://github.com/FCare/Kronos/files/4021923/metal_slug_fin_niveau_1.zip)

**Comment by fafling** [comment]
Le jeu nécessite une cartouche RAM pour fonctionner. Le problème se produit pour les 2 types de cartouche, la 8 mbit et la 32.
Le save state a été enregistré avec la cartouche 32 mbit.

**Comment by FCare** [comment]
Fixed 23/12/20 by cf814d3b6662373484c64d7b10c59ff15e909cf3

**Comment by fafling** [comment]
Problème réglé.
Par contre le fix ne correspond pas au comportement de la console : possible que des jeux comptent sur le temps d'exécution des commandes et continuent de mettre à jour la vram après démarrage du dessin, mais c'est la mise à jour elle-même qui ralentit l'opération du VDP1 (elle l'interrompt momentanément), pas l'erase du framebuffer d'affichage. Celui-ci se déroule en parallèle sur un autre bus (il y en a un par framebuffer) et n'a pas d'impact sur la vitesse de dessin.
La p.19 du mode d'emploi du VDP1 décrit l'interruption du VDP1 par l'accès des CPU à la VRAM. Même chose page suivante pour les accès au framebuffer de dessin. Et en plus ça ralentit le CPU aussi qui perd quelque cycles en attendant qu'on lui donne la priorité.
