### ISSUE TITLE
[Winter Heat] graphismes tronqués en résolution non-originale

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#735]
- Winter Heat (USA)
- Port libretro
- Linux x64
- i7-2600k + GTX960
- cd image redump zippée
- testé en config standard avec réso 480p, 720p, 1080p, et native. pas de soucis en réso originale.

![Winter Heat (USA)-200107-092941](https://user-images.githubusercontent.com/10391265/71881674-04180e80-3133-11ea-9041-36d8d8f06ef8.png)

Je n'ai pas de debugger en version libretro pour voir quelle "couche" pose soucis. @fafling pourra certainement donner plus d'information.

**Comment by FCare** [comment]
C'est un probleme qur l'upscale des windows

**Comment by FCare** [comment]
Fixé le 11/01/2020

**Comment by barbudreadmon** [comment]
Je confirme (https://github.com/FCare/Kronos/commit/2b4ef0d7c897cb5cab2f6531ec50a392389329d6)
