### ISSUE TITLE
[Sega touring car championship] Fort ralentissements de l'écran titre après la demo en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#736]
En v2.0.1 publique, en noyau compute shader :
- Attendre à l'écran titre (tourne à 65 fps chez moi avec faible utilisation du GPU) et laisser la demo démarrer.
- Interrompre la demo en appuyant sur start.
L'écran titre qui s'affiche la 2ème fois tourne chez moi à 10 fps avec le GPU quasiment à 100%, alors qu'il n'y a pas de différence visible avec l'écran titre initial.

Si on essaie d'afficher l'écran debug VDP1 à ce moment-là, l'émulateur freeze. Pas de message dans debugView, mais dans le gestionnaire des tâches, on voit la mémoire utilisée par Kronos augmenter sans arrêt.

En OpenGL, il y a un ralentissement aussi mais nettement moins marqué (60 fps pour le 1er écran titre, 45 fps pour le 2ème) et l'affichage de l'écran debug VDP1 au 2ème écran titre ne bloque pas Kronos.

Testé avec le CD US.

**Comment by FCare** [comment]
Sous linux ca semble nickel chez moi. tu peux refaire un test?

**Comment by FCare** [comment]
semble venir de la version windows

**Comment by fafling** [comment]
Bon, ben impossible de reproduire le problème que j'avais en v2.0.1 publique…
