### ISSUE TITLE
[Contrôles] Jeux avec des problèmes de contrôles...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#738]
Voici une liste de jeu Saturn avec des problèmes de contrôleurs : 

<s>Batsugun : presser Start sur l'écran press start screen ne fonctionne pas.</s> 08.09.2021
<s>Lupin The 3rd - The Master File : les boutons ne fonctionnent pas.</s> kronos20231206_3006f2d
Pro Majhong Kiwame S : le bouton start (et peut être les autres) ne fonctionnent pas.
<s>Shangai Triple Threat :  Le déplacement dans le jeu de la main est haché voir très difficile.</s> 08.09.2021
<s>Shockwave Assault : les boutons ne fonctionnent pas.</s> kronos20231206_3006f2d
<s>Thunderhawk - Firestorm :  les contrôles ne fonctionnent pas sous windows.</s> kronos20231206_3006f2d

Voici une liste de jeu STV avec les problèmes de contrôleurs :

Final Arch : les boutons ne fonctionnent pas.
Winter Heat : les boutons ne fonctionnent pas.

**Comment by BenjaminSiskoo** [comment]
Problème avec la manette PS3  Dualshock 2 :
- Lupin The 3rd
- Shockwave Assault
- Thunderhawk Firestorm.

**Comment by barbudreadmon** [comment]
Sur STV, finlarch, winterheat et suikoenb (même si pas mentionné) fixés par https://github.com/FCare/Kronos/commit/441f83e941d39c7588d537cb95bfed5d577b3d33

**Comment by BenjaminSiskoo** [comment]
Kronos 2.3.1

3D Lemmings : ne fonctionne pas avec la manette Dual Shock 2 (SCPH-10010). Pas de soucis avec le clavier

**Comment by BenjaminSiskoo** [comment]
Kronos Wip 01.06.2021

Father Chrismas : ne fonctionne pas avec la manette Dual Shock 2 (SCPH-10010)

**Comment by BenjaminSiskoo** [comment]
Kronos Wip 01.06.2021

Heisei Tensai Bakabon - Susume! Bakabons (Japan) : ne fonctionne pas avec la manette Dual Shock 2 (SCPH-10010)

**Comment by fafling** [comment]
Pour Shockwave Assault, la situation est la même que pour X-Japan #518 et World heroes perfect #455 : les boutons ne répondent pas avec une manette USB, mais ils répondent s'ils sont mappés sur des touches du clavier. Ce problème existait déjà en v1.6.0, mais pas en v1.5.0.

**Comment by fafling** [comment]
Dans Bug! (US), même problème que dans les jeux ci-dessus uniquement pendant la video d'intro (le jeu fonctionne sans problème à partir de l'écran titre).
Dans ce jeu, ma manette USB se comporte dans Kronos exactement comme le fait la manette 3d en mode digital sur la console : pas de réponse pendant l'intro et ça marche à partir de l'écran titre.

**Comment by fafling** [comment]
Sur la console, Shockwave Assault (US) et X-Japan ne répondent pas non plus avec la manette 3d en mode digital, par contre World heroes perfect fonctionne sans problème.

**Comment by BenjaminSiskoo** [comment]
Corrigé kronos20231216_0a26fe6
