### ISSUE TITLE
Trames en damier irrégulières

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#740]
Actuellement Kronos affiche de façon irrégulière les trames de pixels en damier. Ces motifs sont dessinés la plupart du temps avec le mesh mode du VDP1 (projecteurs dans le 1er niveau de Megaman X4, fenêtre de dialogue dans Code R...), mais ils peuvent aussi être en dur dans certaines textures (ombres dessinées par le VDP1 dans Sonic 3D, logo sur le NBG2 en début de combat dans Fighting vipers…).

Les irrégularités sont plus visibles quand Kronos s'affiche dans une fenêtre de petite taille. Elles sont peu visible en plein écran. Elles sont dues à un zoom non entier au plus proche voisin sur les pixels affichés par la console.

Il faudrait au moins une option permettant d'ajuster la taille de l'affichage fenêtré à un multiple entier de la résolution de la console.

**Comment by fafling** [comment]
Voir #724 pour la discussion sur ce problème.

**Comment by fafling** [comment]
En WIP du 31/03, les trames sont régulières dans ce qui correspond à la taille native pour un jeu comme Steeldom (haute résolution horizontale), par contre les ratios de zoom supérieurs montrent des irrégularités visibles sur un jeu comme Steeldom, ici sur l'écran de pause :
![image](https://user-images.githubusercontent.com/7624262/78086254-aad01c00-73bd-11ea-90c3-6bd31494cfdf.png)

Sur Sonic 3D (résolution standard), on voit des irrégularités dans les trames sur tous les ratios, ici le x2 :
![image](https://user-images.githubusercontent.com/7624262/78086530-8e80af00-73be-11ea-97fe-f484de011762.png)

**Comment by fafling** [comment]
Fixé pour Sonic 3D, les trames sont régulières à tous les ratios de zoom entiers.

Dans Steeldom, l'image est aplatie. Comme c'est un jeu high res progessif, il faut prendre en compte un upscale vertical x2 automatique de l'image :
![image](https://user-images.githubusercontent.com/7624262/78131581-9884cb00-741b-11ea-928a-31565ba82671.png)

En partant d'un kronos.ini vide, cela ne se produit que si on augmente la taille par rapport à la fenêtre par défaut, qui doit être trop petite pour afficher le ratio de zoom x1 en high res.

Est-ce qu'il est possible d'augmenter la taille par défaut de la fenêtre de Kronos pour afficher un zoom entier x1 sur la résolution max de la console, soit 704x512 ?

**Comment by FCare** [comment]
C'est fixé maintenant
