### ISSUE TITLE
[Defcon 5] CS - Problème graphique...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#743]
Wip du 15/01/2020

![defcon51](https://user-images.githubusercontent.com/12481242/72430897-c307a600-3793-11ea-9be3-1ba4ceae9e6b.PNG)

![defonc5](https://user-images.githubusercontent.com/12481242/72430898-c3a03c80-3793-11ea-8522-905f96f088a0.PNG)

Savestate : 
[defcon5.zip](https://github.com/FCare/Kronos/files/4064695/defcon5.zip)

**Comment by barbudreadmon** [comment]
Régression (tout au moins pour le logo) apparue dans https://github.com/FCare/Kronos/commit/3e5263d4ffd3a11790125e1383e0193e17f1091c

**Comment by BenjaminSiskoo** [comment]
Corrigé le 16/03/2020
