### ISSUE TITLE
Kronos peut lire un BIN+CUE dans une archive ZIP ?

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#744]
Bonsoir, tout est dans le titre.

Je me suis aperçus qu'il recherche également les fichiers ZIP mais lorsque j'essaye de charger une archive avec dedans un BIN+CUE l'emulateur crash.

Est ce un bug de pouvoir charger une archive ou y a t il un truc à savoir pour rendre compatible le chargement d'une archive ?

**Comment by barbudreadmon** [comment]
> ISO+CUE

Uniquement bin+cue dans un zip.

**Comment by CloudFR** [comment]
Ca crash chez moi

**Comment by FCare** [comment]
Est ce que l'ensemble des fichiers listés dans le .cue sont bien a la bonne
place dans le zip?

**Comment by CloudFR** [comment]
Oui
Je ne comprends pas du tout pourquoi, j'ai essayé avec 7zip plusieurs niveau de compression et c'est toujours pareil l’émulateur crash.

**Comment by CloudFR** [comment]
Bon effectivement ça fonctionne, même avec des cds + cdd. J'ai testé ça fonctionne sauf avec SFIII patché, pourquoi je l'ignore...

**Comment by barbudreadmon** [comment]
> J'ai testé ça fonctionne sauf avec SFIII patché, pourquoi je l'ignore...

Aucun problème de mon côté avec la trad officieuse de sf3 (en bin+cue dans un zip), à la limite passe sur notre discord, on sera peut-être en mesure de t'aider.
