### ISSUE TITLE
[Grandia] RBG0 incorrect en noyau OpenGL

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#746]
Dans la WIP du 15/01 et en v2.0.1 publique, en noyau OpenGL uniquement, le RBG0 ne s'affiche pas au 2ème écran titre qui suit la 1ère séquence de dialogue, puis il est fixe pendant le survol de la 1ère ville et disparaît même partiellement ensuite.

Au 2ème écran titre (à droite l'affichage correct en compute shader) :
![image](https://user-images.githubusercontent.com/7624262/72664635-88ef0c00-3a00-11ea-838f-2d7402f5432c.png)

Pendant le survol de la ville :
![image](https://user-images.githubusercontent.com/7624262/72664663-d0759800-3a00-11ea-8b96-08e6b9e0e62f.png)

Save state au 2ème écran titre (le survol est juste après) :
[grandia_ecran_titre_2.zip](https://github.com/FCare/Kronos/files/4080742/grandia_ecran_titre_2.zip)

Le problème d'affichage se poursuit in game, mais il y a une partie de la ville où le RBG0 s'affiche correctement, vers le port. J'ai fait un save state dans cette partie juste devant la porte qui mène à la zone où l'affichage bugge :
[grandia_ville_limite_bug_RBG0.zip](https://github.com/FCare/Kronos/files/4080744/grandia_ville_limite_bug_RBG0.zip)

Dans l'écran debug du VDP2, je n'ai pas vu de différence entre les 2 parties de la ville.

L'affichage était correct en v1.7.0 publique. Le problème est apparu en WIP du 29/12.

Testé avec le CD jap.

**Comment by FCare** [comment]
Le fix en cause est celui la:
https://github.com/FCare/Kronos/commit/2144e966e184fb80beac4bfcf281259d31435e6d

**Comment by FCare** [comment]
Fixé le 22/01/20 par 421c59348dbaac9008eff3c57474c59bdaf4ebf7

**Comment by FCare** [comment]
Back...

**Comment by fafling** [comment]
De nouveau présent en v2.1.5 publique et dans la dernière WIP.
Le bug est revenu entre la WIP du 30/01/2020 et celle du 02/02/2020 (une dizaine de jours après le 1er correctif).
Testé avec le CD d'origine (2M) et le redump 1M.
Save state :
[grandia_survol_ville.zip](https://github.com/FCare/Kronos/files/5992065/grandia_survol_ville.zip)

**Comment by BenjaminSiskoo** [comment]
Support OpenGL supprimé
