### ISSUE TITLE
[SH2] Implémentation partielle des registres (?)

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#749]
mednafen semble avoir une implémentation beaucoup plus complète au niveau de la lecture/écriture des registres sh2, je link les fonctions ici au cas où il y aurait des choses intéressantes : 
Lecture : https://github.com/libretro/beetle-saturn-libretro/blob/master/mednafen/ss/sh7095.inc#L1446
Ecriture : https://github.com/libretro/beetle-saturn-libretro/blob/3313cc6760c14cffa9226e0cfd41debc11df8bdd/mednafen/ss/sh7095.inc#L942

**Comment by barbudreadmon** [comment]
Par curiosité, j'ai remplacé les read sh2 de kronos par https://pastebin.com/raw/XbbQK322 et testé une trentaine de jeu (principalement des jeux marqués comme non jouable dans la liste de compatibilité, ou tout au moins avec glitchs), pas trouvé d'amélioration, mais pas trouvé de régression non plus.

**Comment by BenjaminSiskoo** [comment]
Je pense qu'on peut fermer :)

**Comment by FCare** [comment]
Oui, de plus la saturn dispose de SH2 SH-7604 pas des SH-7095

Donc les registres ne doivent pas etre utilisés. L'implementation actuelle comporte bien tous les registres du SH2 SH-7604
