### ISSUE TITLE
Kronos 2.0.1 64bits chargement .img / .cdd

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#750]
Bonsoir,

La dernière version (2.0.1 en 64bits pour ma part) ne charge plus les .img / .cdd, l'émulateur crash.

L'ancienne version 1.7.0 fonctionnait pour info.

**Comment by BenjaminSiskoo** [comment]
Merci pour les  retours. Il peut prendre du temps avant correction, mais les bug reports sont très utile.

**Comment by barbudreadmon** [comment]
Je ne vois pas de changements entre la 1.7.0 et aujourd'hui sur le chargement des ccd. N'hésite pas à passer sur discord, ce sera plus simple pour trouver d'où peut venir ton problème.

**Comment by CloudFR** [comment]
Oui mais pourtant ça crash, j'ai également testé avec la version 32bits c'est la même chose.
Je repasse sur la 1.7.0 pas de soucis.

**Comment by barbudreadmon** [comment]
Ok, j'ai réussi à mettre la main sur un dump ccd saturn afin de faire des tests, effectivement il y a un soucis, certainement un effet secondaire des correctifs effectués pour les pregap des cue.

**Comment by CloudFR** [comment]
Ok très bien

**Comment by barbudreadmon** [comment]
Fixé dans https://github.com/FCare/Kronos/commit/78eeb2d979260f9850259f6c056cf4321c6a4ccc
