### ISSUE TITLE
OpenGL VS Computer shader

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#751]
Bonsoir,

Peut on faire un récap sur le nouveau noyau compute shader et ce que ça apporte ?

**Comment by BenjaminSiskoo** [comment]
Lis les documentations fournies avec l'émulateur, tu devrais trouver les réponses :)

**Comment by fafling** [comment]
Le noyau compute shader permet un dessin des polygones du VDP1 plus proche de ce que fait la console :
- Distortion des textures sans correction de perspective ni tessellation : évite des corruptions de textures (ex : Quake), ou de Gouraud shading (ex : Krazy Ivan).
- Dessin de pixels supplémentaires sur les lignes obliques sans expansion de coordonnées : supprime des trous entre polygones sans créer de discontinuités entre eux (ex : Sega rally).
- Rendu correct des effets de blending du VDP1 en plusieurs passes (ex : titre des niveaux de Powerslave/Exhumed).

Au niveau des couches RBG du VDP2, le compute shader rend possible leur dessin avec une définition supérieure à celle de la console..

**Comment by barbudreadmon** [comment]
@CloudFR As-tu joué à un émulateur PSX avec et sans PGXP ? C'est un peu la même idée. 
Il y a encore quelques soucis à résoudre mais le noyau OpenGL CS devrait devenir très supérieur au noyau OpenGL dans un futur proche, il l'est déjà dans certains cas. C'est aussi une porte ouverte vers le futur développement d'un noyau vulkan, car celui-ci est très orienté sur l'utilisation des CS.

**Comment by CloudFR** [comment]
Merci pour l'info @fafling car je n'ai pas trouvé la doc justement pour comprendre à quoi ça servait.
@barbudreadmon Non ça ne me dit rien, merci pour ton retour.
