### ISSUE TITLE
[Doom] Logo corrompu en noyau CS

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#753]
- Doom (USA)
- Port libretro
- Linux x64
- i7-2600k + GTX960
- cd image redump zippée
- avec noyau CS, le reste est par défaut

Il y a un soucis sur le logo au démarrage du jeu : 
![Doom (USA)-200123-110939](https://user-images.githubusercontent.com/10391265/72975380-020bac00-3dd1-11ea-9f36-e582d1540012.png)
La façon dont ce logo est corrompu semble complètement aléatoire (parfois on voit la silhouette d'éléments du jeu qui n'ont rien à faire là), je soupçonne un overflow ou quelque chose du genre.

**Comment by fafling** [comment]
Le problème du sol est déjà suivi dans le #470. Le logo c'est nouveau.

**Comment by barbudreadmon** [comment]
Oops, j'avais cherché vite fait mais je n'avais pas vu le ticket, j'édite le br histoire d'éviter les doublons

**Comment by fafling** [comment]
Je n'ai pas remarqué ce problème dans mes tests récents, c'est résolu, non ?

**Comment by barbudreadmon** [comment]
effectivement c'est résolu
