### ISSUE TITLE
[Interface QT] Simplification des options vidéo

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#757]
Dans l'onglet Vidéo des paramètres, il faudrait fusionner les options Noyau Vidéo et Compute Shader puisque seules 2 combinaisons de ces options sont supportées :
- Noyau Vidéo à "Interface Vidéo OpenGL" et Compute Shader à Off : correspond au noyau OpenGL.
- Noyau Vidéo à "Interface Vidéo Compute Shader" et Compute Shader à On : correspond au noyau Compute Shader.

De plus, il faudrait griser l'option Tesselation quand le noyau Compute Shader est sélectionné.

**Comment by barbudreadmon** [comment]
A ma connaissance, les 2 réglages ("noyau compute shaders" et "compute shaders") ne sont pas liés

**Comment by FCare** [comment]
pour la simplification de l'interface Qt, j'avais essayé, mais le code de l'UI est vraiement degueu... Pour implementer ce qu'on veut faire, il faudrait limite refaire l'UI au total. J'ai pas vraiement le temps et pas de solution autre que Qt pour passer sur Windows et Linux. Du coup, je botte en touche.
et quitte a redevelopper, je pense que je passerais par une gui comme ca: https://github.com/mitsuba-renderer/nanogui

**Comment by fafling** [comment]
En WIP du 07/05, les options incompatibles avec un noyau video sont cachées.
Finalement, les options noyau video et GPU RBG restent séparées.
