### ISSUE TITLE
[Sakura wars] Fenêtre incorrecte pendant la video

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#764]
En WIP du 03/02, et en v2.0.1 publique, il y a un écart à droite entre la 1ère vidéo in-game et son ombre.
![image](https://user-images.githubusercontent.com/7624262/73699466-2fffc300-46e4-11ea-8bc4-b126acc83e22.png)

Affichage correct sur la console :
![image](https://user-images.githubusercontent.com/7624262/73700918-3d1eb100-46e8-11ea-9e78-2746f4770396.png)

Le NBG1 (l'ombre) et le RBG0 (la video) utilisent la fenêtre W0, le 1er à l'extérieur, le 2ème à l'intérieur :
![image](https://user-images.githubusercontent.com/7624262/73699360-e1522900-46e3-11ea-8ceb-f9dbf0ad21b5.png)

Testé avec le CD jap.

**Comment by fafling** [comment]
En WIP du 04/04, c'est correct sur la video dans les 2 noyaux, mais pas sur la 1ère image fixe du jeu :
![image](https://user-images.githubusercontent.com/7624262/78460247-8460f800-76bf-11ea-8b78-8791db169295.png)

Il n'y a aucun écart entre l'image et son ombre sur la console.

Dans Kronos, lors que l'image apparaît avec un effet de semi-transparence progressive, l'affichage est correct. L'écart entre l'image et son ombre n'apparaît qu'a la fin de la transition.

L'ombre est toujours affichée par le NBG1, mais il n'utilise plus de fenêtre. L'image est affichée par le NBG2, qui n'utilise pas non plus de fenêtre.
![image](https://user-images.githubusercontent.com/7624262/78460430-1fa69d00-76c1-11ea-9f41-c7eb8700d28f.png)

Save state juste avant l'apparition de l'image :
[sakura_wars_1ere_image_fixe.zip](https://github.com/FCare/Kronos/files/4432466/sakura_wars_1ere_image_fixe.zip)

**Comment by fafling** [comment]
Problème toujours présent dans la dernière WIP. Nouveau save state, l'ancien ne marche plus :
[sakura_wars_1ere_image_fixe_20201117.zip](https://github.com/FCare/Kronos/files/5550703/sakura_wars_1ere_image_fixe_20201117.zip)

**Comment by BenjaminSiskoo** [comment]
Même problème Kronos 2.1.5 du 14.01.2021

**Comment by fafling** [comment]
Depuis la 3ème WIP du 15/12, qui corrige les combinaisons de fenêtres, dans les 2 noyaux, il y a de nouveau l'écart à droite entre la 1ère vidéo in-game et son ombre, alors que l'écart à droite entre la 1ère image fixe in-game et son ombre a disparu.

Peut-être un problème similaire à celui de la fenêtre des sprites dans Doom qui réapparaît en même temps, voir #665.

**Comment by fafling** [comment]
Fixé dans les 2 noyaux en WIP du 18/01/2022.
