### ISSUE TITLE
[Blazing tornado] Corruption de sprites à la sélection du perso

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#765]
En WIP du 03/02, dans les 2 noyaux, il y a des corruptions intermittentes de tous les sprites des persos à l'écran de sélection, sauf pour le perso le plus à gauche :
![image](https://user-images.githubusercontent.com/7624262/73703822-87f0f680-46f1-11ea-8107-7a42a5cff40f.png)

La corruption a un motif en zig-zag semblable à celui observé dans Earthworm Jim 2 #473 .

Problème apparu dans la 2ème WIP du 23/01, peut-être lié au fix des corruptions sur les stats de fin de niveau dans Metal slug #732 .

Testé avec le CD jap.

**Comment by barbudreadmon** [comment]
Est apparu dans https://github.com/FCare/Kronos/commit/cf814d3b6662373484c64d7b10c59ff15e909cf3
Je remarque au moins une étrangeté dans ce commit : une copie de PTMR est faite dans une nouvelle variable, mais celle-ci n'est jamais utilisée.

Des corruptions similaires affectent également golden axe the duel depuis ce commit : 
![Golden Axe - The Duel (USA)-200204-080613](https://user-images.githubusercontent.com/10391265/73722692-5f83ef00-4727-11ea-9f18-cd239c8b11fe.png)

NB : Je suis tombé sur cette info dans le code source de mednafen à propos du PTMR, au cas où çà serait utile : 
```
When vblank starts: Abort command processing, and if VBE=1, erase framebuffer just displayed according to set values.
When vblank ends: Abort framebuffer erase, swap framebuffer, and if (PTMR&2) start command processing.
See if EDSR and LOPR are modified or not when PTMR=0 and an auto framebuffer swap occurs.
FB erase params are latched at framebuffer swap time probably.
VBE=1 is persistent.```

**Comment by fafling** [comment]
"When vblank starts: Abort command processing" : pour moi, c'est faux. Rien dans la doc du VDP1 n'indique que le traitement des commandes de dessin est interrompu au vblank. Il peut être interrompu soit volontairement par le registre ENDR (p. 51), soit par un basculement de framebuffer. Le vblank erase est un cas particulier du processus d'erase/write, et il peut donc être traité sur le framebuffer d'affichage en parallèle du processus de dessin sur l'autre framebuffer.

**Comment by fafling** [comment]
Ne se produit plus sur les WIP du 22-23/03.
