### ISSUE TITLE
[VDP1_line branch] régression

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#768]
Reset de l'ini, OpenGL uniquement sans filtre.

artefact sur le personnage 

![earthwormjim](https://user-images.githubusercontent.com/12481242/74362461-06702700-4dc9-11ea-8e8d-004ddb7710ad.PNG)

Savestate :  
[earthwormjim.zip](https://github.com/FCare/Kronos/files/4193987/earthwormjim.zip)

![earth](https://user-images.githubusercontent.com/12481242/74362643-564eee00-4dc9-11ea-85ce-6f54f76e7355.PNG)

**Comment by BenjaminSiskoo** [comment]
Reset de l'ini, OpenGL uniquement sans filtre.

artefact sur le personnage 

![earthwormjim](https://user-images.githubusercontent.com/12481242/74362461-06702700-4dc9-11ea-8e8d-004ddb7710ad.PNG)

Savestate :  
[earthwormjim.zip](https://github.com/FCare/Kronos/files/4193987/earthwormjim.zip)

![earth](https://user-images.githubusercontent.com/12481242/74362643-564eee00-4dc9-11ea-85ce-6f54f76e7355.PNG)

**Comment by BenjaminSiskoo** [comment]
Akumajou Dracula X

petite ligne qui scintille en haut à gauche (sous les FPS)

![akumajou](https://user-images.githubusercontent.com/12481242/74388963-173a9000-4dfd-11ea-8237-718c08cb86db.PNG)

Save state : 
[akumajou.zip](https://github.com/FCare/Kronos/files/4195846/akumajou.zip)

**Comment by BenjaminSiskoo** [comment]
College slam : 

Les personnages sont incomplets (juste la tête).

![collegeslam](https://user-images.githubusercontent.com/12481242/74389384-4b628080-4dfe-11ea-97ef-35c92c7e20e6.PNG)


Save state

[collegeslam.zip](https://github.com/FCare/Kronos/files/4195870/collegeslam.zip)

**Comment by BenjaminSiskoo** [comment]
Fantastep : 

Gros problème 'affichage in game : 

![fantastep](https://user-images.githubusercontent.com/12481242/74389684-4a7e1e80-4dff-11ea-8afd-8521c3f11d1c.PNG)

Save state : 

[fantastep.zip](https://github.com/FCare/Kronos/files/4195886/fantastep.zip)

**Comment by BenjaminSiskoo** [comment]
Scorcher :  

Ne fonctionne plus in game 

Savestate : 
[scorcher.zip](https://github.com/FCare/Kronos/files/4195939/scorcher.zip)

**Comment by fafling** [comment]
Crash de Deep fear après le logo Sega.

**Comment by fafling** [comment]
Problème d'erase dans Sonic R (J) :
![image](https://user-images.githubusercontent.com/7624262/74392630-1ce9a300-4e08-11ea-8f5c-4096f46cfb6f.png)
Je pense qu'il utilise le vblank erase vu qu'il n'efface que le bas de l'écran par un polygone.

**Comment by FCare** [comment]
Fantastep et Sonic R ont egalement le pb sur la 2.0.2 officielle...

**Comment by fafling** [comment]
Je ne reproduis pas les problèmes d'erase de ces 2 jeux en v2.0.2 publique. Chez moi, ils apparaissent en WIP du 05/02.
Fanstastep a des problèmes de polygones manquants qui datent d'avant.
