### ISSUE TITLE
[CS] Sycnhroniser les jeux avec OpenGL...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#769]
Les jeux sont corrigés en OpenGL mais pas sous CS : 

Emulation Saturn : Fuusui Sensei - Feng-Shui Master : Correction de l'affichage de la fenêtre in game. Il reste des soucis sur le menu de sélection du nom (François Care). 2.0.2
Emulation Saturn : Hang-On GP '95 : Correction de la fenêtre tronqué in game, il reste un soucis sur l'écran d'avant (François Care). 2.0.2
Emulation Saturn : Highway 2000 : Correction de la fenêtre tronqué in game (François Care). 2.0.2
Emulation Saturn : Pebble Beach Golf Links : Correction des vidéos d'introduction manquantes, correction de l'affichage de la vidéo avec le prof (François Care). 2.0.2
Emulation Saturn : Casper : Correction des artefacts sur les écrans de transitions (François Care). 2.0.2
Emulation Saturn : Dark Savior : Correction de l'écran noir sur le dialogue in game (François Care). 2.0.2
Emulation Saturn : Doom : Amélioration du sol (François Care). 2.0.2

**Comment by ner00** [comment]
> Emulation Saturn : Dark Savior : Correction de l'écran noir sur le dialogue in game (François Care). 2.0.2

This issue still happens with OpenGL on v2.0.2
