### ISSUE TITLE
[Policenauts] Patched version does not boot from CHD

### ISSUE THREAD

**Issue by ner00** [FCare/Kronos#777]
**Description**
This is a very specific issue, and deals with modified disc image + CHD, nevertheless it could mean an improvement for the emulator down the line. As you are aware, Policenauts is an exclusive Japanese game, not officially published or translated in the West. There is a decent unofficial translation for the Saturn version and works quite well, in fact Kronos can perfectly boot the image when patched, just doesn't handle it when converted to CHD format; worthy of note that only Beetle Saturn was able to boot the CHD compressed rom, Yabause and YabaSanshiro also failed with the CHD in the same way.

The patch consists of extracting session 1 of the discs resulting in:

- Track 1: an ISO with the user data;
- Track 2: a WAV with 2 audio tracks (CUE spec);

To them are applied some xdelta diff files for patching. Provided along the patch are ready to use CUE files for each patched ISO/WAV pair. Once patched, the game runs fine, but as mentioned previously Kronos fails to boot if this is converted to CHD. Kronos has no issue with the original 2 track binary image converted to CHD, only has issue booting the the ISO/WAV when converted to CHD.

I have found a workaround of sorts, seems to work fine at the moment but was wondering if Kronos could be made to not need the workaround (as Beetle), because I don't think it should have to since it has no issue with the WAV/ISO/CUE image from which the CHD is derived. Anyway, the workaround is simply to mount the (WAV/ISO) CUE with Daemon Tools and then use ImgBurn to create a new BIN/CUE image of that virtual disc, and finally convert the resulting image to CHD, then it works fine.

**What's the full name of the game (including region) ?**
Policenauts (Japan) - patched with unofficial English translation v1.0.1 (http://policenauts.net/english/patches.html)

**What's your frontend ? (standalone, libretro, ...) ?**
Both

**What's your OS ? (windows, linux, OSX, ...) ?**
Windows 10 x64

**What's your hardware ? (CPU, GPU, ...) ?**
Core i7 4770k, GTX 760

**What's the storage type of the game (official cd, burned cd or cd image) ?**
cd image

**If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)**
cue/iso/wav

**Are you using any setting different from default ? If so, precise**
No

**Did this game work previously ? Do you remember when ? Is it happening with other games ?**
No, this is very specific to the patched version in CHD format.

**If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this**
Nothing, it just boots into the BIOS and states that the disk format is unsupported. I can see nothing in the logs that could be of any help. I could try to provide more information if you tell me what exactly.

**Comment by FCare** [comment]
Hi, thanks for the report. CHD is supported on kronos since last summer. There might be an issue with this specific CHD image.

**Comment by ner00** [comment]
@FCare You mean the resulting CHD that CHDMAN generates or the libchdr implementation in Kronos? In either case, CHD issues aren't exclusive to Kronos, in fact there is a CHD image from an untouched image that does not boot correctly with Beetle but instead boots fine with Kronos (Last Bronx (USA/EUR)). CHD itself can be a bit problematic sometimes, and in this instance there is the additional curve ball of the original image, eevn though it boots, not being standardized like the usual binary only data.

**Comment by ner00** [comment]
A few more tests seem to indicate that the issue between Kronos and CHD comes down to the image type and/or sector size.

Original CUE, track 1 (RAW, MODE1/2352):
```
FILE "Policenauts (Japan) (Disc 1) (Track 1).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
```

Modified CUE, track 1 (ISO, MODE1/2048):
```
FILE "POLICENAUTS_1-1.ENGLISH.iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
```

Not sure why that breaks Kronos but not Beetle which seems to have the almost exact same libchdr implementation.

**Comment by FCare** [comment]
I suspect the uncompressed policenauts binary file size not muliple of 2352, but multiple of 2048.

**Comment by ner00** [comment]
As per specification, the blocksize is 2048 [(libchdr, cdrom.h, line 37),](https://github.com/FCare/Kronos/blob/extui-align/yabause/src/libchdr/src/cdrom.h#L37) but that doesn't seem to be a problem for uncompressed binary (cooked ISO) or compressed binary (CHD) under the other core mentioned. In any case, additional info:

- ISO blocks: 222.921 blocks
- ISO size: 456.542.208 Bytes

```
chdman - MAME Compressed Hunks of Data (CHD) manager 0.218 (mame0218)
Input file:   POLICENAUTS_1.ENGLISH.chd
File Version: 5
Logical size: 550,359,360 bytes
Hunk Size:    19,584 bytes
Total Hunks:  28,103
Unit Size:    2,448 bytes
Total Units:  224,820
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     388,444,798 bytes
Ratio:        70.6%
SHA1:         7641f802f1278969cc5ad634f8f348698d3b3d28
Data SHA1:    4f4a658a1683377de0744c9861d39ead56b2f11b
Metadata:     Tag='CHT2'  Index=0  Length=91 bytes
              TRACK:1 TYPE:MODE1 SUBTYPE:NONE FRAMES:222921 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:150.
Metadata:     Tag='CHT2'  Index=1  Length=89 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:1896 PREGAP:150 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0.

     Hunks  Percent  Name
----------  -------  ------------------------------------
       139     0.5%  Copy from self
    27,042    96.2%  CD LZMA
       694     2.5%  CD Deflate
       228     0.8%  CD FLAC
```

**Comment by ner00** [comment]
The game is now loading on v2.1.2

P.S: Is m3u support for multi-disc planned?

**Comment by barbudreadmon** [comment]
> Is m3u support for multi-disc planned?

In the libretro port ? It was implemented last week.

**Comment by ner00** [comment]
@barbudreadmon Yes, in libretro. This is weird because when I try to change the Policenauts (m3u) core association from my playlist I don't get Kronos as an option. Might it be an RA thing not considering that the core is now supporting it?

**Comment by barbudreadmon** [comment]
oops, i forgot to update core infos, so it's probably not working if you use ui instead of command line, i'll update that soon.
