### ISSUE TITLE
[Mortal Kombat II] sprite and text issues

### ISSUE THREAD

**Issue by leglock** [FCare/Kronos#778]
**What's the full name of the game (including region) ?**
Mortal Kombat II (USA)

**What's your frontend ? (standalone, libretro, ...) ?**
standalone 

**What's your OS ? (windows, linux, OSX, ...) ?**
Windows 10 Pro 1909

**What's your hardware ? (CPU, GPU, ...) ?**
Intel Core i7-4710HQ, Intel HD Graphics 4600, NVIDIA GeForce GTX860M, 16GB ram

**What's the storage type of the game (official cd, burned cd or cd image) ?**
cd image

**If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)**
cue/bin within zip file

**Are you using any setting different from default ? If so, precise**
default settings

**Did this game work previously ? Do you remember when ? Is it happening with other games ?**
First time trying it. I have not experienced this specific issue with other games I have tried.

**If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this**
The character select screen tiles are obscured by black boxes.

![image](https://user-images.githubusercontent.com/5297922/76062035-726a2900-5f4a-11ea-9d69-d7d675abc231.png)

When in game, character sprites are almost entirely invisible - you can see small line near where their head would normally be, that is all. Also, the character text on the life bars and the win counter/press start text above the life bars its only partially visible. 

![image](https://user-images.githubusercontent.com/5297922/76062090-9594d880-5f4a-11ea-8fa2-394aad5b6f3e.png)

**Comment by FCare** [comment]
As a temporary workaround, you can use the compute shader renderer in the settings. I will fix this for openGL core.

**Comment by FCare** [comment]
Due to 6f2e6617c70db05a344713c84e071b7729c3addb

**Comment by FCare** [comment]
Fixed by 04361d668508c5ab2b56315fad77f500947cec5f
