### ISSUE TITLE
[Sailor Moon Super S - Various Emotion (J)] Problème d'affichage dans le mode entrainement...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#78]
UoYabause 1.4.0

Fork : Devmiyax/François

Pour allez dans le mode entrainement, sur le menu press start screen, il suffit de choisir la 4ème option.

Avec NBG0 on : 

![1sailor](https://user-images.githubusercontent.com/12481242/35977908-313a88a2-0cdc-11e8-9cf7-224350b0f088.JPG)

Avec NBG0 off : 

![1sailoroff](https://user-images.githubusercontent.com/12481242/35977939-3ba1c59e-0cdc-11e8-900a-9b0724c34c76.JPG)

**Comment by FCare** [comment]
Issue is in NBG2. BGON is 0x207

**Comment by BenjaminSiskoo** [comment]
NBG2 off avec kronos du 21.04.2018 : 

![1sailor](https://user-images.githubusercontent.com/12481242/39089839-004029de-45bf-11e8-8515-02fc7cbeab26.JPG)

**Comment by BenjaminSiskoo** [comment]
Pareil wip 15/01/2020

**Comment by BenjaminSiskoo** [comment]
Pareil avec Kronos du 26/03/2020 (commit VF Remix)

**Comment by fafling** [comment]
Fixé en WIP du 20/05/2021 par ac75a5ea2948cb92e321e9bc4a20098dbd2a77ab.
Dû à un cycle pattern qui ne contient des timings de character pattern pour le NBG2 sur la partition A0 de la vram alors que les pattern names donnent des adresses de character pattern sur le bank A1(0x38000) :
6 6 f e e e e e
4 4 f e e e e e
2 f f e e e e e
5 5 f e e e e e
