### ISSUE TITLE
[Steeldom] ligne (RGB0)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#780]
Kronos last wip (10/03/2020)

CS : 

![steeldom_cs](https://user-images.githubusercontent.com/12481242/76528038-7927fd00-6470-11ea-9bf0-28e4f02b795c.PNG)

OpenGL : 

![steeldom_opengl](https://user-images.githubusercontent.com/12481242/76528049-7e854780-6470-11ea-86e7-d98bd4fb649a.PNG)

savestate : 

[steeldom_CS.zip](https://github.com/FCare/Kronos/files/4324497/steeldom_CS.zip)
[steeldom_Opengl.zip](https://github.com/FCare/Kronos/files/4324503/steeldom_Opengl.zip)

**Comment by fafling** [comment]
Je n'ai trouvé aucune version de Kronos où le RBG0 est affiché correctement. Il est soit  complètement manquant comme en CS, soit affiché par des lignes comme en OpenGL dans les dernières versions (elles apparaissent en v2.0.1 publique, je ne les vois dans les WIP précédentes).

Affichage correct :
![Capture](https://user-images.githubusercontent.com/7624262/76579709-83c4af80-64cd-11ea-8b6c-1dbe2eee4a32.PNG)

Sur le RBG0, la table de coefficient est utilisée pour modifier les paramètres kx et ky :
![image](https://user-images.githubusercontent.com/7624262/76579858-077e9c00-64ce-11ea-99c6-37076e802fe2.png)
De plus, le VDP2 est en haute résolution non entrelacée, ce qui veut dire que le RBG0 fait l'objet d'un zoom automatique x2 horizontalement sur la console.

Sur le screen en CS, on voit le bug des mesh du VDP1 qui forment des lignes verticales en haute résolution non entrelacée, voir #671 (le system clipping montre que le VDP1 est bien dans cette résolution).

Testé avec le CD jap.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 30/03/2020
