### ISSUE TITLE
[Dark savior] Dégradé manquant sur le RBG0 pendant l'intro

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#782]
En WIP du 19/03, dans les 2 noyaux, il manque un dégradé vers l'horizon sur la mer pendant l'intro :
![image](https://user-images.githubusercontent.com/7624262/77122413-d1956680-6a3d-11ea-987f-51f16fd9e9eb.png)

Affichage correct sur la console (ne pas tenir compte de la teinte rougeâtre) :
![image](https://user-images.githubusercontent.com/7624262/77122261-76637400-6a3d-11ea-9f03-394125006584.png)

Le RBG0 utilise une table de coefficient et la color calculation, possible que l'effet soit obtenu avec le line color screen.
![image](https://user-images.githubusercontent.com/7624262/77122533-26d17800-6a3e-11ea-8f16-b60f2ba07eda.png)

Cependant le dégradé sature vers l'horizon, or le jeu n'a pas l'air d'utiliser le mode as-is comme Panzer dragoon : le NBG1 qui affiche les éclairs les fait disparaître progressivement en variant le color calculation ratio.
Possible que le jeu modifie le registre de color calculation ratio du RBG0 en cours d'affichage pour obtenir le dégradé.

Le dégradé était présent en v1.6.0 publique et disparaît avec le rework.

Testé avec le CD US.

**Comment by FCare** [comment]
due to https://github.com/FCare/Kronos/commit/47cac7e5e0f24af0ee1c42447c3c45103d69d657

**Comment by fafling** [comment]
Fixé en OpenGL en WIP du 22/03.
Le jeu utilise la table de coefficient du RBG0 pour modifier la couleur du line color screen. Le dégradé sur la mer n'est en fait pas uniforme contrairement à ce que je croyais et la variation de couleur du line color screen suffit à obtenir l'effet sans modification pendant la période d'affichage.

**Comment by fafling** [comment]
En WIP du 01/04, même souci que sur Panzer dragoon #624 , c'est correct en GPU RBG off (screen de gauche), mais l'effet vire au bleu en GPU RBG on :
![image](https://user-images.githubusercontent.com/7624262/78193903-ecbf9780-747b-11ea-9e6e-ecef207c8cce.png)

**Comment by fafling** [comment]
OK en CS en WIP du 02/04.
