### ISSUE TITLE
[Athlete Kings] Problème de FB similaire à Fuusei...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#789]
Kronos du 29/03/2020 

 j'ai trouvé je pense encore un problème similaire a fuusei avec le problème de FB. Athlete kings affiche pas les persos, mais si tu mets en pause et que que tu lance, les persos sont affichés (CS)

[athletekingsmenu.zip](https://github.com/FCare/Kronos/files/4399308/athletekingsmenu.zip)

**Comment by fafling** [comment]
Je ne reproduit pas ce problème dans la version US, Decathlete.

**Comment by BenjaminSiskoo** [comment]
Testé sur la version E
