### ISSUE TITLE
[Akumajou Dracula X] Problème d'alignement de l'arrière plan...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#79]
Fork : Devmiyax/François

Problème d'alignement de l'arrière plan du menu de sauvegarde

![akumajo_dracula](https://cloud.githubusercontent.com/assets/12481242/22059376/db284624-dd6c-11e6-9d0b-f639ccb25c68.jpg)

**Comment by FCare** [comment]
Le NBG0 est décalé d'une cellule (8 pixels). Le probleme semble etre dans la fonction Vdp2DrawMapTest.

**Comment by BenjaminSiskoo** [comment]
Pareil wip  15/01/2020

**Comment by BenjaminSiskoo** [comment]
Pareil avec Kronos du 26/03/2020 (commit VF Remix)

**Comment by mishamosher** [comment]
Additional info is available here:

https://github.com/devmiyax/yabause/issues/172

**Comment by BenjaminSiskoo** [comment]
Corrigé le 19/05/2021
