### ISSUE TITLE
[Hangon 95] Artefacts in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#792]
Wip du 01/04/2020

![hangoningame](https://user-images.githubusercontent.com/12481242/78143895-261de600-742f-11ea-8d86-1773d8607d53.PNG)

![hangonmoto](https://user-images.githubusercontent.com/12481242/78143905-2d44f400-742f-11ea-81ac-d49194c705f7.PNG)

Savestate : 

[hangon95.zip](https://github.com/FCare/Kronos/files/4415467/hangon95.zip)

**Comment by fafling** [comment]
Doublon du #234 .
