### ISSUE TITLE
[Panzer dragoon (Jap/Us)] Clignotement du texte pendant l'intro

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#794]
En WIP du 01/04, dans les 2 noyaux, le texte de l'intro clignote quand la video est affichée. Se produit depuis le 20/03 (probablement sur un commit du soir du 19). D'après @BenjaminSiskoo , le problème touche la version jap et us mais à priori pas l'européenne.
![image](https://user-images.githubusercontent.com/7624262/78191890-470a2980-7477-11ea-9cc7-5fc1c34ec97d.png)

Seul le texte est affiché par le VDP1.

Commande de dessin du texte :
![image](https://user-images.githubusercontent.com/7624262/78191913-54bfaf00-7477-11ea-931c-1f7bb2c2ad71.png)

Le polygone juste avant efface la zone où le texte est dessiné :
![image](https://user-images.githubusercontent.com/7624262/78192207-f6df9700-7477-11ea-861e-c7791d14cc14.png)

Testé avec le CD jap.

Save state :
[panzer_dragoon_texte_intro.zip](https://github.com/FCare/Kronos/files/4417962/panzer_dragoon_texte_intro.zip)

**Comment by BenjaminSiskoo** [comment]
Même problème Kronos 2.1.5 du 14.01.2021

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 04.01.2022
Mode Cs

Savestate à jour : 
[Uploading GS-9015_000.zip…]()

**Comment by fafling** [comment]
Fixé au cours des branches fbaccess et syncTiming.
