### ISSUE TITLE
[Highway 2000] Affichage qui saute pendant la rotation de la caméra...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#797]
Kronos wip du 02/04/2020 (commits 6225)

L'ombre sous la voiture passe dessus la voiture pendant la rotation de la caméra.

![highway2000](https://user-images.githubusercontent.com/12481242/78270702-78ccd000-750b-11ea-96f1-29bf33c8d5e3.PNG)

Savestate : 

[highway2000.zip](https://github.com/FCare/Kronos/files/4422119/highway2000.zip)

**Comment by fafling** [comment]
C'est un bug du jeu, c'est pareil sur la console : [https://youtu.be/9xgD5p-Ql2U?t=170](https://youtu.be/9xgD5p-Ql2U?t=170)

**Comment by BenjaminSiskoo** [comment]
Je ferme dans ce cas :) merci
