### ISSUE TITLE
[Gex] Clignotement dans le décor

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#803]
En WIP du 04/04, dans les 2 noyaux, on voit un clignotement de l'eau au fond d'un puits dans le 1er niveau. Ce clignotement ne se produit pas sur la console. Problème repéré sur la version PAL le 05/03 par @BenjaminSiskoo (identique en version US) :
https://youtu.be/dI57o4kpOqo?t=238

Le problème apparaît en WIP du 06/12/2019, peut-être lié au fix des changements de palette de couleur en cour d'affichage pour Sonic jam #695 .

Les graphismes du fond du puits sont affichés par le NBG0 et le NBG1. Les 2 couches ont la même priorité (le NBG0 est censé être au-dessus du NBG1 dans ce cas, p. 225 du mode d'emploi du VDP2). Les 2 utilisent la special priority function par tile, et activent la color calculation avec la special color calculation par tile.
![image](https://user-images.githubusercontent.com/7624262/78451630-f10bd080-7686-11ea-82ac-8eb4ed81bc9d.png)

Testé avec le CD US.

Save state :
[gex_clignotement_puits.zip](https://github.com/FCare/Kronos/files/4431386/gex_clignotement_puits.zip)

**Comment by BenjaminSiskoo** [comment]
Même problème Kronos 2.1.5 du 14.01.2021

**Comment by BenjaminSiskoo** [comment]
Kronos du 04.01.2022
Mode Cs

Savestate à jour : 
[T-15904H50_000.zip](https://github.com/FCare/Kronos/files/7808622/T-15904H50_000.zip)

**Comment by fafling** [comment]
Toujours présent en WIP du 16/11/2023.
Save state à jour :
[gex_clignotement_puits_v2.5.0_20231116.zip](https://github.com/FCare/Kronos/files/13385172/gex_clignotement_puits_v2.5.0_20231116.zip)

**Comment by BenjaminSiskoo** [comment]
Corrigé, wonderfull :)

**Comment by fafling** [comment]
J'ai voulu essayer Gex US pour vérifier le fix du clignotement du décor, je suis mort avant d'y arriver et peu après avoir recommencé le niveau, il y a eu un freeze avec invalid opcode :

Master SH2 invalid opcode

R0 =  000000E0	R12 =  0603164C
R1 =  00000100	R13 =  00000000
R2 =  00000000	R14 =  00000000
R3 =  00000000	R15 =  06001F34
R4 =  060B424C	SR =   00000191
R5 =  00000000	GBR =  00000000
R6 =  025A5001	VBR =  06000000
R7 =  00000075	MACH = 00061A80
R8 =  060B42C0	MACL = 00000000
R9 =  060B424C	PR =   06031506
R10 = FFFFFFFF	PC =   52564544
R11 = 06083E90

Address to inspect 605e8ec

looking for Gex (USA).elf

looking for Gex (USA).elf in E:/Roms/Sega Saturn redump

Could not find elf file, ignoring code

Address to inspect 6000952

looking for Gex (USA).elf

looking for Gex (USA).elf in E:/Roms/Sega Saturn redump

Could not find elf file, ignoring code

Address to inspect 6000952

![image](https://github.com/user-attachments/assets/81b2dc4a-c5d5-47e6-85cc-4435a7c16ae3)

J'ai aussi remarqué des sautes dans la musique pendant que je jouais.

**Comment by fafling** [comment]
Je précise que c'était avec la WIP 837973f.
Les sautes de musique in game existent en v2.6.2 publique mais semblent moins importantes.
J'ai également eu un freeze du jeu avec invalid opcode avec le même PC en v2.6.2 publique.
