### ISSUE TITLE
[SH2 rework] Liste de jeu avec soucis...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#804]
- **2do Aru Koto wa Sando R** : ce jeu bloquait soit quand pressait start, sinon quand on allait in game le perso commencait à courir puis l'ému bloquait au bout de 2-3 secondes.
- **Capcom gen 5** : écran noir après l'intro
- **Kanzen Chuukei Pro Yakyuu Greatest Nine**
- **Lifescape 2 - Body Bionics - Kyoui no Shouuchuu Jintai** : le jeu allait in game, là il bloque sur le press start screen
- **Skeleton Warrios** - Fixé

**Comment by BenjaminSiskoo** [comment]
Capcom gen 5 et Lifescape 2 sont corrigés.

**Comment by FCare** [comment]
skeleton Fixé
