### ISSUE TITLE
[Assault Suit Leynos 2] Crash possible...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#808]
AMELIORATION

Wip du 09/04/2020, avec les récentes modifications pour la première fois dans l'histoire de Yabause, on voir un écran now loading puis Kronos se ferme...

**Comment by FCare** [comment]
Pb de retour de fonction dans le C68. Les appels de fonction sont bons mais au retour de fonction, on ne revient pas au bon endroit

**Comment by BenjaminSiskoo** [comment]
Corrigé le jeu est jouable.
