### ISSUE TITLE
[Bug] Ecran noir in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#809]
AMELIORATION 

Depuis les modifs SH2/SCU (wip du 09/04/2020), le jeu passe l'écran d'introduction pour la première fois dans l'histoire de Yabause, cependant, in game on a un écran noir. En allant sur les debug, on voit les éléments.

Savestate : 

[bug.zip](https://github.com/FCare/Kronos/files/4455746/bug.zip)

**Comment by fafling** [comment]
Quand l'écran devient noir alors qu'il devrait afficher quelque chose, le compteur de FPS disparaît s'il est activé. ça se produit :
- Au 1er logo "Sega away team" qu'il devrait y avoir avant le logo Realtime.
- A l'écran titre.
- Dans le 1er  niveau après l'écran de chargement.

Dans les 3 cas, les commandes de dessin sont visibles dans l'écran debug du VDP1. Je ne vois pas d'anomalie, le seul aspect curieux c'est que les liste de commandes comportent un grand nombre de commandes skippées.

Même s'il est impossible d'interrompre l'intro alors qu'on peut le faire en appuyant sur start sur la console, le jeu répond aux boutons à l'écran titre et dans le 1er niveau même si rien n'est affiché.

**Comment by BenjaminSiskoo** [comment]
Adieu BR.
