### ISSUE TITLE
[Road Rash] Régression avec des artefacts in game..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#810]
Kronos wip du 10/04/2020

Quand tu mets des coups de poings il y a des artefacts façon comme Guardian Heroes.

Savestate : 

[raodrash.zip](https://github.com/FCare/Kronos/files/4461210/raodrash.zip)

**Comment by fafling** [comment]
Ne se produit qu'en noyau CS en v2.1.5 publique.

D'autres sprites sont aussi concernés par des corruptions intermittentes comme la voiture verte au 1er plan sur cette capture :
![image](https://user-images.githubusercontent.com/7624262/103286080-f57bd480-49df-11eb-9ce0-3d60d6213d25.png)

Le sprite est affiché correctement dans l'écran debug :
![image](https://user-images.githubusercontent.com/7624262/103286222-278d3680-49e0-11eb-98d3-89a15a36bfbb.png)

Testé avec le CD US.

**Comment by BenjaminSiskoo** [comment]
kronos20231216_f235e2e

Avec le fix du timing et les commits jusqu'au 15/12/2023, il n'y a quasiment plus d'artefacts. Presque corrigé.

**Comment by BenjaminSiskoo** [comment]
Corrigé vie la branche fb access
