### ISSUE TITLE
[Skeleton warriors] Screen tearing pendant la video d'intro en noyau compute shader

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#818]
En WIP du 12/04, uniquement en CS, il y a un cisaillement de l'image en haut de l'écran pendant la video d'intro (à gauche, affichage correct en OpenGL, à droite en CS) :
![Capture](https://user-images.githubusercontent.com/7624262/79081918-f8377c00-7d21-11ea-8f81-f4d419320348.PNG)

La video est affiché par le VDP1 avec un distorted sprite :
![image](https://user-images.githubusercontent.com/7624262/79081947-4482bc00-7d22-11ea-951c-5da814f0ad6c.png)

Testé avec le CD US.

**Comment by FCare** [comment]
Le tearing est du a un manque de synchro verticale avec l'ecran du PC.
Il y a toujours du tearing, en CS, comme els temps de calcul ne sont pas les memes, le tearing se voit.
Un ecran CRT est synchro a la frequence de la console 50 ou 60 fps. Sur un LCd, ce n'est pas le cas, suivant le jeu soit ton LCD doit etre en 50 hz, soit il doit etre en 60HZ. Si tu es synchro sur l'ecran, ca veut dire que parfois, une trame se reprete deux fois. Ca donne un effet de saccades.

Apres, est ce qu'il faut que ca soit une option ou pas, a voir...

**Comment by fafling** [comment]
@FCare J'ai pris les screenshots avec la synchro verticale activée dans Kronos. Rien que cette option devrait garantir que Kronos synchronise verticalement l'affichage, quelque soit les différences de fréquences entre l'écran et le jeu. En plus, mon écran a une fréquence de 60 Hz et le jeu est en NTSC. Dans ces conditions, je ne vois pas ce qui peut justifier ce tearing qui n'existe pas sur la console. Est-ce que tu peux rouvrir ce br ?

**Comment by FCare** [comment]
La synchro verticale ne synchronise pas sur l'ecran du PC, elle synchronise sur le timing PAL/NTSC.
Si vous voulez synchroniser sur l'ecran du PC, il faut appliquer ce patch la:
diff --git a/yabause/src/qt/YabauseGL.cpp b/yabause/src/qt/YabauseGL.cpp
index 8dc03f52..54cf44d9 100644
--- a/yabause/src/qt/YabauseGL.cpp
+++ b/yabause/src/qt/YabauseGL.cpp
@@ -31,7 +31,7 @@ YabauseGL::YabauseGL( ) : QOpenGLWindow()
   format.setGreenBufferSize(8);
   format.setBlueBufferSize(8);
   format.setAlphaBufferSize(8);
-  format.setSwapInterval(0);
+  format.setSwapInterval(1);
   format.setRenderableType(QSurfaceFormat::OpenGL);
 
 #ifdef _OGL3_

**Comment by FCare** [comment]
Mais si on fait ca, on va rajouter du lag et du "stuttering" dans le  du PAL avec un ecran de PC en 60 fps. 1 image/5 sera doublée. si on a à l'inverse un ecran en 50hz et un jeu en 60fps, on aura un ralentissement du jeu du a la synchro avec l'ecran...

**Comment by fafling** [comment]
En synchro verticale, si on double des image pour passer un jeu 50 fps sur un écran 60 Hz, donc conservant sa vitesse de jeu originale à 50 images de jeu par seconde, le comportement attendu d'un jeu 60 fps sur un écran 50 Hz serait de faire du frame skip pour là encore conserver la vitesse de jeu originale : il y a 60 images de jeu calculées par secondes, mais on n'en affiche que 50.

L'autre possibilité est effectivement de conserver la fluidité de la vidéo au dépend de la vitesse de jeu pour afficher une image du jeu par frame d'écran quelque soit la vitesse d'affichage originale :
- Les jeux en 50 fps sont accélérés sur un écran 60 Hz.
- Les jeux en 60 fps sont ralentis sur un écran 50 Hz.

En tout cas l'option synchro verticale de Kronos devrait s'appeler autrement : actuellement c'est plus un limiteur de framerate à la fréquence originale du jeu, indépendant de la fréquence d'affichage de l'écran.

Je laisse ouvert car il est souhaitable de pemettre à l'utilisateur d'éliminer le tearing par une option, pas en devant recompiler Kronos. J'ai tenté de forcer la synchro verticale par les paramètres de ma carte vidéo, mais cela ne fait que limiter le framerate de Kronos à 60 sans éliminer le tearing.

**Comment by barbudreadmon** [comment]
Chez moi le soucis se produit aussi en noyau opengl + rbg compute shaders

**Comment by fafling** [comment]
Fixé en WIP du 23/04.
