### ISSUE TITLE
ST-V [Cotton Boomerang] and others ST-V roms, starts automatically with credits (see VIDEO)

### ISSUE THREAD

**Issue by r3tro80** [FCare/Kronos#819]
What's the full name of the game (including region) ? Cotton Boomerang (ST-V)

What's your frontend ? (standalone, libretro, ...) ? libretro

What's your OS ? (windows, linux, OSX, ...) ? linux

What's your hardware ? (CPU, GPU, ...) ? i5-9600 -int.GPU

What's the storage type of the game (official cd, burned cd or cd image) ? mame rom

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...) zip

Are you using any setting different from default ? If so, precise: NO

Did this game work previously ? Do you remember when ? Is it happening with other games ? Worked fine some commits ago, other ST-V have same issue.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this: https://youtu.be/Ru2XkRTpa5Y

**Comment by barbudreadmon** [comment]
Thanks for the report, while i knew about the issue (which is not blocking afaik), it doesn't seem it was ever reported.
Not sure what is at work here, probably some smpc weirdness.

**Comment by r3tro80** [comment]
This bug was introduced recently, it was not present some months ago. Cottom Boomerng adds two coins for each player, other games adds only 1 coin for each player. Meanwhile the bug about the slow play of Golden Axe Duel has been solved!!

**Comment by barbudreadmon** [comment]
Yeah, iirc the credit bug appeared after the smpc fixes from january

**Comment by FCare** [comment]
Backup Ram coin increase loop:

Read @3d05 = 5
Read @3d5d = 0
Write 3d5d 1
Read @3d5d = 1
Read @3d05 = 5
Write 3d05 6
Read @3d5d = 1
Write 3d5d 0
Read @3d5d = 0

0x3d05: coin number
0x3d5d: coin lockdown

**Comment by FCare** [comment]
Fixed by cb183d0ce68ac35a69cf947bd094aac9bb1c7577 and 18558c1cd72e4b71077a19136796b0a4bacec478
