### ISSUE TITLE
[F1 challenge] Couleurs incorrectes à l'écran de configuration de la voiture

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#829]
En WIP du 20/04, dans les 2 noyaux, les couleurs sont incorrectes sur les sprites à l'écran de configuration de la voiture :
![Capture](https://user-images.githubusercontent.com/7624262/79787072-afe21480-8346-11ea-8a60-254d45e49e14.PNG)

Présent en v2.1.1 publique, apparaît le 12/04, peut-être suite au fix de la lecture de la coefficient table en color ram pour Wing arms.

Comme Wing arms, F1 challenge utilise le mode 0 de la color ram et se sert de la table de coefficient pour le RBG0.
![image](https://user-images.githubusercontent.com/7624262/79787662-a73e0e00-8347-11ea-8917-7dcfb7b00cc6.png)

Testé avec le CD US.

**Comment by FCare** [comment]
due to 8a72445fa493b2cf0724b01838e1b2dfa96dc74d
