### ISSUE TITLE
[Bug] Le jeu affiche un écran noir...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#83]
Fork : Devmiyax/François

![1bug](https://user-images.githubusercontent.com/12481242/35979706-eac946ce-0ce0-11e8-974b-f4db49add8f8.JPG)

**Comment by BenjaminSiskoo** [comment]
Suite au correctif de Devmiyax du 17/09/2018, le jeu démarre mais bloque après la vidéo d'intro.

**Comment by fafling** [comment]
En v1.7.0 publique, le jeu fait toujours écran noir après la video d'intro (bios réel et émulé) sans répondre aux commandes pendant la video. Avant la video, seul le logo Realtime associates est affiché, le logo Sega Away team n'est pas visible.

En WIP du 28/06/2019, il bloque de nouveau au logo Sega away team en bios réel (pas de changement pour le bios émulé).

Testé avec le CD européen.

**Comment by BenjaminSiskoo** [comment]
Pareil Wip du 15/01/2020

**Comment by BenjaminSiskoo** [comment]
Pareil avec Kronos du 26/03/2020 (commit VF Remix)

**Comment by BenjaminSiskoo** [comment]
Sur la dernière Wip du 27.08.2021, le jeu n'affiche pas le logo puis affiche l'intro vidéo, puis écran noir

**Comment by BenjaminSiskoo** [comment]
Après toutes ces années, c'est avec joie que je ferme ce BR.
