### ISSUE TITLE
[Akumajou Dracula X] Textes manquants en noyau CS upscalé

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#836]
![Akumajou Dracula X - Gekka no Yasoukyoku (Japan) (2M)-200425-200434](https://user-images.githubusercontent.com/10391265/80290113-9a545c80-8743-11ea-8872-ecd9be6cc2f4.png)

Noyau CS en upscaling.
Ma bkram : 
[Akumajou Dracula X - Gekka no Yasoukyoku (Japan) (2M).zip](https://github.com/FCare/Kronos/files/4533949/Akumajou.Dracula.X.-.Gekka.no.Yasoukyoku.Japan.2M.zip)
Chargez la partie => sortez => rentrez => placez vous sous la sorte d'étoile et appuyer sur haut

**Comment by fafling** [comment]
En CS avec upscale, ces textures ne s'affichent pas du tout.
En CS sans upscale et en OpenGL, on peut provoquer ce problème aussi en mettant l'émulation en pause ou en affichant une fenêtre du menu de Kronos avant d'afficher ce menu.
Texture d'un des messages non affichés :
![image](https://user-images.githubusercontent.com/7624262/80292379-bc0b0f00-8756-11ea-8d88-74e086599454.png)

**Comment by BenjaminSiskoo** [comment]
Savestate : 
[T-9527G_001.zip](https://github.com/FCare/Kronos/files/7703709/T-9527G_001.zip)

**Comment by BenjaminSiskoo** [comment]
Semble corrigé avec la wip du 01.02.2023, je réouvrirais si besoin.
