### ISSUE TITLE
[Akumajou Dracula X] Lignes grises verticales en noyau OpenGL

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#837]
![Akumajou Dracula X - Gekka no Yasoukyoku (Japan) (2M)-200425-195923](https://user-images.githubusercontent.com/10391265/80290253-6ded1000-8744-11ea-9acf-d0ec97859e2b.png)

Pas de réglages additionnels, utilisez la bkram de https://github.com/FCare/Kronos/issues/836, chargez la partie, il y aura ces lignes, elles disparaissent au bout d'un moment.

**Comment by fafling** [comment]
Je ne reproduit pas ce problème sur la WIP du 23/04.

**Comment by barbudreadmon** [comment]
Étrange, j'ai le bug de manière consistante, çà pourrait être lié aux commits des 2 derniers jours ?
Les lignes apparaissent pendant l'animation du cercueil après le chargement, quand il s'envole en dehors de l'écran, comme si le cercueil corrompait quelque chose, j'ai fait une petite vidéo : 

[video.zip](https://github.com/FCare/Kronos/files/4534668/video.zip)

**Comment by barbudreadmon** [comment]
réglé par https://github.com/FCare/Kronos/commit/fcc8048519f78ba0bb49de069f7375fbb385a29c
