### ISSUE TITLE
[Akumajou Dracula X] "Etoile" déformée dans la salle de sauvegarde en noyau OpenGL

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#838]
![Akumajou Dracula X - Gekka no Yasoukyoku (Japan) (2M)-200425-200542](https://user-images.githubusercontent.com/10391265/80290420-21ee9b00-8745-11ea-8825-c0144e6c76c1.png)

La sorte d'étoile est déformée, c'est particulièrement visible si l'on compare à la version CS de https://github.com/FCare/Kronos/issues/836 en s'attardant sur les coins et la façon dont la forme pivote. La même bkram est toujours utilisable.

NB : Les textures sont également erronées en perspective correction (utilisé pour ce screenshot), mais çà va beaucoup mieux avec la tesselation

**Comment by fafling** [comment]
L'affiche n'est incorrect qu'en tesselation triangles avec correction de perspective.
Toutes les faces du polyèdre sont dessinée avec des triangles utilisant une textures anamorphiques dont le bas est pincé.
![image](https://user-images.githubusercontent.com/7624262/80291638-a80fdf00-874f-11ea-9f22-6cabeebcbbb3.png)

**Comment by fafling** [comment]
il faut mettre l'émulation en pause juste après l'écran de chargement pour le voir, mais le cercueil où apparaît le perso a le même problème, pour les mêmes raisons :
![image](https://user-images.githubusercontent.com/7624262/80292067-76991280-8753-11ea-8331-dc46aa5232e4.png)

**Comment by FCare** [comment]
Donc ce n'est pas un bug en fait? La tesselation a ete ajoutée pour regler ce pb la.
Je clos le ticket.

**Comment by barbudreadmon** [comment]
Désolé je n'ai pas du être très clair, donc j'ai refait une capture en gpu tess et cette fois j'ai entouré les éléments déformés, merci de ré-ouvrir.

![bug](https://user-images.githubusercontent.com/10391265/80298431-9b5dac00-878c-11ea-9ebf-a4c79b22d8ca.png)


Cette déformation est visible sur les "coins" mais aussi par rapport à la rotation de cette sorte d'étoile, et n'est pas du tout présente en CS, je remets la capture de l'autre br pour que ce soit plus flagrant : 
![en cs](https://user-images.githubusercontent.com/10391265/80290113-9a545c80-8743-11ea-8872-ecd9be6cc2f4.png)
Ici on a de beaux angles et de belles lignes droite sur les faces de cet objet

**Comment by barbudreadmon** [comment]
réglé par https://github.com/FCare/Kronos/commit/fcc8048519f78ba0bb49de069f7375fbb385a29c
