### ISSUE TITLE
[Mega Man X3] Personnage glitché en noyau OpenGL (problème timing ?)

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#841]
![Mega Man X3 (Europe)-200426-184916](https://user-images.githubusercontent.com/10391265/80314044-1fe11680-87ef-11ea-9886-8035bad86b4b.png)

Surement le même problème de timing qu'on a sur d'autres jeux.

**Comment by FCare** [comment]
surement un probleme de cache du core openGL

**Comment by BenjaminSiskoo** [comment]
Arrêt support OpenGL
