### ISSUE TITLE
ST-V [Cotton2 & Cotton Boomerang] main sprites are transparent. (see pics)

### ISSUE THREAD

**Issue by r3tro80** [FCare/Kronos#844]
What's the full name of the game (including region) ? Cotton2 & Cotton Boomerang (ST-V)

What's your frontend ? (standalone, libretro, ...) ? libretro

What's your OS ? (windows, linux, OSX, ...) ? debian

What's your hardware ? (CPU, GPU, ...) ? i5-9600 int.GPU

What's the storage type of the game (official cd, burned cd or cd image) ? mame rom

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)

Are you using any setting different from default ? If so, precise. Default

Did this game work previously ? Do you remember when ? Is it happening with other games ? Yes!

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this:

Regression: Now the main sprite, the nemy sprites and some background is transparent. Bug introduced recently.

![cottonbm-200428-165810](https://user-images.githubusercontent.com/32760152/80509941-572ffe80-897a-11ea-8b24-d301d135bb01.png)
![cottonbm-200428-165824](https://user-images.githubusercontent.com/32760152/80509952-5ac38580-897a-11ea-8ad8-f619ed200d41.png)

**Comment by barbudreadmon** [comment]
Regression from https://github.com/FCare/Kronos/commit/cbcd5c40a8215bd21081f66769934307767bdb7f

Sega Saturn versions are also affected

**Comment by barbudreadmon** [comment]
fixed
