### ISSUE TITLE
ST-V [Maruchan De Goo] transparent sprites in intro & between stages. (PICS)

### ISSUE THREAD

**Issue by r3tro80** [FCare/Kronos#849]
What's the full name of the game (including region) ? Maruchan De Goo

What's your frontend ? (standalone, libretro, ...) ? libretro

What's your OS ? (windows, linux, OSX, ...) ? debian

What's your hardware ? (CPU, GPU, ...) ? i5-9600K, int.GPU

What's the storage type of the game (official cd, burned cd or cd image) ? mame rom

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)

Are you using any setting different from default ? If so, precise: Default settings

Did this game work previously ? Do you remember when ? Is it happening with other games ? Yes, previously worked flawless.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this:

Sprites during intro and between stages are sometimes transparent (similar to the bug of the Cotton games fixed today). SEE PICS

![maruchan-200429-154854](https://user-images.githubusercontent.com/32760152/80610878-2fa06b00-8a3a-11ea-87a5-a67c50bc80fd.png)
![maruchan-200429-154912](https://user-images.githubusercontent.com/32760152/80610915-39c26980-8a3a-11ea-81a5-7ed8b1c5cab6.png)
![maruchan-200429-155010](https://user-images.githubusercontent.com/32760152/80610938-421aa480-8a3a-11ea-8dfa-e4992a77e7a8.png)

**Comment by barbudreadmon** [comment]
Regression from https://github.com/FCare/Kronos/commit/cbcd5c40a8215bd21081f66769934307767bdb7f too, but somehow the cotton fix didn't fix this one.

**Comment by barbudreadmon** [comment]
@fastpop72 it was closed because it was fixed btw :)
