### ISSUE TITLE
[Fantastic Pinball] Problème couleur d'arrière plan...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#85]
Fork : Devmiyax/François

![fantastic](https://cloud.githubusercontent.com/assets/12481242/22063217/efac6af6-dd7d-11e6-8235-8a2731880515.png)

**Comment by FCare** [comment]
Fixed by https://github.com/FCare/yabause/commit/a07d7eb15d51d0000e4ddfa0783188531770db29
