### ISSUE TITLE
[Filtre] Affichage du filet dans Breakpoint Tennis...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#855]
Wip du 30 Avril 2020 

Avec le filtre 4xBRZ, le filet est surprononcé, c'est peut être normal, mais je fais ce BR au cas ou c'est un vrai problème 

![breakpoint](https://user-images.githubusercontent.com/12481242/80797353-ed923900-8ba1-11ea-986f-a78484304d5c.PNG)

**Comment by FCare** [comment]
C'est normal le 4xBRZ interpole les images pour tenter de les lisser...
