### ISSUE TITLE
[Hang on GP] Fenêtres incorrectes à la sélection de la moto

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#861]
En WIP du 02/05, dans les 2 noyaux, il y a un décalage par rapport à la console des 2 fenêtres qui tronquent au milieu de l'écran les jauges affichées par le NBG2 à l'écran de sélection de la moto. C'est visible en particulier sur les jauges du haut de l'écran qui ne sont tronquées que sur une partie de leur hauteur.

A gauche Kronos, à droite une photo prise sur ma console :
![image](https://user-images.githubusercontent.com/7624262/81025623-7bf30d00-8e77-11ea-9687-08c34dc21e14.png)

Je ne suis pas arrivé à trouver une video qui affiche les jauges pareil et avec le même décalage par rapport au sprites. Il y a en effet un décalage horizontal des jauges avec les icônes et le titre affichés par les sprites, peut-être dû à une émulation incorrecte de la transformation du framebuffer utilisée par ce jeu (voir #234 ).

Les artifacts visibles à gauche de l'écran appartiennent aussi en NBG2.

Le NBG2 est affiché à l'extérieur des 2 fenêtres W0 et W1 :
![image](https://user-images.githubusercontent.com/7624262/81023871-12bccb00-8e72-11ea-9a42-ca7e964b9c3f.png)

Testé avec le CD US.

Save state :
[hang_on_gp_selection_moto.zip](https://github.com/FCare/Kronos/files/4578306/hang_on_gp_selection_moto.zip)

**Comment by fafling** [comment]
Le problème des fenêtres est apparu en v1.7.0. Leur positionnement à l'air correct en v1.6.0 :
![image](https://user-images.githubusercontent.com/7624262/81026586-e48fb900-8e7a-11ea-877a-c146e3c8e275.png)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 21.05.2021

**Comment by fafling** [comment]
@BenjaminSiskoo Les artifacts et le décalage du NBG2 sont effectivement réglés, mais la fenêtre qui tronque les jauges n'est toujours pas correcte. Est-ce que tu peux rouvrir ?

**Comment by BenjaminSiskoo** [comment]
@fafling tu pourrais peut être refaire un BR spécifique pour ce bug ?

**Comment by fafling** [comment]
@BenjaminSiskoo Je préfère ne pas multiplier les br sur le même sujet.

Même avec la correction du décalage horizontal du NBG2, le positionnement horizontal et vertical des fenêtres reste incorrect :
![image](https://user-images.githubusercontent.com/7624262/119225965-1cf64980-bb07-11eb-955d-9719c2901e54.png)

Mise à jour du save state (version US) :
[hang_on_gp_selection_moto_20210522.zip](https://github.com/FCare/Kronos/files/6526367/hang_on_gp_selection_moto_20210522.zip)

**Comment by fafling** [comment]
Fixé dans les 2 noyaux dans la dernière WIP, et depuis la 3ème du 15/12 qui corrige les combinaisons de fenêtres. C'était donc le même problème que #986 .
