### ISSUE TITLE
Gestion langue bios

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#869]
Le choix de la langue du bios (pas la région !) semble impacter la langue de certains jeux sur saturn, voir https://mednafen.github.io/documentation/ss.html (chercher "ss.smpc.autortc.lang"), ce serait bien d'implémenter un mécanisme permettant de la sélectionner dans Kronos.

Jeu(x) utilisant cette fonctionnalité : 
- Panzer Dragoon (Europe)
- ???

**Comment by fafling** [comment]
Doublon de #420 .

**Comment by barbudreadmon** [comment]
Pas tout à fait, ce qui m'intéresse surtout dans ce br-ci, c'est qu'il est visiblement possible de configurer çà en amont au lieu de devoir aller dans le bios. Donc c'est surtout un reminder disant d'aller voir comment çà fonctionne dans le code de mednafen pour éventuellement backporter sur Kronos.

**Comment by barbudreadmon** [comment]
setting implémenté, il restera à l'ajouter sur l'interface QT

**Comment by fafling** [comment]
Le paramètre "bios language" fonctionne en WIP standalone du 16/12.
