### ISSUE TITLE
[Street Fighter - The Movie (Europe)] Problèmes d'ombres sous les perso en OpenGL...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#87]
Fork : Devmiyax/François

L'ombre possède des traits horizontaux vides.

![streetthemovie](https://cloud.githubusercontent.com/assets/12481242/22065932/c5c537e2-dd8a-11e6-89cc-1b5e04425cf3.JPG)

**Comment by BenjaminSiskoo** [comment]
Corrigé en ce jour du 31/10/2018

**Comment by fafling** [comment]
@BenjaminSiskoo Est-ce que tu peux rouvrir ?

Le problème est de nouveau présent en noyau OpenGL uniquement, en WIP accurate_vdp1 du 26/10 et extui-align du 11/09. Il est réapparu en WIP du 17/03 et est présent dans la v1.7.0 publique.

C'est indépendant du mode de tessellation, par contre ce n'est visible qu'en OpenGL size original pour les 2 branches, et native mais seulement en extui-align (autres paramètres et taille de fenêtre par défaut pour les 2, sauf désactivation de la synchro verticale).

Les ombres sont dessinées avec des distorted sprites qui utilisent le mode MSB on. Leurs coordonnées verticales sont adjacentes, il ne devrait pas y avoir d'espace entre chaque sprite comme sur la console.

Un save state pour reproduire :
[street_fighter_the_movie_1er_combat.zip](https://github.com/FCare/Kronos/files/3775124/street_fighter_the_movie_1er_combat.zip)

Testé avec le CD PAL.

**Comment by fafling** [comment]
Problème toujours présent en noyau OpenGL uniquement en v2.0.1 publique.

**Comment by BenjaminSiskoo** [comment]
Pareil Wip du 15/01/2020

**Comment by BenjaminSiskoo** [comment]
Problème OpenGL toujours présent Kronos du 26/03/2020 (commit VF Remix)

**Comment by BenjaminSiskoo** [comment]
Problème OpenGL toujours présent Kronos du 03/04/2020

**Comment by BenjaminSiskoo** [comment]
Toujours présent wip du 20/10/2020

**Comment by BenjaminSiskoo** [comment]
Toujours présent avec Kronos 2.1.5

**Comment by BenjaminSiskoo** [comment]
Corrigé Kronos 2.1.5

**Comment by fafling** [comment]
C'est toujours présent chez moi dans la dernière WIP.
Mise à jour de la save state du CD PAL :
[street_fighter_the_movie_1er_combat_20210428.zip](https://github.com/FCare/Kronos/files/6394968/street_fighter_the_movie_1er_combat_20210428.zip)

**Comment by BenjaminSiskoo** [comment]
Kronos du 14.01.2022
Mode OpenGl 

![image](https://user-images.githubusercontent.com/12481242/149495815-5d5f84e5-e3ab-4e3d-b716-e4042657c7f9.png)

**Comment by fafling** [comment]
Toujours présent chez moi dans la dernière WIP.
Mise à jour du save state (version PAL) :
[street_fighter_the_movie_1er_combat_20220118.zip](https://github.com/FCare/Kronos/files/7893365/street_fighter_the_movie_1er_combat_20220118.zip)

**Comment by BenjaminSiskoo** [comment]
Abandon opengl
