### ISSUE TITLE
Aide - comment on se sert exactement de l'outils "transfert"

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#872]
Bonjour,

J'ai beau chercher sur google, sous le nom de yabause, uoyabause, yaba sanshiro et kronos, je trouves nul part un texte ou un tuto pour comprendre à quoi sert l'outils dans le menu qui s'appel groot... ah non lui c'est l'autre con d'arbre, l'outils "transfert".

Enfaite je souhaite importer un RAW BIN d'une carte mémoire dumpé dans mon émulateur, mais dès que je charge le fichier bin il se passe rien, aucun message, aucun log.

Adresse de début et adresse de fin on ne comprends pas ce que ça veut dire.

Pouvez-vous m'expliquer svp ou y aurait'il un lien que je n'ai pas vu ?

**Comment by fafling** [comment]
Il y a une petite doc là-dessus : [https://web.archive.org/web/20180819221713/http://wiki.yabause.org/index.php5?title=Readme_QT#Memory_Transfer](https://web.archive.org/web/20180819221713/http://wiki.yabause.org/index.php5?title=Readme_QT#Memory_Transfer)

Mais je ne sais pas si ça peut permettre d'importer le contenu d'une carte mémoire.

**Comment by barbudreadmon** [comment]
Je me demande si https://github.com/hitomi2500/ss-save-parser/releases/tag/0.9.5 ne pourrait pas être utile, c'est un outil pour transférer des sauvegardes d'un émulateur à un autre, il y a des chances pour qu'il accepte également des vrais dumps de carte mémoire (qui devraient être proches du format que yabause et yabasanshiro utilisent, nous on a retiré les bits de mirroring pour gagner de la place et être compatible avec mednafen)

**Comment by CloudFR** [comment]
Merci mais la doc n'est pas vraiment utile... tant pis.
