### ISSUE TITLE
Copie d'ecran enregistre des screenshots noir

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#873]
Bonjour,

J'ai réalisé des copies d'écrans (CTRL+P) et j'ai réalisé qu'il enregistré des screens tout noir.

![image](https://user-images.githubusercontent.com/50514097/81466625-64978500-91d3-11ea-8dc7-9640e11c6f0b.png)

Kronos version : 2.1.2
Ma config :
![image](https://user-images.githubusercontent.com/50514097/81466594-3fa31200-91d3-11ea-94dc-b56eabb13a7d.png)

La version précédente de kronos 1.7.0 ou 2.0 ça fonctionnait.

**Comment by fafling** [comment]
Je ne reproduit le problème qu'en utilisant le filtre HQ4x.
Avec un autre réglage de filtre d'interpolation, la capture d'écran fonctionne.
Le problème apparaît en WIP du 19/05.

**Comment by BenjaminSiskoo** [comment]
Même problème le 09.09.2021.

**Comment by BenjaminSiskoo** [comment]
Corrigé avec Kronos 2.6.1
