### ISSUE TITLE
Comment créer un zip d'une bin+cue bootable ?

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#874]
Bonjour,

Je n'arrive pas à comprendre d'où vient le problème.

Kronos 2.1.2 charge et boot des jeux zip contenant soit des bin+cue ou même des img+cue.

Lorsque je réalise une archive zip avec 7zip, n'importe quels modes de compressions, kronos ne les charges pas.

Y a t'ils des specs à savoir pour créer une archive zip bootable ?

**Comment by FCare** [comment]
Bonjour,

On utilise une librairie de decompression du format zip. Le format 7z est
legerement different.
Il faut bien s'assurer que le format utiliser et du zip, pas seulement
l'extension.
7zip sait faire les deux.

Au pire, connectes toi sur le discord et envoie ton zip en MP.

Francois

**Comment by CloudFR** [comment]
Bonjour,

Je viens d'essayer tous les algorithmes de compressions de 7zip au format zip, ainsi que tous les modes de compression (de aucune à ultra), rien à faire les zip ne sont pas bootable.

Je ne vois aucune différence, donc ça veut dire que 7zip n'utilise pas le bon algo de compression que vous utilisez pour le décompresser ?

Avec quel logiciel de compression vous le faites si ce n'est pas 7zip ?

**Comment by CloudFR** [comment]
Oh mon GOD laissez tomber ! Je vois que dans l'exploration vous pouvez charger des... CHD !!!!!
J'espère que ça fonctionne à 100% car c'est mon format de compression préféré :)
Je vais de ce pas essayer ça.
Je pensais que le zip était le seul moyen de gagner de l'espace de disque.

EDIT

Non en faite ne laissez pas tomber
https://github.com/FCare/Kronos/issues/875

**Comment by CloudFR** [comment]
Bonjour,

Bon ça fonctionne avec d'autres jeux autre que SFIII patché.

**Comment by barbudreadmon** [comment]
à mon avis çà doit être le même problème que pour les CHD, probablement une bizarrerie dans la taille des secteurs après le patch...
