### ISSUE TITLE
Fichier CHD => disque inconnu par le système

### ISSUE THREAD

**Issue by CloudFR** [FCare/Kronos#875]
Bonjour,

J’étais entre le zip et le chd depuis tout à l'heure, je viens de tester une conversion chd et le jeu n'est pas bootable, même avec le bon BIOS de la zone.

J'ai le message du BIOS "Disque illisible pour le système"

![image](https://user-images.githubusercontent.com/50514097/81478319-c03a3080-921c-11ea-8b5c-430ec893c613.png)

**Comment by barbudreadmon** [comment]
T'es sûr que ton cue/bin n'a pas un soucis ? il est bootable en tant que cue/bin non zippé ?

**Comment by CloudFR** [comment]
Bonjour, Oui tout à fait !
Je vais essayer avec un autre jeux je reviens dans 5 minutes.

**Comment by barbudreadmon** [comment]
c'est quoi le jeu ? idéalement vient sur le discord pour qu'on puisse debug çà ensemble, parce que je n'ai tes soucis ni avec les cue/bin zippés, ni avec les chd

**Comment by CloudFR** [comment]
Je viens d'essayer un autre ça à fonctionné... je check d'ou ça vient...
j'ai modifié les .cue, ça ne change rien...
C'est SFIII sc1 en jap pour les tests.

**Comment by barbudreadmon** [comment]
> C'est SFIII sc1 en jap pour les tests.

Non patché ?

**Comment by CloudFR** [comment]
Si ils le sont, les autres jeux ça marche crème...

**Comment by CloudFR** [comment]
Bon ça fonctionne très bien, c'est juste que un jeu patché malheureusement ne fonctionne pas en CHD...

**Comment by barbudreadmon** [comment]
oui, de mémoire le format CHD a tendance à merder avec les homebrews et autres hacks, j'ai souvent vu des reports sur çà avec les CDIs convertis en CHD sur flycast...
