### ISSUE TITLE
Vandal Hearts - no rectangular cursor

### ISSUE THREAD

**Issue by paul-met** [FCare/Kronos#896]
Vandal Hearts still does not display a rectangular cursor. In VDP1 debugging it says "CMD size is null, skipped". This bug is typical for all emulators on the Yabause engine.

**Comment by fafling** [comment]
First, the display of the blue selection rectangle on title screen menu is correct in Yabause 0.9.14 with the software interface only :
![image](https://user-images.githubusercontent.com/7624262/85181754-01474b00-b287-11ea-882b-3362cdc45d10.png)

Incorrect display in Kronos v2.1.2 and last WIP with both video cores, selection rectangle is missing :
![image](https://user-images.githubusercontent.com/7624262/85181988-abbf6e00-b287-11ea-8612-2bca6d615b0e.png)

I haven't found a version of Kronos where the rectangle was displayed.

In Kronos VDP1 debug screen :
![image](https://user-images.githubusercontent.com/7624262/85182172-2c7e6a00-b288-11ea-9400-2ac089ff0edf.png)

In Yabause VDP1 debug screen :
![image](https://user-images.githubusercontent.com/7624262/85182425-eb3a8a00-b288-11ea-914a-f65b1cedea8f.png)

With local coordinates [160, 112], the coordinates of the scaled sprite match the selection rectangle area. Its texture dimensions both set to 0 are indeed invalid, however, the console does not skip the command. It is drawn with following undocumented rules (from Charles MacDonald in [https://segaretro.org/Saturn_VDP1_hardware_notes_(2003-05-17)](<https://segaretro.org/Saturn_VDP1_hardware_notes_(2003-05-17)>) :
- If the width in CMDSIZE is set to zero, the first pixel in the texture map is shown for every pixel of every line (this is the case for the selection rectangle).
- If the height in CMDSIZE is set to zero, it works the same as a height of one. (e.g. the first line of the texture map is shown for all lines of the sprite).

Tested with the original CD.

**Comment by fafling** [comment]
The cursor isn't displayed in OpenGL core since the 7 Sep 2020 WIP.  It was only correct in the 2 Sep 2020 WIP.
It is still correct in CS core in the last WIP.
@FCare or @BenjaminSiskoo can you reopen ?

**Comment by BenjaminSiskoo** [comment]
Kronos 10.01.2023

Fixed with CS, 
OpenGl shound not be maintened.
