### ISSUE TITLE
.desktop file error on Fedora Linux

### ISSUE THREAD

**Issue by jdwininger** [FCare/Kronos#899]
I'm running Fedora Linux 32 and I've compiled Kronos form the extui-align branch. When I make install the .desktop file is installed properly into /usr/share/applications but it fails to show up in gnome-shell's application list. After poking around in the kronos.desktop file I noticed the tag **TryExec=yabause**. This is one I've not encountered before. Since i wasn't familiar with the tag I made a backup of the kronos.desktop and deleted the line. After the edit and restarting gnome-shell the launcher appeared as expected in the applications list.

If the tag **TryExec=yabause** is not needed can it be removed form the kronos.desktop file so the launcher will show up in gnome-shell's applications list.

**Comment by FCare** [comment]
Fixed.
