### ISSUE TITLE
[Contra - Legacy Of War] Ecran de transition manquant...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#90]
Fork : Devmiyax/François

![contra-ecranmanquant](https://cloud.githubusercontent.com/assets/12481242/23017489/bf2a147c-f43a-11e6-84b1-7bb29db4a365.JPG)

**Comment by fafling** [comment]
Pendant l'écran noir, dans un 1er temps il n'y a pas d'affichage (toutes les couches sont désactivées dans l'écran debug du VDP2)., puis on voit la commande de dessin dans l'écran debug du VDP1 :
![Capture_contra_loading1](https://user-images.githubusercontent.com/7624262/58057181-45d45480-7b64-11e9-8c4e-7af71fb07cec.PNG)

Les infos du VDP2 à ce moment-là :

Border Color Mode = Back screen
Display Resolution = 320 x 224(NTSC)
Interlace Mode = Non-Interlace
Latches HV counter when external latch flag is read
H Counter = 0
V Counter = 242

Line Color Screen Stuff
-----------------------
Mode = Single color
Address = 05E00000

Back Screen Stuff
-----------------
Mode = Single color
Address = 05E3FFFE
Color Offset A Enabled
R = 0, G = 0, B = 0

Sprite Stuff
------------
Sprite Type = 3
VDP1 Framebuffer Data Format = RGB and palette
Sprite Window Enabled
Window disabled whole screen
Color RAM Offset = 0
Priority 0 = 6
Priority 1 = 5
Priority 2 = 5
Priority 3 = 5
Priority 4 = 5
Priority 5 = 5
Priority 6 = 5
Priority 7 = 5
Color Offset A Enabled
R = 0, G = 0, B = 0

Peu après, on voit toujours le commande de dessin dans l'écran debug du VDP1, mais la texture est corrompue :
![Capture_contra_loading2](https://user-images.githubusercontent.com/7624262/58057289-9ba8fc80-7b64-11e9-9a2e-28d1445a2fea.PNG)

**Comment by BenjaminSiskoo** [comment]
![contra](https://user-images.githubusercontent.com/12481242/71718695-52b86680-2e1c-11ea-9486-a2dab50f2bb4.PNG)

**Comment by BenjaminSiskoo** [comment]
Pareil avec Kronos du 26/03/2020 (commit VF Remix)

**Comment by BenjaminSiskoo** [comment]
Pareil avec Kronos du 03/04/2020

**Comment by fafling** [comment]
D'après Mednafen, pendant l'affichage de l'écran de transition :
- Les registres TVMR et FBCR sont à 0, le VDP1 est donc en one-cycle mode avec des framebuffers normal 16bpp.
- Le registre EWLR est à 0x00DF, donc [X1, Y1] vaut [0, 224].
- Le registre EWRR est à 0x02DF, donc [X3, Y3] vaut [7, 224].

Comme la résolution du VDP2 est 320 x 224, l'effacement de l'erase/write a donc lieu en-dehors de la zone visible.
L'écran de transition est certainement dessiné 2 fois successivement au départ pour qu'il soit présent sur les 2 framebuffers, qui alternent ensuite sans que ce qui a été dessiné soit effacé par l'erase/write.
Le dessin cesse après les 2 1ères fois, puisqu'on ne voit pas la texture corrompue à l'écran.

C'est donc un autre problème dû au non respect des coordonnées de l'erase/write, voir #1351, #1327 et #1072 .

**Comment by BenjaminSiskoo** [comment]
C'est un adieau j'espère :pEnfin ce bug est corrigé, pendant des années il m'a hanté ^^
