### ISSUE TITLE
[libretro] Output flickers in OpenGL renderer

### ISSUE THREAD

**Issue by Edojp** [FCare/Kronos#901]
Version is 2.1.2 95a6176

What's the full name of the game (including region) ?
Panzer Dragoon Saga/Azel (Japan)

What's your frontend ? (standalone, libretro, ...) ?
libretro (Retroarch 1.8.8)

What's your OS ? (windows, linux, OSX, ...) ?
Windows 10

What's your hardware ? (CPU, GPU, ...) ?
Intel 9700K, Geforce 2080 Ti (latest drivers)

What's the storage type of the game (official cd, burned cd or cd image) ?
cue/bin image

Are you using any setting different from default ? If so, precise
Have tried I believe every setting in core Options (including all OpenGL versions, internal resolution options etc.)

Did this game work previously ? Do you remember when ? Is it happening with other games ?
Not sure, first time I am trying Kronos

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this
Game runs fine but output in gameplay flickers heavily, like a strong interlacing shader is in use (confirmed shaders are disabled). Menus/static images are not affected. Retroarch log here:

[retroarch__2020_06_10__12_22_53.log](https://github.com/FCare/Kronos/files/4756059/retroarch__2020_06_10__12_22_53.log)

I tried compiling latest version from source but does not compile in Cygwin, libFLAC dependency fails:

libFLAC/stream_decoder.c:1258:26: error: ‘_O_BINARY’ undeclared (first use in this function); did you mean ‘O_BINARY’?

**Comment by Edojp** [comment]
Video of issue here:

https://www.youtube.com/watch?v=a_piqNLIMmg

**Comment by barbudreadmon** [comment]
Retroarch issue, dupe of https://github.com/libretro/RetroArch/issues/10486, at some point i fixed it but the fix was reverted. Use glcore video driver until retroarch devs fix that issue again. You can close this issue.

**Comment by Edojp** [comment]
Lovely, thank you.
