### ISSUE TITLE
[Grandia] Problème pendant les combats sur Grandia Saturn

### ISSUE THREAD

**Issue by tailter** [FCare/Kronos#903]
Bonjour,

J'ai des difficultés à faire apparaitre les sprites des combattants pendant une phase de combat, les ennemies ainsi que les personnages du joueur apparaissent sans textures.
Malgré les différentes modifications effectuées sur les paramètres vidéo, je n'ai pas réussi à corriger le problème.
![Capture](https://user-images.githubusercontent.com/67054719/84893935-56753800-b0a0-11ea-8e5c-a7011fdf5b7a.PNG)

**Comment by BenjaminSiskoo** [comment]
Hello pourrais tu ajouter une savestate aussi merci

**Comment by tailter** [comment]
Bonjour, 

Tu parles d'une sauvegarde d'état j'imagine ?
J'en ai fait une en plein combat je la transfert en format ZIP. 

Merci au faite tu fais un super boulot ! La Saturn est une machine incroyable.

[T-4507G_009.zip](https://github.com/FCare/Kronos/files/4798694/T-4507G_009.zip)

**Comment by BenjaminSiskoo** [comment]
Oui c'est ca, je suis pas le développeur, je beta test, prépare les builds, etc... Mais merci. François est pas mal occupé donc ca peut prendre du temps avant d'être corrigé. Merci pour ton retour :)

**Comment by tailter** [comment]
Bah merci à vous dans tous les cas. Pour info j'ai pas ce bug avec un autre émulateur (yabasanshiro dernière version). Donc je ne comprends pas. 
Bonne journée,

**Comment by BenjaminSiskoo** [comment]
C'est normal, Kronos est basé sur Yabause et Yaba Sanshiro. Mais depuis François a retravaillé le code pour qu'il soit plus proche de la machine.  Certains jeux passeront mieux sur Yaba tandis que d'autres passeront mieux sur Kronos.

**Comment by Starhowl** [comment]
Kronos 2.5.0 recently has been released; does the issue still persist?

**Comment by BenjaminSiskoo** [comment]
Fixed for the next release
