### ISSUE TITLE
[Virtual On - Cyber Troopers] Flickering in-game

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#904]
Original report from https://www.reddit.com/r/RetroArch/comments/hc87j7/saturnstv_kronos_flicker/

The issue started with https://github.com/FCare/Kronos/commit/dba1bf003701eef7cff4ef2742674a4fb3ee277f

It happens with any settings, on both libretro and standalone.

**Comment by BenjaminSiskoo** [comment]
It seems fixed.
