### ISSUE TITLE
[Bishoujo Hanafuda Kikou - Michinoku Hitou Koi Monogatari Special] Problème d'affichage.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#905]
Testé avec mednafen à gauche de la vidéo.

OpenGl et CS

Il semble qu'il a une sorte de problème avec la priorité des plans.

J'ai crée une vidéo.

https://youtu.be/IWA63Yy7LdA

**Comment by fafling** [comment]
Les effets d'ouverture/fondu au noir ont l'air inversés sur les écrans de l'intro est en jeu : l'affichage de Kronos est noir quand une image devrait être affichée, et une image apparaît dans Kronos quand elle devrait virer au noir.

Il peut y avoir un écran initial affichant que le jeu a besoin de plus de place que ce qui est disponible en mémoire interne (243 blocs), affiché noir par Kronos. Il faut appuyer sur un bouton pour le passer.

Les couches concernées par le problème activent le line color screen et la color calculation. Leur color calculation ratio reste constant à 31:1. Comme l'aspect graphique n'est pas celui d'un blending additif, ce sont probablement les ratios de la 2nd image qui sont utilisés.
@FCare est-ce que le registre CCRTMD du VDP2 est à 1 ?

Si c'est le cas, comme les couches qui posent problème sont en top image, c'est le color calculation ratio du line color screen qui est utilisé. En fait, ce ratio ne peut l'être que dans ce cas de figure, puisque le line color screen ne s'insère qu'en 2nd image. Vu le rendu graphique, je pense que Kronos utilise ce ratio à l'envers.

**Comment by BenjaminSiskoo** [comment]
Amélioration mais pas encore corrigé la WIP du 03/12/2020

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 16.12.2021

Problème toujours présent : 

Il manquait la savestate : 

[T-36701G_000.zip](https://github.com/FCare/Kronos/files/7726112/T-36701G_000.zip)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 18.01.2022
