### ISSUE TITLE
[Dark Seed II] Chute de FPS en CS...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#906]
Testé avec Kronos 2.1.2

OpenGl : pas de soucis avec les vidéos
CS : chute de FPS avec toutes les vidéos

**Comment by fafling** [comment]
Dark seed fait plusieurs listes de commandes VDP1 par frame. Selon le moment où on ouvre l'écran debug, la commande de dessin de la video n'est pas toujours là. Il semble qu'il lance en boucle une liste de dessin bidon tant qu'il n'a pas fini de décoder la frame de video.

**Comment by BenjaminSiskoo** [comment]
Problème toujours présent avec kronos 2.2.0 du 16.12.2021

Ajout de la savestate :  
[T-36101G_000.zip](https://github.com/FCare/Kronos/files/7726131/T-36101G_000.zip)

**Comment by fafling** [comment]
Temporairement résolu entre les WIP du 17/12 et du 31/12 en ne dessinant pas des listes de commandes consécutives identiques, mais provoque des clignotements dans des jeux Capcom #1291 car la détection peut considérer des listes identiques alors qu'elles ont juste des ressemblances.
Pour considérer 2 listes de commandes identiques, il faut tout comparer de A à Z : toutes les commandes, les tables liées (Gouraud et CLUT), et les textures associées. Un hash sur les commandes ne suffit pas.

**Comment by fafling** [comment]
De plus, même si la détection de listes consécutive était correcte, elle ne doit pas s'appliquer sur une liste utilisant les fonctions de semi-transparences RGB du VDP1 (half-transparency ou shadow), car il est possible de répéter une liste de commande pour obtenir des effets de blending cumulatifs.

**Comment by fafling** [comment]
De nouveau résolu depuis la WIP du 05/01/2022.
