### ISSUE TITLE
[Kunoichi Torimonochou (J)] Problème d'affichae VDP1...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#908]
Problème avec le VDP1 

![kunoichi](https://user-images.githubusercontent.com/12481242/89122914-931fb600-d4cb-11ea-8b92-84b3eec894bf.PNG)

Savestate : 

[kunoichi.zip](https://github.com/FCare/Kronos/files/5012151/kunoichi.zip)

**Comment by fafling** [comment]
Le problème est présent dans les 2 noyaux en v2.1.3 publique et dans la dernière WIP.
Il apparaît en 1.6.0 où la couleur de fond du framebuffer du VDP1 devient noire au lieu de transparente. Elle vire au mauve en v2.0.1.
Il n'y a pas de commande de dessin d'effacement sur le VDP1. Donc c'est l'effacement automatique de l'erase/write qui doit écrire cette couleur de fond (ou bien c'est fait par le CPU si les devs ont voulu se compliquer la vie).
@FCare Quelle est la valeur du registre EWDR du VDP1 sur cet écran ?

**Comment by fafling** [comment]
EWDR à 0x8000, framebuffer normal (donc 16 bits par pixel) sur le VDP1.
Type de sprite à F sur le VDP2, donc celui-ci s'attend à des pixels de sprites sur 8 bits.
Apparemment dans ce cas de figure, le VDP2 ne prend en compte que les 8 bits de poids faible de chaque pixels de 16 bits transmis par le VDP1. Comme ces 8 bits sont tous à 0, le VDP2 considère tous les pixels de sprites comme transparents.
