### ISSUE TITLE
[Waku^2 Monster] Freeze avec l'interpreteur SH2 Kronos...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#909]
Avec l'interpréteur SH2, pas de soucis.
Avec l’interpréteur SH2 Kronos, le jeu freeze sur le press start screen.

Save state : 

[waku^2.zip](https://github.com/FCare/Kronos/files/5014989/waku.2.zip)

**Comment by FCare** [comment]
Si on comment la mise en cache, ca passe. Il y a donc un write qqpart qui n'est pas notifié...

**Comment by BenjaminSiskoo** [comment]
Corrigé WIP du 03/12/2020
