### ISSUE TITLE
[Shining Force 3 Scénario 2] Affichage de l'eau incorrecte...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#912]
Kronos 2.1.3

réf mednaffen : 

![shiningforcemednffen](https://user-images.githubusercontent.com/12481242/91712218-99b35300-eb87-11ea-9caf-33ce50f2a7f7.PNG)

Kronos : 

![Capture](https://user-images.githubusercontent.com/12481242/91712237-a172f780-eb87-11ea-8e5c-5293e4fc2933.PNG)

Savestate : 

[GS-9188_000.zip](https://github.com/FCare/Kronos/files/5149861/GS-9188_000.zip)

**Comment by fafling** [comment]
Avec la WIP du 01/09, l'affichage est correct dans les 2 noyau. 👍 

Ici en noyau CS :
![image](https://user-images.githubusercontent.com/7624262/91942160-be7c0780-ecfa-11ea-933a-014918fa3e19.png)
