### ISSUE TITLE
[Black Matrix (Japan) (Rerelease)] Problème de timing... ?

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#914]
Kronos 2.1.3 : pas de soucis avec les dialogues.
Kronos 2.1.4 : les dialogues se chevauchent comme un problème de refresh.

Mode CS

![blackmatrix](https://user-images.githubusercontent.com/12481242/91979808-9aceb680-ed26-11ea-958e-b7644efb945f.PNG)

[blackmatrix.zip](https://github.com/FCare/Kronos/files/5162185/blackmatrix.zip)

**Comment by fafling** [comment]
Les fenêtres de dialogue sont dessinées en 2 moitiés par 2 normal sprites avec la même texture inversée horizontalement et verticalement pour la moitié droite de la fenêtre :
![image](https://user-images.githubusercontent.com/7624262/92042844-54f00d80-ed7b-11ea-9be1-534124bb1f40.png)

Le décalage entre les 2 moitiés est plus visible en plein écran. La moitié droite semble décalée vers le bas d'un pixel par rapport à la moitié gauche, et sa dernière ligne est tronquée.

**Comment by fafling** [comment]
Ce problème n'existe qu'en noyau CS.
Ce n'est pas un nouveau problème, il est présent en 2.1.3 publique, et apparaît dans la WIP du 23/03 qui fixait l'aileron de Sega rally en CS.
