### ISSUE TITLE
[Saturn Bomberman (Japan)] Freezes after Hudson logo

### ISSUE THREAD

**Issue by Edojp** [FCare/Kronos#918]
Version 2.1.3 71ca4ce on Retroarch 1.9.0

I tried both CS and regular OpenGL settings and both real/HLE bios but does not make a difference. The screen fades to black after the Hudson logo and never progresses (you do not heard the "Hudson!" voice, either)

Any ideas? Many thanks.

**Comment by barbudreadmon** [comment]
It works properly here, so i think the issue might be with your iso. Could you try with redump's iso ?

**Comment by Edojp** [comment]
Hrm it does work fine with Beetle but yes, I'll try redumping!

**Comment by barbudreadmon** [comment]
Worst case scenario, come to our [discord](https://discordapp.com/invite/c5q4EU2) and we'll look at your current iso together.

**Comment by Edojp** [comment]
So I redumped the CD to bin/cue and that fixed the freezing issue however now the BGM is missing! Opening FMV sounds OK, though.

Any ideas? Many thanks.

**Comment by Edojp** [comment]
Sorry I am an idiot I was loading it from the bin file instead of the cue file. All good now!
