### ISSUE TITLE
[Scorcher] Compteur manquant...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#920]
Kronos 2.1.4 

CS et OpenGL

Affichage sur Kronos : 
![scorcher3](https://user-images.githubusercontent.com/12481242/93069488-021d2c80-f67e-11ea-8709-0c5369007983.PNG)

Affichage sur Mednaffen : 

![scorcher](https://user-images.githubusercontent.com/12481242/93069476-fc274b80-f67d-11ea-8bb2-31dde369506f.PNG)

**Comment by fafling** [comment]
@BenjaminSiskoo Doublon de #698

**Comment by BenjaminSiskoo** [comment]
Ok je ferme
