### ISSUE TITLE
[Souris] Problème de focus...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#921]
J'ai testé la souris, il semble qu'elle ne soit pas focus dans la fenêtre de l'émulateur. Résultat elle n'est pas utilisable.

**Comment by BenjaminSiskoo** [comment]
Amélioration avec Kronos 2.2.0, on a le focus, mais le souris devrait être au milieu de l'écran mais elle est décalé au milieu et en haut de l'écran

**Comment by fafling** [comment]
Je viens de tester la souris pour la 1ère fois dans Atlantis (fr) : le mouvement latéral fonctionne bien, mais le mouvement vertical est effectivement bloqué vers le haut sauf temporairement quand on descend la souris. C'est comme si l'émulateur détectait un mouvement de la souris vers le haut en permanence.

**Comment by BenjaminSiskoo** [comment]
Corrigé en le 16 mars 2022
