### ISSUE TITLE
[Sentimental Graffiti - First Window] Différence de couleur entre VDP1 et VDP2

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#922]
Dans la WIP du 07/09 comme en v2.1.3 publique, dans les 2 noyaux, il y a un écart de couleur entre les côtés de l'image, affichés par le VDP1, et le centre affiché par le VDP2, visible dès les logos :
![kronos_is](https://user-images.githubusercontent.com/7624262/94083485-8cdef380-fe03-11ea-802d-58fb2f86bc14.png)

Le screenshot est fait en integer scaling pour que tous les pixels soient présents.
L'affichage des côtés est plus clair que le centre dans toute la suite du jeu qui affiche les menus et artworks avec le même principe.

Affichage correct dans Yabause 0.9.14 en ce qui concerne les couleurs (la résolution est incorrecte) :
![yabause](https://user-images.githubusercontent.com/7624262/94083788-52298b00-fe04-11ea-80ab-e32ea2c923dd.png)

Les côtés de l'image sont dessiné par des sprites RGB sur le VDP1 :
![image](https://user-images.githubusercontent.com/7624262/94083931-a2a0e880-fe04-11ea-8d28-bbbbbd23a11f.png)

Le centre est un bitmap RGB sur le VDP2 :
![image](https://user-images.githubusercontent.com/7624262/94083975-b9dfd600-fe04-11ea-9ec5-188739ad7071.png)

Le jeu est en haute résolution double entrelacée sur le VDP2 :
![image](https://user-images.githubusercontent.com/7624262/94084376-a3864a00-fe05-11ea-8d56-78f3171add69.png)

Le VDP1 utilise un framebuffer 16 bpp et fait donc l'objet d'un zoom x2 en largeur (mais pas en hauteur car il est aussi entrelacé).

Avec l'éditeur mémoire de Yabause, on voit que les 1ers pixels des textures du VDP1 et du VDP2 utilisent une couleur commune, F3BC en hexa, ce qui donne 224 232 224 en couleur RGB 888. Or cette couleur est affiché par Kronos avec les couleurs RGB 888 suivantes :
- Sur le VDP1 : 231 239 231
- Sur le VDP2 : 225 233 226
Les 2 sont trop claires, et celle du VDP1 l'est nettement plus.

Le problème apparaît sur la branche accurate VDP1 le 14/09/2019.

Testé avec le CD d'origine.

**Comment by fafling** [comment]
Détail de la conversion BGR 555 vers RGB 888 :
F3BC en hexa = 1 (msb) 11100 (bleu) 11101 (vert) 11100 (rouge) en binaire
Extension des couleurs de 5 à 8 bit par décalage de chaque canal de couleur de 3 bits vers la gauche :
Rouge 8 = 11100000 en binaire = 224 en décimal
Vert 8 = 11101000 en binaire = 232 en décimal
Bleu 8 = 11100000 en binaire = 224 en décimal

**Comment by FCare** [comment]
La conversion par decalage n'est pas exacte. Elle permet de calculer plus
vite dans un emulateur mais elle presente une erreur d'arrondi.
Par exemple: la couleur maximale sur 5 bits est 0x11111, ce qui correspond
à 31 doit correpondre au meme maximum 0x11111111 en 8 bits, soit 255.
La conversion exacte est donc x255/31. Sinon, les blancs en
RGB555 deviennent gris en RGB888.

donc on devrait avoir:
Rouge: 28*255/31 = 230
Vert: 29*255/31 = 238
Bleu: 28*255/31 = 230

**Comment by FCare** [comment]
Donc le VDP1 est correct (interpretation de l'arrondi).
Par contre le VDP2 utilise le decalage (a l'arrondi pret)

Il faut donc corriger le VDP2

**Comment by fafling** [comment]
La conversion des couleurs de 5 à 8 bits par décalage vers la gauche est ce que fait le VDP2 : voir p. 218 du mode d'emploi du VDP2.

Effectivement le BGR 555 de la Saturn donne des couleurs moins saturées une fois converties en RGB 888 par le VDP2. Chaque canal plafonne à 248. Le blanc BGR 555 est donc légèrement gris (mais sans avoir le blanc BGR 555 et le blanc BGR 888 côte à côte, ça ne se voit pas).

Sur Saturn, la saturation maximale d'un canal de couleur ne peut être obtenue qu'avec des couleurs BGR 888 natives, soit dans la color RAM, soit sur les couches du VDP2 qui supporte les pixels BGR 888.

**Comment by fafling** [comment]
En WIP du 28/09, dans les 2 noyaux, on a les couleurs RGB 888 suivantes :
- Sur le VDP1 : 225 233 225
- Sur le VDP2 : 225 233 226

L'écart entre les 2 n'est plus visible. Par contre, les couleurs sont très proches de la couleur correcte, 224 232 224, mais pas exactes.

**Comment by fafling** [comment]
Le problème était visible dans Casper où le sol est dessiné alternativement par le VDP1 et le VDP2. A cet endroit on peut le voir changer de luminosité dans la v2.1.3 publique quand Casper monte et descend, ce n'est plus le cas dans la WIP :
[casper_variation_luminosite_sol_2.1.3.zip](https://github.com/FCare/Kronos/files/5301466/casper_variation_luminosite_sol_2.1.3.zip)

**Comment by barbudreadmon** [comment]
> En WIP du 28/09, dans les 2 noyaux, on a les couleurs RGB 888 suivantes :
> 
> * Sur le VDP1 : 225 233 225
> * Sur le VDP2 : 225 233 226
> 
> L'écart entre les 2 n'est plus visible. Par contre, les couleurs sont très proches de la couleur correcte, 224 232 224, mais pas exactes.

Hmmmm, peut-être qu'avec un right shift de 8 plutôt qu'une division par 255.0, on serait plus proche de la couleur correcte ?

**Comment by fafling** [comment]
Avec un right shit de 8 sur une couleur 8 bits, il va pas rester grand chose.

Je suppose qu'à un moment donné, il y a forcément une multiplication du flottant obtenu par la division par 255.0 pour retrouver une couleur 8 bit. Ce serait pas multiplié par 256.0 au lieu de de 255.0 par hasard ?

**Comment by FCare** [comment]
C'est peut être l'arrondi et très certainement un calcul a base de 256 au
lieu de 255. Quitte à ne pas être précis, autant simplifier le hw...

**Comment by barbudreadmon** [comment]
> Avec un right shift de 8 sur une couleur 8 bits, il va pas rester grand chose.

Je pensais à la division par 255 dans https://github.com/FCare/Kronos/commit/2743fe30fc6778705d62dd5e7c078a6882a2954b
Mais effectivement l'idée du shift n'est pas bonne vu qu'on veut un float entre 0 et 1, dommage car les shift sont plus rapides que les divisions.

**Comment by FCare** [comment]
Le probleme vient de la stack openGL. En openGL, 255.0 correspond bien à 1.0. si on passe de 255 a 256, ca va degrader les perfs graphique en ajoutant une multiplication et une division par pixel. La saturn n'etant pas exacte, je prefere garder ce petit ecart.
