### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [kronos_libretro.dylib] Error 1

### ISSUE THREAD

**Issue by Ultimatron** [FCare/Kronos#928]
Hi, I'm simply trying to compile the Kronos libretro core on macOS, so I cloned the repo and followed the instructions, but the output ended with 
`../core/m68k/musashi/m68kcpu.c:41:10:` `fatal error: 'm68kops.h' file not found`
`#include "m68kops.h"`
`         ^~~~~~~~~~~`
`1 error generated.`
`make: *** [../core/m68k/musashi/m68kcpu.c.o] Error 1`

Any help?

**Comment by FCare** [comment]
MacOS build is not supported. No dev on Kronos have a MacOS.

It looks like the makefiles are broken for Mac...

Le lun. 12 oct. 2020 à 11:13, Ultimatron <notifications@github.com> a
écrit :

**Comment by FCare** [comment]
Did you followed the compilation command in the readme.md? the
generate-files is required to generate first m68k files.

For retroarch core: - mkdir build_retro; cd build_retro; - make -j4 -C
../yabause/src/libretro/ generate-files - make -j4 -C
../yabause/src/libretro/ - then execute retroarch -L
../yabause/src/libretro/kronos_libretro.so path_to_your_iso

**Comment by Ultimatron** [comment]
Hi, sorry for the late reply, after following the instructions and creating the m68k files, I tried running `make -j4 -C
../yabause/src/libretro/`, but I got an error: `clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [kronos_libretro.dylib] Error 1`

**Comment by barbudreadmon** [comment]
kronos requires opengl 4.2, macosx is limited to opengl 4.1, so there is no point in trying to run kronos on macosx

**Comment by Ultimatron** [comment]
I see. In that case, what is the best emulator for Sega Saturn on macOS? I know Yabause is an option, but the macOS port lacks many features. Or does Kronos support Vulkan? This may be a noobish question, but maybe it can be run with MoltenVK, like Dolphin? 
Thanks. 
I will close this issue soon.

**Comment by barbudreadmon** [comment]
No vulkan support yet, and moltenvk isn't fully compliant with vulkan anyway.
You can use yabause or mednafen/beetle saturn on macosx.

**Comment by Ultimatron** [comment]
Alright, thanks! I will close this issue. Thanks for your help!

**Comment by Ultimatron** [comment]
Sorry for bringing this back up again, but I've tested multiple Saturn emulators on macOS, and none of them seem to support upscaling, which was the main reason why I'm trying to get Kronos to work. So I've got just a few questions. What's wrong with the error? If compiled, can the core be run on Metal? Are there any other Saturn emulators out there that allow upscaling, or am I just doing something wrong? Thanks.

**Comment by barbudreadmon** [comment]
> can the core be run on Metal? Are there any other Saturn emulators out there that allow upscaling, or am I just doing something wrong?

No and no. Long story short : apple isn't interested in implementing cross-platform gfx api and expect us to use their shitty metal proprietary gfx api, tbh they can go fuck themselves. If apple fanboys want to keep being scammed by apple, that's not our problem.

**Comment by BenjaminSiskoo** [comment]
Hi, 

Windows, Linux and RA are supported for the moment. If some devs are interested to dev on differents devices (android, mac, switch,...), kronos is open source. If you know a mac dev, talk about this project...
