### ISSUE TITLE
[Jikkyou Oshaberi Parodius - Forever With Me] Fenêtre incorrecte pendant l'intro en OpenGL

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#932]
Dans la dernière WIP, et depuis celle du 07/05, en noyau OpenGL seulement, les sprites s'affichent assombris au lieu d'être invisibles en-dehors de la window W0 qui limite aussi les autres couches du VDP2 (voir #685) :
![image](https://user-images.githubusercontent.com/7624262/96057890-402e8b80-0e8a-11eb-8ed4-3d31f5d0c38d.png)

Affichage correct en noyau CS :
![image](https://user-images.githubusercontent.com/7624262/96057977-73711a80-0e8a-11eb-950a-f10a368ac477.png)

Testé avec le CD d'origine.

**Comment by FCare** [comment]
Meme cause que #916.
Apparu avec 32c3e9679fc753bccb2d5b8c1064665992989e69
