### ISSUE TITLE
[FIFA soccer 97] Invalid opcode au chargement d'un match et freeze

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#935]
En v2.1.3 publique et dans la dernière WIP, dans les 2 noyaux, il y a un slave invalid opcode lors du chargement au début d'un match pendant cet écran :
![image](https://user-images.githubusercontent.com/7624262/96521460-a001a980-1271-11eb-8442-5acea9e99198.png)

R0 =  0000000E R12 =  0608E1E8
R1 =  00000000 R13 =  00000001
R2 =  00000080 R14 =  21800000
R3 =  FFFFFE11 R15 =  06000FDC
R4 =  00000000 SR =   000000F1
R5 =  000000FC GBR =  00000000
R6 =  00000000 VBR =  06000400
R7 =  000000FD MACH = 00000000
R8 =  060E403D MACL = 00000000
R9 =  060ECAD8 PR =   0608C982
R10 = 00000005 PC =   0608C938
R11 = 00000017

De plus, Kronos freeze pendant ce chargement depuis la WIP du 02/09.

Testé avec le redump US.

**Comment by FCare** [comment]
Le freeze est reglé depuis 0af7c74edd28bcc4b088e62c627c3cbd58fe07aa

**Comment by fafling** [comment]
Je confirme que le freeze est fixé.
Pour info, le slave invalid opcode est toujours présent. Il n'a l'air de se produire que la première fois qu'on lance un match.
