### ISSUE TITLE
[Régression] Digital Pinball n'est plus jouable...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#940]
Le jeu fonctionne avec Kronos 2.0.2 mais pas avec la 2.1.1

Ecran noir après le premier écran de chargement alors que le jeu était jouable.

peut être à cause de ca :Saturn Emulation : SCU : improve interrupt handling mechanism (François Care).

**Comment by fafling** [comment]
Le blocage n'est pas présent dans la v2.0.2 publique du 03/02/2020 et apparaît dans la WIP du 04/02/2020.
Il concerne les 2 noyaux, pas d'affichage dans debugView, pas d'influence du nombre de manettes.
Les versions PAL (Digital pinball) et US (Last gladiators) ont le même problème.

**Comment by fafling** [comment]
Le framerate du VDP1 reste à 0 à partir du blocage.
L'émulateur continue de répondre, mais pas les boutons, y compris la combinaison A+B+C+start.

La liste de commandes du VDP1 est celle de l'affichage de la video d'intro qui commence à ce moment-là. Je ne vois rien de particulier dedans.

Le moment où le blocage se produit correspond à un changement de résolution du VDP2 : il passe de 640x480i à 320x224p. D'après la taille du system clipping, le VDP1 change aussi de type de framebuffer à ce moment-là, on passe d'un framebuffer hi res en double interlaced à un framebuffer normal progressif.

**Comment by BenjaminSiskoo** [comment]
Corrigé le 9.01.2023
