### ISSUE TITLE
[Régression] Rayman n'est plus jouable (CS)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#944]
Kronos WIp 01.11.2020 

CS mode 

![rayman](https://user-images.githubusercontent.com/12481242/97801647-8af82380-1c3e-11eb-8670-76ae82021351.PNG)

Savestate : 

[rayman.zip](https://github.com/FCare/Kronos/files/5470687/rayman.zip)

**Comment by fafling** [comment]
Le problème apparaît dans la WIP du 31/10 qui fixe Off-world

**Comment by FCare** [comment]
Due to 349f520f2feacd1069fc85cbe4ddef67ebb893c4

**Comment by fafling** [comment]
@FCare tu as déjà fixé le problème du reset des local coordinates.
En fait le bug se produit aléatoirement depuis la WIP du 02/09.
Je ne suis pas parvenu à déterminer une  séquence d'action qui le produit systématiquement ou pas.
Malgré de nombreux essais, je ne l'ai pas vu en version publique v2.1.3.

**Comment by FCare** [comment]
C'est ce que j'ai vu hier soir.
Si je rajoute un printf, ca se met à fonctionner...

**Comment by BenjaminSiskoo** [comment]
Corrigé avec la WIP du 03/12/2020
