### ISSUE TITLE
[Régression] Die Hard Arcade (E) problème de texture...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#948]
Kronos WIP 01.11.2020 commit f3ad1ae
Mode CS

Problème avec les textures sur la version européenne.

![diehardarcade](https://user-images.githubusercontent.com/12481242/97804332-635d8700-1c4f-11eb-9a4b-dc1884abe999.PNG)

Savestate :

[diehardarcade.zip](https://github.com/FCare/Kronos/files/5470926/diehardarcade.zip)

**Comment by fafling** [comment]
Se produit aussi en OpenGL.
Ne se produit que si on appuie sur start rapidement plusieurs fois jusqu'au début du jeu à partir du logo Fox (le logo Fox doit être interrompu, si le fondu au noir commence avant le lancement de la demo, l'interruption n'est plus possible).
Les versions US et jap n'ont pas ce problème.
Il apparaît dans la WIP du 06/12/2019 qui fixe la color ram par ligne pour les jeux Sonic Megadrive dans Sonic jam.

**Comment by BenjaminSiskoo** [comment]
Toujours présent WIp du 3/12/2020

**Comment by BenjaminSiskoo** [comment]
Corrigé le 9 01 2023. PAs testé en opengl mais peut ^tre que ca disparaitra
