### ISSUE TITLE
[Criticom] Manque les ombres sous les persos...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#949]
Kronos Wip du 01/11/2020

Mode CS

![criticom](https://user-images.githubusercontent.com/12481242/97804988-8e49da00-1c53-11eb-9f4b-b72a95233ee8.PNG)

Savestates

[criticom.zip](https://github.com/FCare/Kronos/files/5470989/criticom.zip)

**Comment by FCare** [comment]
Elles y sont bien si tu regardes de pres...
