### ISSUE TITLE
[Régression] Quake est cassé en CS..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#950]
Kronos Wip du 01/11/2020

![quake](https://user-images.githubusercontent.com/12481242/97805129-7cb50200-1c54-11eb-8805-f4bf059b20be.PNG)

**Comment by fafling** [comment]
Je ne reproduis pas le problème. C'est avec quelle version de Quake ?

**Comment by BenjaminSiskoo** [comment]
J'avais pas vu ton comment @fafling en tout cas ca mieux mais j'ai l'impression qu'il y a un soucis quand tu appuie sur start, il y a une bande pleine de quelques millimètre en bas de l'écran ? Normal ?

Testé en CS sans aucun amélioration vidéo

![quake](https://user-images.githubusercontent.com/12481242/100948308-e0f30c00-3507-11eb-9659-d610b931fae9.PNG)

**Comment by fafling** [comment]
Je n'ai pas la version PAL en CD pour vérifier sur la console., mais vu les commandes du VDP1, oui c'est normal. La zone de dessin est décalée vers le haut, alors qu'elle est centrée en version US.

**Comment by BenjaminSiskoo** [comment]
Ok je ferme merci :)
