### ISSUE TITLE
[Hat Trick] Vidéo intro cassé...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#954]
Kronos Wip du 10.11.2020

![hattrick](https://user-images.githubusercontent.com/12481242/98612077-a8d71f80-22f3-11eb-8b3b-289bb1c8de95.PNG)

Savestate : 

[hattrick.zip](https://github.com/FCare/Kronos/files/5514006/hattrick.zip)

**Comment by fafling** [comment]
Doublon de #235
