### ISSUE TITLE
[Powerslave] Régressions graphiques depuis le 02/09

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#955]
En WIP du 10/11 et depuis la WIP du 02/09, il y a 3 régressions graphiques dans Powerslave dans les 2 noyaux :

- Après avoir fait "New game" et choisi un slot de sauvegarde, en haut à gauche de la carte qui s'affiche ensuite, on voit passer régulièrement la liste des slots affichés à l'écran précédent par le VDP1. La liste de commande du VDP1 ne contient pas les sprites correspondants. La liste des slots clignote aussi brièvement pendant l'écran de loading qui suit la carte.
![image](https://user-images.githubusercontent.com/7624262/98853890-17ce8880-245a-11eb-89ae-aa35825c0560.png)
Save state pris à ce moment :
[Powerslave_clignotement_slots_sur_carte.zip](https://github.com/FCare/Kronos/files/5526180/Powerslave_clignotement_slots_sur_carte.zip)

- Dans le 1er niveau, les textures des murs et du sol comportent des pixels bleus, verts et transparents incorrects. Ces pixels sont visibles en bas à droite des textures dans l'écran debug du VDP1. En CS, ils apparaissent seulement sur les murs :
![image](https://user-images.githubusercontent.com/7624262/98854296-aa6f2780-245a-11eb-9ba5-26561cc8431a.png)
Save state :
[powerslave_pixels_incorrects_mur_CS.zip](https://github.com/FCare/Kronos/files/5526284/powerslave_pixels_incorrects_mur_CS.zip)
En OpenGL on les voit uniquement sur le sol :
![image](https://user-images.githubusercontent.com/7624262/98855135-d048fc00-245b-11eb-8a40-ff546f8b189d.png)
Save state :
[powerslave_pixels_incorrects_sol_OpenGL.zip](https://github.com/FCare/Kronos/files/5526241/powerslave_pixels_incorrects_sol_OpenGL.zip)

- Relancer le jeu et refaire "New game", choisir le slot utilisé la 1ère fois. En bas du dialogue qui demande si on veut écraser la sauvegarde, une partie de la liste des slots est visible alors qu'on ne la voit pas sur la console. Les commandes qui dessine ces sprites apparaissent à la fin de la liste de commandes du VDP1. On ne les voit pas en version publique.
![image](https://user-images.githubusercontent.com/7624262/98856509-ece63380-245d-11eb-91cc-cc2fdc9afc0c.png)
Save state :
[powerslave_new_game_overwrite.zip](https://github.com/FCare/Kronos/files/5526342/powerslave_new_game_overwrite.zip)

Testé avec le CD US.

**Comment by BenjaminSiskoo** [comment]
Kronos 14.01.2022
Mode Cs

Il semble que les points de la deuxième photo sur le premier post soit corrigé

**Comment by fafling** [comment]
Aucun de ces problèmes ne subsiste dans la dernière WIP.
