### ISSUE TITLE
[J. League Go Go Goal!] Ombres des joueurs incorrectes

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#957]
Dans la dernière WIP et en v2.1.3 publique, dans les 2 noyaux, l'ombre des joueurs est noir opaque au lieu d'être une trame noire :
![image](https://user-images.githubusercontent.com/7624262/99890883-23912a80-2c64-11eb-98f0-d9169ebe8bd4.png)

Affichage correct sur la console :
![image](https://user-images.githubusercontent.com/7624262/99890903-54715f80-2c64-11eb-9fe9-4b970b451d82.png)

![image](https://user-images.githubusercontent.com/7624262/99890927-a6b28080-2c64-11eb-84b1-4c7b5e233d91.png)
L'ombre est dessinée en mode MSB on, mesh activée et color calculation shadow. Kronos ne semble pas prendre en compte le mode mesh.
Par contre la couleur noire de l'ombre est correcte. La doc du VDP1 indique de ne pas utiliser la color calculation du VDP1 avec le mode MSB on (p. 97, "Do not specify color calculation (specify replace instead)"). Apparemment ça n'a pas d'impact sur le rendu visuel, qui correspond à l'effet du MSB on avec replace : le VDP1 bascule à 1 le MSB des pixels du framebuffer où il aurait dessiné un pixel opaque de la texture. Comme les pixels du framebuffer où l'ombre est dessinée sont transparents, puisqu'ils laissent voir le RBG0, passer leur MSB à 1 leur donne la valeur hexa 8000.
Comme le framebuffer est paramétré en RGB+palette sur le VDP2, celui-ci traite donc ces pixels comme du noir RGB.
![image](https://user-images.githubusercontent.com/7624262/99891180-820bd800-2c67-11eb-80a5-a899cdd646d0.png)

Save state :
[J_League_Go_Go_Goal_ombre_joueurs.zip](https://github.com/FCare/Kronos/files/5578718/J_League_Go_Go_Goal_ombre_joueurs.zip)

Testé avec le CD jap.

**Comment by BenjaminSiskoo** [comment]
Même problème Kronos 2.1.5 du 14.01.2021

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 même problème

**Comment by BenjaminSiskoo** [comment]
Corrigé le 13/12/2021

**Comment by fafling** [comment]
L'ombre est correcte en noyau CS, mais elle est toujours noire opaque en OpenGL.
Et dans les 2 noyaux, l'ombre est noire opaque en mesh mode improved au lieu d'être semi-transparente.
@BenjaminSiskoo Est-ce que tu peux rouvrir ?

**Comment by fafling** [comment]
Dans la dernière WIP du 15/12/2021, les ombres ne s'affichent plus en CS en mesh mode original.
![image](https://user-images.githubusercontent.com/7624262/146283678-caf61b7c-1f65-4ded-b594-852be9b5d0db.png)

Elles sont correctes en CS en mesh mode improved :
![image](https://user-images.githubusercontent.com/7624262/146283735-361dfee8-fb6d-44cf-96de-b9d5526f354b.png)

Elles sont incorrectes en OpenGL quel que soit le mesh mode car noires opaques :
![image](https://user-images.githubusercontent.com/7624262/146283950-ac91f2b0-7717-4c5f-be35-21c2530ef556.png)

**Comment by BenjaminSiskoo** [comment]
Doit être corrigé avec Kronos 2.2.0 du 16.12.2021

**Comment by fafling** [comment]
En WIP du 16/12, c'est correct en noyau CS dans les 2 mesh mode, par contre les ombres sont toujours noires opaques en OpenGL quel que soit le mesh mode.

**Comment by fafling** [comment]
Correct dans les 2 noyaux quel que soit le mesh mode. 👍

**Comment by fafling** [comment]
En WIP du 03/01, les ombres sont de nouveau noires opaques en OpenGL :
![image](https://user-images.githubusercontent.com/7624262/147993543-81f1b039-7d79-498c-ae82-e02fad5cc9a4.png)

La régression date de cette WIP, la précédente du 31/12 était correcte.
L'affichage reste correct en CS.
