### ISSUE TITLE
[ThunderForce 5] L'écran d'alerte sur le boss reste (NBG3 ?)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#959]
Kronos 2.14 Wip

Thunderforce 5

Mode CS / OpenGL

![thunderforce5](https://user-images.githubusercontent.com/12481242/100344399-0ac8a200-2fe1-11eb-83db-6e990a983b30.PNG)

Quand on arrive sur le premier boss, un message d'alerte s'affiche sur l'écran et devrait disparaitre quand on combat, mais il reste. En désactivant la couche NBG3, il disparait.

Savestate : 

[thunderfoce5.zip](https://github.com/FCare/Kronos/files/5602494/thunderfoce5.zip)

**Comment by fafling** [comment]
J'ai testé dans la WIP du 10/11, la seule façon dont je vois le problème c'est en chargeant le save state.
Sinon en partant du début du jeu, je ne suis pas arrivé à reproduire ce problème même en changeant différentes options (noyau, upscale, interpréteur, bios intégré ou réel).

**Comment by fafling** [comment]
![image](https://user-images.githubusercontent.com/7624262/100540890-8bd1a480-3240-11eb-827f-e28eca9395bd.png)
@BenjaminSiskoo Donc problème dû à une image disque incorrecte ?

**Comment by BenjaminSiskoo** [comment]
![thunderforce](https://user-images.githubusercontent.com/12481242/100541255-cfc5a900-3242-11eb-8874-386adb7dbe32.PNG)

C'est une image qui n'avait jamais posé de problème avant

**Comment by BenjaminSiskoo** [comment]
Image incorrecte, je ferme
