### ISSUE TITLE
Latest RA core has graphic problems with House of the Dead ( Europe ) 

### ISSUE THREAD

**Issue by BroKill** [FCare/Kronos#963]
What's the full name of the game (including region) ?
House of the Dead ( Europe )

What's your frontend ? (standalone, libretro, ...) ?
RetroArch

What's your OS ? (windows, linux, OSX, ...) ?
Windows 10 1803 x64

What's your hardware ? (CPU, GPU, ...) ?
i7 4790k, GTX 770 2 GB, 16 GB DDR3

What's the storage type of the game (official cd, burned cd or cd image) ?
CD image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)
Cue/Bin

Are you using any setting different from default ? If so, precise
No except BIOS language set to Italian

Did this game work previously ? Do you remember when ? Is it happening with other games ?
The game works ok with a previous build from April 2020

Hope you guys will fix it.

CHEERs

**Comment by barbudreadmon** [comment]
i just synced with standalone, it's ok now (i don't know when the new core will hit the libretro buildbot though)

**Comment by BroKill** [comment]
Thanks.

When it will be out I will close this.



EDIT

Got it, thanks!


CHEERs
