### ISSUE TITLE
[Mujintou Monogatari R] Freeze au début de la présentation des persos

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#965]
En WIP du 03/12, comme en v2.1.3 publique, dans les 2 noyaux, le jeu freeze dans la boucle de démo quand commence la présentation des persos juste après l'écran titre. L'IHM de Kronos continue de répondre.
![image](https://user-images.githubusercontent.com/7624262/102280280-23b3db80-3f2d-11eb-850e-e9bcfafc1d99.png)

Dans debugView, on voit 2 invalid opcode à ce moment-là :

Error: Master SH2 invalid opcode

R0 =  00000000 R12 =  05FA0F44
R1 =  0607B610 R13 =  060111BC
R2 =  00020000 R14 =  00001A38
R3 =  06000900 R15 =  06001EB8
R4 =  FFFFFFFE SR =   000000E0
R5 =  25FE00A0 GBR =  00000000
R6 =  0602854A VBR =  06000000
R7 =  0000697C MACH = FFFFFDE9
R8 =  373D395F MACL = 00000080
R9 =  00000000 PR =   06028608
R10 = 00000A28 PC =   00020006
R11 = 00001238

Error: Slave SH2 invalid opcode

R0 =  00000000 R12 =  FFFFFE11
R1 =  10A00000 R13 =  26072CD0
R2 =  00000001 R14 =  06000FDC
R3 =  00000080 R15 =  06000FDC
R4 =  0606AD20 SR =   000000F0
R5 =  2609CA30 GBR =  00000000
R6 =  00000000 VBR =  06000400
R7 =  2609CA4E MACH = 00000000
R8 =  06000FDE MACL = 00000000
R9 =  26050C00 PR =   06010DA8
R10 = 06000FDE PC =   10A00000
R11 = 2607B5D8

Le freeze et les invalid opcode apparaissent en WIP de la v1.7.0 du 13/04/2019. Ils ne se produisent ni en WIP du 17/03/2019, ni en v1.6.0 publique.

Save state juste avant le freeze :
[mujintou_monogatari_r_écran_titre.zip](https://github.com/FCare/Kronos/files/5699037/mujintou_monogatari_r_ecran_titre.zip)

Testé avec le CD d'origine.

**Comment by BenjaminSiskoo** [comment]
Même problème Kronos 2.1.5 du 14.01.2021

**Comment by BenjaminSiskoo** [comment]
Kronos 2.2.0 du 17.12.2021

savestate : 
[T-28901G_000.zip](https://github.com/FCare/Kronos/files/7736834/T-28901G_000.zip)

**Comment by BenjaminSiskoo** [comment]
Corrigé le 11.01.2023 : 
![image](https://user-images.githubusercontent.com/12481242/211781507-fea7c9b8-970f-444d-a1f8-bac6f18527ac.png)
