### ISSUE TITLE
mini18n libs directory

### ISSUE THREAD

**Issue by metafarion** [FCare/Kronos#972]
I've been working up a Gentoo ebuild for Kronos, and I happened on a limitation of the install parameters.  Currently, the compiled mini18n libraries are hardcoded to install to $CMAKE_INSTALL_PREFIX/lib which is problematic for 64-bit builds on multilib distros which prefer to use lib64 strictly for 64-bit libraries.  I was able to resolve this by editing the install targets in yabause/src/tools/mini18n/src/CMakeLists.txt, but I'm thinking there's probably a mechanism for cmake to detect the appropriate install directory on its own.

**Comment by metafarion** [comment]
I'm getting the impression the solution has something to do with this GNUInstallDirs module described here: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by BenjaminSiskoo** [comment]
Hello, @FCare is actually busy, You'll get an answer sooner I hope. Thanks for your report.

**Comment by FCare** [comment]
Hi, Kronos is using only the static version of the mini18n lib. So there is no need to install it on lib.
I will fix the CMakeList to not intall the shared lib version.

**Comment by FCare** [comment]
@metafarion Can you check if it is fixing your issue and close the ticket if it is the case?

**Comment by metafarion** [comment]
Yeah, this looks good; the default build doesn't produce any shared libs anymore.
