### ISSUE TITLE
[X-Men vs. Street Fighter] Décor manquant dans le niveau Manhattan

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#974]
En v2.1.5, dans les 2 noyaux, les véhicules de l'arrière-plan sont manquants dans ce niveau :
![image](https://user-images.githubusercontent.com/7624262/103479875-f42c1c80-4dd0-11eb-9b63-7caecc55729d.png)

Affichage correct sur la console :
![image](https://user-images.githubusercontent.com/7624262/103479897-11f98180-4dd1-11eb-8ac7-9a5adec88eb5.png)

Les véhicules sont visibles sur le NBG1 si on désactive les couches NBG0 et NBG3 :
![image](https://user-images.githubusercontent.com/7624262/103480191-2b033200-4dd3-11eb-8e3d-58a62dd59022.png)

Le NBG1 à une priorité de 2, et se trouve derrière les bâtiments affichés par les NBG0 (priorité 3) et NBG3 (priorité 4) :
![image](https://user-images.githubusercontent.com/7624262/103479966-921fe700-4dd1-11eb-8412-8d3f22aff3c8.png)

Le NBG1 affiche aussi les buildings qui se trouvent derrière les NBG0 et NBG3 ce qui correspond bien à sa priorité à 2. La special priority function n'est pas utilisée, il y a donc sans doute un changement de priorité du NBG1 en cours d'affichage pour lui faire afficher les véhicules devant les 2 autres couches (problème similaire au volant caché dans Need for speed #417 ).

Save state :
[X-Men_vs_Street_Fighter_Manhattan.zip](https://github.com/FCare/Kronos/files/5761647/X-Men_vs_Street_Fighter_Manhattan.zip)

Testé avec le CD jap.

**Comment by FCare** [comment]
NBG1 prio 4 (34)
NBG1 prio 2 (225)

**Comment by fafling** [comment]
Dans la dernière WIP dans les 2 noyaux, le NBG1 est entièrement devant les NBG0 et NBG3, les buildings en haut qui devraient être en grande partie cachés sont complètement visibles :
![image](https://user-images.githubusercontent.com/7624262/103596362-11aad480-4efe-11eb-825b-29ad1e8a0bda.png)

Affichage correct sur la console :
![image](https://user-images.githubusercontent.com/7624262/103596786-0015fc80-4eff-11eb-8fe6-b2bb68fcfc0c.png)

**Comment by fafling** [comment]
C'est fixé dans les 2 noyau dans la dernière WIP.
@FCare ton patch restreint la possibilité de changer la priorité en cours d'affichage sur les NBG (seulement pour les NBG0 et 1 quand ils ont le line scrolling activé). Sur la console, c'est possible sur tous les NBG, quelle que soit leur configuration.
