### ISSUE TITLE
[World Heroes Perfect] Personnage manquant in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#975]
Kronos du 5 Janvier 2021

Dans le débug VDP1 il n'y a pas d'info.

![worldheroesperfect](https://user-images.githubusercontent.com/12481242/103637955-89075500-4f4c-11eb-9189-bcf1a2eb7527.PNG)

Savestate :  
[worldheroesperfect.zip](https://github.com/FCare/Kronos/files/5769716/worldheroesperfect.zip)

**Comment by FCare** [comment]
duplicate #748
