### ISSUE TITLE
[Street racer extra] Le RBG0 disparaît derrière le RBG1

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#978]
Dans la dernière WIP, avec les 2 noyaux, les nuages du RBG0 disparaissent au niveau de la cime des arbres du 1er circuit, au lieu d'être visible jusqu'à passer derrière les montagnes.

Dans Kronos :
![image](https://user-images.githubusercontent.com/7624262/104534289-4dd3e880-5614-11eb-9ac4-7027d722348a.png)

Sur la console :
![image](https://user-images.githubusercontent.com/7624262/104534066-daca7200-5613-11eb-8e8b-72e6106e949c.png)

Ce problème apparaît en WIP du 05/01, avec le fix de la priorité par ligne sur le RBG0 (voir #417 ), cependant l'affichage n'était pas correct avant. Ici en v2.1.5 publique on voit les nuages rester devant les montagnes au lieu de passer derrière :
![image](https://user-images.githubusercontent.com/7624262/104534192-17966900-5614-11eb-9bb2-04b4aa6ec18e.png)

Les nuages sont affichés par le RBG0 avec une priorité de 5, alors que les montagnes sont sur le RBG1 avec une priorité de 4, sans utiliser la special priority :
![image](https://user-images.githubusercontent.com/7624262/104533139-182e0000-5612-11eb-8b38-e2e62c909b68.png)

Les nuages du RBG0 sont donc normalement devant les montagnes du RBG1 comme en version publique, or c'est le contraire sur la console.

C'est donc qu'il y a un changement de priorité pendant l'affichage au niveau de la cimes des arbres, qui fait passer le RBG0 sous le RBG1. Ce changement de priorité est maintenant émulé. Le problème dans Kronos est que le RBG1 est complètement opaque au RBG0, alors qu'on voit bien le dégradé du back screen dans ses zones transparentes. Si on désactive le RBG1, les nuages manquants réapparaissent sous la cime des arbres :
![image](https://user-images.githubusercontent.com/7624262/104534344-65ab6c80-5614-11eb-857d-40d65240c08e.png)

Save state :
[street_racer_1er_circuit.zip](https://github.com/FCare/Kronos/files/5811960/street_racer_1er_circuit.zip)

Testé avec le CD jap.

**Comment by FCare** [comment]
RBG0 Draw from 0 to 82 30
RBG0 CCTLL 51
RGB0 prio = 5
RBG0 Draw from 82 to 149 30
RBG0 CCTLL 51
RGB0 prio = 3
RBG0 Draw from 149 to 256 30
RBG0 CCTLL 50
RGB0 prio = 6
RBG1 Draw from 0 to 82 30
RGB1 prio = 4
RBG1 Draw from 82 to 149 30
RGB1 prio = 4

**Comment by FCare** [comment]
Fix with 66ca62f69c595a2f4a5b9860ca267d3d253add66

**Comment by fafling** [comment]
Pour info, pas de dégradation des perf dans Street racer en WIP par rapport à la version publique suite à ce patch.
Dans les 2 cas, je gagne 10-15 fps en activant le GPU RBG. 👍
