### ISSUE TITLE
[Earthworm Jim] Scintillements...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#982]
Kronos 2.1.5 du 13.01.2021

Mode OpenGL et CS

Il y a des scintillements sur les sprites sur l'écran suivant et dans le jeu : 

![earthwormjim2](https://user-images.githubusercontent.com/12481242/104581442-e3946580-565e-11eb-84d8-8651ec0dcca8.PNG)

**Comment by fafling** [comment]
Les sprites clignotent comme s'il apparaissaient un frame sur 2.
Problème présent en version 2.1.5 publique, apparaît en WIP du 28/10.
Ne touche que la version PAL du jeu, les versions US et jap n'ont pas de souci.

**Comment by FCare** [comment]
Coupable a7341b0d8d636b7aa89a1c299f09adebd5f36567

Le jeu doit reutiliser des command list

**Comment by BenjaminSiskoo** [comment]
Corrigé le 14.012021

**Comment by fafling** [comment]
De retour de puis la WIP du 20/09/2021 en même temps que le fix de la régression sur Burning rangers. Un bug chasse l'autre...
@BenjaminSiskoo Est-ce que tu peux rouvrir ?

**Comment by FCare** [comment]
commit en cause: 
dd292d09d8af5e67035c01aa4af2ce269ec5e109

**Comment by FCare** [comment]
Ok, il y avait un probleme dans la gestion de commandes invalides et une mauvaise implementation du registre ENDR. Du coup, Burning rangers et reglé maintenant et Earthworm jim ne clignote plus

**Comment by fafling** [comment]
Effectivement ça ne clignotement plus, mais gros problème de perf sur Burning rangers #1134
