### ISSUE TITLE
[Régression] Avec les commits du 14 Janvier 2021

### ISSUE THREAD

**Issue by BenjaminSiskoo** [FCare/Kronos#987]
Suite au 3 commits du 14 Janvier, il y a plusieurs régressions

NBA Live 98 (l'écran freeze sur la vidéo d'intro), Darklight conflict, Virtual Hydlide (dans le menu des objets, scintillements), Metal Slug (corruption de sprite)" 

https://github.com/FCare/Kronos/commit/13e1a02ae92df9b4ad9db22a22bd69402a6d98af

**Comment by fafling** [comment]
666ef14 fixe aussi le freeze de la video de NBA live 98.

**Comment by fafling** [comment]
Les corruptions de sprites dans Metal slug apparaissent avec la WIP du 14/01 qui fixe les clignotements de sprites dans Earthworm Jim PAL.
Save state (pour reproduire la corruption, faire avancer le personnage vers la gauche contre le bord de l'écran) :
[metal_slug_corruption sprite.zip](https://github.com/FCare/Kronos/files/5999217/metal_slug_corruption.sprite.zip)

**Comment by fafling** [comment]
666ef14 fixe aussi le freeze de Darklight conflict.

**Comment by fafling** [comment]
Comme pour Metal slug, les clignotement dans l'inventaire de Virtual Hydlide apparaissent avec la WIP du 14/01 qui fixe les clignotements de sprites dans Earthworm Jim PAL.
Save state (version US) :
[Virtual_hydlide_clignotement_inventaire.zip](https://github.com/FCare/Kronos/files/5999309/Virtual_hydlide_clignotement_inventaire.zip)

**Comment by BenjaminSiskoo** [comment]
Régression trop ancienne.
