### ISSUE TITLE
[Ponut64 demo] Tremblements de la caméra

### ISSUE THREAD

**Issue by fafling** [FCare/Kronos#990]
Dans la dernière WIP et depuis celle du 14/01 sur les modifs du FRT, il y a des tremblements cycliques sur l'angle de la caméra dans la demo soumise par Ponut64 pour la compétition du 26ème anniversaire de la Saturn ([https://segaxtreme.net/threads/sega-saturn-26th-anniversary-game-competition.24626/post-179060](https://segaxtreme.net/threads/sega-saturn-26th-anniversary-game-competition.24626/post-179060)).

Le problème se produit dans les 2 noyaux.

Un zip de la démo :
[ponut64_compo_26.zip](https://github.com/FCare/Kronos/files/5953944/ponut64_compo_26.zip)

**Comment by FCare** [comment]
Fixed with 666ef149666dd8358dd03a345c93e66342880b42
